package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AqCourseSearchId generated by hbm2java
 */
@Embeddable
public class AqCourseSearchId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int sistockItemId;
	private int csCourseId;
	private int csCourseTypeId;
	private short soStoreId;
	private int cccostCenterId;
	private String simodelNameTx;
	private int ststockTypeId;
	private String stcategoryNameTx;
	private String simodelNumberTx;
	private String sidescriptionTxN;
	private BigDecimal siunitCostMn;
	private BigDecimal siregularPriceMn;
	private BigDecimal sieolpriceMn;
	private String siimageUrltxN;
	private String siimageUrl2txN;
	private String siimageUrl3txN;
	private String sispecialOfferTxN;
	private int simanufacturerId;
	private int sichildrenCountIn;
	private int sistockLevelIn;
	private boolean simaintainStockLevelBl;
	private String sivideoUrltxN;
	private String suManufacturerNameTx;
	private boolean zlDisplayOnWebBl;
	private boolean siserialRequiredBl;
	private Short sieventDataTypeIdN;
	private Integer siprimaryColorIdN;
	private Integer sisecondaryColorIdN;
	private Integer sisizeIdN;
	private Double siweightFlN;
	private boolean sishowPriceInEolbl;
	private float sitaxRateFl;
	private boolean sicalcTaxOnShippingAddressBl;
	private Integer siparentIdN;
	private int siclickActionId;
	private String siclickActionParamsTxN;
	private String siclickActionPromptTxN;
	private String siclickUrlTextTxN;
	private Date csStartDate;
	private Date csEndDate;
	private int lcLocationId;
	private String lcAddress3txN;
	private String lcAddress2txN;
	private String lcAddress1txN;
	private String lcAddress4txN;
	private Integer seStateId;
	private String seStateTx;
	private String seShortNameTx;
	private Integer ctcertPriorityInN;
	private Integer csTermIdN;

	public AqCourseSearchId() {
	}

	public AqCourseSearchId(int sistockItemId, int csCourseId, int csCourseTypeId, short soStoreId, int cccostCenterId,
			String simodelNameTx, int ststockTypeId, String stcategoryNameTx, String simodelNumberTx,
			BigDecimal siunitCostMn, BigDecimal siregularPriceMn, BigDecimal sieolpriceMn, int simanufacturerId,
			int sichildrenCountIn, int sistockLevelIn, boolean simaintainStockLevelBl,
			String suManufacturerNameTx, boolean zlDisplayOnWebBl, boolean siserialRequiredBl,
			boolean sishowPriceInEolbl, float sitaxRateFl, boolean sicalcTaxOnShippingAddressBl, int siclickActionId,
			Date csStartDate, Date csEndDate, int lcLocationId) {
		this.sistockItemId = sistockItemId;
		this.csCourseId = csCourseId;
		this.csCourseTypeId = csCourseTypeId;
		this.soStoreId = soStoreId;
		this.cccostCenterId = cccostCenterId;
		this.simodelNameTx = simodelNameTx;
		this.ststockTypeId = ststockTypeId;
		this.stcategoryNameTx = stcategoryNameTx;
		this.simodelNumberTx = simodelNumberTx;
		this.siunitCostMn = siunitCostMn;
		this.siregularPriceMn = siregularPriceMn;
		this.sieolpriceMn = sieolpriceMn;
		this.simanufacturerId = simanufacturerId;
		this.sichildrenCountIn = sichildrenCountIn;
		this.sistockLevelIn = sistockLevelIn;
		this.simaintainStockLevelBl = simaintainStockLevelBl;
		this.suManufacturerNameTx = suManufacturerNameTx;
		this.zlDisplayOnWebBl = zlDisplayOnWebBl;
		this.siserialRequiredBl = siserialRequiredBl;
		this.sishowPriceInEolbl = sishowPriceInEolbl;
		this.sitaxRateFl = sitaxRateFl;
		this.sicalcTaxOnShippingAddressBl = sicalcTaxOnShippingAddressBl;
		this.siclickActionId = siclickActionId;
		this.csStartDate = csStartDate;
		this.csEndDate = csEndDate;
		this.lcLocationId = lcLocationId;
	}

	public AqCourseSearchId(int sistockItemId, int csCourseId, int csCourseTypeId, short soStoreId, int cccostCenterId,
			String simodelNameTx, int ststockTypeId, String stcategoryNameTx, String simodelNumberTx,
			String sidescriptionTxN, BigDecimal siunitCostMn, BigDecimal siregularPriceMn,
			BigDecimal sieolpriceMn, String siimageUrltxN, String siimageUrl2txN,
			String siimageUrl3txN, String sispecialOfferTxN, int simanufacturerId, int sichildrenCountIn,
			int sistockLevelIn, boolean simaintainStockLevelBl, String sivideoUrltxN,
			String suManufacturerNameTx, boolean zlDisplayOnWebBl, boolean siserialRequiredBl,
			Short sieventDataTypeIdN, Integer siprimaryColorIdN, Integer sisecondaryColorIdN, Integer sisizeIdN,
			Double siweightFlN, boolean sishowPriceInEolbl, float sitaxRateFl, boolean sicalcTaxOnShippingAddressBl,
			Integer siparentIdN, int siclickActionId, String siclickActionParamsTxN,
			String siclickActionPromptTxN, String siclickUrlTextTxN, Date csStartDate, Date csEndDate,
			int lcLocationId, String lcAddress3txN, String lcAddress2txN, String lcAddress1txN,
			String lcAddress4txN, Integer seStateId, String seStateTx, String seShortNameTx,
			Integer ctcertPriorityInN, Integer csTermIdN) {
		this.sistockItemId = sistockItemId;
		this.csCourseId = csCourseId;
		this.csCourseTypeId = csCourseTypeId;
		this.soStoreId = soStoreId;
		this.cccostCenterId = cccostCenterId;
		this.simodelNameTx = simodelNameTx;
		this.ststockTypeId = ststockTypeId;
		this.stcategoryNameTx = stcategoryNameTx;
		this.simodelNumberTx = simodelNumberTx;
		this.sidescriptionTxN = sidescriptionTxN;
		this.siunitCostMn = siunitCostMn;
		this.siregularPriceMn = siregularPriceMn;
		this.sieolpriceMn = sieolpriceMn;
		this.siimageUrltxN = siimageUrltxN;
		this.siimageUrl2txN = siimageUrl2txN;
		this.siimageUrl3txN = siimageUrl3txN;
		this.sispecialOfferTxN = sispecialOfferTxN;
		this.simanufacturerId = simanufacturerId;
		this.sichildrenCountIn = sichildrenCountIn;
		this.sistockLevelIn = sistockLevelIn;
		this.simaintainStockLevelBl = simaintainStockLevelBl;
		this.sivideoUrltxN = sivideoUrltxN;
		this.suManufacturerNameTx = suManufacturerNameTx;
		this.zlDisplayOnWebBl = zlDisplayOnWebBl;
		this.siserialRequiredBl = siserialRequiredBl;
		this.sieventDataTypeIdN = sieventDataTypeIdN;
		this.siprimaryColorIdN = siprimaryColorIdN;
		this.sisecondaryColorIdN = sisecondaryColorIdN;
		this.sisizeIdN = sisizeIdN;
		this.siweightFlN = siweightFlN;
		this.sishowPriceInEolbl = sishowPriceInEolbl;
		this.sitaxRateFl = sitaxRateFl;
		this.sicalcTaxOnShippingAddressBl = sicalcTaxOnShippingAddressBl;
		this.siparentIdN = siparentIdN;
		this.siclickActionId = siclickActionId;
		this.siclickActionParamsTxN = siclickActionParamsTxN;
		this.siclickActionPromptTxN = siclickActionPromptTxN;
		this.siclickUrlTextTxN = siclickUrlTextTxN;
		this.csStartDate = csStartDate;
		this.csEndDate = csEndDate;
		this.lcLocationId = lcLocationId;
		this.lcAddress3txN = lcAddress3txN;
		this.lcAddress2txN = lcAddress2txN;
		this.lcAddress1txN = lcAddress1txN;
		this.lcAddress4txN = lcAddress4txN;
		this.seStateId = seStateId;
		this.seStateTx = seStateTx;
		this.seShortNameTx = seShortNameTx;
		this.ctcertPriorityInN = ctcertPriorityInN;
		this.csTermIdN = csTermIdN;
	}

	@Column(name = "SIStockItemID", nullable = false)
	public int getSistockItemId() {
		return this.sistockItemId;
	}

	public void setSistockItemId(int sistockItemId) {
		this.sistockItemId = sistockItemId;
	}

	@Column(name = "CsCourseID", nullable = false)
	public int getCsCourseId() {
		return this.csCourseId;
	}

	public void setCsCourseId(int csCourseId) {
		this.csCourseId = csCourseId;
	}

	@Column(name = "CsCourseTypeId", nullable = false)
	public int getCsCourseTypeId() {
		return this.csCourseTypeId;
	}

	public void setCsCourseTypeId(int csCourseTypeId) {
		this.csCourseTypeId = csCourseTypeId;
	}

	@Column(name = "SoStoreId", nullable = false)
	public short getSoStoreId() {
		return this.soStoreId;
	}

	public void setSoStoreId(short soStoreId) {
		this.soStoreId = soStoreId;
	}

	@Column(name = "CCCostCenterID", nullable = false)
	public int getCccostCenterId() {
		return this.cccostCenterId;
	}

	public void setCccostCenterId(int cccostCenterId) {
		this.cccostCenterId = cccostCenterId;
	}

	@Column(name = "SIModelNameTx", nullable = false)
	public String getSimodelNameTx() {
		return this.simodelNameTx;
	}

	public void setSimodelNameTx(String simodelNameTx) {
		this.simodelNameTx = simodelNameTx;
	}

	@Column(name = "STStockTypeID", nullable = false)
	public int getStstockTypeId() {
		return this.ststockTypeId;
	}

	public void setStstockTypeId(int ststockTypeId) {
		this.ststockTypeId = ststockTypeId;
	}

	@Column(name = "STCategoryNameTx", nullable = false)
	public String getStcategoryNameTx() {
		return this.stcategoryNameTx;
	}

	public void setStcategoryNameTx(String stcategoryNameTx) {
		this.stcategoryNameTx = stcategoryNameTx;
	}

	@Column(name = "SIModelNumberTx", nullable = false)
	public String getSimodelNumberTx() {
		return this.simodelNumberTx;
	}

	public void setSimodelNumberTx(String simodelNumberTx) {
		this.simodelNumberTx = simodelNumberTx;
	}

	@Column(name = "SIDescriptionTx_N")
	public String getSidescriptionTxN() {
		return this.sidescriptionTxN;
	}

	public void setSidescriptionTxN(String sidescriptionTxN) {
		this.sidescriptionTxN = sidescriptionTxN;
	}

	@Column(name = "SIUnitCostMn", nullable = false, scale = 4)
	public BigDecimal getSiunitCostMn() {
		return this.siunitCostMn;
	}

	public void setSiunitCostMn(BigDecimal siunitCostMn) {
		this.siunitCostMn = siunitCostMn;
	}

	@Column(name = "SIRegularPriceMn", nullable = false, scale = 4)
	public BigDecimal getSiregularPriceMn() {
		return this.siregularPriceMn;
	}

	public void setSiregularPriceMn(BigDecimal siregularPriceMn) {
		this.siregularPriceMn = siregularPriceMn;
	}

	@Column(name = "SIEOLPriceMn", nullable = false, scale = 4)
	public BigDecimal getSieolpriceMn() {
		return this.sieolpriceMn;
	}

	public void setSieolpriceMn(BigDecimal sieolpriceMn) {
		this.sieolpriceMn = sieolpriceMn;
	}

	@Column(name = "SIImageURLTx_N")
	public String getSiimageUrltxN() {
		return this.siimageUrltxN;
	}

	public void setSiimageUrltxN(String siimageUrltxN) {
		this.siimageUrltxN = siimageUrltxN;
	}

	@Column(name = "SIImageURL2Tx_N")
	public String getSiimageUrl2txN() {
		return this.siimageUrl2txN;
	}

	public void setSiimageUrl2txN(String siimageUrl2txN) {
		this.siimageUrl2txN = siimageUrl2txN;
	}

	@Column(name = "SIImageURL3Tx_N")
	public String getSiimageUrl3txN() {
		return this.siimageUrl3txN;
	}

	public void setSiimageUrl3txN(String siimageUrl3txN) {
		this.siimageUrl3txN = siimageUrl3txN;
	}

	@Column(name = "SISpecialOfferTx_N")
	public String getSispecialOfferTxN() {
		return this.sispecialOfferTxN;
	}

	public void setSispecialOfferTxN(String sispecialOfferTxN) {
		this.sispecialOfferTxN = sispecialOfferTxN;
	}

	@Column(name = "SIManufacturerID", nullable = false)
	public int getSimanufacturerId() {
		return this.simanufacturerId;
	}

	public void setSimanufacturerId(int simanufacturerId) {
		this.simanufacturerId = simanufacturerId;
	}

	@Column(name = "SIChildrenCountIn", nullable = false)
	public int getSichildrenCountIn() {
		return this.sichildrenCountIn;
	}

	public void setSichildrenCountIn(int sichildrenCountIn) {
		this.sichildrenCountIn = sichildrenCountIn;
	}

	@Column(name = "SIStockLevelIn", nullable = false)
	public int getSistockLevelIn() {
		return this.sistockLevelIn;
	}

	public void setSistockLevelIn(int sistockLevelIn) {
		this.sistockLevelIn = sistockLevelIn;
	}

	@Column(name = "SIMaintainStockLevelBl", nullable = false)
	public boolean isSimaintainStockLevelBl() {
		return this.simaintainStockLevelBl;
	}

	public void setSimaintainStockLevelBl(boolean simaintainStockLevelBl) {
		this.simaintainStockLevelBl = simaintainStockLevelBl;
	}

	@Column(name = "SIVideoURLTx_N")
	public String getSivideoUrltxN() {
		return this.sivideoUrltxN;
	}

	public void setSivideoUrltxN(String sivideoUrltxN) {
		this.sivideoUrltxN = sivideoUrltxN;
	}

	@Column(name = "SuManufacturerNameTx", nullable = false)
	public String getSuManufacturerNameTx() {
		return this.suManufacturerNameTx;
	}

	public void setSuManufacturerNameTx(String suManufacturerNameTx) {
		this.suManufacturerNameTx = suManufacturerNameTx;
	}

	@Column(name = "ZlDisplayOnWebBl", nullable = false)
	public boolean isZlDisplayOnWebBl() {
		return this.zlDisplayOnWebBl;
	}

	public void setZlDisplayOnWebBl(boolean zlDisplayOnWebBl) {
		this.zlDisplayOnWebBl = zlDisplayOnWebBl;
	}

	@Column(name = "SISerialRequiredBl", nullable = false)
	public boolean isSiserialRequiredBl() {
		return this.siserialRequiredBl;
	}

	public void setSiserialRequiredBl(boolean siserialRequiredBl) {
		this.siserialRequiredBl = siserialRequiredBl;
	}

	@Column(name = "SIEventDataTypeID_N")
	public Short getSieventDataTypeIdN() {
		return this.sieventDataTypeIdN;
	}

	public void setSieventDataTypeIdN(Short sieventDataTypeIdN) {
		this.sieventDataTypeIdN = sieventDataTypeIdN;
	}

	@Column(name = "SIPrimaryColorID_N")
	public Integer getSiprimaryColorIdN() {
		return this.siprimaryColorIdN;
	}

	public void setSiprimaryColorIdN(Integer siprimaryColorIdN) {
		this.siprimaryColorIdN = siprimaryColorIdN;
	}

	@Column(name = "SISecondaryColorID_N")
	public Integer getSisecondaryColorIdN() {
		return this.sisecondaryColorIdN;
	}

	public void setSisecondaryColorIdN(Integer sisecondaryColorIdN) {
		this.sisecondaryColorIdN = sisecondaryColorIdN;
	}

	@Column(name = "SISizeID_N")
	public Integer getSisizeIdN() {
		return this.sisizeIdN;
	}

	public void setSisizeIdN(Integer sisizeIdN) {
		this.sisizeIdN = sisizeIdN;
	}

	@Column(name = "SIWeightFl_N", precision = 53, scale = 0)
	public Double getSiweightFlN() {
		return this.siweightFlN;
	}

	public void setSiweightFlN(Double siweightFlN) {
		this.siweightFlN = siweightFlN;
	}

	@Column(name = "SIShowPriceInEOLBl", nullable = false)
	public boolean isSishowPriceInEolbl() {
		return this.sishowPriceInEolbl;
	}

	public void setSishowPriceInEolbl(boolean sishowPriceInEolbl) {
		this.sishowPriceInEolbl = sishowPriceInEolbl;
	}

	@Column(name = "SITaxRateFl", nullable = false, precision = 24, scale = 0)
	public float getSitaxRateFl() {
		return this.sitaxRateFl;
	}

	public void setSitaxRateFl(float sitaxRateFl) {
		this.sitaxRateFl = sitaxRateFl;
	}

	@Column(name = "SICalcTaxOnShippingAddressBl", nullable = false)
	public boolean isSicalcTaxOnShippingAddressBl() {
		return this.sicalcTaxOnShippingAddressBl;
	}

	public void setSicalcTaxOnShippingAddressBl(boolean sicalcTaxOnShippingAddressBl) {
		this.sicalcTaxOnShippingAddressBl = sicalcTaxOnShippingAddressBl;
	}

	@Column(name = "SIParentID_N")
	public Integer getSiparentIdN() {
		return this.siparentIdN;
	}

	public void setSiparentIdN(Integer siparentIdN) {
		this.siparentIdN = siparentIdN;
	}

	@Column(name = "SIClickActionID", nullable = false)
	public int getSiclickActionId() {
		return this.siclickActionId;
	}

	public void setSiclickActionId(int siclickActionId) {
		this.siclickActionId = siclickActionId;
	}

	@Column(name = "SIClickActionParamsTx_N")
	public String getSiclickActionParamsTxN() {
		return this.siclickActionParamsTxN;
	}

	public void setSiclickActionParamsTxN(String siclickActionParamsTxN) {
		this.siclickActionParamsTxN = siclickActionParamsTxN;
	}

	@Column(name = "SIClickActionPromptTx_N")
	public String getSiclickActionPromptTxN() {
		return this.siclickActionPromptTxN;
	}

	public void setSiclickActionPromptTxN(String siclickActionPromptTxN) {
		this.siclickActionPromptTxN = siclickActionPromptTxN;
	}

	@Column(name = "SIClickUrlTextTx_N")
	public String getSiclickUrlTextTxN() {
		return this.siclickUrlTextTxN;
	}

	public void setSiclickUrlTextTxN(String siclickUrlTextTxN) {
		this.siclickUrlTextTxN = siclickUrlTextTxN;
	}

	@Column(name = "CsStartDate", nullable = false, length = 23)
	public Date getCsStartDate() {
		return this.csStartDate;
	}

	public void setCsStartDate(Date csStartDate) {
		this.csStartDate = csStartDate;
	}

	@Column(name = "CsEndDate", nullable = false, length = 23)
	public Date getCsEndDate() {
		return this.csEndDate;
	}

	public void setCsEndDate(Date csEndDate) {
		this.csEndDate = csEndDate;
	}

	@Column(name = "LcLocationId", nullable = false)
	public int getLcLocationId() {
		return this.lcLocationId;
	}

	public void setLcLocationId(int lcLocationId) {
		this.lcLocationId = lcLocationId;
	}

	@Column(name = "LcAddress3Tx_N")
	public String getLcAddress3txN() {
		return this.lcAddress3txN;
	}

	public void setLcAddress3txN(String lcAddress3txN) {
		this.lcAddress3txN = lcAddress3txN;
	}

	@Column(name = "LcAddress2Tx_N")
	public String getLcAddress2txN() {
		return this.lcAddress2txN;
	}

	public void setLcAddress2txN(String lcAddress2txN) {
		this.lcAddress2txN = lcAddress2txN;
	}

	@Column(name = "LcAddress1Tx_N")
	public String getLcAddress1txN() {
		return this.lcAddress1txN;
	}

	public void setLcAddress1txN(String lcAddress1txN) {
		this.lcAddress1txN = lcAddress1txN;
	}

	@Column(name = "LcAddress4Tx_N")
	public String getLcAddress4txN() {
		return this.lcAddress4txN;
	}

	public void setLcAddress4txN(String lcAddress4txN) {
		this.lcAddress4txN = lcAddress4txN;
	}

	@Column(name = "SeStateID")
	public Integer getSeStateId() {
		return this.seStateId;
	}

	public void setSeStateId(Integer seStateId) {
		this.seStateId = seStateId;
	}

	@Column(name = "SeStateTx")
	public String getSeStateTx() {
		return this.seStateTx;
	}

	public void setSeStateTx(String seStateTx) {
		this.seStateTx = seStateTx;
	}

	@Column(name = "SeShortNameTx")
	public String getSeShortNameTx() {
		return this.seShortNameTx;
	}

	public void setSeShortNameTx(String seShortNameTx) {
		this.seShortNameTx = seShortNameTx;
	}

	@Column(name = "CTCertPriorityIn_N")
	public Integer getCtcertPriorityInN() {
		return this.ctcertPriorityInN;
	}

	public void setCtcertPriorityInN(Integer ctcertPriorityInN) {
		this.ctcertPriorityInN = ctcertPriorityInN;
	}

	@Column(name = "CsTermId_N")
	public Integer getCsTermIdN() {
		return this.csTermIdN;
	}

	public void setCsTermIdN(Integer csTermIdN) {
		this.csTermIdN = csTermIdN;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AqCourseSearchId))
			return false;
		AqCourseSearchId castOther = (AqCourseSearchId) other;

		return (this.getSistockItemId() == castOther.getSistockItemId())
				&& (this.getCsCourseId() == castOther.getCsCourseId())
				&& (this.getCsCourseTypeId() == castOther.getCsCourseTypeId())
				&& (this.getSoStoreId() == castOther.getSoStoreId())
				&& (this.getCccostCenterId() == castOther.getCccostCenterId())
				&& ((this.getSimodelNameTx() == castOther.getSimodelNameTx())
						|| (this.getSimodelNameTx() != null && castOther.getSimodelNameTx() != null
								&& this.getSimodelNameTx().equals(castOther.getSimodelNameTx())))
				&& (this.getStstockTypeId() == castOther.getStstockTypeId())
				&& ((this.getStcategoryNameTx() == castOther.getStcategoryNameTx())
						|| (this.getStcategoryNameTx() != null && castOther.getStcategoryNameTx() != null
								&& this.getStcategoryNameTx().equals(castOther.getStcategoryNameTx())))
				&& ((this.getSimodelNumberTx() == castOther.getSimodelNumberTx())
						|| (this.getSimodelNumberTx() != null && castOther.getSimodelNumberTx() != null
								&& this.getSimodelNumberTx().equals(castOther.getSimodelNumberTx())))
				&& ((this.getSidescriptionTxN() == castOther.getSidescriptionTxN())
						|| (this.getSidescriptionTxN() != null && castOther.getSidescriptionTxN() != null
								&& this.getSidescriptionTxN().equals(castOther.getSidescriptionTxN())))
				&& ((this.getSiunitCostMn() == castOther.getSiunitCostMn())
						|| (this.getSiunitCostMn() != null && castOther.getSiunitCostMn() != null
								&& this.getSiunitCostMn().equals(castOther.getSiunitCostMn())))
				&& ((this.getSiregularPriceMn() == castOther.getSiregularPriceMn())
						|| (this.getSiregularPriceMn() != null && castOther.getSiregularPriceMn() != null
								&& this.getSiregularPriceMn().equals(castOther.getSiregularPriceMn())))
				&& ((this.getSieolpriceMn() == castOther.getSieolpriceMn())
						|| (this.getSieolpriceMn() != null && castOther.getSieolpriceMn() != null
								&& this.getSieolpriceMn().equals(castOther.getSieolpriceMn())))
				&& ((this.getSiimageUrltxN() == castOther.getSiimageUrltxN())
						|| (this.getSiimageUrltxN() != null && castOther.getSiimageUrltxN() != null
								&& this.getSiimageUrltxN().equals(castOther.getSiimageUrltxN())))
				&& ((this.getSiimageUrl2txN() == castOther.getSiimageUrl2txN())
						|| (this.getSiimageUrl2txN() != null && castOther.getSiimageUrl2txN() != null
								&& this.getSiimageUrl2txN().equals(castOther.getSiimageUrl2txN())))
				&& ((this.getSiimageUrl3txN() == castOther.getSiimageUrl3txN())
						|| (this.getSiimageUrl3txN() != null && castOther.getSiimageUrl3txN() != null
								&& this.getSiimageUrl3txN().equals(castOther.getSiimageUrl3txN())))
				&& ((this.getSispecialOfferTxN() == castOther.getSispecialOfferTxN())
						|| (this.getSispecialOfferTxN() != null && castOther.getSispecialOfferTxN() != null
								&& this.getSispecialOfferTxN().equals(castOther.getSispecialOfferTxN())))
				&& (this.getSimanufacturerId() == castOther.getSimanufacturerId())
				&& (this.getSichildrenCountIn() == castOther.getSichildrenCountIn())
				&& (this.getSistockLevelIn() == castOther.getSistockLevelIn())
				&& (this.isSimaintainStockLevelBl() == castOther.isSimaintainStockLevelBl())
				&& ((this.getSivideoUrltxN() == castOther.getSivideoUrltxN())
						|| (this.getSivideoUrltxN() != null && castOther.getSivideoUrltxN() != null
								&& this.getSivideoUrltxN().equals(castOther.getSivideoUrltxN())))
				&& ((this.getSuManufacturerNameTx() == castOther.getSuManufacturerNameTx())
						|| (this.getSuManufacturerNameTx() != null && castOther.getSuManufacturerNameTx() != null
								&& this.getSuManufacturerNameTx().equals(castOther.getSuManufacturerNameTx())))
				&& (this.isZlDisplayOnWebBl() == castOther.isZlDisplayOnWebBl())
				&& (this.isSiserialRequiredBl() == castOther.isSiserialRequiredBl())
				&& ((this.getSieventDataTypeIdN() == castOther.getSieventDataTypeIdN())
						|| (this.getSieventDataTypeIdN() != null && castOther.getSieventDataTypeIdN() != null
								&& this.getSieventDataTypeIdN().equals(castOther.getSieventDataTypeIdN())))
				&& ((this.getSiprimaryColorIdN() == castOther.getSiprimaryColorIdN())
						|| (this.getSiprimaryColorIdN() != null && castOther.getSiprimaryColorIdN() != null
								&& this.getSiprimaryColorIdN().equals(castOther.getSiprimaryColorIdN())))
				&& ((this.getSisecondaryColorIdN() == castOther.getSisecondaryColorIdN())
						|| (this.getSisecondaryColorIdN() != null && castOther.getSisecondaryColorIdN() != null
								&& this.getSisecondaryColorIdN().equals(castOther.getSisecondaryColorIdN())))
				&& ((this.getSisizeIdN() == castOther.getSisizeIdN()) || (this.getSisizeIdN() != null
						&& castOther.getSisizeIdN() != null && this.getSisizeIdN().equals(castOther.getSisizeIdN())))
				&& ((this.getSiweightFlN() == castOther.getSiweightFlN())
						|| (this.getSiweightFlN() != null && castOther.getSiweightFlN() != null
								&& this.getSiweightFlN().equals(castOther.getSiweightFlN())))
				&& (this.isSishowPriceInEolbl() == castOther.isSishowPriceInEolbl())
				&& (this.getSitaxRateFl() == castOther.getSitaxRateFl())
				&& (this.isSicalcTaxOnShippingAddressBl() == castOther.isSicalcTaxOnShippingAddressBl())
				&& ((this.getSiparentIdN() == castOther.getSiparentIdN())
						|| (this.getSiparentIdN() != null && castOther.getSiparentIdN() != null
								&& this.getSiparentIdN().equals(castOther.getSiparentIdN())))
				&& (this.getSiclickActionId() == castOther.getSiclickActionId())
				&& ((this.getSiclickActionParamsTxN() == castOther.getSiclickActionParamsTxN())
						|| (this.getSiclickActionParamsTxN() != null && castOther.getSiclickActionParamsTxN() != null
								&& this.getSiclickActionParamsTxN().equals(castOther.getSiclickActionParamsTxN())))
				&& ((this.getSiclickActionPromptTxN() == castOther.getSiclickActionPromptTxN())
						|| (this.getSiclickActionPromptTxN() != null && castOther.getSiclickActionPromptTxN() != null
								&& this.getSiclickActionPromptTxN().equals(castOther.getSiclickActionPromptTxN())))
				&& ((this.getSiclickUrlTextTxN() == castOther.getSiclickUrlTextTxN())
						|| (this.getSiclickUrlTextTxN() != null && castOther.getSiclickUrlTextTxN() != null
								&& this.getSiclickUrlTextTxN().equals(castOther.getSiclickUrlTextTxN())))
				&& ((this.getCsStartDate() == castOther.getCsStartDate())
						|| (this.getCsStartDate() != null && castOther.getCsStartDate() != null
								&& this.getCsStartDate().equals(castOther.getCsStartDate())))
				&& ((this.getCsEndDate() == castOther.getCsEndDate()) || (this.getCsEndDate() != null
						&& castOther.getCsEndDate() != null && this.getCsEndDate().equals(castOther.getCsEndDate())))
				&& (this.getLcLocationId() == castOther.getLcLocationId())
				&& ((this.getLcAddress3txN() == castOther.getLcAddress3txN())
						|| (this.getLcAddress3txN() != null && castOther.getLcAddress3txN() != null
								&& this.getLcAddress3txN().equals(castOther.getLcAddress3txN())))
				&& ((this.getLcAddress2txN() == castOther.getLcAddress2txN())
						|| (this.getLcAddress2txN() != null && castOther.getLcAddress2txN() != null
								&& this.getLcAddress2txN().equals(castOther.getLcAddress2txN())))
				&& ((this.getLcAddress1txN() == castOther.getLcAddress1txN())
						|| (this.getLcAddress1txN() != null && castOther.getLcAddress1txN() != null
								&& this.getLcAddress1txN().equals(castOther.getLcAddress1txN())))
				&& ((this.getLcAddress4txN() == castOther.getLcAddress4txN())
						|| (this.getLcAddress4txN() != null && castOther.getLcAddress4txN() != null
								&& this.getLcAddress4txN().equals(castOther.getLcAddress4txN())))
				&& ((this.getSeStateId() == castOther.getSeStateId()) || (this.getSeStateId() != null
						&& castOther.getSeStateId() != null && this.getSeStateId().equals(castOther.getSeStateId())))
				&& ((this.getSeStateTx() == castOther.getSeStateTx()) || (this.getSeStateTx() != null
						&& castOther.getSeStateTx() != null && this.getSeStateTx().equals(castOther.getSeStateTx())))
				&& ((this.getSeShortNameTx() == castOther.getSeShortNameTx())
						|| (this.getSeShortNameTx() != null && castOther.getSeShortNameTx() != null
								&& this.getSeShortNameTx().equals(castOther.getSeShortNameTx())))
				&& ((this.getCtcertPriorityInN() == castOther.getCtcertPriorityInN())
						|| (this.getCtcertPriorityInN() != null && castOther.getCtcertPriorityInN() != null
								&& this.getCtcertPriorityInN().equals(castOther.getCtcertPriorityInN())))
				&& ((this.getCsTermIdN() == castOther.getCsTermIdN()) || (this.getCsTermIdN() != null
						&& castOther.getCsTermIdN() != null && this.getCsTermIdN().equals(castOther.getCsTermIdN())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSistockItemId();
		result = 37 * result + this.getCsCourseId();
		result = 37 * result + this.getCsCourseTypeId();
		result = 37 * result + this.getSoStoreId();
		result = 37 * result + this.getCccostCenterId();
		result = 37 * result + (getSimodelNameTx() == null ? 0 : this.getSimodelNameTx().hashCode());
		result = 37 * result + this.getStstockTypeId();
		result = 37 * result + (getStcategoryNameTx() == null ? 0 : this.getStcategoryNameTx().hashCode());
		result = 37 * result + (getSimodelNumberTx() == null ? 0 : this.getSimodelNumberTx().hashCode());
		result = 37 * result + (getSidescriptionTxN() == null ? 0 : this.getSidescriptionTxN().hashCode());
		result = 37 * result + (getSiunitCostMn() == null ? 0 : this.getSiunitCostMn().hashCode());
		result = 37 * result + (getSiregularPriceMn() == null ? 0 : this.getSiregularPriceMn().hashCode());
		result = 37 * result + (getSieolpriceMn() == null ? 0 : this.getSieolpriceMn().hashCode());
		result = 37 * result + (getSiimageUrltxN() == null ? 0 : this.getSiimageUrltxN().hashCode());
		result = 37 * result + (getSiimageUrl2txN() == null ? 0 : this.getSiimageUrl2txN().hashCode());
		result = 37 * result + (getSiimageUrl3txN() == null ? 0 : this.getSiimageUrl3txN().hashCode());
		result = 37 * result + (getSispecialOfferTxN() == null ? 0 : this.getSispecialOfferTxN().hashCode());
		result = 37 * result + this.getSimanufacturerId();
		result = 37 * result + this.getSichildrenCountIn();
		result = 37 * result + this.getSistockLevelIn();
		result = 37 * result + (this.isSimaintainStockLevelBl() ? 1 : 0);
		result = 37 * result + (getSivideoUrltxN() == null ? 0 : this.getSivideoUrltxN().hashCode());
		result = 37 * result + (getSuManufacturerNameTx() == null ? 0 : this.getSuManufacturerNameTx().hashCode());
		result = 37 * result + (this.isZlDisplayOnWebBl() ? 1 : 0);
		result = 37 * result + (this.isSiserialRequiredBl() ? 1 : 0);
		result = 37 * result + (getSieventDataTypeIdN() == null ? 0 : this.getSieventDataTypeIdN().hashCode());
		result = 37 * result + (getSiprimaryColorIdN() == null ? 0 : this.getSiprimaryColorIdN().hashCode());
		result = 37 * result + (getSisecondaryColorIdN() == null ? 0 : this.getSisecondaryColorIdN().hashCode());
		result = 37 * result + (getSisizeIdN() == null ? 0 : this.getSisizeIdN().hashCode());
		result = 37 * result + (getSiweightFlN() == null ? 0 : this.getSiweightFlN().hashCode());
		result = 37 * result + (this.isSishowPriceInEolbl() ? 1 : 0);
		result = 37 * result + (int) this.getSitaxRateFl();
		result = 37 * result + (this.isSicalcTaxOnShippingAddressBl() ? 1 : 0);
		result = 37 * result + (getSiparentIdN() == null ? 0 : this.getSiparentIdN().hashCode());
		result = 37 * result + this.getSiclickActionId();
		result = 37 * result + (getSiclickActionParamsTxN() == null ? 0 : this.getSiclickActionParamsTxN().hashCode());
		result = 37 * result + (getSiclickActionPromptTxN() == null ? 0 : this.getSiclickActionPromptTxN().hashCode());
		result = 37 * result + (getSiclickUrlTextTxN() == null ? 0 : this.getSiclickUrlTextTxN().hashCode());
		result = 37 * result + (getCsStartDate() == null ? 0 : this.getCsStartDate().hashCode());
		result = 37 * result + (getCsEndDate() == null ? 0 : this.getCsEndDate().hashCode());
		result = 37 * result + this.getLcLocationId();
		result = 37 * result + (getLcAddress3txN() == null ? 0 : this.getLcAddress3txN().hashCode());
		result = 37 * result + (getLcAddress2txN() == null ? 0 : this.getLcAddress2txN().hashCode());
		result = 37 * result + (getLcAddress1txN() == null ? 0 : this.getLcAddress1txN().hashCode());
		result = 37 * result + (getLcAddress4txN() == null ? 0 : this.getLcAddress4txN().hashCode());
		result = 37 * result + (getSeStateId() == null ? 0 : this.getSeStateId().hashCode());
		result = 37 * result + (getSeStateTx() == null ? 0 : this.getSeStateTx().hashCode());
		result = 37 * result + (getSeShortNameTx() == null ? 0 : this.getSeShortNameTx().hashCode());
		result = 37 * result + (getCtcertPriorityInN() == null ? 0 : this.getCtcertPriorityInN().hashCode());
		result = 37 * result + (getCsTermIdN() == null ? 0 : this.getCsTermIdN().hashCode());
		return result;
	}

}
