package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AqEmpModuleView generated by hbm2java
 */
@Entity
@Table(name = "aq_EmpModuleView")
public class AqEmpModuleView implements java.io.Serializable {

	private AqEmpModuleViewId id;

	public AqEmpModuleView() {
	}

	public AqEmpModuleView(AqEmpModuleViewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "moModuleId", column = @Column(name = "MoModuleID")),
			@AttributeOverride(name = "csCourseId", column = @Column(name = "CsCourseID")),
			@AttributeOverride(name = "moModuleTypeId", column = @Column(name = "MoModuleTypeID")),
			@AttributeOverride(name = "moStartDateN", column = @Column(name = "MoStartDate_N", length = 23)),
			@AttributeOverride(name = "moEndDateN", column = @Column(name = "MoEndDate_N", length = 23)),
			@AttributeOverride(name = "mtModuleNameTx", column = @Column(name = "MtModuleNameTx", nullable = false)),
			@AttributeOverride(name = "lcLocationNameTx", column = @Column(name = "LcLocationNameTx")),
			@AttributeOverride(name = "lcLocationId", column = @Column(name = "LcLocationId")),
			@AttributeOverride(name = "emEmpId", column = @Column(name = "EmEmpId", nullable = false)),
			@AttributeOverride(name = "edNotesTxN", column = @Column(name = "EdNotesTx_N")) })
	public AqEmpModuleViewId getId() {
		return this.id;
	}

	public void setId(AqEmpModuleViewId id) {
		this.id = id;
	}

}
