package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AspnetSchemaVersions generated by hbm2java
 */
@Entity
@Table(name = "Aspnet_SchemaVersions")
public class AspnetSchemaVersions implements java.io.Serializable {

	private AspnetSchemaVersionsId id;
	private boolean isCurrentVersion;

	public AspnetSchemaVersions() {
	}

	public AspnetSchemaVersions(AspnetSchemaVersionsId id, boolean isCurrentVersion) {
		this.id = id;
		this.isCurrentVersion = isCurrentVersion;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "feature", column = @Column(name = "Feature", nullable = false)),
			@AttributeOverride(name = "compatibleSchemaVersion", column = @Column(name = "CompatibleSchemaVersion", nullable = false)) })
	public AspnetSchemaVersionsId getId() {
		return this.id;
	}

	public void setId(AspnetSchemaVersionsId id) {
		this.id = id;
	}

	@Column(name = "IsCurrentVersion", nullable = false)
	public boolean isIsCurrentVersion() {
		return this.isCurrentVersion;
	}

	public void setIsCurrentVersion(boolean isCurrentVersion) {
		this.isCurrentVersion = isCurrentVersion;
	}

}
