package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CmrcShoppingCart generated by hbm2java
 */
@Entity
@Table(name = "CMRC_ShoppingCart")
public class CmrcShoppingCart implements java.io.Serializable {

	private int recordId;
	private TCuCust TCuCust;
	private int quantity;
	private int productId;
	private Integer categoryId;
	private String selectedColor;
	private String selectedSize;
	private Date selectedDate;
	private Date dateCreated;
	private Double retailPrice;
	private Integer selectedCourseId;
	private Integer selectedTripId;
	private String certNotes;
	private String specialArrangements;
	private Boolean waiverSigned;
	private Boolean pickUpRequired;
	private Integer pickUpVanId;
	private String pickUpLocation;
	private Date pickUpDateTime;
	private Double installmentPrice;
	private Double installmentTax;
	private Boolean isDiver;
	private Integer selectedCustomerId;
	private Integer discountBandId;
	private String priceNotes;
	private Double costPriceAtos;
	private Date expirationDate;
	private boolean isExpirationDateAbsolute;
	private Integer packageParentRecordId;
	private short storeId;

	public CmrcShoppingCart() {
	}

	public CmrcShoppingCart(int recordId, TCuCust TCuCust, int quantity, int productId, Date dateCreated,
			boolean isExpirationDateAbsolute, short storeId) {
		this.recordId = recordId;
		this.TCuCust = TCuCust;
		this.quantity = quantity;
		this.productId = productId;
		this.dateCreated = dateCreated;
		this.isExpirationDateAbsolute = isExpirationDateAbsolute;
		this.storeId = storeId;
	}

	public CmrcShoppingCart(int recordId, TCuCust TCuCust, int quantity, int productId, Integer categoryId,
			String selectedColor, String selectedSize, Date selectedDate, Date dateCreated, Double retailPrice,
			Integer selectedCourseId, Integer selectedTripId, String certNotes, String specialArrangements,
			Boolean waiverSigned, Boolean pickUpRequired, Integer pickUpVanId, String pickUpLocation,
			Date pickUpDateTime, Double installmentPrice, Double installmentTax, Boolean isDiver,
			Integer selectedCustomerId, Integer discountBandId, String priceNotes, Double costPriceAtos,
			Date expirationDate, boolean isExpirationDateAbsolute, Integer packageParentRecordId, short storeId) {
		this.recordId = recordId;
		this.TCuCust = TCuCust;
		this.quantity = quantity;
		this.productId = productId;
		this.categoryId = categoryId;
		this.selectedColor = selectedColor;
		this.selectedSize = selectedSize;
		this.selectedDate = selectedDate;
		this.dateCreated = dateCreated;
		this.retailPrice = retailPrice;
		this.selectedCourseId = selectedCourseId;
		this.selectedTripId = selectedTripId;
		this.certNotes = certNotes;
		this.specialArrangements = specialArrangements;
		this.waiverSigned = waiverSigned;
		this.pickUpRequired = pickUpRequired;
		this.pickUpVanId = pickUpVanId;
		this.pickUpLocation = pickUpLocation;
		this.pickUpDateTime = pickUpDateTime;
		this.installmentPrice = installmentPrice;
		this.installmentTax = installmentTax;
		this.isDiver = isDiver;
		this.selectedCustomerId = selectedCustomerId;
		this.discountBandId = discountBandId;
		this.priceNotes = priceNotes;
		this.costPriceAtos = costPriceAtos;
		this.expirationDate = expirationDate;
		this.isExpirationDateAbsolute = isExpirationDateAbsolute;
		this.packageParentRecordId = packageParentRecordId;
		this.storeId = storeId;
	}

	@Id

	@Column(name = "RecordID", unique = true, nullable = false)
	public int getRecordId() {
		return this.recordId;
	}

	public void setRecordId(int recordId) {
		this.recordId = recordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerID", nullable = false)
	public TCuCust getTCuCust() {
		return this.TCuCust;
	}

	public void setTCuCust(TCuCust TCuCust) {
		this.TCuCust = TCuCust;
	}

	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "ProductID", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "CategoryID")
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "SelectedColor", length = 50)
	public String getSelectedColor() {
		return this.selectedColor;
	}

	public void setSelectedColor(String selectedColor) {
		this.selectedColor = selectedColor;
	}

	@Column(name = "SelectedSize", length = 50)
	public String getSelectedSize() {
		return this.selectedSize;
	}

	public void setSelectedSize(String selectedSize) {
		this.selectedSize = selectedSize;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SelectedDate", length = 23)
	public Date getSelectedDate() {
		return this.selectedDate;
	}

	public void setSelectedDate(Date selectedDate) {
		this.selectedDate = selectedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreated", nullable = false, length = 23)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "RetailPrice", precision = 53, scale = 0)
	public Double getRetailPrice() {
		return this.retailPrice;
	}

	public void setRetailPrice(Double retailPrice) {
		this.retailPrice = retailPrice;
	}

	@Column(name = "SelectedCourseID")
	public Integer getSelectedCourseId() {
		return this.selectedCourseId;
	}

	public void setSelectedCourseId(Integer selectedCourseId) {
		this.selectedCourseId = selectedCourseId;
	}

	@Column(name = "SelectedTripID")
	public Integer getSelectedTripId() {
		return this.selectedTripId;
	}

	public void setSelectedTripId(Integer selectedTripId) {
		this.selectedTripId = selectedTripId;
	}

	@Column(name = "CertNotes")
	public String getCertNotes() {
		return this.certNotes;
	}

	public void setCertNotes(String certNotes) {
		this.certNotes = certNotes;
	}

	@Column(name = "SpecialArrangements")
	public String getSpecialArrangements() {
		return this.specialArrangements;
	}

	public void setSpecialArrangements(String specialArrangements) {
		this.specialArrangements = specialArrangements;
	}

	@Column(name = "WaiverSigned")
	public Boolean getWaiverSigned() {
		return this.waiverSigned;
	}

	public void setWaiverSigned(Boolean waiverSigned) {
		this.waiverSigned = waiverSigned;
	}

	@Column(name = "PickUpRequired")
	public Boolean getPickUpRequired() {
		return this.pickUpRequired;
	}

	public void setPickUpRequired(Boolean pickUpRequired) {
		this.pickUpRequired = pickUpRequired;
	}

	@Column(name = "PickUpVanID")
	public Integer getPickUpVanId() {
		return this.pickUpVanId;
	}

	public void setPickUpVanId(Integer pickUpVanId) {
		this.pickUpVanId = pickUpVanId;
	}

	@Column(name = "PickUpLocation")
	public String getPickUpLocation() {
		return this.pickUpLocation;
	}

	public void setPickUpLocation(String pickUpLocation) {
		this.pickUpLocation = pickUpLocation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PickUpDateTime", length = 23)
	public Date getPickUpDateTime() {
		return this.pickUpDateTime;
	}

	public void setPickUpDateTime(Date pickUpDateTime) {
		this.pickUpDateTime = pickUpDateTime;
	}

	@Column(name = "InstallmentPrice", precision = 53, scale = 0)
	public Double getInstallmentPrice() {
		return this.installmentPrice;
	}

	public void setInstallmentPrice(Double installmentPrice) {
		this.installmentPrice = installmentPrice;
	}

	@Column(name = "InstallmentTax", precision = 53, scale = 0)
	public Double getInstallmentTax() {
		return this.installmentTax;
	}

	public void setInstallmentTax(Double installmentTax) {
		this.installmentTax = installmentTax;
	}

	@Column(name = "IsDiver")
	public Boolean getIsDiver() {
		return this.isDiver;
	}

	public void setIsDiver(Boolean isDiver) {
		this.isDiver = isDiver;
	}

	@Column(name = "SelectedCustomerID")
	public Integer getSelectedCustomerId() {
		return this.selectedCustomerId;
	}

	public void setSelectedCustomerId(Integer selectedCustomerId) {
		this.selectedCustomerId = selectedCustomerId;
	}

	@Column(name = "DiscountBandId")
	public Integer getDiscountBandId() {
		return this.discountBandId;
	}

	public void setDiscountBandId(Integer discountBandId) {
		this.discountBandId = discountBandId;
	}

	@Column(name = "PriceNotes")
	public String getPriceNotes() {
		return this.priceNotes;
	}

	public void setPriceNotes(String priceNotes) {
		this.priceNotes = priceNotes;
	}

	@Column(name = "CostPriceATOS", precision = 53, scale = 0)
	public Double getCostPriceAtos() {
		return this.costPriceAtos;
	}

	public void setCostPriceAtos(Double costPriceAtos) {
		this.costPriceAtos = costPriceAtos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ExpirationDate", length = 23)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	@Column(name = "IsExpirationDateAbsolute", nullable = false)
	public boolean isIsExpirationDateAbsolute() {
		return this.isExpirationDateAbsolute;
	}

	public void setIsExpirationDateAbsolute(boolean isExpirationDateAbsolute) {
		this.isExpirationDateAbsolute = isExpirationDateAbsolute;
	}

	@Column(name = "PackageParentRecordID")
	public Integer getPackageParentRecordId() {
		return this.packageParentRecordId;
	}

	public void setPackageParentRecordId(Integer packageParentRecordId) {
		this.packageParentRecordId = packageParentRecordId;
	}

	@Column(name = "StoreId", nullable = false)
	public short getStoreId() {
		return this.storeId;
	}

	public void setStoreId(short storeId) {
		this.storeId = storeId;
	}

}
