package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CmrcReviews generated by hbm2java
 */
@Entity
@Table(name = "CMRC_Reviews")
public class CmrcReviews implements java.io.Serializable {

	private CmrcReviewsId id;

	public CmrcReviews() {
	}

	public CmrcReviews(CmrcReviewsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "reviewId", column = @Column(name = "ReviewID", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "ProductID", nullable = false)),
			@AttributeOverride(name = "customerName", column = @Column(name = "CustomerName")),
			@AttributeOverride(name = "customerEmail", column = @Column(name = "CustomerEmail")),
			@AttributeOverride(name = "rating", column = @Column(name = "Rating", nullable = false)),
			@AttributeOverride(name = "comments", column = @Column(name = "Comments")) })
	public CmrcReviewsId getId() {
		return this.id;
	}

	public void setId(CmrcReviewsId id) {
		this.id = id;
	}

}
