package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D01CuCustId generated by hbm2java
 */
@Embeddable
public class D01CuCustId implements java.io.Serializable {

	private int cuCustId;
	private short cuStoreId;
	private String cuFirstNameTx;
	private String cuMiddleInitialTxN;
	private String cuLastNameTx;
	private String cuKnownAsTxN;
	private String cuOccupationTxN;
	private Date cuBirthDateN;
	private Short cuSexIdN;
	private Short cuMaritalStatusIdN;
	private Integer cuSourceIdN;
	private String cuAddress1txN;
	private String cuAddress2txN;
	private String cuAddress3txN;
	private String cuAddress4txN;
	private Integer cuStateIdN;
	private String cuPostcodeTxN;
	private Integer cuCountryIdN;
	private Integer cuCompanyIdN;
	private String cuCompanyTxN;
	private String cuWaddress1txN;
	private String cuWaddress2txN;
	private String cuWaddress3txN;
	private String cuWaddress4txN;
	private Integer cuWstateIdN;
	private String cuWpostcodeTxN;
	private Integer cuWcountryIdN;
	private String cuLaddress1txN;
	private String cuLaddress2txN;
	private String cuLaddress3txN;
	private String cuLaddress4txN;
	private String cuLpostcodeTxN;
	private String cuTelLocalTxN;
	private String cuTelHomeTxN;
	private String cuTelWorkTxN;
	private String cuTelMobileTxN;
	private String cuFaxTxN;
	private String cuEmailTxN;
	private String cuPagerTxN;
	private Integer cuFirstLanguageIdN;
	private String cuNoknameTxN;
	private String cuNokrelationshipTxN;
	private String cuNokaddress1txN;
	private String cuNokaddress2txN;
	private String cuNokaddress3txN;
	private String cuNokaddress4txN;
	private String cuNokpostcodeTxN;
	private String cuNoktelTxN;
	private String cuImagePathTxN;
	private String cuNotesTxN;
	private boolean cuDoctorsReportRequiredBl;
	private boolean cuDoctorsReportReceivedBl;
	private String cuSuggestionTxN;
	private boolean cuUnavailableBl;
	private Date cuLastUpdatedDate;
	private String cuPassportNoTxN;
	private String cuFrequentFlyerTxN;
	private String cuSsntxN;
	private int cuStatusId;
	private String cuPadikeyTxN;
	private boolean cuCommissionableBl;
	private Date cuLastPurchaseDate;
	private double cuCreditMn;
	private double cuCreditLimitMn;
	private Date cuCreationDate;
	private String cuUserDefined1txN;
	private String cuUserDefined2txN;
	private String cuUserDefined3txN;
	private String cuUserNameTxN;
	private String cuPasswordTxN;
	private Short cuNoOfDivesInN;
	private Date cuLastDiveDateN;
	private boolean cuCardSeenBl;
	private Float cuHeightFlN;
	private Float cuWeightFlN;
	private String cuInsuranceNoTxN;
	private String cuInsuranceCoTxN;
	private Float cuShoeSizeFlN;
	private String cuSkypeNameTxN;
	private Date cuInsuranceDateN;
	private Date cuDoctorsReportDateN;
	private String cuVerifyGuid;
	private Integer cuBounceCountInN;
	private String cuStoreNoTxN;
	private Boolean cuIsAnonymousBlN;
	private Date cuLastActivityDateN;
	private boolean cuCreditRiskBl;
	private Integer cuAccManagerIdN;
	private String cuSecretQuestionTxN;
	private String cuSecretAnswerTxN;
	private boolean cuIsCustomerCompletlyRegisteredBl;
	private String cuCustNumberTxN;
	private String cuSwipeTxN;
	private boolean cuRequiredBl;
	private boolean cuPadimailingsBl;
	private boolean cu3rdPartyMailingsBl;
	private Integer cuScubaTribeIdN;
	private Date cuScubaTribeSentDate;
	private String cuScubaTribeCodeTxN;
	private Integer cuPadiidN;
	private String cuDataSourceTxN;
	private String cuInitialCatalogTxN;
	private String cuDbuserIdtxN;
	private String cuDbpasswordTxN;

	public D01CuCustId() {
	}

	public D01CuCustId(int cuCustId, short cuStoreId, String cuFirstNameTx, String cuLastNameTx,
			boolean cuDoctorsReportRequiredBl, boolean cuDoctorsReportReceivedBl, boolean cuUnavailableBl,
			Date cuLastUpdatedDate, int cuStatusId, boolean cuCommissionableBl, Date cuLastPurchaseDate,
			double cuCreditMn, double cuCreditLimitMn, Date cuCreationDate, boolean cuCardSeenBl,
			boolean cuCreditRiskBl, boolean cuIsCustomerCompletlyRegisteredBl, boolean cuRequiredBl,
			boolean cuPadimailingsBl, boolean cu3rdPartyMailingsBl, Date cuScubaTribeSentDate) {
		this.cuCustId = cuCustId;
		this.cuStoreId = cuStoreId;
		this.cuFirstNameTx = cuFirstNameTx;
		this.cuLastNameTx = cuLastNameTx;
		this.cuDoctorsReportRequiredBl = cuDoctorsReportRequiredBl;
		this.cuDoctorsReportReceivedBl = cuDoctorsReportReceivedBl;
		this.cuUnavailableBl = cuUnavailableBl;
		this.cuLastUpdatedDate = cuLastUpdatedDate;
		this.cuStatusId = cuStatusId;
		this.cuCommissionableBl = cuCommissionableBl;
		this.cuLastPurchaseDate = cuLastPurchaseDate;
		this.cuCreditMn = cuCreditMn;
		this.cuCreditLimitMn = cuCreditLimitMn;
		this.cuCreationDate = cuCreationDate;
		this.cuCardSeenBl = cuCardSeenBl;
		this.cuCreditRiskBl = cuCreditRiskBl;
		this.cuIsCustomerCompletlyRegisteredBl = cuIsCustomerCompletlyRegisteredBl;
		this.cuRequiredBl = cuRequiredBl;
		this.cuPadimailingsBl = cuPadimailingsBl;
		this.cu3rdPartyMailingsBl = cu3rdPartyMailingsBl;
		this.cuScubaTribeSentDate = cuScubaTribeSentDate;
	}

	public D01CuCustId(int cuCustId, short cuStoreId, String cuFirstNameTx, String cuMiddleInitialTxN,
			String cuLastNameTx, String cuKnownAsTxN, String cuOccupationTxN, Date cuBirthDateN,
			Short cuSexIdN, Short cuMaritalStatusIdN, Integer cuSourceIdN, String cuAddress1txN,
			String cuAddress2txN, String cuAddress3txN, String cuAddress4txN, Integer cuStateIdN,
			String cuPostcodeTxN, Integer cuCountryIdN, Integer cuCompanyIdN, String cuCompanyTxN,
			String cuWaddress1txN, String cuWaddress2txN, String cuWaddress3txN,
			String cuWaddress4txN, Integer cuWstateIdN, String cuWpostcodeTxN, Integer cuWcountryIdN,
			String cuLaddress1txN, String cuLaddress2txN, String cuLaddress3txN,
			String cuLaddress4txN, String cuLpostcodeTxN, String cuTelLocalTxN,
			String cuTelHomeTxN, String cuTelWorkTxN, String cuTelMobileTxN, String cuFaxTxN,
			String cuEmailTxN, String cuPagerTxN, Integer cuFirstLanguageIdN, String cuNoknameTxN,
			String cuNokrelationshipTxN, String cuNokaddress1txN, String cuNokaddress2txN,
			String cuNokaddress3txN, String cuNokaddress4txN, String cuNokpostcodeTxN,
			String cuNoktelTxN, String cuImagePathTxN, String cuNotesTxN,
			boolean cuDoctorsReportRequiredBl, boolean cuDoctorsReportReceivedBl, String cuSuggestionTxN,
			boolean cuUnavailableBl, Date cuLastUpdatedDate, String cuPassportNoTxN,
			String cuFrequentFlyerTxN, String cuSsntxN, int cuStatusId, String cuPadikeyTxN,
			boolean cuCommissionableBl, Date cuLastPurchaseDate, double cuCreditMn, double cuCreditLimitMn,
			Date cuCreationDate, String cuUserDefined1txN, String cuUserDefined2txN,
			String cuUserDefined3txN, String cuUserNameTxN, String cuPasswordTxN,
			Short cuNoOfDivesInN, Date cuLastDiveDateN, boolean cuCardSeenBl, Float cuHeightFlN, Float cuWeightFlN,
			String cuInsuranceNoTxN, String cuInsuranceCoTxN, Float cuShoeSizeFlN,
			String cuSkypeNameTxN, Date cuInsuranceDateN, Date cuDoctorsReportDateN, String cuVerifyGuid,
			Integer cuBounceCountInN, String cuStoreNoTxN, Boolean cuIsAnonymousBlN, Date cuLastActivityDateN,
			boolean cuCreditRiskBl, Integer cuAccManagerIdN, String cuSecretQuestionTxN,
			String cuSecretAnswerTxN, boolean cuIsCustomerCompletlyRegisteredBl, String cuCustNumberTxN,
			String cuSwipeTxN, boolean cuRequiredBl, boolean cuPadimailingsBl, boolean cu3rdPartyMailingsBl,
			Integer cuScubaTribeIdN, Date cuScubaTribeSentDate, String cuScubaTribeCodeTxN, Integer cuPadiidN,
			String cuDataSourceTxN, String cuInitialCatalogTxN, String cuDbuserIdtxN,
			String cuDbpasswordTxN) {
		this.cuCustId = cuCustId;
		this.cuStoreId = cuStoreId;
		this.cuFirstNameTx = cuFirstNameTx;
		this.cuMiddleInitialTxN = cuMiddleInitialTxN;
		this.cuLastNameTx = cuLastNameTx;
		this.cuKnownAsTxN = cuKnownAsTxN;
		this.cuOccupationTxN = cuOccupationTxN;
		this.cuBirthDateN = cuBirthDateN;
		this.cuSexIdN = cuSexIdN;
		this.cuMaritalStatusIdN = cuMaritalStatusIdN;
		this.cuSourceIdN = cuSourceIdN;
		this.cuAddress1txN = cuAddress1txN;
		this.cuAddress2txN = cuAddress2txN;
		this.cuAddress3txN = cuAddress3txN;
		this.cuAddress4txN = cuAddress4txN;
		this.cuStateIdN = cuStateIdN;
		this.cuPostcodeTxN = cuPostcodeTxN;
		this.cuCountryIdN = cuCountryIdN;
		this.cuCompanyIdN = cuCompanyIdN;
		this.cuCompanyTxN = cuCompanyTxN;
		this.cuWaddress1txN = cuWaddress1txN;
		this.cuWaddress2txN = cuWaddress2txN;
		this.cuWaddress3txN = cuWaddress3txN;
		this.cuWaddress4txN = cuWaddress4txN;
		this.cuWstateIdN = cuWstateIdN;
		this.cuWpostcodeTxN = cuWpostcodeTxN;
		this.cuWcountryIdN = cuWcountryIdN;
		this.cuLaddress1txN = cuLaddress1txN;
		this.cuLaddress2txN = cuLaddress2txN;
		this.cuLaddress3txN = cuLaddress3txN;
		this.cuLaddress4txN = cuLaddress4txN;
		this.cuLpostcodeTxN = cuLpostcodeTxN;
		this.cuTelLocalTxN = cuTelLocalTxN;
		this.cuTelHomeTxN = cuTelHomeTxN;
		this.cuTelWorkTxN = cuTelWorkTxN;
		this.cuTelMobileTxN = cuTelMobileTxN;
		this.cuFaxTxN = cuFaxTxN;
		this.cuEmailTxN = cuEmailTxN;
		this.cuPagerTxN = cuPagerTxN;
		this.cuFirstLanguageIdN = cuFirstLanguageIdN;
		this.cuNoknameTxN = cuNoknameTxN;
		this.cuNokrelationshipTxN = cuNokrelationshipTxN;
		this.cuNokaddress1txN = cuNokaddress1txN;
		this.cuNokaddress2txN = cuNokaddress2txN;
		this.cuNokaddress3txN = cuNokaddress3txN;
		this.cuNokaddress4txN = cuNokaddress4txN;
		this.cuNokpostcodeTxN = cuNokpostcodeTxN;
		this.cuNoktelTxN = cuNoktelTxN;
		this.cuImagePathTxN = cuImagePathTxN;
		this.cuNotesTxN = cuNotesTxN;
		this.cuDoctorsReportRequiredBl = cuDoctorsReportRequiredBl;
		this.cuDoctorsReportReceivedBl = cuDoctorsReportReceivedBl;
		this.cuSuggestionTxN = cuSuggestionTxN;
		this.cuUnavailableBl = cuUnavailableBl;
		this.cuLastUpdatedDate = cuLastUpdatedDate;
		this.cuPassportNoTxN = cuPassportNoTxN;
		this.cuFrequentFlyerTxN = cuFrequentFlyerTxN;
		this.cuSsntxN = cuSsntxN;
		this.cuStatusId = cuStatusId;
		this.cuPadikeyTxN = cuPadikeyTxN;
		this.cuCommissionableBl = cuCommissionableBl;
		this.cuLastPurchaseDate = cuLastPurchaseDate;
		this.cuCreditMn = cuCreditMn;
		this.cuCreditLimitMn = cuCreditLimitMn;
		this.cuCreationDate = cuCreationDate;
		this.cuUserDefined1txN = cuUserDefined1txN;
		this.cuUserDefined2txN = cuUserDefined2txN;
		this.cuUserDefined3txN = cuUserDefined3txN;
		this.cuUserNameTxN = cuUserNameTxN;
		this.cuPasswordTxN = cuPasswordTxN;
		this.cuNoOfDivesInN = cuNoOfDivesInN;
		this.cuLastDiveDateN = cuLastDiveDateN;
		this.cuCardSeenBl = cuCardSeenBl;
		this.cuHeightFlN = cuHeightFlN;
		this.cuWeightFlN = cuWeightFlN;
		this.cuInsuranceNoTxN = cuInsuranceNoTxN;
		this.cuInsuranceCoTxN = cuInsuranceCoTxN;
		this.cuShoeSizeFlN = cuShoeSizeFlN;
		this.cuSkypeNameTxN = cuSkypeNameTxN;
		this.cuInsuranceDateN = cuInsuranceDateN;
		this.cuDoctorsReportDateN = cuDoctorsReportDateN;
		this.cuVerifyGuid = cuVerifyGuid;
		this.cuBounceCountInN = cuBounceCountInN;
		this.cuStoreNoTxN = cuStoreNoTxN;
		this.cuIsAnonymousBlN = cuIsAnonymousBlN;
		this.cuLastActivityDateN = cuLastActivityDateN;
		this.cuCreditRiskBl = cuCreditRiskBl;
		this.cuAccManagerIdN = cuAccManagerIdN;
		this.cuSecretQuestionTxN = cuSecretQuestionTxN;
		this.cuSecretAnswerTxN = cuSecretAnswerTxN;
		this.cuIsCustomerCompletlyRegisteredBl = cuIsCustomerCompletlyRegisteredBl;
		this.cuCustNumberTxN = cuCustNumberTxN;
		this.cuSwipeTxN = cuSwipeTxN;
		this.cuRequiredBl = cuRequiredBl;
		this.cuPadimailingsBl = cuPadimailingsBl;
		this.cu3rdPartyMailingsBl = cu3rdPartyMailingsBl;
		this.cuScubaTribeIdN = cuScubaTribeIdN;
		this.cuScubaTribeSentDate = cuScubaTribeSentDate;
		this.cuScubaTribeCodeTxN = cuScubaTribeCodeTxN;
		this.cuPadiidN = cuPadiidN;
		this.cuDataSourceTxN = cuDataSourceTxN;
		this.cuInitialCatalogTxN = cuInitialCatalogTxN;
		this.cuDbuserIdtxN = cuDbuserIdtxN;
		this.cuDbpasswordTxN = cuDbpasswordTxN;
	}

	@Column(name = "CuCustID", nullable = false)
	public int getCuCustId() {
		return this.cuCustId;
	}

	public void setCuCustId(int cuCustId) {
		this.cuCustId = cuCustId;
	}

	@Column(name = "CuStoreID", nullable = false)
	public short getCuStoreId() {
		return this.cuStoreId;
	}

	public void setCuStoreId(short cuStoreId) {
		this.cuStoreId = cuStoreId;
	}

	@Column(name = "CuFirstNameTx", nullable = false)
	public String getCuFirstNameTx() {
		return this.cuFirstNameTx;
	}

	public void setCuFirstNameTx(String cuFirstNameTx) {
		this.cuFirstNameTx = cuFirstNameTx;
	}

	@Column(name = "CuMiddleInitialTx_N")
	public String getCuMiddleInitialTxN() {
		return this.cuMiddleInitialTxN;
	}

	public void setCuMiddleInitialTxN(String cuMiddleInitialTxN) {
		this.cuMiddleInitialTxN = cuMiddleInitialTxN;
	}

	@Column(name = "CuLastNameTx", nullable = false)
	public String getCuLastNameTx() {
		return this.cuLastNameTx;
	}

	public void setCuLastNameTx(String cuLastNameTx) {
		this.cuLastNameTx = cuLastNameTx;
	}

	@Column(name = "CuKnownAsTx_N")
	public String getCuKnownAsTxN() {
		return this.cuKnownAsTxN;
	}

	public void setCuKnownAsTxN(String cuKnownAsTxN) {
		this.cuKnownAsTxN = cuKnownAsTxN;
	}

	@Column(name = "CuOccupationTx_N")
	public String getCuOccupationTxN() {
		return this.cuOccupationTxN;
	}

	public void setCuOccupationTxN(String cuOccupationTxN) {
		this.cuOccupationTxN = cuOccupationTxN;
	}

	@Column(name = "CuBirthDate_N", length = 23)
	public Date getCuBirthDateN() {
		return this.cuBirthDateN;
	}

	public void setCuBirthDateN(Date cuBirthDateN) {
		this.cuBirthDateN = cuBirthDateN;
	}

	@Column(name = "CuSexID_N")
	public Short getCuSexIdN() {
		return this.cuSexIdN;
	}

	public void setCuSexIdN(Short cuSexIdN) {
		this.cuSexIdN = cuSexIdN;
	}

	@Column(name = "CuMaritalStatusID_N")
	public Short getCuMaritalStatusIdN() {
		return this.cuMaritalStatusIdN;
	}

	public void setCuMaritalStatusIdN(Short cuMaritalStatusIdN) {
		this.cuMaritalStatusIdN = cuMaritalStatusIdN;
	}

	@Column(name = "CuSourceID_N")
	public Integer getCuSourceIdN() {
		return this.cuSourceIdN;
	}

	public void setCuSourceIdN(Integer cuSourceIdN) {
		this.cuSourceIdN = cuSourceIdN;
	}

	@Column(name = "CuAddress1Tx_N")
	public String getCuAddress1txN() {
		return this.cuAddress1txN;
	}

	public void setCuAddress1txN(String cuAddress1txN) {
		this.cuAddress1txN = cuAddress1txN;
	}

	@Column(name = "CuAddress2Tx_N")
	public String getCuAddress2txN() {
		return this.cuAddress2txN;
	}

	public void setCuAddress2txN(String cuAddress2txN) {
		this.cuAddress2txN = cuAddress2txN;
	}

	@Column(name = "CuAddress3Tx_N")
	public String getCuAddress3txN() {
		return this.cuAddress3txN;
	}

	public void setCuAddress3txN(String cuAddress3txN) {
		this.cuAddress3txN = cuAddress3txN;
	}

	@Column(name = "CuAddress4Tx_N")
	public String getCuAddress4txN() {
		return this.cuAddress4txN;
	}

	public void setCuAddress4txN(String cuAddress4txN) {
		this.cuAddress4txN = cuAddress4txN;
	}

	@Column(name = "CuStateID_N")
	public Integer getCuStateIdN() {
		return this.cuStateIdN;
	}

	public void setCuStateIdN(Integer cuStateIdN) {
		this.cuStateIdN = cuStateIdN;
	}

	@Column(name = "CuPostcodeTx_N")
	public String getCuPostcodeTxN() {
		return this.cuPostcodeTxN;
	}

	public void setCuPostcodeTxN(String cuPostcodeTxN) {
		this.cuPostcodeTxN = cuPostcodeTxN;
	}

	@Column(name = "CuCountryID_N")
	public Integer getCuCountryIdN() {
		return this.cuCountryIdN;
	}

	public void setCuCountryIdN(Integer cuCountryIdN) {
		this.cuCountryIdN = cuCountryIdN;
	}

	@Column(name = "CuCompanyID_N")
	public Integer getCuCompanyIdN() {
		return this.cuCompanyIdN;
	}

	public void setCuCompanyIdN(Integer cuCompanyIdN) {
		this.cuCompanyIdN = cuCompanyIdN;
	}

	@Column(name = "CuCompanyTx_N")
	public String getCuCompanyTxN() {
		return this.cuCompanyTxN;
	}

	public void setCuCompanyTxN(String cuCompanyTxN) {
		this.cuCompanyTxN = cuCompanyTxN;
	}

	@Column(name = "CuWAddress1Tx_N")
	public String getCuWaddress1txN() {
		return this.cuWaddress1txN;
	}

	public void setCuWaddress1txN(String cuWaddress1txN) {
		this.cuWaddress1txN = cuWaddress1txN;
	}

	@Column(name = "CuWAddress2Tx_N")
	public String getCuWaddress2txN() {
		return this.cuWaddress2txN;
	}

	public void setCuWaddress2txN(String cuWaddress2txN) {
		this.cuWaddress2txN = cuWaddress2txN;
	}

	@Column(name = "CuWAddress3Tx_N")
	public String getCuWaddress3txN() {
		return this.cuWaddress3txN;
	}

	public void setCuWaddress3txN(String cuWaddress3txN) {
		this.cuWaddress3txN = cuWaddress3txN;
	}

	@Column(name = "CuWAddress4Tx_N")
	public String getCuWaddress4txN() {
		return this.cuWaddress4txN;
	}

	public void setCuWaddress4txN(String cuWaddress4txN) {
		this.cuWaddress4txN = cuWaddress4txN;
	}

	@Column(name = "CuWStateID_N")
	public Integer getCuWstateIdN() {
		return this.cuWstateIdN;
	}

	public void setCuWstateIdN(Integer cuWstateIdN) {
		this.cuWstateIdN = cuWstateIdN;
	}

	@Column(name = "CuWPostcodeTx_N")
	public String getCuWpostcodeTxN() {
		return this.cuWpostcodeTxN;
	}

	public void setCuWpostcodeTxN(String cuWpostcodeTxN) {
		this.cuWpostcodeTxN = cuWpostcodeTxN;
	}

	@Column(name = "CuWCountryID_N")
	public Integer getCuWcountryIdN() {
		return this.cuWcountryIdN;
	}

	public void setCuWcountryIdN(Integer cuWcountryIdN) {
		this.cuWcountryIdN = cuWcountryIdN;
	}

	@Column(name = "CuLAddress1Tx_N")
	public String getCuLaddress1txN() {
		return this.cuLaddress1txN;
	}

	public void setCuLaddress1txN(String cuLaddress1txN) {
		this.cuLaddress1txN = cuLaddress1txN;
	}

	@Column(name = "CuLAddress2Tx_N")
	public String getCuLaddress2txN() {
		return this.cuLaddress2txN;
	}

	public void setCuLaddress2txN(String cuLaddress2txN) {
		this.cuLaddress2txN = cuLaddress2txN;
	}

	@Column(name = "CuLAddress3Tx_N")
	public String getCuLaddress3txN() {
		return this.cuLaddress3txN;
	}

	public void setCuLaddress3txN(String cuLaddress3txN) {
		this.cuLaddress3txN = cuLaddress3txN;
	}

	@Column(name = "CuLAddress4Tx_N")
	public String getCuLaddress4txN() {
		return this.cuLaddress4txN;
	}

	public void setCuLaddress4txN(String cuLaddress4txN) {
		this.cuLaddress4txN = cuLaddress4txN;
	}

	@Column(name = "CuLPostcodeTx_N")
	public String getCuLpostcodeTxN() {
		return this.cuLpostcodeTxN;
	}

	public void setCuLpostcodeTxN(String cuLpostcodeTxN) {
		this.cuLpostcodeTxN = cuLpostcodeTxN;
	}

	@Column(name = "CuTelLocalTx_N")
	public String getCuTelLocalTxN() {
		return this.cuTelLocalTxN;
	}

	public void setCuTelLocalTxN(String cuTelLocalTxN) {
		this.cuTelLocalTxN = cuTelLocalTxN;
	}

	@Column(name = "CuTelHomeTx_N")
	public String getCuTelHomeTxN() {
		return this.cuTelHomeTxN;
	}

	public void setCuTelHomeTxN(String cuTelHomeTxN) {
		this.cuTelHomeTxN = cuTelHomeTxN;
	}

	@Column(name = "CuTelWorkTx_N")
	public String getCuTelWorkTxN() {
		return this.cuTelWorkTxN;
	}

	public void setCuTelWorkTxN(String cuTelWorkTxN) {
		this.cuTelWorkTxN = cuTelWorkTxN;
	}

	@Column(name = "CuTelMobileTx_N")
	public String getCuTelMobileTxN() {
		return this.cuTelMobileTxN;
	}

	public void setCuTelMobileTxN(String cuTelMobileTxN) {
		this.cuTelMobileTxN = cuTelMobileTxN;
	}

	@Column(name = "CuFaxTx_N")
	public String getCuFaxTxN() {
		return this.cuFaxTxN;
	}

	public void setCuFaxTxN(String cuFaxTxN) {
		this.cuFaxTxN = cuFaxTxN;
	}

	@Column(name = "CuEMailTx_N")
	public String getCuEmailTxN() {
		return this.cuEmailTxN;
	}

	public void setCuEmailTxN(String cuEmailTxN) {
		this.cuEmailTxN = cuEmailTxN;
	}

	@Column(name = "CuPagerTx_N")
	public String getCuPagerTxN() {
		return this.cuPagerTxN;
	}

	public void setCuPagerTxN(String cuPagerTxN) {
		this.cuPagerTxN = cuPagerTxN;
	}

	@Column(name = "CuFirstLanguageID_N")
	public Integer getCuFirstLanguageIdN() {
		return this.cuFirstLanguageIdN;
	}

	public void setCuFirstLanguageIdN(Integer cuFirstLanguageIdN) {
		this.cuFirstLanguageIdN = cuFirstLanguageIdN;
	}

	@Column(name = "CuNOKNameTx_N")
	public String getCuNoknameTxN() {
		return this.cuNoknameTxN;
	}

	public void setCuNoknameTxN(String cuNoknameTxN) {
		this.cuNoknameTxN = cuNoknameTxN;
	}

	@Column(name = "CuNOKRelationshipTx_N")
	public String getCuNokrelationshipTxN() {
		return this.cuNokrelationshipTxN;
	}

	public void setCuNokrelationshipTxN(String cuNokrelationshipTxN) {
		this.cuNokrelationshipTxN = cuNokrelationshipTxN;
	}

	@Column(name = "CuNOKAddress1Tx_N")
	public String getCuNokaddress1txN() {
		return this.cuNokaddress1txN;
	}

	public void setCuNokaddress1txN(String cuNokaddress1txN) {
		this.cuNokaddress1txN = cuNokaddress1txN;
	}

	@Column(name = "CuNOKAddress2Tx_N")
	public String getCuNokaddress2txN() {
		return this.cuNokaddress2txN;
	}

	public void setCuNokaddress2txN(String cuNokaddress2txN) {
		this.cuNokaddress2txN = cuNokaddress2txN;
	}

	@Column(name = "CuNOKAddress3Tx_N")
	public String getCuNokaddress3txN() {
		return this.cuNokaddress3txN;
	}

	public void setCuNokaddress3txN(String cuNokaddress3txN) {
		this.cuNokaddress3txN = cuNokaddress3txN;
	}

	@Column(name = "CuNOKAddress4Tx_N")
	public String getCuNokaddress4txN() {
		return this.cuNokaddress4txN;
	}

	public void setCuNokaddress4txN(String cuNokaddress4txN) {
		this.cuNokaddress4txN = cuNokaddress4txN;
	}

	@Column(name = "CuNOKPostcodeTx_N")
	public String getCuNokpostcodeTxN() {
		return this.cuNokpostcodeTxN;
	}

	public void setCuNokpostcodeTxN(String cuNokpostcodeTxN) {
		this.cuNokpostcodeTxN = cuNokpostcodeTxN;
	}

	@Column(name = "CuNOKTelTx_N")
	public String getCuNoktelTxN() {
		return this.cuNoktelTxN;
	}

	public void setCuNoktelTxN(String cuNoktelTxN) {
		this.cuNoktelTxN = cuNoktelTxN;
	}

	@Column(name = "CuImagePathTx_N")
	public String getCuImagePathTxN() {
		return this.cuImagePathTxN;
	}

	public void setCuImagePathTxN(String cuImagePathTxN) {
		this.cuImagePathTxN = cuImagePathTxN;
	}

	@Column(name = "CuNotesTx_N")
	public String getCuNotesTxN() {
		return this.cuNotesTxN;
	}

	public void setCuNotesTxN(String cuNotesTxN) {
		this.cuNotesTxN = cuNotesTxN;
	}

	@Column(name = "CuDoctorsReportRequiredBl", nullable = false)
	public boolean isCuDoctorsReportRequiredBl() {
		return this.cuDoctorsReportRequiredBl;
	}

	public void setCuDoctorsReportRequiredBl(boolean cuDoctorsReportRequiredBl) {
		this.cuDoctorsReportRequiredBl = cuDoctorsReportRequiredBl;
	}

	@Column(name = "CuDoctorsReportReceivedBl", nullable = false)
	public boolean isCuDoctorsReportReceivedBl() {
		return this.cuDoctorsReportReceivedBl;
	}

	public void setCuDoctorsReportReceivedBl(boolean cuDoctorsReportReceivedBl) {
		this.cuDoctorsReportReceivedBl = cuDoctorsReportReceivedBl;
	}

	@Column(name = "CuSuggestionTx_N")
	public String getCuSuggestionTxN() {
		return this.cuSuggestionTxN;
	}

	public void setCuSuggestionTxN(String cuSuggestionTxN) {
		this.cuSuggestionTxN = cuSuggestionTxN;
	}

	@Column(name = "CuUnavailableBl", nullable = false)
	public boolean isCuUnavailableBl() {
		return this.cuUnavailableBl;
	}

	public void setCuUnavailableBl(boolean cuUnavailableBl) {
		this.cuUnavailableBl = cuUnavailableBl;
	}

	@Column(name = "CuLastUpdatedDate", nullable = false, length = 23)
	public Date getCuLastUpdatedDate() {
		return this.cuLastUpdatedDate;
	}

	public void setCuLastUpdatedDate(Date cuLastUpdatedDate) {
		this.cuLastUpdatedDate = cuLastUpdatedDate;
	}

	@Column(name = "CuPassportNoTx_N")
	public String getCuPassportNoTxN() {
		return this.cuPassportNoTxN;
	}

	public void setCuPassportNoTxN(String cuPassportNoTxN) {
		this.cuPassportNoTxN = cuPassportNoTxN;
	}

	@Column(name = "CuFrequentFlyerTx_N")
	public String getCuFrequentFlyerTxN() {
		return this.cuFrequentFlyerTxN;
	}

	public void setCuFrequentFlyerTxN(String cuFrequentFlyerTxN) {
		this.cuFrequentFlyerTxN = cuFrequentFlyerTxN;
	}

	@Column(name = "CuSSNTx_N")
	public String getCuSsntxN() {
		return this.cuSsntxN;
	}

	public void setCuSsntxN(String cuSsntxN) {
		this.cuSsntxN = cuSsntxN;
	}

	@Column(name = "CuStatusID", nullable = false)
	public int getCuStatusId() {
		return this.cuStatusId;
	}

	public void setCuStatusId(int cuStatusId) {
		this.cuStatusId = cuStatusId;
	}

	@Column(name = "CuPADIKeyTx_N")
	public String getCuPadikeyTxN() {
		return this.cuPadikeyTxN;
	}

	public void setCuPadikeyTxN(String cuPadikeyTxN) {
		this.cuPadikeyTxN = cuPadikeyTxN;
	}

	@Column(name = "CuCommissionableBl", nullable = false)
	public boolean isCuCommissionableBl() {
		return this.cuCommissionableBl;
	}

	public void setCuCommissionableBl(boolean cuCommissionableBl) {
		this.cuCommissionableBl = cuCommissionableBl;
	}

	@Column(name = "CuLastPurchaseDate", nullable = false, length = 23)
	public Date getCuLastPurchaseDate() {
		return this.cuLastPurchaseDate;
	}

	public void setCuLastPurchaseDate(Date cuLastPurchaseDate) {
		this.cuLastPurchaseDate = cuLastPurchaseDate;
	}

	@Column(name = "CuCreditMn", nullable = false, precision = 53, scale = 0)
	public double getCuCreditMn() {
		return this.cuCreditMn;
	}

	public void setCuCreditMn(double cuCreditMn) {
		this.cuCreditMn = cuCreditMn;
	}

	@Column(name = "CuCreditLimitMn", nullable = false, precision = 53, scale = 0)
	public double getCuCreditLimitMn() {
		return this.cuCreditLimitMn;
	}

	public void setCuCreditLimitMn(double cuCreditLimitMn) {
		this.cuCreditLimitMn = cuCreditLimitMn;
	}

	@Column(name = "CuCreationDate", nullable = false, length = 23)
	public Date getCuCreationDate() {
		return this.cuCreationDate;
	}

	public void setCuCreationDate(Date cuCreationDate) {
		this.cuCreationDate = cuCreationDate;
	}

	@Column(name = "CuUserDefined1Tx_N")
	public String getCuUserDefined1txN() {
		return this.cuUserDefined1txN;
	}

	public void setCuUserDefined1txN(String cuUserDefined1txN) {
		this.cuUserDefined1txN = cuUserDefined1txN;
	}

	@Column(name = "CuUserDefined2Tx_N")
	public String getCuUserDefined2txN() {
		return this.cuUserDefined2txN;
	}

	public void setCuUserDefined2txN(String cuUserDefined2txN) {
		this.cuUserDefined2txN = cuUserDefined2txN;
	}

	@Column(name = "CuUserDefined3Tx_N")
	public String getCuUserDefined3txN() {
		return this.cuUserDefined3txN;
	}

	public void setCuUserDefined3txN(String cuUserDefined3txN) {
		this.cuUserDefined3txN = cuUserDefined3txN;
	}

	@Column(name = "CuUserNameTx_N")
	public String getCuUserNameTxN() {
		return this.cuUserNameTxN;
	}

	public void setCuUserNameTxN(String cuUserNameTxN) {
		this.cuUserNameTxN = cuUserNameTxN;
	}

	@Column(name = "CuPasswordTx_N")
	public String getCuPasswordTxN() {
		return this.cuPasswordTxN;
	}

	public void setCuPasswordTxN(String cuPasswordTxN) {
		this.cuPasswordTxN = cuPasswordTxN;
	}

	@Column(name = "CuNoOfDivesIn_N")
	public Short getCuNoOfDivesInN() {
		return this.cuNoOfDivesInN;
	}

	public void setCuNoOfDivesInN(Short cuNoOfDivesInN) {
		this.cuNoOfDivesInN = cuNoOfDivesInN;
	}

	@Column(name = "CuLastDiveDate_N", length = 23)
	public Date getCuLastDiveDateN() {
		return this.cuLastDiveDateN;
	}

	public void setCuLastDiveDateN(Date cuLastDiveDateN) {
		this.cuLastDiveDateN = cuLastDiveDateN;
	}

	@Column(name = "CuCardSeenBl", nullable = false)
	public boolean isCuCardSeenBl() {
		return this.cuCardSeenBl;
	}

	public void setCuCardSeenBl(boolean cuCardSeenBl) {
		this.cuCardSeenBl = cuCardSeenBl;
	}

	@Column(name = "CuHeightFl_N", precision = 24, scale = 0)
	public Float getCuHeightFlN() {
		return this.cuHeightFlN;
	}

	public void setCuHeightFlN(Float cuHeightFlN) {
		this.cuHeightFlN = cuHeightFlN;
	}

	@Column(name = "CuWeightFl_N", precision = 24, scale = 0)
	public Float getCuWeightFlN() {
		return this.cuWeightFlN;
	}

	public void setCuWeightFlN(Float cuWeightFlN) {
		this.cuWeightFlN = cuWeightFlN;
	}

	@Column(name = "CuInsuranceNoTx_N")
	public String getCuInsuranceNoTxN() {
		return this.cuInsuranceNoTxN;
	}

	public void setCuInsuranceNoTxN(String cuInsuranceNoTxN) {
		this.cuInsuranceNoTxN = cuInsuranceNoTxN;
	}

	@Column(name = "CuInsuranceCoTx_N")
	public String getCuInsuranceCoTxN() {
		return this.cuInsuranceCoTxN;
	}

	public void setCuInsuranceCoTxN(String cuInsuranceCoTxN) {
		this.cuInsuranceCoTxN = cuInsuranceCoTxN;
	}

	@Column(name = "CuShoeSizeFl_N", precision = 24, scale = 0)
	public Float getCuShoeSizeFlN() {
		return this.cuShoeSizeFlN;
	}

	public void setCuShoeSizeFlN(Float cuShoeSizeFlN) {
		this.cuShoeSizeFlN = cuShoeSizeFlN;
	}

	@Column(name = "CuSkypeNameTx_N")
	public String getCuSkypeNameTxN() {
		return this.cuSkypeNameTxN;
	}

	public void setCuSkypeNameTxN(String cuSkypeNameTxN) {
		this.cuSkypeNameTxN = cuSkypeNameTxN;
	}

	@Column(name = "CuInsuranceDate_N", length = 23)
	public Date getCuInsuranceDateN() {
		return this.cuInsuranceDateN;
	}

	public void setCuInsuranceDateN(Date cuInsuranceDateN) {
		this.cuInsuranceDateN = cuInsuranceDateN;
	}

	@Column(name = "CuDoctorsReportDate_N", length = 23)
	public Date getCuDoctorsReportDateN() {
		return this.cuDoctorsReportDateN;
	}

	public void setCuDoctorsReportDateN(Date cuDoctorsReportDateN) {
		this.cuDoctorsReportDateN = cuDoctorsReportDateN;
	}

	@Column(name = "CuVerifyGuid", length = 36)
	public String getCuVerifyGuid() {
		return this.cuVerifyGuid;
	}

	public void setCuVerifyGuid(String cuVerifyGuid) {
		this.cuVerifyGuid = cuVerifyGuid;
	}

	@Column(name = "CuBounceCountIn_N")
	public Integer getCuBounceCountInN() {
		return this.cuBounceCountInN;
	}

	public void setCuBounceCountInN(Integer cuBounceCountInN) {
		this.cuBounceCountInN = cuBounceCountInN;
	}

	@Column(name = "CuStoreNoTx_N")
	public String getCuStoreNoTxN() {
		return this.cuStoreNoTxN;
	}

	public void setCuStoreNoTxN(String cuStoreNoTxN) {
		this.cuStoreNoTxN = cuStoreNoTxN;
	}

	@Column(name = "CuIsAnonymousBl_N")
	public Boolean getCuIsAnonymousBlN() {
		return this.cuIsAnonymousBlN;
	}

	public void setCuIsAnonymousBlN(Boolean cuIsAnonymousBlN) {
		this.cuIsAnonymousBlN = cuIsAnonymousBlN;
	}

	@Column(name = "CuLastActivityDate_N", length = 23)
	public Date getCuLastActivityDateN() {
		return this.cuLastActivityDateN;
	}

	public void setCuLastActivityDateN(Date cuLastActivityDateN) {
		this.cuLastActivityDateN = cuLastActivityDateN;
	}

	@Column(name = "CuCreditRiskBl", nullable = false)
	public boolean isCuCreditRiskBl() {
		return this.cuCreditRiskBl;
	}

	public void setCuCreditRiskBl(boolean cuCreditRiskBl) {
		this.cuCreditRiskBl = cuCreditRiskBl;
	}

	@Column(name = "CuAccManagerID_N")
	public Integer getCuAccManagerIdN() {
		return this.cuAccManagerIdN;
	}

	public void setCuAccManagerIdN(Integer cuAccManagerIdN) {
		this.cuAccManagerIdN = cuAccManagerIdN;
	}

	@Column(name = "CuSecretQuestionTx_N")
	public String getCuSecretQuestionTxN() {
		return this.cuSecretQuestionTxN;
	}

	public void setCuSecretQuestionTxN(String cuSecretQuestionTxN) {
		this.cuSecretQuestionTxN = cuSecretQuestionTxN;
	}

	@Column(name = "CuSecretAnswerTx_N")
	public String getCuSecretAnswerTxN() {
		return this.cuSecretAnswerTxN;
	}

	public void setCuSecretAnswerTxN(String cuSecretAnswerTxN) {
		this.cuSecretAnswerTxN = cuSecretAnswerTxN;
	}

	@Column(name = "CuIsCustomerCompletlyRegisteredBl", nullable = false)
	public boolean isCuIsCustomerCompletlyRegisteredBl() {
		return this.cuIsCustomerCompletlyRegisteredBl;
	}

	public void setCuIsCustomerCompletlyRegisteredBl(boolean cuIsCustomerCompletlyRegisteredBl) {
		this.cuIsCustomerCompletlyRegisteredBl = cuIsCustomerCompletlyRegisteredBl;
	}

	@Column(name = "CuCustNumberTx_N")
	public String getCuCustNumberTxN() {
		return this.cuCustNumberTxN;
	}

	public void setCuCustNumberTxN(String cuCustNumberTxN) {
		this.cuCustNumberTxN = cuCustNumberTxN;
	}

	@Column(name = "CuSwipeTx_N")
	public String getCuSwipeTxN() {
		return this.cuSwipeTxN;
	}

	public void setCuSwipeTxN(String cuSwipeTxN) {
		this.cuSwipeTxN = cuSwipeTxN;
	}

	@Column(name = "CuRequiredBl", nullable = false)
	public boolean isCuRequiredBl() {
		return this.cuRequiredBl;
	}

	public void setCuRequiredBl(boolean cuRequiredBl) {
		this.cuRequiredBl = cuRequiredBl;
	}

	@Column(name = "CuPADIMailingsBl", nullable = false)
	public boolean isCuPadimailingsBl() {
		return this.cuPadimailingsBl;
	}

	public void setCuPadimailingsBl(boolean cuPadimailingsBl) {
		this.cuPadimailingsBl = cuPadimailingsBl;
	}

	@Column(name = "Cu3rdPartyMailingsBl", nullable = false)
	public boolean isCu3rdPartyMailingsBl() {
		return this.cu3rdPartyMailingsBl;
	}

	public void setCu3rdPartyMailingsBl(boolean cu3rdPartyMailingsBl) {
		this.cu3rdPartyMailingsBl = cu3rdPartyMailingsBl;
	}

	@Column(name = "CuScubaTribeID_N")
	public Integer getCuScubaTribeIdN() {
		return this.cuScubaTribeIdN;
	}

	public void setCuScubaTribeIdN(Integer cuScubaTribeIdN) {
		this.cuScubaTribeIdN = cuScubaTribeIdN;
	}

	@Column(name = "CuScubaTribeSentDate", nullable = false, length = 23)
	public Date getCuScubaTribeSentDate() {
		return this.cuScubaTribeSentDate;
	}

	public void setCuScubaTribeSentDate(Date cuScubaTribeSentDate) {
		this.cuScubaTribeSentDate = cuScubaTribeSentDate;
	}

	@Column(name = "CuScubaTribeCodeTx_N")
	public String getCuScubaTribeCodeTxN() {
		return this.cuScubaTribeCodeTxN;
	}

	public void setCuScubaTribeCodeTxN(String cuScubaTribeCodeTxN) {
		this.cuScubaTribeCodeTxN = cuScubaTribeCodeTxN;
	}

	@Column(name = "CuPADIID_N")
	public Integer getCuPadiidN() {
		return this.cuPadiidN;
	}

	public void setCuPadiidN(Integer cuPadiidN) {
		this.cuPadiidN = cuPadiidN;
	}

	@Column(name = "CuDataSourceTx_N")
	public String getCuDataSourceTxN() {
		return this.cuDataSourceTxN;
	}

	public void setCuDataSourceTxN(String cuDataSourceTxN) {
		this.cuDataSourceTxN = cuDataSourceTxN;
	}

	@Column(name = "CuInitialCatalogTx_N")
	public String getCuInitialCatalogTxN() {
		return this.cuInitialCatalogTxN;
	}

	public void setCuInitialCatalogTxN(String cuInitialCatalogTxN) {
		this.cuInitialCatalogTxN = cuInitialCatalogTxN;
	}

	@Column(name = "CuDBUserIDTx_N")
	public String getCuDbuserIdtxN() {
		return this.cuDbuserIdtxN;
	}

	public void setCuDbuserIdtxN(String cuDbuserIdtxN) {
		this.cuDbuserIdtxN = cuDbuserIdtxN;
	}

	@Column(name = "CuDBPasswordTx_N")
	public String getCuDbpasswordTxN() {
		return this.cuDbpasswordTxN;
	}

	public void setCuDbpasswordTxN(String cuDbpasswordTxN) {
		this.cuDbpasswordTxN = cuDbpasswordTxN;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D01CuCustId))
			return false;
		D01CuCustId castOther = (D01CuCustId) other;

		return (this.getCuCustId() == castOther.getCuCustId()) && (this.getCuStoreId() == castOther.getCuStoreId())
				&& ((this.getCuFirstNameTx() == castOther.getCuFirstNameTx())
						|| (this.getCuFirstNameTx() != null && castOther.getCuFirstNameTx() != null
								&& this.getCuFirstNameTx().equals(castOther.getCuFirstNameTx())))
				&& ((this.getCuMiddleInitialTxN() == castOther.getCuMiddleInitialTxN())
						|| (this.getCuMiddleInitialTxN() != null && castOther.getCuMiddleInitialTxN() != null
								&& this.getCuMiddleInitialTxN().equals(castOther.getCuMiddleInitialTxN())))
				&& ((this.getCuLastNameTx() == castOther.getCuLastNameTx())
						|| (this.getCuLastNameTx() != null && castOther.getCuLastNameTx() != null
								&& this.getCuLastNameTx().equals(castOther.getCuLastNameTx())))
				&& ((this.getCuKnownAsTxN() == castOther.getCuKnownAsTxN())
						|| (this.getCuKnownAsTxN() != null && castOther.getCuKnownAsTxN() != null
								&& this.getCuKnownAsTxN().equals(castOther.getCuKnownAsTxN())))
				&& ((this.getCuOccupationTxN() == castOther.getCuOccupationTxN())
						|| (this.getCuOccupationTxN() != null && castOther.getCuOccupationTxN() != null
								&& this.getCuOccupationTxN().equals(castOther.getCuOccupationTxN())))
				&& ((this.getCuBirthDateN() == castOther.getCuBirthDateN())
						|| (this.getCuBirthDateN() != null && castOther.getCuBirthDateN() != null
								&& this.getCuBirthDateN().equals(castOther.getCuBirthDateN())))
				&& ((this.getCuSexIdN() == castOther.getCuSexIdN()) || (this.getCuSexIdN() != null
						&& castOther.getCuSexIdN() != null && this.getCuSexIdN().equals(castOther.getCuSexIdN())))
				&& ((this.getCuMaritalStatusIdN() == castOther.getCuMaritalStatusIdN())
						|| (this.getCuMaritalStatusIdN() != null && castOther.getCuMaritalStatusIdN() != null
								&& this.getCuMaritalStatusIdN().equals(castOther.getCuMaritalStatusIdN())))
				&& ((this.getCuSourceIdN() == castOther.getCuSourceIdN())
						|| (this.getCuSourceIdN() != null && castOther.getCuSourceIdN() != null
								&& this.getCuSourceIdN().equals(castOther.getCuSourceIdN())))
				&& ((this.getCuAddress1txN() == castOther.getCuAddress1txN())
						|| (this.getCuAddress1txN() != null && castOther.getCuAddress1txN() != null
								&& this.getCuAddress1txN().equals(castOther.getCuAddress1txN())))
				&& ((this.getCuAddress2txN() == castOther.getCuAddress2txN())
						|| (this.getCuAddress2txN() != null && castOther.getCuAddress2txN() != null
								&& this.getCuAddress2txN().equals(castOther.getCuAddress2txN())))
				&& ((this.getCuAddress3txN() == castOther.getCuAddress3txN())
						|| (this.getCuAddress3txN() != null && castOther.getCuAddress3txN() != null
								&& this.getCuAddress3txN().equals(castOther.getCuAddress3txN())))
				&& ((this.getCuAddress4txN() == castOther.getCuAddress4txN())
						|| (this.getCuAddress4txN() != null && castOther.getCuAddress4txN() != null
								&& this.getCuAddress4txN().equals(castOther.getCuAddress4txN())))
				&& ((this.getCuStateIdN() == castOther.getCuStateIdN()) || (this.getCuStateIdN() != null
						&& castOther.getCuStateIdN() != null && this.getCuStateIdN().equals(castOther.getCuStateIdN())))
				&& ((this.getCuPostcodeTxN() == castOther.getCuPostcodeTxN())
						|| (this.getCuPostcodeTxN() != null && castOther.getCuPostcodeTxN() != null
								&& this.getCuPostcodeTxN().equals(castOther.getCuPostcodeTxN())))
				&& ((this.getCuCountryIdN() == castOther.getCuCountryIdN())
						|| (this.getCuCountryIdN() != null && castOther.getCuCountryIdN() != null
								&& this.getCuCountryIdN().equals(castOther.getCuCountryIdN())))
				&& ((this.getCuCompanyIdN() == castOther.getCuCompanyIdN())
						|| (this.getCuCompanyIdN() != null && castOther.getCuCompanyIdN() != null
								&& this.getCuCompanyIdN().equals(castOther.getCuCompanyIdN())))
				&& ((this.getCuCompanyTxN() == castOther.getCuCompanyTxN())
						|| (this.getCuCompanyTxN() != null && castOther.getCuCompanyTxN() != null
								&& this.getCuCompanyTxN().equals(castOther.getCuCompanyTxN())))
				&& ((this.getCuWaddress1txN() == castOther.getCuWaddress1txN())
						|| (this.getCuWaddress1txN() != null && castOther.getCuWaddress1txN() != null
								&& this.getCuWaddress1txN().equals(castOther.getCuWaddress1txN())))
				&& ((this.getCuWaddress2txN() == castOther.getCuWaddress2txN())
						|| (this.getCuWaddress2txN() != null && castOther.getCuWaddress2txN() != null
								&& this.getCuWaddress2txN().equals(castOther.getCuWaddress2txN())))
				&& ((this.getCuWaddress3txN() == castOther.getCuWaddress3txN())
						|| (this.getCuWaddress3txN() != null && castOther.getCuWaddress3txN() != null
								&& this.getCuWaddress3txN().equals(castOther.getCuWaddress3txN())))
				&& ((this.getCuWaddress4txN() == castOther.getCuWaddress4txN())
						|| (this.getCuWaddress4txN() != null && castOther.getCuWaddress4txN() != null
								&& this.getCuWaddress4txN().equals(castOther.getCuWaddress4txN())))
				&& ((this.getCuWstateIdN() == castOther.getCuWstateIdN())
						|| (this.getCuWstateIdN() != null && castOther.getCuWstateIdN() != null
								&& this.getCuWstateIdN().equals(castOther.getCuWstateIdN())))
				&& ((this.getCuWpostcodeTxN() == castOther.getCuWpostcodeTxN())
						|| (this.getCuWpostcodeTxN() != null && castOther.getCuWpostcodeTxN() != null
								&& this.getCuWpostcodeTxN().equals(castOther.getCuWpostcodeTxN())))
				&& ((this.getCuWcountryIdN() == castOther.getCuWcountryIdN())
						|| (this.getCuWcountryIdN() != null && castOther.getCuWcountryIdN() != null
								&& this.getCuWcountryIdN().equals(castOther.getCuWcountryIdN())))
				&& ((this.getCuLaddress1txN() == castOther.getCuLaddress1txN())
						|| (this.getCuLaddress1txN() != null && castOther.getCuLaddress1txN() != null
								&& this.getCuLaddress1txN().equals(castOther.getCuLaddress1txN())))
				&& ((this.getCuLaddress2txN() == castOther.getCuLaddress2txN())
						|| (this.getCuLaddress2txN() != null && castOther.getCuLaddress2txN() != null
								&& this.getCuLaddress2txN().equals(castOther.getCuLaddress2txN())))
				&& ((this.getCuLaddress3txN() == castOther.getCuLaddress3txN())
						|| (this.getCuLaddress3txN() != null && castOther.getCuLaddress3txN() != null
								&& this.getCuLaddress3txN().equals(castOther.getCuLaddress3txN())))
				&& ((this.getCuLaddress4txN() == castOther.getCuLaddress4txN())
						|| (this.getCuLaddress4txN() != null && castOther.getCuLaddress4txN() != null
								&& this.getCuLaddress4txN().equals(castOther.getCuLaddress4txN())))
				&& ((this.getCuLpostcodeTxN() == castOther.getCuLpostcodeTxN())
						|| (this.getCuLpostcodeTxN() != null && castOther.getCuLpostcodeTxN() != null
								&& this.getCuLpostcodeTxN().equals(castOther.getCuLpostcodeTxN())))
				&& ((this.getCuTelLocalTxN() == castOther.getCuTelLocalTxN())
						|| (this.getCuTelLocalTxN() != null && castOther.getCuTelLocalTxN() != null
								&& this.getCuTelLocalTxN().equals(castOther.getCuTelLocalTxN())))
				&& ((this.getCuTelHomeTxN() == castOther.getCuTelHomeTxN())
						|| (this.getCuTelHomeTxN() != null && castOther.getCuTelHomeTxN() != null
								&& this.getCuTelHomeTxN().equals(castOther.getCuTelHomeTxN())))
				&& ((this.getCuTelWorkTxN() == castOther.getCuTelWorkTxN())
						|| (this.getCuTelWorkTxN() != null && castOther.getCuTelWorkTxN() != null
								&& this.getCuTelWorkTxN().equals(castOther.getCuTelWorkTxN())))
				&& ((this.getCuTelMobileTxN() == castOther.getCuTelMobileTxN())
						|| (this.getCuTelMobileTxN() != null && castOther.getCuTelMobileTxN() != null
								&& this.getCuTelMobileTxN().equals(castOther.getCuTelMobileTxN())))
				&& ((this.getCuFaxTxN() == castOther.getCuFaxTxN()) || (this.getCuFaxTxN() != null
						&& castOther.getCuFaxTxN() != null && this.getCuFaxTxN().equals(castOther.getCuFaxTxN())))
				&& ((this.getCuEmailTxN() == castOther.getCuEmailTxN()) || (this.getCuEmailTxN() != null
						&& castOther.getCuEmailTxN() != null && this.getCuEmailTxN().equals(castOther.getCuEmailTxN())))
				&& ((this.getCuPagerTxN() == castOther.getCuPagerTxN()) || (this.getCuPagerTxN() != null
						&& castOther.getCuPagerTxN() != null && this.getCuPagerTxN().equals(castOther.getCuPagerTxN())))
				&& ((this.getCuFirstLanguageIdN() == castOther.getCuFirstLanguageIdN())
						|| (this.getCuFirstLanguageIdN() != null && castOther.getCuFirstLanguageIdN() != null
								&& this.getCuFirstLanguageIdN().equals(castOther.getCuFirstLanguageIdN())))
				&& ((this.getCuNoknameTxN() == castOther.getCuNoknameTxN())
						|| (this.getCuNoknameTxN() != null && castOther.getCuNoknameTxN() != null
								&& this.getCuNoknameTxN().equals(castOther.getCuNoknameTxN())))
				&& ((this.getCuNokrelationshipTxN() == castOther.getCuNokrelationshipTxN())
						|| (this.getCuNokrelationshipTxN() != null && castOther.getCuNokrelationshipTxN() != null
								&& this.getCuNokrelationshipTxN().equals(castOther.getCuNokrelationshipTxN())))
				&& ((this.getCuNokaddress1txN() == castOther.getCuNokaddress1txN())
						|| (this.getCuNokaddress1txN() != null && castOther.getCuNokaddress1txN() != null
								&& this.getCuNokaddress1txN().equals(castOther.getCuNokaddress1txN())))
				&& ((this.getCuNokaddress2txN() == castOther.getCuNokaddress2txN())
						|| (this.getCuNokaddress2txN() != null && castOther.getCuNokaddress2txN() != null
								&& this.getCuNokaddress2txN().equals(castOther.getCuNokaddress2txN())))
				&& ((this.getCuNokaddress3txN() == castOther.getCuNokaddress3txN())
						|| (this.getCuNokaddress3txN() != null && castOther.getCuNokaddress3txN() != null
								&& this.getCuNokaddress3txN().equals(castOther.getCuNokaddress3txN())))
				&& ((this.getCuNokaddress4txN() == castOther.getCuNokaddress4txN())
						|| (this.getCuNokaddress4txN() != null && castOther.getCuNokaddress4txN() != null
								&& this.getCuNokaddress4txN().equals(castOther.getCuNokaddress4txN())))
				&& ((this.getCuNokpostcodeTxN() == castOther.getCuNokpostcodeTxN())
						|| (this.getCuNokpostcodeTxN() != null && castOther.getCuNokpostcodeTxN() != null
								&& this.getCuNokpostcodeTxN().equals(castOther.getCuNokpostcodeTxN())))
				&& ((this.getCuNoktelTxN() == castOther.getCuNoktelTxN())
						|| (this.getCuNoktelTxN() != null && castOther.getCuNoktelTxN() != null
								&& this.getCuNoktelTxN().equals(castOther.getCuNoktelTxN())))
				&& ((this.getCuImagePathTxN() == castOther.getCuImagePathTxN())
						|| (this.getCuImagePathTxN() != null && castOther.getCuImagePathTxN() != null
								&& this.getCuImagePathTxN().equals(castOther.getCuImagePathTxN())))
				&& ((this.getCuNotesTxN() == castOther.getCuNotesTxN()) || (this.getCuNotesTxN() != null
						&& castOther.getCuNotesTxN() != null && this.getCuNotesTxN().equals(castOther.getCuNotesTxN())))
				&& (this.isCuDoctorsReportRequiredBl() == castOther.isCuDoctorsReportRequiredBl())
				&& (this.isCuDoctorsReportReceivedBl() == castOther.isCuDoctorsReportReceivedBl())
				&& ((this.getCuSuggestionTxN() == castOther.getCuSuggestionTxN())
						|| (this.getCuSuggestionTxN() != null && castOther.getCuSuggestionTxN() != null
								&& this.getCuSuggestionTxN().equals(castOther.getCuSuggestionTxN())))
				&& (this.isCuUnavailableBl() == castOther.isCuUnavailableBl())
				&& ((this.getCuLastUpdatedDate() == castOther.getCuLastUpdatedDate())
						|| (this.getCuLastUpdatedDate() != null && castOther.getCuLastUpdatedDate() != null
								&& this.getCuLastUpdatedDate().equals(castOther.getCuLastUpdatedDate())))
				&& ((this.getCuPassportNoTxN() == castOther.getCuPassportNoTxN())
						|| (this.getCuPassportNoTxN() != null && castOther.getCuPassportNoTxN() != null
								&& this.getCuPassportNoTxN().equals(castOther.getCuPassportNoTxN())))
				&& ((this.getCuFrequentFlyerTxN() == castOther.getCuFrequentFlyerTxN())
						|| (this.getCuFrequentFlyerTxN() != null && castOther.getCuFrequentFlyerTxN() != null
								&& this.getCuFrequentFlyerTxN().equals(castOther.getCuFrequentFlyerTxN())))
				&& ((this.getCuSsntxN() == castOther.getCuSsntxN()) || (this.getCuSsntxN() != null
						&& castOther.getCuSsntxN() != null && this.getCuSsntxN().equals(castOther.getCuSsntxN())))
				&& (this.getCuStatusId() == castOther.getCuStatusId())
				&& ((this.getCuPadikeyTxN() == castOther.getCuPadikeyTxN())
						|| (this.getCuPadikeyTxN() != null && castOther.getCuPadikeyTxN() != null
								&& this.getCuPadikeyTxN().equals(castOther.getCuPadikeyTxN())))
				&& (this.isCuCommissionableBl() == castOther.isCuCommissionableBl())
				&& ((this.getCuLastPurchaseDate() == castOther.getCuLastPurchaseDate())
						|| (this.getCuLastPurchaseDate() != null && castOther.getCuLastPurchaseDate() != null
								&& this.getCuLastPurchaseDate().equals(castOther.getCuLastPurchaseDate())))
				&& (this.getCuCreditMn() == castOther.getCuCreditMn())
				&& (this.getCuCreditLimitMn() == castOther.getCuCreditLimitMn())
				&& ((this.getCuCreationDate() == castOther.getCuCreationDate())
						|| (this.getCuCreationDate() != null && castOther.getCuCreationDate() != null
								&& this.getCuCreationDate().equals(castOther.getCuCreationDate())))
				&& ((this.getCuUserDefined1txN() == castOther.getCuUserDefined1txN())
						|| (this.getCuUserDefined1txN() != null && castOther.getCuUserDefined1txN() != null
								&& this.getCuUserDefined1txN().equals(castOther.getCuUserDefined1txN())))
				&& ((this.getCuUserDefined2txN() == castOther.getCuUserDefined2txN())
						|| (this.getCuUserDefined2txN() != null && castOther.getCuUserDefined2txN() != null
								&& this.getCuUserDefined2txN().equals(castOther.getCuUserDefined2txN())))
				&& ((this.getCuUserDefined3txN() == castOther.getCuUserDefined3txN())
						|| (this.getCuUserDefined3txN() != null && castOther.getCuUserDefined3txN() != null
								&& this.getCuUserDefined3txN().equals(castOther.getCuUserDefined3txN())))
				&& ((this.getCuUserNameTxN() == castOther.getCuUserNameTxN())
						|| (this.getCuUserNameTxN() != null && castOther.getCuUserNameTxN() != null
								&& this.getCuUserNameTxN().equals(castOther.getCuUserNameTxN())))
				&& ((this.getCuPasswordTxN() == castOther.getCuPasswordTxN())
						|| (this.getCuPasswordTxN() != null && castOther.getCuPasswordTxN() != null
								&& this.getCuPasswordTxN().equals(castOther.getCuPasswordTxN())))
				&& ((this.getCuNoOfDivesInN() == castOther.getCuNoOfDivesInN())
						|| (this.getCuNoOfDivesInN() != null && castOther.getCuNoOfDivesInN() != null
								&& this.getCuNoOfDivesInN().equals(castOther.getCuNoOfDivesInN())))
				&& ((this.getCuLastDiveDateN() == castOther.getCuLastDiveDateN())
						|| (this.getCuLastDiveDateN() != null && castOther.getCuLastDiveDateN() != null
								&& this.getCuLastDiveDateN().equals(castOther.getCuLastDiveDateN())))
				&& (this.isCuCardSeenBl() == castOther.isCuCardSeenBl())
				&& ((this.getCuHeightFlN() == castOther.getCuHeightFlN())
						|| (this.getCuHeightFlN() != null && castOther.getCuHeightFlN() != null
								&& this.getCuHeightFlN().equals(castOther.getCuHeightFlN())))
				&& ((this.getCuWeightFlN() == castOther.getCuWeightFlN())
						|| (this.getCuWeightFlN() != null && castOther.getCuWeightFlN() != null
								&& this.getCuWeightFlN().equals(castOther.getCuWeightFlN())))
				&& ((this.getCuInsuranceNoTxN() == castOther.getCuInsuranceNoTxN())
						|| (this.getCuInsuranceNoTxN() != null && castOther.getCuInsuranceNoTxN() != null
								&& this.getCuInsuranceNoTxN().equals(castOther.getCuInsuranceNoTxN())))
				&& ((this.getCuInsuranceCoTxN() == castOther.getCuInsuranceCoTxN())
						|| (this.getCuInsuranceCoTxN() != null && castOther.getCuInsuranceCoTxN() != null
								&& this.getCuInsuranceCoTxN().equals(castOther.getCuInsuranceCoTxN())))
				&& ((this.getCuShoeSizeFlN() == castOther.getCuShoeSizeFlN())
						|| (this.getCuShoeSizeFlN() != null && castOther.getCuShoeSizeFlN() != null
								&& this.getCuShoeSizeFlN().equals(castOther.getCuShoeSizeFlN())))
				&& ((this.getCuSkypeNameTxN() == castOther.getCuSkypeNameTxN())
						|| (this.getCuSkypeNameTxN() != null && castOther.getCuSkypeNameTxN() != null
								&& this.getCuSkypeNameTxN().equals(castOther.getCuSkypeNameTxN())))
				&& ((this.getCuInsuranceDateN() == castOther.getCuInsuranceDateN())
						|| (this.getCuInsuranceDateN() != null && castOther.getCuInsuranceDateN() != null
								&& this.getCuInsuranceDateN().equals(castOther.getCuInsuranceDateN())))
				&& ((this.getCuDoctorsReportDateN() == castOther.getCuDoctorsReportDateN())
						|| (this.getCuDoctorsReportDateN() != null && castOther.getCuDoctorsReportDateN() != null
								&& this.getCuDoctorsReportDateN().equals(castOther.getCuDoctorsReportDateN())))
				&& ((this.getCuVerifyGuid() == castOther.getCuVerifyGuid())
						|| (this.getCuVerifyGuid() != null && castOther.getCuVerifyGuid() != null
								&& this.getCuVerifyGuid().equals(castOther.getCuVerifyGuid())))
				&& ((this.getCuBounceCountInN() == castOther.getCuBounceCountInN())
						|| (this.getCuBounceCountInN() != null && castOther.getCuBounceCountInN() != null
								&& this.getCuBounceCountInN().equals(castOther.getCuBounceCountInN())))
				&& ((this.getCuStoreNoTxN() == castOther.getCuStoreNoTxN())
						|| (this.getCuStoreNoTxN() != null && castOther.getCuStoreNoTxN() != null
								&& this.getCuStoreNoTxN().equals(castOther.getCuStoreNoTxN())))
				&& ((this.getCuIsAnonymousBlN() == castOther.getCuIsAnonymousBlN())
						|| (this.getCuIsAnonymousBlN() != null && castOther.getCuIsAnonymousBlN() != null
								&& this.getCuIsAnonymousBlN().equals(castOther.getCuIsAnonymousBlN())))
				&& ((this.getCuLastActivityDateN() == castOther.getCuLastActivityDateN())
						|| (this.getCuLastActivityDateN() != null && castOther.getCuLastActivityDateN() != null
								&& this.getCuLastActivityDateN().equals(castOther.getCuLastActivityDateN())))
				&& (this.isCuCreditRiskBl() == castOther.isCuCreditRiskBl())
				&& ((this.getCuAccManagerIdN() == castOther.getCuAccManagerIdN())
						|| (this.getCuAccManagerIdN() != null && castOther.getCuAccManagerIdN() != null
								&& this.getCuAccManagerIdN().equals(castOther.getCuAccManagerIdN())))
				&& ((this.getCuSecretQuestionTxN() == castOther.getCuSecretQuestionTxN())
						|| (this.getCuSecretQuestionTxN() != null && castOther.getCuSecretQuestionTxN() != null
								&& this.getCuSecretQuestionTxN().equals(castOther.getCuSecretQuestionTxN())))
				&& ((this.getCuSecretAnswerTxN() == castOther.getCuSecretAnswerTxN())
						|| (this.getCuSecretAnswerTxN() != null && castOther.getCuSecretAnswerTxN() != null
								&& this.getCuSecretAnswerTxN().equals(castOther.getCuSecretAnswerTxN())))
				&& (this.isCuIsCustomerCompletlyRegisteredBl() == castOther.isCuIsCustomerCompletlyRegisteredBl())
				&& ((this.getCuCustNumberTxN() == castOther.getCuCustNumberTxN())
						|| (this.getCuCustNumberTxN() != null && castOther.getCuCustNumberTxN() != null
								&& this.getCuCustNumberTxN().equals(castOther.getCuCustNumberTxN())))
				&& ((this.getCuSwipeTxN() == castOther.getCuSwipeTxN()) || (this.getCuSwipeTxN() != null
						&& castOther.getCuSwipeTxN() != null && this.getCuSwipeTxN().equals(castOther.getCuSwipeTxN())))
				&& (this.isCuRequiredBl() == castOther.isCuRequiredBl())
				&& (this.isCuPadimailingsBl() == castOther.isCuPadimailingsBl())
				&& (this.isCu3rdPartyMailingsBl() == castOther.isCu3rdPartyMailingsBl())
				&& ((this.getCuScubaTribeIdN() == castOther.getCuScubaTribeIdN())
						|| (this.getCuScubaTribeIdN() != null && castOther.getCuScubaTribeIdN() != null
								&& this.getCuScubaTribeIdN().equals(castOther.getCuScubaTribeIdN())))
				&& ((this.getCuScubaTribeSentDate() == castOther.getCuScubaTribeSentDate())
						|| (this.getCuScubaTribeSentDate() != null && castOther.getCuScubaTribeSentDate() != null
								&& this.getCuScubaTribeSentDate().equals(castOther.getCuScubaTribeSentDate())))
				&& ((this.getCuScubaTribeCodeTxN() == castOther.getCuScubaTribeCodeTxN())
						|| (this.getCuScubaTribeCodeTxN() != null && castOther.getCuScubaTribeCodeTxN() != null
								&& this.getCuScubaTribeCodeTxN().equals(castOther.getCuScubaTribeCodeTxN())))
				&& ((this.getCuPadiidN() == castOther.getCuPadiidN()) || (this.getCuPadiidN() != null
						&& castOther.getCuPadiidN() != null && this.getCuPadiidN().equals(castOther.getCuPadiidN())))
				&& ((this.getCuDataSourceTxN() == castOther.getCuDataSourceTxN())
						|| (this.getCuDataSourceTxN() != null && castOther.getCuDataSourceTxN() != null
								&& this.getCuDataSourceTxN().equals(castOther.getCuDataSourceTxN())))
				&& ((this.getCuInitialCatalogTxN() == castOther.getCuInitialCatalogTxN())
						|| (this.getCuInitialCatalogTxN() != null && castOther.getCuInitialCatalogTxN() != null
								&& this.getCuInitialCatalogTxN().equals(castOther.getCuInitialCatalogTxN())))
				&& ((this.getCuDbuserIdtxN() == castOther.getCuDbuserIdtxN())
						|| (this.getCuDbuserIdtxN() != null && castOther.getCuDbuserIdtxN() != null
								&& this.getCuDbuserIdtxN().equals(castOther.getCuDbuserIdtxN())))
				&& ((this.getCuDbpasswordTxN() == castOther.getCuDbpasswordTxN())
						|| (this.getCuDbpasswordTxN() != null && castOther.getCuDbpasswordTxN() != null
								&& this.getCuDbpasswordTxN().equals(castOther.getCuDbpasswordTxN())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCuCustId();
		result = 37 * result + this.getCuStoreId();
		result = 37 * result + (getCuFirstNameTx() == null ? 0 : this.getCuFirstNameTx().hashCode());
		result = 37 * result + (getCuMiddleInitialTxN() == null ? 0 : this.getCuMiddleInitialTxN().hashCode());
		result = 37 * result + (getCuLastNameTx() == null ? 0 : this.getCuLastNameTx().hashCode());
		result = 37 * result + (getCuKnownAsTxN() == null ? 0 : this.getCuKnownAsTxN().hashCode());
		result = 37 * result + (getCuOccupationTxN() == null ? 0 : this.getCuOccupationTxN().hashCode());
		result = 37 * result + (getCuBirthDateN() == null ? 0 : this.getCuBirthDateN().hashCode());
		result = 37 * result + (getCuSexIdN() == null ? 0 : this.getCuSexIdN().hashCode());
		result = 37 * result + (getCuMaritalStatusIdN() == null ? 0 : this.getCuMaritalStatusIdN().hashCode());
		result = 37 * result + (getCuSourceIdN() == null ? 0 : this.getCuSourceIdN().hashCode());
		result = 37 * result + (getCuAddress1txN() == null ? 0 : this.getCuAddress1txN().hashCode());
		result = 37 * result + (getCuAddress2txN() == null ? 0 : this.getCuAddress2txN().hashCode());
		result = 37 * result + (getCuAddress3txN() == null ? 0 : this.getCuAddress3txN().hashCode());
		result = 37 * result + (getCuAddress4txN() == null ? 0 : this.getCuAddress4txN().hashCode());
		result = 37 * result + (getCuStateIdN() == null ? 0 : this.getCuStateIdN().hashCode());
		result = 37 * result + (getCuPostcodeTxN() == null ? 0 : this.getCuPostcodeTxN().hashCode());
		result = 37 * result + (getCuCountryIdN() == null ? 0 : this.getCuCountryIdN().hashCode());
		result = 37 * result + (getCuCompanyIdN() == null ? 0 : this.getCuCompanyIdN().hashCode());
		result = 37 * result + (getCuCompanyTxN() == null ? 0 : this.getCuCompanyTxN().hashCode());
		result = 37 * result + (getCuWaddress1txN() == null ? 0 : this.getCuWaddress1txN().hashCode());
		result = 37 * result + (getCuWaddress2txN() == null ? 0 : this.getCuWaddress2txN().hashCode());
		result = 37 * result + (getCuWaddress3txN() == null ? 0 : this.getCuWaddress3txN().hashCode());
		result = 37 * result + (getCuWaddress4txN() == null ? 0 : this.getCuWaddress4txN().hashCode());
		result = 37 * result + (getCuWstateIdN() == null ? 0 : this.getCuWstateIdN().hashCode());
		result = 37 * result + (getCuWpostcodeTxN() == null ? 0 : this.getCuWpostcodeTxN().hashCode());
		result = 37 * result + (getCuWcountryIdN() == null ? 0 : this.getCuWcountryIdN().hashCode());
		result = 37 * result + (getCuLaddress1txN() == null ? 0 : this.getCuLaddress1txN().hashCode());
		result = 37 * result + (getCuLaddress2txN() == null ? 0 : this.getCuLaddress2txN().hashCode());
		result = 37 * result + (getCuLaddress3txN() == null ? 0 : this.getCuLaddress3txN().hashCode());
		result = 37 * result + (getCuLaddress4txN() == null ? 0 : this.getCuLaddress4txN().hashCode());
		result = 37 * result + (getCuLpostcodeTxN() == null ? 0 : this.getCuLpostcodeTxN().hashCode());
		result = 37 * result + (getCuTelLocalTxN() == null ? 0 : this.getCuTelLocalTxN().hashCode());
		result = 37 * result + (getCuTelHomeTxN() == null ? 0 : this.getCuTelHomeTxN().hashCode());
		result = 37 * result + (getCuTelWorkTxN() == null ? 0 : this.getCuTelWorkTxN().hashCode());
		result = 37 * result + (getCuTelMobileTxN() == null ? 0 : this.getCuTelMobileTxN().hashCode());
		result = 37 * result + (getCuFaxTxN() == null ? 0 : this.getCuFaxTxN().hashCode());
		result = 37 * result + (getCuEmailTxN() == null ? 0 : this.getCuEmailTxN().hashCode());
		result = 37 * result + (getCuPagerTxN() == null ? 0 : this.getCuPagerTxN().hashCode());
		result = 37 * result + (getCuFirstLanguageIdN() == null ? 0 : this.getCuFirstLanguageIdN().hashCode());
		result = 37 * result + (getCuNoknameTxN() == null ? 0 : this.getCuNoknameTxN().hashCode());
		result = 37 * result + (getCuNokrelationshipTxN() == null ? 0 : this.getCuNokrelationshipTxN().hashCode());
		result = 37 * result + (getCuNokaddress1txN() == null ? 0 : this.getCuNokaddress1txN().hashCode());
		result = 37 * result + (getCuNokaddress2txN() == null ? 0 : this.getCuNokaddress2txN().hashCode());
		result = 37 * result + (getCuNokaddress3txN() == null ? 0 : this.getCuNokaddress3txN().hashCode());
		result = 37 * result + (getCuNokaddress4txN() == null ? 0 : this.getCuNokaddress4txN().hashCode());
		result = 37 * result + (getCuNokpostcodeTxN() == null ? 0 : this.getCuNokpostcodeTxN().hashCode());
		result = 37 * result + (getCuNoktelTxN() == null ? 0 : this.getCuNoktelTxN().hashCode());
		result = 37 * result + (getCuImagePathTxN() == null ? 0 : this.getCuImagePathTxN().hashCode());
		result = 37 * result + (getCuNotesTxN() == null ? 0 : this.getCuNotesTxN().hashCode());
		result = 37 * result + (this.isCuDoctorsReportRequiredBl() ? 1 : 0);
		result = 37 * result + (this.isCuDoctorsReportReceivedBl() ? 1 : 0);
		result = 37 * result + (getCuSuggestionTxN() == null ? 0 : this.getCuSuggestionTxN().hashCode());
		result = 37 * result + (this.isCuUnavailableBl() ? 1 : 0);
		result = 37 * result + (getCuLastUpdatedDate() == null ? 0 : this.getCuLastUpdatedDate().hashCode());
		result = 37 * result + (getCuPassportNoTxN() == null ? 0 : this.getCuPassportNoTxN().hashCode());
		result = 37 * result + (getCuFrequentFlyerTxN() == null ? 0 : this.getCuFrequentFlyerTxN().hashCode());
		result = 37 * result + (getCuSsntxN() == null ? 0 : this.getCuSsntxN().hashCode());
		result = 37 * result + this.getCuStatusId();
		result = 37 * result + (getCuPadikeyTxN() == null ? 0 : this.getCuPadikeyTxN().hashCode());
		result = 37 * result + (this.isCuCommissionableBl() ? 1 : 0);
		result = 37 * result + (getCuLastPurchaseDate() == null ? 0 : this.getCuLastPurchaseDate().hashCode());
		result = 37 * result + (int) this.getCuCreditMn();
		result = 37 * result + (int) this.getCuCreditLimitMn();
		result = 37 * result + (getCuCreationDate() == null ? 0 : this.getCuCreationDate().hashCode());
		result = 37 * result + (getCuUserDefined1txN() == null ? 0 : this.getCuUserDefined1txN().hashCode());
		result = 37 * result + (getCuUserDefined2txN() == null ? 0 : this.getCuUserDefined2txN().hashCode());
		result = 37 * result + (getCuUserDefined3txN() == null ? 0 : this.getCuUserDefined3txN().hashCode());
		result = 37 * result + (getCuUserNameTxN() == null ? 0 : this.getCuUserNameTxN().hashCode());
		result = 37 * result + (getCuPasswordTxN() == null ? 0 : this.getCuPasswordTxN().hashCode());
		result = 37 * result + (getCuNoOfDivesInN() == null ? 0 : this.getCuNoOfDivesInN().hashCode());
		result = 37 * result + (getCuLastDiveDateN() == null ? 0 : this.getCuLastDiveDateN().hashCode());
		result = 37 * result + (this.isCuCardSeenBl() ? 1 : 0);
		result = 37 * result + (getCuHeightFlN() == null ? 0 : this.getCuHeightFlN().hashCode());
		result = 37 * result + (getCuWeightFlN() == null ? 0 : this.getCuWeightFlN().hashCode());
		result = 37 * result + (getCuInsuranceNoTxN() == null ? 0 : this.getCuInsuranceNoTxN().hashCode());
		result = 37 * result + (getCuInsuranceCoTxN() == null ? 0 : this.getCuInsuranceCoTxN().hashCode());
		result = 37 * result + (getCuShoeSizeFlN() == null ? 0 : this.getCuShoeSizeFlN().hashCode());
		result = 37 * result + (getCuSkypeNameTxN() == null ? 0 : this.getCuSkypeNameTxN().hashCode());
		result = 37 * result + (getCuInsuranceDateN() == null ? 0 : this.getCuInsuranceDateN().hashCode());
		result = 37 * result + (getCuDoctorsReportDateN() == null ? 0 : this.getCuDoctorsReportDateN().hashCode());
		result = 37 * result + (getCuVerifyGuid() == null ? 0 : this.getCuVerifyGuid().hashCode());
		result = 37 * result + (getCuBounceCountInN() == null ? 0 : this.getCuBounceCountInN().hashCode());
		result = 37 * result + (getCuStoreNoTxN() == null ? 0 : this.getCuStoreNoTxN().hashCode());
		result = 37 * result + (getCuIsAnonymousBlN() == null ? 0 : this.getCuIsAnonymousBlN().hashCode());
		result = 37 * result + (getCuLastActivityDateN() == null ? 0 : this.getCuLastActivityDateN().hashCode());
		result = 37 * result + (this.isCuCreditRiskBl() ? 1 : 0);
		result = 37 * result + (getCuAccManagerIdN() == null ? 0 : this.getCuAccManagerIdN().hashCode());
		result = 37 * result + (getCuSecretQuestionTxN() == null ? 0 : this.getCuSecretQuestionTxN().hashCode());
		result = 37 * result + (getCuSecretAnswerTxN() == null ? 0 : this.getCuSecretAnswerTxN().hashCode());
		result = 37 * result + (this.isCuIsCustomerCompletlyRegisteredBl() ? 1 : 0);
		result = 37 * result + (getCuCustNumberTxN() == null ? 0 : this.getCuCustNumberTxN().hashCode());
		result = 37 * result + (getCuSwipeTxN() == null ? 0 : this.getCuSwipeTxN().hashCode());
		result = 37 * result + (this.isCuRequiredBl() ? 1 : 0);
		result = 37 * result + (this.isCuPadimailingsBl() ? 1 : 0);
		result = 37 * result + (this.isCu3rdPartyMailingsBl() ? 1 : 0);
		result = 37 * result + (getCuScubaTribeIdN() == null ? 0 : this.getCuScubaTribeIdN().hashCode());
		result = 37 * result + (getCuScubaTribeSentDate() == null ? 0 : this.getCuScubaTribeSentDate().hashCode());
		result = 37 * result + (getCuScubaTribeCodeTxN() == null ? 0 : this.getCuScubaTribeCodeTxN().hashCode());
		result = 37 * result + (getCuPadiidN() == null ? 0 : this.getCuPadiidN().hashCode());
		result = 37 * result + (getCuDataSourceTxN() == null ? 0 : this.getCuDataSourceTxN().hashCode());
		result = 37 * result + (getCuInitialCatalogTxN() == null ? 0 : this.getCuInitialCatalogTxN().hashCode());
		result = 37 * result + (getCuDbuserIdtxN() == null ? 0 : this.getCuDbuserIdtxN().hashCode());
		result = 37 * result + (getCuDbpasswordTxN() == null ? 0 : this.getCuDbpasswordTxN().hashCode());
		return result;
	}

}
