package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * D01DtDestination generated by hbm2java
 */
@Entity
@Table(name = "d01_DtDestination")
public class D01DtDestination implements java.io.Serializable {

	private D01DtDestinationId id;

	public D01DtDestination() {
	}

	public D01DtDestination(D01DtDestinationId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dtDestinationId", column = @Column(name = "DtDestinationID", nullable = false)),
			@AttributeOverride(name = "dtDestinationTx", column = @Column(name = "DtDestinationTx", nullable = false)),
			@AttributeOverride(name = "dtUnavailableBl", column = @Column(name = "DtUnavailableBl", nullable = false)),
			@AttributeOverride(name = "dtVideoTxN", column = @Column(name = "DtVideoTx_N")),
			@AttributeOverride(name = "dtMinNoIn", column = @Column(name = "DtMinNoIn", nullable = false)),
			@AttributeOverride(name = "dtMaxNoIn", column = @Column(name = "DtMaxNoIn", nullable = false)),
			@AttributeOverride(name = "dtLastUpdatedDate", column = @Column(name = "DtLastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "dtRequiredBl", column = @Column(name = "DtRequiredBl", nullable = false)),
			@AttributeOverride(name = "dtCreationDate", column = @Column(name = "DtCreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "dtForeColorIn", column = @Column(name = "DtForeColorIn", nullable = false)),
			@AttributeOverride(name = "dtBackColorIn", column = @Column(name = "DtBackColorIn", nullable = false)),
			@AttributeOverride(name = "dtPrefixTx", column = @Column(name = "DtPrefixTx", nullable = false)),
			@AttributeOverride(name = "dtUrltxN", column = @Column(name = "DtURLTx_N")) })
	public D01DtDestinationId getId() {
		return this.id;
	}

	public void setId(D01DtDestinationId id) {
		this.id = id;
	}

}
