package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * D01EkEmpClockIn generated by hbm2java
 */
@Entity
@Table(name = "d01_EkEmpClockIn")
public class D01EkEmpClockIn implements java.io.Serializable {

	private D01EkEmpClockInId id;

	public D01EkEmpClockIn() {
	}

	public D01EkEmpClockIn(D01EkEmpClockInId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ekEmpClockInId", column = @Column(name = "EkEmpClockInID", nullable = false)),
			@AttributeOverride(name = "ekEmpId", column = @Column(name = "EkEmpID", nullable = false)),
			@AttributeOverride(name = "ekClockInDate", column = @Column(name = "EkClockInDate", nullable = false, length = 23)),
			@AttributeOverride(name = "ekClockOutDateN", column = @Column(name = "EkClockOutDate_N", length = 23)),
			@AttributeOverride(name = "ekPcid", column = @Column(name = "EkPCID", nullable = false)),
			@AttributeOverride(name = "ekCommentsTxN", column = @Column(name = "EkCommentsTx_N")),
			@AttributeOverride(name = "ekStoreId", column = @Column(name = "EkStoreID", nullable = false)),
			@AttributeOverride(name = "ekTaskTypeIdN", column = @Column(name = "EkTaskTypeID_N")) })
	public D01EkEmpClockInId getId() {
		return this.id;
	}

	public void setId(D01EkEmpClockInId id) {
		this.id = id;
	}

}
