package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * D01E3emailAgent generated by hbm2java
 */
@Entity
@Table(name = "d01_E3EmailAgent")
public class D01E3emailAgent implements java.io.Serializable {

	private D01E3emailAgentId id;

	public D01E3emailAgent() {
	}

	public D01E3emailAgent(D01E3emailAgentId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "e3emailAgentId", column = @Column(name = "E3EmailAgentID", nullable = false)),
			@AttributeOverride(name = "e3eventTx", column = @Column(name = "E3EventTx", nullable = false)),
			@AttributeOverride(name = "e3eventParam1txN", column = @Column(name = "E3EventParam1Tx_N")),
			@AttributeOverride(name = "e3eventParam2txN", column = @Column(name = "E3EventParam2Tx_N")),
			@AttributeOverride(name = "e3sqltx", column = @Column(name = "E3SQLTx", nullable = false)),
			@AttributeOverride(name = "e3outlookFolderTxN", column = @Column(name = "E3OutlookFolderTx_N")),
			@AttributeOverride(name = "e3subjectLineTx", column = @Column(name = "E3SubjectLineTx", nullable = false)),
			@AttributeOverride(name = "e3delayIn", column = @Column(name = "E3DelayIn", nullable = false)),
			@AttributeOverride(name = "e3expiryDaysIn", column = @Column(name = "E3ExpiryDaysIn", nullable = false)),
			@AttributeOverride(name = "e3lastRunDate", column = @Column(name = "E3LastRunDate", nullable = false, length = 23)),
			@AttributeOverride(name = "e3confirmationRequiredBl", column = @Column(name = "E3ConfirmationRequiredBl", nullable = false)),
			@AttributeOverride(name = "e3lastRunStatusTxN", column = @Column(name = "E3LastRunStatusTx_N")),
			@AttributeOverride(name = "e3runLaterIfAgentOffBl", column = @Column(name = "E3RunLaterIfAgentOffBl", nullable = false)),
			@AttributeOverride(name = "e3unavailableBl", column = @Column(name = "E3UnavailableBl", nullable = false)),
			@AttributeOverride(name = "e3onMailingListsTxN", column = @Column(name = "E3OnMailingListsTx_N")),
			@AttributeOverride(name = "e3notOnMailingListsTxN", column = @Column(name = "E3NotOnMailingListsTx_N")),
			@AttributeOverride(name = "e3subQueryTxN", column = @Column(name = "E3SubQueryTx_N")),
			@AttributeOverride(name = "e3priorityIn", column = @Column(name = "E3PriorityIn", nullable = false)),
			@AttributeOverride(name = "e3sendToNewsletterEngineBl", column = @Column(name = "E3SendToNewsletterEngineBl", nullable = false)),
			@AttributeOverride(name = "e3newsletterTemplateTxN", column = @Column(name = "E3NewsletterTemplateTx_N")),
			@AttributeOverride(name = "e3notesTxN", column = @Column(name = "E3NotesTx_N")),
			@AttributeOverride(name = "e3fromAccountTxN", column = @Column(name = "E3FromAccountTx_N")),
			@AttributeOverride(name = "e3storeId", column = @Column(name = "E3StoreID", nullable = false)),
			@AttributeOverride(name = "e3primaryTablesTx", column = @Column(name = "E3PrimaryTablesTx", nullable = false)),
			@AttributeOverride(name = "e3jobTypeId", column = @Column(name = "E3JobTypeID", nullable = false)),
			@AttributeOverride(name = "e3subJobTypeId", column = @Column(name = "E3SubJobTypeID", nullable = false)),
			@AttributeOverride(name = "e3listTxN", column = @Column(name = "E3ListTx_N")),
			@AttributeOverride(name = "e3moveToFolderBl", column = @Column(name = "E3MoveToFolderBl", nullable = false)),
			@AttributeOverride(name = "e3viewTxN", column = @Column(name = "E3ViewTx_N")),
			@AttributeOverride(name = "e3columnsTxN", column = @Column(name = "E3ColumnsTx_N")),
			@AttributeOverride(name = "e3dateColumnTxN", column = @Column(name = "E3DateColumnTx_N")),
			@AttributeOverride(name = "e3datePeriodInN", column = @Column(name = "E3DatePeriodIn_N")),
			@AttributeOverride(name = "e3dateValueInN", column = @Column(name = "E3DateValueIn_N")),
			@AttributeOverride(name = "e3groupIdN", column = @Column(name = "E3GroupID_N")) })
	public D01E3emailAgentId getId() {
		return this.id;
	}

	public void setId(D01E3emailAgentId id) {
		this.id = id;
	}

}
