package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * D01Popo generated by hbm2java
 */
@Entity
@Table(name = "d01_POPO")
public class D01Popo implements java.io.Serializable {

	private D01PopoId id;

	public D01Popo() {
	}

	public D01Popo(D01PopoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "poid", column = @Column(name = "POID", nullable = false)),
			@AttributeOverride(name = "postoreId", column = @Column(name = "POStoreID", nullable = false)),
			@AttributeOverride(name = "pocostCenterId", column = @Column(name = "POCostCenterID", nullable = false)),
			@AttributeOverride(name = "posupplierId", column = @Column(name = "POSupplierID", nullable = false)),
			@AttributeOverride(name = "poshipToStoreId", column = @Column(name = "POShipToStoreID", nullable = false)),
			@AttributeOverride(name = "poshippingInstructionsTxN", column = @Column(name = "POShippingInstructionsTx_N")),
			@AttributeOverride(name = "popaymentTermsTxN", column = @Column(name = "POPaymentTermsTx_N")),
			@AttributeOverride(name = "poempId", column = @Column(name = "POEmpID", nullable = false)),
			@AttributeOverride(name = "posentDateN", column = @Column(name = "POSentDate_N", length = 23)),
			@AttributeOverride(name = "poorderSubTotalMn", column = @Column(name = "POOrderSubTotalMn", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "poorderTaxMn", column = @Column(name = "POOrderTaxMn", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "pocurrencyId", column = @Column(name = "POCurrencyID", nullable = false)),
			@AttributeOverride(name = "poexchangeRateFl", column = @Column(name = "POExchangeRateFl", nullable = false, precision = 24, scale = 0)),
			@AttributeOverride(name = "polastUpdatedDate", column = @Column(name = "POLastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "pocompletedDateN", column = @Column(name = "POCompletedDate_N", length = 23)),
			@AttributeOverride(name = "postatusId", column = @Column(name = "POStatusID", nullable = false)),
			@AttributeOverride(name = "povoidDateN", column = @Column(name = "POVoidDate_N", length = 23)),
			@AttributeOverride(name = "povoidReasonTxN", column = @Column(name = "POVoidReasonTx_N")),
			@AttributeOverride(name = "ponotesTxN", column = @Column(name = "PONotesTx_N")),
			@AttributeOverride(name = "pocreationDate", column = @Column(name = "POCreationDate", nullable = false, length = 23)) })
	public D01PopoId getId() {
		return this.id;
	}

	public void setId(D01PopoId id) {
		this.id = id;
	}

}
