package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * D01PmpaymentMethod generated by hbm2java
 */
@Entity
@Table(name = "d01_PMPaymentMethod")
public class D01PmpaymentMethod implements java.io.Serializable {

	private D01PmpaymentMethodId id;

	public D01PmpaymentMethod() {
	}

	public D01PmpaymentMethod(D01PmpaymentMethodId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "pmpaymentMethodId", column = @Column(name = "PMPaymentMethodID", nullable = false)),
			@AttributeOverride(name = "pmpaymentMethodTx", column = @Column(name = "PMPaymentMethodTx", nullable = false)),
			@AttributeOverride(name = "pmccpromptBl", column = @Column(name = "PMCCPromptBl", nullable = false)),
			@AttributeOverride(name = "pmopenCashDrawerBl", column = @Column(name = "PMOpenCashDrawerBl", nullable = false)),
			@AttributeOverride(name = "pmauthorizationRequiredBl", column = @Column(name = "PMAuthorizationRequiredBl", nullable = false)),
			@AttributeOverride(name = "pmcustomerRequiredBl", column = @Column(name = "PMCustomerRequiredBl", nullable = false)),
			@AttributeOverride(name = "pmidrequiredBl", column = @Column(name = "PMIDRequiredBl", nullable = false)),
			@AttributeOverride(name = "pmchqNoPromptBl", column = @Column(name = "PMChqNoPromptBl", nullable = false)),
			@AttributeOverride(name = "pmchqNoMandatoryBl", column = @Column(name = "PMChqNoMandatoryBl", nullable = false)),
			@AttributeOverride(name = "pmgiftCardPromptBl", column = @Column(name = "PMGiftCardPromptBl", nullable = false)),
			@AttributeOverride(name = "pmunavailableBl", column = @Column(name = "PMUnavailableBl", nullable = false)),
			@AttributeOverride(name = "pmlastUpdatedDate", column = @Column(name = "PMLastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "pmrequiredBl", column = @Column(name = "PMRequiredBl", nullable = false)),
			@AttributeOverride(name = "pmccrequiredOnFileBl", column = @Column(name = "PMCCRequiredOnFileBl", nullable = false)),
			@AttributeOverride(name = "pmglaccountIdN", column = @Column(name = "PMGLAccountID_N")),
			@AttributeOverride(name = "pmccprefixTxN", column = @Column(name = "PMCCPrefixTx_N")),
			@AttributeOverride(name = "pmccallowedLenTxN", column = @Column(name = "PMCCAllowedLenTx_N")),
			@AttributeOverride(name = "pmcreationDate", column = @Column(name = "PMCreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "pmgraphicTxN", column = @Column(name = "PMGraphicTx_N")),
			@AttributeOverride(name = "pmccnoMandatoryBl", column = @Column(name = "PMCCNoMandatoryBl", nullable = false)),
			@AttributeOverride(name = "pmexpDateMandatoryBl", column = @Column(name = "PMExpDateMandatoryBl", nullable = false)),
			@AttributeOverride(name = "pmauthNoMandatoryBl", column = @Column(name = "PMAuthNoMandatoryBl", nullable = false)),
			@AttributeOverride(name = "pmgiftCertPromptBl", column = @Column(name = "PMGiftCertPromptBl", nullable = false)),
			@AttributeOverride(name = "pmvoucherPromptBl", column = @Column(name = "PMVoucherPromptBl", nullable = false)),
			@AttributeOverride(name = "pmaccountPromptBl", column = @Column(name = "PMAccountPromptBl", nullable = false)),
			@AttributeOverride(name = "pminvoiceTextTxN", column = @Column(name = "PMInvoiceTextTx_N")),
			@AttributeOverride(name = "pmtransmitCcbl", column = @Column(name = "PMTransmitCCBl", nullable = false)),
			@AttributeOverride(name = "pmtransmitDcbl", column = @Column(name = "PMTransmitDCBl", nullable = false)),
			@AttributeOverride(name = "pmcreditCardBl", column = @Column(name = "PMCreditCardBl", nullable = false)),
			@AttributeOverride(name = "pmadditionalPrintCopiesIn", column = @Column(name = "PMAdditionalPrintCopiesIn", nullable = false)),
			@AttributeOverride(name = "pmvalidFromAndIssueNoMandatoryBl", column = @Column(name = "PMValidFromAndIssueNoMandatoryBl", nullable = false)),
			@AttributeOverride(name = "pmnonSalesAccountIdN", column = @Column(name = "PMNonSalesAccountID_N")),
			@AttributeOverride(name = "pmsurchargeStockItemIdN", column = @Column(name = "PMSurchargeStockItemID_N")),
			@AttributeOverride(name = "pmsurchargeAmountMnN", column = @Column(name = "PMSurchargeAmountMn_N", precision = 53, scale = 0)),
			@AttributeOverride(name = "pmsurchargePercentFlN", column = @Column(name = "PMSurchargePercentFl_N", precision = 53, scale = 0)),
			@AttributeOverride(name = "pmquickPayBl", column = @Column(name = "PMQuickPayBl", nullable = false)) })
	public D01PmpaymentMethodId getId() {
		return this.id;
	}

	public void setId(D01PmpaymentMethodId id) {
		this.id = id;
	}

}
