package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * D01PaPodeliveryItem generated by hbm2java
 */
@Entity
@Table(name = "d01_PaPODeliveryItem")
public class D01PaPodeliveryItem implements java.io.Serializable {

	private D01PaPodeliveryItemId id;

	public D01PaPodeliveryItem() {
	}

	public D01PaPodeliveryItem(D01PaPodeliveryItemId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "paPodeliveryItemId", column = @Column(name = "PaPODeliveryItemID", nullable = false)),
			@AttributeOverride(name = "paPodeliveryIdN", column = @Column(name = "PaPODeliveryID_N")),
			@AttributeOverride(name = "paStoreId", column = @Column(name = "PaStoreID", nullable = false)),
			@AttributeOverride(name = "paPoitemIdN", column = @Column(name = "PaPOItemID_N")),
			@AttributeOverride(name = "paStockItemId", column = @Column(name = "PaStockItemID", nullable = false)),
			@AttributeOverride(name = "paReceivedDate", column = @Column(name = "PaReceivedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "paQtyReceivedIn", column = @Column(name = "PaQtyReceivedIn", nullable = false)),
			@AttributeOverride(name = "paQtyInStockIn", column = @Column(name = "PaQtyInStockIn", nullable = false)),
			@AttributeOverride(name = "paCostPriceMn", column = @Column(name = "PaCostPriceMn", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "paAccountingPeriodIdN", column = @Column(name = "PaAccountingPeriodID_N")),
			@AttributeOverride(name = "paTransferIdN", column = @Column(name = "PaTransferID_N")) })
	public D01PaPodeliveryItemId getId() {
		return this.id;
	}

	public void setId(D01PaPodeliveryItemId id) {
		this.id = id;
	}

}
