package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * D01StstockType generated by hbm2java
 */
@Entity
@Table(name = "d01_STStockType")
public class D01StstockType implements java.io.Serializable {

	private D01StstockTypeId id;

	public D01StstockType() {
	}

	public D01StstockType(D01StstockTypeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ststockTypeId", column = @Column(name = "STStockTypeID", nullable = false)),
			@AttributeOverride(name = "ststockTypeTx", column = @Column(name = "STStockTypeTx", nullable = false)),
			@AttributeOverride(name = "stprofitCenterId", column = @Column(name = "STProfitCenterID", nullable = false)),
			@AttributeOverride(name = "stprofileBl", column = @Column(name = "STProfileBl", nullable = false)),
			@AttributeOverride(name = "stforRentBl", column = @Column(name = "STForRentBl", nullable = false)),
			@AttributeOverride(name = "stforServiceBl", column = @Column(name = "STForServiceBl", nullable = false)),
			@AttributeOverride(name = "stforServicePartsBl", column = @Column(name = "STForServicePartsBl", nullable = false)),
			@AttributeOverride(name = "stforSaleBl", column = @Column(name = "STForSaleBl", nullable = false)),
			@AttributeOverride(name = "sttrackOwnershipBl", column = @Column(name = "STTrackOwnershipBl", nullable = false)),
			@AttributeOverride(name = "stforChecklistBl", column = @Column(name = "STForChecklistBl", nullable = false)),
			@AttributeOverride(name = "stcustomerRequiredBl", column = @Column(name = "STCustomerRequiredBl", nullable = false)),
			@AttributeOverride(name = "stunavailableBl", column = @Column(name = "STUnavailableBl", nullable = false)),
			@AttributeOverride(name = "stlastUpdatedDate", column = @Column(name = "STLastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "stcommissionRateFl", column = @Column(name = "STCommissionRateFl", nullable = false, precision = 24, scale = 0)),
			@AttributeOverride(name = "stsaleDiscountBandIdN", column = @Column(name = "STSaleDiscountBandID_N")),
			@AttributeOverride(name = "strequiredBl", column = @Column(name = "STRequiredBl", nullable = false)),
			@AttributeOverride(name = "stinvoiceTextTxN", column = @Column(name = "STInvoiceTextTx_N")),
			@AttributeOverride(name = "stservicePeriodIn", column = @Column(name = "STServicePeriodIn", nullable = false)),
			@AttributeOverride(name = "stcreationDate", column = @Column(name = "STCreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "stgiftCertPromptBl", column = @Column(name = "STGiftCertPromptBl", nullable = false)),
			@AttributeOverride(name = "stgiftCardPromptBl", column = @Column(name = "STGiftCardPromptBl", nullable = false)),
			@AttributeOverride(name = "stroomBookingPromptBl", column = @Column(name = "STRoomBookingPromptBl", nullable = false)),
			@AttributeOverride(name = "strebiidN", column = @Column(name = "STREBIID_N")),
			@AttributeOverride(name = "stwebAdminEntryBl", column = @Column(name = "STWebAdminEntryBl", nullable = false)),
			@AttributeOverride(name = "stwebAdminDeletedBl", column = @Column(name = "STWebAdminDeletedBl", nullable = false)),
			@AttributeOverride(name = "sttechnicianActivityBl", column = @Column(name = "STTechnicianActivityBl", nullable = false)),
			@AttributeOverride(name = "stdisplayOrderIn", column = @Column(name = "STDisplayOrderIn", nullable = false)),
			@AttributeOverride(name = "steventDataTypeIdN", column = @Column(name = "STEventDataTypeID_N")),
			@AttributeOverride(name = "stseotagTxN", column = @Column(name = "STSEOTagTx_N")),
			@AttributeOverride(name = "stshowCylinderInfoBl", column = @Column(name = "STShowCylinderInfoBl", nullable = false)),
			@AttributeOverride(name = "stclassNameTxN", column = @Column(name = "STClassNameTx_N", length = 50)),
			@AttributeOverride(name = "steolstockTypeTxN", column = @Column(name = "STEOLStockTypeTx_N")),
			@AttributeOverride(name = "steolheaderId", column = @Column(name = "STEOLHeaderID", nullable = false)),
			@AttributeOverride(name = "stallowPriceUpdatesBl", column = @Column(name = "STAllowPriceUpdatesBl", nullable = false)),
			@AttributeOverride(name = "stqtyBasedDiscountsTxN", column = @Column(name = "STQtyBasedDiscountsTx_N")),
			@AttributeOverride(name = "stallowPaymentSurchargeBl", column = @Column(name = "STAllowPaymentSurchargeBl", nullable = false)) })
	public D01StstockTypeId getId() {
		return this.id;
	}

	public void setId(D01StstockTypeId id) {
		this.id = id;
	}

}
