package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D01SuSupplierId generated by hbm2java
 */
@Embeddable
public class D01SuSupplierId implements java.io.Serializable {

	private int suSupplierId;
	private String suSupplierTx;
	private String suContactTxN;
	private String suSalesmanTxN;
	private String suAddress1txN;
	private String suAddress2txN;
	private String suAddress3txN;
	private String suAddress4txN;
	private String suPostcodeTxN;
	private String suCountryTxN;
	private String suTelephone1txN;
	private String suTelephone2txN;
	private String suFaxTxN;
	private String suEmailTxN;
	private String suWebTxN;
	private boolean suUnavailableBl;
	private Date suLastUpdatedDate;
	private boolean suRequiredBl;
	private Date suCreationDate;
	private String suB2bfnTxN;
	private String suB2bemailTxN;
	private String suContact2txN;
	private String suContact3txN;
	private String suNotesTxN;
	private int suDisplayOrderIn;

	public D01SuSupplierId() {
	}

	public D01SuSupplierId(int suSupplierId, String suSupplierTx, boolean suUnavailableBl, Date suLastUpdatedDate,
			boolean suRequiredBl, Date suCreationDate, int suDisplayOrderIn) {
		this.suSupplierId = suSupplierId;
		this.suSupplierTx = suSupplierTx;
		this.suUnavailableBl = suUnavailableBl;
		this.suLastUpdatedDate = suLastUpdatedDate;
		this.suRequiredBl = suRequiredBl;
		this.suCreationDate = suCreationDate;
		this.suDisplayOrderIn = suDisplayOrderIn;
	}

	public D01SuSupplierId(int suSupplierId, String suSupplierTx, String suContactTxN,
			String suSalesmanTxN, String suAddress1txN, String suAddress2txN,
			String suAddress3txN, String suAddress4txN, String suPostcodeTxN,
			String suCountryTxN, String suTelephone1txN, String suTelephone2txN,
			String suFaxTxN, String suEmailTxN, String suWebTxN, boolean suUnavailableBl,
			Date suLastUpdatedDate, boolean suRequiredBl, Date suCreationDate, String suB2bfnTxN,
			String suB2bemailTxN, String suContact2txN, String suContact3txN, String suNotesTxN,
			int suDisplayOrderIn) {
		this.suSupplierId = suSupplierId;
		this.suSupplierTx = suSupplierTx;
		this.suContactTxN = suContactTxN;
		this.suSalesmanTxN = suSalesmanTxN;
		this.suAddress1txN = suAddress1txN;
		this.suAddress2txN = suAddress2txN;
		this.suAddress3txN = suAddress3txN;
		this.suAddress4txN = suAddress4txN;
		this.suPostcodeTxN = suPostcodeTxN;
		this.suCountryTxN = suCountryTxN;
		this.suTelephone1txN = suTelephone1txN;
		this.suTelephone2txN = suTelephone2txN;
		this.suFaxTxN = suFaxTxN;
		this.suEmailTxN = suEmailTxN;
		this.suWebTxN = suWebTxN;
		this.suUnavailableBl = suUnavailableBl;
		this.suLastUpdatedDate = suLastUpdatedDate;
		this.suRequiredBl = suRequiredBl;
		this.suCreationDate = suCreationDate;
		this.suB2bfnTxN = suB2bfnTxN;
		this.suB2bemailTxN = suB2bemailTxN;
		this.suContact2txN = suContact2txN;
		this.suContact3txN = suContact3txN;
		this.suNotesTxN = suNotesTxN;
		this.suDisplayOrderIn = suDisplayOrderIn;
	}

	@Column(name = "SuSupplierID", nullable = false)
	public int getSuSupplierId() {
		return this.suSupplierId;
	}

	public void setSuSupplierId(int suSupplierId) {
		this.suSupplierId = suSupplierId;
	}

	@Column(name = "SuSupplierTx", nullable = false)
	public String getSuSupplierTx() {
		return this.suSupplierTx;
	}

	public void setSuSupplierTx(String suSupplierTx) {
		this.suSupplierTx = suSupplierTx;
	}

	@Column(name = "SuContactTx_N")
	public String getSuContactTxN() {
		return this.suContactTxN;
	}

	public void setSuContactTxN(String suContactTxN) {
		this.suContactTxN = suContactTxN;
	}

	@Column(name = "SuSalesmanTx_N")
	public String getSuSalesmanTxN() {
		return this.suSalesmanTxN;
	}

	public void setSuSalesmanTxN(String suSalesmanTxN) {
		this.suSalesmanTxN = suSalesmanTxN;
	}

	@Column(name = "SuAddress1Tx_N")
	public String getSuAddress1txN() {
		return this.suAddress1txN;
	}

	public void setSuAddress1txN(String suAddress1txN) {
		this.suAddress1txN = suAddress1txN;
	}

	@Column(name = "SuAddress2Tx_N")
	public String getSuAddress2txN() {
		return this.suAddress2txN;
	}

	public void setSuAddress2txN(String suAddress2txN) {
		this.suAddress2txN = suAddress2txN;
	}

	@Column(name = "SuAddress3Tx_N")
	public String getSuAddress3txN() {
		return this.suAddress3txN;
	}

	public void setSuAddress3txN(String suAddress3txN) {
		this.suAddress3txN = suAddress3txN;
	}

	@Column(name = "SuAddress4Tx_N")
	public String getSuAddress4txN() {
		return this.suAddress4txN;
	}

	public void setSuAddress4txN(String suAddress4txN) {
		this.suAddress4txN = suAddress4txN;
	}

	@Column(name = "SuPostcodeTx_N")
	public String getSuPostcodeTxN() {
		return this.suPostcodeTxN;
	}

	public void setSuPostcodeTxN(String suPostcodeTxN) {
		this.suPostcodeTxN = suPostcodeTxN;
	}

	@Column(name = "SuCountryTx_N")
	public String getSuCountryTxN() {
		return this.suCountryTxN;
	}

	public void setSuCountryTxN(String suCountryTxN) {
		this.suCountryTxN = suCountryTxN;
	}

	@Column(name = "SuTelephone1Tx_N")
	public String getSuTelephone1txN() {
		return this.suTelephone1txN;
	}

	public void setSuTelephone1txN(String suTelephone1txN) {
		this.suTelephone1txN = suTelephone1txN;
	}

	@Column(name = "SuTelephone2Tx_N")
	public String getSuTelephone2txN() {
		return this.suTelephone2txN;
	}

	public void setSuTelephone2txN(String suTelephone2txN) {
		this.suTelephone2txN = suTelephone2txN;
	}

	@Column(name = "SuFaxTx_N")
	public String getSuFaxTxN() {
		return this.suFaxTxN;
	}

	public void setSuFaxTxN(String suFaxTxN) {
		this.suFaxTxN = suFaxTxN;
	}

	@Column(name = "SuEMailTx_N")
	public String getSuEmailTxN() {
		return this.suEmailTxN;
	}

	public void setSuEmailTxN(String suEmailTxN) {
		this.suEmailTxN = suEmailTxN;
	}

	@Column(name = "SuWebTx_N")
	public String getSuWebTxN() {
		return this.suWebTxN;
	}

	public void setSuWebTxN(String suWebTxN) {
		this.suWebTxN = suWebTxN;
	}

	@Column(name = "SuUnavailableBl", nullable = false)
	public boolean isSuUnavailableBl() {
		return this.suUnavailableBl;
	}

	public void setSuUnavailableBl(boolean suUnavailableBl) {
		this.suUnavailableBl = suUnavailableBl;
	}

	@Column(name = "SuLastUpdatedDate", nullable = false, length = 23)
	public Date getSuLastUpdatedDate() {
		return this.suLastUpdatedDate;
	}

	public void setSuLastUpdatedDate(Date suLastUpdatedDate) {
		this.suLastUpdatedDate = suLastUpdatedDate;
	}

	@Column(name = "SuRequiredBl", nullable = false)
	public boolean isSuRequiredBl() {
		return this.suRequiredBl;
	}

	public void setSuRequiredBl(boolean suRequiredBl) {
		this.suRequiredBl = suRequiredBl;
	}

	@Column(name = "SuCreationDate", nullable = false, length = 23)
	public Date getSuCreationDate() {
		return this.suCreationDate;
	}

	public void setSuCreationDate(Date suCreationDate) {
		this.suCreationDate = suCreationDate;
	}

	@Column(name = "SuB2BFnTx_N")
	public String getSuB2bfnTxN() {
		return this.suB2bfnTxN;
	}

	public void setSuB2bfnTxN(String suB2bfnTxN) {
		this.suB2bfnTxN = suB2bfnTxN;
	}

	@Column(name = "SuB2BEmailTx_N")
	public String getSuB2bemailTxN() {
		return this.suB2bemailTxN;
	}

	public void setSuB2bemailTxN(String suB2bemailTxN) {
		this.suB2bemailTxN = suB2bemailTxN;
	}

	@Column(name = "SuContact2Tx_N")
	public String getSuContact2txN() {
		return this.suContact2txN;
	}

	public void setSuContact2txN(String suContact2txN) {
		this.suContact2txN = suContact2txN;
	}

	@Column(name = "SuContact3Tx_N")
	public String getSuContact3txN() {
		return this.suContact3txN;
	}

	public void setSuContact3txN(String suContact3txN) {
		this.suContact3txN = suContact3txN;
	}

	@Column(name = "SuNotesTx_N")
	public String getSuNotesTxN() {
		return this.suNotesTxN;
	}

	public void setSuNotesTxN(String suNotesTxN) {
		this.suNotesTxN = suNotesTxN;
	}

	@Column(name = "SuDisplayOrderIn", nullable = false)
	public int getSuDisplayOrderIn() {
		return this.suDisplayOrderIn;
	}

	public void setSuDisplayOrderIn(int suDisplayOrderIn) {
		this.suDisplayOrderIn = suDisplayOrderIn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D01SuSupplierId))
			return false;
		D01SuSupplierId castOther = (D01SuSupplierId) other;

		return (this.getSuSupplierId() == castOther.getSuSupplierId())
				&& ((this.getSuSupplierTx() == castOther.getSuSupplierTx())
						|| (this.getSuSupplierTx() != null && castOther.getSuSupplierTx() != null
								&& this.getSuSupplierTx().equals(castOther.getSuSupplierTx())))
				&& ((this.getSuContactTxN() == castOther.getSuContactTxN())
						|| (this.getSuContactTxN() != null && castOther.getSuContactTxN() != null
								&& this.getSuContactTxN().equals(castOther.getSuContactTxN())))
				&& ((this.getSuSalesmanTxN() == castOther.getSuSalesmanTxN())
						|| (this.getSuSalesmanTxN() != null && castOther.getSuSalesmanTxN() != null
								&& this.getSuSalesmanTxN().equals(castOther.getSuSalesmanTxN())))
				&& ((this.getSuAddress1txN() == castOther.getSuAddress1txN())
						|| (this.getSuAddress1txN() != null && castOther.getSuAddress1txN() != null
								&& this.getSuAddress1txN().equals(castOther.getSuAddress1txN())))
				&& ((this.getSuAddress2txN() == castOther.getSuAddress2txN())
						|| (this.getSuAddress2txN() != null && castOther.getSuAddress2txN() != null
								&& this.getSuAddress2txN().equals(castOther.getSuAddress2txN())))
				&& ((this.getSuAddress3txN() == castOther.getSuAddress3txN())
						|| (this.getSuAddress3txN() != null && castOther.getSuAddress3txN() != null
								&& this.getSuAddress3txN().equals(castOther.getSuAddress3txN())))
				&& ((this.getSuAddress4txN() == castOther.getSuAddress4txN())
						|| (this.getSuAddress4txN() != null && castOther.getSuAddress4txN() != null
								&& this.getSuAddress4txN().equals(castOther.getSuAddress4txN())))
				&& ((this.getSuPostcodeTxN() == castOther.getSuPostcodeTxN())
						|| (this.getSuPostcodeTxN() != null && castOther.getSuPostcodeTxN() != null
								&& this.getSuPostcodeTxN().equals(castOther.getSuPostcodeTxN())))
				&& ((this.getSuCountryTxN() == castOther.getSuCountryTxN())
						|| (this.getSuCountryTxN() != null && castOther.getSuCountryTxN() != null
								&& this.getSuCountryTxN().equals(castOther.getSuCountryTxN())))
				&& ((this.getSuTelephone1txN() == castOther.getSuTelephone1txN())
						|| (this.getSuTelephone1txN() != null && castOther.getSuTelephone1txN() != null
								&& this.getSuTelephone1txN().equals(castOther.getSuTelephone1txN())))
				&& ((this.getSuTelephone2txN() == castOther.getSuTelephone2txN())
						|| (this.getSuTelephone2txN() != null && castOther.getSuTelephone2txN() != null
								&& this.getSuTelephone2txN().equals(castOther.getSuTelephone2txN())))
				&& ((this.getSuFaxTxN() == castOther.getSuFaxTxN()) || (this.getSuFaxTxN() != null
						&& castOther.getSuFaxTxN() != null && this.getSuFaxTxN().equals(castOther.getSuFaxTxN())))
				&& ((this.getSuEmailTxN() == castOther.getSuEmailTxN()) || (this.getSuEmailTxN() != null
						&& castOther.getSuEmailTxN() != null && this.getSuEmailTxN().equals(castOther.getSuEmailTxN())))
				&& ((this.getSuWebTxN() == castOther.getSuWebTxN()) || (this.getSuWebTxN() != null
						&& castOther.getSuWebTxN() != null && this.getSuWebTxN().equals(castOther.getSuWebTxN())))
				&& (this.isSuUnavailableBl() == castOther.isSuUnavailableBl())
				&& ((this.getSuLastUpdatedDate() == castOther.getSuLastUpdatedDate())
						|| (this.getSuLastUpdatedDate() != null && castOther.getSuLastUpdatedDate() != null
								&& this.getSuLastUpdatedDate().equals(castOther.getSuLastUpdatedDate())))
				&& (this.isSuRequiredBl() == castOther.isSuRequiredBl())
				&& ((this.getSuCreationDate() == castOther.getSuCreationDate())
						|| (this.getSuCreationDate() != null && castOther.getSuCreationDate() != null
								&& this.getSuCreationDate().equals(castOther.getSuCreationDate())))
				&& ((this.getSuB2bfnTxN() == castOther.getSuB2bfnTxN()) || (this.getSuB2bfnTxN() != null
						&& castOther.getSuB2bfnTxN() != null && this.getSuB2bfnTxN().equals(castOther.getSuB2bfnTxN())))
				&& ((this.getSuB2bemailTxN() == castOther.getSuB2bemailTxN())
						|| (this.getSuB2bemailTxN() != null && castOther.getSuB2bemailTxN() != null
								&& this.getSuB2bemailTxN().equals(castOther.getSuB2bemailTxN())))
				&& ((this.getSuContact2txN() == castOther.getSuContact2txN())
						|| (this.getSuContact2txN() != null && castOther.getSuContact2txN() != null
								&& this.getSuContact2txN().equals(castOther.getSuContact2txN())))
				&& ((this.getSuContact3txN() == castOther.getSuContact3txN())
						|| (this.getSuContact3txN() != null && castOther.getSuContact3txN() != null
								&& this.getSuContact3txN().equals(castOther.getSuContact3txN())))
				&& ((this.getSuNotesTxN() == castOther.getSuNotesTxN()) || (this.getSuNotesTxN() != null
						&& castOther.getSuNotesTxN() != null && this.getSuNotesTxN().equals(castOther.getSuNotesTxN())))
				&& (this.getSuDisplayOrderIn() == castOther.getSuDisplayOrderIn());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSuSupplierId();
		result = 37 * result + (getSuSupplierTx() == null ? 0 : this.getSuSupplierTx().hashCode());
		result = 37 * result + (getSuContactTxN() == null ? 0 : this.getSuContactTxN().hashCode());
		result = 37 * result + (getSuSalesmanTxN() == null ? 0 : this.getSuSalesmanTxN().hashCode());
		result = 37 * result + (getSuAddress1txN() == null ? 0 : this.getSuAddress1txN().hashCode());
		result = 37 * result + (getSuAddress2txN() == null ? 0 : this.getSuAddress2txN().hashCode());
		result = 37 * result + (getSuAddress3txN() == null ? 0 : this.getSuAddress3txN().hashCode());
		result = 37 * result + (getSuAddress4txN() == null ? 0 : this.getSuAddress4txN().hashCode());
		result = 37 * result + (getSuPostcodeTxN() == null ? 0 : this.getSuPostcodeTxN().hashCode());
		result = 37 * result + (getSuCountryTxN() == null ? 0 : this.getSuCountryTxN().hashCode());
		result = 37 * result + (getSuTelephone1txN() == null ? 0 : this.getSuTelephone1txN().hashCode());
		result = 37 * result + (getSuTelephone2txN() == null ? 0 : this.getSuTelephone2txN().hashCode());
		result = 37 * result + (getSuFaxTxN() == null ? 0 : this.getSuFaxTxN().hashCode());
		result = 37 * result + (getSuEmailTxN() == null ? 0 : this.getSuEmailTxN().hashCode());
		result = 37 * result + (getSuWebTxN() == null ? 0 : this.getSuWebTxN().hashCode());
		result = 37 * result + (this.isSuUnavailableBl() ? 1 : 0);
		result = 37 * result + (getSuLastUpdatedDate() == null ? 0 : this.getSuLastUpdatedDate().hashCode());
		result = 37 * result + (this.isSuRequiredBl() ? 1 : 0);
		result = 37 * result + (getSuCreationDate() == null ? 0 : this.getSuCreationDate().hashCode());
		result = 37 * result + (getSuB2bfnTxN() == null ? 0 : this.getSuB2bfnTxN().hashCode());
		result = 37 * result + (getSuB2bemailTxN() == null ? 0 : this.getSuB2bemailTxN().hashCode());
		result = 37 * result + (getSuContact2txN() == null ? 0 : this.getSuContact2txN().hashCode());
		result = 37 * result + (getSuContact3txN() == null ? 0 : this.getSuContact3txN().hashCode());
		result = 37 * result + (getSuNotesTxN() == null ? 0 : this.getSuNotesTxN().hashCode());
		result = 37 * result + this.getSuDisplayOrderIn();
		return result;
	}

}
