package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * D01TbtaxBand generated by hbm2java
 */
@Entity
@Table(name = "d01_TBTaxBand")
public class D01TbtaxBand implements java.io.Serializable {

	private D01TbtaxBandId id;

	public D01TbtaxBand() {
	}

	public D01TbtaxBand(D01TbtaxBandId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tbtaxBandId", column = @Column(name = "TBTaxBandID", nullable = false)),
			@AttributeOverride(name = "tbtaxBandTx", column = @Column(name = "TBTaxBandTx", nullable = false)),
			@AttributeOverride(name = "tbtaxRateFl", column = @Column(name = "TBTaxRateFl", nullable = false, precision = 24, scale = 0)),
			@AttributeOverride(name = "tbunavailableBl", column = @Column(name = "TBUnavailableBl", nullable = false)),
			@AttributeOverride(name = "tblastUpdatedDate", column = @Column(name = "TBLastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "tbrequiredBl", column = @Column(name = "TBRequiredBl", nullable = false)),
			@AttributeOverride(name = "tbglaccountIdN", column = @Column(name = "TBGLAccountID_N")),
			@AttributeOverride(name = "tbsupplierIdN", column = @Column(name = "TBSupplierID_N")),
			@AttributeOverride(name = "tbcreationDate", column = @Column(name = "TBCreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "tballowExemptionBl", column = @Column(name = "TBAllowExemptionBl", nullable = false)),
			@AttributeOverride(name = "tbnonSalesAccountIdN", column = @Column(name = "TBNonSalesAccountID_N")) })
	public D01TbtaxBandId getId() {
		return this.id;
	}

	public void setId(D01TbtaxBandId id) {
		this.id = id;
	}

}
