package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * D01TkTask generated by hbm2java
 */
@Entity
@Table(name = "d01_TkTask")
public class D01TkTask implements java.io.Serializable {

	private D01TkTaskId id;

	public D01TkTask() {
	}

	public D01TkTask(D01TkTaskId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "tkTaskId", column = @Column(name = "TkTaskID", nullable = false)),
			@AttributeOverride(name = "tkEmpIdN", column = @Column(name = "TkEmpID_N")),
			@AttributeOverride(name = "tkDueStartDate", column = @Column(name = "TkDueStartDate", nullable = false, length = 23)),
			@AttributeOverride(name = "tkDueEndDate", column = @Column(name = "TkDueEndDate", nullable = false, length = 23)),
			@AttributeOverride(name = "tkReminderDate", column = @Column(name = "TkReminderDate", nullable = false, length = 23)),
			@AttributeOverride(name = "tkNotesTxN", column = @Column(name = "TkNotesTx_N")),
			@AttributeOverride(name = "tkTaskTypeId", column = @Column(name = "TkTaskTypeID", nullable = false)),
			@AttributeOverride(name = "tkTaskStatusId", column = @Column(name = "TkTaskStatusID", nullable = false)),
			@AttributeOverride(name = "tkCreationDate", column = @Column(name = "TkCreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "tkLastUpdatedDate", column = @Column(name = "TkLastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "tkStoreId", column = @Column(name = "TkStoreID", nullable = false)),
			@AttributeOverride(name = "tkActualStartDateN", column = @Column(name = "TkActualStartDate_N", length = 23)),
			@AttributeOverride(name = "tkActualEndDateN", column = @Column(name = "TkActualEndDate_N", length = 23)),
			@AttributeOverride(name = "tkSmsreminderBl", column = @Column(name = "TkSMSReminderBl", nullable = false)),
			@AttributeOverride(name = "tkSmssentDate", column = @Column(name = "TkSMSSentDate", length = 23)),
			@AttributeOverride(name = "tkFromEmpIdN", column = @Column(name = "TkFromEmpId_N")),
			@AttributeOverride(name = "tkCommissionClosingIdN", column = @Column(name = "TkCommissionClosingID_N")),
			@AttributeOverride(name = "tkAssignedByEmpId", column = @Column(name = "TkAssignedByEmpID", nullable = false)) })
	public D01TkTaskId getId() {
		return this.id;
	}

	public void setId(D01TkTaskId id) {
		this.id = id;
	}

}
