package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EmailAgentClubMemberships generated by hbm2java
 */
@Entity
@Table(name = "EmailAgent_ClubMemberships")
public class EmailAgentClubMemberships implements java.io.Serializable {

	private EmailAgentClubMembershipsId id;

	public EmailAgentClubMemberships() {
	}

	public EmailAgentClubMemberships(EmailAgentClubMembershipsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cfCustClubId", column = @Column(name = "CfCustClubID", nullable = false)),
			@AttributeOverride(name = "firstName", column = @Column(name = "FirstName", nullable = false)),
			@AttributeOverride(name = "middleInitial", column = @Column(name = "MiddleInitial")),
			@AttributeOverride(name = "lastName", column = @Column(name = "LastName", nullable = false)),
			@AttributeOverride(name = "knownAs", column = @Column(name = "KnownAs")),
			@AttributeOverride(name = "email", column = @Column(name = "EMail")),
			@AttributeOverride(name = "firstLanguage", column = @Column(name = "FirstLanguage")),
			@AttributeOverride(name = "birthDate", column = @Column(name = "BirthDate", length = 23)),
			@AttributeOverride(name = "nextBirthDay", column = @Column(name = "NextBirthDay", length = 23)),
			@AttributeOverride(name = "previousBirthDay", column = @Column(name = "PreviousBirthDay", length = 23)),
			@AttributeOverride(name = "age", column = @Column(name = "Age")),
			@AttributeOverride(name = "homeAddress1", column = @Column(name = "HomeAddress1")),
			@AttributeOverride(name = "homeAddress2", column = @Column(name = "HomeAddress2")),
			@AttributeOverride(name = "homeAddress3", column = @Column(name = "HomeAddress3")),
			@AttributeOverride(name = "homeAddress4", column = @Column(name = "HomeAddress4")),
			@AttributeOverride(name = "homeState", column = @Column(name = "HomeState")),
			@AttributeOverride(name = "homePostcode", column = @Column(name = "HomePostcode")),
			@AttributeOverride(name = "homeCountry", column = @Column(name = "HomeCountry")),
			@AttributeOverride(name = "telHome", column = @Column(name = "TelHome")),
			@AttributeOverride(name = "telMobile", column = @Column(name = "TelMobile")),
			@AttributeOverride(name = "telWork", column = @Column(name = "TelWork")),
			@AttributeOverride(name = "telLocal", column = @Column(name = "TelLocal")),
			@AttributeOverride(name = "certLevel", column = @Column(name = "CertLevel")),
			@AttributeOverride(name = "sex", column = @Column(name = "Sex")),
			@AttributeOverride(name = "maritalStatus", column = @Column(name = "MaritalStatus")),
			@AttributeOverride(name = "club", column = @Column(name = "Club", nullable = false)),
			@AttributeOverride(name = "clubNotes", column = @Column(name = "ClubNotes")),
			@AttributeOverride(name = "clubCreationDate", column = @Column(name = "ClubCreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "membershipNo", column = @Column(name = "MembershipNo")),
			@AttributeOverride(name = "membershipType", column = @Column(name = "MembershipType")),
			@AttributeOverride(name = "membershipStartDate", column = @Column(name = "MembershipStartDate", length = 23)),
			@AttributeOverride(name = "membershipEndDate", column = @Column(name = "MembershipEndDate", length = 23)),
			@AttributeOverride(name = "cardLastPrintedDate", column = @Column(name = "CardLastPrintedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "membershipTypeId", column = @Column(name = "MembershipTypeID")),
			@AttributeOverride(name = "custId", column = @Column(name = "CustID", nullable = false)),
			@AttributeOverride(name = "clubId", column = @Column(name = "ClubID", nullable = false)),
			@AttributeOverride(name = "certLevelId", column = @Column(name = "CertLevelID")),
			@AttributeOverride(name = "storeId", column = @Column(name = "StoreID", nullable = false)) })
	public EmailAgentClubMembershipsId getId() {
		return this.id;
	}

	public void setId(EmailAgentClubMembershipsId id) {
		this.id = id;
	}

}
