package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EmailAgentItemsPurchased generated by hbm2java
 */
@Entity
@Table(name = "EmailAgent_ItemsPurchased")
public class EmailAgentItemsPurchased implements java.io.Serializable {

	private EmailAgentItemsPurchasedId id;

	public EmailAgentItemsPurchased() {
	}

	public EmailAgentItemsPurchased(EmailAgentItemsPurchasedId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "invoiceItemId", column = @Column(name = "InvoiceItemID", nullable = false)),
			@AttributeOverride(name = "invoiceId", column = @Column(name = "InvoiceID", nullable = false)),
			@AttributeOverride(name = "ticketNo", column = @Column(name = "TicketNo")),
			@AttributeOverride(name = "invoiceType", column = @Column(name = "InvoiceType", nullable = false)),
			@AttributeOverride(name = "costCenter", column = @Column(name = "CostCenter", nullable = false)),
			@AttributeOverride(name = "accountName", column = @Column(name = "AccountName")),
			@AttributeOverride(name = "firstName", column = @Column(name = "FirstName", nullable = false)),
			@AttributeOverride(name = "middleInitial", column = @Column(name = "MiddleInitial")),
			@AttributeOverride(name = "lastName", column = @Column(name = "LastName", nullable = false)),
			@AttributeOverride(name = "knownAs", column = @Column(name = "KnownAs")),
			@AttributeOverride(name = "email", column = @Column(name = "EMail")),
			@AttributeOverride(name = "firstLanguage", column = @Column(name = "FirstLanguage")),
			@AttributeOverride(name = "birthDate", column = @Column(name = "BirthDate", length = 23)),
			@AttributeOverride(name = "nextBirthDay", column = @Column(name = "NextBirthDay", length = 23)),
			@AttributeOverride(name = "previousBirthDay", column = @Column(name = "PreviousBirthDay", length = 23)),
			@AttributeOverride(name = "age", column = @Column(name = "Age")),
			@AttributeOverride(name = "homeAddress1", column = @Column(name = "HomeAddress1")),
			@AttributeOverride(name = "homeAddress2", column = @Column(name = "HomeAddress2")),
			@AttributeOverride(name = "homeAddress3", column = @Column(name = "HomeAddress3")),
			@AttributeOverride(name = "homeAddress4", column = @Column(name = "HomeAddress4")),
			@AttributeOverride(name = "homeState", column = @Column(name = "HomeState")),
			@AttributeOverride(name = "homePostcode", column = @Column(name = "HomePostcode")),
			@AttributeOverride(name = "homeCountry", column = @Column(name = "HomeCountry")),
			@AttributeOverride(name = "telHome", column = @Column(name = "TelHome")),
			@AttributeOverride(name = "telMobile", column = @Column(name = "TelMobile")),
			@AttributeOverride(name = "telWork", column = @Column(name = "TelWork")),
			@AttributeOverride(name = "telLocal", column = @Column(name = "TelLocal")),
			@AttributeOverride(name = "certLevel", column = @Column(name = "CertLevel")),
			@AttributeOverride(name = "noOfDives", column = @Column(name = "NoOfDives")),
			@AttributeOverride(name = "sex", column = @Column(name = "Sex")),
			@AttributeOverride(name = "maritalStatus", column = @Column(name = "MaritalStatus")),
			@AttributeOverride(name = "invoiceCreationDate", column = @Column(name = "InvoiceCreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "invoiceLastUpdatedDate", column = @Column(name = "InvoiceLastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "invoicePaymentDueDate", column = @Column(name = "InvoicePaymentDueDate", length = 23)),
			@AttributeOverride(name = "invoiceVoidDate", column = @Column(name = "InvoiceVoidDate", length = 23)),
			@AttributeOverride(name = "employee", column = @Column(name = "Employee", nullable = false)),
			@AttributeOverride(name = "invoiceStatus", column = @Column(name = "InvoiceStatus", nullable = false)),
			@AttributeOverride(name = "source", column = @Column(name = "Source")),
			@AttributeOverride(name = "notes", column = @Column(name = "Notes")),
			@AttributeOverride(name = "voidReason", column = @Column(name = "VoidReason")),
			@AttributeOverride(name = "stockNo", column = @Column(name = "StockNo", nullable = false)),
			@AttributeOverride(name = "stockItem", column = @Column(name = "StockItem", nullable = false)),
			@AttributeOverride(name = "stockType", column = @Column(name = "StockType", nullable = false)),
			@AttributeOverride(name = "manufacturer", column = @Column(name = "Manufacturer", nullable = false)),
			@AttributeOverride(name = "profitCenter", column = @Column(name = "ProfitCenter", nullable = false)),
			@AttributeOverride(name = "primaryColor", column = @Column(name = "PrimaryColor")),
			@AttributeOverride(name = "secondaryColor", column = @Column(name = "SecondaryColor")),
			@AttributeOverride(name = "size", column = @Column(name = "Size")),
			@AttributeOverride(name = "stockItemId", column = @Column(name = "StockItemID", nullable = false)),
			@AttributeOverride(name = "serialNo", column = @Column(name = "SerialNo")),
			@AttributeOverride(name = "qty", column = @Column(name = "Qty", nullable = false)),
			@AttributeOverride(name = "qtyAwaitingPickup", column = @Column(name = "QtyAwaitingPickup", nullable = false)),
			@AttributeOverride(name = "unitPrice", column = @Column(name = "UnitPrice", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "price", column = @Column(name = "Price", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "tax", column = @Column(name = "Tax", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "total", column = @Column(name = "Total", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "costPrice", column = @Column(name = "CostPrice", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "taxBand", column = @Column(name = "TaxBand", nullable = false)),
			@AttributeOverride(name = "taxRate", column = @Column(name = "TaxRate", nullable = false)),
			@AttributeOverride(name = "discountBand", column = @Column(name = "DiscountBand")),
			@AttributeOverride(name = "lineItemCreationDate", column = @Column(name = "LineItemCreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "lineItemLastUpdatedDate", column = @Column(name = "LineItemLastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "courseNo", column = @Column(name = "CourseNo")),
			@AttributeOverride(name = "courseType", column = @Column(name = "CourseType")),
			@AttributeOverride(name = "tripNo", column = @Column(name = "TripNo")),
			@AttributeOverride(name = "destination", column = @Column(name = "Destination")),
			@AttributeOverride(name = "boat", column = @Column(name = "Boat")),
			@AttributeOverride(name = "giftCertNo", column = @Column(name = "GiftCertNo")),
			@AttributeOverride(name = "giftCardNo", column = @Column(name = "GiftCardNo")),
			@AttributeOverride(name = "commissionRate", column = @Column(name = "CommissionRate", nullable = false, precision = 24, scale = 0)),
			@AttributeOverride(name = "lineItemNotes", column = @Column(name = "LineItemNotes")),
			@AttributeOverride(name = "closingId", column = @Column(name = "ClosingID")),
			@AttributeOverride(name = "accountingPeriodId", column = @Column(name = "AccountingPeriodID")),
			@AttributeOverride(name = "inventoryLocation", column = @Column(name = "InventoryLocation")),
			@AttributeOverride(name = "profitCenterId", column = @Column(name = "ProfitCenterID", nullable = false)),
			@AttributeOverride(name = "stockTypeId", column = @Column(name = "StockTypeID", nullable = false)),
			@AttributeOverride(name = "manufacturerId", column = @Column(name = "ManufacturerID", nullable = false)),
			@AttributeOverride(name = "storeLocationId", column = @Column(name = "StoreLocationID")),
			@AttributeOverride(name = "custCourseId", column = @Column(name = "CustCourseID")),
			@AttributeOverride(name = "custTripId", column = @Column(name = "CustTripID")),
			@AttributeOverride(name = "multiSaleId", column = @Column(name = "MultiSaleID")),
			@AttributeOverride(name = "rentalBookingId", column = @Column(name = "RentalBookingID")),
			@AttributeOverride(name = "serviceBookingId", column = @Column(name = "ServiceBookingID")),
			@AttributeOverride(name = "roomBookingId", column = @Column(name = "RoomBookingID")),
			@AttributeOverride(name = "giftCertId", column = @Column(name = "GiftCertID")),
			@AttributeOverride(name = "giftCardId", column = @Column(name = "GiftCardID")),
			@AttributeOverride(name = "discountBandId", column = @Column(name = "DiscountBandID")),
			@AttributeOverride(name = "invoiceTypeId", column = @Column(name = "InvoiceTypeID", nullable = false)),
			@AttributeOverride(name = "custId", column = @Column(name = "CustID", nullable = false)),
			@AttributeOverride(name = "costCenterId", column = @Column(name = "CostCenterID", nullable = false)),
			@AttributeOverride(name = "employeeId", column = @Column(name = "EmployeeID", nullable = false)),
			@AttributeOverride(name = "pcid", column = @Column(name = "PCID", nullable = false)),
			@AttributeOverride(name = "invoiceStatusId", column = @Column(name = "InvoiceStatusID", nullable = false)),
			@AttributeOverride(name = "sourceId", column = @Column(name = "SourceID")),
			@AttributeOverride(name = "accountId", column = @Column(name = "AccountID")),
			@AttributeOverride(name = "certLevelId", column = @Column(name = "CertLevelID")),
			@AttributeOverride(name = "storeId", column = @Column(name = "StoreID", nullable = false)) })
	public EmailAgentItemsPurchasedId getId() {
		return this.id;
	}

	public void setId(EmailAgentItemsPurchasedId id) {
		this.id = id;
	}

}
