package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmailAgentCertificationsId generated by hbm2java
 */
@Embeddable
public class EmailAgentCertificationsId implements java.io.Serializable {

	private int custCourseId;
	private String courseType;
	private String courseNo;
	private Date courseStartDate;
	private int custId;
	private String firstName;
	private String middleInitial;
	private String lastName;
	private String knownAs;
	private Date birthDate;
	private Date nextBirthDay;
	private Date previousBirthDay;
	private Integer age;
	private String homeAddress1;
	private String homeAddress2;
	private String homeAddress3;
	private String homeAddress4;
	private String homeState;
	private String homePostcode;
	private String homeCountry;
	private String email;
	private String telHome;
	private String telMobile;
	private String telWork;
	private String telLocal;
	private String scubaTribeCode;
	private String certifyingInstructor;
	private String certificationNo;
	private Date certificationDate;
	private String picstatus;
	private Date picsentDate;
	private Date picreceivedDate;
	private String piccard;
	private Integer returnCardTo;
	private Date picpickedUpDate;
	private Integer picpickupMethod;
	private String picprocessedBy;
	private Date creationDate;
	private Date lastUpdatedDate;
	private boolean referral;
	private String referralStoreNo;
	private boolean preRegistration;
	private String certNotes;
	private String certType;
	private boolean qualifiedHere;
	private String fatherName;
	private int courseTypeId;
	private Integer courseId;
	private Integer instructorId;
	private short picstatusId;
	private Integer piccardId;
	private Integer returnCardToId;
	private Integer picprocessedById;
	private short storeId;
	private Integer homeStateId;
	private Integer homeCountryId;
	private int certTypeId;

	public EmailAgentCertificationsId() {
	}

	public EmailAgentCertificationsId(int custCourseId, String courseType, int custId, String firstName,
			String lastName, Date creationDate, Date lastUpdatedDate, boolean referral, boolean preRegistration,
			boolean qualifiedHere, int courseTypeId, short picstatusId, short storeId, int certTypeId) {
		this.custCourseId = custCourseId;
		this.courseType = courseType;
		this.custId = custId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.referral = referral;
		this.preRegistration = preRegistration;
		this.qualifiedHere = qualifiedHere;
		this.courseTypeId = courseTypeId;
		this.picstatusId = picstatusId;
		this.storeId = storeId;
		this.certTypeId = certTypeId;
	}

	public EmailAgentCertificationsId(int custCourseId, String courseType, String courseNo,
			Date courseStartDate, int custId, String firstName, String middleInitial, String lastName,
			String knownAs, Date birthDate, Date nextBirthDay, Date previousBirthDay, Integer age,
			String homeAddress1, String homeAddress2, String homeAddress3, String homeAddress4,
			String homeState, String homePostcode, String homeCountry, String email,
			String telHome, String telMobile, String telWork, String telLocal,
			String scubaTribeCode, String certifyingInstructor, String certificationNo,
			Date certificationDate, String picstatus, Date picsentDate, Date picreceivedDate,
			String piccard, Integer returnCardTo, Date picpickedUpDate, Integer picpickupMethod,
			String picprocessedBy, Date creationDate, Date lastUpdatedDate, boolean referral,
			String referralStoreNo, boolean preRegistration, String certNotes, String certType,
			boolean qualifiedHere, String fatherName, int courseTypeId, Integer courseId, Integer instructorId,
			short picstatusId, Integer piccardId, Integer returnCardToId, Integer picprocessedById, short storeId,
			Integer homeStateId, Integer homeCountryId, int certTypeId) {
		this.custCourseId = custCourseId;
		this.courseType = courseType;
		this.courseNo = courseNo;
		this.courseStartDate = courseStartDate;
		this.custId = custId;
		this.firstName = firstName;
		this.middleInitial = middleInitial;
		this.lastName = lastName;
		this.knownAs = knownAs;
		this.birthDate = birthDate;
		this.nextBirthDay = nextBirthDay;
		this.previousBirthDay = previousBirthDay;
		this.age = age;
		this.homeAddress1 = homeAddress1;
		this.homeAddress2 = homeAddress2;
		this.homeAddress3 = homeAddress3;
		this.homeAddress4 = homeAddress4;
		this.homeState = homeState;
		this.homePostcode = homePostcode;
		this.homeCountry = homeCountry;
		this.email = email;
		this.telHome = telHome;
		this.telMobile = telMobile;
		this.telWork = telWork;
		this.telLocal = telLocal;
		this.scubaTribeCode = scubaTribeCode;
		this.certifyingInstructor = certifyingInstructor;
		this.certificationNo = certificationNo;
		this.certificationDate = certificationDate;
		this.picstatus = picstatus;
		this.picsentDate = picsentDate;
		this.picreceivedDate = picreceivedDate;
		this.piccard = piccard;
		this.returnCardTo = returnCardTo;
		this.picpickedUpDate = picpickedUpDate;
		this.picpickupMethod = picpickupMethod;
		this.picprocessedBy = picprocessedBy;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.referral = referral;
		this.referralStoreNo = referralStoreNo;
		this.preRegistration = preRegistration;
		this.certNotes = certNotes;
		this.certType = certType;
		this.qualifiedHere = qualifiedHere;
		this.fatherName = fatherName;
		this.courseTypeId = courseTypeId;
		this.courseId = courseId;
		this.instructorId = instructorId;
		this.picstatusId = picstatusId;
		this.piccardId = piccardId;
		this.returnCardToId = returnCardToId;
		this.picprocessedById = picprocessedById;
		this.storeId = storeId;
		this.homeStateId = homeStateId;
		this.homeCountryId = homeCountryId;
		this.certTypeId = certTypeId;
	}

	@Column(name = "CustCourseID", nullable = false)
	public int getCustCourseId() {
		return this.custCourseId;
	}

	public void setCustCourseId(int custCourseId) {
		this.custCourseId = custCourseId;
	}

	@Column(name = "CourseType", nullable = false)
	public String getCourseType() {
		return this.courseType;
	}

	public void setCourseType(String courseType) {
		this.courseType = courseType;
	}

	@Column(name = "CourseNo")
	public String getCourseNo() {
		return this.courseNo;
	}

	public void setCourseNo(String courseNo) {
		this.courseNo = courseNo;
	}

	@Column(name = "CourseStartDate", length = 23)
	public Date getCourseStartDate() {
		return this.courseStartDate;
	}

	public void setCourseStartDate(Date courseStartDate) {
		this.courseStartDate = courseStartDate;
	}

	@Column(name = "CustID", nullable = false)
	public int getCustId() {
		return this.custId;
	}

	public void setCustId(int custId) {
		this.custId = custId;
	}

	@Column(name = "FirstName", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "MiddleInitial")
	public String getMiddleInitial() {
		return this.middleInitial;
	}

	public void setMiddleInitial(String middleInitial) {
		this.middleInitial = middleInitial;
	}

	@Column(name = "LastName", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "KnownAs")
	public String getKnownAs() {
		return this.knownAs;
	}

	public void setKnownAs(String knownAs) {
		this.knownAs = knownAs;
	}

	@Column(name = "BirthDate", length = 23)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "NextBirthDay", length = 23)
	public Date getNextBirthDay() {
		return this.nextBirthDay;
	}

	public void setNextBirthDay(Date nextBirthDay) {
		this.nextBirthDay = nextBirthDay;
	}

	@Column(name = "PreviousBirthDay", length = 23)
	public Date getPreviousBirthDay() {
		return this.previousBirthDay;
	}

	public void setPreviousBirthDay(Date previousBirthDay) {
		this.previousBirthDay = previousBirthDay;
	}

	@Column(name = "Age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "HomeAddress1")
	public String getHomeAddress1() {
		return this.homeAddress1;
	}

	public void setHomeAddress1(String homeAddress1) {
		this.homeAddress1 = homeAddress1;
	}

	@Column(name = "HomeAddress2")
	public String getHomeAddress2() {
		return this.homeAddress2;
	}

	public void setHomeAddress2(String homeAddress2) {
		this.homeAddress2 = homeAddress2;
	}

	@Column(name = "HomeAddress3")
	public String getHomeAddress3() {
		return this.homeAddress3;
	}

	public void setHomeAddress3(String homeAddress3) {
		this.homeAddress3 = homeAddress3;
	}

	@Column(name = "HomeAddress4")
	public String getHomeAddress4() {
		return this.homeAddress4;
	}

	public void setHomeAddress4(String homeAddress4) {
		this.homeAddress4 = homeAddress4;
	}

	@Column(name = "HomeState")
	public String getHomeState() {
		return this.homeState;
	}

	public void setHomeState(String homeState) {
		this.homeState = homeState;
	}

	@Column(name = "HomePostcode")
	public String getHomePostcode() {
		return this.homePostcode;
	}

	public void setHomePostcode(String homePostcode) {
		this.homePostcode = homePostcode;
	}

	@Column(name = "HomeCountry")
	public String getHomeCountry() {
		return this.homeCountry;
	}

	public void setHomeCountry(String homeCountry) {
		this.homeCountry = homeCountry;
	}

	@Column(name = "EMail")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TelHome")
	public String getTelHome() {
		return this.telHome;
	}

	public void setTelHome(String telHome) {
		this.telHome = telHome;
	}

	@Column(name = "TelMobile")
	public String getTelMobile() {
		return this.telMobile;
	}

	public void setTelMobile(String telMobile) {
		this.telMobile = telMobile;
	}

	@Column(name = "TelWork")
	public String getTelWork() {
		return this.telWork;
	}

	public void setTelWork(String telWork) {
		this.telWork = telWork;
	}

	@Column(name = "TelLocal")
	public String getTelLocal() {
		return this.telLocal;
	}

	public void setTelLocal(String telLocal) {
		this.telLocal = telLocal;
	}

	@Column(name = "ScubaTribeCode")
	public String getScubaTribeCode() {
		return this.scubaTribeCode;
	}

	public void setScubaTribeCode(String scubaTribeCode) {
		this.scubaTribeCode = scubaTribeCode;
	}

	@Column(name = "CertifyingInstructor")
	public String getCertifyingInstructor() {
		return this.certifyingInstructor;
	}

	public void setCertifyingInstructor(String certifyingInstructor) {
		this.certifyingInstructor = certifyingInstructor;
	}

	@Column(name = "CertificationNo")
	public String getCertificationNo() {
		return this.certificationNo;
	}

	public void setCertificationNo(String certificationNo) {
		this.certificationNo = certificationNo;
	}

	@Column(name = "CertificationDate", length = 23)
	public Date getCertificationDate() {
		return this.certificationDate;
	}

	public void setCertificationDate(Date certificationDate) {
		this.certificationDate = certificationDate;
	}

	@Column(name = "PICStatus")
	public String getPicstatus() {
		return this.picstatus;
	}

	public void setPicstatus(String picstatus) {
		this.picstatus = picstatus;
	}

	@Column(name = "PICSentDate", length = 23)
	public Date getPicsentDate() {
		return this.picsentDate;
	}

	public void setPicsentDate(Date picsentDate) {
		this.picsentDate = picsentDate;
	}

	@Column(name = "PICReceivedDate", length = 23)
	public Date getPicreceivedDate() {
		return this.picreceivedDate;
	}

	public void setPicreceivedDate(Date picreceivedDate) {
		this.picreceivedDate = picreceivedDate;
	}

	@Column(name = "PICCard")
	public String getPiccard() {
		return this.piccard;
	}

	public void setPiccard(String piccard) {
		this.piccard = piccard;
	}

	@Column(name = "ReturnCardTo")
	public Integer getReturnCardTo() {
		return this.returnCardTo;
	}

	public void setReturnCardTo(Integer returnCardTo) {
		this.returnCardTo = returnCardTo;
	}

	@Column(name = "PICPickedUpDate", length = 23)
	public Date getPicpickedUpDate() {
		return this.picpickedUpDate;
	}

	public void setPicpickedUpDate(Date picpickedUpDate) {
		this.picpickedUpDate = picpickedUpDate;
	}

	@Column(name = "PICPickupMethod")
	public Integer getPicpickupMethod() {
		return this.picpickupMethod;
	}

	public void setPicpickupMethod(Integer picpickupMethod) {
		this.picpickupMethod = picpickupMethod;
	}

	@Column(name = "PICProcessedBy")
	public String getPicprocessedBy() {
		return this.picprocessedBy;
	}

	public void setPicprocessedBy(String picprocessedBy) {
		this.picprocessedBy = picprocessedBy;
	}

	@Column(name = "CreationDate", nullable = false, length = 23)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "LastUpdatedDate", nullable = false, length = 23)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "Referral", nullable = false)
	public boolean isReferral() {
		return this.referral;
	}

	public void setReferral(boolean referral) {
		this.referral = referral;
	}

	@Column(name = "ReferralStoreNo")
	public String getReferralStoreNo() {
		return this.referralStoreNo;
	}

	public void setReferralStoreNo(String referralStoreNo) {
		this.referralStoreNo = referralStoreNo;
	}

	@Column(name = "PreRegistration", nullable = false)
	public boolean isPreRegistration() {
		return this.preRegistration;
	}

	public void setPreRegistration(boolean preRegistration) {
		this.preRegistration = preRegistration;
	}

	@Column(name = "CertNotes")
	public String getCertNotes() {
		return this.certNotes;
	}

	public void setCertNotes(String certNotes) {
		this.certNotes = certNotes;
	}

	@Column(name = "CertType")
	public String getCertType() {
		return this.certType;
	}

	public void setCertType(String certType) {
		this.certType = certType;
	}

	@Column(name = "QualifiedHere", nullable = false)
	public boolean isQualifiedHere() {
		return this.qualifiedHere;
	}

	public void setQualifiedHere(boolean qualifiedHere) {
		this.qualifiedHere = qualifiedHere;
	}

	@Column(name = "FatherName")
	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	@Column(name = "CourseTypeID", nullable = false)
	public int getCourseTypeId() {
		return this.courseTypeId;
	}

	public void setCourseTypeId(int courseTypeId) {
		this.courseTypeId = courseTypeId;
	}

	@Column(name = "CourseID")
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "InstructorID")
	public Integer getInstructorId() {
		return this.instructorId;
	}

	public void setInstructorId(Integer instructorId) {
		this.instructorId = instructorId;
	}

	@Column(name = "PICStatusID", nullable = false)
	public short getPicstatusId() {
		return this.picstatusId;
	}

	public void setPicstatusId(short picstatusId) {
		this.picstatusId = picstatusId;
	}

	@Column(name = "PICCardID")
	public Integer getPiccardId() {
		return this.piccardId;
	}

	public void setPiccardId(Integer piccardId) {
		this.piccardId = piccardId;
	}

	@Column(name = "ReturnCardToID")
	public Integer getReturnCardToId() {
		return this.returnCardToId;
	}

	public void setReturnCardToId(Integer returnCardToId) {
		this.returnCardToId = returnCardToId;
	}

	@Column(name = "PICProcessedByID")
	public Integer getPicprocessedById() {
		return this.picprocessedById;
	}

	public void setPicprocessedById(Integer picprocessedById) {
		this.picprocessedById = picprocessedById;
	}

	@Column(name = "StoreID", nullable = false)
	public short getStoreId() {
		return this.storeId;
	}

	public void setStoreId(short storeId) {
		this.storeId = storeId;
	}

	@Column(name = "HomeStateID")
	public Integer getHomeStateId() {
		return this.homeStateId;
	}

	public void setHomeStateId(Integer homeStateId) {
		this.homeStateId = homeStateId;
	}

	@Column(name = "HomeCountryID")
	public Integer getHomeCountryId() {
		return this.homeCountryId;
	}

	public void setHomeCountryId(Integer homeCountryId) {
		this.homeCountryId = homeCountryId;
	}

	@Column(name = "CertTypeID", nullable = false)
	public int getCertTypeId() {
		return this.certTypeId;
	}

	public void setCertTypeId(int certTypeId) {
		this.certTypeId = certTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmailAgentCertificationsId))
			return false;
		EmailAgentCertificationsId castOther = (EmailAgentCertificationsId) other;

		return (this.getCustCourseId() == castOther.getCustCourseId())
				&& ((this.getCourseType() == castOther.getCourseType()) || (this.getCourseType() != null
						&& castOther.getCourseType() != null && this.getCourseType().equals(castOther.getCourseType())))
				&& ((this.getCourseNo() == castOther.getCourseNo()) || (this.getCourseNo() != null
						&& castOther.getCourseNo() != null && this.getCourseNo().equals(castOther.getCourseNo())))
				&& ((this.getCourseStartDate() == castOther.getCourseStartDate())
						|| (this.getCourseStartDate() != null && castOther.getCourseStartDate() != null
								&& this.getCourseStartDate().equals(castOther.getCourseStartDate())))
				&& (this.getCustId() == castOther.getCustId())
				&& ((this.getFirstName() == castOther.getFirstName()) || (this.getFirstName() != null
						&& castOther.getFirstName() != null && this.getFirstName().equals(castOther.getFirstName())))
				&& ((this.getMiddleInitial() == castOther.getMiddleInitial())
						|| (this.getMiddleInitial() != null && castOther.getMiddleInitial() != null
								&& this.getMiddleInitial().equals(castOther.getMiddleInitial())))
				&& ((this.getLastName() == castOther.getLastName()) || (this.getLastName() != null
						&& castOther.getLastName() != null && this.getLastName().equals(castOther.getLastName())))
				&& ((this.getKnownAs() == castOther.getKnownAs()) || (this.getKnownAs() != null
						&& castOther.getKnownAs() != null && this.getKnownAs().equals(castOther.getKnownAs())))
				&& ((this.getBirthDate() == castOther.getBirthDate()) || (this.getBirthDate() != null
						&& castOther.getBirthDate() != null && this.getBirthDate().equals(castOther.getBirthDate())))
				&& ((this.getNextBirthDay() == castOther.getNextBirthDay())
						|| (this.getNextBirthDay() != null && castOther.getNextBirthDay() != null
								&& this.getNextBirthDay().equals(castOther.getNextBirthDay())))
				&& ((this.getPreviousBirthDay() == castOther.getPreviousBirthDay())
						|| (this.getPreviousBirthDay() != null && castOther.getPreviousBirthDay() != null
								&& this.getPreviousBirthDay().equals(castOther.getPreviousBirthDay())))
				&& ((this.getAge() == castOther.getAge()) || (this.getAge() != null && castOther.getAge() != null
						&& this.getAge().equals(castOther.getAge())))
				&& ((this.getHomeAddress1() == castOther.getHomeAddress1())
						|| (this.getHomeAddress1() != null && castOther.getHomeAddress1() != null
								&& this.getHomeAddress1().equals(castOther.getHomeAddress1())))
				&& ((this.getHomeAddress2() == castOther.getHomeAddress2())
						|| (this.getHomeAddress2() != null && castOther.getHomeAddress2() != null
								&& this.getHomeAddress2().equals(castOther.getHomeAddress2())))
				&& ((this.getHomeAddress3() == castOther.getHomeAddress3())
						|| (this.getHomeAddress3() != null && castOther.getHomeAddress3() != null
								&& this.getHomeAddress3().equals(castOther.getHomeAddress3())))
				&& ((this.getHomeAddress4() == castOther.getHomeAddress4())
						|| (this.getHomeAddress4() != null && castOther.getHomeAddress4() != null
								&& this.getHomeAddress4().equals(castOther.getHomeAddress4())))
				&& ((this.getHomeState() == castOther.getHomeState()) || (this.getHomeState() != null
						&& castOther.getHomeState() != null && this.getHomeState().equals(castOther.getHomeState())))
				&& ((this.getHomePostcode() == castOther.getHomePostcode())
						|| (this.getHomePostcode() != null && castOther.getHomePostcode() != null
								&& this.getHomePostcode().equals(castOther.getHomePostcode())))
				&& ((this.getHomeCountry() == castOther.getHomeCountry())
						|| (this.getHomeCountry() != null && castOther.getHomeCountry() != null
								&& this.getHomeCountry().equals(castOther.getHomeCountry())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getTelHome() == castOther.getTelHome()) || (this.getTelHome() != null
						&& castOther.getTelHome() != null && this.getTelHome().equals(castOther.getTelHome())))
				&& ((this.getTelMobile() == castOther.getTelMobile()) || (this.getTelMobile() != null
						&& castOther.getTelMobile() != null && this.getTelMobile().equals(castOther.getTelMobile())))
				&& ((this.getTelWork() == castOther.getTelWork()) || (this.getTelWork() != null
						&& castOther.getTelWork() != null && this.getTelWork().equals(castOther.getTelWork())))
				&& ((this.getTelLocal() == castOther.getTelLocal()) || (this.getTelLocal() != null
						&& castOther.getTelLocal() != null && this.getTelLocal().equals(castOther.getTelLocal())))
				&& ((this.getScubaTribeCode() == castOther.getScubaTribeCode())
						|| (this.getScubaTribeCode() != null && castOther.getScubaTribeCode() != null
								&& this.getScubaTribeCode().equals(castOther.getScubaTribeCode())))
				&& ((this.getCertifyingInstructor() == castOther.getCertifyingInstructor())
						|| (this.getCertifyingInstructor() != null && castOther.getCertifyingInstructor() != null
								&& this.getCertifyingInstructor().equals(castOther.getCertifyingInstructor())))
				&& ((this.getCertificationNo() == castOther.getCertificationNo())
						|| (this.getCertificationNo() != null && castOther.getCertificationNo() != null
								&& this.getCertificationNo().equals(castOther.getCertificationNo())))
				&& ((this.getCertificationDate() == castOther.getCertificationDate())
						|| (this.getCertificationDate() != null && castOther.getCertificationDate() != null
								&& this.getCertificationDate().equals(castOther.getCertificationDate())))
				&& ((this.getPicstatus() == castOther.getPicstatus()) || (this.getPicstatus() != null
						&& castOther.getPicstatus() != null && this.getPicstatus().equals(castOther.getPicstatus())))
				&& ((this.getPicsentDate() == castOther.getPicsentDate())
						|| (this.getPicsentDate() != null && castOther.getPicsentDate() != null
								&& this.getPicsentDate().equals(castOther.getPicsentDate())))
				&& ((this.getPicreceivedDate() == castOther.getPicreceivedDate())
						|| (this.getPicreceivedDate() != null && castOther.getPicreceivedDate() != null
								&& this.getPicreceivedDate().equals(castOther.getPicreceivedDate())))
				&& ((this.getPiccard() == castOther.getPiccard()) || (this.getPiccard() != null
						&& castOther.getPiccard() != null && this.getPiccard().equals(castOther.getPiccard())))
				&& ((this.getReturnCardTo() == castOther.getReturnCardTo())
						|| (this.getReturnCardTo() != null && castOther.getReturnCardTo() != null
								&& this.getReturnCardTo().equals(castOther.getReturnCardTo())))
				&& ((this.getPicpickedUpDate() == castOther.getPicpickedUpDate())
						|| (this.getPicpickedUpDate() != null && castOther.getPicpickedUpDate() != null
								&& this.getPicpickedUpDate().equals(castOther.getPicpickedUpDate())))
				&& ((this.getPicpickupMethod() == castOther.getPicpickupMethod())
						|| (this.getPicpickupMethod() != null && castOther.getPicpickupMethod() != null
								&& this.getPicpickupMethod().equals(castOther.getPicpickupMethod())))
				&& ((this.getPicprocessedBy() == castOther.getPicprocessedBy())
						|| (this.getPicprocessedBy() != null && castOther.getPicprocessedBy() != null
								&& this.getPicprocessedBy().equals(castOther.getPicprocessedBy())))
				&& ((this.getCreationDate() == castOther.getCreationDate())
						|| (this.getCreationDate() != null && castOther.getCreationDate() != null
								&& this.getCreationDate().equals(castOther.getCreationDate())))
				&& ((this.getLastUpdatedDate() == castOther.getLastUpdatedDate())
						|| (this.getLastUpdatedDate() != null && castOther.getLastUpdatedDate() != null
								&& this.getLastUpdatedDate().equals(castOther.getLastUpdatedDate())))
				&& (this.isReferral() == castOther.isReferral())
				&& ((this.getReferralStoreNo() == castOther.getReferralStoreNo())
						|| (this.getReferralStoreNo() != null && castOther.getReferralStoreNo() != null
								&& this.getReferralStoreNo().equals(castOther.getReferralStoreNo())))
				&& (this.isPreRegistration() == castOther.isPreRegistration())
				&& ((this.getCertNotes() == castOther.getCertNotes()) || (this.getCertNotes() != null
						&& castOther.getCertNotes() != null && this.getCertNotes().equals(castOther.getCertNotes())))
				&& ((this.getCertType() == castOther.getCertType()) || (this.getCertType() != null
						&& castOther.getCertType() != null && this.getCertType().equals(castOther.getCertType())))
				&& (this.isQualifiedHere() == castOther.isQualifiedHere())
				&& ((this.getFatherName() == castOther.getFatherName()) || (this.getFatherName() != null
						&& castOther.getFatherName() != null && this.getFatherName().equals(castOther.getFatherName())))
				&& (this.getCourseTypeId() == castOther.getCourseTypeId())
				&& ((this.getCourseId() == castOther.getCourseId()) || (this.getCourseId() != null
						&& castOther.getCourseId() != null && this.getCourseId().equals(castOther.getCourseId())))
				&& ((this.getInstructorId() == castOther.getInstructorId())
						|| (this.getInstructorId() != null && castOther.getInstructorId() != null
								&& this.getInstructorId().equals(castOther.getInstructorId())))
				&& (this.getPicstatusId() == castOther.getPicstatusId())
				&& ((this.getPiccardId() == castOther.getPiccardId()) || (this.getPiccardId() != null
						&& castOther.getPiccardId() != null && this.getPiccardId().equals(castOther.getPiccardId())))
				&& ((this.getReturnCardToId() == castOther.getReturnCardToId())
						|| (this.getReturnCardToId() != null && castOther.getReturnCardToId() != null
								&& this.getReturnCardToId().equals(castOther.getReturnCardToId())))
				&& ((this.getPicprocessedById() == castOther.getPicprocessedById())
						|| (this.getPicprocessedById() != null && castOther.getPicprocessedById() != null
								&& this.getPicprocessedById().equals(castOther.getPicprocessedById())))
				&& (this.getStoreId() == castOther.getStoreId())
				&& ((this.getHomeStateId() == castOther.getHomeStateId())
						|| (this.getHomeStateId() != null && castOther.getHomeStateId() != null
								&& this.getHomeStateId().equals(castOther.getHomeStateId())))
				&& ((this.getHomeCountryId() == castOther.getHomeCountryId())
						|| (this.getHomeCountryId() != null && castOther.getHomeCountryId() != null
								&& this.getHomeCountryId().equals(castOther.getHomeCountryId())))
				&& (this.getCertTypeId() == castOther.getCertTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCustCourseId();
		result = 37 * result + (getCourseType() == null ? 0 : this.getCourseType().hashCode());
		result = 37 * result + (getCourseNo() == null ? 0 : this.getCourseNo().hashCode());
		result = 37 * result + (getCourseStartDate() == null ? 0 : this.getCourseStartDate().hashCode());
		result = 37 * result + this.getCustId();
		result = 37 * result + (getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = 37 * result + (getMiddleInitial() == null ? 0 : this.getMiddleInitial().hashCode());
		result = 37 * result + (getLastName() == null ? 0 : this.getLastName().hashCode());
		result = 37 * result + (getKnownAs() == null ? 0 : this.getKnownAs().hashCode());
		result = 37 * result + (getBirthDate() == null ? 0 : this.getBirthDate().hashCode());
		result = 37 * result + (getNextBirthDay() == null ? 0 : this.getNextBirthDay().hashCode());
		result = 37 * result + (getPreviousBirthDay() == null ? 0 : this.getPreviousBirthDay().hashCode());
		result = 37 * result + (getAge() == null ? 0 : this.getAge().hashCode());
		result = 37 * result + (getHomeAddress1() == null ? 0 : this.getHomeAddress1().hashCode());
		result = 37 * result + (getHomeAddress2() == null ? 0 : this.getHomeAddress2().hashCode());
		result = 37 * result + (getHomeAddress3() == null ? 0 : this.getHomeAddress3().hashCode());
		result = 37 * result + (getHomeAddress4() == null ? 0 : this.getHomeAddress4().hashCode());
		result = 37 * result + (getHomeState() == null ? 0 : this.getHomeState().hashCode());
		result = 37 * result + (getHomePostcode() == null ? 0 : this.getHomePostcode().hashCode());
		result = 37 * result + (getHomeCountry() == null ? 0 : this.getHomeCountry().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getTelHome() == null ? 0 : this.getTelHome().hashCode());
		result = 37 * result + (getTelMobile() == null ? 0 : this.getTelMobile().hashCode());
		result = 37 * result + (getTelWork() == null ? 0 : this.getTelWork().hashCode());
		result = 37 * result + (getTelLocal() == null ? 0 : this.getTelLocal().hashCode());
		result = 37 * result + (getScubaTribeCode() == null ? 0 : this.getScubaTribeCode().hashCode());
		result = 37 * result + (getCertifyingInstructor() == null ? 0 : this.getCertifyingInstructor().hashCode());
		result = 37 * result + (getCertificationNo() == null ? 0 : this.getCertificationNo().hashCode());
		result = 37 * result + (getCertificationDate() == null ? 0 : this.getCertificationDate().hashCode());
		result = 37 * result + (getPicstatus() == null ? 0 : this.getPicstatus().hashCode());
		result = 37 * result + (getPicsentDate() == null ? 0 : this.getPicsentDate().hashCode());
		result = 37 * result + (getPicreceivedDate() == null ? 0 : this.getPicreceivedDate().hashCode());
		result = 37 * result + (getPiccard() == null ? 0 : this.getPiccard().hashCode());
		result = 37 * result + (getReturnCardTo() == null ? 0 : this.getReturnCardTo().hashCode());
		result = 37 * result + (getPicpickedUpDate() == null ? 0 : this.getPicpickedUpDate().hashCode());
		result = 37 * result + (getPicpickupMethod() == null ? 0 : this.getPicpickupMethod().hashCode());
		result = 37 * result + (getPicprocessedBy() == null ? 0 : this.getPicprocessedBy().hashCode());
		result = 37 * result + (getCreationDate() == null ? 0 : this.getCreationDate().hashCode());
		result = 37 * result + (getLastUpdatedDate() == null ? 0 : this.getLastUpdatedDate().hashCode());
		result = 37 * result + (this.isReferral() ? 1 : 0);
		result = 37 * result + (getReferralStoreNo() == null ? 0 : this.getReferralStoreNo().hashCode());
		result = 37 * result + (this.isPreRegistration() ? 1 : 0);
		result = 37 * result + (getCertNotes() == null ? 0 : this.getCertNotes().hashCode());
		result = 37 * result + (getCertType() == null ? 0 : this.getCertType().hashCode());
		result = 37 * result + (this.isQualifiedHere() ? 1 : 0);
		result = 37 * result + (getFatherName() == null ? 0 : this.getFatherName().hashCode());
		result = 37 * result + this.getCourseTypeId();
		result = 37 * result + (getCourseId() == null ? 0 : this.getCourseId().hashCode());
		result = 37 * result + (getInstructorId() == null ? 0 : this.getInstructorId().hashCode());
		result = 37 * result + this.getPicstatusId();
		result = 37 * result + (getPiccardId() == null ? 0 : this.getPiccardId().hashCode());
		result = 37 * result + (getReturnCardToId() == null ? 0 : this.getReturnCardToId().hashCode());
		result = 37 * result + (getPicprocessedById() == null ? 0 : this.getPicprocessedById().hashCode());
		result = 37 * result + this.getStoreId();
		result = 37 * result + (getHomeStateId() == null ? 0 : this.getHomeStateId().hashCode());
		result = 37 * result + (getHomeCountryId() == null ? 0 : this.getHomeCountryId().hashCode());
		result = 37 * result + this.getCertTypeId();
		return result;
	}

}
