package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EmailAgentEquipmentItems generated by hbm2java
 */
@Entity
@Table(name = "EmailAgent_EquipmentItems")
public class EmailAgentEquipmentItems implements java.io.Serializable {

	private EmailAgentEquipmentItemsId id;

	public EmailAgentEquipmentItems() {
	}

	public EmailAgentEquipmentItems(EmailAgentEquipmentItemsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "equipmentId", column = @Column(name = "EquipmentID", nullable = false)),
			@AttributeOverride(name = "equipment", column = @Column(name = "Equipment", nullable = false)),
			@AttributeOverride(name = "stockType", column = @Column(name = "StockType", nullable = false)),
			@AttributeOverride(name = "refNo", column = @Column(name = "RefNo")),
			@AttributeOverride(name = "serialNo", column = @Column(name = "SerialNo")),
			@AttributeOverride(name = "manufacturer", column = @Column(name = "Manufacturer")),
			@AttributeOverride(name = "description", column = @Column(name = "Description")),
			@AttributeOverride(name = "size", column = @Column(name = "Size")),
			@AttributeOverride(name = "primaryColor", column = @Column(name = "PrimaryColor")),
			@AttributeOverride(name = "secondaryColor", column = @Column(name = "SecondaryColor")),
			@AttributeOverride(name = "barcodeNo", column = @Column(name = "BarcodeNo")),
			@AttributeOverride(name = "nextServiceDate", column = @Column(name = "NextServiceDate", length = 23)),
			@AttributeOverride(name = "lastServiceDate", column = @Column(name = "LastServiceDate", length = 23)),
			@AttributeOverride(name = "purchasedDate", column = @Column(name = "PurchasedDate", length = 23)),
			@AttributeOverride(name = "manufacturedDate", column = @Column(name = "ManufacturedDate", length = 23)),
			@AttributeOverride(name = "creationDate", column = @Column(name = "CreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "lastUpdatedDate", column = @Column(name = "LastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "netWorth", column = @Column(name = "NetWorth", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "package_", column = @Column(name = "Package", nullable = false)),
			@AttributeOverride(name = "bypassDblBookingCheck", column = @Column(name = "BypassDblBookingCheck", nullable = false)),
			@AttributeOverride(name = "cylinderValveOther", column = @Column(name = "CylinderValveOther")),
			@AttributeOverride(name = "cylinderTypeOther", column = @Column(name = "CylinderTypeOther")),
			@AttributeOverride(name = "cylinderBoot", column = @Column(name = "CylinderBoot")),
			@AttributeOverride(name = "cylinderBackpack", column = @Column(name = "CylinderBackpack")),
			@AttributeOverride(name = "cylinderWorkPressure", column = @Column(name = "CylinderWorkPressure")),
			@AttributeOverride(name = "cylinderLabno", column = @Column(name = "CylinderLABNo")),
			@AttributeOverride(name = "cylinderMaterialId", column = @Column(name = "CylinderMaterialID", nullable = false)),
			@AttributeOverride(name = "cylinderValveId", column = @Column(name = "CylinderValveID", nullable = false)),
			@AttributeOverride(name = "cylinderTypeId", column = @Column(name = "CylinderTypeID", nullable = false)),
			@AttributeOverride(name = "cylinderTestPressure", column = @Column(name = "CylinderTestPressure")),
			@AttributeOverride(name = "cylinderWaterCap", column = @Column(name = "CylinderWaterCap")),
			@AttributeOverride(name = "cylinderHydroDate", column = @Column(name = "CylinderHydroDate", length = 23)),
			@AttributeOverride(name = "custId", column = @Column(name = "CustID", nullable = false)),
			@AttributeOverride(name = "firstName", column = @Column(name = "FirstName", nullable = false)),
			@AttributeOverride(name = "middleInitial", column = @Column(name = "MiddleInitial")),
			@AttributeOverride(name = "lastName", column = @Column(name = "LastName", nullable = false)),
			@AttributeOverride(name = "knownAs", column = @Column(name = "KnownAs")),
			@AttributeOverride(name = "birthDate", column = @Column(name = "BirthDate", length = 23)),
			@AttributeOverride(name = "nextBirthDay", column = @Column(name = "NextBirthDay", length = 23)),
			@AttributeOverride(name = "previousBirthDay", column = @Column(name = "PreviousBirthDay", length = 23)),
			@AttributeOverride(name = "age", column = @Column(name = "Age")),
			@AttributeOverride(name = "homeAddress1", column = @Column(name = "HomeAddress1")),
			@AttributeOverride(name = "homeAddress2", column = @Column(name = "HomeAddress2")),
			@AttributeOverride(name = "homeAddress3", column = @Column(name = "HomeAddress3")),
			@AttributeOverride(name = "homeAddress4", column = @Column(name = "HomeAddress4")),
			@AttributeOverride(name = "homeState", column = @Column(name = "HomeState")),
			@AttributeOverride(name = "homePostcode", column = @Column(name = "HomePostcode")),
			@AttributeOverride(name = "homeCountry", column = @Column(name = "HomeCountry")),
			@AttributeOverride(name = "email", column = @Column(name = "EMail")),
			@AttributeOverride(name = "telHome", column = @Column(name = "TelHome")),
			@AttributeOverride(name = "telMobile", column = @Column(name = "TelMobile")),
			@AttributeOverride(name = "telWork", column = @Column(name = "TelWork")),
			@AttributeOverride(name = "telLocal", column = @Column(name = "TelLocal")),
			@AttributeOverride(name = "stockTypeId", column = @Column(name = "StockTypeID", nullable = false)),
			@AttributeOverride(name = "manufacturerId", column = @Column(name = "ManufacturerID")),
			@AttributeOverride(name = "sizeId", column = @Column(name = "SizeID")),
			@AttributeOverride(name = "primaryColorId", column = @Column(name = "PrimaryColorID")),
			@AttributeOverride(name = "secondaryColorId", column = @Column(name = "SecondaryColorID")),
			@AttributeOverride(name = "homeStateId", column = @Column(name = "HomeStateID")),
			@AttributeOverride(name = "homeCountryId", column = @Column(name = "HomeCountryID")),
			@AttributeOverride(name = "storeId", column = @Column(name = "StoreID", nullable = false)) })
	public EmailAgentEquipmentItemsId getId() {
		return this.id;
	}

	public void setId(EmailAgentEquipmentItemsId id) {
		this.id = id;
	}

}
