package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EmailAgentInvoices generated by hbm2java
 */
@Entity
@Table(name = "EmailAgent_Invoices")
public class EmailAgentInvoices implements java.io.Serializable {

	private EmailAgentInvoicesId id;

	public EmailAgentInvoices() {
	}

	public EmailAgentInvoices(EmailAgentInvoicesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "invoiceId", column = @Column(name = "InvoiceID", nullable = false)),
			@AttributeOverride(name = "ticketNo", column = @Column(name = "TicketNo")),
			@AttributeOverride(name = "invoiceType", column = @Column(name = "InvoiceType", nullable = false)),
			@AttributeOverride(name = "costCenter", column = @Column(name = "CostCenter", nullable = false)),
			@AttributeOverride(name = "accountName", column = @Column(name = "AccountName")),
			@AttributeOverride(name = "firstName", column = @Column(name = "FirstName", nullable = false)),
			@AttributeOverride(name = "middleInitial", column = @Column(name = "MiddleInitial")),
			@AttributeOverride(name = "lastName", column = @Column(name = "LastName", nullable = false)),
			@AttributeOverride(name = "knownAs", column = @Column(name = "KnownAs")),
			@AttributeOverride(name = "email", column = @Column(name = "EMail")),
			@AttributeOverride(name = "firstLanguage", column = @Column(name = "FirstLanguage")),
			@AttributeOverride(name = "birthDate", column = @Column(name = "BirthDate", length = 23)),
			@AttributeOverride(name = "nextBirthDay", column = @Column(name = "NextBirthDay", length = 23)),
			@AttributeOverride(name = "previousBirthDay", column = @Column(name = "PreviousBirthDay", length = 23)),
			@AttributeOverride(name = "age", column = @Column(name = "Age")),
			@AttributeOverride(name = "homeAddress1", column = @Column(name = "HomeAddress1")),
			@AttributeOverride(name = "homeAddress2", column = @Column(name = "HomeAddress2")),
			@AttributeOverride(name = "homeAddress3", column = @Column(name = "HomeAddress3")),
			@AttributeOverride(name = "homeAddress4", column = @Column(name = "HomeAddress4")),
			@AttributeOverride(name = "homeState", column = @Column(name = "HomeState")),
			@AttributeOverride(name = "homePostcode", column = @Column(name = "HomePostcode")),
			@AttributeOverride(name = "homeCountry", column = @Column(name = "HomeCountry")),
			@AttributeOverride(name = "telHome", column = @Column(name = "TelHome")),
			@AttributeOverride(name = "telMobile", column = @Column(name = "TelMobile")),
			@AttributeOverride(name = "telWork", column = @Column(name = "TelWork")),
			@AttributeOverride(name = "telLocal", column = @Column(name = "TelLocal")),
			@AttributeOverride(name = "certLevel", column = @Column(name = "CertLevel")),
			@AttributeOverride(name = "noOfDives", column = @Column(name = "NoOfDives")),
			@AttributeOverride(name = "sex", column = @Column(name = "Sex")),
			@AttributeOverride(name = "maritalStatus", column = @Column(name = "MaritalStatus")),
			@AttributeOverride(name = "creationDate", column = @Column(name = "CreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "lastUpdatedDate", column = @Column(name = "LastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "paymentDueDate", column = @Column(name = "PaymentDueDate", length = 23)),
			@AttributeOverride(name = "voidDate", column = @Column(name = "VoidDate", length = 23)),
			@AttributeOverride(name = "employee", column = @Column(name = "Employee", nullable = false)),
			@AttributeOverride(name = "commissionable", column = @Column(name = "Commissionable", nullable = false)),
			@AttributeOverride(name = "subTotal", column = @Column(name = "SubTotal", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "tax", column = @Column(name = "Tax", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "total", column = @Column(name = "Total", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "pc", column = @Column(name = "PC", nullable = false)),
			@AttributeOverride(name = "invoiceStatus", column = @Column(name = "InvoiceStatus", nullable = false)),
			@AttributeOverride(name = "source", column = @Column(name = "Source")),
			@AttributeOverride(name = "notes", column = @Column(name = "Notes")),
			@AttributeOverride(name = "voidReason", column = @Column(name = "VoidReason")),
			@AttributeOverride(name = "invoiceTypeId", column = @Column(name = "InvoiceTypeID", nullable = false)),
			@AttributeOverride(name = "custId", column = @Column(name = "CustID", nullable = false)),
			@AttributeOverride(name = "costCenterId", column = @Column(name = "CostCenterID", nullable = false)),
			@AttributeOverride(name = "employeeId", column = @Column(name = "EmployeeID", nullable = false)),
			@AttributeOverride(name = "pcid", column = @Column(name = "PCID", nullable = false)),
			@AttributeOverride(name = "invoiceStatusId", column = @Column(name = "InvoiceStatusID", nullable = false)),
			@AttributeOverride(name = "sourceId", column = @Column(name = "SourceID")),
			@AttributeOverride(name = "accountId", column = @Column(name = "AccountID")),
			@AttributeOverride(name = "certLevelId", column = @Column(name = "CertLevelID")),
			@AttributeOverride(name = "storeId", column = @Column(name = "StoreID", nullable = false)) })
	public EmailAgentInvoicesId getId() {
		return this.id;
	}

	public void setId(EmailAgentInvoicesId id) {
		this.id = id;
	}

}
