package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EmailAgentCourseEnrollments generated by hbm2java
 */
@Entity
@Table(name = "EmailAgent_CourseEnrollments")
public class EmailAgentCourseEnrollments implements java.io.Serializable {

	private EmailAgentCourseEnrollmentsId id;

	public EmailAgentCourseEnrollments() {
	}

	public EmailAgentCourseEnrollments(EmailAgentCourseEnrollmentsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "custCourseId", column = @Column(name = "CustCourseID", nullable = false)),
			@AttributeOverride(name = "courseType", column = @Column(name = "CourseType", nullable = false)),
			@AttributeOverride(name = "courseNo", column = @Column(name = "CourseNo")),
			@AttributeOverride(name = "courseStartDate", column = @Column(name = "CourseStartDate", length = 30)),
			@AttributeOverride(name = "earliestModuleDate", column = @Column(name = "EarliestModuleDate", length = 30)),
			@AttributeOverride(name = "earliestModuleTime", column = @Column(name = "EarliestModuleTime", length = 5)),
			@AttributeOverride(name = "earliestModuleTypeId1", column = @Column(name = "EarliestModuleTypeID1")),
			@AttributeOverride(name = "custId", column = @Column(name = "CustID", nullable = false)),
			@AttributeOverride(name = "firstName", column = @Column(name = "FirstName", nullable = false)),
			@AttributeOverride(name = "middleInitial", column = @Column(name = "MiddleInitial")),
			@AttributeOverride(name = "lastName", column = @Column(name = "LastName", nullable = false)),
			@AttributeOverride(name = "knownAs", column = @Column(name = "KnownAs")),
			@AttributeOverride(name = "knownAsOrFirstName", column = @Column(name = "KnownAsOrFirstName")),
			@AttributeOverride(name = "birthDate", column = @Column(name = "BirthDate", length = 23)),
			@AttributeOverride(name = "nextBirthDay", column = @Column(name = "NextBirthDay", length = 23)),
			@AttributeOverride(name = "previousBirthDay", column = @Column(name = "PreviousBirthDay", length = 23)),
			@AttributeOverride(name = "age", column = @Column(name = "Age")),
			@AttributeOverride(name = "homeAddress1", column = @Column(name = "HomeAddress1")),
			@AttributeOverride(name = "homeAddress2", column = @Column(name = "HomeAddress2")),
			@AttributeOverride(name = "homeAddress3", column = @Column(name = "HomeAddress3")),
			@AttributeOverride(name = "homeAddress4", column = @Column(name = "HomeAddress4")),
			@AttributeOverride(name = "homeState", column = @Column(name = "HomeState")),
			@AttributeOverride(name = "homePostcode", column = @Column(name = "HomePostcode")),
			@AttributeOverride(name = "homeCountry", column = @Column(name = "HomeCountry")),
			@AttributeOverride(name = "email", column = @Column(name = "EMail")),
			@AttributeOverride(name = "telHome", column = @Column(name = "TelHome")),
			@AttributeOverride(name = "telMobile", column = @Column(name = "TelMobile")),
			@AttributeOverride(name = "telWork", column = @Column(name = "TelWork")),
			@AttributeOverride(name = "telLocal", column = @Column(name = "TelLocal")),
			@AttributeOverride(name = "instructor", column = @Column(name = "Instructor")),
			@AttributeOverride(name = "courseLocation", column = @Column(name = "CourseLocation")),
			@AttributeOverride(name = "courseNotes", column = @Column(name = "CourseNotes")),
			@AttributeOverride(name = "courseStatus", column = @Column(name = "CourseStatus")),
			@AttributeOverride(name = "courseLanguage", column = @Column(name = "CourseLanguage")),
			@AttributeOverride(name = "creationDate", column = @Column(name = "CreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "lastUpdatedDate", column = @Column(name = "LastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "referral", column = @Column(name = "Referral", nullable = false)),
			@AttributeOverride(name = "enrollmentStatus", column = @Column(name = "EnrollmentStatus")),
			@AttributeOverride(name = "picstatus", column = @Column(name = "PICStatus")),
			@AttributeOverride(name = "referralStoreNo", column = @Column(name = "ReferralStoreNo")),
			@AttributeOverride(name = "preRegistration", column = @Column(name = "PreRegistration", nullable = false)),
			@AttributeOverride(name = "certNotes", column = @Column(name = "CertNotes")),
			@AttributeOverride(name = "certType", column = @Column(name = "CertType")),
			@AttributeOverride(name = "scubaTribeCode", column = @Column(name = "ScubaTribeCode")),
			@AttributeOverride(name = "courseTypeId", column = @Column(name = "CourseTypeID", nullable = false)),
			@AttributeOverride(name = "courseId", column = @Column(name = "CourseID")),
			@AttributeOverride(name = "instructorId", column = @Column(name = "InstructorID")),
			@AttributeOverride(name = "enrollmentStatusId", column = @Column(name = "EnrollmentStatusID", nullable = false)),
			@AttributeOverride(name = "picstatusId", column = @Column(name = "PICStatusID", nullable = false)),
			@AttributeOverride(name = "piccardId", column = @Column(name = "PICCardID")),
			@AttributeOverride(name = "returnCardToId", column = @Column(name = "ReturnCardToID")),
			@AttributeOverride(name = "picprocessedById", column = @Column(name = "PICProcessedByID")),
			@AttributeOverride(name = "courseLocationId", column = @Column(name = "CourseLocationID")),
			@AttributeOverride(name = "courseStatusId", column = @Column(name = "CourseStatusID")),
			@AttributeOverride(name = "courseLanguageId", column = @Column(name = "CourseLanguageID")),
			@AttributeOverride(name = "storeId", column = @Column(name = "StoreID", nullable = false)),
			@AttributeOverride(name = "homeStateId", column = @Column(name = "HomeStateID")),
			@AttributeOverride(name = "homeCountryId", column = @Column(name = "HomeCountryID")),
			@AttributeOverride(name = "certTypeId", column = @Column(name = "CertTypeID", nullable = false)) })
	public EmailAgentCourseEnrollmentsId getId() {
		return this.id;
	}

	public void setId(EmailAgentCourseEnrollmentsId id) {
		this.id = id;
	}

}
