package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EmailAgentCustomers generated by hbm2java
 */
@Entity
@Table(name = "EmailAgent_Customers")
public class EmailAgentCustomers implements java.io.Serializable {

	private EmailAgentCustomersId id;

	public EmailAgentCustomers() {
	}

	public EmailAgentCustomers(EmailAgentCustomersId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "custId", column = @Column(name = "CustID", nullable = false)),
			@AttributeOverride(name = "firstName", column = @Column(name = "FirstName", nullable = false)),
			@AttributeOverride(name = "middleInitial", column = @Column(name = "MiddleInitial")),
			@AttributeOverride(name = "lastName", column = @Column(name = "LastName", nullable = false)),
			@AttributeOverride(name = "knownAs", column = @Column(name = "KnownAs")),
			@AttributeOverride(name = "email", column = @Column(name = "EMail")),
			@AttributeOverride(name = "birthDate", column = @Column(name = "BirthDate", length = 23)),
			@AttributeOverride(name = "nextBirthDay", column = @Column(name = "NextBirthDay", length = 23)),
			@AttributeOverride(name = "previousBirthDay", column = @Column(name = "PreviousBirthDay", length = 23)),
			@AttributeOverride(name = "age", column = @Column(name = "Age")),
			@AttributeOverride(name = "sex", column = @Column(name = "Sex")),
			@AttributeOverride(name = "maritalStatus", column = @Column(name = "MaritalStatus")),
			@AttributeOverride(name = "enquirySource", column = @Column(name = "EnquirySource")),
			@AttributeOverride(name = "homeAddress1", column = @Column(name = "HomeAddress1")),
			@AttributeOverride(name = "homeAddress2", column = @Column(name = "HomeAddress2")),
			@AttributeOverride(name = "homeAddress3", column = @Column(name = "HomeAddress3")),
			@AttributeOverride(name = "homeAddress4", column = @Column(name = "HomeAddress4")),
			@AttributeOverride(name = "homeState", column = @Column(name = "HomeState")),
			@AttributeOverride(name = "homePostcode", column = @Column(name = "HomePostcode")),
			@AttributeOverride(name = "homeCountry", column = @Column(name = "HomeCountry")),
			@AttributeOverride(name = "occupation", column = @Column(name = "Occupation")),
			@AttributeOverride(name = "company", column = @Column(name = "Company")),
			@AttributeOverride(name = "workAddress1", column = @Column(name = "WorkAddress1")),
			@AttributeOverride(name = "workAddress2", column = @Column(name = "WorkAddress2")),
			@AttributeOverride(name = "workAddress3", column = @Column(name = "WorkAddress3")),
			@AttributeOverride(name = "workAddress4", column = @Column(name = "WorkAddress4")),
			@AttributeOverride(name = "workState", column = @Column(name = "WorkState")),
			@AttributeOverride(name = "workPostcode", column = @Column(name = "WorkPostcode")),
			@AttributeOverride(name = "workCountry", column = @Column(name = "WorkCountry")),
			@AttributeOverride(name = "localAddress1", column = @Column(name = "LocalAddress1")),
			@AttributeOverride(name = "localAddress2", column = @Column(name = "LocalAddress2")),
			@AttributeOverride(name = "localAddress3", column = @Column(name = "LocalAddress3")),
			@AttributeOverride(name = "localAddress4", column = @Column(name = "LocalAddress4")),
			@AttributeOverride(name = "localPostcode", column = @Column(name = "LocalPostcode")),
			@AttributeOverride(name = "telHome", column = @Column(name = "TelHome")),
			@AttributeOverride(name = "telMobile", column = @Column(name = "TelMobile")),
			@AttributeOverride(name = "telWork", column = @Column(name = "TelWork")),
			@AttributeOverride(name = "telLocal", column = @Column(name = "TelLocal")),
			@AttributeOverride(name = "skypeName", column = @Column(name = "SkypeName")),
			@AttributeOverride(name = "fax", column = @Column(name = "Fax")),
			@AttributeOverride(name = "pager", column = @Column(name = "Pager")),
			@AttributeOverride(name = "firstLanguage", column = @Column(name = "FirstLanguage")),
			@AttributeOverride(name = "nokname", column = @Column(name = "NOKName")),
			@AttributeOverride(name = "nokrelationship", column = @Column(name = "NOKRelationship")),
			@AttributeOverride(name = "nokaddress1", column = @Column(name = "NOKAddress1")),
			@AttributeOverride(name = "nokaddress2", column = @Column(name = "NOKAddress2")),
			@AttributeOverride(name = "nokaddress3", column = @Column(name = "NOKAddress3")),
			@AttributeOverride(name = "nokaddress4", column = @Column(name = "NOKAddress4")),
			@AttributeOverride(name = "nokpostcode", column = @Column(name = "NOKPostcode")),
			@AttributeOverride(name = "noktel", column = @Column(name = "NOKTel")),
			@AttributeOverride(name = "imagePath", column = @Column(name = "ImagePath")),
			@AttributeOverride(name = "notes", column = @Column(name = "Notes")),
			@AttributeOverride(name = "doctorsReportRequired", column = @Column(name = "DoctorsReportRequired", nullable = false)),
			@AttributeOverride(name = "doctorsReportReceived", column = @Column(name = "DoctorsReportReceived", nullable = false)),
			@AttributeOverride(name = "doctorsReportDate", column = @Column(name = "DoctorsReportDate", length = 23)),
			@AttributeOverride(name = "unavailable", column = @Column(name = "Unavailable", nullable = false)),
			@AttributeOverride(name = "passportNo", column = @Column(name = "PassportNo")),
			@AttributeOverride(name = "frequentFlyer", column = @Column(name = "FrequentFlyer")),
			@AttributeOverride(name = "ssn", column = @Column(name = "SSN")),
			@AttributeOverride(name = "commissionable", column = @Column(name = "Commissionable", nullable = false)),
			@AttributeOverride(name = "arbalance", column = @Column(name = "ARBalance", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "creditLimit", column = @Column(name = "CreditLimit", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "creditRisk", column = @Column(name = "CreditRisk", nullable = false)),
			@AttributeOverride(name = "creationDate", column = @Column(name = "CreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "lastUpdatedDate", column = @Column(name = "LastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "lastPurchaseDate", column = @Column(name = "LastPurchaseDate", nullable = false, length = 23)),
			@AttributeOverride(name = "lastDiveDate", column = @Column(name = "LastDiveDate", length = 23)),
			@AttributeOverride(name = "userDefined1", column = @Column(name = "UserDefined1")),
			@AttributeOverride(name = "userDefined2", column = @Column(name = "UserDefined2")),
			@AttributeOverride(name = "userDefined3", column = @Column(name = "UserDefined3")),
			@AttributeOverride(name = "userName", column = @Column(name = "UserName")),
			@AttributeOverride(name = "noOfDives", column = @Column(name = "NoOfDives")),
			@AttributeOverride(name = "cardSeen", column = @Column(name = "CardSeen", nullable = false)),
			@AttributeOverride(name = "height", column = @Column(name = "Height", precision = 24, scale = 0)),
			@AttributeOverride(name = "weight", column = @Column(name = "Weight", precision = 24, scale = 0)),
			@AttributeOverride(name = "shoeSize", column = @Column(name = "ShoeSize", precision = 24, scale = 0)),
			@AttributeOverride(name = "insuranceNo", column = @Column(name = "InsuranceNo")),
			@AttributeOverride(name = "insuranceCo", column = @Column(name = "InsuranceCo")),
			@AttributeOverride(name = "insuranceDate", column = @Column(name = "InsuranceDate", length = 23)),
			@AttributeOverride(name = "accountManager", column = @Column(name = "AccountManager")),
			@AttributeOverride(name = "scubaTribeCode", column = @Column(name = "ScubaTribeCode")),
			@AttributeOverride(name = "storeName", column = @Column(name = "StoreName")),
			@AttributeOverride(name = "storeId", column = @Column(name = "StoreID", nullable = false)),
			@AttributeOverride(name = "mailingLists", column = @Column(name = "MailingLists")),
			@AttributeOverride(name = "customerTypes", column = @Column(name = "CustomerTypes")),
			@AttributeOverride(name = "taxExemptions", column = @Column(name = "TaxExemptions")),
			@AttributeOverride(name = "clubs", column = @Column(name = "Clubs")),
			@AttributeOverride(name = "certLevel", column = @Column(name = "CertLevel")),
			@AttributeOverride(name = "sexId", column = @Column(name = "SexID")),
			@AttributeOverride(name = "maritalStatusId", column = @Column(name = "MaritalStatusID")),
			@AttributeOverride(name = "enquirySourceId", column = @Column(name = "EnquirySourceID")),
			@AttributeOverride(name = "homeStateId", column = @Column(name = "HomeStateID")),
			@AttributeOverride(name = "homeCountryId", column = @Column(name = "HomeCountryID")),
			@AttributeOverride(name = "companyId", column = @Column(name = "CompanyID")),
			@AttributeOverride(name = "workStateId", column = @Column(name = "WorkStateID")),
			@AttributeOverride(name = "workCountryId", column = @Column(name = "WorkCountryID")),
			@AttributeOverride(name = "firstLanguageId", column = @Column(name = "FirstLanguageID")),
			@AttributeOverride(name = "accountManagerId", column = @Column(name = "AccountManagerID")),
			@AttributeOverride(name = "certLevelId", column = @Column(name = "CertLevelID")) })
	public EmailAgentCustomersId getId() {
		return this.id;
	}

	public void setId(EmailAgentCustomersId id) {
		this.id = id;
	}

}
