package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EolProductItemId generated by hbm2java
 */
@Embeddable
public class EolProductItemId implements java.io.Serializable {

	private int sistockItemId;
	private int sistockTypeId;
	private String ststockTypeTx;
	private String sistockItemTx;
	private String sistockItem2txN;
	private String sistockNoTx;
	private String siimageUrltxN;
	private String siimageUrl2txN;
	private String siimageUrl3txN;
//	private String siimageUrl4txN;
//	private String siimageUrl5txN;
	private String sivideoTxN;
	private boolean simaintainStockLevelBl;
	private BigDecimal psunitCostMn;
	private BigDecimal psregularPriceMn;
	private BigDecimal pseolpriceMn;
	private BigDecimal psregularPriceComputedMn;
	private BigDecimal pseolpriceComputedMn;
	private String sidescriptionTxN;
	private String sispecialOfferTxN;
	private int simanufacturerId;
	private String suSupplierTx;
	private int zlMinStock1in;
	private int pscurrentStockLevelIn;
	private boolean zlDisplayOnWebBl;
	private boolean siserialNosBl;
	private Short sieventDataTypeIdN;
	private Integer siprimaryColorIdN;
	private Integer sisecondaryColorIdN;
	private Integer sisizeIdN;
	private Double siweightFlN;
	private boolean sishowPriceInEolbl;
	private float psTaxRateFl;
	private boolean psCalcTaxOnShippingAddressBl;
	private int pschildrenCountIn;
	private int cccostCenterId;
	private short z5storeId;
	private short zmStoreId;
	private short zlStoreId;
	private int sidisplayOrderIn;
	private Integer siparentIdN;
	private boolean sipackageBl;
	private boolean sieolshowPackagePageBl;
	private boolean sipackageItemsIncludedBl;
	private int siclickActionId;
	private String siclickActionParamsTxN;
	private String siclickActionPromptTxN;
	private String siclickUrlTextTxN;

	public EolProductItemId() {
	}

	public EolProductItemId(int sistockItemId, int sistockTypeId, String ststockTypeTx,
			String sistockItemTx, String sistockNoTx, boolean simaintainStockLevelBl,
			BigDecimal psunitCostMn, BigDecimal psregularPriceMn, BigDecimal pseolpriceMn,
			BigDecimal psregularPriceComputedMn, BigDecimal pseolpriceComputedMn, int simanufacturerId,
			String suSupplierTx, int zlMinStock1in, int pscurrentStockLevelIn, boolean zlDisplayOnWebBl,
			boolean siserialNosBl, boolean sishowPriceInEolbl, float psTaxRateFl, boolean psCalcTaxOnShippingAddressBl,
			int pschildrenCountIn, int cccostCenterId, short z5storeId, short zmStoreId, short zlStoreId,
			int sidisplayOrderIn, boolean sipackageBl, boolean sieolshowPackagePageBl, boolean sipackageItemsIncludedBl,
			int siclickActionId) {
		this.sistockItemId = sistockItemId;
		this.sistockTypeId = sistockTypeId;
		this.ststockTypeTx = ststockTypeTx;
		this.sistockItemTx = sistockItemTx;
		this.sistockNoTx = sistockNoTx;
		this.simaintainStockLevelBl = simaintainStockLevelBl;
		this.psunitCostMn = psunitCostMn;
		this.psregularPriceMn = psregularPriceMn;
		this.pseolpriceMn = pseolpriceMn;
		this.psregularPriceComputedMn = psregularPriceComputedMn;
		this.pseolpriceComputedMn = pseolpriceComputedMn;
		this.simanufacturerId = simanufacturerId;
		this.suSupplierTx = suSupplierTx;
		this.zlMinStock1in = zlMinStock1in;
		this.pscurrentStockLevelIn = pscurrentStockLevelIn;
		this.zlDisplayOnWebBl = zlDisplayOnWebBl;
		this.siserialNosBl = siserialNosBl;
		this.sishowPriceInEolbl = sishowPriceInEolbl;
		this.psTaxRateFl = psTaxRateFl;
		this.psCalcTaxOnShippingAddressBl = psCalcTaxOnShippingAddressBl;
		this.pschildrenCountIn = pschildrenCountIn;
		this.cccostCenterId = cccostCenterId;
		this.z5storeId = z5storeId;
		this.zmStoreId = zmStoreId;
		this.zlStoreId = zlStoreId;
		this.sidisplayOrderIn = sidisplayOrderIn;
		this.sipackageBl = sipackageBl;
		this.sieolshowPackagePageBl = sieolshowPackagePageBl;
		this.sipackageItemsIncludedBl = sipackageItemsIncludedBl;
		this.siclickActionId = siclickActionId;
	}

	public EolProductItemId(int sistockItemId, int sistockTypeId, String ststockTypeTx,
			String sistockItemTx, String sistockItem2txN, String sistockNoTx,
			String siimageUrltxN, String siimageUrl2txN, String siimageUrl3txN,
			String siimageUrl4txN, String siimageUrl5txN, String sivideoTxN,
			boolean simaintainStockLevelBl, BigDecimal psunitCostMn, BigDecimal psregularPriceMn,
			BigDecimal pseolpriceMn, BigDecimal psregularPriceComputedMn, BigDecimal pseolpriceComputedMn,
			String sidescriptionTxN, String sispecialOfferTxN, int simanufacturerId,
			String suSupplierTx, int zlMinStock1in, int pscurrentStockLevelIn, boolean zlDisplayOnWebBl,
			boolean siserialNosBl, Short sieventDataTypeIdN, Integer siprimaryColorIdN, Integer sisecondaryColorIdN,
			Integer sisizeIdN, Double siweightFlN, boolean sishowPriceInEolbl, float psTaxRateFl,
			boolean psCalcTaxOnShippingAddressBl, int pschildrenCountIn, int cccostCenterId, short z5storeId,
			short zmStoreId, short zlStoreId, int sidisplayOrderIn, Integer siparentIdN, boolean sipackageBl,
			boolean sieolshowPackagePageBl, boolean sipackageItemsIncludedBl, int siclickActionId,
			String siclickActionParamsTxN, String siclickActionPromptTxN, String siclickUrlTextTxN) {
		this.sistockItemId = sistockItemId;
		this.sistockTypeId = sistockTypeId;
		this.ststockTypeTx = ststockTypeTx;
		this.sistockItemTx = sistockItemTx;
		this.sistockItem2txN = sistockItem2txN;
		this.sistockNoTx = sistockNoTx;
		this.siimageUrltxN = siimageUrltxN;
		this.siimageUrl2txN = siimageUrl2txN;
		this.siimageUrl3txN = siimageUrl3txN;
//		this.siimageUrl4txN = siimageUrl4txN;
//		this.siimageUrl5txN = siimageUrl5txN;
		this.sivideoTxN = sivideoTxN;
		this.simaintainStockLevelBl = simaintainStockLevelBl;
		this.psunitCostMn = psunitCostMn;
		this.psregularPriceMn = psregularPriceMn;
		this.pseolpriceMn = pseolpriceMn;
		this.psregularPriceComputedMn = psregularPriceComputedMn;
		this.pseolpriceComputedMn = pseolpriceComputedMn;
		this.sidescriptionTxN = sidescriptionTxN;
		this.sispecialOfferTxN = sispecialOfferTxN;
		this.simanufacturerId = simanufacturerId;
		this.suSupplierTx = suSupplierTx;
		this.zlMinStock1in = zlMinStock1in;
		this.pscurrentStockLevelIn = pscurrentStockLevelIn;
		this.zlDisplayOnWebBl = zlDisplayOnWebBl;
		this.siserialNosBl = siserialNosBl;
		this.sieventDataTypeIdN = sieventDataTypeIdN;
		this.siprimaryColorIdN = siprimaryColorIdN;
		this.sisecondaryColorIdN = sisecondaryColorIdN;
		this.sisizeIdN = sisizeIdN;
		this.siweightFlN = siweightFlN;
		this.sishowPriceInEolbl = sishowPriceInEolbl;
		this.psTaxRateFl = psTaxRateFl;
		this.psCalcTaxOnShippingAddressBl = psCalcTaxOnShippingAddressBl;
		this.pschildrenCountIn = pschildrenCountIn;
		this.cccostCenterId = cccostCenterId;
		this.z5storeId = z5storeId;
		this.zmStoreId = zmStoreId;
		this.zlStoreId = zlStoreId;
		this.sidisplayOrderIn = sidisplayOrderIn;
		this.siparentIdN = siparentIdN;
		this.sipackageBl = sipackageBl;
		this.sieolshowPackagePageBl = sieolshowPackagePageBl;
		this.sipackageItemsIncludedBl = sipackageItemsIncludedBl;
		this.siclickActionId = siclickActionId;
		this.siclickActionParamsTxN = siclickActionParamsTxN;
		this.siclickActionPromptTxN = siclickActionPromptTxN;
		this.siclickUrlTextTxN = siclickUrlTextTxN;
	}

	@Column(name = "SIStockItemID", nullable = false)
	public int getSistockItemId() {
		return this.sistockItemId;
	}

	public void setSistockItemId(int sistockItemId) {
		this.sistockItemId = sistockItemId;
	}

	@Column(name = "SIStockTypeID", nullable = false)
	public int getSistockTypeId() {
		return this.sistockTypeId;
	}

	public void setSistockTypeId(int sistockTypeId) {
		this.sistockTypeId = sistockTypeId;
	}

	@Column(name = "STStockTypeTx", nullable = false)
	public String getStstockTypeTx() {
		return this.ststockTypeTx;
	}

	public void setStstockTypeTx(String ststockTypeTx) {
		this.ststockTypeTx = ststockTypeTx;
	}

	@Column(name = "SIStockItemTx", nullable = false)
	public String getSistockItemTx() {
		return this.sistockItemTx;
	}

	public void setSistockItemTx(String sistockItemTx) {
		this.sistockItemTx = sistockItemTx;
	}

	@Column(name = "SIStockItem2Tx_N")
	public String getSistockItem2txN() {
		return this.sistockItem2txN;
	}

	public void setSistockItem2txN(String sistockItem2txN) {
		this.sistockItem2txN = sistockItem2txN;
	}

	@Column(name = "SIStockNoTx", nullable = false)
	public String getSistockNoTx() {
		return this.sistockNoTx;
	}

	public void setSistockNoTx(String sistockNoTx) {
		this.sistockNoTx = sistockNoTx;
	}

	@Column(name = "SIImageURLTx_N")
	public String getSiimageUrltxN() {
		return this.siimageUrltxN;
	}

	public void setSiimageUrltxN(String siimageUrltxN) {
		this.siimageUrltxN = siimageUrltxN;
	}

	@Column(name = "SIImageURL2Tx_N")
	public String getSiimageUrl2txN() {
		return this.siimageUrl2txN;
	}

	public void setSiimageUrl2txN(String siimageUrl2txN) {
		this.siimageUrl2txN = siimageUrl2txN;
	}

	@Column(name = "SIImageURL3Tx_N")
	public String getSiimageUrl3txN() {
		return this.siimageUrl3txN;
	}

	public void setSiimageUrl3txN(String siimageUrl3txN) {
		this.siimageUrl3txN = siimageUrl3txN;
	}

//	@Column(name = "SIImageURL4Tx_N")
//	public String getSiimageUrl4txN() {
//		return this.siimageUrl4txN;
//	}
//
//	public void setSiimageUrl4txN(String siimageUrl4txN) {
//		this.siimageUrl4txN = siimageUrl4txN;
//	}
//
//	@Column(name = "SIImageURL5Tx_N")
//	public String getSiimageUrl5txN() {
//		return this.siimageUrl5txN;
//	}
//
//	public void setSiimageUrl5txN(String siimageUrl5txN) {
//		this.siimageUrl5txN = siimageUrl5txN;
//	}

	@Column(name = "SIVideoTx_N")
	public String getSivideoTxN() {
		return this.sivideoTxN;
	}

	public void setSivideoTxN(String sivideoTxN) {
		this.sivideoTxN = sivideoTxN;
	}

	@Column(name = "SIMaintainStockLevelBl", nullable = false)
	public boolean isSimaintainStockLevelBl() {
		return this.simaintainStockLevelBl;
	}

	public void setSimaintainStockLevelBl(boolean simaintainStockLevelBl) {
		this.simaintainStockLevelBl = simaintainStockLevelBl;
	}

	@Column(name = "PSUnitCostMn", nullable = false, scale = 4)
	public BigDecimal getPsunitCostMn() {
		return this.psunitCostMn;
	}

	public void setPsunitCostMn(BigDecimal psunitCostMn) {
		this.psunitCostMn = psunitCostMn;
	}

	@Column(name = "PSRegularPriceMn", nullable = false, scale = 4)
	public BigDecimal getPsregularPriceMn() {
		return this.psregularPriceMn;
	}

	public void setPsregularPriceMn(BigDecimal psregularPriceMn) {
		this.psregularPriceMn = psregularPriceMn;
	}

	@Column(name = "PSEOLPriceMn", nullable = false, scale = 4)
	public BigDecimal getPseolpriceMn() {
		return this.pseolpriceMn;
	}

	public void setPseolpriceMn(BigDecimal pseolpriceMn) {
		this.pseolpriceMn = pseolpriceMn;
	}

	@Column(name = "PSRegularPriceComputedMn", nullable = false, scale = 4)
	public BigDecimal getPsregularPriceComputedMn() {
		return this.psregularPriceComputedMn;
	}

	public void setPsregularPriceComputedMn(BigDecimal psregularPriceComputedMn) {
		this.psregularPriceComputedMn = psregularPriceComputedMn;
	}

	@Column(name = "PSEOLPriceComputedMn", nullable = false, scale = 4)
	public BigDecimal getPseolpriceComputedMn() {
		return this.pseolpriceComputedMn;
	}

	public void setPseolpriceComputedMn(BigDecimal pseolpriceComputedMn) {
		this.pseolpriceComputedMn = pseolpriceComputedMn;
	}

	@Column(name = "SIDescriptionTx_N")
	public String getSidescriptionTxN() {
		return this.sidescriptionTxN;
	}

	public void setSidescriptionTxN(String sidescriptionTxN) {
		this.sidescriptionTxN = sidescriptionTxN;
	}

	@Column(name = "SISpecialOfferTx_N")
	public String getSispecialOfferTxN() {
		return this.sispecialOfferTxN;
	}

	public void setSispecialOfferTxN(String sispecialOfferTxN) {
		this.sispecialOfferTxN = sispecialOfferTxN;
	}

	@Column(name = "SIManufacturerID", nullable = false)
	public int getSimanufacturerId() {
		return this.simanufacturerId;
	}

	public void setSimanufacturerId(int simanufacturerId) {
		this.simanufacturerId = simanufacturerId;
	}

	@Column(name = "SuSupplierTx", nullable = false)
	public String getSuSupplierTx() {
		return this.suSupplierTx;
	}

	public void setSuSupplierTx(String suSupplierTx) {
		this.suSupplierTx = suSupplierTx;
	}

	@Column(name = "ZlMinStock1In", nullable = false)
	public int getZlMinStock1in() {
		return this.zlMinStock1in;
	}

	public void setZlMinStock1in(int zlMinStock1in) {
		this.zlMinStock1in = zlMinStock1in;
	}

	@Column(name = "PSCurrentStockLevelIn", nullable = false)
	public int getPscurrentStockLevelIn() {
		return this.pscurrentStockLevelIn;
	}

	public void setPscurrentStockLevelIn(int pscurrentStockLevelIn) {
		this.pscurrentStockLevelIn = pscurrentStockLevelIn;
	}

	@Column(name = "ZlDisplayOnWebBl", nullable = false)
	public boolean isZlDisplayOnWebBl() {
		return this.zlDisplayOnWebBl;
	}

	public void setZlDisplayOnWebBl(boolean zlDisplayOnWebBl) {
		this.zlDisplayOnWebBl = zlDisplayOnWebBl;
	}

	@Column(name = "SISerialNosBl", nullable = false)
	public boolean isSiserialNosBl() {
		return this.siserialNosBl;
	}

	public void setSiserialNosBl(boolean siserialNosBl) {
		this.siserialNosBl = siserialNosBl;
	}

	@Column(name = "SIEventDataTypeID_N")
	public Short getSieventDataTypeIdN() {
		return this.sieventDataTypeIdN;
	}

	public void setSieventDataTypeIdN(Short sieventDataTypeIdN) {
		this.sieventDataTypeIdN = sieventDataTypeIdN;
	}

	@Column(name = "SIPrimaryColorID_N")
	public Integer getSiprimaryColorIdN() {
		return this.siprimaryColorIdN;
	}

	public void setSiprimaryColorIdN(Integer siprimaryColorIdN) {
		this.siprimaryColorIdN = siprimaryColorIdN;
	}

	@Column(name = "SISecondaryColorID_N")
	public Integer getSisecondaryColorIdN() {
		return this.sisecondaryColorIdN;
	}

	public void setSisecondaryColorIdN(Integer sisecondaryColorIdN) {
		this.sisecondaryColorIdN = sisecondaryColorIdN;
	}

	@Column(name = "SISizeID_N")
	public Integer getSisizeIdN() {
		return this.sisizeIdN;
	}

	public void setSisizeIdN(Integer sisizeIdN) {
		this.sisizeIdN = sisizeIdN;
	}

	@Column(name = "SIWeightFl_N", precision = 53, scale = 0)
	public Double getSiweightFlN() {
		return this.siweightFlN;
	}

	public void setSiweightFlN(Double siweightFlN) {
		this.siweightFlN = siweightFlN;
	}

	@Column(name = "SIShowPriceInEOLBl", nullable = false)
	public boolean isSishowPriceInEolbl() {
		return this.sishowPriceInEolbl;
	}

	public void setSishowPriceInEolbl(boolean sishowPriceInEolbl) {
		this.sishowPriceInEolbl = sishowPriceInEolbl;
	}

	@Column(name = "PsTaxRateFl", nullable = false, precision = 24, scale = 0)
	public float getPsTaxRateFl() {
		return this.psTaxRateFl;
	}

	public void setPsTaxRateFl(float psTaxRateFl) {
		this.psTaxRateFl = psTaxRateFl;
	}

	@Column(name = "PsCalcTaxOnShippingAddressBl", nullable = false)
	public boolean isPsCalcTaxOnShippingAddressBl() {
		return this.psCalcTaxOnShippingAddressBl;
	}

	public void setPsCalcTaxOnShippingAddressBl(boolean psCalcTaxOnShippingAddressBl) {
		this.psCalcTaxOnShippingAddressBl = psCalcTaxOnShippingAddressBl;
	}

	@Column(name = "PSChildrenCountIn", nullable = false)
	public int getPschildrenCountIn() {
		return this.pschildrenCountIn;
	}

	public void setPschildrenCountIn(int pschildrenCountIn) {
		this.pschildrenCountIn = pschildrenCountIn;
	}

	@Column(name = "CCCostCenterId", nullable = false)
	public int getCccostCenterId() {
		return this.cccostCenterId;
	}

	public void setCccostCenterId(int cccostCenterId) {
		this.cccostCenterId = cccostCenterId;
	}

	@Column(name = "Z5StoreId", nullable = false)
	public short getZ5storeId() {
		return this.z5storeId;
	}

	public void setZ5storeId(short z5storeId) {
		this.z5storeId = z5storeId;
	}

	@Column(name = "ZmStoreId", nullable = false)
	public short getZmStoreId() {
		return this.zmStoreId;
	}

	public void setZmStoreId(short zmStoreId) {
		this.zmStoreId = zmStoreId;
	}

	@Column(name = "ZlStoreId", nullable = false)
	public short getZlStoreId() {
		return this.zlStoreId;
	}

	public void setZlStoreId(short zlStoreId) {
		this.zlStoreId = zlStoreId;
	}

	@Column(name = "SIDisplayOrderIn", nullable = false)
	public int getSidisplayOrderIn() {
		return this.sidisplayOrderIn;
	}

	public void setSidisplayOrderIn(int sidisplayOrderIn) {
		this.sidisplayOrderIn = sidisplayOrderIn;
	}

	@Column(name = "SIParentID_N")
	public Integer getSiparentIdN() {
		return this.siparentIdN;
	}

	public void setSiparentIdN(Integer siparentIdN) {
		this.siparentIdN = siparentIdN;
	}

	@Column(name = "SIPackageBl", nullable = false)
	public boolean isSipackageBl() {
		return this.sipackageBl;
	}

	public void setSipackageBl(boolean sipackageBl) {
		this.sipackageBl = sipackageBl;
	}

	@Column(name = "SIEOLShowPackagePageBl", nullable = false)
	public boolean isSieolshowPackagePageBl() {
		return this.sieolshowPackagePageBl;
	}

	public void setSieolshowPackagePageBl(boolean sieolshowPackagePageBl) {
		this.sieolshowPackagePageBl = sieolshowPackagePageBl;
	}

	@Column(name = "SIPackageItemsIncludedBl", nullable = false)
	public boolean isSipackageItemsIncludedBl() {
		return this.sipackageItemsIncludedBl;
	}

	public void setSipackageItemsIncludedBl(boolean sipackageItemsIncludedBl) {
		this.sipackageItemsIncludedBl = sipackageItemsIncludedBl;
	}

	@Column(name = "SIClickActionID", nullable = false)
	public int getSiclickActionId() {
		return this.siclickActionId;
	}

	public void setSiclickActionId(int siclickActionId) {
		this.siclickActionId = siclickActionId;
	}

	@Column(name = "SIClickActionParamsTx_N")
	public String getSiclickActionParamsTxN() {
		return this.siclickActionParamsTxN;
	}

	public void setSiclickActionParamsTxN(String siclickActionParamsTxN) {
		this.siclickActionParamsTxN = siclickActionParamsTxN;
	}

	@Column(name = "SIClickActionPromptTx_N")
	public String getSiclickActionPromptTxN() {
		return this.siclickActionPromptTxN;
	}

	public void setSiclickActionPromptTxN(String siclickActionPromptTxN) {
		this.siclickActionPromptTxN = siclickActionPromptTxN;
	}

	@Column(name = "SIClickUrlTextTx_N")
	public String getSiclickUrlTextTxN() {
		return this.siclickUrlTextTxN;
	}

	public void setSiclickUrlTextTxN(String siclickUrlTextTxN) {
		this.siclickUrlTextTxN = siclickUrlTextTxN;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EolProductItemId))
			return false;
		EolProductItemId castOther = (EolProductItemId) other;

		return (this.getSistockItemId() == castOther.getSistockItemId())
				&& (this.getSistockTypeId() == castOther.getSistockTypeId())
				&& ((this.getStstockTypeTx() == castOther.getStstockTypeTx())
						|| (this.getStstockTypeTx() != null && castOther.getStstockTypeTx() != null
								&& this.getStstockTypeTx().equals(castOther.getStstockTypeTx())))
				&& ((this.getSistockItemTx() == castOther.getSistockItemTx())
						|| (this.getSistockItemTx() != null && castOther.getSistockItemTx() != null
								&& this.getSistockItemTx().equals(castOther.getSistockItemTx())))
				&& ((this.getSistockItem2txN() == castOther.getSistockItem2txN())
						|| (this.getSistockItem2txN() != null && castOther.getSistockItem2txN() != null
								&& this.getSistockItem2txN().equals(castOther.getSistockItem2txN())))
				&& ((this.getSistockNoTx() == castOther.getSistockNoTx())
						|| (this.getSistockNoTx() != null && castOther.getSistockNoTx() != null
								&& this.getSistockNoTx().equals(castOther.getSistockNoTx())))
				&& ((this.getSiimageUrltxN() == castOther.getSiimageUrltxN())
						|| (this.getSiimageUrltxN() != null && castOther.getSiimageUrltxN() != null
								&& this.getSiimageUrltxN().equals(castOther.getSiimageUrltxN())))
				&& ((this.getSiimageUrl2txN() == castOther.getSiimageUrl2txN())
						|| (this.getSiimageUrl2txN() != null && castOther.getSiimageUrl2txN() != null
								&& this.getSiimageUrl2txN().equals(castOther.getSiimageUrl2txN())))
				&& ((this.getSiimageUrl3txN() == castOther.getSiimageUrl3txN())
						|| (this.getSiimageUrl3txN() != null && castOther.getSiimageUrl3txN() != null
								&& this.getSiimageUrl3txN().equals(castOther.getSiimageUrl3txN())))
//				&& ((this.getSiimageUrl4txN() == castOther.getSiimageUrl4txN())
//						|| (this.getSiimageUrl4txN() != null && castOther.getSiimageUrl4txN() != null
//								&& this.getSiimageUrl4txN().equals(castOther.getSiimageUrl4txN())))
//				&& ((this.getSiimageUrl5txN() == castOther.getSiimageUrl5txN())
//						|| (this.getSiimageUrl5txN() != null && castOther.getSiimageUrl5txN() != null
//								&& this.getSiimageUrl5txN().equals(castOther.getSiimageUrl5txN())))
				&& ((this.getSivideoTxN() == castOther.getSivideoTxN()) || (this.getSivideoTxN() != null
						&& castOther.getSivideoTxN() != null && this.getSivideoTxN().equals(castOther.getSivideoTxN())))
				&& (this.isSimaintainStockLevelBl() == castOther.isSimaintainStockLevelBl())
				&& ((this.getPsunitCostMn() == castOther.getPsunitCostMn())
						|| (this.getPsunitCostMn() != null && castOther.getPsunitCostMn() != null
								&& this.getPsunitCostMn().equals(castOther.getPsunitCostMn())))
				&& ((this.getPsregularPriceMn() == castOther.getPsregularPriceMn())
						|| (this.getPsregularPriceMn() != null && castOther.getPsregularPriceMn() != null
								&& this.getPsregularPriceMn().equals(castOther.getPsregularPriceMn())))
				&& ((this.getPseolpriceMn() == castOther.getPseolpriceMn())
						|| (this.getPseolpriceMn() != null && castOther.getPseolpriceMn() != null
								&& this.getPseolpriceMn().equals(castOther.getPseolpriceMn())))
				&& ((this.getPsregularPriceComputedMn() == castOther.getPsregularPriceComputedMn())
						|| (this.getPsregularPriceComputedMn() != null
								&& castOther.getPsregularPriceComputedMn() != null
								&& this.getPsregularPriceComputedMn().equals(castOther.getPsregularPriceComputedMn())))
				&& ((this.getPseolpriceComputedMn() == castOther.getPseolpriceComputedMn())
						|| (this.getPseolpriceComputedMn() != null && castOther.getPseolpriceComputedMn() != null
								&& this.getPseolpriceComputedMn().equals(castOther.getPseolpriceComputedMn())))
				&& ((this.getSidescriptionTxN() == castOther.getSidescriptionTxN())
						|| (this.getSidescriptionTxN() != null && castOther.getSidescriptionTxN() != null
								&& this.getSidescriptionTxN().equals(castOther.getSidescriptionTxN())))
				&& ((this.getSispecialOfferTxN() == castOther.getSispecialOfferTxN())
						|| (this.getSispecialOfferTxN() != null && castOther.getSispecialOfferTxN() != null
								&& this.getSispecialOfferTxN().equals(castOther.getSispecialOfferTxN())))
				&& (this.getSimanufacturerId() == castOther.getSimanufacturerId())
				&& ((this.getSuSupplierTx() == castOther.getSuSupplierTx())
						|| (this.getSuSupplierTx() != null && castOther.getSuSupplierTx() != null
								&& this.getSuSupplierTx().equals(castOther.getSuSupplierTx())))
				&& (this.getZlMinStock1in() == castOther.getZlMinStock1in())
				&& (this.getPscurrentStockLevelIn() == castOther.getPscurrentStockLevelIn())
				&& (this.isZlDisplayOnWebBl() == castOther.isZlDisplayOnWebBl())
				&& (this.isSiserialNosBl() == castOther.isSiserialNosBl())
				&& ((this.getSieventDataTypeIdN() == castOther.getSieventDataTypeIdN())
						|| (this.getSieventDataTypeIdN() != null && castOther.getSieventDataTypeIdN() != null
								&& this.getSieventDataTypeIdN().equals(castOther.getSieventDataTypeIdN())))
				&& ((this.getSiprimaryColorIdN() == castOther.getSiprimaryColorIdN())
						|| (this.getSiprimaryColorIdN() != null && castOther.getSiprimaryColorIdN() != null
								&& this.getSiprimaryColorIdN().equals(castOther.getSiprimaryColorIdN())))
				&& ((this.getSisecondaryColorIdN() == castOther.getSisecondaryColorIdN())
						|| (this.getSisecondaryColorIdN() != null && castOther.getSisecondaryColorIdN() != null
								&& this.getSisecondaryColorIdN().equals(castOther.getSisecondaryColorIdN())))
				&& ((this.getSisizeIdN() == castOther.getSisizeIdN()) || (this.getSisizeIdN() != null
						&& castOther.getSisizeIdN() != null && this.getSisizeIdN().equals(castOther.getSisizeIdN())))
				&& ((this.getSiweightFlN() == castOther.getSiweightFlN())
						|| (this.getSiweightFlN() != null && castOther.getSiweightFlN() != null
								&& this.getSiweightFlN().equals(castOther.getSiweightFlN())))
				&& (this.isSishowPriceInEolbl() == castOther.isSishowPriceInEolbl())
				&& (this.getPsTaxRateFl() == castOther.getPsTaxRateFl())
				&& (this.isPsCalcTaxOnShippingAddressBl() == castOther.isPsCalcTaxOnShippingAddressBl())
				&& (this.getPschildrenCountIn() == castOther.getPschildrenCountIn())
				&& (this.getCccostCenterId() == castOther.getCccostCenterId())
				&& (this.getZ5storeId() == castOther.getZ5storeId())
				&& (this.getZmStoreId() == castOther.getZmStoreId())
				&& (this.getZlStoreId() == castOther.getZlStoreId())
				&& (this.getSidisplayOrderIn() == castOther.getSidisplayOrderIn())
				&& ((this.getSiparentIdN() == castOther.getSiparentIdN())
						|| (this.getSiparentIdN() != null && castOther.getSiparentIdN() != null
								&& this.getSiparentIdN().equals(castOther.getSiparentIdN())))
				&& (this.isSipackageBl() == castOther.isSipackageBl())
				&& (this.isSieolshowPackagePageBl() == castOther.isSieolshowPackagePageBl())
				&& (this.isSipackageItemsIncludedBl() == castOther.isSipackageItemsIncludedBl())
				&& (this.getSiclickActionId() == castOther.getSiclickActionId())
				&& ((this.getSiclickActionParamsTxN() == castOther.getSiclickActionParamsTxN())
						|| (this.getSiclickActionParamsTxN() != null && castOther.getSiclickActionParamsTxN() != null
								&& this.getSiclickActionParamsTxN().equals(castOther.getSiclickActionParamsTxN())))
				&& ((this.getSiclickActionPromptTxN() == castOther.getSiclickActionPromptTxN())
						|| (this.getSiclickActionPromptTxN() != null && castOther.getSiclickActionPromptTxN() != null
								&& this.getSiclickActionPromptTxN().equals(castOther.getSiclickActionPromptTxN())))
				&& ((this.getSiclickUrlTextTxN() == castOther.getSiclickUrlTextTxN())
						|| (this.getSiclickUrlTextTxN() != null && castOther.getSiclickUrlTextTxN() != null
								&& this.getSiclickUrlTextTxN().equals(castOther.getSiclickUrlTextTxN())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSistockItemId();
		result = 37 * result + this.getSistockTypeId();
		result = 37 * result + (getStstockTypeTx() == null ? 0 : this.getStstockTypeTx().hashCode());
		result = 37 * result + (getSistockItemTx() == null ? 0 : this.getSistockItemTx().hashCode());
		result = 37 * result + (getSistockItem2txN() == null ? 0 : this.getSistockItem2txN().hashCode());
		result = 37 * result + (getSistockNoTx() == null ? 0 : this.getSistockNoTx().hashCode());
		result = 37 * result + (getSiimageUrltxN() == null ? 0 : this.getSiimageUrltxN().hashCode());
		result = 37 * result + (getSiimageUrl2txN() == null ? 0 : this.getSiimageUrl2txN().hashCode());
		result = 37 * result + (getSiimageUrl3txN() == null ? 0 : this.getSiimageUrl3txN().hashCode());
//		result = 37 * result + (getSiimageUrl4txN() == null ? 0 : this.getSiimageUrl4txN().hashCode());
//		result = 37 * result + (getSiimageUrl5txN() == null ? 0 : this.getSiimageUrl5txN().hashCode());
		result = 37 * result + (getSivideoTxN() == null ? 0 : this.getSivideoTxN().hashCode());
		result = 37 * result + (this.isSimaintainStockLevelBl() ? 1 : 0);
		result = 37 * result + (getPsunitCostMn() == null ? 0 : this.getPsunitCostMn().hashCode());
		result = 37 * result + (getPsregularPriceMn() == null ? 0 : this.getPsregularPriceMn().hashCode());
		result = 37 * result + (getPseolpriceMn() == null ? 0 : this.getPseolpriceMn().hashCode());
		result = 37 * result
				+ (getPsregularPriceComputedMn() == null ? 0 : this.getPsregularPriceComputedMn().hashCode());
		result = 37 * result + (getPseolpriceComputedMn() == null ? 0 : this.getPseolpriceComputedMn().hashCode());
		result = 37 * result + (getSidescriptionTxN() == null ? 0 : this.getSidescriptionTxN().hashCode());
		result = 37 * result + (getSispecialOfferTxN() == null ? 0 : this.getSispecialOfferTxN().hashCode());
		result = 37 * result + this.getSimanufacturerId();
		result = 37 * result + (getSuSupplierTx() == null ? 0 : this.getSuSupplierTx().hashCode());
		result = 37 * result + this.getZlMinStock1in();
		result = 37 * result + this.getPscurrentStockLevelIn();
		result = 37 * result + (this.isZlDisplayOnWebBl() ? 1 : 0);
		result = 37 * result + (this.isSiserialNosBl() ? 1 : 0);
		result = 37 * result + (getSieventDataTypeIdN() == null ? 0 : this.getSieventDataTypeIdN().hashCode());
		result = 37 * result + (getSiprimaryColorIdN() == null ? 0 : this.getSiprimaryColorIdN().hashCode());
		result = 37 * result + (getSisecondaryColorIdN() == null ? 0 : this.getSisecondaryColorIdN().hashCode());
		result = 37 * result + (getSisizeIdN() == null ? 0 : this.getSisizeIdN().hashCode());
		result = 37 * result + (getSiweightFlN() == null ? 0 : this.getSiweightFlN().hashCode());
		result = 37 * result + (this.isSishowPriceInEolbl() ? 1 : 0);
		result = 37 * result + (int) this.getPsTaxRateFl();
		result = 37 * result + (this.isPsCalcTaxOnShippingAddressBl() ? 1 : 0);
		result = 37 * result + this.getPschildrenCountIn();
		result = 37 * result + this.getCccostCenterId();
		result = 37 * result + this.getZ5storeId();
		result = 37 * result + this.getZmStoreId();
		result = 37 * result + this.getZlStoreId();
		result = 37 * result + this.getSidisplayOrderIn();
		result = 37 * result + (getSiparentIdN() == null ? 0 : this.getSiparentIdN().hashCode());
		result = 37 * result + (this.isSipackageBl() ? 1 : 0);
		result = 37 * result + (this.isSieolshowPackagePageBl() ? 1 : 0);
		result = 37 * result + (this.isSipackageItemsIncludedBl() ? 1 : 0);
		result = 37 * result + this.getSiclickActionId();
		result = 37 * result + (getSiclickActionParamsTxN() == null ? 0 : this.getSiclickActionParamsTxN().hashCode());
		result = 37 * result + (getSiclickActionPromptTxN() == null ? 0 : this.getSiclickActionPromptTxN().hashCode());
		result = 37 * result + (getSiclickUrlTextTxN() == null ? 0 : this.getSiclickUrlTextTxN().hashCode());
		return result;
	}

}
