package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EolProductItem generated by hbm2java
 */
@Entity
@Table(name = "eol_ProductItem")
public class EolProductItem implements java.io.Serializable {

	private EolProductItemId id;

	public EolProductItem() {
	}

	public EolProductItem(EolProductItemId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "sistockItemId", column = @Column(name = "SIStockItemID", nullable = false)),
			@AttributeOverride(name = "sistockTypeId", column = @Column(name = "SIStockTypeID", nullable = false)),
			@AttributeOverride(name = "ststockTypeTx", column = @Column(name = "STStockTypeTx", nullable = false)),
			@AttributeOverride(name = "sistockItemTx", column = @Column(name = "SIStockItemTx", nullable = false)),
			@AttributeOverride(name = "sistockItem2txN", column = @Column(name = "SIStockItem2Tx_N")),
			@AttributeOverride(name = "sistockNoTx", column = @Column(name = "SIStockNoTx", nullable = false)),
			@AttributeOverride(name = "siimageUrltxN", column = @Column(name = "SIImageURLTx_N")),
			@AttributeOverride(name = "siimageUrl2txN", column = @Column(name = "SIImageURL2Tx_N")),
			@AttributeOverride(name = "siimageUrl3txN", column = @Column(name = "SIImageURL3Tx_N")),
			@AttributeOverride(name = "siimageUrl4txN", column = @Column(name = "SIImageURL4Tx_N")),
			@AttributeOverride(name = "siimageUrl5txN", column = @Column(name = "SIImageURL5Tx_N")),
			@AttributeOverride(name = "sivideoTxN", column = @Column(name = "SIVideoTx_N")),
			@AttributeOverride(name = "simaintainStockLevelBl", column = @Column(name = "SIMaintainStockLevelBl", nullable = false)),
			@AttributeOverride(name = "psunitCostMn", column = @Column(name = "PSUnitCostMn", nullable = false, scale = 4)),
			@AttributeOverride(name = "psregularPriceMn", column = @Column(name = "PSRegularPriceMn", nullable = false, scale = 4)),
			@AttributeOverride(name = "pseolpriceMn", column = @Column(name = "PSEOLPriceMn", nullable = false, scale = 4)),
			@AttributeOverride(name = "psregularPriceComputedMn", column = @Column(name = "PSRegularPriceComputedMn", nullable = false, scale = 4)),
			@AttributeOverride(name = "pseolpriceComputedMn", column = @Column(name = "PSEOLPriceComputedMn", nullable = false, scale = 4)),
			@AttributeOverride(name = "sidescriptionTxN", column = @Column(name = "SIDescriptionTx_N")),
			@AttributeOverride(name = "sispecialOfferTxN", column = @Column(name = "SISpecialOfferTx_N")),
			@AttributeOverride(name = "simanufacturerId", column = @Column(name = "SIManufacturerID", nullable = false)),
			@AttributeOverride(name = "suSupplierTx", column = @Column(name = "SuSupplierTx", nullable = false)),
			@AttributeOverride(name = "zlMinStock1in", column = @Column(name = "ZlMinStock1In", nullable = false)),
			@AttributeOverride(name = "pscurrentStockLevelIn", column = @Column(name = "PSCurrentStockLevelIn", nullable = false)),
			@AttributeOverride(name = "zlDisplayOnWebBl", column = @Column(name = "ZlDisplayOnWebBl", nullable = false)),
			@AttributeOverride(name = "siserialNosBl", column = @Column(name = "SISerialNosBl", nullable = false)),
			@AttributeOverride(name = "sieventDataTypeIdN", column = @Column(name = "SIEventDataTypeID_N")),
			@AttributeOverride(name = "siprimaryColorIdN", column = @Column(name = "SIPrimaryColorID_N")),
			@AttributeOverride(name = "sisecondaryColorIdN", column = @Column(name = "SISecondaryColorID_N")),
			@AttributeOverride(name = "sisizeIdN", column = @Column(name = "SISizeID_N")),
			@AttributeOverride(name = "siweightFlN", column = @Column(name = "SIWeightFl_N", precision = 53, scale = 0)),
			@AttributeOverride(name = "sishowPriceInEolbl", column = @Column(name = "SIShowPriceInEOLBl", nullable = false)),
			@AttributeOverride(name = "psTaxRateFl", column = @Column(name = "PsTaxRateFl", nullable = false, precision = 24, scale = 0)),
			@AttributeOverride(name = "psCalcTaxOnShippingAddressBl", column = @Column(name = "PsCalcTaxOnShippingAddressBl", nullable = false)),
			@AttributeOverride(name = "pschildrenCountIn", column = @Column(name = "PSChildrenCountIn", nullable = false)),
			@AttributeOverride(name = "cccostCenterId", column = @Column(name = "CCCostCenterId", nullable = false)),
			@AttributeOverride(name = "z5storeId", column = @Column(name = "Z5StoreId", nullable = false)),
			@AttributeOverride(name = "zmStoreId", column = @Column(name = "ZmStoreId", nullable = false)),
			@AttributeOverride(name = "zlStoreId", column = @Column(name = "ZlStoreId", nullable = false)),
			@AttributeOverride(name = "sidisplayOrderIn", column = @Column(name = "SIDisplayOrderIn", nullable = false)),
			@AttributeOverride(name = "siparentIdN", column = @Column(name = "SIParentID_N")),
			@AttributeOverride(name = "sipackageBl", column = @Column(name = "SIPackageBl", nullable = false)),
			@AttributeOverride(name = "sieolshowPackagePageBl", column = @Column(name = "SIEOLShowPackagePageBl", nullable = false)),
			@AttributeOverride(name = "sipackageItemsIncludedBl", column = @Column(name = "SIPackageItemsIncludedBl", nullable = false)),
			@AttributeOverride(name = "siclickActionId", column = @Column(name = "SIClickActionID", nullable = false)),
			@AttributeOverride(name = "siclickActionParamsTxN", column = @Column(name = "SIClickActionParamsTx_N")),
			@AttributeOverride(name = "siclickActionPromptTxN", column = @Column(name = "SIClickActionPromptTx_N")),
			@AttributeOverride(name = "siclickUrlTextTxN", column = @Column(name = "SIClickUrlTextTx_N")) })
	public EolProductItemId getId() {
		return this.id;
	}

	public void setId(EolProductItemId id) {
		this.id = id;
	}

}
