package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * S01AcAccountId generated by hbm2java
 */
@Embeddable
public class S01AcAccountId implements java.io.Serializable {

	private int acAccountId;
	private int acAccountTypeId;
	private int acCustId;
	private String acAccountNameTx;
	private Date acCreationDate;
	private BigDecimal acCreditLimitMn;
	private int acCostCenterId;
	private Date acClosedDateN;
	private Date acLastUpdatedDate;
	private short acCurrencyId;
	private float acExchangeRateFl;
	private BigDecimal acBalanceMn;
	private short acStoreId;

	public S01AcAccountId() {
	}

	public S01AcAccountId(int acAccountId, int acAccountTypeId, int acCustId, String acAccountNameTx,
			Date acCreationDate, BigDecimal acCreditLimitMn, int acCostCenterId, Date acLastUpdatedDate,
			short acCurrencyId, float acExchangeRateFl, BigDecimal acBalanceMn, short acStoreId) {
		this.acAccountId = acAccountId;
		this.acAccountTypeId = acAccountTypeId;
		this.acCustId = acCustId;
		this.acAccountNameTx = acAccountNameTx;
		this.acCreationDate = acCreationDate;
		this.acCreditLimitMn = acCreditLimitMn;
		this.acCostCenterId = acCostCenterId;
		this.acLastUpdatedDate = acLastUpdatedDate;
		this.acCurrencyId = acCurrencyId;
		this.acExchangeRateFl = acExchangeRateFl;
		this.acBalanceMn = acBalanceMn;
		this.acStoreId = acStoreId;
	}

	public S01AcAccountId(int acAccountId, int acAccountTypeId, int acCustId, String acAccountNameTx,
			Date acCreationDate, BigDecimal acCreditLimitMn, int acCostCenterId, Date acClosedDateN,
			Date acLastUpdatedDate, short acCurrencyId, float acExchangeRateFl, BigDecimal acBalanceMn,
			short acStoreId) {
		this.acAccountId = acAccountId;
		this.acAccountTypeId = acAccountTypeId;
		this.acCustId = acCustId;
		this.acAccountNameTx = acAccountNameTx;
		this.acCreationDate = acCreationDate;
		this.acCreditLimitMn = acCreditLimitMn;
		this.acCostCenterId = acCostCenterId;
		this.acClosedDateN = acClosedDateN;
		this.acLastUpdatedDate = acLastUpdatedDate;
		this.acCurrencyId = acCurrencyId;
		this.acExchangeRateFl = acExchangeRateFl;
		this.acBalanceMn = acBalanceMn;
		this.acStoreId = acStoreId;
	}

	@Column(name = "AcAccountID", nullable = false)
	public int getAcAccountId() {
		return this.acAccountId;
	}

	public void setAcAccountId(int acAccountId) {
		this.acAccountId = acAccountId;
	}

	@Column(name = "AcAccountTypeID", nullable = false)
	public int getAcAccountTypeId() {
		return this.acAccountTypeId;
	}

	public void setAcAccountTypeId(int acAccountTypeId) {
		this.acAccountTypeId = acAccountTypeId;
	}

	@Column(name = "AcCustID", nullable = false)
	public int getAcCustId() {
		return this.acCustId;
	}

	public void setAcCustId(int acCustId) {
		this.acCustId = acCustId;
	}

	@Column(name = "AcAccountNameTx", nullable = false)
	public String getAcAccountNameTx() {
		return this.acAccountNameTx;
	}

	public void setAcAccountNameTx(String acAccountNameTx) {
		this.acAccountNameTx = acAccountNameTx;
	}

	@Column(name = "AcCreationDate", nullable = false, length = 23)
	public Date getAcCreationDate() {
		return this.acCreationDate;
	}

	public void setAcCreationDate(Date acCreationDate) {
		this.acCreationDate = acCreationDate;
	}

	@Column(name = "AcCreditLimitMn", nullable = false, scale = 4)
	public BigDecimal getAcCreditLimitMn() {
		return this.acCreditLimitMn;
	}

	public void setAcCreditLimitMn(BigDecimal acCreditLimitMn) {
		this.acCreditLimitMn = acCreditLimitMn;
	}

	@Column(name = "AcCostCenterID", nullable = false)
	public int getAcCostCenterId() {
		return this.acCostCenterId;
	}

	public void setAcCostCenterId(int acCostCenterId) {
		this.acCostCenterId = acCostCenterId;
	}

	@Column(name = "AcClosedDate_N", length = 23)
	public Date getAcClosedDateN() {
		return this.acClosedDateN;
	}

	public void setAcClosedDateN(Date acClosedDateN) {
		this.acClosedDateN = acClosedDateN;
	}

	@Column(name = "AcLastUpdatedDate", nullable = false, length = 23)
	public Date getAcLastUpdatedDate() {
		return this.acLastUpdatedDate;
	}

	public void setAcLastUpdatedDate(Date acLastUpdatedDate) {
		this.acLastUpdatedDate = acLastUpdatedDate;
	}

	@Column(name = "AcCurrencyID", nullable = false)
	public short getAcCurrencyId() {
		return this.acCurrencyId;
	}

	public void setAcCurrencyId(short acCurrencyId) {
		this.acCurrencyId = acCurrencyId;
	}

	@Column(name = "AcExchangeRateFl", nullable = false, precision = 24, scale = 0)
	public float getAcExchangeRateFl() {
		return this.acExchangeRateFl;
	}

	public void setAcExchangeRateFl(float acExchangeRateFl) {
		this.acExchangeRateFl = acExchangeRateFl;
	}

	@Column(name = "AcBalanceMn", nullable = false, scale = 4)
	public BigDecimal getAcBalanceMn() {
		return this.acBalanceMn;
	}

	public void setAcBalanceMn(BigDecimal acBalanceMn) {
		this.acBalanceMn = acBalanceMn;
	}

	@Column(name = "AcStoreID", nullable = false)
	public short getAcStoreId() {
		return this.acStoreId;
	}

	public void setAcStoreId(short acStoreId) {
		this.acStoreId = acStoreId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof S01AcAccountId))
			return false;
		S01AcAccountId castOther = (S01AcAccountId) other;

		return (this.getAcAccountId() == castOther.getAcAccountId())
				&& (this.getAcAccountTypeId() == castOther.getAcAccountTypeId())
				&& (this.getAcCustId() == castOther.getAcCustId())
				&& ((this.getAcAccountNameTx() == castOther.getAcAccountNameTx())
						|| (this.getAcAccountNameTx() != null && castOther.getAcAccountNameTx() != null
								&& this.getAcAccountNameTx().equals(castOther.getAcAccountNameTx())))
				&& ((this.getAcCreationDate() == castOther.getAcCreationDate())
						|| (this.getAcCreationDate() != null && castOther.getAcCreationDate() != null
								&& this.getAcCreationDate().equals(castOther.getAcCreationDate())))
				&& ((this.getAcCreditLimitMn() == castOther.getAcCreditLimitMn())
						|| (this.getAcCreditLimitMn() != null && castOther.getAcCreditLimitMn() != null
								&& this.getAcCreditLimitMn().equals(castOther.getAcCreditLimitMn())))
				&& (this.getAcCostCenterId() == castOther.getAcCostCenterId())
				&& ((this.getAcClosedDateN() == castOther.getAcClosedDateN())
						|| (this.getAcClosedDateN() != null && castOther.getAcClosedDateN() != null
								&& this.getAcClosedDateN().equals(castOther.getAcClosedDateN())))
				&& ((this.getAcLastUpdatedDate() == castOther.getAcLastUpdatedDate())
						|| (this.getAcLastUpdatedDate() != null && castOther.getAcLastUpdatedDate() != null
								&& this.getAcLastUpdatedDate().equals(castOther.getAcLastUpdatedDate())))
				&& (this.getAcCurrencyId() == castOther.getAcCurrencyId())
				&& (this.getAcExchangeRateFl() == castOther.getAcExchangeRateFl())
				&& ((this.getAcBalanceMn() == castOther.getAcBalanceMn())
						|| (this.getAcBalanceMn() != null && castOther.getAcBalanceMn() != null
								&& this.getAcBalanceMn().equals(castOther.getAcBalanceMn())))
				&& (this.getAcStoreId() == castOther.getAcStoreId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAcAccountId();
		result = 37 * result + this.getAcAccountTypeId();
		result = 37 * result + this.getAcCustId();
		result = 37 * result + (getAcAccountNameTx() == null ? 0 : this.getAcAccountNameTx().hashCode());
		result = 37 * result + (getAcCreationDate() == null ? 0 : this.getAcCreationDate().hashCode());
		result = 37 * result + (getAcCreditLimitMn() == null ? 0 : this.getAcCreditLimitMn().hashCode());
		result = 37 * result + this.getAcCostCenterId();
		result = 37 * result + (getAcClosedDateN() == null ? 0 : this.getAcClosedDateN().hashCode());
		result = 37 * result + (getAcLastUpdatedDate() == null ? 0 : this.getAcLastUpdatedDate().hashCode());
		result = 37 * result + this.getAcCurrencyId();
		result = 37 * result + (int) this.getAcExchangeRateFl();
		result = 37 * result + (getAcBalanceMn() == null ? 0 : this.getAcBalanceMn().hashCode());
		result = 37 * result + this.getAcStoreId();
		return result;
	}

}
