package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * S01CacertAgency generated by hbm2java
 */
@Entity
@Table(name = "s01_CACertAgency")
public class S01CacertAgency implements java.io.Serializable {

	private S01CacertAgencyId id;

	public S01CacertAgency() {
	}

	public S01CacertAgency(S01CacertAgencyId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cacertAgencyId", column = @Column(name = "CACertAgencyID", nullable = false)),
			@AttributeOverride(name = "cacontactTxN", column = @Column(name = "CAContactTx_N")),
			@AttributeOverride(name = "cacertAgencyTx", column = @Column(name = "CACertAgencyTx", nullable = false)),
			@AttributeOverride(name = "caaddress1txN", column = @Column(name = "CAAddress1Tx_N")),
			@AttributeOverride(name = "caaddress2txN", column = @Column(name = "CAAddress2Tx_N")),
			@AttributeOverride(name = "caaddress3txN", column = @Column(name = "CAAddress3Tx_N")),
			@AttributeOverride(name = "caaddress4txN", column = @Column(name = "CAAddress4Tx_N")),
			@AttributeOverride(name = "capostcodeTxN", column = @Column(name = "CAPostcodeTx_N")),
			@AttributeOverride(name = "cacountryTxN", column = @Column(name = "CACountryTx_N")),
			@AttributeOverride(name = "catelTxN", column = @Column(name = "CATelTx_N")),
			@AttributeOverride(name = "cafaxTxN", column = @Column(name = "CAFaxTx_N")),
			@AttributeOverride(name = "caemailTxN", column = @Column(name = "CAEMailTx_N")),
			@AttributeOverride(name = "caurltxN", column = @Column(name = "CAURLTx_N")),
			@AttributeOverride(name = "calastUpdatedDate", column = @Column(name = "CALastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "caunavailableBl", column = @Column(name = "CAUnavailableBl", nullable = false)),
			@AttributeOverride(name = "capicurltxN", column = @Column(name = "CAPICURLTx_N")),
			@AttributeOverride(name = "carequiredBl", column = @Column(name = "CARequiredBl", nullable = false)),
			@AttributeOverride(name = "cacreationDate", column = @Column(name = "CACreationDate", nullable = false, length = 23)) })
	public S01CacertAgencyId getId() {
		return this.id;
	}

	public void setId(S01CacertAgencyId id) {
		this.id = id;
	}

}
