package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * S01CsCourse generated by hbm2java
 */
@Entity
@Table(name = "s01_CsCourse")
public class S01CsCourse implements java.io.Serializable {

	private S01CsCourseId id;

	public S01CsCourse() {
	}

	public S01CsCourse(S01CsCourseId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "csCourseId", column = @Column(name = "CsCourseID", nullable = false)),
			@AttributeOverride(name = "csStoreId", column = @Column(name = "CsStoreID", nullable = false)),
			@AttributeOverride(name = "csCourseTypeId", column = @Column(name = "CsCourseTypeID", nullable = false)),
			@AttributeOverride(name = "csCourseNoTx", column = @Column(name = "CsCourseNoTx", nullable = false)),
			@AttributeOverride(name = "csStartDate", column = @Column(name = "CsStartDate", nullable = false, length = 23)),
			@AttributeOverride(name = "csEndDate", column = @Column(name = "CsEndDate", nullable = false, length = 23)),
			@AttributeOverride(name = "csNotesTxN", column = @Column(name = "CsNotesTx_N")),
			@AttributeOverride(name = "csLastUpdatedDate", column = @Column(name = "CsLastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "csMinNoIn", column = @Column(name = "CsMinNoIn", nullable = false)),
			@AttributeOverride(name = "csMaxNoIn", column = @Column(name = "CsMaxNoIn", nullable = false)),
			@AttributeOverride(name = "csCreationDate", column = @Column(name = "CsCreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "csCourseStatusId", column = @Column(name = "CsCourseStatusID")),
			@AttributeOverride(name = "csLanguageIdN", column = @Column(name = "CsLanguageID_N")),
			@AttributeOverride(name = "csPrivateNotesTxN", column = @Column(name = "CsPrivateNotesTx_N")),
			@AttributeOverride(name = "csLocationIdN", column = @Column(name = "CsLocationId_N")),
			@AttributeOverride(name = "csWaitingListCapacityIn", column = @Column(name = "CsWaitingListCapacityIn", nullable = false)),
			@AttributeOverride(name = "csAvailableWaitingListPlacesIn", column = @Column(name = "CsAvailableWaitingListPlacesIn", nullable = false)),
			@AttributeOverride(name = "csTermIdN", column = @Column(name = "CsTermID_N")),
			@AttributeOverride(name = "csPreviousTermPreviousCourseIdN", column = @Column(name = "CsPreviousTermPreviousCourseID_N")),
			@AttributeOverride(name = "csCurrentTermPreviousCourseIdN", column = @Column(name = "CsCurrentTermPreviousCourseID_N")),
			@AttributeOverride(name = "csMoreInfoTxN", column = @Column(name = "CsMoreInfoTx_N")) })
	public S01CsCourseId getId() {
		return this.id;
	}

	public void setId(S01CsCourseId id) {
		this.id = id;
	}

}
