package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * S01ChCustTypeId generated by hbm2java
 */
@Embeddable
public class S01ChCustTypeId implements java.io.Serializable {

	private int chCustTypeId;
	private String chCustTypeTx;
	private boolean chDiscountableBl;
	private boolean chCourseRoleBl;
	private boolean chTripRoleBl;
	private boolean chUnavailableBl;
	private Date chLastUpdatedDate;
	private boolean chRequiredBl;
	private Date chCreationDate;
	private boolean chEmployeeBl;
	private boolean chTripCustTypeBl;
	private String chInvoiceTextTxN;
	private boolean chSupportStaffBl;

	public S01ChCustTypeId() {
	}

	public S01ChCustTypeId(int chCustTypeId, String chCustTypeTx, boolean chDiscountableBl,
			boolean chCourseRoleBl, boolean chTripRoleBl, boolean chUnavailableBl, Date chLastUpdatedDate,
			boolean chRequiredBl, Date chCreationDate, boolean chEmployeeBl, boolean chTripCustTypeBl,
			boolean chSupportStaffBl) {
		this.chCustTypeId = chCustTypeId;
		this.chCustTypeTx = chCustTypeTx;
		this.chDiscountableBl = chDiscountableBl;
		this.chCourseRoleBl = chCourseRoleBl;
		this.chTripRoleBl = chTripRoleBl;
		this.chUnavailableBl = chUnavailableBl;
		this.chLastUpdatedDate = chLastUpdatedDate;
		this.chRequiredBl = chRequiredBl;
		this.chCreationDate = chCreationDate;
		this.chEmployeeBl = chEmployeeBl;
		this.chTripCustTypeBl = chTripCustTypeBl;
		this.chSupportStaffBl = chSupportStaffBl;
	}

	public S01ChCustTypeId(int chCustTypeId, String chCustTypeTx, boolean chDiscountableBl,
			boolean chCourseRoleBl, boolean chTripRoleBl, boolean chUnavailableBl, Date chLastUpdatedDate,
			boolean chRequiredBl, Date chCreationDate, boolean chEmployeeBl, boolean chTripCustTypeBl,
			String chInvoiceTextTxN, boolean chSupportStaffBl) {
		this.chCustTypeId = chCustTypeId;
		this.chCustTypeTx = chCustTypeTx;
		this.chDiscountableBl = chDiscountableBl;
		this.chCourseRoleBl = chCourseRoleBl;
		this.chTripRoleBl = chTripRoleBl;
		this.chUnavailableBl = chUnavailableBl;
		this.chLastUpdatedDate = chLastUpdatedDate;
		this.chRequiredBl = chRequiredBl;
		this.chCreationDate = chCreationDate;
		this.chEmployeeBl = chEmployeeBl;
		this.chTripCustTypeBl = chTripCustTypeBl;
		this.chInvoiceTextTxN = chInvoiceTextTxN;
		this.chSupportStaffBl = chSupportStaffBl;
	}

	@Column(name = "ChCustTypeID", nullable = false)
	public int getChCustTypeId() {
		return this.chCustTypeId;
	}

	public void setChCustTypeId(int chCustTypeId) {
		this.chCustTypeId = chCustTypeId;
	}

	@Column(name = "ChCustTypeTx", nullable = false)
	public String getChCustTypeTx() {
		return this.chCustTypeTx;
	}

	public void setChCustTypeTx(String chCustTypeTx) {
		this.chCustTypeTx = chCustTypeTx;
	}

	@Column(name = "ChDiscountableBl", nullable = false)
	public boolean isChDiscountableBl() {
		return this.chDiscountableBl;
	}

	public void setChDiscountableBl(boolean chDiscountableBl) {
		this.chDiscountableBl = chDiscountableBl;
	}

	@Column(name = "ChCourseRoleBl", nullable = false)
	public boolean isChCourseRoleBl() {
		return this.chCourseRoleBl;
	}

	public void setChCourseRoleBl(boolean chCourseRoleBl) {
		this.chCourseRoleBl = chCourseRoleBl;
	}

	@Column(name = "ChTripRoleBl", nullable = false)
	public boolean isChTripRoleBl() {
		return this.chTripRoleBl;
	}

	public void setChTripRoleBl(boolean chTripRoleBl) {
		this.chTripRoleBl = chTripRoleBl;
	}

	@Column(name = "ChUnavailableBl", nullable = false)
	public boolean isChUnavailableBl() {
		return this.chUnavailableBl;
	}

	public void setChUnavailableBl(boolean chUnavailableBl) {
		this.chUnavailableBl = chUnavailableBl;
	}

	@Column(name = "ChLastUpdatedDate", nullable = false, length = 23)
	public Date getChLastUpdatedDate() {
		return this.chLastUpdatedDate;
	}

	public void setChLastUpdatedDate(Date chLastUpdatedDate) {
		this.chLastUpdatedDate = chLastUpdatedDate;
	}

	@Column(name = "ChRequiredBl", nullable = false)
	public boolean isChRequiredBl() {
		return this.chRequiredBl;
	}

	public void setChRequiredBl(boolean chRequiredBl) {
		this.chRequiredBl = chRequiredBl;
	}

	@Column(name = "ChCreationDate", nullable = false, length = 23)
	public Date getChCreationDate() {
		return this.chCreationDate;
	}

	public void setChCreationDate(Date chCreationDate) {
		this.chCreationDate = chCreationDate;
	}

	@Column(name = "ChEmployeeBl", nullable = false)
	public boolean isChEmployeeBl() {
		return this.chEmployeeBl;
	}

	public void setChEmployeeBl(boolean chEmployeeBl) {
		this.chEmployeeBl = chEmployeeBl;
	}

	@Column(name = "ChTripCustTypeBl", nullable = false)
	public boolean isChTripCustTypeBl() {
		return this.chTripCustTypeBl;
	}

	public void setChTripCustTypeBl(boolean chTripCustTypeBl) {
		this.chTripCustTypeBl = chTripCustTypeBl;
	}

	@Column(name = "ChInvoiceTextTx_N")
	public String getChInvoiceTextTxN() {
		return this.chInvoiceTextTxN;
	}

	public void setChInvoiceTextTxN(String chInvoiceTextTxN) {
		this.chInvoiceTextTxN = chInvoiceTextTxN;
	}

	@Column(name = "ChSupportStaffBl", nullable = false)
	public boolean isChSupportStaffBl() {
		return this.chSupportStaffBl;
	}

	public void setChSupportStaffBl(boolean chSupportStaffBl) {
		this.chSupportStaffBl = chSupportStaffBl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof S01ChCustTypeId))
			return false;
		S01ChCustTypeId castOther = (S01ChCustTypeId) other;

		return (this.getChCustTypeId() == castOther.getChCustTypeId())
				&& ((this.getChCustTypeTx() == castOther.getChCustTypeTx())
						|| (this.getChCustTypeTx() != null && castOther.getChCustTypeTx() != null
								&& this.getChCustTypeTx().equals(castOther.getChCustTypeTx())))
				&& (this.isChDiscountableBl() == castOther.isChDiscountableBl())
				&& (this.isChCourseRoleBl() == castOther.isChCourseRoleBl())
				&& (this.isChTripRoleBl() == castOther.isChTripRoleBl())
				&& (this.isChUnavailableBl() == castOther.isChUnavailableBl())
				&& ((this.getChLastUpdatedDate() == castOther.getChLastUpdatedDate())
						|| (this.getChLastUpdatedDate() != null && castOther.getChLastUpdatedDate() != null
								&& this.getChLastUpdatedDate().equals(castOther.getChLastUpdatedDate())))
				&& (this.isChRequiredBl() == castOther.isChRequiredBl())
				&& ((this.getChCreationDate() == castOther.getChCreationDate())
						|| (this.getChCreationDate() != null && castOther.getChCreationDate() != null
								&& this.getChCreationDate().equals(castOther.getChCreationDate())))
				&& (this.isChEmployeeBl() == castOther.isChEmployeeBl())
				&& (this.isChTripCustTypeBl() == castOther.isChTripCustTypeBl())
				&& ((this.getChInvoiceTextTxN() == castOther.getChInvoiceTextTxN())
						|| (this.getChInvoiceTextTxN() != null && castOther.getChInvoiceTextTxN() != null
								&& this.getChInvoiceTextTxN().equals(castOther.getChInvoiceTextTxN())))
				&& (this.isChSupportStaffBl() == castOther.isChSupportStaffBl());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getChCustTypeId();
		result = 37 * result + (getChCustTypeTx() == null ? 0 : this.getChCustTypeTx().hashCode());
		result = 37 * result + (this.isChDiscountableBl() ? 1 : 0);
		result = 37 * result + (this.isChCourseRoleBl() ? 1 : 0);
		result = 37 * result + (this.isChTripRoleBl() ? 1 : 0);
		result = 37 * result + (this.isChUnavailableBl() ? 1 : 0);
		result = 37 * result + (getChLastUpdatedDate() == null ? 0 : this.getChLastUpdatedDate().hashCode());
		result = 37 * result + (this.isChRequiredBl() ? 1 : 0);
		result = 37 * result + (getChCreationDate() == null ? 0 : this.getChCreationDate().hashCode());
		result = 37 * result + (this.isChEmployeeBl() ? 1 : 0);
		result = 37 * result + (this.isChTripCustTypeBl() ? 1 : 0);
		result = 37 * result + (getChInvoiceTextTxN() == null ? 0 : this.getChInvoiceTextTxN().hashCode());
		result = 37 * result + (this.isChSupportStaffBl() ? 1 : 0);
		return result;
	}

}
