package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * S01CnContact generated by hbm2java
 */
@Entity
@Table(name = "s01_CnContact")
public class S01CnContact implements java.io.Serializable {

	private S01CnContactId id;

	public S01CnContact() {
	}

	public S01CnContact(S01CnContactId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cnContactId", column = @Column(name = "CnContactID", nullable = false)),
			@AttributeOverride(name = "cnCustId", column = @Column(name = "CnCustID", nullable = false)),
			@AttributeOverride(name = "cnCustInterestIdN", column = @Column(name = "CnCustInterestID_N")),
			@AttributeOverride(name = "cnCreationDate", column = @Column(name = "CnCreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "cnLastUpdatedDate", column = @Column(name = "CnLastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "cnContactMethodId", column = @Column(name = "CnContactMethodID", nullable = false)),
			@AttributeOverride(name = "cnEmpIdN", column = @Column(name = "CnEmpID_N")),
			@AttributeOverride(name = "cnActionId", column = @Column(name = "CnActionID", nullable = false)),
			@AttributeOverride(name = "cnNotesTxN", column = @Column(name = "CnNotesTx_N")),
			@AttributeOverride(name = "cnActualDateN", column = @Column(name = "CnActualDate_N", length = 23)),
			@AttributeOverride(name = "cnProposedDate", column = @Column(name = "CnProposedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "cnReminderDate", column = @Column(name = "CnReminderDate", nullable = false, length = 23)),
			@AttributeOverride(name = "cnSmsreminderBl", column = @Column(name = "CnSMSReminderBl", nullable = false)),
			@AttributeOverride(name = "cnSmssentDate", column = @Column(name = "CnSMSSentDate", length = 23)),
			@AttributeOverride(name = "cnProposedEndDateN", column = @Column(name = "CnProposedEndDate_N", length = 23)),
			@AttributeOverride(name = "cnActualEndDateN", column = @Column(name = "CnActualEndDate_N", length = 23)),
			@AttributeOverride(name = "cnStoreId", column = @Column(name = "CnStoreID", nullable = false)),
			@AttributeOverride(name = "cnOrigInvoiceIdN", column = @Column(name = "CnOrigInvoiceID_N")),
			@AttributeOverride(name = "cnStreetAddressTxN", column = @Column(name = "CnStreetAddressTx_N")),
			@AttributeOverride(name = "cnPostcodeTxN", column = @Column(name = "CnPostcodeTx_N")) })
	public S01CnContactId getId() {
		return this.id;
	}

	public void setId(S01CnContactId id) {
		this.id = id;
	}

}
