package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * S01CccostCenter generated by hbm2java
 */
@Entity
@Table(name = "s01_CCCostCenter")
public class S01CccostCenter implements java.io.Serializable {

	private S01CccostCenterId id;

	public S01CccostCenter() {
	}

	public S01CccostCenter(S01CccostCenterId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cccostCenterId", column = @Column(name = "CCCostCenterID", nullable = false)),
			@AttributeOverride(name = "cccostCenterTx", column = @Column(name = "CCCostCenterTx", nullable = false)),
			@AttributeOverride(name = "cctaxRegNoTxN", column = @Column(name = "CCTaxRegNoTx_N")),
			@AttributeOverride(name = "ccsloganTxN", column = @Column(name = "CCSloganTx_N")),
			@AttributeOverride(name = "ccunavailableBl", column = @Column(name = "CCUnavailableBl", nullable = false)),
			@AttributeOverride(name = "cclastUpdatedDate", column = @Column(name = "CCLastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "ccrequiredBl", column = @Column(name = "CCRequiredBl", nullable = false)),
			@AttributeOverride(name = "cccoRegNoTxN", column = @Column(name = "CCCoRegNoTx_N")),
			@AttributeOverride(name = "cccompanyFileTxN", column = @Column(name = "CCCompanyFileTx_N")),
			@AttributeOverride(name = "cccreationDate", column = @Column(name = "CCCreationDate", nullable = false, length = 23)) })
	public S01CccostCenterId getId() {
		return this.id;
	}

	public void setId(S01CccostCenterId id) {
		this.id = id;
	}

}
