package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * S01CsCourseId generated by hbm2java
 */
@Embeddable
public class S01CsCourseId implements java.io.Serializable {

	private int csCourseId;
	private short csStoreId;
	private int csCourseTypeId;
	private String csCourseNoTx;
	private Date csStartDate;
	private Date csEndDate;
	private String csNotesTxN;
	private Date csLastUpdatedDate;
	private short csMinNoIn;
	private short csMaxNoIn;
	private Date csCreationDate;
	private Integer csCourseStatusId;
	private Integer csLanguageIdN;
	private String csPrivateNotesTxN;
	private Integer csLocationIdN;
	private int csWaitingListCapacityIn;
	private int csAvailableWaitingListPlacesIn;
	private Integer csTermIdN;
	private Integer csPreviousTermPreviousCourseIdN;
	private Integer csCurrentTermPreviousCourseIdN;
	private String csMoreInfoTxN;

	public S01CsCourseId() {
	}

	public S01CsCourseId(int csCourseId, short csStoreId, int csCourseTypeId, String csCourseNoTx,
			Date csStartDate, Date csEndDate, Date csLastUpdatedDate, short csMinNoIn, short csMaxNoIn,
			Date csCreationDate, int csWaitingListCapacityIn, int csAvailableWaitingListPlacesIn) {
		this.csCourseId = csCourseId;
		this.csStoreId = csStoreId;
		this.csCourseTypeId = csCourseTypeId;
		this.csCourseNoTx = csCourseNoTx;
		this.csStartDate = csStartDate;
		this.csEndDate = csEndDate;
		this.csLastUpdatedDate = csLastUpdatedDate;
		this.csMinNoIn = csMinNoIn;
		this.csMaxNoIn = csMaxNoIn;
		this.csCreationDate = csCreationDate;
		this.csWaitingListCapacityIn = csWaitingListCapacityIn;
		this.csAvailableWaitingListPlacesIn = csAvailableWaitingListPlacesIn;
	}

	public S01CsCourseId(int csCourseId, short csStoreId, int csCourseTypeId, String csCourseNoTx,
			Date csStartDate, Date csEndDate, String csNotesTxN, Date csLastUpdatedDate, short csMinNoIn,
			short csMaxNoIn, Date csCreationDate, Integer csCourseStatusId, Integer csLanguageIdN,
			String csPrivateNotesTxN, Integer csLocationIdN, int csWaitingListCapacityIn,
			int csAvailableWaitingListPlacesIn, Integer csTermIdN, Integer csPreviousTermPreviousCourseIdN,
			Integer csCurrentTermPreviousCourseIdN, String csMoreInfoTxN) {
		this.csCourseId = csCourseId;
		this.csStoreId = csStoreId;
		this.csCourseTypeId = csCourseTypeId;
		this.csCourseNoTx = csCourseNoTx;
		this.csStartDate = csStartDate;
		this.csEndDate = csEndDate;
		this.csNotesTxN = csNotesTxN;
		this.csLastUpdatedDate = csLastUpdatedDate;
		this.csMinNoIn = csMinNoIn;
		this.csMaxNoIn = csMaxNoIn;
		this.csCreationDate = csCreationDate;
		this.csCourseStatusId = csCourseStatusId;
		this.csLanguageIdN = csLanguageIdN;
		this.csPrivateNotesTxN = csPrivateNotesTxN;
		this.csLocationIdN = csLocationIdN;
		this.csWaitingListCapacityIn = csWaitingListCapacityIn;
		this.csAvailableWaitingListPlacesIn = csAvailableWaitingListPlacesIn;
		this.csTermIdN = csTermIdN;
		this.csPreviousTermPreviousCourseIdN = csPreviousTermPreviousCourseIdN;
		this.csCurrentTermPreviousCourseIdN = csCurrentTermPreviousCourseIdN;
		this.csMoreInfoTxN = csMoreInfoTxN;
	}

	@Column(name = "CsCourseID", nullable = false)
	public int getCsCourseId() {
		return this.csCourseId;
	}

	public void setCsCourseId(int csCourseId) {
		this.csCourseId = csCourseId;
	}

	@Column(name = "CsStoreID", nullable = false)
	public short getCsStoreId() {
		return this.csStoreId;
	}

	public void setCsStoreId(short csStoreId) {
		this.csStoreId = csStoreId;
	}

	@Column(name = "CsCourseTypeID", nullable = false)
	public int getCsCourseTypeId() {
		return this.csCourseTypeId;
	}

	public void setCsCourseTypeId(int csCourseTypeId) {
		this.csCourseTypeId = csCourseTypeId;
	}

	@Column(name = "CsCourseNoTx", nullable = false)
	public String getCsCourseNoTx() {
		return this.csCourseNoTx;
	}

	public void setCsCourseNoTx(String csCourseNoTx) {
		this.csCourseNoTx = csCourseNoTx;
	}

	@Column(name = "CsStartDate", nullable = false, length = 23)
	public Date getCsStartDate() {
		return this.csStartDate;
	}

	public void setCsStartDate(Date csStartDate) {
		this.csStartDate = csStartDate;
	}

	@Column(name = "CsEndDate", nullable = false, length = 23)
	public Date getCsEndDate() {
		return this.csEndDate;
	}

	public void setCsEndDate(Date csEndDate) {
		this.csEndDate = csEndDate;
	}

	@Column(name = "CsNotesTx_N")
	public String getCsNotesTxN() {
		return this.csNotesTxN;
	}

	public void setCsNotesTxN(String csNotesTxN) {
		this.csNotesTxN = csNotesTxN;
	}

	@Column(name = "CsLastUpdatedDate", nullable = false, length = 23)
	public Date getCsLastUpdatedDate() {
		return this.csLastUpdatedDate;
	}

	public void setCsLastUpdatedDate(Date csLastUpdatedDate) {
		this.csLastUpdatedDate = csLastUpdatedDate;
	}

	@Column(name = "CsMinNoIn", nullable = false)
	public short getCsMinNoIn() {
		return this.csMinNoIn;
	}

	public void setCsMinNoIn(short csMinNoIn) {
		this.csMinNoIn = csMinNoIn;
	}

	@Column(name = "CsMaxNoIn", nullable = false)
	public short getCsMaxNoIn() {
		return this.csMaxNoIn;
	}

	public void setCsMaxNoIn(short csMaxNoIn) {
		this.csMaxNoIn = csMaxNoIn;
	}

	@Column(name = "CsCreationDate", nullable = false, length = 23)
	public Date getCsCreationDate() {
		return this.csCreationDate;
	}

	public void setCsCreationDate(Date csCreationDate) {
		this.csCreationDate = csCreationDate;
	}

	@Column(name = "CsCourseStatusID")
	public Integer getCsCourseStatusId() {
		return this.csCourseStatusId;
	}

	public void setCsCourseStatusId(Integer csCourseStatusId) {
		this.csCourseStatusId = csCourseStatusId;
	}

	@Column(name = "CsLanguageID_N")
	public Integer getCsLanguageIdN() {
		return this.csLanguageIdN;
	}

	public void setCsLanguageIdN(Integer csLanguageIdN) {
		this.csLanguageIdN = csLanguageIdN;
	}

	@Column(name = "CsPrivateNotesTx_N")
	public String getCsPrivateNotesTxN() {
		return this.csPrivateNotesTxN;
	}

	public void setCsPrivateNotesTxN(String csPrivateNotesTxN) {
		this.csPrivateNotesTxN = csPrivateNotesTxN;
	}

	@Column(name = "CsLocationId_N")
	public Integer getCsLocationIdN() {
		return this.csLocationIdN;
	}

	public void setCsLocationIdN(Integer csLocationIdN) {
		this.csLocationIdN = csLocationIdN;
	}

	@Column(name = "CsWaitingListCapacityIn", nullable = false)
	public int getCsWaitingListCapacityIn() {
		return this.csWaitingListCapacityIn;
	}

	public void setCsWaitingListCapacityIn(int csWaitingListCapacityIn) {
		this.csWaitingListCapacityIn = csWaitingListCapacityIn;
	}

	@Column(name = "CsAvailableWaitingListPlacesIn", nullable = false)
	public int getCsAvailableWaitingListPlacesIn() {
		return this.csAvailableWaitingListPlacesIn;
	}

	public void setCsAvailableWaitingListPlacesIn(int csAvailableWaitingListPlacesIn) {
		this.csAvailableWaitingListPlacesIn = csAvailableWaitingListPlacesIn;
	}

	@Column(name = "CsTermID_N")
	public Integer getCsTermIdN() {
		return this.csTermIdN;
	}

	public void setCsTermIdN(Integer csTermIdN) {
		this.csTermIdN = csTermIdN;
	}

	@Column(name = "CsPreviousTermPreviousCourseID_N")
	public Integer getCsPreviousTermPreviousCourseIdN() {
		return this.csPreviousTermPreviousCourseIdN;
	}

	public void setCsPreviousTermPreviousCourseIdN(Integer csPreviousTermPreviousCourseIdN) {
		this.csPreviousTermPreviousCourseIdN = csPreviousTermPreviousCourseIdN;
	}

	@Column(name = "CsCurrentTermPreviousCourseID_N")
	public Integer getCsCurrentTermPreviousCourseIdN() {
		return this.csCurrentTermPreviousCourseIdN;
	}

	public void setCsCurrentTermPreviousCourseIdN(Integer csCurrentTermPreviousCourseIdN) {
		this.csCurrentTermPreviousCourseIdN = csCurrentTermPreviousCourseIdN;
	}

	@Column(name = "CsMoreInfoTx_N")
	public String getCsMoreInfoTxN() {
		return this.csMoreInfoTxN;
	}

	public void setCsMoreInfoTxN(String csMoreInfoTxN) {
		this.csMoreInfoTxN = csMoreInfoTxN;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof S01CsCourseId))
			return false;
		S01CsCourseId castOther = (S01CsCourseId) other;

		return (this.getCsCourseId() == castOther.getCsCourseId()) && (this.getCsStoreId() == castOther.getCsStoreId())
				&& (this.getCsCourseTypeId() == castOther.getCsCourseTypeId())
				&& ((this.getCsCourseNoTx() == castOther.getCsCourseNoTx())
						|| (this.getCsCourseNoTx() != null && castOther.getCsCourseNoTx() != null
								&& this.getCsCourseNoTx().equals(castOther.getCsCourseNoTx())))
				&& ((this.getCsStartDate() == castOther.getCsStartDate())
						|| (this.getCsStartDate() != null && castOther.getCsStartDate() != null
								&& this.getCsStartDate().equals(castOther.getCsStartDate())))
				&& ((this.getCsEndDate() == castOther.getCsEndDate()) || (this.getCsEndDate() != null
						&& castOther.getCsEndDate() != null && this.getCsEndDate().equals(castOther.getCsEndDate())))
				&& ((this.getCsNotesTxN() == castOther.getCsNotesTxN()) || (this.getCsNotesTxN() != null
						&& castOther.getCsNotesTxN() != null && this.getCsNotesTxN().equals(castOther.getCsNotesTxN())))
				&& ((this.getCsLastUpdatedDate() == castOther.getCsLastUpdatedDate())
						|| (this.getCsLastUpdatedDate() != null && castOther.getCsLastUpdatedDate() != null
								&& this.getCsLastUpdatedDate().equals(castOther.getCsLastUpdatedDate())))
				&& (this.getCsMinNoIn() == castOther.getCsMinNoIn())
				&& (this.getCsMaxNoIn() == castOther.getCsMaxNoIn())
				&& ((this.getCsCreationDate() == castOther.getCsCreationDate())
						|| (this.getCsCreationDate() != null && castOther.getCsCreationDate() != null
								&& this.getCsCreationDate().equals(castOther.getCsCreationDate())))
				&& ((this.getCsCourseStatusId() == castOther.getCsCourseStatusId())
						|| (this.getCsCourseStatusId() != null && castOther.getCsCourseStatusId() != null
								&& this.getCsCourseStatusId().equals(castOther.getCsCourseStatusId())))
				&& ((this.getCsLanguageIdN() == castOther.getCsLanguageIdN())
						|| (this.getCsLanguageIdN() != null && castOther.getCsLanguageIdN() != null
								&& this.getCsLanguageIdN().equals(castOther.getCsLanguageIdN())))
				&& ((this.getCsPrivateNotesTxN() == castOther.getCsPrivateNotesTxN())
						|| (this.getCsPrivateNotesTxN() != null && castOther.getCsPrivateNotesTxN() != null
								&& this.getCsPrivateNotesTxN().equals(castOther.getCsPrivateNotesTxN())))
				&& ((this.getCsLocationIdN() == castOther.getCsLocationIdN())
						|| (this.getCsLocationIdN() != null && castOther.getCsLocationIdN() != null
								&& this.getCsLocationIdN().equals(castOther.getCsLocationIdN())))
				&& (this.getCsWaitingListCapacityIn() == castOther.getCsWaitingListCapacityIn())
				&& (this.getCsAvailableWaitingListPlacesIn() == castOther.getCsAvailableWaitingListPlacesIn())
				&& ((this.getCsTermIdN() == castOther.getCsTermIdN()) || (this.getCsTermIdN() != null
						&& castOther.getCsTermIdN() != null && this.getCsTermIdN().equals(castOther.getCsTermIdN())))
				&& ((this.getCsPreviousTermPreviousCourseIdN() == castOther.getCsPreviousTermPreviousCourseIdN())
						|| (this.getCsPreviousTermPreviousCourseIdN() != null
								&& castOther.getCsPreviousTermPreviousCourseIdN() != null
								&& this.getCsPreviousTermPreviousCourseIdN()
										.equals(castOther.getCsPreviousTermPreviousCourseIdN())))
				&& ((this.getCsCurrentTermPreviousCourseIdN() == castOther.getCsCurrentTermPreviousCourseIdN())
						|| (this.getCsCurrentTermPreviousCourseIdN() != null
								&& castOther.getCsCurrentTermPreviousCourseIdN() != null
								&& this.getCsCurrentTermPreviousCourseIdN()
										.equals(castOther.getCsCurrentTermPreviousCourseIdN())))
				&& ((this.getCsMoreInfoTxN() == castOther.getCsMoreInfoTxN())
						|| (this.getCsMoreInfoTxN() != null && castOther.getCsMoreInfoTxN() != null
								&& this.getCsMoreInfoTxN().equals(castOther.getCsMoreInfoTxN())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCsCourseId();
		result = 37 * result + this.getCsStoreId();
		result = 37 * result + this.getCsCourseTypeId();
		result = 37 * result + (getCsCourseNoTx() == null ? 0 : this.getCsCourseNoTx().hashCode());
		result = 37 * result + (getCsStartDate() == null ? 0 : this.getCsStartDate().hashCode());
		result = 37 * result + (getCsEndDate() == null ? 0 : this.getCsEndDate().hashCode());
		result = 37 * result + (getCsNotesTxN() == null ? 0 : this.getCsNotesTxN().hashCode());
		result = 37 * result + (getCsLastUpdatedDate() == null ? 0 : this.getCsLastUpdatedDate().hashCode());
		result = 37 * result + this.getCsMinNoIn();
		result = 37 * result + this.getCsMaxNoIn();
		result = 37 * result + (getCsCreationDate() == null ? 0 : this.getCsCreationDate().hashCode());
		result = 37 * result + (getCsCourseStatusId() == null ? 0 : this.getCsCourseStatusId().hashCode());
		result = 37 * result + (getCsLanguageIdN() == null ? 0 : this.getCsLanguageIdN().hashCode());
		result = 37 * result + (getCsPrivateNotesTxN() == null ? 0 : this.getCsPrivateNotesTxN().hashCode());
		result = 37 * result + (getCsLocationIdN() == null ? 0 : this.getCsLocationIdN().hashCode());
		result = 37 * result + this.getCsWaitingListCapacityIn();
		result = 37 * result + this.getCsAvailableWaitingListPlacesIn();
		result = 37 * result + (getCsTermIdN() == null ? 0 : this.getCsTermIdN().hashCode());
		result = 37 * result + (getCsPreviousTermPreviousCourseIdN() == null ? 0
				: this.getCsPreviousTermPreviousCourseIdN().hashCode());
		result = 37 * result + (getCsCurrentTermPreviousCourseIdN() == null ? 0
				: this.getCsCurrentTermPreviousCourseIdN().hashCode());
		result = 37 * result + (getCsMoreInfoTxN() == null ? 0 : this.getCsMoreInfoTxN().hashCode());
		return result;
	}

}
