package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * S01InInvoice generated by hbm2java
 */
@Entity
@Table(name = "s01_InInvoice")
public class S01InInvoice implements java.io.Serializable {

	private S01InInvoiceId id;

	public S01InInvoice() {
	}

	public S01InInvoice(S01InInvoiceId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "inInvoiceId", column = @Column(name = "InInvoiceID", nullable = false)),
			@AttributeOverride(name = "inInvoiceTypeId", column = @Column(name = "InInvoiceTypeID", nullable = false)),
			@AttributeOverride(name = "inCustId", column = @Column(name = "InCustID", nullable = false)),
			@AttributeOverride(name = "inStoreId", column = @Column(name = "InStoreID", nullable = false)),
			@AttributeOverride(name = "inCostCenterId", column = @Column(name = "InCostCenterID", nullable = false)),
			@AttributeOverride(name = "inAccountIdN", column = @Column(name = "InAccountID_N")),
			@AttributeOverride(name = "inCreationDate", column = @Column(name = "InCreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "inCommittedDateN", column = @Column(name = "InCommittedDate_N", length = 23)),
			@AttributeOverride(name = "inClosedDateN", column = @Column(name = "InClosedDate_N", length = 23)),
			@AttributeOverride(name = "inEmpId", column = @Column(name = "InEmpID", nullable = false)),
			@AttributeOverride(name = "inCommissionEmpId", column = @Column(name = "InCommissionEmpID")),
			@AttributeOverride(name = "inCommissionRateFl", column = @Column(name = "InCommissionRateFl", nullable = false, precision = 24, scale = 0)),
			@AttributeOverride(name = "inCommissionableBl", column = @Column(name = "InCommissionableBl", nullable = false)),
			@AttributeOverride(name = "inSubTotalMn", column = @Column(name = "InSubTotalMn", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "inTaxMn", column = @Column(name = "InTaxMn", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "inLegacyAccPayAmountMnN", column = @Column(name = "InLegacyAccPayAmountMn_N", precision = 53, scale = 0)),
			@AttributeOverride(name = "inCurrencyId", column = @Column(name = "InCurrencyID", nullable = false)),
			@AttributeOverride(name = "inExchangeRateFl", column = @Column(name = "InExchangeRateFl", nullable = false, precision = 24, scale = 0)),
			@AttributeOverride(name = "inLastUpdatedDate", column = @Column(name = "InLastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "inPcid", column = @Column(name = "InPCID", nullable = false)),
			@AttributeOverride(name = "inTransStatusId", column = @Column(name = "InTransStatusID", nullable = false)),
			@AttributeOverride(name = "inNotesTxN", column = @Column(name = "InNotesTx_N")),
			@AttributeOverride(name = "inVoidDateN", column = @Column(name = "InVoidDate_N", length = 23)),
			@AttributeOverride(name = "inVoidReasonTxN", column = @Column(name = "InVoidReasonTx_N")),
			@AttributeOverride(name = "inPaymentDueDateN", column = @Column(name = "InPaymentDueDate_N", length = 23)),
			@AttributeOverride(name = "inShipDate", column = @Column(name = "InShipDate", length = 23)),
			@AttributeOverride(name = "inPostageId", column = @Column(name = "InPostageID")),
			@AttributeOverride(name = "inProcessedBl", column = @Column(name = "InProcessedBl", nullable = false)),
			@AttributeOverride(name = "inTicketNoTxN", column = @Column(name = "InTicketNoTx_N")),
			@AttributeOverride(name = "inBillingAddressId", column = @Column(name = "InBillingAddressId")),
			@AttributeOverride(name = "inShippingAddressId", column = @Column(name = "InShippingAddressId")),
			@AttributeOverride(name = "inInvoiceNumberTxN", column = @Column(name = "InInvoiceNumberTx_N", length = 50)),
			@AttributeOverride(name = "inUserIptxN", column = @Column(name = "InUserIPTx_N", length = 50)),
			@AttributeOverride(name = "inOrderStatusTxN", column = @Column(name = "InOrderStatusTx_N", length = 50)),
			@AttributeOverride(name = "inOrderStatusCodeInN", column = @Column(name = "InOrderStatusCodeIn_N", nullable = false)),
			@AttributeOverride(name = "inSourceIdN", column = @Column(name = "InSourceID_N")),
			@AttributeOverride(name = "inStockLevelsUpdatedBl", column = @Column(name = "InStockLevelsUpdatedBl", nullable = false)) })
	public S01InInvoiceId getId() {
		return this.id;
	}

	public void setId(S01InInvoiceId id) {
		this.id = id;
	}

}
