package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * S01RbrentalBooking generated by hbm2java
 */
@Entity
@Table(name = "s01_RBRentalBooking")
public class S01RbrentalBooking implements java.io.Serializable {

	private S01RbrentalBookingId id;

	public S01RbrentalBooking() {
	}

	public S01RbrentalBooking(S01RbrentalBookingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rbrentalBookingId", column = @Column(name = "RBRentalBookingID", nullable = false)),
			@AttributeOverride(name = "rbinvoiceIdN", column = @Column(name = "RBInvoiceID_N")),
			@AttributeOverride(name = "rbstoreId", column = @Column(name = "RBStoreID", nullable = false)),
			@AttributeOverride(name = "rbcostCenterIdN", column = @Column(name = "RBCostCenterID_N")),
			@AttributeOverride(name = "rbcustId", column = @Column(name = "RBCustID", nullable = false)),
			@AttributeOverride(name = "rbcreationDate", column = @Column(name = "RBCreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "rbempId", column = @Column(name = "RBEmpID", nullable = false)),
			@AttributeOverride(name = "rbbookingAmountMn", column = @Column(name = "RBBookingAmountMn", nullable = false, scale = 4)),
			@AttributeOverride(name = "rbbookingTaxMn", column = @Column(name = "RBBookingTaxMn", nullable = false, scale = 4)),
			@AttributeOverride(name = "rbcurrencyId", column = @Column(name = "RBCurrencyID", nullable = false)),
			@AttributeOverride(name = "rbexchangeRateFl", column = @Column(name = "RBExchangeRateFl", nullable = false, precision = 24, scale = 0)),
			@AttributeOverride(name = "rblastUpdatedDate", column = @Column(name = "RBLastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "rbnotesTxN", column = @Column(name = "RBNotesTx_N")),
			@AttributeOverride(name = "rbstatusId", column = @Column(name = "RBStatusID", nullable = false)),
			@AttributeOverride(name = "rbvoidDateN", column = @Column(name = "RBVoidDate_N", length = 23)),
			@AttributeOverride(name = "rbvoidReasonTxN", column = @Column(name = "RBVoidReasonTx_N")),
			@AttributeOverride(name = "rbdueStartDate", column = @Column(name = "RBDueStartDate", nullable = false, length = 23)),
			@AttributeOverride(name = "rbdueEndDate", column = @Column(name = "RBDueEndDate", nullable = false, length = 23)),
			@AttributeOverride(name = "rbbagNoInN", column = @Column(name = "RBBagNoIn_N")),
			@AttributeOverride(name = "rbpenaltyBl", column = @Column(name = "RBPenaltyBl", nullable = false)) })
	public S01RbrentalBookingId getId() {
		return this.id;
	}

	public void setId(S01RbrentalBookingId id) {
		this.id = id;
	}

}
