package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * S01SbserviceBooking generated by hbm2java
 */
@Entity
@Table(name = "s01_SBServiceBooking")
public class S01SbserviceBooking implements java.io.Serializable {

	private S01SbserviceBookingId id;

	public S01SbserviceBooking() {
	}

	public S01SbserviceBooking(S01SbserviceBookingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "sbserviceBookingId", column = @Column(name = "SBServiceBookingID", nullable = false)),
			@AttributeOverride(name = "sbinvoiceIdN", column = @Column(name = "SBInvoiceID_N")),
			@AttributeOverride(name = "sbstoreId", column = @Column(name = "SBStoreID", nullable = false)),
			@AttributeOverride(name = "sbcostCenterId", column = @Column(name = "SBCostCenterID", nullable = false)),
			@AttributeOverride(name = "sbcustId", column = @Column(name = "SBCustID", nullable = false)),
			@AttributeOverride(name = "sbcreationDate", column = @Column(name = "SBCreationDate", nullable = false, length = 23)),
			@AttributeOverride(name = "sbempId", column = @Column(name = "SBEmpID", nullable = false)),
			@AttributeOverride(name = "sbcurrencyId", column = @Column(name = "SBCurrencyID", nullable = false)),
			@AttributeOverride(name = "sbexchangeRateFl", column = @Column(name = "SBExchangeRateFl", nullable = false, precision = 24, scale = 0)),
			@AttributeOverride(name = "sblastUpdatedDate", column = @Column(name = "SBLastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "sbnotesTxN", column = @Column(name = "SBNotesTx_N")),
			@AttributeOverride(name = "sbstatusId", column = @Column(name = "SBStatusID", nullable = false)),
			@AttributeOverride(name = "sbvoidDateN", column = @Column(name = "SBVoidDate_N", length = 23)),
			@AttributeOverride(name = "sbvoidReasonTxN", column = @Column(name = "SBVoidReasonTx_N")),
			@AttributeOverride(name = "sbpartsAmountMn", column = @Column(name = "SBPartsAmountMn", nullable = false, scale = 4)),
			@AttributeOverride(name = "sbpartTaxMn", column = @Column(name = "SBPartTaxMn", nullable = false, scale = 4)),
			@AttributeOverride(name = "sbbookingLaborMn", column = @Column(name = "SBBookingLaborMn", nullable = false, scale = 4)),
			@AttributeOverride(name = "sbbookingLaborTaxMn", column = @Column(name = "SBBookingLaborTaxMn", nullable = false, scale = 4)),
			@AttributeOverride(name = "sbbookingHandlingMn", column = @Column(name = "SBBookingHandlingMn", nullable = false, scale = 4)),
			@AttributeOverride(name = "sbbookingHandlingTaxMn", column = @Column(name = "SBBookingHandlingTaxMn", nullable = false, scale = 4)),
			@AttributeOverride(name = "sbdueStartDate", column = @Column(name = "SBDueStartDate", nullable = false, length = 23)),
			@AttributeOverride(name = "sbdueEndDate", column = @Column(name = "SBDueEndDate", nullable = false, length = 23)),
			@AttributeOverride(name = "sbticketNoInN", column = @Column(name = "SBTicketNoIn_N")) })
	public S01SbserviceBookingId getId() {
		return this.id;
	}

	public void setId(S01SbserviceBookingId id) {
		this.id = id;
	}

}
