package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * S01SnserialNo generated by hbm2java
 */
@Entity
@Table(name = "s01_SNSerialNo")
public class S01SnserialNo implements java.io.Serializable {

	private S01SnserialNoId id;

	public S01SnserialNo() {
	}

	public S01SnserialNo(S01SnserialNoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "snstockItemId", column = @Column(name = "SNStockItemID", nullable = false)),
			@AttributeOverride(name = "snserialNoTx", column = @Column(name = "SNSerialNoTx", nullable = false)),
			@AttributeOverride(name = "snstoreId", column = @Column(name = "SNStoreID", nullable = false)),
			@AttributeOverride(name = "sninvoiceIdN", column = @Column(name = "SNInvoiceID_N")),
			@AttributeOverride(name = "sncreationDate", column = @Column(name = "SNCreationDate", nullable = false, length = 23)) })
	public S01SnserialNoId getId() {
		return this.id;
	}

	public void setId(S01SnserialNoId id) {
		this.id = id;
	}

}
