package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * S01ScSource generated by hbm2java
 */
@Entity
@Table(name = "s01_ScSource")
public class S01ScSource implements java.io.Serializable {

	private S01ScSourceId id;

	public S01ScSource() {
	}

	public S01ScSource(S01ScSourceId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "scSourceId", column = @Column(name = "ScSourceID", nullable = false)),
			@AttributeOverride(name = "scSourceTx", column = @Column(name = "ScSourceTx", nullable = false)),
			@AttributeOverride(name = "scUnavailableBl", column = @Column(name = "ScUnavailableBl", nullable = false)),
			@AttributeOverride(name = "scLastUpdatedDate", column = @Column(name = "ScLastUpdatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "scRequiredBl", column = @Column(name = "ScRequiredBl", nullable = false)),
			@AttributeOverride(name = "scCreationDate", column = @Column(name = "ScCreationDate", nullable = false, length = 23)) })
	public S01ScSourceId getId() {
		return this.id;
	}

	public void setId(S01ScSourceId id) {
		this.id = id;
	}

}
