package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TA2menu generated by hbm2java
 */
@Entity
@Table(name = "T_A2Menu")
public class TA2menu implements java.io.Serializable {

	private int a2menuId;
	private TA1tab TA1tab;
	private String a2menuTx;
	private int a2displayOrderIn;
	private Set<TA3propertyType> TA3propertyTypes = new HashSet<TA3propertyType>(0);

	public TA2menu() {
	}

	public TA2menu(int a2menuId, String a2menuTx, int a2displayOrderIn) {
		this.a2menuId = a2menuId;
		this.a2menuTx = a2menuTx;
		this.a2displayOrderIn = a2displayOrderIn;
	}

	public TA2menu(int a2menuId, TA1tab TA1tab, String a2menuTx, int a2displayOrderIn,
			Set<TA3propertyType> TA3propertyTypes) {
		this.a2menuId = a2menuId;
		this.TA1tab = TA1tab;
		this.a2menuTx = a2menuTx;
		this.a2displayOrderIn = a2displayOrderIn;
		this.TA3propertyTypes = TA3propertyTypes;
	}

	@Id

	@Column(name = "A2MenuID", unique = true, nullable = false)
	public int getA2menuId() {
		return this.a2menuId;
	}

	public void setA2menuId(int a2menuId) {
		this.a2menuId = a2menuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "A2TabID_N")
	public TA1tab getTA1tab() {
		return this.TA1tab;
	}

	public void setTA1tab(TA1tab TA1tab) {
		this.TA1tab = TA1tab;
	}

	@Column(name = "A2MenuTx", nullable = false)
	public String getA2menuTx() {
		return this.a2menuTx;
	}

	public void setA2menuTx(String a2menuTx) {
		this.a2menuTx = a2menuTx;
	}

	@Column(name = "A2DisplayOrderIn", nullable = false)
	public int getA2displayOrderIn() {
		return this.a2displayOrderIn;
	}

	public void setA2displayOrderIn(int a2displayOrderIn) {
		this.a2displayOrderIn = a2displayOrderIn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TA2menu")
	public Set<TA3propertyType> getTA3propertyTypes() {
		return this.TA3propertyTypes;
	}

	public void setTA3propertyTypes(Set<TA3propertyType> TA3propertyTypes) {
		this.TA3propertyTypes = TA3propertyTypes;
	}

}
