package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TA3propertyType generated by hbm2java
 */
@Entity
@Table(name = "T_A3PropertyType")
public class TA3propertyType implements java.io.Serializable {

	private int a3propertyTypeId;
	private TA2menu TA2menu;
	private String a3propertyTypeTx;
	private int a3displayOrderId;
	private Set<TA4propertyValue> TA4propertyValues = new HashSet<TA4propertyValue>(0);

	public TA3propertyType() {
	}

	public TA3propertyType(int a3propertyTypeId, String a3propertyTypeTx, int a3displayOrderId) {
		this.a3propertyTypeId = a3propertyTypeId;
		this.a3propertyTypeTx = a3propertyTypeTx;
		this.a3displayOrderId = a3displayOrderId;
	}

	public TA3propertyType(int a3propertyTypeId, TA2menu TA2menu, String a3propertyTypeTx, int a3displayOrderId,
			Set<TA4propertyValue> TA4propertyValues) {
		this.a3propertyTypeId = a3propertyTypeId;
		this.TA2menu = TA2menu;
		this.a3propertyTypeTx = a3propertyTypeTx;
		this.a3displayOrderId = a3displayOrderId;
		this.TA4propertyValues = TA4propertyValues;
	}

	@Id

	@Column(name = "A3PropertyTypeID", unique = true, nullable = false)
	public int getA3propertyTypeId() {
		return this.a3propertyTypeId;
	}

	public void setA3propertyTypeId(int a3propertyTypeId) {
		this.a3propertyTypeId = a3propertyTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "A3MenuID_N")
	public TA2menu getTA2menu() {
		return this.TA2menu;
	}

	public void setTA2menu(TA2menu TA2menu) {
		this.TA2menu = TA2menu;
	}

	@Column(name = "A3PropertyTypeTx", nullable = false)
	public String getA3propertyTypeTx() {
		return this.a3propertyTypeTx;
	}

	public void setA3propertyTypeTx(String a3propertyTypeTx) {
		this.a3propertyTypeTx = a3propertyTypeTx;
	}

	@Column(name = "A3DisplayOrderID", nullable = false)
	public int getA3displayOrderId() {
		return this.a3displayOrderId;
	}

	public void setA3displayOrderId(int a3displayOrderId) {
		this.a3displayOrderId = a3displayOrderId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TA3propertyType")
	public Set<TA4propertyValue> getTA4propertyValues() {
		return this.TA4propertyValues;
	}

	public void setTA4propertyValues(Set<TA4propertyValue> TA4propertyValues) {
		this.TA4propertyValues = TA4propertyValues;
	}

}
