package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tables1 generated by hbm2java
 */
@Entity
@Table(name = "_Tables1")
public class Tables1 implements java.io.Serializable {

	private Tables1Id id;

	public Tables1() {
	}

	public Tables1(Tables1Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "name", column = @Column(name = "Name")),
			@AttributeOverride(name = "processOrder", column = @Column(name = "ProcessOrder")),
			@AttributeOverride(name = "sql", column = @Column(name = "SQL")),
			@AttributeOverride(name = "sql2", column = @Column(name = "SQL2")) })
	public Tables1Id getId() {
		return this.id;
	}

	public void setId(Tables1Id id) {
		this.id = id;
	}

}
