package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TAdAddress generated by hbm2java
 */
@Entity
@Table(name = "T_AdAddress")
public class TAdAddress implements java.io.Serializable {

	private int adAddressId;
	private TCuCust TCuCust;
	private String adUserNameTx;
	private String adFirstNameTx;
	private String adLastNameTx;
	private String adPhoneTxN;
	private String adEmailTxN;
	private String adAddress1tx;
	private String adAddress2txN;
	private String adCityTx;
	private String adStateOrRegionTx;
	private String adZipTx;
	private String adCountryTxN;
	private Set<TInInvoice> TInInvoicesForInBillingAddressId = new HashSet<TInInvoice>(0);
	private Set<TInInvoice> TInInvoicesForInShippingAddressId = new HashSet<TInInvoice>(0);

	public TAdAddress() {
	}

	public TAdAddress(int adAddressId) {
		this.adAddressId = adAddressId;
	}

	public TAdAddress(int adAddressId, TCuCust TCuCust, String adUserNameTx, String adFirstNameTx,
			String adLastNameTx, String adPhoneTxN, String adEmailTxN, String adAddress1tx,
			String adAddress2txN, String adCityTx, String adStateOrRegionTx, String adZipTx,
			String adCountryTxN, Set<TInInvoice> TInInvoicesForInBillingAddressId,
			Set<TInInvoice> TInInvoicesForInShippingAddressId) {
		this.adAddressId = adAddressId;
		this.TCuCust = TCuCust;
		this.adUserNameTx = adUserNameTx;
		this.adFirstNameTx = adFirstNameTx;
		this.adLastNameTx = adLastNameTx;
		this.adPhoneTxN = adPhoneTxN;
		this.adEmailTxN = adEmailTxN;
		this.adAddress1tx = adAddress1tx;
		this.adAddress2txN = adAddress2txN;
		this.adCityTx = adCityTx;
		this.adStateOrRegionTx = adStateOrRegionTx;
		this.adZipTx = adZipTx;
		this.adCountryTxN = adCountryTxN;
		this.TInInvoicesForInBillingAddressId = TInInvoicesForInBillingAddressId;
		this.TInInvoicesForInShippingAddressId = TInInvoicesForInShippingAddressId;
	}

	@Id

	@Column(name = "AdAddressID", unique = true, nullable = false)
	public int getAdAddressId() {
		return this.adAddressId;
	}

	public void setAdAddressId(int adAddressId) {
		this.adAddressId = adAddressId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AdCustId")
	public TCuCust getTCuCust() {
		return this.TCuCust;
	}

	public void setTCuCust(TCuCust TCuCust) {
		this.TCuCust = TCuCust;
	}

	@Column(name = "AdUserNameTx")
	public String getAdUserNameTx() {
		return this.adUserNameTx;
	}

	public void setAdUserNameTx(String adUserNameTx) {
		this.adUserNameTx = adUserNameTx;
	}

	@Column(name = "AdFirstNameTx")
	public String getAdFirstNameTx() {
		return this.adFirstNameTx;
	}

	public void setAdFirstNameTx(String adFirstNameTx) {
		this.adFirstNameTx = adFirstNameTx;
	}

	@Column(name = "AdLastNameTx")
	public String getAdLastNameTx() {
		return this.adLastNameTx;
	}

	public void setAdLastNameTx(String adLastNameTx) {
		this.adLastNameTx = adLastNameTx;
	}

	@Column(name = "AdPhoneTx_N")
	public String getAdPhoneTxN() {
		return this.adPhoneTxN;
	}

	public void setAdPhoneTxN(String adPhoneTxN) {
		this.adPhoneTxN = adPhoneTxN;
	}

	@Column(name = "AdEmailTx_N")
	public String getAdEmailTxN() {
		return this.adEmailTxN;
	}

	public void setAdEmailTxN(String adEmailTxN) {
		this.adEmailTxN = adEmailTxN;
	}

	@Column(name = "AdAddress1Tx")
	public String getAdAddress1tx() {
		return this.adAddress1tx;
	}

	public void setAdAddress1tx(String adAddress1tx) {
		this.adAddress1tx = adAddress1tx;
	}

	@Column(name = "AdAddress2Tx_N")
	public String getAdAddress2txN() {
		return this.adAddress2txN;
	}

	public void setAdAddress2txN(String adAddress2txN) {
		this.adAddress2txN = adAddress2txN;
	}

	@Column(name = "AdCityTx")
	public String getAdCityTx() {
		return this.adCityTx;
	}

	public void setAdCityTx(String adCityTx) {
		this.adCityTx = adCityTx;
	}

	@Column(name = "AdStateOrRegionTx")
	public String getAdStateOrRegionTx() {
		return this.adStateOrRegionTx;
	}

	public void setAdStateOrRegionTx(String adStateOrRegionTx) {
		this.adStateOrRegionTx = adStateOrRegionTx;
	}

	@Column(name = "AdZipTx")
	public String getAdZipTx() {
		return this.adZipTx;
	}

	public void setAdZipTx(String adZipTx) {
		this.adZipTx = adZipTx;
	}

	@Column(name = "AdCountryTx_N")
	public String getAdCountryTxN() {
		return this.adCountryTxN;
	}

	public void setAdCountryTxN(String adCountryTxN) {
		this.adCountryTxN = adCountryTxN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAdAddressByInBillingAddressId")
	public Set<TInInvoice> getTInInvoicesForInBillingAddressId() {
		return this.TInInvoicesForInBillingAddressId;
	}

	public void setTInInvoicesForInBillingAddressId(Set<TInInvoice> TInInvoicesForInBillingAddressId) {
		this.TInInvoicesForInBillingAddressId = TInInvoicesForInBillingAddressId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAdAddressByInShippingAddressId")
	public Set<TInInvoice> getTInInvoicesForInShippingAddressId() {
		return this.TInInvoicesForInShippingAddressId;
	}

	public void setTInInvoicesForInShippingAddressId(Set<TInInvoice> TInInvoicesForInShippingAddressId) {
		this.TInInvoicesForInShippingAddressId = TInInvoicesForInShippingAddressId;
	}

}
