package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TAkAutoTask generated by hbm2java
 */
@Entity
@Table(name = "T_AkAutoTask")
public class TAkAutoTask implements java.io.Serializable {

	private int akAutoTaskId;
	private String akAutoTaskTx;
	private int akTypeId;
	private String akSqltxN;
	private Date akActivationDate;
	private String akEmailSubjectTxN;
	private String akConfirmationAddressTxN;

	public TAkAutoTask() {
	}

	public TAkAutoTask(int akAutoTaskId, String akAutoTaskTx, int akTypeId, Date akActivationDate) {
		this.akAutoTaskId = akAutoTaskId;
		this.akAutoTaskTx = akAutoTaskTx;
		this.akTypeId = akTypeId;
		this.akActivationDate = akActivationDate;
	}

	public TAkAutoTask(int akAutoTaskId, String akAutoTaskTx, int akTypeId, String akSqltxN,
			Date akActivationDate, String akEmailSubjectTxN, String akConfirmationAddressTxN) {
		this.akAutoTaskId = akAutoTaskId;
		this.akAutoTaskTx = akAutoTaskTx;
		this.akTypeId = akTypeId;
		this.akSqltxN = akSqltxN;
		this.akActivationDate = akActivationDate;
		this.akEmailSubjectTxN = akEmailSubjectTxN;
		this.akConfirmationAddressTxN = akConfirmationAddressTxN;
	}

	@Id

	@Column(name = "AkAutoTaskID", unique = true, nullable = false)
	public int getAkAutoTaskId() {
		return this.akAutoTaskId;
	}

	public void setAkAutoTaskId(int akAutoTaskId) {
		this.akAutoTaskId = akAutoTaskId;
	}

	@Column(name = "AkAutoTaskTx", nullable = false)
	public String getAkAutoTaskTx() {
		return this.akAutoTaskTx;
	}

	public void setAkAutoTaskTx(String akAutoTaskTx) {
		this.akAutoTaskTx = akAutoTaskTx;
	}

	@Column(name = "AkTypeID", nullable = false)
	public int getAkTypeId() {
		return this.akTypeId;
	}

	public void setAkTypeId(int akTypeId) {
		this.akTypeId = akTypeId;
	}

	@Column(name = "AkSQLTx_N")
	public String getAkSqltxN() {
		return this.akSqltxN;
	}

	public void setAkSqltxN(String akSqltxN) {
		this.akSqltxN = akSqltxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AkActivationDate", nullable = false, length = 23)
	public Date getAkActivationDate() {
		return this.akActivationDate;
	}

	public void setAkActivationDate(Date akActivationDate) {
		this.akActivationDate = akActivationDate;
	}

	@Column(name = "AkEmailSubjectTx_N")
	public String getAkEmailSubjectTxN() {
		return this.akEmailSubjectTxN;
	}

	public void setAkEmailSubjectTxN(String akEmailSubjectTxN) {
		this.akEmailSubjectTxN = akEmailSubjectTxN;
	}

	@Column(name = "AkConfirmationAddressTx_N")
	public String getAkConfirmationAddressTxN() {
		return this.akConfirmationAddressTxN;
	}

	public void setAkConfirmationAddressTxN(String akConfirmationAddressTxN) {
		this.akConfirmationAddressTxN = akConfirmationAddressTxN;
	}

}
