package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TAmAlarm generated by hbm2java
 */
@Entity
@Table(name = "T_AmAlarm")
public class TAmAlarm implements java.io.Serializable {

	private TAmAlarmId id;
	private TDtdataType TDtdataType;
	private TPcpc TPcpc;
	private Date amReminderDate;

	public TAmAlarm() {
	}

	public TAmAlarm(TAmAlarmId id, TDtdataType TDtdataType, TPcpc TPcpc, Date amReminderDate) {
		this.id = id;
		this.TDtdataType = TDtdataType;
		this.TPcpc = TPcpc;
		this.amReminderDate = amReminderDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "amDataTypeId", column = @Column(name = "AmDataTypeID", nullable = false)),
			@AttributeOverride(name = "amDataId", column = @Column(name = "AmDataID", nullable = false)),
			@AttributeOverride(name = "amPcid", column = @Column(name = "AmPCID", nullable = false)) })
	public TAmAlarmId getId() {
		return this.id;
	}

	public void setId(TAmAlarmId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AmDataTypeID", nullable = false, insertable = false, updatable = false)
	public TDtdataType getTDtdataType() {
		return this.TDtdataType;
	}

	public void setTDtdataType(TDtdataType TDtdataType) {
		this.TDtdataType = TDtdataType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AmPCID", nullable = false, insertable = false, updatable = false)
	public TPcpc getTPcpc() {
		return this.TPcpc;
	}

	public void setTPcpc(TPcpc TPcpc) {
		this.TPcpc = TPcpc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AmReminderDate", nullable = false, length = 23)
	public Date getAmReminderDate() {
		return this.amReminderDate;
	}

	public void setAmReminderDate(Date amReminderDate) {
		this.amReminderDate = amReminderDate;
	}

}
