package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TAnClosing generated by hbm2java
 */
@Entity
@Table(name = "T_AnClosing")
public class TAnClosing implements java.io.Serializable {

	private int anClosingId;
	private TSoStore TSoStore;
	private Date anClosingDate;
	private Set<TTxTax> TTxTaxes = new HashSet<TTxTax>(0);
	private Set<TVivoucherItem> TVivoucherItems = new HashSet<TVivoucherItem>(0);
	private Set<TAyAccountPayment> TAyAccountPayments = new HashSet<TAyAccountPayment>(0);
	private Set<TIiinvoiceItem> TIiinvoiceItems = new HashSet<TIiinvoiceItem>(0);
	private Set<TPyPayment> TPyPayments = new HashSet<TPyPayment>(0);

	public TAnClosing() {
	}

	public TAnClosing(int anClosingId, TSoStore TSoStore, Date anClosingDate) {
		this.anClosingId = anClosingId;
		this.TSoStore = TSoStore;
		this.anClosingDate = anClosingDate;
	}

	public TAnClosing(int anClosingId, TSoStore TSoStore, Date anClosingDate, Set<TTxTax> TTxTaxes,
			Set<TVivoucherItem> TVivoucherItems, Set<TAyAccountPayment> TAyAccountPayments,
			Set<TIiinvoiceItem> TIiinvoiceItems, Set<TPyPayment> TPyPayments) {
		this.anClosingId = anClosingId;
		this.TSoStore = TSoStore;
		this.anClosingDate = anClosingDate;
		this.TTxTaxes = TTxTaxes;
		this.TVivoucherItems = TVivoucherItems;
		this.TAyAccountPayments = TAyAccountPayments;
		this.TIiinvoiceItems = TIiinvoiceItems;
		this.TPyPayments = TPyPayments;
	}

	@Id

	@Column(name = "AnClosingID", unique = true, nullable = false)
	public int getAnClosingId() {
		return this.anClosingId;
	}

	public void setAnClosingId(int anClosingId) {
		this.anClosingId = anClosingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AnStoreID", nullable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AnClosingDate", nullable = false, length = 23)
	public Date getAnClosingDate() {
		return this.anClosingDate;
	}

	public void setAnClosingDate(Date anClosingDate) {
		this.anClosingDate = anClosingDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAnClosing")
	public Set<TTxTax> getTTxTaxes() {
		return this.TTxTaxes;
	}

	public void setTTxTaxes(Set<TTxTax> TTxTaxes) {
		this.TTxTaxes = TTxTaxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAnClosing")
	public Set<TVivoucherItem> getTVivoucherItems() {
		return this.TVivoucherItems;
	}

	public void setTVivoucherItems(Set<TVivoucherItem> TVivoucherItems) {
		this.TVivoucherItems = TVivoucherItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAnClosing")
	public Set<TAyAccountPayment> getTAyAccountPayments() {
		return this.TAyAccountPayments;
	}

	public void setTAyAccountPayments(Set<TAyAccountPayment> TAyAccountPayments) {
		this.TAyAccountPayments = TAyAccountPayments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAnClosing")
	public Set<TIiinvoiceItem> getTIiinvoiceItems() {
		return this.TIiinvoiceItems;
	}

	public void setTIiinvoiceItems(Set<TIiinvoiceItem> TIiinvoiceItems) {
		this.TIiinvoiceItems = TIiinvoiceItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAnClosing")
	public Set<TPyPayment> getTPyPayments() {
		return this.TPyPayments;
	}

	public void setTPyPayments(Set<TPyPayment> TPyPayments) {
		this.TPyPayments = TPyPayments;
	}

}
