package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TAoCommissionClosing generated by hbm2java
 */
@Entity
@Table(name = "T_AoCommissionClosing")
public class TAoCommissionClosing implements java.io.Serializable {

	private int aoCommissionClosingId;
	private TSoStore TSoStore;
	private Date aoDate;
	private String aoEmpIds;

	public TAoCommissionClosing() {
	}

	public TAoCommissionClosing(int aoCommissionClosingId, TSoStore TSoStore, Date aoDate) {
		this.aoCommissionClosingId = aoCommissionClosingId;
		this.TSoStore = TSoStore;
		this.aoDate = aoDate;
	}

	public TAoCommissionClosing(int aoCommissionClosingId, TSoStore TSoStore, Date aoDate, String aoEmpIds) {
		this.aoCommissionClosingId = aoCommissionClosingId;
		this.TSoStore = TSoStore;
		this.aoDate = aoDate;
		this.aoEmpIds = aoEmpIds;
	}

	@Id

	@Column(name = "AoCommissionClosingID", unique = true, nullable = false)
	public int getAoCommissionClosingId() {
		return this.aoCommissionClosingId;
	}

	public void setAoCommissionClosingId(int aoCommissionClosingId) {
		this.aoCommissionClosingId = aoCommissionClosingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AoStoreID", nullable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AoDate", nullable = false, length = 23)
	public Date getAoDate() {
		return this.aoDate;
	}

	public void setAoDate(Date aoDate) {
		this.aoDate = aoDate;
	}

	@Column(name = "AoEmpIDs")
	public String getAoEmpIds() {
		return this.aoEmpIds;
	}

	public void setAoEmpIds(String aoEmpIds) {
		this.aoEmpIds = aoEmpIds;
	}

}
