package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TApAspnetPersonalizationPerUser generated by hbm2java
 */
@Entity
@Table(name = "T_ApAspnet_PersonalizationPerUser")
public class TApAspnetPersonalizationPerUser implements java.io.Serializable {

	private String apId;
	private TApAspnetPaths TApAspnetPaths;
	private Integer apUserIdN;
	private byte[] apPageSettings;
	private Date apLastUpdatedDate;

	public TApAspnetPersonalizationPerUser() {
	}

	public TApAspnetPersonalizationPerUser(String apId, byte[] apPageSettings, Date apLastUpdatedDate) {
		this.apId = apId;
		this.apPageSettings = apPageSettings;
		this.apLastUpdatedDate = apLastUpdatedDate;
	}

	public TApAspnetPersonalizationPerUser(String apId, TApAspnetPaths TApAspnetPaths, Integer apUserIdN,
			byte[] apPageSettings, Date apLastUpdatedDate) {
		this.apId = apId;
		this.TApAspnetPaths = TApAspnetPaths;
		this.apUserIdN = apUserIdN;
		this.apPageSettings = apPageSettings;
		this.apLastUpdatedDate = apLastUpdatedDate;
	}

	@Id

	@Column(name = "ApId", unique = true, nullable = false, length = 36)
	public String getApId() {
		return this.apId;
	}

	public void setApId(String apId) {
		this.apId = apId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ApPathId_N")
	public TApAspnetPaths getTApAspnetPaths() {
		return this.TApAspnetPaths;
	}

	public void setTApAspnetPaths(TApAspnetPaths TApAspnetPaths) {
		this.TApAspnetPaths = TApAspnetPaths;
	}

	@Column(name = "ApUserId_N")
	public Integer getApUserIdN() {
		return this.apUserIdN;
	}

	public void setApUserIdN(Integer apUserIdN) {
		this.apUserIdN = apUserIdN;
	}

	@Column(name = "ApPageSettings", nullable = false)
	public byte[] getApPageSettings() {
		return this.apPageSettings;
	}

	public void setApPageSettings(byte[] apPageSettings) {
		this.apPageSettings = apPageSettings;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ApLastUpdatedDate", nullable = false, length = 23)
	public Date getApLastUpdatedDate() {
		return this.apLastUpdatedDate;
	}

	public void setApLastUpdatedDate(Date apLastUpdatedDate) {
		this.apLastUpdatedDate = apLastUpdatedDate;
	}

}
