package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TBbcoolbar generated by hbm2java
 */
@Entity
@Table(name = "T_BBCoolbar")
public class TBbcoolbar implements java.io.Serializable {

	private TBbcoolbarId id;

	public TBbcoolbar() {
	}

	public TBbcoolbar(TBbcoolbarId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "bbcoolbarId", column = @Column(name = "BBCoolbarID", nullable = false)),
			@AttributeOverride(name = "bbcoolbarTx", column = @Column(name = "BBCoolbarTx", nullable = false)) })
	public TBbcoolbarId getId() {
		return this.id;
	}

	public void setId(TBbcoolbarId id) {
		this.id = id;
	}

}
