package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TBtBoat generated by hbm2java
 */
@Entity
@Table(name = "T_BtBoat", uniqueConstraints = @UniqueConstraint(columnNames = "BtBoatNameTx"))
public class TBtBoat implements java.io.Serializable {

	private int btBoatId;
	private String btBoatNameTx;
	private short btCapacityIn;
	private String btCallSignTxN;
	private boolean btUnavailableBl;
	private Date btLastUpdatedDate;
	private boolean btRequiredBl;
	private float btLeftFl;
	private float btTopFl;
	private float btWidthFl;
	private float btHeightFl;
	private short btImageIdx;
	private Date btCreationDate;
	private String btNotesTxN;
	private int btForeColorIn;
	private int btBackColorIn;
	private String btPrefixTx;
	private String btUrltxN;
	private short btMinNoIn;
	private String btSeatConfigTxN;
	private String btBoatGraphicTxN;
	private String btBoatIconGraphicTxN;
	private int btBoatGraphicLeftIn;
	private int btBoatGraphicWidthIn;
	private int btBoatGraphicHeightIn;
	private Set<TTpTrip> TTpTrips = new HashSet<TTpTrip>(0);
	private Set<TSyStockTrip> TSyStockTrips = new HashSet<TSyStockTrip>(0);
	private Set<TSoStore> TSoStores = new HashSet<TSoStore>(0);

	public TBtBoat() {
	}

	public TBtBoat(int btBoatId, String btBoatNameTx, short btCapacityIn, boolean btUnavailableBl,
			Date btLastUpdatedDate, boolean btRequiredBl, float btLeftFl, float btTopFl, float btWidthFl,
			float btHeightFl, short btImageIdx, Date btCreationDate, int btForeColorIn, int btBackColorIn,
			String btPrefixTx, short btMinNoIn, int btBoatGraphicLeftIn, int btBoatGraphicWidthIn,
			int btBoatGraphicHeightIn) {
		this.btBoatId = btBoatId;
		this.btBoatNameTx = btBoatNameTx;
		this.btCapacityIn = btCapacityIn;
		this.btUnavailableBl = btUnavailableBl;
		this.btLastUpdatedDate = btLastUpdatedDate;
		this.btRequiredBl = btRequiredBl;
		this.btLeftFl = btLeftFl;
		this.btTopFl = btTopFl;
		this.btWidthFl = btWidthFl;
		this.btHeightFl = btHeightFl;
		this.btImageIdx = btImageIdx;
		this.btCreationDate = btCreationDate;
		this.btForeColorIn = btForeColorIn;
		this.btBackColorIn = btBackColorIn;
		this.btPrefixTx = btPrefixTx;
		this.btMinNoIn = btMinNoIn;
		this.btBoatGraphicLeftIn = btBoatGraphicLeftIn;
		this.btBoatGraphicWidthIn = btBoatGraphicWidthIn;
		this.btBoatGraphicHeightIn = btBoatGraphicHeightIn;
	}

	public TBtBoat(int btBoatId, String btBoatNameTx, short btCapacityIn, String btCallSignTxN,
			boolean btUnavailableBl, Date btLastUpdatedDate, boolean btRequiredBl, float btLeftFl, float btTopFl,
			float btWidthFl, float btHeightFl, short btImageIdx, Date btCreationDate, String btNotesTxN,
			int btForeColorIn, int btBackColorIn, String btPrefixTx, String btUrltxN, short btMinNoIn,
			String btSeatConfigTxN, String btBoatGraphicTxN, String btBoatIconGraphicTxN,
			int btBoatGraphicLeftIn, int btBoatGraphicWidthIn, int btBoatGraphicHeightIn, Set<TTpTrip> TTpTrips,
			Set<TSyStockTrip> TSyStockTrips, Set<TSoStore> TSoStores) {
		this.btBoatId = btBoatId;
		this.btBoatNameTx = btBoatNameTx;
		this.btCapacityIn = btCapacityIn;
		this.btCallSignTxN = btCallSignTxN;
		this.btUnavailableBl = btUnavailableBl;
		this.btLastUpdatedDate = btLastUpdatedDate;
		this.btRequiredBl = btRequiredBl;
		this.btLeftFl = btLeftFl;
		this.btTopFl = btTopFl;
		this.btWidthFl = btWidthFl;
		this.btHeightFl = btHeightFl;
		this.btImageIdx = btImageIdx;
		this.btCreationDate = btCreationDate;
		this.btNotesTxN = btNotesTxN;
		this.btForeColorIn = btForeColorIn;
		this.btBackColorIn = btBackColorIn;
		this.btPrefixTx = btPrefixTx;
		this.btUrltxN = btUrltxN;
		this.btMinNoIn = btMinNoIn;
		this.btSeatConfigTxN = btSeatConfigTxN;
		this.btBoatGraphicTxN = btBoatGraphicTxN;
		this.btBoatIconGraphicTxN = btBoatIconGraphicTxN;
		this.btBoatGraphicLeftIn = btBoatGraphicLeftIn;
		this.btBoatGraphicWidthIn = btBoatGraphicWidthIn;
		this.btBoatGraphicHeightIn = btBoatGraphicHeightIn;
		this.TTpTrips = TTpTrips;
		this.TSyStockTrips = TSyStockTrips;
		this.TSoStores = TSoStores;
	}

	@Id

	@Column(name = "BtBoatID", unique = true, nullable = false)
	public int getBtBoatId() {
		return this.btBoatId;
	}

	public void setBtBoatId(int btBoatId) {
		this.btBoatId = btBoatId;
	}

	@Column(name = "BtBoatNameTx", unique = true, nullable = false)
	public String getBtBoatNameTx() {
		return this.btBoatNameTx;
	}

	public void setBtBoatNameTx(String btBoatNameTx) {
		this.btBoatNameTx = btBoatNameTx;
	}

	@Column(name = "BtCapacityIn", nullable = false)
	public short getBtCapacityIn() {
		return this.btCapacityIn;
	}

	public void setBtCapacityIn(short btCapacityIn) {
		this.btCapacityIn = btCapacityIn;
	}

	@Column(name = "BtCallSignTx_N")
	public String getBtCallSignTxN() {
		return this.btCallSignTxN;
	}

	public void setBtCallSignTxN(String btCallSignTxN) {
		this.btCallSignTxN = btCallSignTxN;
	}

	@Column(name = "BtUnavailableBl", nullable = false)
	public boolean isBtUnavailableBl() {
		return this.btUnavailableBl;
	}

	public void setBtUnavailableBl(boolean btUnavailableBl) {
		this.btUnavailableBl = btUnavailableBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BtLastUpdatedDate", nullable = false, length = 23)
	public Date getBtLastUpdatedDate() {
		return this.btLastUpdatedDate;
	}

	public void setBtLastUpdatedDate(Date btLastUpdatedDate) {
		this.btLastUpdatedDate = btLastUpdatedDate;
	}

	@Column(name = "BtRequiredBl", nullable = false)
	public boolean isBtRequiredBl() {
		return this.btRequiredBl;
	}

	public void setBtRequiredBl(boolean btRequiredBl) {
		this.btRequiredBl = btRequiredBl;
	}

	@Column(name = "BtLeftFl", nullable = false, precision = 24, scale = 0)
	public float getBtLeftFl() {
		return this.btLeftFl;
	}

	public void setBtLeftFl(float btLeftFl) {
		this.btLeftFl = btLeftFl;
	}

	@Column(name = "BtTopFl", nullable = false, precision = 24, scale = 0)
	public float getBtTopFl() {
		return this.btTopFl;
	}

	public void setBtTopFl(float btTopFl) {
		this.btTopFl = btTopFl;
	}

	@Column(name = "BtWidthFl", nullable = false, precision = 24, scale = 0)
	public float getBtWidthFl() {
		return this.btWidthFl;
	}

	public void setBtWidthFl(float btWidthFl) {
		this.btWidthFl = btWidthFl;
	}

	@Column(name = "BtHeightFl", nullable = false, precision = 24, scale = 0)
	public float getBtHeightFl() {
		return this.btHeightFl;
	}

	public void setBtHeightFl(float btHeightFl) {
		this.btHeightFl = btHeightFl;
	}

	@Column(name = "BtImageIdx", nullable = false)
	public short getBtImageIdx() {
		return this.btImageIdx;
	}

	public void setBtImageIdx(short btImageIdx) {
		this.btImageIdx = btImageIdx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BtCreationDate", nullable = false, length = 23)
	public Date getBtCreationDate() {
		return this.btCreationDate;
	}

	public void setBtCreationDate(Date btCreationDate) {
		this.btCreationDate = btCreationDate;
	}

	@Column(name = "BtNotesTx_N")
	public String getBtNotesTxN() {
		return this.btNotesTxN;
	}

	public void setBtNotesTxN(String btNotesTxN) {
		this.btNotesTxN = btNotesTxN;
	}

	@Column(name = "BtForeColorIn", nullable = false)
	public int getBtForeColorIn() {
		return this.btForeColorIn;
	}

	public void setBtForeColorIn(int btForeColorIn) {
		this.btForeColorIn = btForeColorIn;
	}

	@Column(name = "BtBackColorIn", nullable = false)
	public int getBtBackColorIn() {
		return this.btBackColorIn;
	}

	public void setBtBackColorIn(int btBackColorIn) {
		this.btBackColorIn = btBackColorIn;
	}

	@Column(name = "BtPrefixTx", nullable = false)
	public String getBtPrefixTx() {
		return this.btPrefixTx;
	}

	public void setBtPrefixTx(String btPrefixTx) {
		this.btPrefixTx = btPrefixTx;
	}

	@Column(name = "BtURLTx_N")
	public String getBtUrltxN() {
		return this.btUrltxN;
	}

	public void setBtUrltxN(String btUrltxN) {
		this.btUrltxN = btUrltxN;
	}

	@Column(name = "BtMinNoIn", nullable = false)
	public short getBtMinNoIn() {
		return this.btMinNoIn;
	}

	public void setBtMinNoIn(short btMinNoIn) {
		this.btMinNoIn = btMinNoIn;
	}

	@Column(name = "BtSeatConfigTx_N")
	public String getBtSeatConfigTxN() {
		return this.btSeatConfigTxN;
	}

	public void setBtSeatConfigTxN(String btSeatConfigTxN) {
		this.btSeatConfigTxN = btSeatConfigTxN;
	}

	@Column(name = "BtBoatGraphicTx_N")
	public String getBtBoatGraphicTxN() {
		return this.btBoatGraphicTxN;
	}

	public void setBtBoatGraphicTxN(String btBoatGraphicTxN) {
		this.btBoatGraphicTxN = btBoatGraphicTxN;
	}

	@Column(name = "BtBoatIconGraphicTx_N")
	public String getBtBoatIconGraphicTxN() {
		return this.btBoatIconGraphicTxN;
	}

	public void setBtBoatIconGraphicTxN(String btBoatIconGraphicTxN) {
		this.btBoatIconGraphicTxN = btBoatIconGraphicTxN;
	}

	@Column(name = "BtBoatGraphicLeftIn", nullable = false)
	public int getBtBoatGraphicLeftIn() {
		return this.btBoatGraphicLeftIn;
	}

	public void setBtBoatGraphicLeftIn(int btBoatGraphicLeftIn) {
		this.btBoatGraphicLeftIn = btBoatGraphicLeftIn;
	}

	@Column(name = "BtBoatGraphicWidthIn", nullable = false)
	public int getBtBoatGraphicWidthIn() {
		return this.btBoatGraphicWidthIn;
	}

	public void setBtBoatGraphicWidthIn(int btBoatGraphicWidthIn) {
		this.btBoatGraphicWidthIn = btBoatGraphicWidthIn;
	}

	@Column(name = "BtBoatGraphicHeightIn", nullable = false)
	public int getBtBoatGraphicHeightIn() {
		return this.btBoatGraphicHeightIn;
	}

	public void setBtBoatGraphicHeightIn(int btBoatGraphicHeightIn) {
		this.btBoatGraphicHeightIn = btBoatGraphicHeightIn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TBtBoat")
	public Set<TTpTrip> getTTpTrips() {
		return this.TTpTrips;
	}

	public void setTTpTrips(Set<TTpTrip> TTpTrips) {
		this.TTpTrips = TTpTrips;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TBtBoat")
	public Set<TSyStockTrip> getTSyStockTrips() {
		return this.TSyStockTrips;
	}

	public void setTSyStockTrips(Set<TSyStockTrip> TSyStockTrips) {
		this.TSyStockTrips = TSyStockTrips;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_Z1StoreBoat", joinColumns = {
			@JoinColumn(name = "Z1BoatID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Z1StoreID", nullable = false, updatable = false) })
	public Set<TSoStore> getTSoStores() {
		return this.TSoStores;
	}

	public void setTSoStores(Set<TSoStore> TSoStores) {
		this.TSoStores = TSoStores;
	}

}
