package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TC5custEquipment generated by hbm2java
 */
@Entity
@Table(name = "T_C5CustEquipment")
public class TC5custEquipment implements java.io.Serializable {

	private TC5custEquipmentId id;
	private TCuCust TCuCust;
	private TStstockType TStstockType;
	private Date c5lastUpdatedDate;

	public TC5custEquipment() {
	}

	public TC5custEquipment(TC5custEquipmentId id, TCuCust TCuCust, TStstockType TStstockType, Date c5lastUpdatedDate) {
		this.id = id;
		this.TCuCust = TCuCust;
		this.TStstockType = TStstockType;
		this.c5lastUpdatedDate = c5lastUpdatedDate;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "c5custId", column = @Column(name = "C5CustID", nullable = false)),
			@AttributeOverride(name = "c5stockTypeId", column = @Column(name = "C5StockTypeID", nullable = false)) })
	public TC5custEquipmentId getId() {
		return this.id;
	}

	public void setId(TC5custEquipmentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C5CustID", nullable = false, insertable = false, updatable = false)
	public TCuCust getTCuCust() {
		return this.TCuCust;
	}

	public void setTCuCust(TCuCust TCuCust) {
		this.TCuCust = TCuCust;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C5StockTypeID", nullable = false, insertable = false, updatable = false)
	public TStstockType getTStstockType() {
		return this.TStstockType;
	}

	public void setTStstockType(TStstockType TStstockType) {
		this.TStstockType = TStstockType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "C5LastUpdatedDate", nullable = false, length = 23)
	public Date getC5lastUpdatedDate() {
		return this.c5lastUpdatedDate;
	}

	public void setC5lastUpdatedDate(Date c5lastUpdatedDate) {
		this.c5lastUpdatedDate = c5lastUpdatedDate;
	}

}
