package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TC5custEquipmentId generated by hbm2java
 */
@Embeddable
public class TC5custEquipmentId implements java.io.Serializable {

	private int c5custId;
	private int c5stockTypeId;

	public TC5custEquipmentId() {
	}

	public TC5custEquipmentId(int c5custId, int c5stockTypeId) {
		this.c5custId = c5custId;
		this.c5stockTypeId = c5stockTypeId;
	}

	@Column(name = "C5CustID", nullable = false)
	public int getC5custId() {
		return this.c5custId;
	}

	public void setC5custId(int c5custId) {
		this.c5custId = c5custId;
	}

	@Column(name = "C5StockTypeID", nullable = false)
	public int getC5stockTypeId() {
		return this.c5stockTypeId;
	}

	public void setC5stockTypeId(int c5stockTypeId) {
		this.c5stockTypeId = c5stockTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TC5custEquipmentId))
			return false;
		TC5custEquipmentId castOther = (TC5custEquipmentId) other;

		return (this.getC5custId() == castOther.getC5custId())
				&& (this.getC5stockTypeId() == castOther.getC5stockTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getC5custId();
		result = 37 * result + this.getC5stockTypeId();
		return result;
	}

}
