package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TC6custPopup generated by hbm2java
 */
@Entity
@Table(name = "T_C6CustPopup")
public class TC6custPopup implements java.io.Serializable {

	private int c6custPopupId;
	private TCuCust TCuCust;
	private String c6notesTx;
	private Date c6startDate;
	private Date c6endDate;
	private Date c6creationDate;
	private Date c6lastUpdatedDate;

	public TC6custPopup() {
	}

	public TC6custPopup(int c6custPopupId, TCuCust TCuCust, String c6notesTx, Date c6startDate, Date c6endDate,
			Date c6creationDate, Date c6lastUpdatedDate) {
		this.c6custPopupId = c6custPopupId;
		this.TCuCust = TCuCust;
		this.c6notesTx = c6notesTx;
		this.c6startDate = c6startDate;
		this.c6endDate = c6endDate;
		this.c6creationDate = c6creationDate;
		this.c6lastUpdatedDate = c6lastUpdatedDate;
	}

	@Id

	@Column(name = "C6CustPopupID", unique = true, nullable = false)
	public int getC6custPopupId() {
		return this.c6custPopupId;
	}

	public void setC6custPopupId(int c6custPopupId) {
		this.c6custPopupId = c6custPopupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C6CustID", nullable = false)
	public TCuCust getTCuCust() {
		return this.TCuCust;
	}

	public void setTCuCust(TCuCust TCuCust) {
		this.TCuCust = TCuCust;
	}

	@Column(name = "C6NotesTx", nullable = false)
	public String getC6notesTx() {
		return this.c6notesTx;
	}

	public void setC6notesTx(String c6notesTx) {
		this.c6notesTx = c6notesTx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "C6StartDate", nullable = false, length = 23)
	public Date getC6startDate() {
		return this.c6startDate;
	}

	public void setC6startDate(Date c6startDate) {
		this.c6startDate = c6startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "C6EndDate", nullable = false, length = 23)
	public Date getC6endDate() {
		return this.c6endDate;
	}

	public void setC6endDate(Date c6endDate) {
		this.c6endDate = c6endDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "C6CreationDate", nullable = false, length = 23)
	public Date getC6creationDate() {
		return this.c6creationDate;
	}

	public void setC6creationDate(Date c6creationDate) {
		this.c6creationDate = c6creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "C6LastUpdatedDate", nullable = false, length = 23)
	public Date getC6lastUpdatedDate() {
		return this.c6lastUpdatedDate;
	}

	public void setC6lastUpdatedDate(Date c6lastUpdatedDate) {
		this.c6lastUpdatedDate = c6lastUpdatedDate;
	}

}
