package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TC9custMailingListId generated by hbm2java
 */
@Embeddable
public class TC9custMailingListId implements java.io.Serializable {

	private int c9custId;
	private int c9mailingListId;

	public TC9custMailingListId() {
	}

	public TC9custMailingListId(int c9custId, int c9mailingListId) {
		this.c9custId = c9custId;
		this.c9mailingListId = c9mailingListId;
	}

	@Column(name = "C9CustID", nullable = false)
	public int getC9custId() {
		return this.c9custId;
	}

	public void setC9custId(int c9custId) {
		this.c9custId = c9custId;
	}

	@Column(name = "C9MailingListID", nullable = false)
	public int getC9mailingListId() {
		return this.c9mailingListId;
	}

	public void setC9mailingListId(int c9mailingListId) {
		this.c9mailingListId = c9mailingListId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TC9custMailingListId))
			return false;
		TC9custMailingListId castOther = (TC9custMailingListId) other;

		return (this.getC9custId() == castOther.getC9custId())
				&& (this.getC9mailingListId() == castOther.getC9mailingListId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getC9custId();
		result = 37 * result + this.getC9mailingListId();
		return result;
	}

}
