package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TCccostCenter generated by hbm2java
 */
@Entity
@Table(name = "T_CCCostCenter", uniqueConstraints = @UniqueConstraint(columnNames = "CCCostCenterTx"))
public class TCccostCenter implements java.io.Serializable {

	private int cccostCenterId;
	private String cccostCenterTx;
	private String cctaxRegNoTxN;
	private String ccsloganTxN;
	private boolean ccunavailableBl;
	private Date cclastUpdatedDate;
	private boolean ccrequiredBl;
	private String cccoRegNoTxN;
	private String cccompanyFileTxN;
	private Date cccreationDate;
	private Set<TRbrentalBooking> TRbrentalBookings = new HashSet<TRbrentalBooking>(0);
	private Set<TSbserviceBooking> TSbserviceBookings = new HashSet<TSbserviceBooking>(0);
	private Set<TRpretailPrice> TRpretailPrices = new HashSet<TRpretailPrice>(0);
	private Set<TSoStore> TSoStores = new HashSet<TSoStore>(0);
	private Set<TAcAccount> TAcAccounts = new HashSet<TAcAccount>(0);
	private Set<TCvCustTypeDiscountBand> TCvCustTypeDiscountBands = new HashSet<TCvCustTypeDiscountBand>(0);
	private Set<TGcgiftCert> TGcgiftCerts = new HashSet<TGcgiftCert>(0);
	private Set<TApaccountingPeriod> TApaccountingPeriods = new HashSet<TApaccountingPeriod>(0);
	private Set<TC7costCenterStockType> TC7costCenterStockTypes = new HashSet<TC7costCenterStockType>(0);
	private Set<TGdGiftCard> TGdGiftCards = new HashSet<TGdGiftCard>(0);
	private Set<TInInvoice> TInInvoices = new HashSet<TInInvoice>(0);
	private Set<TQuQuote> TQuQuotes = new HashSet<TQuQuote>(0);
	private Set<TVoVoucher> TVoVouchers = new HashSet<TVoVoucher>(0);
	private Set<TPopo> TPopos = new HashSet<TPopo>(0);

	public TCccostCenter() {
	}

	public TCccostCenter(int cccostCenterId, String cccostCenterTx, boolean ccunavailableBl,
			Date cclastUpdatedDate, boolean ccrequiredBl, Date cccreationDate) {
		this.cccostCenterId = cccostCenterId;
		this.cccostCenterTx = cccostCenterTx;
		this.ccunavailableBl = ccunavailableBl;
		this.cclastUpdatedDate = cclastUpdatedDate;
		this.ccrequiredBl = ccrequiredBl;
		this.cccreationDate = cccreationDate;
	}

	public TCccostCenter(int cccostCenterId, String cccostCenterTx, String cctaxRegNoTxN,
			String ccsloganTxN, boolean ccunavailableBl, Date cclastUpdatedDate, boolean ccrequiredBl,
			String cccoRegNoTxN, String cccompanyFileTxN, Date cccreationDate,
			Set<TRbrentalBooking> TRbrentalBookings, Set<TSbserviceBooking> TSbserviceBookings,
			Set<TRpretailPrice> TRpretailPrices, Set<TSoStore> TSoStores, Set<TAcAccount> TAcAccounts,
			Set<TCvCustTypeDiscountBand> TCvCustTypeDiscountBands, Set<TGcgiftCert> TGcgiftCerts,
			Set<TApaccountingPeriod> TApaccountingPeriods, Set<TC7costCenterStockType> TC7costCenterStockTypes,
			Set<TGdGiftCard> TGdGiftCards, Set<TInInvoice> TInInvoices, Set<TQuQuote> TQuQuotes,
			Set<TVoVoucher> TVoVouchers, Set<TPopo> TPopos) {
		this.cccostCenterId = cccostCenterId;
		this.cccostCenterTx = cccostCenterTx;
		this.cctaxRegNoTxN = cctaxRegNoTxN;
		this.ccsloganTxN = ccsloganTxN;
		this.ccunavailableBl = ccunavailableBl;
		this.cclastUpdatedDate = cclastUpdatedDate;
		this.ccrequiredBl = ccrequiredBl;
		this.cccoRegNoTxN = cccoRegNoTxN;
		this.cccompanyFileTxN = cccompanyFileTxN;
		this.cccreationDate = cccreationDate;
		this.TRbrentalBookings = TRbrentalBookings;
		this.TSbserviceBookings = TSbserviceBookings;
		this.TRpretailPrices = TRpretailPrices;
		this.TSoStores = TSoStores;
		this.TAcAccounts = TAcAccounts;
		this.TCvCustTypeDiscountBands = TCvCustTypeDiscountBands;
		this.TGcgiftCerts = TGcgiftCerts;
		this.TApaccountingPeriods = TApaccountingPeriods;
		this.TC7costCenterStockTypes = TC7costCenterStockTypes;
		this.TGdGiftCards = TGdGiftCards;
		this.TInInvoices = TInInvoices;
		this.TQuQuotes = TQuQuotes;
		this.TVoVouchers = TVoVouchers;
		this.TPopos = TPopos;
	}

	@Id

	@Column(name = "CCCostCenterID", unique = true, nullable = false)
	public int getCccostCenterId() {
		return this.cccostCenterId;
	}

	public void setCccostCenterId(int cccostCenterId) {
		this.cccostCenterId = cccostCenterId;
	}

	@Column(name = "CCCostCenterTx", unique = true, nullable = false)
	public String getCccostCenterTx() {
		return this.cccostCenterTx;
	}

	public void setCccostCenterTx(String cccostCenterTx) {
		this.cccostCenterTx = cccostCenterTx;
	}

	@Column(name = "CCTaxRegNoTx_N")
	public String getCctaxRegNoTxN() {
		return this.cctaxRegNoTxN;
	}

	public void setCctaxRegNoTxN(String cctaxRegNoTxN) {
		this.cctaxRegNoTxN = cctaxRegNoTxN;
	}

	@Column(name = "CCSloganTx_N")
	public String getCcsloganTxN() {
		return this.ccsloganTxN;
	}

	public void setCcsloganTxN(String ccsloganTxN) {
		this.ccsloganTxN = ccsloganTxN;
	}

	@Column(name = "CCUnavailableBl", nullable = false)
	public boolean isCcunavailableBl() {
		return this.ccunavailableBl;
	}

	public void setCcunavailableBl(boolean ccunavailableBl) {
		this.ccunavailableBl = ccunavailableBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CCLastUpdatedDate", nullable = false, length = 23)
	public Date getCclastUpdatedDate() {
		return this.cclastUpdatedDate;
	}

	public void setCclastUpdatedDate(Date cclastUpdatedDate) {
		this.cclastUpdatedDate = cclastUpdatedDate;
	}

	@Column(name = "CCRequiredBl", nullable = false)
	public boolean isCcrequiredBl() {
		return this.ccrequiredBl;
	}

	public void setCcrequiredBl(boolean ccrequiredBl) {
		this.ccrequiredBl = ccrequiredBl;
	}

	@Column(name = "CCCoRegNoTx_N")
	public String getCccoRegNoTxN() {
		return this.cccoRegNoTxN;
	}

	public void setCccoRegNoTxN(String cccoRegNoTxN) {
		this.cccoRegNoTxN = cccoRegNoTxN;
	}

	@Column(name = "CCCompanyFileTx_N")
	public String getCccompanyFileTxN() {
		return this.cccompanyFileTxN;
	}

	public void setCccompanyFileTxN(String cccompanyFileTxN) {
		this.cccompanyFileTxN = cccompanyFileTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CCCreationDate", nullable = false, length = 23)
	public Date getCccreationDate() {
		return this.cccreationDate;
	}

	public void setCccreationDate(Date cccreationDate) {
		this.cccreationDate = cccreationDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCccostCenter")
	public Set<TRbrentalBooking> getTRbrentalBookings() {
		return this.TRbrentalBookings;
	}

	public void setTRbrentalBookings(Set<TRbrentalBooking> TRbrentalBookings) {
		this.TRbrentalBookings = TRbrentalBookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCccostCenter")
	public Set<TSbserviceBooking> getTSbserviceBookings() {
		return this.TSbserviceBookings;
	}

	public void setTSbserviceBookings(Set<TSbserviceBooking> TSbserviceBookings) {
		this.TSbserviceBookings = TSbserviceBookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCccostCenter")
	public Set<TRpretailPrice> getTRpretailPrices() {
		return this.TRpretailPrices;
	}

	public void setTRpretailPrices(Set<TRpretailPrice> TRpretailPrices) {
		this.TRpretailPrices = TRpretailPrices;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_Z4StoreCostCenter", joinColumns = {
			@JoinColumn(name = "Z4CostCenterID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Z4StoreID", nullable = false, updatable = false) })
	public Set<TSoStore> getTSoStores() {
		return this.TSoStores;
	}

	public void setTSoStores(Set<TSoStore> TSoStores) {
		this.TSoStores = TSoStores;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCccostCenter")
	public Set<TAcAccount> getTAcAccounts() {
		return this.TAcAccounts;
	}

	public void setTAcAccounts(Set<TAcAccount> TAcAccounts) {
		this.TAcAccounts = TAcAccounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCccostCenter")
	public Set<TCvCustTypeDiscountBand> getTCvCustTypeDiscountBands() {
		return this.TCvCustTypeDiscountBands;
	}

	public void setTCvCustTypeDiscountBands(Set<TCvCustTypeDiscountBand> TCvCustTypeDiscountBands) {
		this.TCvCustTypeDiscountBands = TCvCustTypeDiscountBands;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCccostCenter")
	public Set<TGcgiftCert> getTGcgiftCerts() {
		return this.TGcgiftCerts;
	}

	public void setTGcgiftCerts(Set<TGcgiftCert> TGcgiftCerts) {
		this.TGcgiftCerts = TGcgiftCerts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCccostCenter")
	public Set<TApaccountingPeriod> getTApaccountingPeriods() {
		return this.TApaccountingPeriods;
	}

	public void setTApaccountingPeriods(Set<TApaccountingPeriod> TApaccountingPeriods) {
		this.TApaccountingPeriods = TApaccountingPeriods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCccostCenter")
	public Set<TC7costCenterStockType> getTC7costCenterStockTypes() {
		return this.TC7costCenterStockTypes;
	}

	public void setTC7costCenterStockTypes(Set<TC7costCenterStockType> TC7costCenterStockTypes) {
		this.TC7costCenterStockTypes = TC7costCenterStockTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCccostCenter")
	public Set<TGdGiftCard> getTGdGiftCards() {
		return this.TGdGiftCards;
	}

	public void setTGdGiftCards(Set<TGdGiftCard> TGdGiftCards) {
		this.TGdGiftCards = TGdGiftCards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCccostCenter")
	public Set<TInInvoice> getTInInvoices() {
		return this.TInInvoices;
	}

	public void setTInInvoices(Set<TInInvoice> TInInvoices) {
		this.TInInvoices = TInInvoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCccostCenter")
	public Set<TQuQuote> getTQuQuotes() {
		return this.TQuQuotes;
	}

	public void setTQuQuotes(Set<TQuQuote> TQuQuotes) {
		this.TQuQuotes = TQuQuotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCccostCenter")
	public Set<TVoVoucher> getTVoVouchers() {
		return this.TVoVouchers;
	}

	public void setTVoVouchers(Set<TVoVoucher> TVoVouchers) {
		this.TVoVouchers = TVoVouchers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCccostCenter")
	public Set<TPopo> getTPopos() {
		return this.TPopos;
	}

	public void setTPopos(Set<TPopo> TPopos) {
		this.TPopos = TPopos;
	}

}
