package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TCdCustOrder generated by hbm2java
 */
@Entity
@Table(name = "T_CdCustOrder")
public class TCdCustOrder implements java.io.Serializable {

	private int cdCustOrderId;
	private TCuCust TCuCust;
	private TEmEmp TEmEmp;
	private TSoStore TSoStore;
	private TIiinvoiceItem TIiinvoiceItem;
	private TSistockItem TSistockItem;
	private TCmcontactMethod TCmcontactMethod;
	private Date cdCreationDate;
	private Integer cdPoidN;
	private short cdQtyIn;
	private Date cdPickedUpDateN;
	private Date cdNotifiedDateN;
	private String cdNotesTxN;
	private String cdPonotesTxN;
	private Date cdLastUpdatedDate;
	private String cdLocationTxN;
	private Date cdRequiredByDateN;
	private Set<TPipoitem> TPipoitems = new HashSet<TPipoitem>(0);

	public TCdCustOrder() {
	}

	public TCdCustOrder(int cdCustOrderId, TCuCust TCuCust, TEmEmp TEmEmp, TSoStore TSoStore, TSistockItem TSistockItem,
			Date cdCreationDate, short cdQtyIn, Date cdLastUpdatedDate) {
		this.cdCustOrderId = cdCustOrderId;
		this.TCuCust = TCuCust;
		this.TEmEmp = TEmEmp;
		this.TSoStore = TSoStore;
		this.TSistockItem = TSistockItem;
		this.cdCreationDate = cdCreationDate;
		this.cdQtyIn = cdQtyIn;
		this.cdLastUpdatedDate = cdLastUpdatedDate;
	}

	public TCdCustOrder(int cdCustOrderId, TCuCust TCuCust, TEmEmp TEmEmp, TSoStore TSoStore,
			TIiinvoiceItem TIiinvoiceItem, TSistockItem TSistockItem, TCmcontactMethod TCmcontactMethod,
			Date cdCreationDate, Integer cdPoidN, short cdQtyIn, Date cdPickedUpDateN, Date cdNotifiedDateN,
			String cdNotesTxN, String cdPonotesTxN, Date cdLastUpdatedDate, String cdLocationTxN,
			Date cdRequiredByDateN, Set<TPipoitem> TPipoitems) {
		this.cdCustOrderId = cdCustOrderId;
		this.TCuCust = TCuCust;
		this.TEmEmp = TEmEmp;
		this.TSoStore = TSoStore;
		this.TIiinvoiceItem = TIiinvoiceItem;
		this.TSistockItem = TSistockItem;
		this.TCmcontactMethod = TCmcontactMethod;
		this.cdCreationDate = cdCreationDate;
		this.cdPoidN = cdPoidN;
		this.cdQtyIn = cdQtyIn;
		this.cdPickedUpDateN = cdPickedUpDateN;
		this.cdNotifiedDateN = cdNotifiedDateN;
		this.cdNotesTxN = cdNotesTxN;
		this.cdPonotesTxN = cdPonotesTxN;
		this.cdLastUpdatedDate = cdLastUpdatedDate;
		this.cdLocationTxN = cdLocationTxN;
		this.cdRequiredByDateN = cdRequiredByDateN;
		this.TPipoitems = TPipoitems;
	}

	@Id

	@Column(name = "CdCustOrderID", unique = true, nullable = false)
	public int getCdCustOrderId() {
		return this.cdCustOrderId;
	}

	public void setCdCustOrderId(int cdCustOrderId) {
		this.cdCustOrderId = cdCustOrderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CdCustID", nullable = false)
	public TCuCust getTCuCust() {
		return this.TCuCust;
	}

	public void setTCuCust(TCuCust TCuCust) {
		this.TCuCust = TCuCust;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CdEmpID", nullable = false)
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CdStoreID", nullable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CdInvoiceItemID_N")
	public TIiinvoiceItem getTIiinvoiceItem() {
		return this.TIiinvoiceItem;
	}

	public void setTIiinvoiceItem(TIiinvoiceItem TIiinvoiceItem) {
		this.TIiinvoiceItem = TIiinvoiceItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CdStockItemID", nullable = false)
	public TSistockItem getTSistockItem() {
		return this.TSistockItem;
	}

	public void setTSistockItem(TSistockItem TSistockItem) {
		this.TSistockItem = TSistockItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CdContactMethodID_N")
	public TCmcontactMethod getTCmcontactMethod() {
		return this.TCmcontactMethod;
	}

	public void setTCmcontactMethod(TCmcontactMethod TCmcontactMethod) {
		this.TCmcontactMethod = TCmcontactMethod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CdCreationDate", nullable = false, length = 23)
	public Date getCdCreationDate() {
		return this.cdCreationDate;
	}

	public void setCdCreationDate(Date cdCreationDate) {
		this.cdCreationDate = cdCreationDate;
	}

	@Column(name = "CdPOID_N")
	public Integer getCdPoidN() {
		return this.cdPoidN;
	}

	public void setCdPoidN(Integer cdPoidN) {
		this.cdPoidN = cdPoidN;
	}

	@Column(name = "CdQtyIn", nullable = false)
	public short getCdQtyIn() {
		return this.cdQtyIn;
	}

	public void setCdQtyIn(short cdQtyIn) {
		this.cdQtyIn = cdQtyIn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CdPickedUpDate_N", length = 23)
	public Date getCdPickedUpDateN() {
		return this.cdPickedUpDateN;
	}

	public void setCdPickedUpDateN(Date cdPickedUpDateN) {
		this.cdPickedUpDateN = cdPickedUpDateN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CdNotifiedDate_N", length = 23)
	public Date getCdNotifiedDateN() {
		return this.cdNotifiedDateN;
	}

	public void setCdNotifiedDateN(Date cdNotifiedDateN) {
		this.cdNotifiedDateN = cdNotifiedDateN;
	}

	@Column(name = "CdNotesTx_N")
	public String getCdNotesTxN() {
		return this.cdNotesTxN;
	}

	public void setCdNotesTxN(String cdNotesTxN) {
		this.cdNotesTxN = cdNotesTxN;
	}

	@Column(name = "CdPONotesTx_N")
	public String getCdPonotesTxN() {
		return this.cdPonotesTxN;
	}

	public void setCdPonotesTxN(String cdPonotesTxN) {
		this.cdPonotesTxN = cdPonotesTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CdLastUpdatedDate", nullable = false, length = 23)
	public Date getCdLastUpdatedDate() {
		return this.cdLastUpdatedDate;
	}

	public void setCdLastUpdatedDate(Date cdLastUpdatedDate) {
		this.cdLastUpdatedDate = cdLastUpdatedDate;
	}

	@Column(name = "CdLocationTx_N")
	public String getCdLocationTxN() {
		return this.cdLocationTxN;
	}

	public void setCdLocationTxN(String cdLocationTxN) {
		this.cdLocationTxN = cdLocationTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CdRequiredByDate_N", length = 23)
	public Date getCdRequiredByDateN() {
		return this.cdRequiredByDateN;
	}

	public void setCdRequiredByDateN(Date cdRequiredByDateN) {
		this.cdRequiredByDateN = cdRequiredByDateN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCdCustOrder")
	public Set<TPipoitem> getTPipoitems() {
		return this.TPipoitems;
	}

	public void setTPipoitems(Set<TPipoitem> TPipoitems) {
		this.TPipoitems = TPipoitems;
	}

}
