package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TCeCostPrice generated by hbm2java
 */
@Entity
@Table(name = "T_CeCostPrice")
public class TCeCostPrice implements java.io.Serializable {

	private TCeCostPriceId id;
	private TSoStore TSoStore;
	private TSistockItem TSistockItem;
	private TSuSupplier TSuSupplier;
	private double ceCostPriceMn;
	private short ceCurrencyId;
	private float ceExchangeRate;

	public TCeCostPrice() {
	}

	public TCeCostPrice(TCeCostPriceId id, TSoStore TSoStore, TSistockItem TSistockItem, TSuSupplier TSuSupplier,
			double ceCostPriceMn, short ceCurrencyId, float ceExchangeRate) {
		this.id = id;
		this.TSoStore = TSoStore;
		this.TSistockItem = TSistockItem;
		this.TSuSupplier = TSuSupplier;
		this.ceCostPriceMn = ceCostPriceMn;
		this.ceCurrencyId = ceCurrencyId;
		this.ceExchangeRate = ceExchangeRate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ceStoreId", column = @Column(name = "CeStoreID", nullable = false)),
			@AttributeOverride(name = "ceSupplierId", column = @Column(name = "CeSupplierID", nullable = false)),
			@AttributeOverride(name = "ceStockItemId", column = @Column(name = "CeStockItemID", nullable = false)),
			@AttributeOverride(name = "ceLevelIn", column = @Column(name = "CeLevelIn", nullable = false)) })
	public TCeCostPriceId getId() {
		return this.id;
	}

	public void setId(TCeCostPriceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CeStoreID", nullable = false, insertable = false, updatable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CeStockItemID", nullable = false, insertable = false, updatable = false)
	public TSistockItem getTSistockItem() {
		return this.TSistockItem;
	}

	public void setTSistockItem(TSistockItem TSistockItem) {
		this.TSistockItem = TSistockItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CeSupplierID", nullable = false, insertable = false, updatable = false)
	public TSuSupplier getTSuSupplier() {
		return this.TSuSupplier;
	}

	public void setTSuSupplier(TSuSupplier TSuSupplier) {
		this.TSuSupplier = TSuSupplier;
	}

	@Column(name = "CeCostPriceMn", nullable = false, precision = 53, scale = 0)
	public double getCeCostPriceMn() {
		return this.ceCostPriceMn;
	}

	public void setCeCostPriceMn(double ceCostPriceMn) {
		this.ceCostPriceMn = ceCostPriceMn;
	}

	@Column(name = "CeCurrencyID", nullable = false)
	public short getCeCurrencyId() {
		return this.ceCurrencyId;
	}

	public void setCeCurrencyId(short ceCurrencyId) {
		this.ceCurrencyId = ceCurrencyId;
	}

	@Column(name = "CeExchangeRate", nullable = false, precision = 24, scale = 0)
	public float getCeExchangeRate() {
		return this.ceExchangeRate;
	}

	public void setCeExchangeRate(float ceExchangeRate) {
		this.ceExchangeRate = ceExchangeRate;
	}

}
