package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TCgcustGroup generated by hbm2java
 */
@Entity
@Table(name = "T_CGCustGroup", uniqueConstraints = @UniqueConstraint(columnNames = { "CGCustID", "CGGroupID" }))
public class TCgcustGroup implements java.io.Serializable {

	private int cgcustGroupId;
	private TCuCust TCuCust;
	private TGpGroup TGpGroup;
	private Date cgcreationDate;

	public TCgcustGroup() {
	}

	public TCgcustGroup(int cgcustGroupId, TCuCust TCuCust, TGpGroup TGpGroup, Date cgcreationDate) {
		this.cgcustGroupId = cgcustGroupId;
		this.TCuCust = TCuCust;
		this.TGpGroup = TGpGroup;
		this.cgcreationDate = cgcreationDate;
	}

	@Id

	@Column(name = "CGCustGroupID", unique = true, nullable = false)
	public int getCgcustGroupId() {
		return this.cgcustGroupId;
	}

	public void setCgcustGroupId(int cgcustGroupId) {
		this.cgcustGroupId = cgcustGroupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CGCustID", nullable = false)
	public TCuCust getTCuCust() {
		return this.TCuCust;
	}

	public void setTCuCust(TCuCust TCuCust) {
		this.TCuCust = TCuCust;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CGGroupID", nullable = false)
	public TGpGroup getTGpGroup() {
		return this.TGpGroup;
	}

	public void setTGpGroup(TGpGroup TGpGroup) {
		this.TGpGroup = TGpGroup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CGCreationDate", nullable = false, length = 23)
	public Date getCgcreationDate() {
		return this.cgcreationDate;
	}

	public void setCgcreationDate(Date cgcreationDate) {
		this.cgcreationDate = cgcreationDate;
	}

}
