package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TCiCustCourseChecklist generated by hbm2java
 */
@Entity
@Table(name = "T_CiCustCourseChecklist")
public class TCiCustCourseChecklist implements java.io.Serializable {

	private TCiCustCourseChecklistId id;
	private TC1custCourse TC1custCourse;
	private TStstockType TStstockType;
	private String ciRequirementTxN;
	private Integer ciSizeIdN;

	public TCiCustCourseChecklist() {
	}

	public TCiCustCourseChecklist(TCiCustCourseChecklistId id, TC1custCourse TC1custCourse, TStstockType TStstockType) {
		this.id = id;
		this.TC1custCourse = TC1custCourse;
		this.TStstockType = TStstockType;
	}

	public TCiCustCourseChecklist(TCiCustCourseChecklistId id, TC1custCourse TC1custCourse, TStstockType TStstockType,
			String ciRequirementTxN, Integer ciSizeIdN) {
		this.id = id;
		this.TC1custCourse = TC1custCourse;
		this.TStstockType = TStstockType;
		this.ciRequirementTxN = ciRequirementTxN;
		this.ciSizeIdN = ciSizeIdN;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ciCustCourseId", column = @Column(name = "CiCustCourseID", nullable = false)),
			@AttributeOverride(name = "ciStockTypeId", column = @Column(name = "CiStockTypeID", nullable = false)) })
	public TCiCustCourseChecklistId getId() {
		return this.id;
	}

	public void setId(TCiCustCourseChecklistId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CiCustCourseID", nullable = false, insertable = false, updatable = false)
	public TC1custCourse getTC1custCourse() {
		return this.TC1custCourse;
	}

	public void setTC1custCourse(TC1custCourse TC1custCourse) {
		this.TC1custCourse = TC1custCourse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CiStockTypeID", nullable = false, insertable = false, updatable = false)
	public TStstockType getTStstockType() {
		return this.TStstockType;
	}

	public void setTStstockType(TStstockType TStstockType) {
		this.TStstockType = TStstockType;
	}

	@Column(name = "CiRequirementTx_N")
	public String getCiRequirementTxN() {
		return this.ciRequirementTxN;
	}

	public void setCiRequirementTxN(String ciRequirementTxN) {
		this.ciRequirementTxN = ciRequirementTxN;
	}

	@Column(name = "CiSizeID_N")
	public Integer getCiSizeIdN() {
		return this.ciSizeIdN;
	}

	public void setCiSizeIdN(Integer ciSizeIdN) {
		this.ciSizeIdN = ciSizeIdN;
	}

}
