package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TCkCustTripChecklistId generated by hbm2java
 */
@Embeddable
public class TCkCustTripChecklistId implements java.io.Serializable {

	private int ckCustTripId;
	private int ckStockTypeId;

	public TCkCustTripChecklistId() {
	}

	public TCkCustTripChecklistId(int ckCustTripId, int ckStockTypeId) {
		this.ckCustTripId = ckCustTripId;
		this.ckStockTypeId = ckStockTypeId;
	}

	@Column(name = "CkCustTripID", nullable = false)
	public int getCkCustTripId() {
		return this.ckCustTripId;
	}

	public void setCkCustTripId(int ckCustTripId) {
		this.ckCustTripId = ckCustTripId;
	}

	@Column(name = "CkStockTypeID", nullable = false)
	public int getCkStockTypeId() {
		return this.ckStockTypeId;
	}

	public void setCkStockTypeId(int ckStockTypeId) {
		this.ckStockTypeId = ckStockTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TCkCustTripChecklistId))
			return false;
		TCkCustTripChecklistId castOther = (TCkCustTripChecklistId) other;

		return (this.getCkCustTripId() == castOther.getCkCustTripId())
				&& (this.getCkStockTypeId() == castOther.getCkStockTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCkCustTripId();
		result = 37 * result + this.getCkStockTypeId();
		return result;
	}

}
