package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TClColor generated by hbm2java
 */
@Entity
@Table(name = "T_ClColor", uniqueConstraints = @UniqueConstraint(columnNames = "ClColorTx"))
public class TClColor implements java.io.Serializable {

	private int clColorId;
	private String clColorTx;
	private boolean clUnavailableBl;
	private Date clLastUpdatedDate;
	private boolean clRequiredBl;
	private Date clCreationDate;
	private boolean clShouldDisplayBl;
	private Set<TSistockItem> TSistockItemsForSisecondaryColorIdN = new HashSet<TSistockItem>(0);
	private Set<TEqEquipment> TEqEquipmentsForEqSecondaryColorIdN = new HashSet<TEqEquipment>(0);
	private Set<TEqEquipment> TEqEquipmentsForEqPrimaryColorIdN = new HashSet<TEqEquipment>(0);
	private Set<TSistockItem> TSistockItemsForSiprimaryColorIdN = new HashSet<TSistockItem>(0);

	public TClColor() {
	}

	public TClColor(int clColorId, String clColorTx, boolean clUnavailableBl, Date clLastUpdatedDate,
			boolean clRequiredBl, Date clCreationDate, boolean clShouldDisplayBl) {
		this.clColorId = clColorId;
		this.clColorTx = clColorTx;
		this.clUnavailableBl = clUnavailableBl;
		this.clLastUpdatedDate = clLastUpdatedDate;
		this.clRequiredBl = clRequiredBl;
		this.clCreationDate = clCreationDate;
		this.clShouldDisplayBl = clShouldDisplayBl;
	}

	public TClColor(int clColorId, String clColorTx, boolean clUnavailableBl, Date clLastUpdatedDate,
			boolean clRequiredBl, Date clCreationDate, boolean clShouldDisplayBl,
			Set<TSistockItem> TSistockItemsForSisecondaryColorIdN,
			Set<TEqEquipment> TEqEquipmentsForEqSecondaryColorIdN, Set<TEqEquipment> TEqEquipmentsForEqPrimaryColorIdN,
			Set<TSistockItem> TSistockItemsForSiprimaryColorIdN) {
		this.clColorId = clColorId;
		this.clColorTx = clColorTx;
		this.clUnavailableBl = clUnavailableBl;
		this.clLastUpdatedDate = clLastUpdatedDate;
		this.clRequiredBl = clRequiredBl;
		this.clCreationDate = clCreationDate;
		this.clShouldDisplayBl = clShouldDisplayBl;
		this.TSistockItemsForSisecondaryColorIdN = TSistockItemsForSisecondaryColorIdN;
		this.TEqEquipmentsForEqSecondaryColorIdN = TEqEquipmentsForEqSecondaryColorIdN;
		this.TEqEquipmentsForEqPrimaryColorIdN = TEqEquipmentsForEqPrimaryColorIdN;
		this.TSistockItemsForSiprimaryColorIdN = TSistockItemsForSiprimaryColorIdN;
	}

	@Id

	@Column(name = "ClColorID", unique = true, nullable = false)
	public int getClColorId() {
		return this.clColorId;
	}

	public void setClColorId(int clColorId) {
		this.clColorId = clColorId;
	}

	@Column(name = "ClColorTx", unique = true, nullable = false)
	public String getClColorTx() {
		return this.clColorTx;
	}

	public void setClColorTx(String clColorTx) {
		this.clColorTx = clColorTx;
	}

	@Column(name = "ClUnavailableBl", nullable = false)
	public boolean isClUnavailableBl() {
		return this.clUnavailableBl;
	}

	public void setClUnavailableBl(boolean clUnavailableBl) {
		this.clUnavailableBl = clUnavailableBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ClLastUpdatedDate", nullable = false, length = 23)
	public Date getClLastUpdatedDate() {
		return this.clLastUpdatedDate;
	}

	public void setClLastUpdatedDate(Date clLastUpdatedDate) {
		this.clLastUpdatedDate = clLastUpdatedDate;
	}

	@Column(name = "ClRequiredBl", nullable = false)
	public boolean isClRequiredBl() {
		return this.clRequiredBl;
	}

	public void setClRequiredBl(boolean clRequiredBl) {
		this.clRequiredBl = clRequiredBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ClCreationDate", nullable = false, length = 23)
	public Date getClCreationDate() {
		return this.clCreationDate;
	}

	public void setClCreationDate(Date clCreationDate) {
		this.clCreationDate = clCreationDate;
	}

	@Column(name = "ClShouldDisplayBl", nullable = false)
	public boolean isClShouldDisplayBl() {
		return this.clShouldDisplayBl;
	}

	public void setClShouldDisplayBl(boolean clShouldDisplayBl) {
		this.clShouldDisplayBl = clShouldDisplayBl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TClColorBySisecondaryColorIdN")
	public Set<TSistockItem> getTSistockItemsForSisecondaryColorIdN() {
		return this.TSistockItemsForSisecondaryColorIdN;
	}

	public void setTSistockItemsForSisecondaryColorIdN(Set<TSistockItem> TSistockItemsForSisecondaryColorIdN) {
		this.TSistockItemsForSisecondaryColorIdN = TSistockItemsForSisecondaryColorIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TClColorByEqSecondaryColorIdN")
	public Set<TEqEquipment> getTEqEquipmentsForEqSecondaryColorIdN() {
		return this.TEqEquipmentsForEqSecondaryColorIdN;
	}

	public void setTEqEquipmentsForEqSecondaryColorIdN(Set<TEqEquipment> TEqEquipmentsForEqSecondaryColorIdN) {
		this.TEqEquipmentsForEqSecondaryColorIdN = TEqEquipmentsForEqSecondaryColorIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TClColorByEqPrimaryColorIdN")
	public Set<TEqEquipment> getTEqEquipmentsForEqPrimaryColorIdN() {
		return this.TEqEquipmentsForEqPrimaryColorIdN;
	}

	public void setTEqEquipmentsForEqPrimaryColorIdN(Set<TEqEquipment> TEqEquipmentsForEqPrimaryColorIdN) {
		this.TEqEquipmentsForEqPrimaryColorIdN = TEqEquipmentsForEqPrimaryColorIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TClColorBySiprimaryColorIdN")
	public Set<TSistockItem> getTSistockItemsForSiprimaryColorIdN() {
		return this.TSistockItemsForSiprimaryColorIdN;
	}

	public void setTSistockItemsForSiprimaryColorIdN(Set<TSistockItem> TSistockItemsForSiprimaryColorIdN) {
		this.TSistockItemsForSiprimaryColorIdN = TSistockItemsForSiprimaryColorIdN;
	}

}
