package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TCnContact generated by hbm2java
 */
@Entity
@Table(name = "T_CnContact")
public class TCnContact implements java.io.Serializable {

	private int cnContactId;
	private TC8custInterest TC8custInterest;
	private TEmEmp TEmEmp;
	private TSoStore TSoStore;
	private TCmcontactMethod TCmcontactMethod;
	private TCuCust TCuCust;
	private TFafollowUpAction TFafollowUpAction;
	private Date cnCreationDate;
	private Date cnLastUpdatedDate;
	private String cnNotesTxN;
	private Date cnActualDateN;
	private Date cnProposedDate;
	private Date cnReminderDate;
	private boolean cnSmsreminderBl;
	private Date cnSmssentDate;
	private Date cnProposedEndDateN;
	private Date cnActualEndDateN;
	private Integer cnOrigInvoiceIdN;
	private String cnStreetAddressTxN;
	private String cnPostcodeTxN;

	public TCnContact() {
	}

	public TCnContact(int cnContactId, TSoStore TSoStore, TCmcontactMethod TCmcontactMethod, TCuCust TCuCust,
			TFafollowUpAction TFafollowUpAction, Date cnCreationDate, Date cnLastUpdatedDate, Date cnProposedDate,
			Date cnReminderDate, boolean cnSmsreminderBl) {
		this.cnContactId = cnContactId;
		this.TSoStore = TSoStore;
		this.TCmcontactMethod = TCmcontactMethod;
		this.TCuCust = TCuCust;
		this.TFafollowUpAction = TFafollowUpAction;
		this.cnCreationDate = cnCreationDate;
		this.cnLastUpdatedDate = cnLastUpdatedDate;
		this.cnProposedDate = cnProposedDate;
		this.cnReminderDate = cnReminderDate;
		this.cnSmsreminderBl = cnSmsreminderBl;
	}

	public TCnContact(int cnContactId, TC8custInterest TC8custInterest, TEmEmp TEmEmp, TSoStore TSoStore,
			TCmcontactMethod TCmcontactMethod, TCuCust TCuCust, TFafollowUpAction TFafollowUpAction,
			Date cnCreationDate, Date cnLastUpdatedDate, String cnNotesTxN, Date cnActualDateN,
			Date cnProposedDate, Date cnReminderDate, boolean cnSmsreminderBl, Date cnSmssentDate,
			Date cnProposedEndDateN, Date cnActualEndDateN, Integer cnOrigInvoiceIdN, String cnStreetAddressTxN,
			String cnPostcodeTxN) {
		this.cnContactId = cnContactId;
		this.TC8custInterest = TC8custInterest;
		this.TEmEmp = TEmEmp;
		this.TSoStore = TSoStore;
		this.TCmcontactMethod = TCmcontactMethod;
		this.TCuCust = TCuCust;
		this.TFafollowUpAction = TFafollowUpAction;
		this.cnCreationDate = cnCreationDate;
		this.cnLastUpdatedDate = cnLastUpdatedDate;
		this.cnNotesTxN = cnNotesTxN;
		this.cnActualDateN = cnActualDateN;
		this.cnProposedDate = cnProposedDate;
		this.cnReminderDate = cnReminderDate;
		this.cnSmsreminderBl = cnSmsreminderBl;
		this.cnSmssentDate = cnSmssentDate;
		this.cnProposedEndDateN = cnProposedEndDateN;
		this.cnActualEndDateN = cnActualEndDateN;
		this.cnOrigInvoiceIdN = cnOrigInvoiceIdN;
		this.cnStreetAddressTxN = cnStreetAddressTxN;
		this.cnPostcodeTxN = cnPostcodeTxN;
	}

	@Id

	@Column(name = "CnContactID", unique = true, nullable = false)
	public int getCnContactId() {
		return this.cnContactId;
	}

	public void setCnContactId(int cnContactId) {
		this.cnContactId = cnContactId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CnCustInterestID_N")
	public TC8custInterest getTC8custInterest() {
		return this.TC8custInterest;
	}

	public void setTC8custInterest(TC8custInterest TC8custInterest) {
		this.TC8custInterest = TC8custInterest;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CnEmpID_N")
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CnStoreID", nullable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CnContactMethodID", nullable = false)
	public TCmcontactMethod getTCmcontactMethod() {
		return this.TCmcontactMethod;
	}

	public void setTCmcontactMethod(TCmcontactMethod TCmcontactMethod) {
		this.TCmcontactMethod = TCmcontactMethod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CnCustID", nullable = false)
	public TCuCust getTCuCust() {
		return this.TCuCust;
	}

	public void setTCuCust(TCuCust TCuCust) {
		this.TCuCust = TCuCust;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CnActionID", nullable = false)
	public TFafollowUpAction getTFafollowUpAction() {
		return this.TFafollowUpAction;
	}

	public void setTFafollowUpAction(TFafollowUpAction TFafollowUpAction) {
		this.TFafollowUpAction = TFafollowUpAction;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CnCreationDate", nullable = false, length = 23)
	public Date getCnCreationDate() {
		return this.cnCreationDate;
	}

	public void setCnCreationDate(Date cnCreationDate) {
		this.cnCreationDate = cnCreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CnLastUpdatedDate", nullable = false, length = 23)
	public Date getCnLastUpdatedDate() {
		return this.cnLastUpdatedDate;
	}

	public void setCnLastUpdatedDate(Date cnLastUpdatedDate) {
		this.cnLastUpdatedDate = cnLastUpdatedDate;
	}

	@Column(name = "CnNotesTx_N")
	public String getCnNotesTxN() {
		return this.cnNotesTxN;
	}

	public void setCnNotesTxN(String cnNotesTxN) {
		this.cnNotesTxN = cnNotesTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CnActualDate_N", length = 23)
	public Date getCnActualDateN() {
		return this.cnActualDateN;
	}

	public void setCnActualDateN(Date cnActualDateN) {
		this.cnActualDateN = cnActualDateN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CnProposedDate", nullable = false, length = 23)
	public Date getCnProposedDate() {
		return this.cnProposedDate;
	}

	public void setCnProposedDate(Date cnProposedDate) {
		this.cnProposedDate = cnProposedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CnReminderDate", nullable = false, length = 23)
	public Date getCnReminderDate() {
		return this.cnReminderDate;
	}

	public void setCnReminderDate(Date cnReminderDate) {
		this.cnReminderDate = cnReminderDate;
	}

	@Column(name = "CnSMSReminderBl", nullable = false)
	public boolean isCnSmsreminderBl() {
		return this.cnSmsreminderBl;
	}

	public void setCnSmsreminderBl(boolean cnSmsreminderBl) {
		this.cnSmsreminderBl = cnSmsreminderBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CnSMSSentDate", length = 23)
	public Date getCnSmssentDate() {
		return this.cnSmssentDate;
	}

	public void setCnSmssentDate(Date cnSmssentDate) {
		this.cnSmssentDate = cnSmssentDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CnProposedEndDate_N", length = 23)
	public Date getCnProposedEndDateN() {
		return this.cnProposedEndDateN;
	}

	public void setCnProposedEndDateN(Date cnProposedEndDateN) {
		this.cnProposedEndDateN = cnProposedEndDateN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CnActualEndDate_N", length = 23)
	public Date getCnActualEndDateN() {
		return this.cnActualEndDateN;
	}

	public void setCnActualEndDateN(Date cnActualEndDateN) {
		this.cnActualEndDateN = cnActualEndDateN;
	}

	@Column(name = "CnOrigInvoiceID_N")
	public Integer getCnOrigInvoiceIdN() {
		return this.cnOrigInvoiceIdN;
	}

	public void setCnOrigInvoiceIdN(Integer cnOrigInvoiceIdN) {
		this.cnOrigInvoiceIdN = cnOrigInvoiceIdN;
	}

	@Column(name = "CnStreetAddressTx_N")
	public String getCnStreetAddressTxN() {
		return this.cnStreetAddressTxN;
	}

	public void setCnStreetAddressTxN(String cnStreetAddressTxN) {
		this.cnStreetAddressTxN = cnStreetAddressTxN;
	}

	@Column(name = "CnPostcodeTx_N")
	public String getCnPostcodeTxN() {
		return this.cnPostcodeTxN;
	}

	public void setCnPostcodeTxN(String cnPostcodeTxN) {
		this.cnPostcodeTxN = cnPostcodeTxN;
	}

}
