package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TCvCustTypeDiscountBand generated by hbm2java
 */
@Entity
@Table(name = "T_CvCustTypeDiscountBand")
public class TCvCustTypeDiscountBand implements java.io.Serializable {

	private TCvCustTypeDiscountBandId id;
	private TChCustType TChCustType;
	private TDbdiscountBand TDbdiscountBand;
	private TStstockType TStstockType;
	private TCccostCenter TCccostCenter;

	public TCvCustTypeDiscountBand() {
	}

	public TCvCustTypeDiscountBand(TCvCustTypeDiscountBandId id, TChCustType TChCustType,
			TDbdiscountBand TDbdiscountBand, TStstockType TStstockType, TCccostCenter TCccostCenter) {
		this.id = id;
		this.TChCustType = TChCustType;
		this.TDbdiscountBand = TDbdiscountBand;
		this.TStstockType = TStstockType;
		this.TCccostCenter = TCccostCenter;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cvCustTypeId", column = @Column(name = "CvCustTypeID", nullable = false)),
			@AttributeOverride(name = "cvStockTypeId", column = @Column(name = "CvStockTypeID", nullable = false)),
			@AttributeOverride(name = "cvCostCenterId", column = @Column(name = "CvCostCenterID", nullable = false)) })
	public TCvCustTypeDiscountBandId getId() {
		return this.id;
	}

	public void setId(TCvCustTypeDiscountBandId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CvCustTypeID", nullable = false, insertable = false, updatable = false)
	public TChCustType getTChCustType() {
		return this.TChCustType;
	}

	public void setTChCustType(TChCustType TChCustType) {
		this.TChCustType = TChCustType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CvDiscountBandID", nullable = false)
	public TDbdiscountBand getTDbdiscountBand() {
		return this.TDbdiscountBand;
	}

	public void setTDbdiscountBand(TDbdiscountBand TDbdiscountBand) {
		this.TDbdiscountBand = TDbdiscountBand;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CvStockTypeID", nullable = false, insertable = false, updatable = false)
	public TStstockType getTStstockType() {
		return this.TStstockType;
	}

	public void setTStstockType(TStstockType TStstockType) {
		this.TStstockType = TStstockType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CvCostCenterID", nullable = false, insertable = false, updatable = false)
	public TCccostCenter getTCccostCenter() {
		return this.TCccostCenter;
	}

	public void setTCccostCenter(TCccostCenter TCccostCenter) {
		this.TCccostCenter = TCccostCenter;
	}

}
