package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TCyCountry generated by hbm2java
 */
@Entity
@Table(name = "T_CyCountry", uniqueConstraints = { @UniqueConstraint(columnNames = "CyPADIKeyTx"),
		@UniqueConstraint(columnNames = "CyCountryTx") })
public class TCyCountry implements java.io.Serializable {

	private int cyCountryId;
	private String cyCountryTx;
	private String cyPadikeyTx;
	private boolean cyStatedBl;
	private boolean cyUnavailableBl;
	private Date cyLastUpdatedDate;
	private boolean cyRequiredBl;
	private Integer cyNewPadikeyInN;
	private boolean cyPostcodeMandatoryBl;
	private Set<TSoStore> TSoStores = new HashSet<TSoStore>(0);
	private Set<TVcvalidCountry> TVcvalidCountries = new HashSet<TVcvalidCountry>(0);
	private Set<TCuCust> TCuCustsForCuCountryIdN = new HashSet<TCuCust>(0);
	private Set<TXcshippingCountry> TXcshippingCountries = new HashSet<TXcshippingCountry>(0);
	private Set<TCuCust> TCuCustsForCuWcountryIdN = new HashSet<TCuCust>(0);
	private Set<TLcLocation> TLcLocations = new HashSet<TLcLocation>(0);
	private Set<TSeState> TSeStates = new HashSet<TSeState>(0);

	public TCyCountry() {
	}

	public TCyCountry(int cyCountryId, String cyCountryTx, String cyPadikeyTx, boolean cyStatedBl,
			boolean cyUnavailableBl, Date cyLastUpdatedDate, boolean cyRequiredBl, boolean cyPostcodeMandatoryBl) {
		this.cyCountryId = cyCountryId;
		this.cyCountryTx = cyCountryTx;
		this.cyPadikeyTx = cyPadikeyTx;
		this.cyStatedBl = cyStatedBl;
		this.cyUnavailableBl = cyUnavailableBl;
		this.cyLastUpdatedDate = cyLastUpdatedDate;
		this.cyRequiredBl = cyRequiredBl;
		this.cyPostcodeMandatoryBl = cyPostcodeMandatoryBl;
	}

	public TCyCountry(int cyCountryId, String cyCountryTx, String cyPadikeyTx, boolean cyStatedBl,
			boolean cyUnavailableBl, Date cyLastUpdatedDate, boolean cyRequiredBl, Integer cyNewPadikeyInN,
			boolean cyPostcodeMandatoryBl, Set<TSoStore> TSoStores, Set<TVcvalidCountry> TVcvalidCountries,
			Set<TCuCust> TCuCustsForCuCountryIdN, Set<TXcshippingCountry> TXcshippingCountries,
			Set<TCuCust> TCuCustsForCuWcountryIdN, Set<TLcLocation> TLcLocations, Set<TSeState> TSeStates) {
		this.cyCountryId = cyCountryId;
		this.cyCountryTx = cyCountryTx;
		this.cyPadikeyTx = cyPadikeyTx;
		this.cyStatedBl = cyStatedBl;
		this.cyUnavailableBl = cyUnavailableBl;
		this.cyLastUpdatedDate = cyLastUpdatedDate;
		this.cyRequiredBl = cyRequiredBl;
		this.cyNewPadikeyInN = cyNewPadikeyInN;
		this.cyPostcodeMandatoryBl = cyPostcodeMandatoryBl;
		this.TSoStores = TSoStores;
		this.TVcvalidCountries = TVcvalidCountries;
		this.TCuCustsForCuCountryIdN = TCuCustsForCuCountryIdN;
		this.TXcshippingCountries = TXcshippingCountries;
		this.TCuCustsForCuWcountryIdN = TCuCustsForCuWcountryIdN;
		this.TLcLocations = TLcLocations;
		this.TSeStates = TSeStates;
	}

	@Id

	@Column(name = "CyCountryID", unique = true, nullable = false)
	public int getCyCountryId() {
		return this.cyCountryId;
	}

	public void setCyCountryId(int cyCountryId) {
		this.cyCountryId = cyCountryId;
	}

	@Column(name = "CyCountryTx", unique = true, nullable = false)
	public String getCyCountryTx() {
		return this.cyCountryTx;
	}

	public void setCyCountryTx(String cyCountryTx) {
		this.cyCountryTx = cyCountryTx;
	}

	@Column(name = "CyPADIKeyTx", unique = true, nullable = false)
	public String getCyPadikeyTx() {
		return this.cyPadikeyTx;
	}

	public void setCyPadikeyTx(String cyPadikeyTx) {
		this.cyPadikeyTx = cyPadikeyTx;
	}

	@Column(name = "CyStatedBl", nullable = false)
	public boolean isCyStatedBl() {
		return this.cyStatedBl;
	}

	public void setCyStatedBl(boolean cyStatedBl) {
		this.cyStatedBl = cyStatedBl;
	}

	@Column(name = "CyUnavailableBl", nullable = false)
	public boolean isCyUnavailableBl() {
		return this.cyUnavailableBl;
	}

	public void setCyUnavailableBl(boolean cyUnavailableBl) {
		this.cyUnavailableBl = cyUnavailableBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CyLastUpdatedDate", nullable = false, length = 23)
	public Date getCyLastUpdatedDate() {
		return this.cyLastUpdatedDate;
	}

	public void setCyLastUpdatedDate(Date cyLastUpdatedDate) {
		this.cyLastUpdatedDate = cyLastUpdatedDate;
	}

	@Column(name = "CyRequiredBl", nullable = false)
	public boolean isCyRequiredBl() {
		return this.cyRequiredBl;
	}

	public void setCyRequiredBl(boolean cyRequiredBl) {
		this.cyRequiredBl = cyRequiredBl;
	}

	@Column(name = "CyNewPADIKeyIn_N")
	public Integer getCyNewPadikeyInN() {
		return this.cyNewPadikeyInN;
	}

	public void setCyNewPadikeyInN(Integer cyNewPadikeyInN) {
		this.cyNewPadikeyInN = cyNewPadikeyInN;
	}

	@Column(name = "CyPostcodeMandatoryBl", nullable = false)
	public boolean isCyPostcodeMandatoryBl() {
		return this.cyPostcodeMandatoryBl;
	}

	public void setCyPostcodeMandatoryBl(boolean cyPostcodeMandatoryBl) {
		this.cyPostcodeMandatoryBl = cyPostcodeMandatoryBl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCyCountry")
	public Set<TSoStore> getTSoStores() {
		return this.TSoStores;
	}

	public void setTSoStores(Set<TSoStore> TSoStores) {
		this.TSoStores = TSoStores;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCyCountry")
	public Set<TVcvalidCountry> getTVcvalidCountries() {
		return this.TVcvalidCountries;
	}

	public void setTVcvalidCountries(Set<TVcvalidCountry> TVcvalidCountries) {
		this.TVcvalidCountries = TVcvalidCountries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCyCountryByCuCountryIdN")
	public Set<TCuCust> getTCuCustsForCuCountryIdN() {
		return this.TCuCustsForCuCountryIdN;
	}

	public void setTCuCustsForCuCountryIdN(Set<TCuCust> TCuCustsForCuCountryIdN) {
		this.TCuCustsForCuCountryIdN = TCuCustsForCuCountryIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCyCountry")
	public Set<TXcshippingCountry> getTXcshippingCountries() {
		return this.TXcshippingCountries;
	}

	public void setTXcshippingCountries(Set<TXcshippingCountry> TXcshippingCountries) {
		this.TXcshippingCountries = TXcshippingCountries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCyCountryByCuWcountryIdN")
	public Set<TCuCust> getTCuCustsForCuWcountryIdN() {
		return this.TCuCustsForCuWcountryIdN;
	}

	public void setTCuCustsForCuWcountryIdN(Set<TCuCust> TCuCustsForCuWcountryIdN) {
		this.TCuCustsForCuWcountryIdN = TCuCustsForCuWcountryIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCyCountry")
	public Set<TLcLocation> getTLcLocations() {
		return this.TLcLocations;
	}

	public void setTLcLocations(Set<TLcLocation> TLcLocations) {
		this.TLcLocations = TLcLocations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCyCountry")
	public Set<TSeState> getTSeStates() {
		return this.TSeStates;
	}

	public void setTSeStates(Set<TSeState> TSeStates) {
		this.TSeStates = TSeStates;
	}

}
