package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TCzCustModuleId generated by hbm2java
 */
@Embeddable
public class TCzCustModuleId implements java.io.Serializable {

	private int czCustId;
	private int czModuleId;

	public TCzCustModuleId() {
	}

	public TCzCustModuleId(int czCustId, int czModuleId) {
		this.czCustId = czCustId;
		this.czModuleId = czModuleId;
	}

	@Column(name = "CzCustID", nullable = false)
	public int getCzCustId() {
		return this.czCustId;
	}

	public void setCzCustId(int czCustId) {
		this.czCustId = czCustId;
	}

	@Column(name = "CzModuleID", nullable = false)
	public int getCzModuleId() {
		return this.czModuleId;
	}

	public void setCzModuleId(int czModuleId) {
		this.czModuleId = czModuleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TCzCustModuleId))
			return false;
		TCzCustModuleId castOther = (TCzCustModuleId) other;

		return (this.getCzCustId() == castOther.getCzCustId()) && (this.getCzModuleId() == castOther.getCzModuleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCzCustId();
		result = 37 * result + this.getCzModuleId();
		return result;
	}

}
