package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDiDiveProfile generated by hbm2java
 */
@Entity
@Table(name = "T_DiDiveProfile")
public class TDiDiveProfile implements java.io.Serializable {

	private int diDiveProfileId;
	private TEmEmp TEmEmp;
	private TDtDestination TDtDestination;
	private TCuCust TCuCust;
	private Date diStartDateN;
	private Date diEndDateN;
	private String diAirInTxN;
	private String diAirOutTxN;
	private String diMaxDepthTxN;
	private boolean diWellAtStartBl;
	private boolean diWellAtEndBl;
	private boolean diComputerBl;
	private String diNotesTxN;
	private Date diCreationDate;
	private Date diLastUpdatedDate;
	private boolean diWheelBl;
	private String diSurfaceIntervalTxN;
	private String diRgdtxN;

	public TDiDiveProfile() {
	}

	public TDiDiveProfile(int diDiveProfileId, TEmEmp TEmEmp, TCuCust TCuCust, boolean diWellAtStartBl,
			boolean diWellAtEndBl, boolean diComputerBl, Date diCreationDate, Date diLastUpdatedDate,
			boolean diWheelBl) {
		this.diDiveProfileId = diDiveProfileId;
		this.TEmEmp = TEmEmp;
		this.TCuCust = TCuCust;
		this.diWellAtStartBl = diWellAtStartBl;
		this.diWellAtEndBl = diWellAtEndBl;
		this.diComputerBl = diComputerBl;
		this.diCreationDate = diCreationDate;
		this.diLastUpdatedDate = diLastUpdatedDate;
		this.diWheelBl = diWheelBl;
	}

	public TDiDiveProfile(int diDiveProfileId, TEmEmp TEmEmp, TDtDestination TDtDestination, TCuCust TCuCust,
			Date diStartDateN, Date diEndDateN, String diAirInTxN, String diAirOutTxN,
			String diMaxDepthTxN, boolean diWellAtStartBl, boolean diWellAtEndBl, boolean diComputerBl,
			String diNotesTxN, Date diCreationDate, Date diLastUpdatedDate, boolean diWheelBl,
			String diSurfaceIntervalTxN, String diRgdtxN) {
		this.diDiveProfileId = diDiveProfileId;
		this.TEmEmp = TEmEmp;
		this.TDtDestination = TDtDestination;
		this.TCuCust = TCuCust;
		this.diStartDateN = diStartDateN;
		this.diEndDateN = diEndDateN;
		this.diAirInTxN = diAirInTxN;
		this.diAirOutTxN = diAirOutTxN;
		this.diMaxDepthTxN = diMaxDepthTxN;
		this.diWellAtStartBl = diWellAtStartBl;
		this.diWellAtEndBl = diWellAtEndBl;
		this.diComputerBl = diComputerBl;
		this.diNotesTxN = diNotesTxN;
		this.diCreationDate = diCreationDate;
		this.diLastUpdatedDate = diLastUpdatedDate;
		this.diWheelBl = diWheelBl;
		this.diSurfaceIntervalTxN = diSurfaceIntervalTxN;
		this.diRgdtxN = diRgdtxN;
	}

	@Id

	@Column(name = "DiDiveProfileID", unique = true, nullable = false)
	public int getDiDiveProfileId() {
		return this.diDiveProfileId;
	}

	public void setDiDiveProfileId(int diDiveProfileId) {
		this.diDiveProfileId = diDiveProfileId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DiEmpID", nullable = false)
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DiDestinationID_N")
	public TDtDestination getTDtDestination() {
		return this.TDtDestination;
	}

	public void setTDtDestination(TDtDestination TDtDestination) {
		this.TDtDestination = TDtDestination;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DiCustID", nullable = false)
	public TCuCust getTCuCust() {
		return this.TCuCust;
	}

	public void setTCuCust(TCuCust TCuCust) {
		this.TCuCust = TCuCust;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DiStartDate_N", length = 23)
	public Date getDiStartDateN() {
		return this.diStartDateN;
	}

	public void setDiStartDateN(Date diStartDateN) {
		this.diStartDateN = diStartDateN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DiEndDate_N", length = 23)
	public Date getDiEndDateN() {
		return this.diEndDateN;
	}

	public void setDiEndDateN(Date diEndDateN) {
		this.diEndDateN = diEndDateN;
	}

	@Column(name = "DiAirInTx_N")
	public String getDiAirInTxN() {
		return this.diAirInTxN;
	}

	public void setDiAirInTxN(String diAirInTxN) {
		this.diAirInTxN = diAirInTxN;
	}

	@Column(name = "DiAirOutTx_N")
	public String getDiAirOutTxN() {
		return this.diAirOutTxN;
	}

	public void setDiAirOutTxN(String diAirOutTxN) {
		this.diAirOutTxN = diAirOutTxN;
	}

	@Column(name = "DiMaxDepthTx_N")
	public String getDiMaxDepthTxN() {
		return this.diMaxDepthTxN;
	}

	public void setDiMaxDepthTxN(String diMaxDepthTxN) {
		this.diMaxDepthTxN = diMaxDepthTxN;
	}

	@Column(name = "DiWellAtStartBl", nullable = false)
	public boolean isDiWellAtStartBl() {
		return this.diWellAtStartBl;
	}

	public void setDiWellAtStartBl(boolean diWellAtStartBl) {
		this.diWellAtStartBl = diWellAtStartBl;
	}

	@Column(name = "DiWellAtEndBl", nullable = false)
	public boolean isDiWellAtEndBl() {
		return this.diWellAtEndBl;
	}

	public void setDiWellAtEndBl(boolean diWellAtEndBl) {
		this.diWellAtEndBl = diWellAtEndBl;
	}

	@Column(name = "DiComputerBl", nullable = false)
	public boolean isDiComputerBl() {
		return this.diComputerBl;
	}

	public void setDiComputerBl(boolean diComputerBl) {
		this.diComputerBl = diComputerBl;
	}

	@Column(name = "DiNotesTx_N")
	public String getDiNotesTxN() {
		return this.diNotesTxN;
	}

	public void setDiNotesTxN(String diNotesTxN) {
		this.diNotesTxN = diNotesTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DiCreationDate", nullable = false, length = 23)
	public Date getDiCreationDate() {
		return this.diCreationDate;
	}

	public void setDiCreationDate(Date diCreationDate) {
		this.diCreationDate = diCreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DiLastUpdatedDate", nullable = false, length = 23)
	public Date getDiLastUpdatedDate() {
		return this.diLastUpdatedDate;
	}

	public void setDiLastUpdatedDate(Date diLastUpdatedDate) {
		this.diLastUpdatedDate = diLastUpdatedDate;
	}

	@Column(name = "DiWheelBl", nullable = false)
	public boolean isDiWheelBl() {
		return this.diWheelBl;
	}

	public void setDiWheelBl(boolean diWheelBl) {
		this.diWheelBl = diWheelBl;
	}

	@Column(name = "DiSurfaceIntervalTx_N")
	public String getDiSurfaceIntervalTxN() {
		return this.diSurfaceIntervalTxN;
	}

	public void setDiSurfaceIntervalTxN(String diSurfaceIntervalTxN) {
		this.diSurfaceIntervalTxN = diSurfaceIntervalTxN;
	}

	@Column(name = "DiRGDTx_N")
	public String getDiRgdtxN() {
		return this.diRgdtxN;
	}

	public void setDiRgdtxN(String diRgdtxN) {
		this.diRgdtxN = diRgdtxN;
	}

}
