package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TDldocumentLink generated by hbm2java
 */
@Entity
@Table(name = "T_DLDocumentLink", uniqueConstraints = @UniqueConstraint(columnNames = { "DLDataID", "DLDataTypeID",
		"DLDocumentID" }))
public class TDldocumentLink implements java.io.Serializable {

	private int dldocumenLinkId;
	private TDcDocument TDcDocument;
	private TDtdataType TDtdataType;
	private int dldataId;
	private boolean dlrequiredBl;

	public TDldocumentLink() {
	}

	public TDldocumentLink(int dldocumenLinkId, TDcDocument TDcDocument, TDtdataType TDtdataType, int dldataId,
			boolean dlrequiredBl) {
		this.dldocumenLinkId = dldocumenLinkId;
		this.TDcDocument = TDcDocument;
		this.TDtdataType = TDtdataType;
		this.dldataId = dldataId;
		this.dlrequiredBl = dlrequiredBl;
	}

	@Id

	@Column(name = "DLDocumenLinkID", unique = true, nullable = false)
	public int getDldocumenLinkId() {
		return this.dldocumenLinkId;
	}

	public void setDldocumenLinkId(int dldocumenLinkId) {
		this.dldocumenLinkId = dldocumenLinkId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DLDocumentID", nullable = false)
	public TDcDocument getTDcDocument() {
		return this.TDcDocument;
	}

	public void setTDcDocument(TDcDocument TDcDocument) {
		this.TDcDocument = TDcDocument;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DLDataTypeID", nullable = false)
	public TDtdataType getTDtdataType() {
		return this.TDtdataType;
	}

	public void setTDtdataType(TDtdataType TDtdataType) {
		this.TDtdataType = TDtdataType;
	}

	@Column(name = "DLDataID", nullable = false)
	public int getDldataId() {
		return this.dldataId;
	}

	public void setDldataId(int dldataId) {
		this.dldataId = dldataId;
	}

	@Column(name = "DLRequiredBl", nullable = false)
	public boolean isDlrequiredBl() {
		return this.dlrequiredBl;
	}

	public void setDlrequiredBl(boolean dlrequiredBl) {
		this.dlrequiredBl = dlrequiredBl;
	}

}
