package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TDmdataTypeMenu generated by hbm2java
 */
@Entity
@Table(name = "T_DMDataTypeMenu")
public class TDmdataTypeMenu implements java.io.Serializable {

	private int dmdataTypeMenuId;
	private TDtdataType TDtdataType;
	private TMnMenu TMnMenu;

	public TDmdataTypeMenu() {
	}

	public TDmdataTypeMenu(int dmdataTypeMenuId, TDtdataType TDtdataType, TMnMenu TMnMenu) {
		this.dmdataTypeMenuId = dmdataTypeMenuId;
		this.TDtdataType = TDtdataType;
		this.TMnMenu = TMnMenu;
	}

	@Id

	@Column(name = "DMDataTypeMenuID", unique = true, nullable = false)
	public int getDmdataTypeMenuId() {
		return this.dmdataTypeMenuId;
	}

	public void setDmdataTypeMenuId(int dmdataTypeMenuId) {
		this.dmdataTypeMenuId = dmdataTypeMenuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMDataTypeID", nullable = false)
	public TDtdataType getTDtdataType() {
		return this.TDtdataType;
	}

	public void setTDtdataType(TDtdataType TDtdataType) {
		this.TDtdataType = TDtdataType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DMMenuID", nullable = false)
	public TMnMenu getTMnMenu() {
		return this.TMnMenu;
	}

	public void setTMnMenu(TMnMenu TMnMenu) {
		this.TMnMenu = TMnMenu;
	}

}
