package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TDpdataPcdefaults generated by hbm2java
 */
@Entity
@Table(name = "T_DPDataPCDefaults")
public class TDpdataPcdefaults implements java.io.Serializable {

	private TDpdataPcdefaultsId id;

	public TDpdataPcdefaults() {
	}

	public TDpdataPcdefaults(TDpdataPcdefaultsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "dpdataId", column = @Column(name = "DPDataID", nullable = false)),
			@AttributeOverride(name = "dppcid", column = @Column(name = "DPPCID", nullable = false)),
			@AttributeOverride(name = "dpdataValueTxN", column = @Column(name = "DPDataValueTx_N", nullable = false)) })
	public TDpdataPcdefaultsId getId() {
		return this.id;
	}

	public void setId(TDpdataPcdefaultsId id) {
		this.id = id;
	}

}
