package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TDpdataPcdefaultsId generated by hbm2java
 */
@Embeddable
public class TDpdataPcdefaultsId implements java.io.Serializable {

	private int dpdataId;
	private int dppcid;
	private String dpdataValueTxN;

	public TDpdataPcdefaultsId() {
	}

	public TDpdataPcdefaultsId(int dpdataId, int dppcid, String dpdataValueTxN) {
		this.dpdataId = dpdataId;
		this.dppcid = dppcid;
		this.dpdataValueTxN = dpdataValueTxN;
	}

	@Column(name = "DPDataID", nullable = false)
	public int getDpdataId() {
		return this.dpdataId;
	}

	public void setDpdataId(int dpdataId) {
		this.dpdataId = dpdataId;
	}

	@Column(name = "DPPCID", nullable = false)
	public int getDppcid() {
		return this.dppcid;
	}

	public void setDppcid(int dppcid) {
		this.dppcid = dppcid;
	}

	@Column(name = "DPDataValueTx_N", nullable = false)
	public String getDpdataValueTxN() {
		return this.dpdataValueTxN;
	}

	public void setDpdataValueTxN(String dpdataValueTxN) {
		this.dpdataValueTxN = dpdataValueTxN;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TDpdataPcdefaultsId))
			return false;
		TDpdataPcdefaultsId castOther = (TDpdataPcdefaultsId) other;

		return (this.getDpdataId() == castOther.getDpdataId()) && (this.getDppcid() == castOther.getDppcid())
				&& ((this.getDpdataValueTxN() == castOther.getDpdataValueTxN())
						|| (this.getDpdataValueTxN() != null && castOther.getDpdataValueTxN() != null
								&& this.getDpdataValueTxN().equals(castOther.getDpdataValueTxN())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDpdataId();
		result = 37 * result + this.getDppcid();
		result = 37 * result + (getDpdataValueTxN() == null ? 0 : this.getDpdataValueTxN().hashCode());
		return result;
	}

}
