package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TDpdataPc generated by hbm2java
 */
@Entity
@Table(name = "T_DPDataPC", uniqueConstraints = @UniqueConstraint(columnNames = { "DPDataID", "DPStoreID", "DPPCID" }))
public class TDpdataPc implements java.io.Serializable {

	private int dpdataPcid;
	private TDaData TDaData;
	private short dppcid;
	private String dpdataValueTxN;
	private int dpstoreId;

	public TDpdataPc() {
	}

	public TDpdataPc(int dpdataPcid, TDaData TDaData, short dppcid, int dpstoreId) {
		this.dpdataPcid = dpdataPcid;
		this.TDaData = TDaData;
		this.dppcid = dppcid;
		this.dpstoreId = dpstoreId;
	}

	public TDpdataPc(int dpdataPcid, TDaData TDaData, short dppcid, String dpdataValueTxN, int dpstoreId) {
		this.dpdataPcid = dpdataPcid;
		this.TDaData = TDaData;
		this.dppcid = dppcid;
		this.dpdataValueTxN = dpdataValueTxN;
		this.dpstoreId = dpstoreId;
	}

	@Id

	@Column(name = "DPDataPCID", unique = true, nullable = false)
	public int getDpdataPcid() {
		return this.dpdataPcid;
	}

	public void setDpdataPcid(int dpdataPcid) {
		this.dpdataPcid = dpdataPcid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DPDataID", nullable = false)
	public TDaData getTDaData() {
		return this.TDaData;
	}

	public void setTDaData(TDaData TDaData) {
		this.TDaData = TDaData;
	}

	@Column(name = "DPPCID", nullable = false)
	public short getDppcid() {
		return this.dppcid;
	}

	public void setDppcid(short dppcid) {
		this.dppcid = dppcid;
	}

	@Column(name = "DPDataValueTx_N")
	public String getDpdataValueTxN() {
		return this.dpdataValueTxN;
	}

	public void setDpdataValueTxN(String dpdataValueTxN) {
		this.dpdataValueTxN = dpdataValueTxN;
	}

	@Column(name = "DPStoreID", nullable = false)
	public int getDpstoreId() {
		return this.dpstoreId;
	}

	public void setDpstoreId(int dpstoreId) {
		this.dpstoreId = dpstoreId;
	}

}
