package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TDtdataType generated by hbm2java
 */
@Entity
@Table(name = "T_DTDataType", uniqueConstraints = @UniqueConstraint(columnNames = "DTTablePrefix"))
public class TDtdataType implements java.io.Serializable {

	private short dtdataTypeId;
	private String dtdataTypeTx;
	private String dttablePrefix;
	private String dtsingularDescTx;
	private String dtpluralDescTx;
	private int dtprocessOrderIn;
	private int dtminId;
	private int dtmaxId;
	private int dtnextId;
	private Date dtlastUpdatedDate;
	private String dtassemblyTx;
	private String dtclassTx;
	private String dtdataEntryFnTx;
	private String dtdataSearchFnTx;
	private String dtdataDeleteFnTx;
	private String dtdataVoidFnTx;
	private short dtsmallImageIdx;
	private short dtlargeImageIdx;
	private String dtdataTypeIdsTxN;
	private String dtsendToCaptionsTxN;
	private String dtstoreTableTx;
	private boolean dtstoreViewBl;
	private short dtprivViewIn;
	private short dtprivNewIn;
	private short dtprivEditIn;
	private short dtprivDeleteIn;
	private short dtprivVoidIn;
	private short dtprivUnlockIn;
	private String dtstoreViewSqltxN;
	private boolean dtlockableBl;
	private String dtdataPrintFnTx;
	private Short dtnewMenuModuleIdN;
	private Short dtfindMenuModuleIdN;
	private boolean dtlookupBl;
	private boolean dtpreloadLookupBl;
	private String dtexportSqltxN;
	private boolean dtsearchPromptBl;
	private boolean dtshowAllOnLoadBl;
	private String dtorderByTxN;
	private boolean dthasRequiredBl;
	private int dttopXin;
	private Integer dtvalueToAddIn;
	private boolean dtsavePromptBl;
	private String dtdaDataIdsTxN;
	private short dtprivStoreViewIn;
	private short dtprivFindIn;
	private String dtdescriptionTxN;
	private Set<TDldocumentLink> TDldocumentLinks = new HashSet<TDldocumentLink>(0);
	private Set<TFpformProperty> TFpformProperties = new HashSet<TFpformProperty>(0);
	private Set<TShShortcut> TShShortcuts = new HashSet<TShShortcut>(0);
	private Set<TSistockItem> TSistockItems = new HashSet<TSistockItem>(0);
	private Set<TDfDefault> TDfDefaults = new HashSet<TDfDefault>(0);
	private Set<TDmdataTypeMenu> TDmdataTypeMenus = new HashSet<TDmdataTypeMenu>(0);
	private Set<TZoStoreDataType> TZoStoreDataTypes = new HashSet<TZoStoreDataType>(0);
	private Set<TAmAlarm> TAmAlarms = new HashSet<TAmAlarm>(0);
	private Set<TS6storeConfig> TS6storeConfigs = new HashSet<TS6storeConfig>(0);
	private Set<TFoformOpt> TFoformOpts = new HashSet<TFoformOpt>(0);
	private Set<TGigiftTypeAllowedItem> TGigiftTypeAllowedItems = new HashSet<TGigiftTypeAllowedItem>(0);

	public TDtdataType() {
	}

	public TDtdataType(short dtdataTypeId, String dtdataTypeTx, String dtsingularDescTx,
			String dtpluralDescTx, int dtprocessOrderIn, int dtminId, int dtmaxId, int dtnextId,
			Date dtlastUpdatedDate, String dtassemblyTx, String dtdataEntryFnTx,
			String dtdataSearchFnTx, String dtdataDeleteFnTx, String dtdataVoidFnTx,
			short dtsmallImageIdx, short dtlargeImageIdx, boolean dtstoreViewBl, short dtprivViewIn, short dtprivNewIn,
			short dtprivEditIn, short dtprivDeleteIn, short dtprivVoidIn, short dtprivUnlockIn, boolean dtlockableBl,
			String dtdataPrintFnTx, boolean dtlookupBl, boolean dtpreloadLookupBl, boolean dtsearchPromptBl,
			boolean dtshowAllOnLoadBl, boolean dthasRequiredBl, int dttopXin, boolean dtsavePromptBl,
			short dtprivStoreViewIn, short dtprivFindIn) {
		this.dtdataTypeId = dtdataTypeId;
		this.dtdataTypeTx = dtdataTypeTx;
		this.dtsingularDescTx = dtsingularDescTx;
		this.dtpluralDescTx = dtpluralDescTx;
		this.dtprocessOrderIn = dtprocessOrderIn;
		this.dtminId = dtminId;
		this.dtmaxId = dtmaxId;
		this.dtnextId = dtnextId;
		this.dtlastUpdatedDate = dtlastUpdatedDate;
		this.dtassemblyTx = dtassemblyTx;
		this.dtdataEntryFnTx = dtdataEntryFnTx;
		this.dtdataSearchFnTx = dtdataSearchFnTx;
		this.dtdataDeleteFnTx = dtdataDeleteFnTx;
		this.dtdataVoidFnTx = dtdataVoidFnTx;
		this.dtsmallImageIdx = dtsmallImageIdx;
		this.dtlargeImageIdx = dtlargeImageIdx;
		this.dtstoreViewBl = dtstoreViewBl;
		this.dtprivViewIn = dtprivViewIn;
		this.dtprivNewIn = dtprivNewIn;
		this.dtprivEditIn = dtprivEditIn;
		this.dtprivDeleteIn = dtprivDeleteIn;
		this.dtprivVoidIn = dtprivVoidIn;
		this.dtprivUnlockIn = dtprivUnlockIn;
		this.dtlockableBl = dtlockableBl;
		this.dtdataPrintFnTx = dtdataPrintFnTx;
		this.dtlookupBl = dtlookupBl;
		this.dtpreloadLookupBl = dtpreloadLookupBl;
		this.dtsearchPromptBl = dtsearchPromptBl;
		this.dtshowAllOnLoadBl = dtshowAllOnLoadBl;
		this.dthasRequiredBl = dthasRequiredBl;
		this.dttopXin = dttopXin;
		this.dtsavePromptBl = dtsavePromptBl;
		this.dtprivStoreViewIn = dtprivStoreViewIn;
		this.dtprivFindIn = dtprivFindIn;
	}

	public TDtdataType(short dtdataTypeId, String dtdataTypeTx, String dttablePrefix,
			String dtsingularDescTx, String dtpluralDescTx, int dtprocessOrderIn, int dtminId, int dtmaxId,
			int dtnextId, Date dtlastUpdatedDate, String dtassemblyTx, String dtclassTx,
			String dtdataEntryFnTx, String dtdataSearchFnTx, String dtdataDeleteFnTx,
			String dtdataVoidFnTx, short dtsmallImageIdx, short dtlargeImageIdx, String dtdataTypeIdsTxN,
			String dtsendToCaptionsTxN, String dtstoreTableTx, boolean dtstoreViewBl, short dtprivViewIn,
			short dtprivNewIn, short dtprivEditIn, short dtprivDeleteIn, short dtprivVoidIn, short dtprivUnlockIn,
			String dtstoreViewSqltxN, boolean dtlockableBl, String dtdataPrintFnTx,
			Short dtnewMenuModuleIdN, Short dtfindMenuModuleIdN, boolean dtlookupBl, boolean dtpreloadLookupBl,
			String dtexportSqltxN, boolean dtsearchPromptBl, boolean dtshowAllOnLoadBl, String dtorderByTxN,
			boolean dthasRequiredBl, int dttopXin, Integer dtvalueToAddIn, boolean dtsavePromptBl,
			String dtdaDataIdsTxN, short dtprivStoreViewIn, short dtprivFindIn, String dtdescriptionTxN,
			Set<TDldocumentLink> TDldocumentLinks, Set<TFpformProperty> TFpformProperties,
			Set<TShShortcut> TShShortcuts, Set<TSistockItem> TSistockItems, Set<TDfDefault> TDfDefaults,
			Set<TDmdataTypeMenu> TDmdataTypeMenus, Set<TZoStoreDataType> TZoStoreDataTypes, Set<TAmAlarm> TAmAlarms,
			Set<TS6storeConfig> TS6storeConfigs, Set<TFoformOpt> TFoformOpts,
			Set<TGigiftTypeAllowedItem> TGigiftTypeAllowedItems) {
		this.dtdataTypeId = dtdataTypeId;
		this.dtdataTypeTx = dtdataTypeTx;
		this.dttablePrefix = dttablePrefix;
		this.dtsingularDescTx = dtsingularDescTx;
		this.dtpluralDescTx = dtpluralDescTx;
		this.dtprocessOrderIn = dtprocessOrderIn;
		this.dtminId = dtminId;
		this.dtmaxId = dtmaxId;
		this.dtnextId = dtnextId;
		this.dtlastUpdatedDate = dtlastUpdatedDate;
		this.dtassemblyTx = dtassemblyTx;
		this.dtclassTx = dtclassTx;
		this.dtdataEntryFnTx = dtdataEntryFnTx;
		this.dtdataSearchFnTx = dtdataSearchFnTx;
		this.dtdataDeleteFnTx = dtdataDeleteFnTx;
		this.dtdataVoidFnTx = dtdataVoidFnTx;
		this.dtsmallImageIdx = dtsmallImageIdx;
		this.dtlargeImageIdx = dtlargeImageIdx;
		this.dtdataTypeIdsTxN = dtdataTypeIdsTxN;
		this.dtsendToCaptionsTxN = dtsendToCaptionsTxN;
		this.dtstoreTableTx = dtstoreTableTx;
		this.dtstoreViewBl = dtstoreViewBl;
		this.dtprivViewIn = dtprivViewIn;
		this.dtprivNewIn = dtprivNewIn;
		this.dtprivEditIn = dtprivEditIn;
		this.dtprivDeleteIn = dtprivDeleteIn;
		this.dtprivVoidIn = dtprivVoidIn;
		this.dtprivUnlockIn = dtprivUnlockIn;
		this.dtstoreViewSqltxN = dtstoreViewSqltxN;
		this.dtlockableBl = dtlockableBl;
		this.dtdataPrintFnTx = dtdataPrintFnTx;
		this.dtnewMenuModuleIdN = dtnewMenuModuleIdN;
		this.dtfindMenuModuleIdN = dtfindMenuModuleIdN;
		this.dtlookupBl = dtlookupBl;
		this.dtpreloadLookupBl = dtpreloadLookupBl;
		this.dtexportSqltxN = dtexportSqltxN;
		this.dtsearchPromptBl = dtsearchPromptBl;
		this.dtshowAllOnLoadBl = dtshowAllOnLoadBl;
		this.dtorderByTxN = dtorderByTxN;
		this.dthasRequiredBl = dthasRequiredBl;
		this.dttopXin = dttopXin;
		this.dtvalueToAddIn = dtvalueToAddIn;
		this.dtsavePromptBl = dtsavePromptBl;
		this.dtdaDataIdsTxN = dtdaDataIdsTxN;
		this.dtprivStoreViewIn = dtprivStoreViewIn;
		this.dtprivFindIn = dtprivFindIn;
		this.dtdescriptionTxN = dtdescriptionTxN;
		this.TDldocumentLinks = TDldocumentLinks;
		this.TFpformProperties = TFpformProperties;
		this.TShShortcuts = TShShortcuts;
		this.TSistockItems = TSistockItems;
		this.TDfDefaults = TDfDefaults;
		this.TDmdataTypeMenus = TDmdataTypeMenus;
		this.TZoStoreDataTypes = TZoStoreDataTypes;
		this.TAmAlarms = TAmAlarms;
		this.TS6storeConfigs = TS6storeConfigs;
		this.TFoformOpts = TFoformOpts;
		this.TGigiftTypeAllowedItems = TGigiftTypeAllowedItems;
	}

	@Id

	@Column(name = "DTDataTypeID", unique = true, nullable = false)
	public short getDtdataTypeId() {
		return this.dtdataTypeId;
	}

	public void setDtdataTypeId(short dtdataTypeId) {
		this.dtdataTypeId = dtdataTypeId;
	}

	@Column(name = "DTDataTypeTx", nullable = false)
	public String getDtdataTypeTx() {
		return this.dtdataTypeTx;
	}

	public void setDtdataTypeTx(String dtdataTypeTx) {
		this.dtdataTypeTx = dtdataTypeTx;
	}

	@Column(name = "DTTablePrefix", unique = true)
	public String getDttablePrefix() {
		return this.dttablePrefix;
	}

	public void setDttablePrefix(String dttablePrefix) {
		this.dttablePrefix = dttablePrefix;
	}

	@Column(name = "DTSingularDescTx", nullable = false)
	public String getDtsingularDescTx() {
		return this.dtsingularDescTx;
	}

	public void setDtsingularDescTx(String dtsingularDescTx) {
		this.dtsingularDescTx = dtsingularDescTx;
	}

	@Column(name = "DTPluralDescTx", nullable = false)
	public String getDtpluralDescTx() {
		return this.dtpluralDescTx;
	}

	public void setDtpluralDescTx(String dtpluralDescTx) {
		this.dtpluralDescTx = dtpluralDescTx;
	}

	@Column(name = "DTProcessOrderIn", nullable = false)
	public int getDtprocessOrderIn() {
		return this.dtprocessOrderIn;
	}

	public void setDtprocessOrderIn(int dtprocessOrderIn) {
		this.dtprocessOrderIn = dtprocessOrderIn;
	}

	@Column(name = "DTMinID", nullable = false)
	public int getDtminId() {
		return this.dtminId;
	}

	public void setDtminId(int dtminId) {
		this.dtminId = dtminId;
	}

	@Column(name = "DTMaxID", nullable = false)
	public int getDtmaxId() {
		return this.dtmaxId;
	}

	public void setDtmaxId(int dtmaxId) {
		this.dtmaxId = dtmaxId;
	}

	@Column(name = "DTNextID", nullable = false)
	public int getDtnextId() {
		return this.dtnextId;
	}

	public void setDtnextId(int dtnextId) {
		this.dtnextId = dtnextId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTLastUpdatedDate", nullable = false, length = 23)
	public Date getDtlastUpdatedDate() {
		return this.dtlastUpdatedDate;
	}

	public void setDtlastUpdatedDate(Date dtlastUpdatedDate) {
		this.dtlastUpdatedDate = dtlastUpdatedDate;
	}

	@Column(name = "DTAssemblyTx", nullable = false)
	public String getDtassemblyTx() {
		return this.dtassemblyTx;
	}

	public void setDtassemblyTx(String dtassemblyTx) {
		this.dtassemblyTx = dtassemblyTx;
	}

	@Column(name = "DTClassTx")
	public String getDtclassTx() {
		return this.dtclassTx;
	}

	public void setDtclassTx(String dtclassTx) {
		this.dtclassTx = dtclassTx;
	}

	@Column(name = "DTDataEntryFnTx", nullable = false)
	public String getDtdataEntryFnTx() {
		return this.dtdataEntryFnTx;
	}

	public void setDtdataEntryFnTx(String dtdataEntryFnTx) {
		this.dtdataEntryFnTx = dtdataEntryFnTx;
	}

	@Column(name = "DTDataSearchFnTx", nullable = false)
	public String getDtdataSearchFnTx() {
		return this.dtdataSearchFnTx;
	}

	public void setDtdataSearchFnTx(String dtdataSearchFnTx) {
		this.dtdataSearchFnTx = dtdataSearchFnTx;
	}

	@Column(name = "DTDataDeleteFnTx", nullable = false)
	public String getDtdataDeleteFnTx() {
		return this.dtdataDeleteFnTx;
	}

	public void setDtdataDeleteFnTx(String dtdataDeleteFnTx) {
		this.dtdataDeleteFnTx = dtdataDeleteFnTx;
	}

	@Column(name = "DTDataVoidFnTx", nullable = false)
	public String getDtdataVoidFnTx() {
		return this.dtdataVoidFnTx;
	}

	public void setDtdataVoidFnTx(String dtdataVoidFnTx) {
		this.dtdataVoidFnTx = dtdataVoidFnTx;
	}

	@Column(name = "DTSmallImageIdx", nullable = false)
	public short getDtsmallImageIdx() {
		return this.dtsmallImageIdx;
	}

	public void setDtsmallImageIdx(short dtsmallImageIdx) {
		this.dtsmallImageIdx = dtsmallImageIdx;
	}

	@Column(name = "DTLargeImageIdx", nullable = false)
	public short getDtlargeImageIdx() {
		return this.dtlargeImageIdx;
	}

	public void setDtlargeImageIdx(short dtlargeImageIdx) {
		this.dtlargeImageIdx = dtlargeImageIdx;
	}

	@Column(name = "DTDataTypeIDsTx_N")
	public String getDtdataTypeIdsTxN() {
		return this.dtdataTypeIdsTxN;
	}

	public void setDtdataTypeIdsTxN(String dtdataTypeIdsTxN) {
		this.dtdataTypeIdsTxN = dtdataTypeIdsTxN;
	}

	@Column(name = "DTSendToCaptionsTx_N")
	public String getDtsendToCaptionsTxN() {
		return this.dtsendToCaptionsTxN;
	}

	public void setDtsendToCaptionsTxN(String dtsendToCaptionsTxN) {
		this.dtsendToCaptionsTxN = dtsendToCaptionsTxN;
	}

	@Column(name = "DTStoreTableTx")
	public String getDtstoreTableTx() {
		return this.dtstoreTableTx;
	}

	public void setDtstoreTableTx(String dtstoreTableTx) {
		this.dtstoreTableTx = dtstoreTableTx;
	}

	@Column(name = "DTStoreViewBl", nullable = false)
	public boolean isDtstoreViewBl() {
		return this.dtstoreViewBl;
	}

	public void setDtstoreViewBl(boolean dtstoreViewBl) {
		this.dtstoreViewBl = dtstoreViewBl;
	}

	@Column(name = "DTPrivViewIn", nullable = false)
	public short getDtprivViewIn() {
		return this.dtprivViewIn;
	}

	public void setDtprivViewIn(short dtprivViewIn) {
		this.dtprivViewIn = dtprivViewIn;
	}

	@Column(name = "DTPrivNewIn", nullable = false)
	public short getDtprivNewIn() {
		return this.dtprivNewIn;
	}

	public void setDtprivNewIn(short dtprivNewIn) {
		this.dtprivNewIn = dtprivNewIn;
	}

	@Column(name = "DTPrivEditIn", nullable = false)
	public short getDtprivEditIn() {
		return this.dtprivEditIn;
	}

	public void setDtprivEditIn(short dtprivEditIn) {
		this.dtprivEditIn = dtprivEditIn;
	}

	@Column(name = "DTPrivDeleteIn", nullable = false)
	public short getDtprivDeleteIn() {
		return this.dtprivDeleteIn;
	}

	public void setDtprivDeleteIn(short dtprivDeleteIn) {
		this.dtprivDeleteIn = dtprivDeleteIn;
	}

	@Column(name = "DTPrivVoidIn", nullable = false)
	public short getDtprivVoidIn() {
		return this.dtprivVoidIn;
	}

	public void setDtprivVoidIn(short dtprivVoidIn) {
		this.dtprivVoidIn = dtprivVoidIn;
	}

	@Column(name = "DTPrivUnlockIn", nullable = false)
	public short getDtprivUnlockIn() {
		return this.dtprivUnlockIn;
	}

	public void setDtprivUnlockIn(short dtprivUnlockIn) {
		this.dtprivUnlockIn = dtprivUnlockIn;
	}

	@Column(name = "DTStoreViewSQLTx_N")
	public String getDtstoreViewSqltxN() {
		return this.dtstoreViewSqltxN;
	}

	public void setDtstoreViewSqltxN(String dtstoreViewSqltxN) {
		this.dtstoreViewSqltxN = dtstoreViewSqltxN;
	}

	@Column(name = "DTLockableBl", nullable = false)
	public boolean isDtlockableBl() {
		return this.dtlockableBl;
	}

	public void setDtlockableBl(boolean dtlockableBl) {
		this.dtlockableBl = dtlockableBl;
	}

	@Column(name = "DTDataPrintFnTx", nullable = false)
	public String getDtdataPrintFnTx() {
		return this.dtdataPrintFnTx;
	}

	public void setDtdataPrintFnTx(String dtdataPrintFnTx) {
		this.dtdataPrintFnTx = dtdataPrintFnTx;
	}

	@Column(name = "DTNewMenuModuleID_N")
	public Short getDtnewMenuModuleIdN() {
		return this.dtnewMenuModuleIdN;
	}

	public void setDtnewMenuModuleIdN(Short dtnewMenuModuleIdN) {
		this.dtnewMenuModuleIdN = dtnewMenuModuleIdN;
	}

	@Column(name = "DTFindMenuModuleID_N")
	public Short getDtfindMenuModuleIdN() {
		return this.dtfindMenuModuleIdN;
	}

	public void setDtfindMenuModuleIdN(Short dtfindMenuModuleIdN) {
		this.dtfindMenuModuleIdN = dtfindMenuModuleIdN;
	}

	@Column(name = "DTLookupBl", nullable = false)
	public boolean isDtlookupBl() {
		return this.dtlookupBl;
	}

	public void setDtlookupBl(boolean dtlookupBl) {
		this.dtlookupBl = dtlookupBl;
	}

	@Column(name = "DTPreloadLookupBl", nullable = false)
	public boolean isDtpreloadLookupBl() {
		return this.dtpreloadLookupBl;
	}

	public void setDtpreloadLookupBl(boolean dtpreloadLookupBl) {
		this.dtpreloadLookupBl = dtpreloadLookupBl;
	}

	@Column(name = "DTExportSQLTx_N")
	public String getDtexportSqltxN() {
		return this.dtexportSqltxN;
	}

	public void setDtexportSqltxN(String dtexportSqltxN) {
		this.dtexportSqltxN = dtexportSqltxN;
	}

	@Column(name = "DTSearchPromptBl", nullable = false)
	public boolean isDtsearchPromptBl() {
		return this.dtsearchPromptBl;
	}

	public void setDtsearchPromptBl(boolean dtsearchPromptBl) {
		this.dtsearchPromptBl = dtsearchPromptBl;
	}

	@Column(name = "DTShowAllOnLoadBl", nullable = false)
	public boolean isDtshowAllOnLoadBl() {
		return this.dtshowAllOnLoadBl;
	}

	public void setDtshowAllOnLoadBl(boolean dtshowAllOnLoadBl) {
		this.dtshowAllOnLoadBl = dtshowAllOnLoadBl;
	}

	@Column(name = "DTOrderByTx_N")
	public String getDtorderByTxN() {
		return this.dtorderByTxN;
	}

	public void setDtorderByTxN(String dtorderByTxN) {
		this.dtorderByTxN = dtorderByTxN;
	}

	@Column(name = "DTHasRequiredBl", nullable = false)
	public boolean isDthasRequiredBl() {
		return this.dthasRequiredBl;
	}

	public void setDthasRequiredBl(boolean dthasRequiredBl) {
		this.dthasRequiredBl = dthasRequiredBl;
	}

	@Column(name = "DTTopXIn", nullable = false)
	public int getDttopXin() {
		return this.dttopXin;
	}

	public void setDttopXin(int dttopXin) {
		this.dttopXin = dttopXin;
	}

	@Column(name = "DTValueToAddIn")
	public Integer getDtvalueToAddIn() {
		return this.dtvalueToAddIn;
	}

	public void setDtvalueToAddIn(Integer dtvalueToAddIn) {
		this.dtvalueToAddIn = dtvalueToAddIn;
	}

	@Column(name = "DTSavePromptBl", nullable = false)
	public boolean isDtsavePromptBl() {
		return this.dtsavePromptBl;
	}

	public void setDtsavePromptBl(boolean dtsavePromptBl) {
		this.dtsavePromptBl = dtsavePromptBl;
	}

	@Column(name = "DTDaDataIDsTx_N")
	public String getDtdaDataIdsTxN() {
		return this.dtdaDataIdsTxN;
	}

	public void setDtdaDataIdsTxN(String dtdaDataIdsTxN) {
		this.dtdaDataIdsTxN = dtdaDataIdsTxN;
	}

	@Column(name = "DTPrivStoreViewIn", nullable = false)
	public short getDtprivStoreViewIn() {
		return this.dtprivStoreViewIn;
	}

	public void setDtprivStoreViewIn(short dtprivStoreViewIn) {
		this.dtprivStoreViewIn = dtprivStoreViewIn;
	}

	@Column(name = "DTPrivFindIn", nullable = false)
	public short getDtprivFindIn() {
		return this.dtprivFindIn;
	}

	public void setDtprivFindIn(short dtprivFindIn) {
		this.dtprivFindIn = dtprivFindIn;
	}

	@Column(name = "DTDescriptionTx_N")
	public String getDtdescriptionTxN() {
		return this.dtdescriptionTxN;
	}

	public void setDtdescriptionTxN(String dtdescriptionTxN) {
		this.dtdescriptionTxN = dtdescriptionTxN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDtdataType")
	public Set<TDldocumentLink> getTDldocumentLinks() {
		return this.TDldocumentLinks;
	}

	public void setTDldocumentLinks(Set<TDldocumentLink> TDldocumentLinks) {
		this.TDldocumentLinks = TDldocumentLinks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDtdataType")
	public Set<TFpformProperty> getTFpformProperties() {
		return this.TFpformProperties;
	}

	public void setTFpformProperties(Set<TFpformProperty> TFpformProperties) {
		this.TFpformProperties = TFpformProperties;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDtdataType")
	public Set<TShShortcut> getTShShortcuts() {
		return this.TShShortcuts;
	}

	public void setTShShortcuts(Set<TShShortcut> TShShortcuts) {
		this.TShShortcuts = TShShortcuts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDtdataType")
	public Set<TSistockItem> getTSistockItems() {
		return this.TSistockItems;
	}

	public void setTSistockItems(Set<TSistockItem> TSistockItems) {
		this.TSistockItems = TSistockItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDtdataType")
	public Set<TDfDefault> getTDfDefaults() {
		return this.TDfDefaults;
	}

	public void setTDfDefaults(Set<TDfDefault> TDfDefaults) {
		this.TDfDefaults = TDfDefaults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDtdataType")
	public Set<TDmdataTypeMenu> getTDmdataTypeMenus() {
		return this.TDmdataTypeMenus;
	}

	public void setTDmdataTypeMenus(Set<TDmdataTypeMenu> TDmdataTypeMenus) {
		this.TDmdataTypeMenus = TDmdataTypeMenus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDtdataType")
	public Set<TZoStoreDataType> getTZoStoreDataTypes() {
		return this.TZoStoreDataTypes;
	}

	public void setTZoStoreDataTypes(Set<TZoStoreDataType> TZoStoreDataTypes) {
		this.TZoStoreDataTypes = TZoStoreDataTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDtdataType")
	public Set<TAmAlarm> getTAmAlarms() {
		return this.TAmAlarms;
	}

	public void setTAmAlarms(Set<TAmAlarm> TAmAlarms) {
		this.TAmAlarms = TAmAlarms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDtdataType")
	public Set<TS6storeConfig> getTS6storeConfigs() {
		return this.TS6storeConfigs;
	}

	public void setTS6storeConfigs(Set<TS6storeConfig> TS6storeConfigs) {
		this.TS6storeConfigs = TS6storeConfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDtdataType")
	public Set<TFoformOpt> getTFoformOpts() {
		return this.TFoformOpts;
	}

	public void setTFoformOpts(Set<TFoformOpt> TFoformOpts) {
		this.TFoformOpts = TFoformOpts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDtdataType")
	public Set<TGigiftTypeAllowedItem> getTGigiftTypeAllowedItems() {
		return this.TGigiftTypeAllowedItems;
	}

	public void setTGigiftTypeAllowedItems(Set<TGigiftTypeAllowedItem> TGigiftTypeAllowedItems) {
		this.TGigiftTypeAllowedItems = TGigiftTypeAllowedItems;
	}

}
