package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TDvdefaultValueId generated by hbm2java
 */
@Embeddable
public class TDvdefaultValueId implements java.io.Serializable {

	private int dvdefaultId;
	private String dvcontrol;

	public TDvdefaultValueId() {
	}

	public TDvdefaultValueId(int dvdefaultId, String dvcontrol) {
		this.dvdefaultId = dvdefaultId;
		this.dvcontrol = dvcontrol;
	}

	@Column(name = "DVDefaultID", nullable = false)
	public int getDvdefaultId() {
		return this.dvdefaultId;
	}

	public void setDvdefaultId(int dvdefaultId) {
		this.dvdefaultId = dvdefaultId;
	}

	@Column(name = "DVControl", nullable = false)
	public String getDvcontrol() {
		return this.dvcontrol;
	}

	public void setDvcontrol(String dvcontrol) {
		this.dvcontrol = dvcontrol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TDvdefaultValueId))
			return false;
		TDvdefaultValueId castOther = (TDvdefaultValueId) other;

		return (this.getDvdefaultId() == castOther.getDvdefaultId())
				&& ((this.getDvcontrol() == castOther.getDvcontrol()) || (this.getDvcontrol() != null
						&& castOther.getDvcontrol() != null && this.getDvcontrol().equals(castOther.getDvcontrol())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDvdefaultId();
		result = 37 * result + (getDvcontrol() == null ? 0 : this.getDvcontrol().hashCode());
		return result;
	}

}
