package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TDvdefaultValue generated by hbm2java
 */
@Entity
@Table(name = "T_DVDefaultValue")
public class TDvdefaultValue implements java.io.Serializable {

	private TDvdefaultValueId id;
	private TDfDefault TDfDefault;
	private String dvdataValueN;
	private String dvtextN;
	private boolean dvrequiredBl;

	public TDvdefaultValue() {
	}

	public TDvdefaultValue(TDvdefaultValueId id, TDfDefault TDfDefault, boolean dvrequiredBl) {
		this.id = id;
		this.TDfDefault = TDfDefault;
		this.dvrequiredBl = dvrequiredBl;
	}

	public TDvdefaultValue(TDvdefaultValueId id, TDfDefault TDfDefault, String dvdataValueN, String dvtextN,
			boolean dvrequiredBl) {
		this.id = id;
		this.TDfDefault = TDfDefault;
		this.dvdataValueN = dvdataValueN;
		this.dvtextN = dvtextN;
		this.dvrequiredBl = dvrequiredBl;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dvdefaultId", column = @Column(name = "DVDefaultID", nullable = false)),
			@AttributeOverride(name = "dvcontrol", column = @Column(name = "DVControl", nullable = false)) })
	public TDvdefaultValueId getId() {
		return this.id;
	}

	public void setId(TDvdefaultValueId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DVDefaultID", nullable = false, insertable = false, updatable = false)
	public TDfDefault getTDfDefault() {
		return this.TDfDefault;
	}

	public void setTDfDefault(TDfDefault TDfDefault) {
		this.TDfDefault = TDfDefault;
	}

	@Column(name = "DVDataValue_N")
	public String getDvdataValueN() {
		return this.dvdataValueN;
	}

	public void setDvdataValueN(String dvdataValueN) {
		this.dvdataValueN = dvdataValueN;
	}

	@Column(name = "DVText_N")
	public String getDvtextN() {
		return this.dvtextN;
	}

	public void setDvtextN(String dvtextN) {
		this.dvtextN = dvtextN;
	}

	@Column(name = "DVRequiredBl", nullable = false)
	public boolean isDvrequiredBl() {
		return this.dvrequiredBl;
	}

	public void setDvrequiredBl(boolean dvrequiredBl) {
		this.dvrequiredBl = dvrequiredBl;
	}

}
