package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TDyDocumentLinkType generated by hbm2java
 */
@Entity
@Table(name = "T_DyDocumentLinkType", uniqueConstraints = @UniqueConstraint(columnNames = "DyDocumentLinkTypeTx"))
public class TDyDocumentLinkType implements java.io.Serializable {

	private short dyDocumenLinkTypeId;
	private String dyDocumentLinkTypeTx;

	public TDyDocumentLinkType() {
	}

	public TDyDocumentLinkType(short dyDocumenLinkTypeId, String dyDocumentLinkTypeTx) {
		this.dyDocumenLinkTypeId = dyDocumenLinkTypeId;
		this.dyDocumentLinkTypeTx = dyDocumentLinkTypeTx;
	}

	@Id

	@Column(name = "DyDocumenLinkTypeID", unique = true, nullable = false)
	public short getDyDocumenLinkTypeId() {
		return this.dyDocumenLinkTypeId;
	}

	public void setDyDocumenLinkTypeId(short dyDocumenLinkTypeId) {
		this.dyDocumenLinkTypeId = dyDocumenLinkTypeId;
	}

	@Column(name = "DyDocumentLinkTypeTx", unique = true, nullable = false)
	public String getDyDocumentLinkTypeTx() {
		return this.dyDocumentLinkTypeTx;
	}

	public void setDyDocumentLinkTypeTx(String dyDocumentLinkTypeTx) {
		this.dyDocumentLinkTypeTx = dyDocumentLinkTypeTx;
	}

}
