package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TE3emailAgent generated by hbm2java
 */
@Entity
@Table(name = "T_E3EmailAgent")
public class TE3emailAgent implements java.io.Serializable {

	private int e3emailAgentId;
	private String e3eventTx;
	private String e3eventParam1txN;
	private String e3eventParam2txN;
	private String e3sqltx;
	private String e3outlookFolderTxN;
	private String e3subjectLineTx;
	private int e3delayIn;
	private int e3expiryDaysIn;
	private Date e3lastRunDate;
	private boolean e3confirmationRequiredBl;
	private String e3lastRunStatusTxN;
	private boolean e3runLaterIfAgentOffBl;
	private boolean e3unavailableBl;
	private String e3onMailingListsTxN;
	private String e3notOnMailingListsTxN;
	private String e3subQueryTxN;
	private int e3priorityIn;
	private boolean e3sendToNewsletterEngineBl;
	private String e3newsletterTemplateTxN;
	private String e3notesTxN;
	private String e3fromAccountTxN;
	private short e3storeId;
	private String e3primaryTablesTx;
	private int e3jobTypeId;
	private int e3subJobTypeId;
	private String e3listTxN;
	private boolean e3moveToFolderBl;
	private String e3viewTxN;
	private String e3columnsTxN;
	private String e3dateColumnTxN;
	private Integer e3datePeriodInN;
	private Integer e3dateValueInN;
	private Integer e3groupIdN;
	private Set<TE5emailFilter> TE5emailFilters = new HashSet<TE5emailFilter>(0);

	public TE3emailAgent() {
	}

	public TE3emailAgent(int e3emailAgentId, String e3eventTx, String e3sqltx, String e3subjectLineTx,
			int e3delayIn, int e3expiryDaysIn, Date e3lastRunDate, boolean e3confirmationRequiredBl,
			boolean e3runLaterIfAgentOffBl, boolean e3unavailableBl, int e3priorityIn,
			boolean e3sendToNewsletterEngineBl, short e3storeId, String e3primaryTablesTx, int e3jobTypeId,
			int e3subJobTypeId, boolean e3moveToFolderBl) {
		this.e3emailAgentId = e3emailAgentId;
		this.e3eventTx = e3eventTx;
		this.e3sqltx = e3sqltx;
		this.e3subjectLineTx = e3subjectLineTx;
		this.e3delayIn = e3delayIn;
		this.e3expiryDaysIn = e3expiryDaysIn;
		this.e3lastRunDate = e3lastRunDate;
		this.e3confirmationRequiredBl = e3confirmationRequiredBl;
		this.e3runLaterIfAgentOffBl = e3runLaterIfAgentOffBl;
		this.e3unavailableBl = e3unavailableBl;
		this.e3priorityIn = e3priorityIn;
		this.e3sendToNewsletterEngineBl = e3sendToNewsletterEngineBl;
		this.e3storeId = e3storeId;
		this.e3primaryTablesTx = e3primaryTablesTx;
		this.e3jobTypeId = e3jobTypeId;
		this.e3subJobTypeId = e3subJobTypeId;
		this.e3moveToFolderBl = e3moveToFolderBl;
	}

	public TE3emailAgent(int e3emailAgentId, String e3eventTx, String e3eventParam1txN,
			String e3eventParam2txN, String e3sqltx, String e3outlookFolderTxN,
			String e3subjectLineTx, int e3delayIn, int e3expiryDaysIn, Date e3lastRunDate,
			boolean e3confirmationRequiredBl, String e3lastRunStatusTxN, boolean e3runLaterIfAgentOffBl,
			boolean e3unavailableBl, String e3onMailingListsTxN, String e3notOnMailingListsTxN,
			String e3subQueryTxN, int e3priorityIn, boolean e3sendToNewsletterEngineBl,
			String e3newsletterTemplateTxN, String e3notesTxN, String e3fromAccountTxN,
			short e3storeId, String e3primaryTablesTx, int e3jobTypeId, int e3subJobTypeId,
			String e3listTxN, boolean e3moveToFolderBl, String e3viewTxN, String e3columnsTxN,
			String e3dateColumnTxN, Integer e3datePeriodInN, Integer e3dateValueInN, Integer e3groupIdN,
			Set<TE5emailFilter> TE5emailFilters) {
		this.e3emailAgentId = e3emailAgentId;
		this.e3eventTx = e3eventTx;
		this.e3eventParam1txN = e3eventParam1txN;
		this.e3eventParam2txN = e3eventParam2txN;
		this.e3sqltx = e3sqltx;
		this.e3outlookFolderTxN = e3outlookFolderTxN;
		this.e3subjectLineTx = e3subjectLineTx;
		this.e3delayIn = e3delayIn;
		this.e3expiryDaysIn = e3expiryDaysIn;
		this.e3lastRunDate = e3lastRunDate;
		this.e3confirmationRequiredBl = e3confirmationRequiredBl;
		this.e3lastRunStatusTxN = e3lastRunStatusTxN;
		this.e3runLaterIfAgentOffBl = e3runLaterIfAgentOffBl;
		this.e3unavailableBl = e3unavailableBl;
		this.e3onMailingListsTxN = e3onMailingListsTxN;
		this.e3notOnMailingListsTxN = e3notOnMailingListsTxN;
		this.e3subQueryTxN = e3subQueryTxN;
		this.e3priorityIn = e3priorityIn;
		this.e3sendToNewsletterEngineBl = e3sendToNewsletterEngineBl;
		this.e3newsletterTemplateTxN = e3newsletterTemplateTxN;
		this.e3notesTxN = e3notesTxN;
		this.e3fromAccountTxN = e3fromAccountTxN;
		this.e3storeId = e3storeId;
		this.e3primaryTablesTx = e3primaryTablesTx;
		this.e3jobTypeId = e3jobTypeId;
		this.e3subJobTypeId = e3subJobTypeId;
		this.e3listTxN = e3listTxN;
		this.e3moveToFolderBl = e3moveToFolderBl;
		this.e3viewTxN = e3viewTxN;
		this.e3columnsTxN = e3columnsTxN;
		this.e3dateColumnTxN = e3dateColumnTxN;
		this.e3datePeriodInN = e3datePeriodInN;
		this.e3dateValueInN = e3dateValueInN;
		this.e3groupIdN = e3groupIdN;
		this.TE5emailFilters = TE5emailFilters;
	}

	@Id

	@Column(name = "E3EmailAgentID", unique = true, nullable = false)
	public int getE3emailAgentId() {
		return this.e3emailAgentId;
	}

	public void setE3emailAgentId(int e3emailAgentId) {
		this.e3emailAgentId = e3emailAgentId;
	}

	@Column(name = "E3EventTx", nullable = false)
	public String getE3eventTx() {
		return this.e3eventTx;
	}

	public void setE3eventTx(String e3eventTx) {
		this.e3eventTx = e3eventTx;
	}

	@Column(name = "E3EventParam1Tx_N")
	public String getE3eventParam1txN() {
		return this.e3eventParam1txN;
	}

	public void setE3eventParam1txN(String e3eventParam1txN) {
		this.e3eventParam1txN = e3eventParam1txN;
	}

	@Column(name = "E3EventParam2Tx_N")
	public String getE3eventParam2txN() {
		return this.e3eventParam2txN;
	}

	public void setE3eventParam2txN(String e3eventParam2txN) {
		this.e3eventParam2txN = e3eventParam2txN;
	}

	@Column(name = "E3SQLTx", nullable = false)
	public String getE3sqltx() {
		return this.e3sqltx;
	}

	public void setE3sqltx(String e3sqltx) {
		this.e3sqltx = e3sqltx;
	}

	@Column(name = "E3OutlookFolderTx_N")
	public String getE3outlookFolderTxN() {
		return this.e3outlookFolderTxN;
	}

	public void setE3outlookFolderTxN(String e3outlookFolderTxN) {
		this.e3outlookFolderTxN = e3outlookFolderTxN;
	}

	@Column(name = "E3SubjectLineTx", nullable = false)
	public String getE3subjectLineTx() {
		return this.e3subjectLineTx;
	}

	public void setE3subjectLineTx(String e3subjectLineTx) {
		this.e3subjectLineTx = e3subjectLineTx;
	}

	@Column(name = "E3DelayIn", nullable = false)
	public int getE3delayIn() {
		return this.e3delayIn;
	}

	public void setE3delayIn(int e3delayIn) {
		this.e3delayIn = e3delayIn;
	}

	@Column(name = "E3ExpiryDaysIn", nullable = false)
	public int getE3expiryDaysIn() {
		return this.e3expiryDaysIn;
	}

	public void setE3expiryDaysIn(int e3expiryDaysIn) {
		this.e3expiryDaysIn = e3expiryDaysIn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "E3LastRunDate", nullable = false, length = 23)
	public Date getE3lastRunDate() {
		return this.e3lastRunDate;
	}

	public void setE3lastRunDate(Date e3lastRunDate) {
		this.e3lastRunDate = e3lastRunDate;
	}

	@Column(name = "E3ConfirmationRequiredBl", nullable = false)
	public boolean isE3confirmationRequiredBl() {
		return this.e3confirmationRequiredBl;
	}

	public void setE3confirmationRequiredBl(boolean e3confirmationRequiredBl) {
		this.e3confirmationRequiredBl = e3confirmationRequiredBl;
	}

	@Column(name = "E3LastRunStatusTx_N")
	public String getE3lastRunStatusTxN() {
		return this.e3lastRunStatusTxN;
	}

	public void setE3lastRunStatusTxN(String e3lastRunStatusTxN) {
		this.e3lastRunStatusTxN = e3lastRunStatusTxN;
	}

	@Column(name = "E3RunLaterIfAgentOffBl", nullable = false)
	public boolean isE3runLaterIfAgentOffBl() {
		return this.e3runLaterIfAgentOffBl;
	}

	public void setE3runLaterIfAgentOffBl(boolean e3runLaterIfAgentOffBl) {
		this.e3runLaterIfAgentOffBl = e3runLaterIfAgentOffBl;
	}

	@Column(name = "E3UnavailableBl", nullable = false)
	public boolean isE3unavailableBl() {
		return this.e3unavailableBl;
	}

	public void setE3unavailableBl(boolean e3unavailableBl) {
		this.e3unavailableBl = e3unavailableBl;
	}

	@Column(name = "E3OnMailingListsTx_N")
	public String getE3onMailingListsTxN() {
		return this.e3onMailingListsTxN;
	}

	public void setE3onMailingListsTxN(String e3onMailingListsTxN) {
		this.e3onMailingListsTxN = e3onMailingListsTxN;
	}

	@Column(name = "E3NotOnMailingListsTx_N")
	public String getE3notOnMailingListsTxN() {
		return this.e3notOnMailingListsTxN;
	}

	public void setE3notOnMailingListsTxN(String e3notOnMailingListsTxN) {
		this.e3notOnMailingListsTxN = e3notOnMailingListsTxN;
	}

	@Column(name = "E3SubQueryTx_N")
	public String getE3subQueryTxN() {
		return this.e3subQueryTxN;
	}

	public void setE3subQueryTxN(String e3subQueryTxN) {
		this.e3subQueryTxN = e3subQueryTxN;
	}

	@Column(name = "E3PriorityIn", nullable = false)
	public int getE3priorityIn() {
		return this.e3priorityIn;
	}

	public void setE3priorityIn(int e3priorityIn) {
		this.e3priorityIn = e3priorityIn;
	}

	@Column(name = "E3SendToNewsletterEngineBl", nullable = false)
	public boolean isE3sendToNewsletterEngineBl() {
		return this.e3sendToNewsletterEngineBl;
	}

	public void setE3sendToNewsletterEngineBl(boolean e3sendToNewsletterEngineBl) {
		this.e3sendToNewsletterEngineBl = e3sendToNewsletterEngineBl;
	}

	@Column(name = "E3NewsletterTemplateTx_N")
	public String getE3newsletterTemplateTxN() {
		return this.e3newsletterTemplateTxN;
	}

	public void setE3newsletterTemplateTxN(String e3newsletterTemplateTxN) {
		this.e3newsletterTemplateTxN = e3newsletterTemplateTxN;
	}

	@Column(name = "E3NotesTx_N")
	public String getE3notesTxN() {
		return this.e3notesTxN;
	}

	public void setE3notesTxN(String e3notesTxN) {
		this.e3notesTxN = e3notesTxN;
	}

	@Column(name = "E3FromAccountTx_N")
	public String getE3fromAccountTxN() {
		return this.e3fromAccountTxN;
	}

	public void setE3fromAccountTxN(String e3fromAccountTxN) {
		this.e3fromAccountTxN = e3fromAccountTxN;
	}

	@Column(name = "E3StoreID", nullable = false)
	public short getE3storeId() {
		return this.e3storeId;
	}

	public void setE3storeId(short e3storeId) {
		this.e3storeId = e3storeId;
	}

	@Column(name = "E3PrimaryTablesTx", nullable = false)
	public String getE3primaryTablesTx() {
		return this.e3primaryTablesTx;
	}

	public void setE3primaryTablesTx(String e3primaryTablesTx) {
		this.e3primaryTablesTx = e3primaryTablesTx;
	}

	@Column(name = "E3JobTypeID", nullable = false)
	public int getE3jobTypeId() {
		return this.e3jobTypeId;
	}

	public void setE3jobTypeId(int e3jobTypeId) {
		this.e3jobTypeId = e3jobTypeId;
	}

	@Column(name = "E3SubJobTypeID", nullable = false)
	public int getE3subJobTypeId() {
		return this.e3subJobTypeId;
	}

	public void setE3subJobTypeId(int e3subJobTypeId) {
		this.e3subJobTypeId = e3subJobTypeId;
	}

	@Column(name = "E3ListTx_N")
	public String getE3listTxN() {
		return this.e3listTxN;
	}

	public void setE3listTxN(String e3listTxN) {
		this.e3listTxN = e3listTxN;
	}

	@Column(name = "E3MoveToFolderBl", nullable = false)
	public boolean isE3moveToFolderBl() {
		return this.e3moveToFolderBl;
	}

	public void setE3moveToFolderBl(boolean e3moveToFolderBl) {
		this.e3moveToFolderBl = e3moveToFolderBl;
	}

	@Column(name = "E3ViewTx_N")
	public String getE3viewTxN() {
		return this.e3viewTxN;
	}

	public void setE3viewTxN(String e3viewTxN) {
		this.e3viewTxN = e3viewTxN;
	}

	@Column(name = "E3ColumnsTx_N")
	public String getE3columnsTxN() {
		return this.e3columnsTxN;
	}

	public void setE3columnsTxN(String e3columnsTxN) {
		this.e3columnsTxN = e3columnsTxN;
	}

	@Column(name = "E3DateColumnTx_N")
	public String getE3dateColumnTxN() {
		return this.e3dateColumnTxN;
	}

	public void setE3dateColumnTxN(String e3dateColumnTxN) {
		this.e3dateColumnTxN = e3dateColumnTxN;
	}

	@Column(name = "E3DatePeriodIn_N")
	public Integer getE3datePeriodInN() {
		return this.e3datePeriodInN;
	}

	public void setE3datePeriodInN(Integer e3datePeriodInN) {
		this.e3datePeriodInN = e3datePeriodInN;
	}

	@Column(name = "E3DateValueIn_N")
	public Integer getE3dateValueInN() {
		return this.e3dateValueInN;
	}

	public void setE3dateValueInN(Integer e3dateValueInN) {
		this.e3dateValueInN = e3dateValueInN;
	}

	@Column(name = "E3GroupID_N")
	public Integer getE3groupIdN() {
		return this.e3groupIdN;
	}

	public void setE3groupIdN(Integer e3groupIdN) {
		this.e3groupIdN = e3groupIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TE3emailAgent")
	public Set<TE5emailFilter> getTE5emailFilters() {
		return this.TE5emailFilters;
	}

	public void setTE5emailFilters(Set<TE5emailFilter> TE5emailFilters) {
		this.TE5emailFilters = TE5emailFilters;
	}

}
