package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TE4emailHistory generated by hbm2java
 */
@Entity
@Table(name = "T_E4EmailHistory")
public class TE4emailHistory implements java.io.Serializable {

	private int e4emailHistoryId;
	private int e4emailAgentId;
	private Date e4dateRun;
	private String e4statusTx;

	public TE4emailHistory() {
	}

	public TE4emailHistory(int e4emailHistoryId, int e4emailAgentId, Date e4dateRun, String e4statusTx) {
		this.e4emailHistoryId = e4emailHistoryId;
		this.e4emailAgentId = e4emailAgentId;
		this.e4dateRun = e4dateRun;
		this.e4statusTx = e4statusTx;
	}

	@Id

	@Column(name = "E4EmailHistoryID", unique = true, nullable = false)
	public int getE4emailHistoryId() {
		return this.e4emailHistoryId;
	}

	public void setE4emailHistoryId(int e4emailHistoryId) {
		this.e4emailHistoryId = e4emailHistoryId;
	}

	@Column(name = "E4EmailAgentID", nullable = false)
	public int getE4emailAgentId() {
		return this.e4emailAgentId;
	}

	public void setE4emailAgentId(int e4emailAgentId) {
		this.e4emailAgentId = e4emailAgentId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "E4DateRun", nullable = false, length = 16)
	public Date getE4dateRun() {
		return this.e4dateRun;
	}

	public void setE4dateRun(Date e4dateRun) {
		this.e4dateRun = e4dateRun;
	}

	@Column(name = "E4StatusTx", nullable = false)
	public String getE4statusTx() {
		return this.e4statusTx;
	}

	public void setE4statusTx(String e4statusTx) {
		this.e4statusTx = e4statusTx;
	}

}
