package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TE6group generated by hbm2java
 */
@Entity
@Table(name = "T_E6Group", uniqueConstraints = @UniqueConstraint(columnNames = "E6GroupTx"))
public class TE6group implements java.io.Serializable {

	private int e6groupId;
	private String e6groupTx;
	private boolean e6unavailableBl;
	private Date e6creationDate;
	private Date e6lastUpdatedDate;

	public TE6group() {
	}

	public TE6group(int e6groupId, String e6groupTx, boolean e6unavailableBl, Date e6creationDate,
			Date e6lastUpdatedDate) {
		this.e6groupId = e6groupId;
		this.e6groupTx = e6groupTx;
		this.e6unavailableBl = e6unavailableBl;
		this.e6creationDate = e6creationDate;
		this.e6lastUpdatedDate = e6lastUpdatedDate;
	}

	@Id

	@Column(name = "E6GroupID", unique = true, nullable = false)
	public int getE6groupId() {
		return this.e6groupId;
	}

	public void setE6groupId(int e6groupId) {
		this.e6groupId = e6groupId;
	}

	@Column(name = "E6GroupTx", unique = true, nullable = false)
	public String getE6groupTx() {
		return this.e6groupTx;
	}

	public void setE6groupTx(String e6groupTx) {
		this.e6groupTx = e6groupTx;
	}

	@Column(name = "E6UnavailableBl", nullable = false)
	public boolean isE6unavailableBl() {
		return this.e6unavailableBl;
	}

	public void setE6unavailableBl(boolean e6unavailableBl) {
		this.e6unavailableBl = e6unavailableBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "E6CreationDate", nullable = false, length = 23)
	public Date getE6creationDate() {
		return this.e6creationDate;
	}

	public void setE6creationDate(Date e6creationDate) {
		this.e6creationDate = e6creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "E6LastUpdatedDate", nullable = false, length = 23)
	public Date getE6lastUpdatedDate() {
		return this.e6lastUpdatedDate;
	}

	public void setE6lastUpdatedDate(Date e6lastUpdatedDate) {
		this.e6lastUpdatedDate = e6lastUpdatedDate;
	}

}
