package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TEcempModuleCost generated by hbm2java
 */
@Entity
@Table(name = "T_ECEmpModuleCost", uniqueConstraints = @UniqueConstraint(columnNames = { "ECEmpID", "ECModuleTypeID" }))
public class TEcempModuleCost implements java.io.Serializable {

	private int ecempModuleCostId;
	private TEmEmp TEmEmp;
	private TMtmoduleType TMtmoduleType;
	private double ecbaseCostMn;
	private double ecadditionalCostPerCustMn;
	private short eccurrencyId;
	private float ecexchangeRateFl;
	private Date eclastUpdatedDate;

	public TEcempModuleCost() {
	}

	public TEcempModuleCost(int ecempModuleCostId, TEmEmp TEmEmp, TMtmoduleType TMtmoduleType, double ecbaseCostMn,
			double ecadditionalCostPerCustMn, short eccurrencyId, float ecexchangeRateFl, Date eclastUpdatedDate) {
		this.ecempModuleCostId = ecempModuleCostId;
		this.TEmEmp = TEmEmp;
		this.TMtmoduleType = TMtmoduleType;
		this.ecbaseCostMn = ecbaseCostMn;
		this.ecadditionalCostPerCustMn = ecadditionalCostPerCustMn;
		this.eccurrencyId = eccurrencyId;
		this.ecexchangeRateFl = ecexchangeRateFl;
		this.eclastUpdatedDate = eclastUpdatedDate;
	}

	@Id

	@Column(name = "ECEmpModuleCostID", unique = true, nullable = false)
	public int getEcempModuleCostId() {
		return this.ecempModuleCostId;
	}

	public void setEcempModuleCostId(int ecempModuleCostId) {
		this.ecempModuleCostId = ecempModuleCostId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ECEmpID", nullable = false)
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ECModuleTypeID", nullable = false)
	public TMtmoduleType getTMtmoduleType() {
		return this.TMtmoduleType;
	}

	public void setTMtmoduleType(TMtmoduleType TMtmoduleType) {
		this.TMtmoduleType = TMtmoduleType;
	}

	@Column(name = "ECBaseCostMn", nullable = false, precision = 53, scale = 0)
	public double getEcbaseCostMn() {
		return this.ecbaseCostMn;
	}

	public void setEcbaseCostMn(double ecbaseCostMn) {
		this.ecbaseCostMn = ecbaseCostMn;
	}

	@Column(name = "ECAdditionalCostPerCustMn", nullable = false, precision = 53, scale = 0)
	public double getEcadditionalCostPerCustMn() {
		return this.ecadditionalCostPerCustMn;
	}

	public void setEcadditionalCostPerCustMn(double ecadditionalCostPerCustMn) {
		this.ecadditionalCostPerCustMn = ecadditionalCostPerCustMn;
	}

	@Column(name = "ECCurrencyID", nullable = false)
	public short getEccurrencyId() {
		return this.eccurrencyId;
	}

	public void setEccurrencyId(short eccurrencyId) {
		this.eccurrencyId = eccurrencyId;
	}

	@Column(name = "ECExchangeRateFl", nullable = false, precision = 24, scale = 0)
	public float getEcexchangeRateFl() {
		return this.ecexchangeRateFl;
	}

	public void setEcexchangeRateFl(float ecexchangeRateFl) {
		this.ecexchangeRateFl = ecexchangeRateFl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ECLastUpdatedDate", nullable = false, length = 23)
	public Date getEclastUpdatedDate() {
		return this.eclastUpdatedDate;
	}

	public void setEclastUpdatedDate(Date eclastUpdatedDate) {
		this.eclastUpdatedDate = eclastUpdatedDate;
	}

}
