package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TEmEmp generated by hbm2java
 */
@Entity
@Table(name = "T_EmEmp")
public class TEmEmp implements java.io.Serializable {

	private int emEmpId;
	private TCuCust TCuCust;
	private String emInitialsTxN;
	private String emInstructorNoTxN;
	private boolean emInstructorBl;
	private boolean emTechnicianBl;
	private boolean emUserBl;
	private String emPasswordTxN;
	private String emSsntxN;
	private String emPadikeyTxN;
	private float emCommissionRateFl;
	private int emForeColorIn;
	private int emBackColorIn;
	private String emNotesTxN;
	private String emUrltxN;
	private boolean emUnavailableBl;
	private float emAgentCommissionRateFl;
	private Date emPrevLastLoginDateN;
	private Date emLastLoginDateN;
	private String emTechNoTxN;
	private Integer emPreferredUiidN;
	private Set<TSoStore> TSoStores = new HashSet<TSoStore>(0);
	private Set<TEkEmpClockIn> TEkEmpClockIns = new HashSet<TEkEmpClockIn>(0);
	private Set<TTkTask> TTkTasksForTkEmpIdN = new HashSet<TTkTask>(0);
	private Set<TEtempTrip> TEtempTrips = new HashSet<TEtempTrip>(0);
	private Set<TT3ticketRule> TT3ticketRules = new HashSet<TT3ticketRule>(0);
	private Set<TTcTicket> TTcTickets = new HashSet<TTcTicket>(0);
	private Set<TPvPoinvoice> TPvPoinvoices = new HashSet<TPvPoinvoice>(0);
	private Set<TMgMessage> TMgMessagesForMgFromEmpId = new HashSet<TMgMessage>(0);
	private Set<TEsempSchedule> TEsempSchedules = new HashSet<TEsempSchedule>(0);
	private Set<TQuQuote> TQuQuotes = new HashSet<TQuQuote>(0);
	private Set<TVoVoucher> TVoVouchersForVoCommissionEmployeeId = new HashSet<TVoVoucher>(0);
	private Set<TRbrentalBooking> TRbrentalBookings = new HashSet<TRbrentalBooking>(0);
	private Set<TRkRoomBooking> TRkRoomBookings = new HashSet<TRkRoomBooking>(0);
	private Set<TEcempModuleCost> TEcempModuleCosts = new HashSet<TEcempModuleCost>(0);
	private Set<TIfinterestFollowUp> TIfinterestFollowUps = new HashSet<TIfinterestFollowUp>(0);
	private Set<TEpempPrivilege> TEpempPrivileges = new HashSet<TEpempPrivilege>(0);
	private Set<TGdGiftCard> TGdGiftCards = new HashSet<TGdGiftCard>(0);
	private Set<TIeitemCommission> TIeitemCommissions = new HashSet<TIeitemCommission>(0);
	private Set<TRrreportRun> TRrreportRuns = new HashSet<TRrreportRun>(0);
	private Set<TCtcourseType> TCtcourseTypes = new HashSet<TCtcourseType>(0);
	private Set<TCnContact> TCnContacts = new HashSet<TCnContact>(0);
	private Set<TPePodelivery> TPePodeliveries = new HashSet<TPePodelivery>(0);
	private Set<TTcTicket> TTcTickets_1 = new HashSet<TTcTicket>(0);
	private Set<TTkTask> TTkTasksForTkFromEmpIdN = new HashSet<TTkTask>(0);
	private Set<TPopo> TPopos = new HashSet<TPopo>(0);
	private Set<TCdCustOrder> TCdCustOrders = new HashSet<TCdCustOrder>(0);
	private Set<TSgServiceBookingItem> TSgServiceBookingItems = new HashSet<TSgServiceBookingItem>(0);
	private Set<TMgMessage> TMgMessagesForMgToEmpId = new HashSet<TMgMessage>(0);
	private Set<TDiDiveProfile> TDiDiveProfiles = new HashSet<TDiDiveProfile>(0);
	private Set<TSbserviceBooking> TSbserviceBookings = new HashSet<TSbserviceBooking>(0);
	private Set<TEdEmpModule> TEdEmpModules = new HashSet<TEdEmpModule>(0);
	private Set<TErempRole> TErempRoles = new HashSet<TErempRole>(0);
	private Set<TC1custCourse> TC1custCoursesForC1instructorIdN = new HashSet<TC1custCourse>(0);
	private Set<TTrTransfer> TTrTransfers = new HashSet<TTrTransfer>(0);
	private Set<TInInvoice> TInInvoices = new HashSet<TInInvoice>(0);
	private Set<TC8custInterest> TC8custInterests = new HashSet<TC8custInterest>(0);
	private Set<TP7podeliveryItemDetail> TP7podeliveryItemDetails = new HashSet<TP7podeliveryItemDetail>(0);
	private Set<TVoVoucher> TVoVouchersForVoEmpId = new HashSet<TVoVoucher>(0);
	private Set<TEeEmpCourse> TEeEmpCourses = new HashSet<TEeEmpCourse>(0);
	private Set<TGcgiftCert> TGcgiftCerts = new HashSet<TGcgiftCert>(0);
	private Set<TC1custCourse> TC1custCoursesForC1picsentByIdN = new HashSet<TC1custCourse>(0);
	private Set<TExExpense> TExExpenses = new HashSet<TExExpense>(0);

	public TEmEmp() {
	}

	public TEmEmp(TCuCust TCuCust, boolean emInstructorBl, boolean emTechnicianBl, boolean emUserBl,
			float emCommissionRateFl, int emForeColorIn, int emBackColorIn, boolean emUnavailableBl,
			float emAgentCommissionRateFl) {
		this.TCuCust = TCuCust;
		this.emInstructorBl = emInstructorBl;
		this.emTechnicianBl = emTechnicianBl;
		this.emUserBl = emUserBl;
		this.emCommissionRateFl = emCommissionRateFl;
		this.emForeColorIn = emForeColorIn;
		this.emBackColorIn = emBackColorIn;
		this.emUnavailableBl = emUnavailableBl;
		this.emAgentCommissionRateFl = emAgentCommissionRateFl;
	}

	public TEmEmp(TCuCust TCuCust, String emInitialsTxN, String emInstructorNoTxN, boolean emInstructorBl,
			boolean emTechnicianBl, boolean emUserBl, String emPasswordTxN, String emSsntxN,
			String emPadikeyTxN, float emCommissionRateFl, int emForeColorIn, int emBackColorIn,
			String emNotesTxN, String emUrltxN, boolean emUnavailableBl, float emAgentCommissionRateFl,
			Date emPrevLastLoginDateN, Date emLastLoginDateN, String emTechNoTxN, Integer emPreferredUiidN,
			Set<TSoStore> TSoStores, Set<TEkEmpClockIn> TEkEmpClockIns, Set<TTkTask> TTkTasksForTkEmpIdN,
			Set<TEtempTrip> TEtempTrips, Set<TT3ticketRule> TT3ticketRules, Set<TTcTicket> TTcTickets,
			Set<TPvPoinvoice> TPvPoinvoices, Set<TMgMessage> TMgMessagesForMgFromEmpId,
			Set<TEsempSchedule> TEsempSchedules, Set<TQuQuote> TQuQuotes,
			Set<TVoVoucher> TVoVouchersForVoCommissionEmployeeId, Set<TRbrentalBooking> TRbrentalBookings,
			Set<TRkRoomBooking> TRkRoomBookings, Set<TEcempModuleCost> TEcempModuleCosts,
			Set<TIfinterestFollowUp> TIfinterestFollowUps, Set<TEpempPrivilege> TEpempPrivileges,
			Set<TGdGiftCard> TGdGiftCards, Set<TIeitemCommission> TIeitemCommissions, Set<TRrreportRun> TRrreportRuns,
			Set<TCtcourseType> TCtcourseTypes, Set<TCnContact> TCnContacts, Set<TPePodelivery> TPePodeliveries,
			Set<TTcTicket> TTcTickets_1, Set<TTkTask> TTkTasksForTkFromEmpIdN, Set<TPopo> TPopos,
			Set<TCdCustOrder> TCdCustOrders, Set<TSgServiceBookingItem> TSgServiceBookingItems,
			Set<TMgMessage> TMgMessagesForMgToEmpId, Set<TDiDiveProfile> TDiDiveProfiles,
			Set<TSbserviceBooking> TSbserviceBookings, Set<TEdEmpModule> TEdEmpModules, Set<TErempRole> TErempRoles,
			Set<TC1custCourse> TC1custCoursesForC1instructorIdN, Set<TTrTransfer> TTrTransfers,
			Set<TInInvoice> TInInvoices, Set<TC8custInterest> TC8custInterests,
			Set<TP7podeliveryItemDetail> TP7podeliveryItemDetails, Set<TVoVoucher> TVoVouchersForVoEmpId,
			Set<TEeEmpCourse> TEeEmpCourses, Set<TGcgiftCert> TGcgiftCerts,
			Set<TC1custCourse> TC1custCoursesForC1picsentByIdN, Set<TExExpense> TExExpenses) {
		this.TCuCust = TCuCust;
		this.emInitialsTxN = emInitialsTxN;
		this.emInstructorNoTxN = emInstructorNoTxN;
		this.emInstructorBl = emInstructorBl;
		this.emTechnicianBl = emTechnicianBl;
		this.emUserBl = emUserBl;
		this.emPasswordTxN = emPasswordTxN;
		this.emSsntxN = emSsntxN;
		this.emPadikeyTxN = emPadikeyTxN;
		this.emCommissionRateFl = emCommissionRateFl;
		this.emForeColorIn = emForeColorIn;
		this.emBackColorIn = emBackColorIn;
		this.emNotesTxN = emNotesTxN;
		this.emUrltxN = emUrltxN;
		this.emUnavailableBl = emUnavailableBl;
		this.emAgentCommissionRateFl = emAgentCommissionRateFl;
		this.emPrevLastLoginDateN = emPrevLastLoginDateN;
		this.emLastLoginDateN = emLastLoginDateN;
		this.emTechNoTxN = emTechNoTxN;
		this.emPreferredUiidN = emPreferredUiidN;
		this.TSoStores = TSoStores;
		this.TEkEmpClockIns = TEkEmpClockIns;
		this.TTkTasksForTkEmpIdN = TTkTasksForTkEmpIdN;
		this.TEtempTrips = TEtempTrips;
		this.TT3ticketRules = TT3ticketRules;
		this.TTcTickets = TTcTickets;
		this.TPvPoinvoices = TPvPoinvoices;
		this.TMgMessagesForMgFromEmpId = TMgMessagesForMgFromEmpId;
		this.TEsempSchedules = TEsempSchedules;
		this.TQuQuotes = TQuQuotes;
		this.TVoVouchersForVoCommissionEmployeeId = TVoVouchersForVoCommissionEmployeeId;
		this.TRbrentalBookings = TRbrentalBookings;
		this.TRkRoomBookings = TRkRoomBookings;
		this.TEcempModuleCosts = TEcempModuleCosts;
		this.TIfinterestFollowUps = TIfinterestFollowUps;
		this.TEpempPrivileges = TEpempPrivileges;
		this.TGdGiftCards = TGdGiftCards;
		this.TIeitemCommissions = TIeitemCommissions;
		this.TRrreportRuns = TRrreportRuns;
		this.TCtcourseTypes = TCtcourseTypes;
		this.TCnContacts = TCnContacts;
		this.TPePodeliveries = TPePodeliveries;
		this.TTcTickets_1 = TTcTickets_1;
		this.TTkTasksForTkFromEmpIdN = TTkTasksForTkFromEmpIdN;
		this.TPopos = TPopos;
		this.TCdCustOrders = TCdCustOrders;
		this.TSgServiceBookingItems = TSgServiceBookingItems;
		this.TMgMessagesForMgToEmpId = TMgMessagesForMgToEmpId;
		this.TDiDiveProfiles = TDiDiveProfiles;
		this.TSbserviceBookings = TSbserviceBookings;
		this.TEdEmpModules = TEdEmpModules;
		this.TErempRoles = TErempRoles;
		this.TC1custCoursesForC1instructorIdN = TC1custCoursesForC1instructorIdN;
		this.TTrTransfers = TTrTransfers;
		this.TInInvoices = TInInvoices;
		this.TC8custInterests = TC8custInterests;
		this.TP7podeliveryItemDetails = TP7podeliveryItemDetails;
		this.TVoVouchersForVoEmpId = TVoVouchersForVoEmpId;
		this.TEeEmpCourses = TEeEmpCourses;
		this.TGcgiftCerts = TGcgiftCerts;
		this.TC1custCoursesForC1picsentByIdN = TC1custCoursesForC1picsentByIdN;
		this.TExExpenses = TExExpenses;
	}

	@GenericGenerator(name = "temEmpgenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "TCuCust"))
	@Id
	@GeneratedValue(generator = "temEmpgenerator")

	@Column(name = "EmEmpID", unique = true, nullable = false)
	public int getEmEmpId() {
		return this.emEmpId;
	}

	public void setEmEmpId(int emEmpId) {
		this.emEmpId = emEmpId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public TCuCust getTCuCust() {
		return this.TCuCust;
	}

	public void setTCuCust(TCuCust TCuCust) {
		this.TCuCust = TCuCust;
	}

	@Column(name = "EmInitialsTx_N")
	public String getEmInitialsTxN() {
		return this.emInitialsTxN;
	}

	public void setEmInitialsTxN(String emInitialsTxN) {
		this.emInitialsTxN = emInitialsTxN;
	}

	@Column(name = "EmInstructorNoTx_N")
	public String getEmInstructorNoTxN() {
		return this.emInstructorNoTxN;
	}

	public void setEmInstructorNoTxN(String emInstructorNoTxN) {
		this.emInstructorNoTxN = emInstructorNoTxN;
	}

	@Column(name = "EmInstructorBl", nullable = false)
	public boolean isEmInstructorBl() {
		return this.emInstructorBl;
	}

	public void setEmInstructorBl(boolean emInstructorBl) {
		this.emInstructorBl = emInstructorBl;
	}

	@Column(name = "EmTechnicianBl", nullable = false)
	public boolean isEmTechnicianBl() {
		return this.emTechnicianBl;
	}

	public void setEmTechnicianBl(boolean emTechnicianBl) {
		this.emTechnicianBl = emTechnicianBl;
	}

	@Column(name = "EmUserBl", nullable = false)
	public boolean isEmUserBl() {
		return this.emUserBl;
	}

	public void setEmUserBl(boolean emUserBl) {
		this.emUserBl = emUserBl;
	}

	@Column(name = "EmPasswordTx_N")
	public String getEmPasswordTxN() {
		return this.emPasswordTxN;
	}

	public void setEmPasswordTxN(String emPasswordTxN) {
		this.emPasswordTxN = emPasswordTxN;
	}

	@Column(name = "EmSSNTx_N")
	public String getEmSsntxN() {
		return this.emSsntxN;
	}

	public void setEmSsntxN(String emSsntxN) {
		this.emSsntxN = emSsntxN;
	}

	@Column(name = "EmPADIKeyTx_N")
	public String getEmPadikeyTxN() {
		return this.emPadikeyTxN;
	}

	public void setEmPadikeyTxN(String emPadikeyTxN) {
		this.emPadikeyTxN = emPadikeyTxN;
	}

	@Column(name = "EmCommissionRateFl", nullable = false, precision = 24, scale = 0)
	public float getEmCommissionRateFl() {
		return this.emCommissionRateFl;
	}

	public void setEmCommissionRateFl(float emCommissionRateFl) {
		this.emCommissionRateFl = emCommissionRateFl;
	}

	@Column(name = "EmForeColorIn", nullable = false)
	public int getEmForeColorIn() {
		return this.emForeColorIn;
	}

	public void setEmForeColorIn(int emForeColorIn) {
		this.emForeColorIn = emForeColorIn;
	}

	@Column(name = "EmBackColorIn", nullable = false)
	public int getEmBackColorIn() {
		return this.emBackColorIn;
	}

	public void setEmBackColorIn(int emBackColorIn) {
		this.emBackColorIn = emBackColorIn;
	}

	@Column(name = "EmNotesTx_N")
	public String getEmNotesTxN() {
		return this.emNotesTxN;
	}

	public void setEmNotesTxN(String emNotesTxN) {
		this.emNotesTxN = emNotesTxN;
	}

	@Column(name = "EmURLTx_N")
	public String getEmUrltxN() {
		return this.emUrltxN;
	}

	public void setEmUrltxN(String emUrltxN) {
		this.emUrltxN = emUrltxN;
	}

	@Column(name = "EmUnavailableBl", nullable = false)
	public boolean isEmUnavailableBl() {
		return this.emUnavailableBl;
	}

	public void setEmUnavailableBl(boolean emUnavailableBl) {
		this.emUnavailableBl = emUnavailableBl;
	}

	@Column(name = "EmAgentCommissionRateFl", nullable = false, precision = 24, scale = 0)
	public float getEmAgentCommissionRateFl() {
		return this.emAgentCommissionRateFl;
	}

	public void setEmAgentCommissionRateFl(float emAgentCommissionRateFl) {
		this.emAgentCommissionRateFl = emAgentCommissionRateFl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EmPrevLastLoginDate_N", length = 23)
	public Date getEmPrevLastLoginDateN() {
		return this.emPrevLastLoginDateN;
	}

	public void setEmPrevLastLoginDateN(Date emPrevLastLoginDateN) {
		this.emPrevLastLoginDateN = emPrevLastLoginDateN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EmLastLoginDate_N", length = 23)
	public Date getEmLastLoginDateN() {
		return this.emLastLoginDateN;
	}

	public void setEmLastLoginDateN(Date emLastLoginDateN) {
		this.emLastLoginDateN = emLastLoginDateN;
	}

	@Column(name = "EmTechNoTx_N")
	public String getEmTechNoTxN() {
		return this.emTechNoTxN;
	}

	public void setEmTechNoTxN(String emTechNoTxN) {
		this.emTechNoTxN = emTechNoTxN;
	}

	@Column(name = "EmPreferredUIID_N")
	public Integer getEmPreferredUiidN() {
		return this.emPreferredUiidN;
	}

	public void setEmPreferredUiidN(Integer emPreferredUiidN) {
		this.emPreferredUiidN = emPreferredUiidN;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_Z0StoreEmp", joinColumns = {
			@JoinColumn(name = "Z0EmpID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Z0StoreID", nullable = false, updatable = false) })
	public Set<TSoStore> getTSoStores() {
		return this.TSoStores;
	}

	public void setTSoStores(Set<TSoStore> TSoStores) {
		this.TSoStores = TSoStores;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TEkEmpClockIn> getTEkEmpClockIns() {
		return this.TEkEmpClockIns;
	}

	public void setTEkEmpClockIns(Set<TEkEmpClockIn> TEkEmpClockIns) {
		this.TEkEmpClockIns = TEkEmpClockIns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmpByTkEmpIdN")
	public Set<TTkTask> getTTkTasksForTkEmpIdN() {
		return this.TTkTasksForTkEmpIdN;
	}

	public void setTTkTasksForTkEmpIdN(Set<TTkTask> TTkTasksForTkEmpIdN) {
		this.TTkTasksForTkEmpIdN = TTkTasksForTkEmpIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TEtempTrip> getTEtempTrips() {
		return this.TEtempTrips;
	}

	public void setTEtempTrips(Set<TEtempTrip> TEtempTrips) {
		this.TEtempTrips = TEtempTrips;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TT3ticketRule> getTT3ticketRules() {
		return this.TT3ticketRules;
	}

	public void setTT3ticketRules(Set<TT3ticketRule> TT3ticketRules) {
		this.TT3ticketRules = TT3ticketRules;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_T4TicketEmp", joinColumns = {
			@JoinColumn(name = "T4EmpID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "T4TicketID", nullable = false, updatable = false) })
	public Set<TTcTicket> getTTcTickets() {
		return this.TTcTickets;
	}

	public void setTTcTickets(Set<TTcTicket> TTcTickets) {
		this.TTcTickets = TTcTickets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TPvPoinvoice> getTPvPoinvoices() {
		return this.TPvPoinvoices;
	}

	public void setTPvPoinvoices(Set<TPvPoinvoice> TPvPoinvoices) {
		this.TPvPoinvoices = TPvPoinvoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmpByMgFromEmpId")
	public Set<TMgMessage> getTMgMessagesForMgFromEmpId() {
		return this.TMgMessagesForMgFromEmpId;
	}

	public void setTMgMessagesForMgFromEmpId(Set<TMgMessage> TMgMessagesForMgFromEmpId) {
		this.TMgMessagesForMgFromEmpId = TMgMessagesForMgFromEmpId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TEsempSchedule> getTEsempSchedules() {
		return this.TEsempSchedules;
	}

	public void setTEsempSchedules(Set<TEsempSchedule> TEsempSchedules) {
		this.TEsempSchedules = TEsempSchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TQuQuote> getTQuQuotes() {
		return this.TQuQuotes;
	}

	public void setTQuQuotes(Set<TQuQuote> TQuQuotes) {
		this.TQuQuotes = TQuQuotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmpByVoCommissionEmployeeId")
	public Set<TVoVoucher> getTVoVouchersForVoCommissionEmployeeId() {
		return this.TVoVouchersForVoCommissionEmployeeId;
	}

	public void setTVoVouchersForVoCommissionEmployeeId(Set<TVoVoucher> TVoVouchersForVoCommissionEmployeeId) {
		this.TVoVouchersForVoCommissionEmployeeId = TVoVouchersForVoCommissionEmployeeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TRbrentalBooking> getTRbrentalBookings() {
		return this.TRbrentalBookings;
	}

	public void setTRbrentalBookings(Set<TRbrentalBooking> TRbrentalBookings) {
		this.TRbrentalBookings = TRbrentalBookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TRkRoomBooking> getTRkRoomBookings() {
		return this.TRkRoomBookings;
	}

	public void setTRkRoomBookings(Set<TRkRoomBooking> TRkRoomBookings) {
		this.TRkRoomBookings = TRkRoomBookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TEcempModuleCost> getTEcempModuleCosts() {
		return this.TEcempModuleCosts;
	}

	public void setTEcempModuleCosts(Set<TEcempModuleCost> TEcempModuleCosts) {
		this.TEcempModuleCosts = TEcempModuleCosts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TIfinterestFollowUp> getTIfinterestFollowUps() {
		return this.TIfinterestFollowUps;
	}

	public void setTIfinterestFollowUps(Set<TIfinterestFollowUp> TIfinterestFollowUps) {
		this.TIfinterestFollowUps = TIfinterestFollowUps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TEpempPrivilege> getTEpempPrivileges() {
		return this.TEpempPrivileges;
	}

	public void setTEpempPrivileges(Set<TEpempPrivilege> TEpempPrivileges) {
		this.TEpempPrivileges = TEpempPrivileges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TGdGiftCard> getTGdGiftCards() {
		return this.TGdGiftCards;
	}

	public void setTGdGiftCards(Set<TGdGiftCard> TGdGiftCards) {
		this.TGdGiftCards = TGdGiftCards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TIeitemCommission> getTIeitemCommissions() {
		return this.TIeitemCommissions;
	}

	public void setTIeitemCommissions(Set<TIeitemCommission> TIeitemCommissions) {
		this.TIeitemCommissions = TIeitemCommissions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TRrreportRun> getTRrreportRuns() {
		return this.TRrreportRuns;
	}

	public void setTRrreportRuns(Set<TRrreportRun> TRrreportRuns) {
		this.TRrreportRuns = TRrreportRuns;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_E1EmpCourseType", joinColumns = {
			@JoinColumn(name = "E1EmpID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "E1CourseTypeID", nullable = false, updatable = false) })
	public Set<TCtcourseType> getTCtcourseTypes() {
		return this.TCtcourseTypes;
	}

	public void setTCtcourseTypes(Set<TCtcourseType> TCtcourseTypes) {
		this.TCtcourseTypes = TCtcourseTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TCnContact> getTCnContacts() {
		return this.TCnContacts;
	}

	public void setTCnContacts(Set<TCnContact> TCnContacts) {
		this.TCnContacts = TCnContacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TPePodelivery> getTPePodeliveries() {
		return this.TPePodeliveries;
	}

	public void setTPePodeliveries(Set<TPePodelivery> TPePodeliveries) {
		this.TPePodeliveries = TPePodeliveries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TTcTicket> getTTcTickets_1() {
		return this.TTcTickets_1;
	}

	public void setTTcTickets_1(Set<TTcTicket> TTcTickets_1) {
		this.TTcTickets_1 = TTcTickets_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmpByTkFromEmpIdN")
	public Set<TTkTask> getTTkTasksForTkFromEmpIdN() {
		return this.TTkTasksForTkFromEmpIdN;
	}

	public void setTTkTasksForTkFromEmpIdN(Set<TTkTask> TTkTasksForTkFromEmpIdN) {
		this.TTkTasksForTkFromEmpIdN = TTkTasksForTkFromEmpIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TPopo> getTPopos() {
		return this.TPopos;
	}

	public void setTPopos(Set<TPopo> TPopos) {
		this.TPopos = TPopos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TCdCustOrder> getTCdCustOrders() {
		return this.TCdCustOrders;
	}

	public void setTCdCustOrders(Set<TCdCustOrder> TCdCustOrders) {
		this.TCdCustOrders = TCdCustOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TSgServiceBookingItem> getTSgServiceBookingItems() {
		return this.TSgServiceBookingItems;
	}

	public void setTSgServiceBookingItems(Set<TSgServiceBookingItem> TSgServiceBookingItems) {
		this.TSgServiceBookingItems = TSgServiceBookingItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmpByMgToEmpId")
	public Set<TMgMessage> getTMgMessagesForMgToEmpId() {
		return this.TMgMessagesForMgToEmpId;
	}

	public void setTMgMessagesForMgToEmpId(Set<TMgMessage> TMgMessagesForMgToEmpId) {
		this.TMgMessagesForMgToEmpId = TMgMessagesForMgToEmpId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TDiDiveProfile> getTDiDiveProfiles() {
		return this.TDiDiveProfiles;
	}

	public void setTDiDiveProfiles(Set<TDiDiveProfile> TDiDiveProfiles) {
		this.TDiDiveProfiles = TDiDiveProfiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TSbserviceBooking> getTSbserviceBookings() {
		return this.TSbserviceBookings;
	}

	public void setTSbserviceBookings(Set<TSbserviceBooking> TSbserviceBookings) {
		this.TSbserviceBookings = TSbserviceBookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TEdEmpModule> getTEdEmpModules() {
		return this.TEdEmpModules;
	}

	public void setTEdEmpModules(Set<TEdEmpModule> TEdEmpModules) {
		this.TEdEmpModules = TEdEmpModules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TErempRole> getTErempRoles() {
		return this.TErempRoles;
	}

	public void setTErempRoles(Set<TErempRole> TErempRoles) {
		this.TErempRoles = TErempRoles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmpByC1instructorIdN")
	public Set<TC1custCourse> getTC1custCoursesForC1instructorIdN() {
		return this.TC1custCoursesForC1instructorIdN;
	}

	public void setTC1custCoursesForC1instructorIdN(Set<TC1custCourse> TC1custCoursesForC1instructorIdN) {
		this.TC1custCoursesForC1instructorIdN = TC1custCoursesForC1instructorIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TTrTransfer> getTTrTransfers() {
		return this.TTrTransfers;
	}

	public void setTTrTransfers(Set<TTrTransfer> TTrTransfers) {
		this.TTrTransfers = TTrTransfers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TInInvoice> getTInInvoices() {
		return this.TInInvoices;
	}

	public void setTInInvoices(Set<TInInvoice> TInInvoices) {
		this.TInInvoices = TInInvoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TC8custInterest> getTC8custInterests() {
		return this.TC8custInterests;
	}

	public void setTC8custInterests(Set<TC8custInterest> TC8custInterests) {
		this.TC8custInterests = TC8custInterests;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TP7podeliveryItemDetail> getTP7podeliveryItemDetails() {
		return this.TP7podeliveryItemDetails;
	}

	public void setTP7podeliveryItemDetails(Set<TP7podeliveryItemDetail> TP7podeliveryItemDetails) {
		this.TP7podeliveryItemDetails = TP7podeliveryItemDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmpByVoEmpId")
	public Set<TVoVoucher> getTVoVouchersForVoEmpId() {
		return this.TVoVouchersForVoEmpId;
	}

	public void setTVoVouchersForVoEmpId(Set<TVoVoucher> TVoVouchersForVoEmpId) {
		this.TVoVouchersForVoEmpId = TVoVouchersForVoEmpId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TEeEmpCourse> getTEeEmpCourses() {
		return this.TEeEmpCourses;
	}

	public void setTEeEmpCourses(Set<TEeEmpCourse> TEeEmpCourses) {
		this.TEeEmpCourses = TEeEmpCourses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TGcgiftCert> getTGcgiftCerts() {
		return this.TGcgiftCerts;
	}

	public void setTGcgiftCerts(Set<TGcgiftCert> TGcgiftCerts) {
		this.TGcgiftCerts = TGcgiftCerts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmpByC1picsentByIdN")
	public Set<TC1custCourse> getTC1custCoursesForC1picsentByIdN() {
		return this.TC1custCoursesForC1picsentByIdN;
	}

	public void setTC1custCoursesForC1picsentByIdN(Set<TC1custCourse> TC1custCoursesForC1picsentByIdN) {
		this.TC1custCoursesForC1picsentByIdN = TC1custCoursesForC1picsentByIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEmEmp")
	public Set<TExExpense> getTExExpenses() {
		return this.TExExpenses;
	}

	public void setTExExpenses(Set<TExExpense> TExExpenses) {
		this.TExExpenses = TExExpenses;
	}

}
