package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TErempRole generated by hbm2java
 */
@Entity
@Table(name = "T_EREmpRole")
public class TErempRole implements java.io.Serializable {

	private TErempRoleId id;
	private TTpTrip TTpTrip;
	private TChCustType TChCustType;
	private TEmEmp TEmEmp;

	public TErempRole() {
	}

	public TErempRole(TErempRoleId id, TTpTrip TTpTrip, TChCustType TChCustType, TEmEmp TEmEmp) {
		this.id = id;
		this.TTpTrip = TTpTrip;
		this.TChCustType = TChCustType;
		this.TEmEmp = TEmEmp;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ertripId", column = @Column(name = "ERTripID", nullable = false)),
			@AttributeOverride(name = "erempId", column = @Column(name = "EREmpID", nullable = false)),
			@AttributeOverride(name = "ercustTypeId", column = @Column(name = "ERCustTypeID", nullable = false)) })
	public TErempRoleId getId() {
		return this.id;
	}

	public void setId(TErempRoleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ERTripID", nullable = false, insertable = false, updatable = false)
	public TTpTrip getTTpTrip() {
		return this.TTpTrip;
	}

	public void setTTpTrip(TTpTrip TTpTrip) {
		this.TTpTrip = TTpTrip;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ERCustTypeID", nullable = false, insertable = false, updatable = false)
	public TChCustType getTChCustType() {
		return this.TChCustType;
	}

	public void setTChCustType(TChCustType TChCustType) {
		this.TChCustType = TChCustType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EREmpID", nullable = false, insertable = false, updatable = false)
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

}
