package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TEsempSchedule generated by hbm2java
 */
@Entity
@Table(name = "T_ESEmpSchedule")
public class TEsempSchedule implements java.io.Serializable {

	private int esempScheduleId;
	private TEmEmp TEmEmp;
	private TLcLocation TLcLocation;
	private Date esstartDate;
	private Date esendDate;
	private String esnotesTxN;
	private Date escreationDate;
	private Date eslastUpdatedDate;

	public TEsempSchedule() {
	}

	public TEsempSchedule(int esempScheduleId, TEmEmp TEmEmp, Date esstartDate, Date esendDate, Date escreationDate,
			Date eslastUpdatedDate) {
		this.esempScheduleId = esempScheduleId;
		this.TEmEmp = TEmEmp;
		this.esstartDate = esstartDate;
		this.esendDate = esendDate;
		this.escreationDate = escreationDate;
		this.eslastUpdatedDate = eslastUpdatedDate;
	}

	public TEsempSchedule(int esempScheduleId, TEmEmp TEmEmp, TLcLocation TLcLocation, Date esstartDate, Date esendDate,
			String esnotesTxN, Date escreationDate, Date eslastUpdatedDate) {
		this.esempScheduleId = esempScheduleId;
		this.TEmEmp = TEmEmp;
		this.TLcLocation = TLcLocation;
		this.esstartDate = esstartDate;
		this.esendDate = esendDate;
		this.esnotesTxN = esnotesTxN;
		this.escreationDate = escreationDate;
		this.eslastUpdatedDate = eslastUpdatedDate;
	}

	@Id

	@Column(name = "ESEmpScheduleID", unique = true, nullable = false)
	public int getEsempScheduleId() {
		return this.esempScheduleId;
	}

	public void setEsempScheduleId(int esempScheduleId) {
		this.esempScheduleId = esempScheduleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESEmpID", nullable = false)
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESLocationID_N")
	public TLcLocation getTLcLocation() {
		return this.TLcLocation;
	}

	public void setTLcLocation(TLcLocation TLcLocation) {
		this.TLcLocation = TLcLocation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ESStartDate", nullable = false, length = 23)
	public Date getEsstartDate() {
		return this.esstartDate;
	}

	public void setEsstartDate(Date esstartDate) {
		this.esstartDate = esstartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ESEndDate", nullable = false, length = 23)
	public Date getEsendDate() {
		return this.esendDate;
	}

	public void setEsendDate(Date esendDate) {
		this.esendDate = esendDate;
	}

	@Column(name = "ESNotesTx_N")
	public String getEsnotesTxN() {
		return this.esnotesTxN;
	}

	public void setEsnotesTxN(String esnotesTxN) {
		this.esnotesTxN = esnotesTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ESCreationDate", nullable = false, length = 23)
	public Date getEscreationDate() {
		return this.escreationDate;
	}

	public void setEscreationDate(Date escreationDate) {
		this.escreationDate = escreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ESLastUpdatedDate", nullable = false, length = 23)
	public Date getEslastUpdatedDate() {
		return this.eslastUpdatedDate;
	}

	public void setEslastUpdatedDate(Date eslastUpdatedDate) {
		this.eslastUpdatedDate = eslastUpdatedDate;
	}

}
