package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TEtempTrip generated by hbm2java
 */
@Entity
@Table(name = "T_ETEmpTrip", uniqueConstraints = @UniqueConstraint(columnNames = { "ETTripID", "ETEmpID" }))
public class TEtempTrip implements java.io.Serializable {

	private int etempTripId;
	private TTpTrip TTpTrip;
	private TEmEmp TEmEmp;
	private TTttaskType TTttaskType;
	private String etspecialArrangementsTxN;
	private Date etlastUpdatedDate;

	public TEtempTrip() {
	}

	public TEtempTrip(int etempTripId, TTpTrip TTpTrip, TEmEmp TEmEmp, Date etlastUpdatedDate) {
		this.etempTripId = etempTripId;
		this.TTpTrip = TTpTrip;
		this.TEmEmp = TEmEmp;
		this.etlastUpdatedDate = etlastUpdatedDate;
	}

	public TEtempTrip(int etempTripId, TTpTrip TTpTrip, TEmEmp TEmEmp, TTttaskType TTttaskType,
			String etspecialArrangementsTxN, Date etlastUpdatedDate) {
		this.etempTripId = etempTripId;
		this.TTpTrip = TTpTrip;
		this.TEmEmp = TEmEmp;
		this.TTttaskType = TTttaskType;
		this.etspecialArrangementsTxN = etspecialArrangementsTxN;
		this.etlastUpdatedDate = etlastUpdatedDate;
	}

	@Id

	@Column(name = "ETEmpTripID", unique = true, nullable = false)
	public int getEtempTripId() {
		return this.etempTripId;
	}

	public void setEtempTripId(int etempTripId) {
		this.etempTripId = etempTripId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ETTripID", nullable = false)
	public TTpTrip getTTpTrip() {
		return this.TTpTrip;
	}

	public void setTTpTrip(TTpTrip TTpTrip) {
		this.TTpTrip = TTpTrip;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ETEmpID", nullable = false)
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ETRoleID_N")
	public TTttaskType getTTttaskType() {
		return this.TTttaskType;
	}

	public void setTTttaskType(TTttaskType TTttaskType) {
		this.TTttaskType = TTttaskType;
	}

	@Column(name = "ETSpecialArrangementsTx_N")
	public String getEtspecialArrangementsTxN() {
		return this.etspecialArrangementsTxN;
	}

	public void setEtspecialArrangementsTxN(String etspecialArrangementsTxN) {
		this.etspecialArrangementsTxN = etspecialArrangementsTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ETLastUpdatedDate", nullable = false, length = 23)
	public Date getEtlastUpdatedDate() {
		return this.etlastUpdatedDate;
	}

	public void setEtlastUpdatedDate(Date etlastUpdatedDate) {
		this.etlastUpdatedDate = etlastUpdatedDate;
	}

}
