package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TEuEquipmentRentalPrice generated by hbm2java
 */
@Entity
@Table(name = "T_EuEquipmentRentalPrice", uniqueConstraints = @UniqueConstraint(columnNames = { "EuEquipmentID",
		"EuDaysIn" }))
public class TEuEquipmentRentalPrice implements java.io.Serializable {

	private int euEquipRentalPriceId;
	private TEqEquipment TEqEquipment;
	private short euDaysIn;
	private double euPriceMn;
	private double euPenaltyPriceMn;

	public TEuEquipmentRentalPrice() {
	}

	public TEuEquipmentRentalPrice(int euEquipRentalPriceId, TEqEquipment TEqEquipment, short euDaysIn,
			double euPriceMn, double euPenaltyPriceMn) {
		this.euEquipRentalPriceId = euEquipRentalPriceId;
		this.TEqEquipment = TEqEquipment;
		this.euDaysIn = euDaysIn;
		this.euPriceMn = euPriceMn;
		this.euPenaltyPriceMn = euPenaltyPriceMn;
	}

	@Id

	@Column(name = "EuEquipRentalPriceID", unique = true, nullable = false)
	public int getEuEquipRentalPriceId() {
		return this.euEquipRentalPriceId;
	}

	public void setEuEquipRentalPriceId(int euEquipRentalPriceId) {
		this.euEquipRentalPriceId = euEquipRentalPriceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EuEquipmentID", nullable = false)
	public TEqEquipment getTEqEquipment() {
		return this.TEqEquipment;
	}

	public void setTEqEquipment(TEqEquipment TEqEquipment) {
		this.TEqEquipment = TEqEquipment;
	}

	@Column(name = "EuDaysIn", nullable = false)
	public short getEuDaysIn() {
		return this.euDaysIn;
	}

	public void setEuDaysIn(short euDaysIn) {
		this.euDaysIn = euDaysIn;
	}

	@Column(name = "EuPriceMn", nullable = false, precision = 53, scale = 0)
	public double getEuPriceMn() {
		return this.euPriceMn;
	}

	public void setEuPriceMn(double euPriceMn) {
		this.euPriceMn = euPriceMn;
	}

	@Column(name = "EuPenaltyPriceMn", nullable = false, precision = 53, scale = 0)
	public double getEuPenaltyPriceMn() {
		return this.euPenaltyPriceMn;
	}

	public void setEuPenaltyPriceMn(double euPenaltyPriceMn) {
		this.euPenaltyPriceMn = euPenaltyPriceMn;
	}

}
