package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TExExpense generated by hbm2java
 */
@Entity
@Table(name = "T_ExExpense")
public class TExExpense implements java.io.Serializable {

	private int exExpenseId;
	private TSistockItem TSistockItem;
	private TInInvoice TInInvoice;
	private TEmEmp TEmEmp;
	private int exForeignDataId;
	private double exAmountMn;
	private double exTaxMn;
	private String exTaxBandIdsTx;
	private String exTaxRatesTx;
	private Date exExpenseDate;
	private Date exLastUpdatedDate;
	private Date exCreationDate;
	private String exNotesTxN;
	private Integer exEmpEventIdN;
	private short exForeignDataTypeId;
	private Integer exCommissionClosingIdN;

	public TExExpense() {
	}

	public TExExpense(int exExpenseId, TSistockItem TSistockItem, int exForeignDataId, double exAmountMn,
			double exTaxMn, String exTaxBandIdsTx, String exTaxRatesTx, Date exExpenseDate,
			Date exLastUpdatedDate, Date exCreationDate, short exForeignDataTypeId) {
		this.exExpenseId = exExpenseId;
		this.TSistockItem = TSistockItem;
		this.exForeignDataId = exForeignDataId;
		this.exAmountMn = exAmountMn;
		this.exTaxMn = exTaxMn;
		this.exTaxBandIdsTx = exTaxBandIdsTx;
		this.exTaxRatesTx = exTaxRatesTx;
		this.exExpenseDate = exExpenseDate;
		this.exLastUpdatedDate = exLastUpdatedDate;
		this.exCreationDate = exCreationDate;
		this.exForeignDataTypeId = exForeignDataTypeId;
	}

	public TExExpense(int exExpenseId, TSistockItem TSistockItem, TInInvoice TInInvoice, TEmEmp TEmEmp,
			int exForeignDataId, double exAmountMn, double exTaxMn, String exTaxBandIdsTx,
			String exTaxRatesTx, Date exExpenseDate, Date exLastUpdatedDate, Date exCreationDate,
			String exNotesTxN, Integer exEmpEventIdN, short exForeignDataTypeId, Integer exCommissionClosingIdN) {
		this.exExpenseId = exExpenseId;
		this.TSistockItem = TSistockItem;
		this.TInInvoice = TInInvoice;
		this.TEmEmp = TEmEmp;
		this.exForeignDataId = exForeignDataId;
		this.exAmountMn = exAmountMn;
		this.exTaxMn = exTaxMn;
		this.exTaxBandIdsTx = exTaxBandIdsTx;
		this.exTaxRatesTx = exTaxRatesTx;
		this.exExpenseDate = exExpenseDate;
		this.exLastUpdatedDate = exLastUpdatedDate;
		this.exCreationDate = exCreationDate;
		this.exNotesTxN = exNotesTxN;
		this.exEmpEventIdN = exEmpEventIdN;
		this.exForeignDataTypeId = exForeignDataTypeId;
		this.exCommissionClosingIdN = exCommissionClosingIdN;
	}

	@Id

	@Column(name = "ExExpenseID", unique = true, nullable = false)
	public int getExExpenseId() {
		return this.exExpenseId;
	}

	public void setExExpenseId(int exExpenseId) {
		this.exExpenseId = exExpenseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ExStockItemID", nullable = false)
	public TSistockItem getTSistockItem() {
		return this.TSistockItem;
	}

	public void setTSistockItem(TSistockItem TSistockItem) {
		this.TSistockItem = TSistockItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ExInvoiceID_N")
	public TInInvoice getTInInvoice() {
		return this.TInInvoice;
	}

	public void setTInInvoice(TInInvoice TInInvoice) {
		this.TInInvoice = TInInvoice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ExEmpID_N")
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

	@Column(name = "ExForeignDataID", nullable = false)
	public int getExForeignDataId() {
		return this.exForeignDataId;
	}

	public void setExForeignDataId(int exForeignDataId) {
		this.exForeignDataId = exForeignDataId;
	}

	@Column(name = "ExAmountMn", nullable = false, precision = 53, scale = 0)
	public double getExAmountMn() {
		return this.exAmountMn;
	}

	public void setExAmountMn(double exAmountMn) {
		this.exAmountMn = exAmountMn;
	}

	@Column(name = "ExTaxMn", nullable = false, precision = 53, scale = 0)
	public double getExTaxMn() {
		return this.exTaxMn;
	}

	public void setExTaxMn(double exTaxMn) {
		this.exTaxMn = exTaxMn;
	}

	@Column(name = "ExTaxBandIDsTx", nullable = false)
	public String getExTaxBandIdsTx() {
		return this.exTaxBandIdsTx;
	}

	public void setExTaxBandIdsTx(String exTaxBandIdsTx) {
		this.exTaxBandIdsTx = exTaxBandIdsTx;
	}

	@Column(name = "ExTaxRatesTx", nullable = false)
	public String getExTaxRatesTx() {
		return this.exTaxRatesTx;
	}

	public void setExTaxRatesTx(String exTaxRatesTx) {
		this.exTaxRatesTx = exTaxRatesTx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ExExpenseDate", nullable = false, length = 23)
	public Date getExExpenseDate() {
		return this.exExpenseDate;
	}

	public void setExExpenseDate(Date exExpenseDate) {
		this.exExpenseDate = exExpenseDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ExLastUpdatedDate", nullable = false, length = 23)
	public Date getExLastUpdatedDate() {
		return this.exLastUpdatedDate;
	}

	public void setExLastUpdatedDate(Date exLastUpdatedDate) {
		this.exLastUpdatedDate = exLastUpdatedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ExCreationDate", nullable = false, length = 23)
	public Date getExCreationDate() {
		return this.exCreationDate;
	}

	public void setExCreationDate(Date exCreationDate) {
		this.exCreationDate = exCreationDate;
	}

	@Column(name = "ExNotesTx_N")
	public String getExNotesTxN() {
		return this.exNotesTxN;
	}

	public void setExNotesTxN(String exNotesTxN) {
		this.exNotesTxN = exNotesTxN;
	}

	@Column(name = "ExEmpEventID_N")
	public Integer getExEmpEventIdN() {
		return this.exEmpEventIdN;
	}

	public void setExEmpEventIdN(Integer exEmpEventIdN) {
		this.exEmpEventIdN = exEmpEventIdN;
	}

	@Column(name = "ExForeignDataTypeID", nullable = false)
	public short getExForeignDataTypeId() {
		return this.exForeignDataTypeId;
	}

	public void setExForeignDataTypeId(short exForeignDataTypeId) {
		this.exForeignDataTypeId = exForeignDataTypeId;
	}

	@Column(name = "ExCommissionClosingID_N")
	public Integer getExCommissionClosingIdN() {
		return this.exCommissionClosingIdN;
	}

	public void setExCommissionClosingIdN(Integer exCommissionClosingIdN) {
		this.exCommissionClosingIdN = exCommissionClosingIdN;
	}

}
