package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TFoformOpt generated by hbm2java
 */
@Entity
@Table(name = "T_FOFormOpt", uniqueConstraints = @UniqueConstraint(columnNames = { "FODataTypeID", "FOPCID",
		"FOFormTypeID" }))
public class TFoformOpt implements java.io.Serializable {

	private int foformOptId;
	private TDtdataType TDtdataType;
	private short fopcid;
	private short foformTypeId;
	private int foleftIn;
	private int fotopIn;
	private int fowidthIn;
	private int foheightIn;
	private boolean fomaximizedBl;
	private short fonewActionIn;
	private short fosaveActionNewIn;
	private short fosaveActionExistingIn;
	private short fodeleteActionIn;
	private short fomoveActionIn;
	private short foprintActionNewIn;
	private short foprintActionExistingIn;
	private int fodefaultSearchViewId;
	private int fotoolbarLocationIn;
	private int fotoolbarHeightIn;
	private int fotoolbarWidthIn;

	public TFoformOpt() {
	}

	public TFoformOpt(int foformOptId, TDtdataType TDtdataType, short fopcid, short foformTypeId, int foleftIn,
			int fotopIn, int fowidthIn, int foheightIn, boolean fomaximizedBl, short fonewActionIn,
			short fosaveActionNewIn, short fosaveActionExistingIn, short fodeleteActionIn, short fomoveActionIn,
			short foprintActionNewIn, short foprintActionExistingIn, int fodefaultSearchViewId, int fotoolbarLocationIn,
			int fotoolbarHeightIn, int fotoolbarWidthIn) {
		this.foformOptId = foformOptId;
		this.TDtdataType = TDtdataType;
		this.fopcid = fopcid;
		this.foformTypeId = foformTypeId;
		this.foleftIn = foleftIn;
		this.fotopIn = fotopIn;
		this.fowidthIn = fowidthIn;
		this.foheightIn = foheightIn;
		this.fomaximizedBl = fomaximizedBl;
		this.fonewActionIn = fonewActionIn;
		this.fosaveActionNewIn = fosaveActionNewIn;
		this.fosaveActionExistingIn = fosaveActionExistingIn;
		this.fodeleteActionIn = fodeleteActionIn;
		this.fomoveActionIn = fomoveActionIn;
		this.foprintActionNewIn = foprintActionNewIn;
		this.foprintActionExistingIn = foprintActionExistingIn;
		this.fodefaultSearchViewId = fodefaultSearchViewId;
		this.fotoolbarLocationIn = fotoolbarLocationIn;
		this.fotoolbarHeightIn = fotoolbarHeightIn;
		this.fotoolbarWidthIn = fotoolbarWidthIn;
	}

	@Id

	@Column(name = "FOFormOptID", unique = true, nullable = false)
	public int getFoformOptId() {
		return this.foformOptId;
	}

	public void setFoformOptId(int foformOptId) {
		this.foformOptId = foformOptId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FODataTypeID", nullable = false)
	public TDtdataType getTDtdataType() {
		return this.TDtdataType;
	}

	public void setTDtdataType(TDtdataType TDtdataType) {
		this.TDtdataType = TDtdataType;
	}

	@Column(name = "FOPCID", nullable = false)
	public short getFopcid() {
		return this.fopcid;
	}

	public void setFopcid(short fopcid) {
		this.fopcid = fopcid;
	}

	@Column(name = "FOFormTypeID", nullable = false)
	public short getFoformTypeId() {
		return this.foformTypeId;
	}

	public void setFoformTypeId(short foformTypeId) {
		this.foformTypeId = foformTypeId;
	}

	@Column(name = "FOLeftIn", nullable = false)
	public int getFoleftIn() {
		return this.foleftIn;
	}

	public void setFoleftIn(int foleftIn) {
		this.foleftIn = foleftIn;
	}

	@Column(name = "FOTopIn", nullable = false)
	public int getFotopIn() {
		return this.fotopIn;
	}

	public void setFotopIn(int fotopIn) {
		this.fotopIn = fotopIn;
	}

	@Column(name = "FOWidthIn", nullable = false)
	public int getFowidthIn() {
		return this.fowidthIn;
	}

	public void setFowidthIn(int fowidthIn) {
		this.fowidthIn = fowidthIn;
	}

	@Column(name = "FOHeightIn", nullable = false)
	public int getFoheightIn() {
		return this.foheightIn;
	}

	public void setFoheightIn(int foheightIn) {
		this.foheightIn = foheightIn;
	}

	@Column(name = "FOMaximizedBl", nullable = false)
	public boolean isFomaximizedBl() {
		return this.fomaximizedBl;
	}

	public void setFomaximizedBl(boolean fomaximizedBl) {
		this.fomaximizedBl = fomaximizedBl;
	}

	@Column(name = "FONewActionIn", nullable = false)
	public short getFonewActionIn() {
		return this.fonewActionIn;
	}

	public void setFonewActionIn(short fonewActionIn) {
		this.fonewActionIn = fonewActionIn;
	}

	@Column(name = "FOSaveActionNewIn", nullable = false)
	public short getFosaveActionNewIn() {
		return this.fosaveActionNewIn;
	}

	public void setFosaveActionNewIn(short fosaveActionNewIn) {
		this.fosaveActionNewIn = fosaveActionNewIn;
	}

	@Column(name = "FOSaveActionExistingIn", nullable = false)
	public short getFosaveActionExistingIn() {
		return this.fosaveActionExistingIn;
	}

	public void setFosaveActionExistingIn(short fosaveActionExistingIn) {
		this.fosaveActionExistingIn = fosaveActionExistingIn;
	}

	@Column(name = "FODeleteActionIn", nullable = false)
	public short getFodeleteActionIn() {
		return this.fodeleteActionIn;
	}

	public void setFodeleteActionIn(short fodeleteActionIn) {
		this.fodeleteActionIn = fodeleteActionIn;
	}

	@Column(name = "FOMoveActionIn", nullable = false)
	public short getFomoveActionIn() {
		return this.fomoveActionIn;
	}

	public void setFomoveActionIn(short fomoveActionIn) {
		this.fomoveActionIn = fomoveActionIn;
	}

	@Column(name = "FOPrintActionNewIn", nullable = false)
	public short getFoprintActionNewIn() {
		return this.foprintActionNewIn;
	}

	public void setFoprintActionNewIn(short foprintActionNewIn) {
		this.foprintActionNewIn = foprintActionNewIn;
	}

	@Column(name = "FOPrintActionExistingIn", nullable = false)
	public short getFoprintActionExistingIn() {
		return this.foprintActionExistingIn;
	}

	public void setFoprintActionExistingIn(short foprintActionExistingIn) {
		this.foprintActionExistingIn = foprintActionExistingIn;
	}

	@Column(name = "FODefaultSearchViewID", nullable = false)
	public int getFodefaultSearchViewId() {
		return this.fodefaultSearchViewId;
	}

	public void setFodefaultSearchViewId(int fodefaultSearchViewId) {
		this.fodefaultSearchViewId = fodefaultSearchViewId;
	}

	@Column(name = "FOToolbarLocationIn", nullable = false)
	public int getFotoolbarLocationIn() {
		return this.fotoolbarLocationIn;
	}

	public void setFotoolbarLocationIn(int fotoolbarLocationIn) {
		this.fotoolbarLocationIn = fotoolbarLocationIn;
	}

	@Column(name = "FOToolbarHeightIn", nullable = false)
	public int getFotoolbarHeightIn() {
		return this.fotoolbarHeightIn;
	}

	public void setFotoolbarHeightIn(int fotoolbarHeightIn) {
		this.fotoolbarHeightIn = fotoolbarHeightIn;
	}

	@Column(name = "FOToolbarWidthIn", nullable = false)
	public int getFotoolbarWidthIn() {
		return this.fotoolbarWidthIn;
	}

	public void setFotoolbarWidthIn(int fotoolbarWidthIn) {
		this.fotoolbarWidthIn = fotoolbarWidthIn;
	}

}
