package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TFpformProperty generated by hbm2java
 */
@Entity
@Table(name = "T_FPFormProperty", uniqueConstraints = @UniqueConstraint(columnNames = { "FPDataTypeID", "FPFormTypeID",
		"FPPropertyTx", "FPFieldNameTx", "FPPCID", "FPStoreID", "FPUIConfigID" }))
public class TFpformProperty implements java.io.Serializable {

	private TFpformPropertyId id;
	private TDtdataType TDtdataType;

	public TFpformProperty() {
	}

	public TFpformProperty(TFpformPropertyId id, TDtdataType TDtdataType) {
		this.id = id;
		this.TDtdataType = TDtdataType;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fpformPropertyId", column = @Column(name = "FPFormPropertyID", nullable = false)),
			@AttributeOverride(name = "fpdataTypeId", column = @Column(name = "FPDataTypeID", nullable = false)),
			@AttributeOverride(name = "fpformTypeId", column = @Column(name = "FPFormTypeID", nullable = false)),
			@AttributeOverride(name = "fppropertyTx", column = @Column(name = "FPPropertyTx", nullable = false)),
			@AttributeOverride(name = "fpfieldNameTx", column = @Column(name = "FPFieldNameTx", nullable = false)),
			@AttributeOverride(name = "fppropertyValueTx", column = @Column(name = "FPPropertyValueTx", nullable = false)),
			@AttributeOverride(name = "fppropertyTypeTx", column = @Column(name = "FPPropertyTypeTx", nullable = false)),
			@AttributeOverride(name = "fpstoreId", column = @Column(name = "FPStoreID", nullable = false)),
			@AttributeOverride(name = "fppcid", column = @Column(name = "FPPCID", nullable = false)),
			@AttributeOverride(name = "fprequiredBl", column = @Column(name = "FPRequiredBl", nullable = false)),
			@AttributeOverride(name = "fpuiconfigId", column = @Column(name = "FPUIConfigID", nullable = false)) })
	public TFpformPropertyId getId() {
		return this.id;
	}

	public void setId(TFpformPropertyId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FPDataTypeID", nullable = false, insertable = false, updatable = false)
	public TDtdataType getTDtdataType() {
		return this.TDtdataType;
	}

	public void setTDtdataType(TDtdataType TDtdataType) {
		this.TDtdataType = TDtdataType;
	}

}
