package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TFvFavorite generated by hbm2java
 */
@Entity
@Table(name = "T_FvFavorite")
public class TFvFavorite implements java.io.Serializable {

	private int fvFavoriteId;
	private TCuCust TCuCust;
	private TStstockType TStstockType;
	private TEqEquipment TEqEquipment;
	private Date fvLastUpdatedDate;
	private Date fvCreationDate;

	public TFvFavorite() {
	}

	public TFvFavorite(int fvFavoriteId, TCuCust TCuCust, TStstockType TStstockType, TEqEquipment TEqEquipment,
			Date fvLastUpdatedDate, Date fvCreationDate) {
		this.fvFavoriteId = fvFavoriteId;
		this.TCuCust = TCuCust;
		this.TStstockType = TStstockType;
		this.TEqEquipment = TEqEquipment;
		this.fvLastUpdatedDate = fvLastUpdatedDate;
		this.fvCreationDate = fvCreationDate;
	}

	@Id

	@Column(name = "FvFavoriteID", unique = true, nullable = false)
	public int getFvFavoriteId() {
		return this.fvFavoriteId;
	}

	public void setFvFavoriteId(int fvFavoriteId) {
		this.fvFavoriteId = fvFavoriteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FvCustID", nullable = false)
	public TCuCust getTCuCust() {
		return this.TCuCust;
	}

	public void setTCuCust(TCuCust TCuCust) {
		this.TCuCust = TCuCust;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FvStockTypeID", nullable = false)
	public TStstockType getTStstockType() {
		return this.TStstockType;
	}

	public void setTStstockType(TStstockType TStstockType) {
		this.TStstockType = TStstockType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FvEquipmentID", nullable = false)
	public TEqEquipment getTEqEquipment() {
		return this.TEqEquipment;
	}

	public void setTEqEquipment(TEqEquipment TEqEquipment) {
		this.TEqEquipment = TEqEquipment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FvLastUpdatedDate", nullable = false, length = 23)
	public Date getFvLastUpdatedDate() {
		return this.fvLastUpdatedDate;
	}

	public void setFvLastUpdatedDate(Date fvLastUpdatedDate) {
		this.fvLastUpdatedDate = fvLastUpdatedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FvCreationDate", nullable = false, length = 23)
	public Date getFvCreationDate() {
		return this.fvCreationDate;
	}

	public void setFvCreationDate(Date fvCreationDate) {
		this.fvCreationDate = fvCreationDate;
	}

}
