package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TGcgiftCert generated by hbm2java
 */
@Entity
@Table(name = "T_GCGiftCert")
public class TGcgiftCert implements java.io.Serializable {

	private int gcgiftCertId;
	private TCuCust TCuCustByGcpurchasedById;
	private TGtgiftCardType TGtgiftCardType;
	private TSoStore TSoStore;
	private TCuCust TCuCustByGcownedById;
	private TTstransStatus TTstransStatus;
	private TCccostCenter TCccostCenter;
	private TInInvoice TInInvoiceByGcusedInvoiceIdN;
	private TPcpc TPcpc;
	private TApaccountingPeriod TApaccountingPeriod;
	private TEmEmp TEmEmp;
	private TInInvoice TInInvoiceByGcpurchasedInvoiceIdN;
	private String gcgiftCertNoTx;
	private Date gccreationDate;
	private Date gcexpiryDate;
	private Date gcactualExpiryDateN;
	private double gcamountMn;
	private short gccurrencyId;
	private float gcexchangeRateFl;
	private Date gclastUpdatedDate;
	private String gcnotesTxN;
	private Date gcvoidDateN;
	private String gcvoidReasonTxN;
	private Set<TPyPayment> TPyPayments = new HashSet<TPyPayment>(0);
	private Set<TIiinvoiceItem> TIiinvoiceItems = new HashSet<TIiinvoiceItem>(0);
	private Set<TVivoucherItem> TVivoucherItems = new HashSet<TVivoucherItem>(0);

	public TGcgiftCert() {
	}

	public TGcgiftCert(int gcgiftCertId, TCuCust TCuCustByGcpurchasedById, TGtgiftCardType TGtgiftCardType,
			TSoStore TSoStore, TCuCust TCuCustByGcownedById, TTstransStatus TTstransStatus, TCccostCenter TCccostCenter,
			TPcpc TPcpc, TEmEmp TEmEmp, Date gccreationDate, Date gcexpiryDate, double gcamountMn, short gccurrencyId,
			float gcexchangeRateFl, Date gclastUpdatedDate) {
		this.gcgiftCertId = gcgiftCertId;
		this.TCuCustByGcpurchasedById = TCuCustByGcpurchasedById;
		this.TGtgiftCardType = TGtgiftCardType;
		this.TSoStore = TSoStore;
		this.TCuCustByGcownedById = TCuCustByGcownedById;
		this.TTstransStatus = TTstransStatus;
		this.TCccostCenter = TCccostCenter;
		this.TPcpc = TPcpc;
		this.TEmEmp = TEmEmp;
		this.gccreationDate = gccreationDate;
		this.gcexpiryDate = gcexpiryDate;
		this.gcamountMn = gcamountMn;
		this.gccurrencyId = gccurrencyId;
		this.gcexchangeRateFl = gcexchangeRateFl;
		this.gclastUpdatedDate = gclastUpdatedDate;
	}

	public TGcgiftCert(int gcgiftCertId, TCuCust TCuCustByGcpurchasedById, TGtgiftCardType TGtgiftCardType,
			TSoStore TSoStore, TCuCust TCuCustByGcownedById, TTstransStatus TTstransStatus, TCccostCenter TCccostCenter,
			TInInvoice TInInvoiceByGcusedInvoiceIdN, TPcpc TPcpc, TApaccountingPeriod TApaccountingPeriod,
			TEmEmp TEmEmp, TInInvoice TInInvoiceByGcpurchasedInvoiceIdN, String gcgiftCertNoTx,
			Date gccreationDate, Date gcexpiryDate, Date gcactualExpiryDateN, double gcamountMn, short gccurrencyId,
			float gcexchangeRateFl, Date gclastUpdatedDate, String gcnotesTxN, Date gcvoidDateN,
			String gcvoidReasonTxN, Set<TPyPayment> TPyPayments, Set<TIiinvoiceItem> TIiinvoiceItems,
			Set<TVivoucherItem> TVivoucherItems) {
		this.gcgiftCertId = gcgiftCertId;
		this.TCuCustByGcpurchasedById = TCuCustByGcpurchasedById;
		this.TGtgiftCardType = TGtgiftCardType;
		this.TSoStore = TSoStore;
		this.TCuCustByGcownedById = TCuCustByGcownedById;
		this.TTstransStatus = TTstransStatus;
		this.TCccostCenter = TCccostCenter;
		this.TInInvoiceByGcusedInvoiceIdN = TInInvoiceByGcusedInvoiceIdN;
		this.TPcpc = TPcpc;
		this.TApaccountingPeriod = TApaccountingPeriod;
		this.TEmEmp = TEmEmp;
		this.TInInvoiceByGcpurchasedInvoiceIdN = TInInvoiceByGcpurchasedInvoiceIdN;
		this.gcgiftCertNoTx = gcgiftCertNoTx;
		this.gccreationDate = gccreationDate;
		this.gcexpiryDate = gcexpiryDate;
		this.gcactualExpiryDateN = gcactualExpiryDateN;
		this.gcamountMn = gcamountMn;
		this.gccurrencyId = gccurrencyId;
		this.gcexchangeRateFl = gcexchangeRateFl;
		this.gclastUpdatedDate = gclastUpdatedDate;
		this.gcnotesTxN = gcnotesTxN;
		this.gcvoidDateN = gcvoidDateN;
		this.gcvoidReasonTxN = gcvoidReasonTxN;
		this.TPyPayments = TPyPayments;
		this.TIiinvoiceItems = TIiinvoiceItems;
		this.TVivoucherItems = TVivoucherItems;
	}

	@Id

	@Column(name = "GCGiftCertID", unique = true, nullable = false)
	public int getGcgiftCertId() {
		return this.gcgiftCertId;
	}

	public void setGcgiftCertId(int gcgiftCertId) {
		this.gcgiftCertId = gcgiftCertId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GCPurchasedByID", nullable = false)
	public TCuCust getTCuCustByGcpurchasedById() {
		return this.TCuCustByGcpurchasedById;
	}

	public void setTCuCustByGcpurchasedById(TCuCust TCuCustByGcpurchasedById) {
		this.TCuCustByGcpurchasedById = TCuCustByGcpurchasedById;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GCGiftCertTypeID", nullable = false)
	public TGtgiftCardType getTGtgiftCardType() {
		return this.TGtgiftCardType;
	}

	public void setTGtgiftCardType(TGtgiftCardType TGtgiftCardType) {
		this.TGtgiftCardType = TGtgiftCardType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GCStoreID", nullable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GCOwnedByID", nullable = false)
	public TCuCust getTCuCustByGcownedById() {
		return this.TCuCustByGcownedById;
	}

	public void setTCuCustByGcownedById(TCuCust TCuCustByGcownedById) {
		this.TCuCustByGcownedById = TCuCustByGcownedById;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GCTransStatusID", nullable = false)
	public TTstransStatus getTTstransStatus() {
		return this.TTstransStatus;
	}

	public void setTTstransStatus(TTstransStatus TTstransStatus) {
		this.TTstransStatus = TTstransStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GCCostCenterID", nullable = false)
	public TCccostCenter getTCccostCenter() {
		return this.TCccostCenter;
	}

	public void setTCccostCenter(TCccostCenter TCccostCenter) {
		this.TCccostCenter = TCccostCenter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GCUsedInvoiceID_N")
	public TInInvoice getTInInvoiceByGcusedInvoiceIdN() {
		return this.TInInvoiceByGcusedInvoiceIdN;
	}

	public void setTInInvoiceByGcusedInvoiceIdN(TInInvoice TInInvoiceByGcusedInvoiceIdN) {
		this.TInInvoiceByGcusedInvoiceIdN = TInInvoiceByGcusedInvoiceIdN;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GCPCID", nullable = false)
	public TPcpc getTPcpc() {
		return this.TPcpc;
	}

	public void setTPcpc(TPcpc TPcpc) {
		this.TPcpc = TPcpc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GCAccountingPeriodID_N")
	public TApaccountingPeriod getTApaccountingPeriod() {
		return this.TApaccountingPeriod;
	}

	public void setTApaccountingPeriod(TApaccountingPeriod TApaccountingPeriod) {
		this.TApaccountingPeriod = TApaccountingPeriod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GCEmpID", nullable = false)
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GCPurchasedInvoiceID_N")
	public TInInvoice getTInInvoiceByGcpurchasedInvoiceIdN() {
		return this.TInInvoiceByGcpurchasedInvoiceIdN;
	}

	public void setTInInvoiceByGcpurchasedInvoiceIdN(TInInvoice TInInvoiceByGcpurchasedInvoiceIdN) {
		this.TInInvoiceByGcpurchasedInvoiceIdN = TInInvoiceByGcpurchasedInvoiceIdN;
	}

	@Column(name = "GCGiftCertNoTx")
	public String getGcgiftCertNoTx() {
		return this.gcgiftCertNoTx;
	}

	public void setGcgiftCertNoTx(String gcgiftCertNoTx) {
		this.gcgiftCertNoTx = gcgiftCertNoTx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GCCreationDate", nullable = false, length = 23)
	public Date getGccreationDate() {
		return this.gccreationDate;
	}

	public void setGccreationDate(Date gccreationDate) {
		this.gccreationDate = gccreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GCExpiryDate", nullable = false, length = 23)
	public Date getGcexpiryDate() {
		return this.gcexpiryDate;
	}

	public void setGcexpiryDate(Date gcexpiryDate) {
		this.gcexpiryDate = gcexpiryDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GCActualExpiryDate_N", length = 23)
	public Date getGcactualExpiryDateN() {
		return this.gcactualExpiryDateN;
	}

	public void setGcactualExpiryDateN(Date gcactualExpiryDateN) {
		this.gcactualExpiryDateN = gcactualExpiryDateN;
	}

	@Column(name = "GCAmountMn", nullable = false, precision = 53, scale = 0)
	public double getGcamountMn() {
		return this.gcamountMn;
	}

	public void setGcamountMn(double gcamountMn) {
		this.gcamountMn = gcamountMn;
	}

	@Column(name = "GCCurrencyID", nullable = false)
	public short getGccurrencyId() {
		return this.gccurrencyId;
	}

	public void setGccurrencyId(short gccurrencyId) {
		this.gccurrencyId = gccurrencyId;
	}

	@Column(name = "GCExchangeRateFl", nullable = false, precision = 24, scale = 0)
	public float getGcexchangeRateFl() {
		return this.gcexchangeRateFl;
	}

	public void setGcexchangeRateFl(float gcexchangeRateFl) {
		this.gcexchangeRateFl = gcexchangeRateFl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GCLastUpdatedDate", nullable = false, length = 23)
	public Date getGclastUpdatedDate() {
		return this.gclastUpdatedDate;
	}

	public void setGclastUpdatedDate(Date gclastUpdatedDate) {
		this.gclastUpdatedDate = gclastUpdatedDate;
	}

	@Column(name = "GCNotesTx_N")
	public String getGcnotesTxN() {
		return this.gcnotesTxN;
	}

	public void setGcnotesTxN(String gcnotesTxN) {
		this.gcnotesTxN = gcnotesTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GCVoidDate_N", length = 23)
	public Date getGcvoidDateN() {
		return this.gcvoidDateN;
	}

	public void setGcvoidDateN(Date gcvoidDateN) {
		this.gcvoidDateN = gcvoidDateN;
	}

	@Column(name = "GCVoidReasonTx_N")
	public String getGcvoidReasonTxN() {
		return this.gcvoidReasonTxN;
	}

	public void setGcvoidReasonTxN(String gcvoidReasonTxN) {
		this.gcvoidReasonTxN = gcvoidReasonTxN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGcgiftCert")
	public Set<TPyPayment> getTPyPayments() {
		return this.TPyPayments;
	}

	public void setTPyPayments(Set<TPyPayment> TPyPayments) {
		this.TPyPayments = TPyPayments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGcgiftCert")
	public Set<TIiinvoiceItem> getTIiinvoiceItems() {
		return this.TIiinvoiceItems;
	}

	public void setTIiinvoiceItems(Set<TIiinvoiceItem> TIiinvoiceItems) {
		this.TIiinvoiceItems = TIiinvoiceItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGcgiftCert")
	public Set<TVivoucherItem> getTVivoucherItems() {
		return this.TVivoucherItems;
	}

	public void setTVivoucherItems(Set<TVivoucherItem> TVivoucherItems) {
		this.TVivoucherItems = TVivoucherItems;
	}

}
