package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TGigiftTypeAllowedItem generated by hbm2java
 */
@Entity
@Table(name = "T_GIGiftTypeAllowedItem")
public class TGigiftTypeAllowedItem implements java.io.Serializable {

	private TGigiftTypeAllowedItemId id;
	private TDtdataType TDtdataType;
	private TGtgiftCardType TGtgiftCardType;

	public TGigiftTypeAllowedItem() {
	}

	public TGigiftTypeAllowedItem(TGigiftTypeAllowedItemId id, TDtdataType TDtdataType,
			TGtgiftCardType TGtgiftCardType) {
		this.id = id;
		this.TDtdataType = TDtdataType;
		this.TGtgiftCardType = TGtgiftCardType;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "gigiftTypeId", column = @Column(name = "GIGiftTypeID", nullable = false)),
			@AttributeOverride(name = "giallowedDataId", column = @Column(name = "GIAllowedDataID", nullable = false)),
			@AttributeOverride(name = "giallowedDataTypeId", column = @Column(name = "GIAllowedDataTypeID", nullable = false)) })
	public TGigiftTypeAllowedItemId getId() {
		return this.id;
	}

	public void setId(TGigiftTypeAllowedItemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GIAllowedDataTypeID", nullable = false, insertable = false, updatable = false)
	public TDtdataType getTDtdataType() {
		return this.TDtdataType;
	}

	public void setTDtdataType(TDtdataType TDtdataType) {
		this.TDtdataType = TDtdataType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GIGiftTypeID", nullable = false, insertable = false, updatable = false)
	public TGtgiftCardType getTGtgiftCardType() {
		return this.TGtgiftCardType;
	}

	public void setTGtgiftCardType(TGtgiftCardType TGtgiftCardType) {
		this.TGtgiftCardType = TGtgiftCardType;
	}

}
