package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TGlaccount generated by hbm2java
 */
@Entity
@Table(name = "T_GLAccount", uniqueConstraints = @UniqueConstraint(columnNames = "GLAccountTx"))
public class TGlaccount implements java.io.Serializable {

	private int glaccountId;
	private String glaccountTx;
	private Date glcreationDate;
	private Date gllastUpdatedDate;
	private boolean glunavailableBl;
	private boolean glrequiredBl;
	private Set<TSoStore> TSoStores = new HashSet<TSoStore>(0);
	private Set<TTbtaxBand> TTbtaxBands = new HashSet<TTbtaxBand>(0);
	private Set<TPfProfitCenter> TPfProfitCentersForPfCogsaccountIdN = new HashSet<TPfProfitCenter>(0);
	private Set<TPfProfitCenter> TPfProfitCentersForPfGlaccountIdN = new HashSet<TPfProfitCenter>(0);
	private Set<TPfProfitCenter> TPfProfitCentersForPfInventoryAccountIdN = new HashSet<TPfProfitCenter>(0);
	private Set<TPmpaymentMethod> TPmpaymentMethods = new HashSet<TPmpaymentMethod>(0);

	public TGlaccount() {
	}

	public TGlaccount(int glaccountId, String glaccountTx, Date glcreationDate, Date gllastUpdatedDate,
			boolean glunavailableBl, boolean glrequiredBl) {
		this.glaccountId = glaccountId;
		this.glaccountTx = glaccountTx;
		this.glcreationDate = glcreationDate;
		this.gllastUpdatedDate = gllastUpdatedDate;
		this.glunavailableBl = glunavailableBl;
		this.glrequiredBl = glrequiredBl;
	}

	public TGlaccount(int glaccountId, String glaccountTx, Date glcreationDate, Date gllastUpdatedDate,
			boolean glunavailableBl, boolean glrequiredBl, Set<TSoStore> TSoStores, Set<TTbtaxBand> TTbtaxBands,
			Set<TPfProfitCenter> TPfProfitCentersForPfCogsaccountIdN,
			Set<TPfProfitCenter> TPfProfitCentersForPfGlaccountIdN,
			Set<TPfProfitCenter> TPfProfitCentersForPfInventoryAccountIdN, Set<TPmpaymentMethod> TPmpaymentMethods) {
		this.glaccountId = glaccountId;
		this.glaccountTx = glaccountTx;
		this.glcreationDate = glcreationDate;
		this.gllastUpdatedDate = gllastUpdatedDate;
		this.glunavailableBl = glunavailableBl;
		this.glrequiredBl = glrequiredBl;
		this.TSoStores = TSoStores;
		this.TTbtaxBands = TTbtaxBands;
		this.TPfProfitCentersForPfCogsaccountIdN = TPfProfitCentersForPfCogsaccountIdN;
		this.TPfProfitCentersForPfGlaccountIdN = TPfProfitCentersForPfGlaccountIdN;
		this.TPfProfitCentersForPfInventoryAccountIdN = TPfProfitCentersForPfInventoryAccountIdN;
		this.TPmpaymentMethods = TPmpaymentMethods;
	}

	@Id

	@Column(name = "GLAccountID", unique = true, nullable = false)
	public int getGlaccountId() {
		return this.glaccountId;
	}

	public void setGlaccountId(int glaccountId) {
		this.glaccountId = glaccountId;
	}

	@Column(name = "GLAccountTx", unique = true, nullable = false)
	public String getGlaccountTx() {
		return this.glaccountTx;
	}

	public void setGlaccountTx(String glaccountTx) {
		this.glaccountTx = glaccountTx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GLCreationDate", nullable = false, length = 23)
	public Date getGlcreationDate() {
		return this.glcreationDate;
	}

	public void setGlcreationDate(Date glcreationDate) {
		this.glcreationDate = glcreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GLLastUpdatedDate", nullable = false, length = 23)
	public Date getGllastUpdatedDate() {
		return this.gllastUpdatedDate;
	}

	public void setGllastUpdatedDate(Date gllastUpdatedDate) {
		this.gllastUpdatedDate = gllastUpdatedDate;
	}

	@Column(name = "GLUnavailableBl", nullable = false)
	public boolean isGlunavailableBl() {
		return this.glunavailableBl;
	}

	public void setGlunavailableBl(boolean glunavailableBl) {
		this.glunavailableBl = glunavailableBl;
	}

	@Column(name = "GLRequiredBl", nullable = false)
	public boolean isGlrequiredBl() {
		return this.glrequiredBl;
	}

	public void setGlrequiredBl(boolean glrequiredBl) {
		this.glrequiredBl = glrequiredBl;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZaStoreGLAccount", joinColumns = {
			@JoinColumn(name = "ZaGLAccountID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZaStoreID", nullable = false, updatable = false) })
	public Set<TSoStore> getTSoStores() {
		return this.TSoStores;
	}

	public void setTSoStores(Set<TSoStore> TSoStores) {
		this.TSoStores = TSoStores;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGlaccount")
	public Set<TTbtaxBand> getTTbtaxBands() {
		return this.TTbtaxBands;
	}

	public void setTTbtaxBands(Set<TTbtaxBand> TTbtaxBands) {
		this.TTbtaxBands = TTbtaxBands;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGlaccountByPfCogsaccountIdN")
	public Set<TPfProfitCenter> getTPfProfitCentersForPfCogsaccountIdN() {
		return this.TPfProfitCentersForPfCogsaccountIdN;
	}

	public void setTPfProfitCentersForPfCogsaccountIdN(Set<TPfProfitCenter> TPfProfitCentersForPfCogsaccountIdN) {
		this.TPfProfitCentersForPfCogsaccountIdN = TPfProfitCentersForPfCogsaccountIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGlaccountByPfGlaccountIdN")
	public Set<TPfProfitCenter> getTPfProfitCentersForPfGlaccountIdN() {
		return this.TPfProfitCentersForPfGlaccountIdN;
	}

	public void setTPfProfitCentersForPfGlaccountIdN(Set<TPfProfitCenter> TPfProfitCentersForPfGlaccountIdN) {
		this.TPfProfitCentersForPfGlaccountIdN = TPfProfitCentersForPfGlaccountIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGlaccountByPfInventoryAccountIdN")
	public Set<TPfProfitCenter> getTPfProfitCentersForPfInventoryAccountIdN() {
		return this.TPfProfitCentersForPfInventoryAccountIdN;
	}

	public void setTPfProfitCentersForPfInventoryAccountIdN(
			Set<TPfProfitCenter> TPfProfitCentersForPfInventoryAccountIdN) {
		this.TPfProfitCentersForPfInventoryAccountIdN = TPfProfitCentersForPfInventoryAccountIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGlaccount")
	public Set<TPmpaymentMethod> getTPmpaymentMethods() {
		return this.TPmpaymentMethods;
	}

	public void setTPmpaymentMethods(Set<TPmpaymentMethod> TPmpaymentMethods) {
		this.TPmpaymentMethods = TPmpaymentMethods;
	}

}
