package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TGpGroup generated by hbm2java
 */
@Entity
@Table(name = "T_GpGroup", uniqueConstraints = @UniqueConstraint(columnNames = "GpGroupNameTx"))
public class TGpGroup implements java.io.Serializable {

	private int gpGroupId;
	private String gpGroupNameTx;
	private Date gpCreationDate;
	private Date gpLastUpdatedDate;
	private boolean gpUnavailableBl;
	private Date gpStartDateN;
	private Date gpEndDateN;
	private boolean gpShowInEolbl;
	private int gpForeColorIn;
	private int gpBackColorIn;
	private Set<TCgcustGroup> TCgcustGroups = new HashSet<TCgcustGroup>(0);

	public TGpGroup() {
	}

	public TGpGroup(int gpGroupId, String gpGroupNameTx, Date gpCreationDate, Date gpLastUpdatedDate,
			boolean gpUnavailableBl, boolean gpShowInEolbl, int gpForeColorIn, int gpBackColorIn) {
		this.gpGroupId = gpGroupId;
		this.gpGroupNameTx = gpGroupNameTx;
		this.gpCreationDate = gpCreationDate;
		this.gpLastUpdatedDate = gpLastUpdatedDate;
		this.gpUnavailableBl = gpUnavailableBl;
		this.gpShowInEolbl = gpShowInEolbl;
		this.gpForeColorIn = gpForeColorIn;
		this.gpBackColorIn = gpBackColorIn;
	}

	public TGpGroup(int gpGroupId, String gpGroupNameTx, Date gpCreationDate, Date gpLastUpdatedDate,
			boolean gpUnavailableBl, Date gpStartDateN, Date gpEndDateN, boolean gpShowInEolbl, int gpForeColorIn,
			int gpBackColorIn, Set<TCgcustGroup> TCgcustGroups) {
		this.gpGroupId = gpGroupId;
		this.gpGroupNameTx = gpGroupNameTx;
		this.gpCreationDate = gpCreationDate;
		this.gpLastUpdatedDate = gpLastUpdatedDate;
		this.gpUnavailableBl = gpUnavailableBl;
		this.gpStartDateN = gpStartDateN;
		this.gpEndDateN = gpEndDateN;
		this.gpShowInEolbl = gpShowInEolbl;
		this.gpForeColorIn = gpForeColorIn;
		this.gpBackColorIn = gpBackColorIn;
		this.TCgcustGroups = TCgcustGroups;
	}

	@Id

	@Column(name = "GpGroupID", unique = true, nullable = false)
	public int getGpGroupId() {
		return this.gpGroupId;
	}

	public void setGpGroupId(int gpGroupId) {
		this.gpGroupId = gpGroupId;
	}

	@Column(name = "GpGroupNameTx", unique = true, nullable = false)
	public String getGpGroupNameTx() {
		return this.gpGroupNameTx;
	}

	public void setGpGroupNameTx(String gpGroupNameTx) {
		this.gpGroupNameTx = gpGroupNameTx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GpCreationDate", nullable = false, length = 23)
	public Date getGpCreationDate() {
		return this.gpCreationDate;
	}

	public void setGpCreationDate(Date gpCreationDate) {
		this.gpCreationDate = gpCreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GpLastUpdatedDate", nullable = false, length = 23)
	public Date getGpLastUpdatedDate() {
		return this.gpLastUpdatedDate;
	}

	public void setGpLastUpdatedDate(Date gpLastUpdatedDate) {
		this.gpLastUpdatedDate = gpLastUpdatedDate;
	}

	@Column(name = "GpUnavailableBl", nullable = false)
	public boolean isGpUnavailableBl() {
		return this.gpUnavailableBl;
	}

	public void setGpUnavailableBl(boolean gpUnavailableBl) {
		this.gpUnavailableBl = gpUnavailableBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GpStartDate_N", length = 23)
	public Date getGpStartDateN() {
		return this.gpStartDateN;
	}

	public void setGpStartDateN(Date gpStartDateN) {
		this.gpStartDateN = gpStartDateN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GpEndDate_N", length = 23)
	public Date getGpEndDateN() {
		return this.gpEndDateN;
	}

	public void setGpEndDateN(Date gpEndDateN) {
		this.gpEndDateN = gpEndDateN;
	}

	@Column(name = "GpShowInEOLBl", nullable = false)
	public boolean isGpShowInEolbl() {
		return this.gpShowInEolbl;
	}

	public void setGpShowInEolbl(boolean gpShowInEolbl) {
		this.gpShowInEolbl = gpShowInEolbl;
	}

	@Column(name = "GpForeColorIn", nullable = false)
	public int getGpForeColorIn() {
		return this.gpForeColorIn;
	}

	public void setGpForeColorIn(int gpForeColorIn) {
		this.gpForeColorIn = gpForeColorIn;
	}

	@Column(name = "GpBackColorIn", nullable = false)
	public int getGpBackColorIn() {
		return this.gpBackColorIn;
	}

	public void setGpBackColorIn(int gpBackColorIn) {
		this.gpBackColorIn = gpBackColorIn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGpGroup")
	public Set<TCgcustGroup> getTCgcustGroups() {
		return this.TCgcustGroups;
	}

	public void setTCgcustGroups(Set<TCgcustGroup> TCgcustGroups) {
		this.TCgcustGroups = TCgcustGroups;
	}

}
