package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TIbInstallation generated by hbm2java
 */
@Entity
@Table(name = "T_IbInstallation")
public class TIbInstallation implements java.io.Serializable {

	private int ibInstallationId;
	private String ibInstallationTx;
	private Date ibInstalledDate;

	public TIbInstallation() {
	}

	public TIbInstallation(int ibInstallationId, String ibInstallationTx, Date ibInstalledDate) {
		this.ibInstallationId = ibInstallationId;
		this.ibInstallationTx = ibInstallationTx;
		this.ibInstalledDate = ibInstalledDate;
	}

	@Id

	@Column(name = "IbInstallationId", unique = true, nullable = false)
	public int getIbInstallationId() {
		return this.ibInstallationId;
	}

	public void setIbInstallationId(int ibInstallationId) {
		this.ibInstallationId = ibInstallationId;
	}

	@Column(name = "IbInstallationTx", nullable = false)
	public String getIbInstallationTx() {
		return this.ibInstallationTx;
	}

	public void setIbInstallationTx(String ibInstallationTx) {
		this.ibInstallationTx = ibInstallationTx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IbInstalledDate", nullable = false, length = 23)
	public Date getIbInstalledDate() {
		return this.ibInstalledDate;
	}

	public void setIbInstalledDate(Date ibInstalledDate) {
		this.ibInstalledDate = ibInstalledDate;
	}

}
