package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TIcInventoryLocation generated by hbm2java
 */
@Entity
@Table(name = "T_IcInventoryLocation", uniqueConstraints = @UniqueConstraint(columnNames = "IcInventoryLocationTx"))
public class TIcInventoryLocation implements java.io.Serializable {

	private int icInventoryLocationId;
	private TLcLocation TLcLocation;
	private String icInventoryLocationTx;
	private boolean icUnavailableBl;
	private Date icCreationDate;
	private Date icLastUpdatedDate;
	private boolean icRequiredBl;
	private Set<TZlStoreStockItem> TZlStoreStockItemsForZlStoreLocationIdN = new HashSet<TZlStoreStockItem>(0);
	private Set<TSoStore> TSoStores = new HashSet<TSoStore>(0);
	private Set<TZlStoreStockItem> TZlStoreStockItemsForZlStoreRoomLocationIdN = new HashSet<TZlStoreStockItem>(0);

	public TIcInventoryLocation() {
	}

	public TIcInventoryLocation(int icInventoryLocationId, TLcLocation TLcLocation, String icInventoryLocationTx,
			boolean icUnavailableBl, Date icCreationDate, Date icLastUpdatedDate, boolean icRequiredBl) {
		this.icInventoryLocationId = icInventoryLocationId;
		this.TLcLocation = TLcLocation;
		this.icInventoryLocationTx = icInventoryLocationTx;
		this.icUnavailableBl = icUnavailableBl;
		this.icCreationDate = icCreationDate;
		this.icLastUpdatedDate = icLastUpdatedDate;
		this.icRequiredBl = icRequiredBl;
	}

	public TIcInventoryLocation(int icInventoryLocationId, TLcLocation TLcLocation, String icInventoryLocationTx,
			boolean icUnavailableBl, Date icCreationDate, Date icLastUpdatedDate, boolean icRequiredBl,
			Set<TZlStoreStockItem> TZlStoreStockItemsForZlStoreLocationIdN, Set<TSoStore> TSoStores,
			Set<TZlStoreStockItem> TZlStoreStockItemsForZlStoreRoomLocationIdN) {
		this.icInventoryLocationId = icInventoryLocationId;
		this.TLcLocation = TLcLocation;
		this.icInventoryLocationTx = icInventoryLocationTx;
		this.icUnavailableBl = icUnavailableBl;
		this.icCreationDate = icCreationDate;
		this.icLastUpdatedDate = icLastUpdatedDate;
		this.icRequiredBl = icRequiredBl;
		this.TZlStoreStockItemsForZlStoreLocationIdN = TZlStoreStockItemsForZlStoreLocationIdN;
		this.TSoStores = TSoStores;
		this.TZlStoreStockItemsForZlStoreRoomLocationIdN = TZlStoreStockItemsForZlStoreRoomLocationIdN;
	}

	@Id

	@Column(name = "IcInventoryLocationID", unique = true, nullable = false)
	public int getIcInventoryLocationId() {
		return this.icInventoryLocationId;
	}

	public void setIcInventoryLocationId(int icInventoryLocationId) {
		this.icInventoryLocationId = icInventoryLocationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IcLocationID", nullable = false)
	public TLcLocation getTLcLocation() {
		return this.TLcLocation;
	}

	public void setTLcLocation(TLcLocation TLcLocation) {
		this.TLcLocation = TLcLocation;
	}

	@Column(name = "IcInventoryLocationTx", unique = true, nullable = false)
	public String getIcInventoryLocationTx() {
		return this.icInventoryLocationTx;
	}

	public void setIcInventoryLocationTx(String icInventoryLocationTx) {
		this.icInventoryLocationTx = icInventoryLocationTx;
	}

	@Column(name = "IcUnavailableBl", nullable = false)
	public boolean isIcUnavailableBl() {
		return this.icUnavailableBl;
	}

	public void setIcUnavailableBl(boolean icUnavailableBl) {
		this.icUnavailableBl = icUnavailableBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IcCreationDate", nullable = false, length = 23)
	public Date getIcCreationDate() {
		return this.icCreationDate;
	}

	public void setIcCreationDate(Date icCreationDate) {
		this.icCreationDate = icCreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IcLastUpdatedDate", nullable = false, length = 23)
	public Date getIcLastUpdatedDate() {
		return this.icLastUpdatedDate;
	}

	public void setIcLastUpdatedDate(Date icLastUpdatedDate) {
		this.icLastUpdatedDate = icLastUpdatedDate;
	}

	@Column(name = "IcRequiredBl", nullable = false)
	public boolean isIcRequiredBl() {
		return this.icRequiredBl;
	}

	public void setIcRequiredBl(boolean icRequiredBl) {
		this.icRequiredBl = icRequiredBl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TIcInventoryLocationByZlStoreLocationIdN")
	public Set<TZlStoreStockItem> getTZlStoreStockItemsForZlStoreLocationIdN() {
		return this.TZlStoreStockItemsForZlStoreLocationIdN;
	}

	public void setTZlStoreStockItemsForZlStoreLocationIdN(
			Set<TZlStoreStockItem> TZlStoreStockItemsForZlStoreLocationIdN) {
		this.TZlStoreStockItemsForZlStoreLocationIdN = TZlStoreStockItemsForZlStoreLocationIdN;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZpStoreInventoryLocation", joinColumns = {
			@JoinColumn(name = "ZpInventoryLocationID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZpStoreID", nullable = false, updatable = false) })
	public Set<TSoStore> getTSoStores() {
		return this.TSoStores;
	}

	public void setTSoStores(Set<TSoStore> TSoStores) {
		this.TSoStores = TSoStores;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TIcInventoryLocationByZlStoreRoomLocationIdN")
	public Set<TZlStoreStockItem> getTZlStoreStockItemsForZlStoreRoomLocationIdN() {
		return this.TZlStoreStockItemsForZlStoreRoomLocationIdN;
	}

	public void setTZlStoreStockItemsForZlStoreRoomLocationIdN(
			Set<TZlStoreStockItem> TZlStoreStockItemsForZlStoreRoomLocationIdN) {
		this.TZlStoreStockItemsForZlStoreRoomLocationIdN = TZlStoreStockItemsForZlStoreRoomLocationIdN;
	}

}
