package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TIfinterestFollowUp generated by hbm2java
 */
@Entity
@Table(name = "T_IFInterestFollowUp")
public class TIfinterestFollowUp implements java.io.Serializable {

	private int ifinterestFollowUpId;
	private TFafollowUpAction TFafollowUpAction;
	private TC8custInterest TC8custInterest;
	private TEmEmp TEmEmp;
	private Date ifcreationDate;
	private Date iflastUpdatedDate;
	private String ifnotesTxN;
	private boolean ifrequiredBl;

	public TIfinterestFollowUp() {
	}

	public TIfinterestFollowUp(int ifinterestFollowUpId, TFafollowUpAction TFafollowUpAction,
			TC8custInterest TC8custInterest, TEmEmp TEmEmp, Date ifcreationDate, Date iflastUpdatedDate,
			boolean ifrequiredBl) {
		this.ifinterestFollowUpId = ifinterestFollowUpId;
		this.TFafollowUpAction = TFafollowUpAction;
		this.TC8custInterest = TC8custInterest;
		this.TEmEmp = TEmEmp;
		this.ifcreationDate = ifcreationDate;
		this.iflastUpdatedDate = iflastUpdatedDate;
		this.ifrequiredBl = ifrequiredBl;
	}

	public TIfinterestFollowUp(int ifinterestFollowUpId, TFafollowUpAction TFafollowUpAction,
			TC8custInterest TC8custInterest, TEmEmp TEmEmp, Date ifcreationDate, Date iflastUpdatedDate,
			String ifnotesTxN, boolean ifrequiredBl) {
		this.ifinterestFollowUpId = ifinterestFollowUpId;
		this.TFafollowUpAction = TFafollowUpAction;
		this.TC8custInterest = TC8custInterest;
		this.TEmEmp = TEmEmp;
		this.ifcreationDate = ifcreationDate;
		this.iflastUpdatedDate = iflastUpdatedDate;
		this.ifnotesTxN = ifnotesTxN;
		this.ifrequiredBl = ifrequiredBl;
	}

	@Id

	@Column(name = "IFInterestFollowUpID", unique = true, nullable = false)
	public int getIfinterestFollowUpId() {
		return this.ifinterestFollowUpId;
	}

	public void setIfinterestFollowUpId(int ifinterestFollowUpId) {
		this.ifinterestFollowUpId = ifinterestFollowUpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IFActionID", nullable = false)
	public TFafollowUpAction getTFafollowUpAction() {
		return this.TFafollowUpAction;
	}

	public void setTFafollowUpAction(TFafollowUpAction TFafollowUpAction) {
		this.TFafollowUpAction = TFafollowUpAction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IFCustInterestID", nullable = false)
	public TC8custInterest getTC8custInterest() {
		return this.TC8custInterest;
	}

	public void setTC8custInterest(TC8custInterest TC8custInterest) {
		this.TC8custInterest = TC8custInterest;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IFEmpID", nullable = false)
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IFCreationDate", nullable = false, length = 23)
	public Date getIfcreationDate() {
		return this.ifcreationDate;
	}

	public void setIfcreationDate(Date ifcreationDate) {
		this.ifcreationDate = ifcreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IFLastUpdatedDate", nullable = false, length = 23)
	public Date getIflastUpdatedDate() {
		return this.iflastUpdatedDate;
	}

	public void setIflastUpdatedDate(Date iflastUpdatedDate) {
		this.iflastUpdatedDate = iflastUpdatedDate;
	}

	@Column(name = "IFNotesTx_N")
	public String getIfnotesTxN() {
		return this.ifnotesTxN;
	}

	public void setIfnotesTxN(String ifnotesTxN) {
		this.ifnotesTxN = ifnotesTxN;
	}

	@Column(name = "IFRequiredBl", nullable = false)
	public boolean isIfrequiredBl() {
		return this.ifrequiredBl;
	}

	public void setIfrequiredBl(boolean ifrequiredBl) {
		this.ifrequiredBl = ifrequiredBl;
	}

}
