package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TIiinvoiceItem generated by hbm2java
 */
@Entity
@Table(name = "T_IIInvoiceItem")
public class TIiinvoiceItem implements java.io.Serializable {

	private int iiinvoiceItemId;
	private TDbdiscountBand TDbdiscountBand;
	private TGdGiftCard TGdGiftCard;
	private TStstockType TStstockType;
	private TInInvoice TInInvoice;
	private TC1custCourse TC1custCourse;
	private TGcgiftCert TGcgiftCert;
	private TMeMultiSale TMeMultiSale;
	private TRbrentalBooking TRbrentalBooking;
	private TAnClosing TAnClosing;
	private TRkRoomBooking TRkRoomBooking;
	private TCpCustTrip TCpCustTrip;
	private TSbserviceBooking TSbserviceBooking;
	private TApaccountingPeriod TApaccountingPeriod;
	private TSuSupplier TSuSupplier;
	private TSistockItem TSistockItem;
	private TPfProfitCenter TPfProfitCenter;
	private String iiserialNoTxN;
	private String iirefTxN;
	private short iiqtyIn;
	private short iiqtyAwaitingPickupIn;
	private double iiunitPriceMn;
	private double iipriceMn;
	private double iitaxMn;
	private double iicostPriceMn;
	private String iicostPriceCompsTx;
	private String iitaxBandIdsTx;
	private String iitaxRatesTx;
	private short iicurrencyId;
	private float iiexchangeRateFl;
	private Date iilastUpdatedDate;
	private String iistockNoTx;
	private String iistockItemTx;
	private String iistockTypeTx;
	private String iimanufacturerTx;
	private String iiprimaryColorTxN;
	private String iisecondaryColorTxN;
	private String iisizeTxN;
	private float iicommissionRateFl;
	private boolean iicourseRelatedBl;
	private boolean iitripRelatedBl;
	private String iinotesTxN;
	private Date iicreationDate;
	private Integer iiparentIdN;
	private Integer iistoreLocationIdN;
	private Date iishipDateN;
	private double iicostPriceAtosmn;
	private Integer iishoppingCartRecordId;
	private boolean iimainEventBl;
	private String iiinternalNotesTxN;
	private Integer iiagentInvoiceIdN;
	private Double iiloyaltyAmountMn;
	private Integer iiloyaltyCardIdN;
	private Set<TIeitemCommission> TIeitemCommissions = new HashSet<TIeitemCommission>(0);
	private Set<TTxTax> TTxTaxes = new HashSet<TTxTax>(0);
	private Set<TCdCustOrder> TCdCustOrders = new HashSet<TCdCustOrder>(0);

	public TIiinvoiceItem() {
	}

	public TIiinvoiceItem(int iiinvoiceItemId, TStstockType TStstockType, TInInvoice TInInvoice,
			TSuSupplier TSuSupplier, TSistockItem TSistockItem, TPfProfitCenter TPfProfitCenter, short iiqtyIn,
			short iiqtyAwaitingPickupIn, double iiunitPriceMn, double iipriceMn, double iitaxMn, double iicostPriceMn,
			String iicostPriceCompsTx, String iitaxBandIdsTx, String iitaxRatesTx, short iicurrencyId,
			float iiexchangeRateFl, Date iilastUpdatedDate, String iistockNoTx, String iistockItemTx,
			String iistockTypeTx, String iimanufacturerTx, float iicommissionRateFl,
			boolean iicourseRelatedBl, boolean iitripRelatedBl, Date iicreationDate, double iicostPriceAtosmn,
			boolean iimainEventBl) {
		this.iiinvoiceItemId = iiinvoiceItemId;
		this.TStstockType = TStstockType;
		this.TInInvoice = TInInvoice;
		this.TSuSupplier = TSuSupplier;
		this.TSistockItem = TSistockItem;
		this.TPfProfitCenter = TPfProfitCenter;
		this.iiqtyIn = iiqtyIn;
		this.iiqtyAwaitingPickupIn = iiqtyAwaitingPickupIn;
		this.iiunitPriceMn = iiunitPriceMn;
		this.iipriceMn = iipriceMn;
		this.iitaxMn = iitaxMn;
		this.iicostPriceMn = iicostPriceMn;
		this.iicostPriceCompsTx = iicostPriceCompsTx;
		this.iitaxBandIdsTx = iitaxBandIdsTx;
		this.iitaxRatesTx = iitaxRatesTx;
		this.iicurrencyId = iicurrencyId;
		this.iiexchangeRateFl = iiexchangeRateFl;
		this.iilastUpdatedDate = iilastUpdatedDate;
		this.iistockNoTx = iistockNoTx;
		this.iistockItemTx = iistockItemTx;
		this.iistockTypeTx = iistockTypeTx;
		this.iimanufacturerTx = iimanufacturerTx;
		this.iicommissionRateFl = iicommissionRateFl;
		this.iicourseRelatedBl = iicourseRelatedBl;
		this.iitripRelatedBl = iitripRelatedBl;
		this.iicreationDate = iicreationDate;
		this.iicostPriceAtosmn = iicostPriceAtosmn;
		this.iimainEventBl = iimainEventBl;
	}

	public TIiinvoiceItem(int iiinvoiceItemId, TDbdiscountBand TDbdiscountBand, TGdGiftCard TGdGiftCard,
			TStstockType TStstockType, TInInvoice TInInvoice, TC1custCourse TC1custCourse, TGcgiftCert TGcgiftCert,
			TMeMultiSale TMeMultiSale, TRbrentalBooking TRbrentalBooking, TAnClosing TAnClosing,
			TRkRoomBooking TRkRoomBooking, TCpCustTrip TCpCustTrip, TSbserviceBooking TSbserviceBooking,
			TApaccountingPeriod TApaccountingPeriod, TSuSupplier TSuSupplier, TSistockItem TSistockItem,
			TPfProfitCenter TPfProfitCenter, String iiserialNoTxN, String iirefTxN, short iiqtyIn,
			short iiqtyAwaitingPickupIn, double iiunitPriceMn, double iipriceMn, double iitaxMn, double iicostPriceMn,
			String iicostPriceCompsTx, String iitaxBandIdsTx, String iitaxRatesTx, short iicurrencyId,
			float iiexchangeRateFl, Date iilastUpdatedDate, String iistockNoTx, String iistockItemTx,
			String iistockTypeTx, String iimanufacturerTx, String iiprimaryColorTxN,
			String iisecondaryColorTxN, String iisizeTxN, float iicommissionRateFl,
			boolean iicourseRelatedBl, boolean iitripRelatedBl, String iinotesTxN, Date iicreationDate,
			Integer iiparentIdN, Integer iistoreLocationIdN, Date iishipDateN, double iicostPriceAtosmn,
			Integer iishoppingCartRecordId, boolean iimainEventBl, String iiinternalNotesTxN,
			Integer iiagentInvoiceIdN, Double iiloyaltyAmountMn, Integer iiloyaltyCardIdN,
			Set<TIeitemCommission> TIeitemCommissions, Set<TTxTax> TTxTaxes, Set<TCdCustOrder> TCdCustOrders) {
		this.iiinvoiceItemId = iiinvoiceItemId;
		this.TDbdiscountBand = TDbdiscountBand;
		this.TGdGiftCard = TGdGiftCard;
		this.TStstockType = TStstockType;
		this.TInInvoice = TInInvoice;
		this.TC1custCourse = TC1custCourse;
		this.TGcgiftCert = TGcgiftCert;
		this.TMeMultiSale = TMeMultiSale;
		this.TRbrentalBooking = TRbrentalBooking;
		this.TAnClosing = TAnClosing;
		this.TRkRoomBooking = TRkRoomBooking;
		this.TCpCustTrip = TCpCustTrip;
		this.TSbserviceBooking = TSbserviceBooking;
		this.TApaccountingPeriod = TApaccountingPeriod;
		this.TSuSupplier = TSuSupplier;
		this.TSistockItem = TSistockItem;
		this.TPfProfitCenter = TPfProfitCenter;
		this.iiserialNoTxN = iiserialNoTxN;
		this.iirefTxN = iirefTxN;
		this.iiqtyIn = iiqtyIn;
		this.iiqtyAwaitingPickupIn = iiqtyAwaitingPickupIn;
		this.iiunitPriceMn = iiunitPriceMn;
		this.iipriceMn = iipriceMn;
		this.iitaxMn = iitaxMn;
		this.iicostPriceMn = iicostPriceMn;
		this.iicostPriceCompsTx = iicostPriceCompsTx;
		this.iitaxBandIdsTx = iitaxBandIdsTx;
		this.iitaxRatesTx = iitaxRatesTx;
		this.iicurrencyId = iicurrencyId;
		this.iiexchangeRateFl = iiexchangeRateFl;
		this.iilastUpdatedDate = iilastUpdatedDate;
		this.iistockNoTx = iistockNoTx;
		this.iistockItemTx = iistockItemTx;
		this.iistockTypeTx = iistockTypeTx;
		this.iimanufacturerTx = iimanufacturerTx;
		this.iiprimaryColorTxN = iiprimaryColorTxN;
		this.iisecondaryColorTxN = iisecondaryColorTxN;
		this.iisizeTxN = iisizeTxN;
		this.iicommissionRateFl = iicommissionRateFl;
		this.iicourseRelatedBl = iicourseRelatedBl;
		this.iitripRelatedBl = iitripRelatedBl;
		this.iinotesTxN = iinotesTxN;
		this.iicreationDate = iicreationDate;
		this.iiparentIdN = iiparentIdN;
		this.iistoreLocationIdN = iistoreLocationIdN;
		this.iishipDateN = iishipDateN;
		this.iicostPriceAtosmn = iicostPriceAtosmn;
		this.iishoppingCartRecordId = iishoppingCartRecordId;
		this.iimainEventBl = iimainEventBl;
		this.iiinternalNotesTxN = iiinternalNotesTxN;
		this.iiagentInvoiceIdN = iiagentInvoiceIdN;
		this.iiloyaltyAmountMn = iiloyaltyAmountMn;
		this.iiloyaltyCardIdN = iiloyaltyCardIdN;
		this.TIeitemCommissions = TIeitemCommissions;
		this.TTxTaxes = TTxTaxes;
		this.TCdCustOrders = TCdCustOrders;
	}

	@Id

	@Column(name = "IIInvoiceItemID", unique = true, nullable = false)
	public int getIiinvoiceItemId() {
		return this.iiinvoiceItemId;
	}

	public void setIiinvoiceItemId(int iiinvoiceItemId) {
		this.iiinvoiceItemId = iiinvoiceItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IIDiscountBandID_N")
	public TDbdiscountBand getTDbdiscountBand() {
		return this.TDbdiscountBand;
	}

	public void setTDbdiscountBand(TDbdiscountBand TDbdiscountBand) {
		this.TDbdiscountBand = TDbdiscountBand;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IIGiftCardID_N")
	public TGdGiftCard getTGdGiftCard() {
		return this.TGdGiftCard;
	}

	public void setTGdGiftCard(TGdGiftCard TGdGiftCard) {
		this.TGdGiftCard = TGdGiftCard;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IIStockTypeID", nullable = false)
	public TStstockType getTStstockType() {
		return this.TStstockType;
	}

	public void setTStstockType(TStstockType TStstockType) {
		this.TStstockType = TStstockType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IIInvoiceID", nullable = false)
	public TInInvoice getTInInvoice() {
		return this.TInInvoice;
	}

	public void setTInInvoice(TInInvoice TInInvoice) {
		this.TInInvoice = TInInvoice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IICustCourseID_N")
	public TC1custCourse getTC1custCourse() {
		return this.TC1custCourse;
	}

	public void setTC1custCourse(TC1custCourse TC1custCourse) {
		this.TC1custCourse = TC1custCourse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IIGiftCertID_N")
	public TGcgiftCert getTGcgiftCert() {
		return this.TGcgiftCert;
	}

	public void setTGcgiftCert(TGcgiftCert TGcgiftCert) {
		this.TGcgiftCert = TGcgiftCert;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IIMultiSaleID_N")
	public TMeMultiSale getTMeMultiSale() {
		return this.TMeMultiSale;
	}

	public void setTMeMultiSale(TMeMultiSale TMeMultiSale) {
		this.TMeMultiSale = TMeMultiSale;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IIRentalBookingID_N")
	public TRbrentalBooking getTRbrentalBooking() {
		return this.TRbrentalBooking;
	}

	public void setTRbrentalBooking(TRbrentalBooking TRbrentalBooking) {
		this.TRbrentalBooking = TRbrentalBooking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IIClosingID_N")
	public TAnClosing getTAnClosing() {
		return this.TAnClosing;
	}

	public void setTAnClosing(TAnClosing TAnClosing) {
		this.TAnClosing = TAnClosing;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IIRoomBookingID_N")
	public TRkRoomBooking getTRkRoomBooking() {
		return this.TRkRoomBooking;
	}

	public void setTRkRoomBooking(TRkRoomBooking TRkRoomBooking) {
		this.TRkRoomBooking = TRkRoomBooking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IICustTripID_N")
	public TCpCustTrip getTCpCustTrip() {
		return this.TCpCustTrip;
	}

	public void setTCpCustTrip(TCpCustTrip TCpCustTrip) {
		this.TCpCustTrip = TCpCustTrip;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IIServiceBookingID_N")
	public TSbserviceBooking getTSbserviceBooking() {
		return this.TSbserviceBooking;
	}

	public void setTSbserviceBooking(TSbserviceBooking TSbserviceBooking) {
		this.TSbserviceBooking = TSbserviceBooking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IIAccountingPeriodID_N")
	public TApaccountingPeriod getTApaccountingPeriod() {
		return this.TApaccountingPeriod;
	}

	public void setTApaccountingPeriod(TApaccountingPeriod TApaccountingPeriod) {
		this.TApaccountingPeriod = TApaccountingPeriod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IIManufacturerID", nullable = false)
	public TSuSupplier getTSuSupplier() {
		return this.TSuSupplier;
	}

	public void setTSuSupplier(TSuSupplier TSuSupplier) {
		this.TSuSupplier = TSuSupplier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IIStockItemID", nullable = false)
	public TSistockItem getTSistockItem() {
		return this.TSistockItem;
	}

	public void setTSistockItem(TSistockItem TSistockItem) {
		this.TSistockItem = TSistockItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IIProfitCenterID", nullable = false)
	public TPfProfitCenter getTPfProfitCenter() {
		return this.TPfProfitCenter;
	}

	public void setTPfProfitCenter(TPfProfitCenter TPfProfitCenter) {
		this.TPfProfitCenter = TPfProfitCenter;
	}

	@Column(name = "IISerialNoTx_N")
	public String getIiserialNoTxN() {
		return this.iiserialNoTxN;
	}

	public void setIiserialNoTxN(String iiserialNoTxN) {
		this.iiserialNoTxN = iiserialNoTxN;
	}

	@Column(name = "IIRefTx_N")
	public String getIirefTxN() {
		return this.iirefTxN;
	}

	public void setIirefTxN(String iirefTxN) {
		this.iirefTxN = iirefTxN;
	}

	@Column(name = "IIQtyIn", nullable = false)
	public short getIiqtyIn() {
		return this.iiqtyIn;
	}

	public void setIiqtyIn(short iiqtyIn) {
		this.iiqtyIn = iiqtyIn;
	}

	@Column(name = "IIQtyAwaitingPickupIn", nullable = false)
	public short getIiqtyAwaitingPickupIn() {
		return this.iiqtyAwaitingPickupIn;
	}

	public void setIiqtyAwaitingPickupIn(short iiqtyAwaitingPickupIn) {
		this.iiqtyAwaitingPickupIn = iiqtyAwaitingPickupIn;
	}

	@Column(name = "IIUnitPriceMn", nullable = false, precision = 53, scale = 0)
	public double getIiunitPriceMn() {
		return this.iiunitPriceMn;
	}

	public void setIiunitPriceMn(double iiunitPriceMn) {
		this.iiunitPriceMn = iiunitPriceMn;
	}

	@Column(name = "IIPriceMn", nullable = false, precision = 53, scale = 0)
	public double getIipriceMn() {
		return this.iipriceMn;
	}

	public void setIipriceMn(double iipriceMn) {
		this.iipriceMn = iipriceMn;
	}

	@Column(name = "IITaxMn", nullable = false, precision = 53, scale = 0)
	public double getIitaxMn() {
		return this.iitaxMn;
	}

	public void setIitaxMn(double iitaxMn) {
		this.iitaxMn = iitaxMn;
	}

	@Column(name = "IICostPriceMn", nullable = false, precision = 53, scale = 0)
	public double getIicostPriceMn() {
		return this.iicostPriceMn;
	}

	public void setIicostPriceMn(double iicostPriceMn) {
		this.iicostPriceMn = iicostPriceMn;
	}

	@Column(name = "IICostPriceCompsTx", nullable = false)
	public String getIicostPriceCompsTx() {
		return this.iicostPriceCompsTx;
	}

	public void setIicostPriceCompsTx(String iicostPriceCompsTx) {
		this.iicostPriceCompsTx = iicostPriceCompsTx;
	}

	@Column(name = "IITaxBandIDsTx", nullable = false)
	public String getIitaxBandIdsTx() {
		return this.iitaxBandIdsTx;
	}

	public void setIitaxBandIdsTx(String iitaxBandIdsTx) {
		this.iitaxBandIdsTx = iitaxBandIdsTx;
	}

	@Column(name = "IITaxRatesTx", nullable = false)
	public String getIitaxRatesTx() {
		return this.iitaxRatesTx;
	}

	public void setIitaxRatesTx(String iitaxRatesTx) {
		this.iitaxRatesTx = iitaxRatesTx;
	}

	@Column(name = "IICurrencyID", nullable = false)
	public short getIicurrencyId() {
		return this.iicurrencyId;
	}

	public void setIicurrencyId(short iicurrencyId) {
		this.iicurrencyId = iicurrencyId;
	}

	@Column(name = "IIExchangeRateFl", nullable = false, precision = 24, scale = 0)
	public float getIiexchangeRateFl() {
		return this.iiexchangeRateFl;
	}

	public void setIiexchangeRateFl(float iiexchangeRateFl) {
		this.iiexchangeRateFl = iiexchangeRateFl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IILastUpdatedDate", nullable = false, length = 23)
	public Date getIilastUpdatedDate() {
		return this.iilastUpdatedDate;
	}

	public void setIilastUpdatedDate(Date iilastUpdatedDate) {
		this.iilastUpdatedDate = iilastUpdatedDate;
	}

	@Column(name = "IIStockNoTx", nullable = false)
	public String getIistockNoTx() {
		return this.iistockNoTx;
	}

	public void setIistockNoTx(String iistockNoTx) {
		this.iistockNoTx = iistockNoTx;
	}

	@Column(name = "IIStockItemTx", nullable = false)
	public String getIistockItemTx() {
		return this.iistockItemTx;
	}

	public void setIistockItemTx(String iistockItemTx) {
		this.iistockItemTx = iistockItemTx;
	}

	@Column(name = "IIStockTypeTx", nullable = false)
	public String getIistockTypeTx() {
		return this.iistockTypeTx;
	}

	public void setIistockTypeTx(String iistockTypeTx) {
		this.iistockTypeTx = iistockTypeTx;
	}

	@Column(name = "IIManufacturerTx", nullable = false)
	public String getIimanufacturerTx() {
		return this.iimanufacturerTx;
	}

	public void setIimanufacturerTx(String iimanufacturerTx) {
		this.iimanufacturerTx = iimanufacturerTx;
	}

	@Column(name = "IIPrimaryColorTx_N")
	public String getIiprimaryColorTxN() {
		return this.iiprimaryColorTxN;
	}

	public void setIiprimaryColorTxN(String iiprimaryColorTxN) {
		this.iiprimaryColorTxN = iiprimaryColorTxN;
	}

	@Column(name = "IISecondaryColorTx_N")
	public String getIisecondaryColorTxN() {
		return this.iisecondaryColorTxN;
	}

	public void setIisecondaryColorTxN(String iisecondaryColorTxN) {
		this.iisecondaryColorTxN = iisecondaryColorTxN;
	}

	@Column(name = "IISizeTx_N")
	public String getIisizeTxN() {
		return this.iisizeTxN;
	}

	public void setIisizeTxN(String iisizeTxN) {
		this.iisizeTxN = iisizeTxN;
	}

	@Column(name = "IICommissionRateFl", nullable = false, precision = 24, scale = 0)
	public float getIicommissionRateFl() {
		return this.iicommissionRateFl;
	}

	public void setIicommissionRateFl(float iicommissionRateFl) {
		this.iicommissionRateFl = iicommissionRateFl;
	}

	@Column(name = "IICourseRelatedBl", nullable = false)
	public boolean isIicourseRelatedBl() {
		return this.iicourseRelatedBl;
	}

	public void setIicourseRelatedBl(boolean iicourseRelatedBl) {
		this.iicourseRelatedBl = iicourseRelatedBl;
	}

	@Column(name = "IITripRelatedBl", nullable = false)
	public boolean isIitripRelatedBl() {
		return this.iitripRelatedBl;
	}

	public void setIitripRelatedBl(boolean iitripRelatedBl) {
		this.iitripRelatedBl = iitripRelatedBl;
	}

	@Column(name = "IINotesTx_N")
	public String getIinotesTxN() {
		return this.iinotesTxN;
	}

	public void setIinotesTxN(String iinotesTxN) {
		this.iinotesTxN = iinotesTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IICreationDate", nullable = false, length = 23)
	public Date getIicreationDate() {
		return this.iicreationDate;
	}

	public void setIicreationDate(Date iicreationDate) {
		this.iicreationDate = iicreationDate;
	}

	@Column(name = "IIParentID_N")
	public Integer getIiparentIdN() {
		return this.iiparentIdN;
	}

	public void setIiparentIdN(Integer iiparentIdN) {
		this.iiparentIdN = iiparentIdN;
	}

	@Column(name = "IIStoreLocationID_N")
	public Integer getIistoreLocationIdN() {
		return this.iistoreLocationIdN;
	}

	public void setIistoreLocationIdN(Integer iistoreLocationIdN) {
		this.iistoreLocationIdN = iistoreLocationIdN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IIShipDate_N", length = 23)
	public Date getIishipDateN() {
		return this.iishipDateN;
	}

	public void setIishipDateN(Date iishipDateN) {
		this.iishipDateN = iishipDateN;
	}

	@Column(name = "IICostPriceATOSMn", nullable = false, precision = 53, scale = 0)
	public double getIicostPriceAtosmn() {
		return this.iicostPriceAtosmn;
	}

	public void setIicostPriceAtosmn(double iicostPriceAtosmn) {
		this.iicostPriceAtosmn = iicostPriceAtosmn;
	}

	@Column(name = "IIShoppingCartRecordId")
	public Integer getIishoppingCartRecordId() {
		return this.iishoppingCartRecordId;
	}

	public void setIishoppingCartRecordId(Integer iishoppingCartRecordId) {
		this.iishoppingCartRecordId = iishoppingCartRecordId;
	}

	@Column(name = "IIMainEventBl", nullable = false)
	public boolean isIimainEventBl() {
		return this.iimainEventBl;
	}

	public void setIimainEventBl(boolean iimainEventBl) {
		this.iimainEventBl = iimainEventBl;
	}

	@Column(name = "IIInternalNotesTx_N")
	public String getIiinternalNotesTxN() {
		return this.iiinternalNotesTxN;
	}

	public void setIiinternalNotesTxN(String iiinternalNotesTxN) {
		this.iiinternalNotesTxN = iiinternalNotesTxN;
	}

	@Column(name = "IIAgentInvoiceID_N")
	public Integer getIiagentInvoiceIdN() {
		return this.iiagentInvoiceIdN;
	}

	public void setIiagentInvoiceIdN(Integer iiagentInvoiceIdN) {
		this.iiagentInvoiceIdN = iiagentInvoiceIdN;
	}

	@Column(name = "IILoyaltyAmountMn", precision = 53, scale = 0)
	public Double getIiloyaltyAmountMn() {
		return this.iiloyaltyAmountMn;
	}

	public void setIiloyaltyAmountMn(Double iiloyaltyAmountMn) {
		this.iiloyaltyAmountMn = iiloyaltyAmountMn;
	}

	@Column(name = "IILoyaltyCardID_N")
	public Integer getIiloyaltyCardIdN() {
		return this.iiloyaltyCardIdN;
	}

	public void setIiloyaltyCardIdN(Integer iiloyaltyCardIdN) {
		this.iiloyaltyCardIdN = iiloyaltyCardIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TIiinvoiceItem")
	public Set<TIeitemCommission> getTIeitemCommissions() {
		return this.TIeitemCommissions;
	}

	public void setTIeitemCommissions(Set<TIeitemCommission> TIeitemCommissions) {
		this.TIeitemCommissions = TIeitemCommissions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TIiinvoiceItem")
	public Set<TTxTax> getTTxTaxes() {
		return this.TTxTaxes;
	}

	public void setTTxTaxes(Set<TTxTax> TTxTaxes) {
		this.TTxTaxes = TTxTaxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TIiinvoiceItem")
	public Set<TCdCustOrder> getTCdCustOrders() {
		return this.TCdCustOrders;
	}

	public void setTCdCustOrders(Set<TCdCustOrder> TCdCustOrders) {
		this.TCdCustOrders = TCdCustOrders;
	}

}
