package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TInInvoice generated by hbm2java
 */
@Entity
@Table(name = "T_InInvoice")
public class TInInvoice implements java.io.Serializable {

	private int inInvoiceId;
	private TAcAccount TAcAccount;
	private TCuCust TCuCust;
	private TAdAddress TAdAddressByInBillingAddressId;
	private TAdAddress TAdAddressByInShippingAddressId;
	private TSoStore TSoStore;
	private TEmEmp TEmEmp;
	private TScSource TScSource;
	private TItinvoiceType TItinvoiceType;
	private TPcpc TPcpc;
	private TCccostCenter TCccostCenter;
	private TTstransStatus TTstransStatus;
	private Date inCreationDate;
	private Date inCommittedDateN;
	private Date inClosedDateN;
	private Integer inCommissionEmpId;
	private float inCommissionRateFl;
	private boolean inCommissionableBl;
	private double inSubTotalMn;
	private double inTaxMn;
	private Double inLegacyAccPayAmountMnN;
	private short inCurrencyId;
	private float inExchangeRateFl;
	private Date inLastUpdatedDate;
	private String inNotesTxN;
	private Date inVoidDateN;
	private String inVoidReasonTxN;
	private Date inPaymentDueDateN;
	private Date inShipDate;
	private Integer inPostageId;
	private boolean inProcessedBl;
	private String inTicketNoTxN;
	private String inInvoiceNumberTxN;
	private String inUserIptxN;
	private String inOrderStatusTxN;
	private int inOrderStatusCodeInN;
	private boolean inStockLevelsUpdatedBl;
	private Set<TIrinvoiceRelation> TIrinvoiceRelationsForIrchildInvoiceId = new HashSet<TIrinvoiceRelation>(0);
	private Set<TIrinvoiceRelation> TIrinvoiceRelationsForIrparentInvoiceId = new HashSet<TIrinvoiceRelation>(0);
	private Set<TIiinvoiceItem> TIiinvoiceItems = new HashSet<TIiinvoiceItem>(0);
	private Set<TExExpense> TExExpenses = new HashSet<TExExpense>(0);
	private Set<TVoVoucher> TVoVouchersForVoFaultyInvoiceId = new HashSet<TVoVoucher>(0);
	private Set<TMeMultiSale> TMeMultiSales = new HashSet<TMeMultiSale>(0);
	private Set<TGcgiftCert> TGcgiftCertsForGcpurchasedInvoiceIdN = new HashSet<TGcgiftCert>(0);
	private Set<TAyAccountPayment> TAyAccountPayments = new HashSet<TAyAccountPayment>(0);
	private Set<TGrgiftRegistry> TGrgiftRegistries = new HashSet<TGrgiftRegistry>(0);
	private Set<TRbrentalBooking> TRbrentalBookings = new HashSet<TRbrentalBooking>(0);
	private Set<TOnOrderNote> TOnOrderNotes = new HashSet<TOnOrderNote>(0);
	private Set<TGdGiftCard> TGdGiftCards = new HashSet<TGdGiftCard>(0);
	private Set<TSnserialNo> TSnserialNos = new HashSet<TSnserialNo>(0);
	private Set<TVoVoucher> TVoVouchersForVoUsedInvoiceIdN = new HashSet<TVoVoucher>(0);
	private Set<TSbserviceBooking> TSbserviceBookings = new HashSet<TSbserviceBooking>(0);
	private Set<TGcgiftCert> TGcgiftCertsForGcusedInvoiceIdN = new HashSet<TGcgiftCert>(0);
	private Set<TRkRoomBooking> TRkRoomBookings = new HashSet<TRkRoomBooking>(0);
	private Set<TPyPayment> TPyPayments = new HashSet<TPyPayment>(0);

	public TInInvoice() {
	}

	public TInInvoice(int inInvoiceId, TCuCust TCuCust, TSoStore TSoStore, TEmEmp TEmEmp, TItinvoiceType TItinvoiceType,
			TPcpc TPcpc, TCccostCenter TCccostCenter, TTstransStatus TTstransStatus, Date inCreationDate,
			float inCommissionRateFl, boolean inCommissionableBl, double inSubTotalMn, double inTaxMn,
			short inCurrencyId, float inExchangeRateFl, Date inLastUpdatedDate, boolean inProcessedBl,
			int inOrderStatusCodeInN, boolean inStockLevelsUpdatedBl) {
		this.inInvoiceId = inInvoiceId;
		this.TCuCust = TCuCust;
		this.TSoStore = TSoStore;
		this.TEmEmp = TEmEmp;
		this.TItinvoiceType = TItinvoiceType;
		this.TPcpc = TPcpc;
		this.TCccostCenter = TCccostCenter;
		this.TTstransStatus = TTstransStatus;
		this.inCreationDate = inCreationDate;
		this.inCommissionRateFl = inCommissionRateFl;
		this.inCommissionableBl = inCommissionableBl;
		this.inSubTotalMn = inSubTotalMn;
		this.inTaxMn = inTaxMn;
		this.inCurrencyId = inCurrencyId;
		this.inExchangeRateFl = inExchangeRateFl;
		this.inLastUpdatedDate = inLastUpdatedDate;
		this.inProcessedBl = inProcessedBl;
		this.inOrderStatusCodeInN = inOrderStatusCodeInN;
		this.inStockLevelsUpdatedBl = inStockLevelsUpdatedBl;
	}

	public TInInvoice(int inInvoiceId, TAcAccount TAcAccount, TCuCust TCuCust,
			TAdAddress TAdAddressByInBillingAddressId, TAdAddress TAdAddressByInShippingAddressId, TSoStore TSoStore,
			TEmEmp TEmEmp, TScSource TScSource, TItinvoiceType TItinvoiceType, TPcpc TPcpc, TCccostCenter TCccostCenter,
			TTstransStatus TTstransStatus, Date inCreationDate, Date inCommittedDateN, Date inClosedDateN,
			Integer inCommissionEmpId, float inCommissionRateFl, boolean inCommissionableBl, double inSubTotalMn,
			double inTaxMn, Double inLegacyAccPayAmountMnN, short inCurrencyId, float inExchangeRateFl,
			Date inLastUpdatedDate, String inNotesTxN, Date inVoidDateN, String inVoidReasonTxN,
			Date inPaymentDueDateN, Date inShipDate, Integer inPostageId, boolean inProcessedBl,
			String inTicketNoTxN, String inInvoiceNumberTxN, String inUserIptxN, String inOrderStatusTxN,
			int inOrderStatusCodeInN, boolean inStockLevelsUpdatedBl,
			Set<TIrinvoiceRelation> TIrinvoiceRelationsForIrchildInvoiceId,
			Set<TIrinvoiceRelation> TIrinvoiceRelationsForIrparentInvoiceId, Set<TIiinvoiceItem> TIiinvoiceItems,
			Set<TExExpense> TExExpenses, Set<TVoVoucher> TVoVouchersForVoFaultyInvoiceId,
			Set<TMeMultiSale> TMeMultiSales, Set<TGcgiftCert> TGcgiftCertsForGcpurchasedInvoiceIdN,
			Set<TAyAccountPayment> TAyAccountPayments, Set<TGrgiftRegistry> TGrgiftRegistries,
			Set<TRbrentalBooking> TRbrentalBookings, Set<TOnOrderNote> TOnOrderNotes, Set<TGdGiftCard> TGdGiftCards,
			Set<TSnserialNo> TSnserialNos, Set<TVoVoucher> TVoVouchersForVoUsedInvoiceIdN,
			Set<TSbserviceBooking> TSbserviceBookings, Set<TGcgiftCert> TGcgiftCertsForGcusedInvoiceIdN,
			Set<TRkRoomBooking> TRkRoomBookings, Set<TPyPayment> TPyPayments) {
		this.inInvoiceId = inInvoiceId;
		this.TAcAccount = TAcAccount;
		this.TCuCust = TCuCust;
		this.TAdAddressByInBillingAddressId = TAdAddressByInBillingAddressId;
		this.TAdAddressByInShippingAddressId = TAdAddressByInShippingAddressId;
		this.TSoStore = TSoStore;
		this.TEmEmp = TEmEmp;
		this.TScSource = TScSource;
		this.TItinvoiceType = TItinvoiceType;
		this.TPcpc = TPcpc;
		this.TCccostCenter = TCccostCenter;
		this.TTstransStatus = TTstransStatus;
		this.inCreationDate = inCreationDate;
		this.inCommittedDateN = inCommittedDateN;
		this.inClosedDateN = inClosedDateN;
		this.inCommissionEmpId = inCommissionEmpId;
		this.inCommissionRateFl = inCommissionRateFl;
		this.inCommissionableBl = inCommissionableBl;
		this.inSubTotalMn = inSubTotalMn;
		this.inTaxMn = inTaxMn;
		this.inLegacyAccPayAmountMnN = inLegacyAccPayAmountMnN;
		this.inCurrencyId = inCurrencyId;
		this.inExchangeRateFl = inExchangeRateFl;
		this.inLastUpdatedDate = inLastUpdatedDate;
		this.inNotesTxN = inNotesTxN;
		this.inVoidDateN = inVoidDateN;
		this.inVoidReasonTxN = inVoidReasonTxN;
		this.inPaymentDueDateN = inPaymentDueDateN;
		this.inShipDate = inShipDate;
		this.inPostageId = inPostageId;
		this.inProcessedBl = inProcessedBl;
		this.inTicketNoTxN = inTicketNoTxN;
		this.inInvoiceNumberTxN = inInvoiceNumberTxN;
		this.inUserIptxN = inUserIptxN;
		this.inOrderStatusTxN = inOrderStatusTxN;
		this.inOrderStatusCodeInN = inOrderStatusCodeInN;
		this.inStockLevelsUpdatedBl = inStockLevelsUpdatedBl;
		this.TIrinvoiceRelationsForIrchildInvoiceId = TIrinvoiceRelationsForIrchildInvoiceId;
		this.TIrinvoiceRelationsForIrparentInvoiceId = TIrinvoiceRelationsForIrparentInvoiceId;
		this.TIiinvoiceItems = TIiinvoiceItems;
		this.TExExpenses = TExExpenses;
		this.TVoVouchersForVoFaultyInvoiceId = TVoVouchersForVoFaultyInvoiceId;
		this.TMeMultiSales = TMeMultiSales;
		this.TGcgiftCertsForGcpurchasedInvoiceIdN = TGcgiftCertsForGcpurchasedInvoiceIdN;
		this.TAyAccountPayments = TAyAccountPayments;
		this.TGrgiftRegistries = TGrgiftRegistries;
		this.TRbrentalBookings = TRbrentalBookings;
		this.TOnOrderNotes = TOnOrderNotes;
		this.TGdGiftCards = TGdGiftCards;
		this.TSnserialNos = TSnserialNos;
		this.TVoVouchersForVoUsedInvoiceIdN = TVoVouchersForVoUsedInvoiceIdN;
		this.TSbserviceBookings = TSbserviceBookings;
		this.TGcgiftCertsForGcusedInvoiceIdN = TGcgiftCertsForGcusedInvoiceIdN;
		this.TRkRoomBookings = TRkRoomBookings;
		this.TPyPayments = TPyPayments;
	}

	@Id

	@Column(name = "InInvoiceID", unique = true, nullable = false)
	public int getInInvoiceId() {
		return this.inInvoiceId;
	}

	public void setInInvoiceId(int inInvoiceId) {
		this.inInvoiceId = inInvoiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InAccountID_N")
	public TAcAccount getTAcAccount() {
		return this.TAcAccount;
	}

	public void setTAcAccount(TAcAccount TAcAccount) {
		this.TAcAccount = TAcAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InCustID", nullable = false)
	public TCuCust getTCuCust() {
		return this.TCuCust;
	}

	public void setTCuCust(TCuCust TCuCust) {
		this.TCuCust = TCuCust;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InBillingAddressId")
	public TAdAddress getTAdAddressByInBillingAddressId() {
		return this.TAdAddressByInBillingAddressId;
	}

	public void setTAdAddressByInBillingAddressId(TAdAddress TAdAddressByInBillingAddressId) {
		this.TAdAddressByInBillingAddressId = TAdAddressByInBillingAddressId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InShippingAddressId")
	public TAdAddress getTAdAddressByInShippingAddressId() {
		return this.TAdAddressByInShippingAddressId;
	}

	public void setTAdAddressByInShippingAddressId(TAdAddress TAdAddressByInShippingAddressId) {
		this.TAdAddressByInShippingAddressId = TAdAddressByInShippingAddressId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InStoreID", nullable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InEmpID", nullable = false)
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InSourceID_N")
	public TScSource getTScSource() {
		return this.TScSource;
	}

	public void setTScSource(TScSource TScSource) {
		this.TScSource = TScSource;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InInvoiceTypeID", nullable = false)
	public TItinvoiceType getTItinvoiceType() {
		return this.TItinvoiceType;
	}

	public void setTItinvoiceType(TItinvoiceType TItinvoiceType) {
		this.TItinvoiceType = TItinvoiceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InPCID", nullable = false)
	public TPcpc getTPcpc() {
		return this.TPcpc;
	}

	public void setTPcpc(TPcpc TPcpc) {
		this.TPcpc = TPcpc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InCostCenterID", nullable = false)
	public TCccostCenter getTCccostCenter() {
		return this.TCccostCenter;
	}

	public void setTCccostCenter(TCccostCenter TCccostCenter) {
		this.TCccostCenter = TCccostCenter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InTransStatusID", nullable = false)
	public TTstransStatus getTTstransStatus() {
		return this.TTstransStatus;
	}

	public void setTTstransStatus(TTstransStatus TTstransStatus) {
		this.TTstransStatus = TTstransStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InCreationDate", nullable = false, length = 23)
	public Date getInCreationDate() {
		return this.inCreationDate;
	}

	public void setInCreationDate(Date inCreationDate) {
		this.inCreationDate = inCreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InCommittedDate_N", length = 23)
	public Date getInCommittedDateN() {
		return this.inCommittedDateN;
	}

	public void setInCommittedDateN(Date inCommittedDateN) {
		this.inCommittedDateN = inCommittedDateN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InClosedDate_N", length = 23)
	public Date getInClosedDateN() {
		return this.inClosedDateN;
	}

	public void setInClosedDateN(Date inClosedDateN) {
		this.inClosedDateN = inClosedDateN;
	}

	@Column(name = "InCommissionEmpID")
	public Integer getInCommissionEmpId() {
		return this.inCommissionEmpId;
	}

	public void setInCommissionEmpId(Integer inCommissionEmpId) {
		this.inCommissionEmpId = inCommissionEmpId;
	}

	@Column(name = "InCommissionRateFl", nullable = false, precision = 24, scale = 0)
	public float getInCommissionRateFl() {
		return this.inCommissionRateFl;
	}

	public void setInCommissionRateFl(float inCommissionRateFl) {
		this.inCommissionRateFl = inCommissionRateFl;
	}

	@Column(name = "InCommissionableBl", nullable = false)
	public boolean isInCommissionableBl() {
		return this.inCommissionableBl;
	}

	public void setInCommissionableBl(boolean inCommissionableBl) {
		this.inCommissionableBl = inCommissionableBl;
	}

	@Column(name = "InSubTotalMn", nullable = false, precision = 53, scale = 0)
	public double getInSubTotalMn() {
		return this.inSubTotalMn;
	}

	public void setInSubTotalMn(double inSubTotalMn) {
		this.inSubTotalMn = inSubTotalMn;
	}

	@Column(name = "InTaxMn", nullable = false, precision = 53, scale = 0)
	public double getInTaxMn() {
		return this.inTaxMn;
	}

	public void setInTaxMn(double inTaxMn) {
		this.inTaxMn = inTaxMn;
	}

	@Column(name = "InLegacyAccPayAmountMn_N", precision = 53, scale = 0)
	public Double getInLegacyAccPayAmountMnN() {
		return this.inLegacyAccPayAmountMnN;
	}

	public void setInLegacyAccPayAmountMnN(Double inLegacyAccPayAmountMnN) {
		this.inLegacyAccPayAmountMnN = inLegacyAccPayAmountMnN;
	}

	@Column(name = "InCurrencyID", nullable = false)
	public short getInCurrencyId() {
		return this.inCurrencyId;
	}

	public void setInCurrencyId(short inCurrencyId) {
		this.inCurrencyId = inCurrencyId;
	}

	@Column(name = "InExchangeRateFl", nullable = false, precision = 24, scale = 0)
	public float getInExchangeRateFl() {
		return this.inExchangeRateFl;
	}

	public void setInExchangeRateFl(float inExchangeRateFl) {
		this.inExchangeRateFl = inExchangeRateFl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InLastUpdatedDate", nullable = false, length = 23)
	public Date getInLastUpdatedDate() {
		return this.inLastUpdatedDate;
	}

	public void setInLastUpdatedDate(Date inLastUpdatedDate) {
		this.inLastUpdatedDate = inLastUpdatedDate;
	}

	@Column(name = "InNotesTx_N")
	public String getInNotesTxN() {
		return this.inNotesTxN;
	}

	public void setInNotesTxN(String inNotesTxN) {
		this.inNotesTxN = inNotesTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InVoidDate_N", length = 23)
	public Date getInVoidDateN() {
		return this.inVoidDateN;
	}

	public void setInVoidDateN(Date inVoidDateN) {
		this.inVoidDateN = inVoidDateN;
	}

	@Column(name = "InVoidReasonTx_N")
	public String getInVoidReasonTxN() {
		return this.inVoidReasonTxN;
	}

	public void setInVoidReasonTxN(String inVoidReasonTxN) {
		this.inVoidReasonTxN = inVoidReasonTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InPaymentDueDate_N", length = 23)
	public Date getInPaymentDueDateN() {
		return this.inPaymentDueDateN;
	}

	public void setInPaymentDueDateN(Date inPaymentDueDateN) {
		this.inPaymentDueDateN = inPaymentDueDateN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InShipDate", length = 23)
	public Date getInShipDate() {
		return this.inShipDate;
	}

	public void setInShipDate(Date inShipDate) {
		this.inShipDate = inShipDate;
	}

	@Column(name = "InPostageID")
	public Integer getInPostageId() {
		return this.inPostageId;
	}

	public void setInPostageId(Integer inPostageId) {
		this.inPostageId = inPostageId;
	}

	@Column(name = "InProcessedBl", nullable = false)
	public boolean isInProcessedBl() {
		return this.inProcessedBl;
	}

	public void setInProcessedBl(boolean inProcessedBl) {
		this.inProcessedBl = inProcessedBl;
	}

	@Column(name = "InTicketNoTx_N")
	public String getInTicketNoTxN() {
		return this.inTicketNoTxN;
	}

	public void setInTicketNoTxN(String inTicketNoTxN) {
		this.inTicketNoTxN = inTicketNoTxN;
	}

	@Column(name = "InInvoiceNumberTx_N", length = 50)
	public String getInInvoiceNumberTxN() {
		return this.inInvoiceNumberTxN;
	}

	public void setInInvoiceNumberTxN(String inInvoiceNumberTxN) {
		this.inInvoiceNumberTxN = inInvoiceNumberTxN;
	}

	@Column(name = "InUserIPTx_N", length = 50)
	public String getInUserIptxN() {
		return this.inUserIptxN;
	}

	public void setInUserIptxN(String inUserIptxN) {
		this.inUserIptxN = inUserIptxN;
	}

	@Column(name = "InOrderStatusTx_N", length = 50)
	public String getInOrderStatusTxN() {
		return this.inOrderStatusTxN;
	}

	public void setInOrderStatusTxN(String inOrderStatusTxN) {
		this.inOrderStatusTxN = inOrderStatusTxN;
	}

	@Column(name = "InOrderStatusCodeIn_N", nullable = false)
	public int getInOrderStatusCodeInN() {
		return this.inOrderStatusCodeInN;
	}

	public void setInOrderStatusCodeInN(int inOrderStatusCodeInN) {
		this.inOrderStatusCodeInN = inOrderStatusCodeInN;
	}

	@Column(name = "InStockLevelsUpdatedBl", nullable = false)
	public boolean isInStockLevelsUpdatedBl() {
		return this.inStockLevelsUpdatedBl;
	}

	public void setInStockLevelsUpdatedBl(boolean inStockLevelsUpdatedBl) {
		this.inStockLevelsUpdatedBl = inStockLevelsUpdatedBl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoiceByIrchildInvoiceId")
	public Set<TIrinvoiceRelation> getTIrinvoiceRelationsForIrchildInvoiceId() {
		return this.TIrinvoiceRelationsForIrchildInvoiceId;
	}

	public void setTIrinvoiceRelationsForIrchildInvoiceId(
			Set<TIrinvoiceRelation> TIrinvoiceRelationsForIrchildInvoiceId) {
		this.TIrinvoiceRelationsForIrchildInvoiceId = TIrinvoiceRelationsForIrchildInvoiceId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoiceByIrparentInvoiceId")
	public Set<TIrinvoiceRelation> getTIrinvoiceRelationsForIrparentInvoiceId() {
		return this.TIrinvoiceRelationsForIrparentInvoiceId;
	}

	public void setTIrinvoiceRelationsForIrparentInvoiceId(
			Set<TIrinvoiceRelation> TIrinvoiceRelationsForIrparentInvoiceId) {
		this.TIrinvoiceRelationsForIrparentInvoiceId = TIrinvoiceRelationsForIrparentInvoiceId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoice")
	public Set<TIiinvoiceItem> getTIiinvoiceItems() {
		return this.TIiinvoiceItems;
	}

	public void setTIiinvoiceItems(Set<TIiinvoiceItem> TIiinvoiceItems) {
		this.TIiinvoiceItems = TIiinvoiceItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoice")
	public Set<TExExpense> getTExExpenses() {
		return this.TExExpenses;
	}

	public void setTExExpenses(Set<TExExpense> TExExpenses) {
		this.TExExpenses = TExExpenses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoiceByVoFaultyInvoiceId")
	public Set<TVoVoucher> getTVoVouchersForVoFaultyInvoiceId() {
		return this.TVoVouchersForVoFaultyInvoiceId;
	}

	public void setTVoVouchersForVoFaultyInvoiceId(Set<TVoVoucher> TVoVouchersForVoFaultyInvoiceId) {
		this.TVoVouchersForVoFaultyInvoiceId = TVoVouchersForVoFaultyInvoiceId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoice")
	public Set<TMeMultiSale> getTMeMultiSales() {
		return this.TMeMultiSales;
	}

	public void setTMeMultiSales(Set<TMeMultiSale> TMeMultiSales) {
		this.TMeMultiSales = TMeMultiSales;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoiceByGcpurchasedInvoiceIdN")
	public Set<TGcgiftCert> getTGcgiftCertsForGcpurchasedInvoiceIdN() {
		return this.TGcgiftCertsForGcpurchasedInvoiceIdN;
	}

	public void setTGcgiftCertsForGcpurchasedInvoiceIdN(Set<TGcgiftCert> TGcgiftCertsForGcpurchasedInvoiceIdN) {
		this.TGcgiftCertsForGcpurchasedInvoiceIdN = TGcgiftCertsForGcpurchasedInvoiceIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoice")
	public Set<TAyAccountPayment> getTAyAccountPayments() {
		return this.TAyAccountPayments;
	}

	public void setTAyAccountPayments(Set<TAyAccountPayment> TAyAccountPayments) {
		this.TAyAccountPayments = TAyAccountPayments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoice")
	public Set<TGrgiftRegistry> getTGrgiftRegistries() {
		return this.TGrgiftRegistries;
	}

	public void setTGrgiftRegistries(Set<TGrgiftRegistry> TGrgiftRegistries) {
		this.TGrgiftRegistries = TGrgiftRegistries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoice")
	public Set<TRbrentalBooking> getTRbrentalBookings() {
		return this.TRbrentalBookings;
	}

	public void setTRbrentalBookings(Set<TRbrentalBooking> TRbrentalBookings) {
		this.TRbrentalBookings = TRbrentalBookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoice")
	public Set<TOnOrderNote> getTOnOrderNotes() {
		return this.TOnOrderNotes;
	}

	public void setTOnOrderNotes(Set<TOnOrderNote> TOnOrderNotes) {
		this.TOnOrderNotes = TOnOrderNotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoice")
	public Set<TGdGiftCard> getTGdGiftCards() {
		return this.TGdGiftCards;
	}

	public void setTGdGiftCards(Set<TGdGiftCard> TGdGiftCards) {
		this.TGdGiftCards = TGdGiftCards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoice")
	public Set<TSnserialNo> getTSnserialNos() {
		return this.TSnserialNos;
	}

	public void setTSnserialNos(Set<TSnserialNo> TSnserialNos) {
		this.TSnserialNos = TSnserialNos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoiceByVoUsedInvoiceIdN")
	public Set<TVoVoucher> getTVoVouchersForVoUsedInvoiceIdN() {
		return this.TVoVouchersForVoUsedInvoiceIdN;
	}

	public void setTVoVouchersForVoUsedInvoiceIdN(Set<TVoVoucher> TVoVouchersForVoUsedInvoiceIdN) {
		this.TVoVouchersForVoUsedInvoiceIdN = TVoVouchersForVoUsedInvoiceIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoice")
	public Set<TSbserviceBooking> getTSbserviceBookings() {
		return this.TSbserviceBookings;
	}

	public void setTSbserviceBookings(Set<TSbserviceBooking> TSbserviceBookings) {
		this.TSbserviceBookings = TSbserviceBookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoiceByGcusedInvoiceIdN")
	public Set<TGcgiftCert> getTGcgiftCertsForGcusedInvoiceIdN() {
		return this.TGcgiftCertsForGcusedInvoiceIdN;
	}

	public void setTGcgiftCertsForGcusedInvoiceIdN(Set<TGcgiftCert> TGcgiftCertsForGcusedInvoiceIdN) {
		this.TGcgiftCertsForGcusedInvoiceIdN = TGcgiftCertsForGcusedInvoiceIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoice")
	public Set<TRkRoomBooking> getTRkRoomBookings() {
		return this.TRkRoomBookings;
	}

	public void setTRkRoomBookings(Set<TRkRoomBooking> TRkRoomBookings) {
		this.TRkRoomBookings = TRkRoomBookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TInInvoice")
	public Set<TPyPayment> getTPyPayments() {
		return this.TPyPayments;
	}

	public void setTPyPayments(Set<TPyPayment> TPyPayments) {
		this.TPyPayments = TPyPayments;
	}

}
