package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TIuInterestStatus generated by hbm2java
 */
@Entity
@Table(name = "T_IuInterestStatus", uniqueConstraints = @UniqueConstraint(columnNames = "IuInterestStatusTx"))
public class TIuInterestStatus implements java.io.Serializable {

	private int iuInterestStatusId;
	private String iuInterestStatusTx;
	private Date iuCreationDate;
	private Date iuLastUpdated;
	private boolean iuUnavailableBl;
	private boolean iuRequiredBl;

	public TIuInterestStatus() {
	}

	public TIuInterestStatus(int iuInterestStatusId, String iuInterestStatusTx, Date iuCreationDate,
			Date iuLastUpdated, boolean iuUnavailableBl, boolean iuRequiredBl) {
		this.iuInterestStatusId = iuInterestStatusId;
		this.iuInterestStatusTx = iuInterestStatusTx;
		this.iuCreationDate = iuCreationDate;
		this.iuLastUpdated = iuLastUpdated;
		this.iuUnavailableBl = iuUnavailableBl;
		this.iuRequiredBl = iuRequiredBl;
	}

	@Id

	@Column(name = "IuInterestStatusID", unique = true, nullable = false)
	public int getIuInterestStatusId() {
		return this.iuInterestStatusId;
	}

	public void setIuInterestStatusId(int iuInterestStatusId) {
		this.iuInterestStatusId = iuInterestStatusId;
	}

	@Column(name = "IuInterestStatusTx", unique = true, nullable = false)
	public String getIuInterestStatusTx() {
		return this.iuInterestStatusTx;
	}

	public void setIuInterestStatusTx(String iuInterestStatusTx) {
		this.iuInterestStatusTx = iuInterestStatusTx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IuCreationDate", nullable = false, length = 23)
	public Date getIuCreationDate() {
		return this.iuCreationDate;
	}

	public void setIuCreationDate(Date iuCreationDate) {
		this.iuCreationDate = iuCreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IuLastUpdated", nullable = false, length = 23)
	public Date getIuLastUpdated() {
		return this.iuLastUpdated;
	}

	public void setIuLastUpdated(Date iuLastUpdated) {
		this.iuLastUpdated = iuLastUpdated;
	}

	@Column(name = "IuUnavailableBl", nullable = false)
	public boolean isIuUnavailableBl() {
		return this.iuUnavailableBl;
	}

	public void setIuUnavailableBl(boolean iuUnavailableBl) {
		this.iuUnavailableBl = iuUnavailableBl;
	}

	@Column(name = "IuRequiredBl", nullable = false)
	public boolean isIuRequiredBl() {
		return this.iuRequiredBl;
	}

	public void setIuRequiredBl(boolean iuRequiredBl) {
		this.iuRequiredBl = iuRequiredBl;
	}

}
