package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TLhLookupCache generated by hbm2java
 */
@Entity
@Table(name = "T_LhLookupCache")
public class TLhLookupCache implements java.io.Serializable {

	private int lhLookupCacheId;
	private short lhPcid;
	private short lhDataTypeId;
	private Integer lhDataIdN;
	private Date lhCreationDate;

	public TLhLookupCache() {
	}

	public TLhLookupCache(int lhLookupCacheId, short lhPcid, short lhDataTypeId, Date lhCreationDate) {
		this.lhLookupCacheId = lhLookupCacheId;
		this.lhPcid = lhPcid;
		this.lhDataTypeId = lhDataTypeId;
		this.lhCreationDate = lhCreationDate;
	}

	public TLhLookupCache(int lhLookupCacheId, short lhPcid, short lhDataTypeId, Integer lhDataIdN,
			Date lhCreationDate) {
		this.lhLookupCacheId = lhLookupCacheId;
		this.lhPcid = lhPcid;
		this.lhDataTypeId = lhDataTypeId;
		this.lhDataIdN = lhDataIdN;
		this.lhCreationDate = lhCreationDate;
	}

	@Id

	@Column(name = "LhLookupCacheID", unique = true, nullable = false)
	public int getLhLookupCacheId() {
		return this.lhLookupCacheId;
	}

	public void setLhLookupCacheId(int lhLookupCacheId) {
		this.lhLookupCacheId = lhLookupCacheId;
	}

	@Column(name = "LhPCID", nullable = false)
	public short getLhPcid() {
		return this.lhPcid;
	}

	public void setLhPcid(short lhPcid) {
		this.lhPcid = lhPcid;
	}

	@Column(name = "LhDataTypeID", nullable = false)
	public short getLhDataTypeId() {
		return this.lhDataTypeId;
	}

	public void setLhDataTypeId(short lhDataTypeId) {
		this.lhDataTypeId = lhDataTypeId;
	}

	@Column(name = "LhDataID_N")
	public Integer getLhDataIdN() {
		return this.lhDataIdN;
	}

	public void setLhDataIdN(Integer lhDataIdN) {
		this.lhDataIdN = lhDataIdN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LhCreationDate", nullable = false, length = 23)
	public Date getLhCreationDate() {
		return this.lhCreationDate;
	}

	public void setLhCreationDate(Date lhCreationDate) {
		this.lhCreationDate = lhCreationDate;
	}

}
