package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TMdEveModule generated by hbm2java
 */
@Entity
@Table(name = "T_MdEveModule", uniqueConstraints = @UniqueConstraint(columnNames = "MdEveModuleTx"))
public class TMdEveModule implements java.io.Serializable {

	private short mdEvemoduleId;
	private String mdEveModuleTx;
	private String mdBitmap;
	private short mdDisplayOrderIn;
	private int mdBitIn;
	private int mdImageIdx;
	private int mdBackColorIn;
	private int mdForeColorIn;
	private Boolean mdUnavailableBl;
	private String mdDescriptionTxN;
	private String mdUrltxN;
	private boolean mdSortButtonArrayBl;

	public TMdEveModule() {
	}

	public TMdEveModule(short mdEvemoduleId, String mdEveModuleTx, short mdDisplayOrderIn, int mdBitIn,
			int mdImageIdx, int mdBackColorIn, int mdForeColorIn, boolean mdSortButtonArrayBl) {
		this.mdEvemoduleId = mdEvemoduleId;
		this.mdEveModuleTx = mdEveModuleTx;
		this.mdDisplayOrderIn = mdDisplayOrderIn;
		this.mdBitIn = mdBitIn;
		this.mdImageIdx = mdImageIdx;
		this.mdBackColorIn = mdBackColorIn;
		this.mdForeColorIn = mdForeColorIn;
		this.mdSortButtonArrayBl = mdSortButtonArrayBl;
	}

	public TMdEveModule(short mdEvemoduleId, String mdEveModuleTx, String mdBitmap, short mdDisplayOrderIn,
			int mdBitIn, int mdImageIdx, int mdBackColorIn, int mdForeColorIn, Boolean mdUnavailableBl,
			String mdDescriptionTxN, String mdUrltxN, boolean mdSortButtonArrayBl) {
		this.mdEvemoduleId = mdEvemoduleId;
		this.mdEveModuleTx = mdEveModuleTx;
		this.mdBitmap = mdBitmap;
		this.mdDisplayOrderIn = mdDisplayOrderIn;
		this.mdBitIn = mdBitIn;
		this.mdImageIdx = mdImageIdx;
		this.mdBackColorIn = mdBackColorIn;
		this.mdForeColorIn = mdForeColorIn;
		this.mdUnavailableBl = mdUnavailableBl;
		this.mdDescriptionTxN = mdDescriptionTxN;
		this.mdUrltxN = mdUrltxN;
		this.mdSortButtonArrayBl = mdSortButtonArrayBl;
	}

	@Id

	@Column(name = "MdEVEModuleID", unique = true, nullable = false)
	public short getMdEvemoduleId() {
		return this.mdEvemoduleId;
	}

	public void setMdEvemoduleId(short mdEvemoduleId) {
		this.mdEvemoduleId = mdEvemoduleId;
	}

	@Column(name = "MdEveModuleTx", unique = true, nullable = false)
	public String getMdEveModuleTx() {
		return this.mdEveModuleTx;
	}

	public void setMdEveModuleTx(String mdEveModuleTx) {
		this.mdEveModuleTx = mdEveModuleTx;
	}

	@Column(name = "MdBitmap")
	public String getMdBitmap() {
		return this.mdBitmap;
	}

	public void setMdBitmap(String mdBitmap) {
		this.mdBitmap = mdBitmap;
	}

	@Column(name = "MdDisplayOrderIn", nullable = false)
	public short getMdDisplayOrderIn() {
		return this.mdDisplayOrderIn;
	}

	public void setMdDisplayOrderIn(short mdDisplayOrderIn) {
		this.mdDisplayOrderIn = mdDisplayOrderIn;
	}

	@Column(name = "MdBitIn", nullable = false)
	public int getMdBitIn() {
		return this.mdBitIn;
	}

	public void setMdBitIn(int mdBitIn) {
		this.mdBitIn = mdBitIn;
	}

	@Column(name = "MdImageIdx", nullable = false)
	public int getMdImageIdx() {
		return this.mdImageIdx;
	}

	public void setMdImageIdx(int mdImageIdx) {
		this.mdImageIdx = mdImageIdx;
	}

	@Column(name = "MdBackColorIn", nullable = false)
	public int getMdBackColorIn() {
		return this.mdBackColorIn;
	}

	public void setMdBackColorIn(int mdBackColorIn) {
		this.mdBackColorIn = mdBackColorIn;
	}

	@Column(name = "MdForeColorIn", nullable = false)
	public int getMdForeColorIn() {
		return this.mdForeColorIn;
	}

	public void setMdForeColorIn(int mdForeColorIn) {
		this.mdForeColorIn = mdForeColorIn;
	}

	@Column(name = "MdUnavailableBl")
	public Boolean getMdUnavailableBl() {
		return this.mdUnavailableBl;
	}

	public void setMdUnavailableBl(Boolean mdUnavailableBl) {
		this.mdUnavailableBl = mdUnavailableBl;
	}

	@Column(name = "MdDescriptionTx_N")
	public String getMdDescriptionTxN() {
		return this.mdDescriptionTxN;
	}

	public void setMdDescriptionTxN(String mdDescriptionTxN) {
		this.mdDescriptionTxN = mdDescriptionTxN;
	}

	@Column(name = "MdURLTx_N")
	public String getMdUrltxN() {
		return this.mdUrltxN;
	}

	public void setMdUrltxN(String mdUrltxN) {
		this.mdUrltxN = mdUrltxN;
	}

	@Column(name = "MdSortButtonArrayBl", nullable = false)
	public boolean isMdSortButtonArrayBl() {
		return this.mdSortButtonArrayBl;
	}

	public void setMdSortButtonArrayBl(boolean mdSortButtonArrayBl) {
		this.mdSortButtonArrayBl = mdSortButtonArrayBl;
	}

}
