package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TMgMessage generated by hbm2java
 */
@Entity
@Table(name = "T_MgMessage")
public class TMgMessage implements java.io.Serializable {

	private int mgMessageId;
	private TEmEmp TEmEmpByMgToEmpId;
	private TEmEmp TEmEmpByMgFromEmpId;
	private String mgMessageTx;
	private Date mgMsgDate;
	private boolean mgReadBl;

	public TMgMessage() {
	}

	public TMgMessage(int mgMessageId, TEmEmp TEmEmpByMgToEmpId, TEmEmp TEmEmpByMgFromEmpId, String mgMessageTx,
			Date mgMsgDate, boolean mgReadBl) {
		this.mgMessageId = mgMessageId;
		this.TEmEmpByMgToEmpId = TEmEmpByMgToEmpId;
		this.TEmEmpByMgFromEmpId = TEmEmpByMgFromEmpId;
		this.mgMessageTx = mgMessageTx;
		this.mgMsgDate = mgMsgDate;
		this.mgReadBl = mgReadBl;
	}

	@Id

	@Column(name = "MgMessageID", unique = true, nullable = false)
	public int getMgMessageId() {
		return this.mgMessageId;
	}

	public void setMgMessageId(int mgMessageId) {
		this.mgMessageId = mgMessageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MgToEmpID", nullable = false)
	public TEmEmp getTEmEmpByMgToEmpId() {
		return this.TEmEmpByMgToEmpId;
	}

	public void setTEmEmpByMgToEmpId(TEmEmp TEmEmpByMgToEmpId) {
		this.TEmEmpByMgToEmpId = TEmEmpByMgToEmpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MgFromEmpID", nullable = false)
	public TEmEmp getTEmEmpByMgFromEmpId() {
		return this.TEmEmpByMgFromEmpId;
	}

	public void setTEmEmpByMgFromEmpId(TEmEmp TEmEmpByMgFromEmpId) {
		this.TEmEmpByMgFromEmpId = TEmEmpByMgFromEmpId;
	}

	@Column(name = "MgMessageTx", nullable = false)
	public String getMgMessageTx() {
		return this.mgMessageTx;
	}

	public void setMgMessageTx(String mgMessageTx) {
		this.mgMessageTx = mgMessageTx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MgMsgDate", nullable = false, length = 23)
	public Date getMgMsgDate() {
		return this.mgMsgDate;
	}

	public void setMgMsgDate(Date mgMsgDate) {
		this.mgMsgDate = mgMsgDate;
	}

	@Column(name = "MgReadBl", nullable = false)
	public boolean isMgReadBl() {
		return this.mgReadBl;
	}

	public void setMgReadBl(boolean mgReadBl) {
		this.mgReadBl = mgReadBl;
	}

}
