package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TMlmailingList generated by hbm2java
 */
@Entity
@Table(name = "T_MLMailingList", uniqueConstraints = @UniqueConstraint(columnNames = "MLMailingListTx"))
public class TMlmailingList implements java.io.Serializable {

	private int mlmailingListId;
	private String mlmailingListTx;
	private boolean mlunavailableBl;
	private Date mllastUpdatedDate;
	private boolean mlrequiredBl;
	private Date mlcreationDate;
	private boolean mlshowInEolbl;
	private Set<TSoStore> TSoStores = new HashSet<TSoStore>(0);
	private Set<TC9custMailingList> TC9custMailingLists = new HashSet<TC9custMailingList>(0);
	private Set<TMnMenu> TMnMenus = new HashSet<TMnMenu>(0);

	public TMlmailingList() {
	}

	public TMlmailingList(int mlmailingListId, String mlmailingListTx, boolean mlunavailableBl,
			Date mllastUpdatedDate, boolean mlrequiredBl, Date mlcreationDate, boolean mlshowInEolbl) {
		this.mlmailingListId = mlmailingListId;
		this.mlmailingListTx = mlmailingListTx;
		this.mlunavailableBl = mlunavailableBl;
		this.mllastUpdatedDate = mllastUpdatedDate;
		this.mlrequiredBl = mlrequiredBl;
		this.mlcreationDate = mlcreationDate;
		this.mlshowInEolbl = mlshowInEolbl;
	}

	public TMlmailingList(int mlmailingListId, String mlmailingListTx, boolean mlunavailableBl,
			Date mllastUpdatedDate, boolean mlrequiredBl, Date mlcreationDate, boolean mlshowInEolbl,
			Set<TSoStore> TSoStores, Set<TC9custMailingList> TC9custMailingLists, Set<TMnMenu> TMnMenus) {
		this.mlmailingListId = mlmailingListId;
		this.mlmailingListTx = mlmailingListTx;
		this.mlunavailableBl = mlunavailableBl;
		this.mllastUpdatedDate = mllastUpdatedDate;
		this.mlrequiredBl = mlrequiredBl;
		this.mlcreationDate = mlcreationDate;
		this.mlshowInEolbl = mlshowInEolbl;
		this.TSoStores = TSoStores;
		this.TC9custMailingLists = TC9custMailingLists;
		this.TMnMenus = TMnMenus;
	}

	@Id

	@Column(name = "MLMailingListID", unique = true, nullable = false)
	public int getMlmailingListId() {
		return this.mlmailingListId;
	}

	public void setMlmailingListId(int mlmailingListId) {
		this.mlmailingListId = mlmailingListId;
	}

	@Column(name = "MLMailingListTx", unique = true, nullable = false)
	public String getMlmailingListTx() {
		return this.mlmailingListTx;
	}

	public void setMlmailingListTx(String mlmailingListTx) {
		this.mlmailingListTx = mlmailingListTx;
	}

	@Column(name = "MLUnavailableBl", nullable = false)
	public boolean isMlunavailableBl() {
		return this.mlunavailableBl;
	}

	public void setMlunavailableBl(boolean mlunavailableBl) {
		this.mlunavailableBl = mlunavailableBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MLLastUpdatedDate", nullable = false, length = 23)
	public Date getMllastUpdatedDate() {
		return this.mllastUpdatedDate;
	}

	public void setMllastUpdatedDate(Date mllastUpdatedDate) {
		this.mllastUpdatedDate = mllastUpdatedDate;
	}

	@Column(name = "MLRequiredBl", nullable = false)
	public boolean isMlrequiredBl() {
		return this.mlrequiredBl;
	}

	public void setMlrequiredBl(boolean mlrequiredBl) {
		this.mlrequiredBl = mlrequiredBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MLCreationDate", nullable = false, length = 23)
	public Date getMlcreationDate() {
		return this.mlcreationDate;
	}

	public void setMlcreationDate(Date mlcreationDate) {
		this.mlcreationDate = mlcreationDate;
	}

	@Column(name = "MLShowInEOLBl", nullable = false)
	public boolean isMlshowInEolbl() {
		return this.mlshowInEolbl;
	}

	public void setMlshowInEolbl(boolean mlshowInEolbl) {
		this.mlshowInEolbl = mlshowInEolbl;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZfStoreMailingList", joinColumns = {
			@JoinColumn(name = "ZfMailingListID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZfStoreID", nullable = false, updatable = false) })
	public Set<TSoStore> getTSoStores() {
		return this.TSoStores;
	}

	public void setTSoStores(Set<TSoStore> TSoStores) {
		this.TSoStores = TSoStores;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TMlmailingList")
	public Set<TC9custMailingList> getTC9custMailingLists() {
		return this.TC9custMailingLists;
	}

	public void setTC9custMailingLists(Set<TC9custMailingList> TC9custMailingLists) {
		this.TC9custMailingLists = TC9custMailingLists;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_M1MenuMailingList", joinColumns = {
			@JoinColumn(name = "M1MailingListID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "M1MenuID", nullable = false, updatable = false) })
	public Set<TMnMenu> getTMnMenus() {
		return this.TMnMenus;
	}

	public void setTMnMenus(Set<TMnMenu> TMnMenus) {
		this.TMnMenus = TMnMenus;
	}

}
