package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TMoModule generated by hbm2java
 */
@Entity
@Table(name = "T_MoModule")
public class TMoModule implements java.io.Serializable {

	private int moModuleId;
	private TCsCourse TCsCourse;
	private TMtmoduleType TMtmoduleType;
	private TLcLocation TLcLocation;
	private Date moStartDateN;
	private Date moEndDateN;
	private String moNotesTxN;
	private String moProfileTxN;
	private short moCurrencyId;
	private float moExchangeRate;
	private Date moLastUpdatedDate;
	private boolean moRequiredBl;
	private Set<TCzCustModule> TCzCustModules = new HashSet<TCzCustModule>(0);
	private Set<TEdEmpModule> TEdEmpModules = new HashSet<TEdEmpModule>(0);

	public TMoModule() {
	}

	public TMoModule(int moModuleId, TCsCourse TCsCourse, TMtmoduleType TMtmoduleType, short moCurrencyId,
			float moExchangeRate, Date moLastUpdatedDate, boolean moRequiredBl) {
		this.moModuleId = moModuleId;
		this.TCsCourse = TCsCourse;
		this.TMtmoduleType = TMtmoduleType;
		this.moCurrencyId = moCurrencyId;
		this.moExchangeRate = moExchangeRate;
		this.moLastUpdatedDate = moLastUpdatedDate;
		this.moRequiredBl = moRequiredBl;
	}

	public TMoModule(int moModuleId, TCsCourse TCsCourse, TMtmoduleType TMtmoduleType, TLcLocation TLcLocation,
			Date moStartDateN, Date moEndDateN, String moNotesTxN, String moProfileTxN, short moCurrencyId,
			float moExchangeRate, Date moLastUpdatedDate, boolean moRequiredBl, Set<TCzCustModule> TCzCustModules,
			Set<TEdEmpModule> TEdEmpModules) {
		this.moModuleId = moModuleId;
		this.TCsCourse = TCsCourse;
		this.TMtmoduleType = TMtmoduleType;
		this.TLcLocation = TLcLocation;
		this.moStartDateN = moStartDateN;
		this.moEndDateN = moEndDateN;
		this.moNotesTxN = moNotesTxN;
		this.moProfileTxN = moProfileTxN;
		this.moCurrencyId = moCurrencyId;
		this.moExchangeRate = moExchangeRate;
		this.moLastUpdatedDate = moLastUpdatedDate;
		this.moRequiredBl = moRequiredBl;
		this.TCzCustModules = TCzCustModules;
		this.TEdEmpModules = TEdEmpModules;
	}

	@Id

	@Column(name = "MoModuleID", unique = true, nullable = false)
	public int getMoModuleId() {
		return this.moModuleId;
	}

	public void setMoModuleId(int moModuleId) {
		this.moModuleId = moModuleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MoCourseID", nullable = false)
	public TCsCourse getTCsCourse() {
		return this.TCsCourse;
	}

	public void setTCsCourse(TCsCourse TCsCourse) {
		this.TCsCourse = TCsCourse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MoModuleTypeID", nullable = false)
	public TMtmoduleType getTMtmoduleType() {
		return this.TMtmoduleType;
	}

	public void setTMtmoduleType(TMtmoduleType TMtmoduleType) {
		this.TMtmoduleType = TMtmoduleType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MoLocationID_N")
	public TLcLocation getTLcLocation() {
		return this.TLcLocation;
	}

	public void setTLcLocation(TLcLocation TLcLocation) {
		this.TLcLocation = TLcLocation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MoStartDate_N", length = 23)
	public Date getMoStartDateN() {
		return this.moStartDateN;
	}

	public void setMoStartDateN(Date moStartDateN) {
		this.moStartDateN = moStartDateN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MoEndDate_N", length = 23)
	public Date getMoEndDateN() {
		return this.moEndDateN;
	}

	public void setMoEndDateN(Date moEndDateN) {
		this.moEndDateN = moEndDateN;
	}

	@Column(name = "MoNotesTx_N")
	public String getMoNotesTxN() {
		return this.moNotesTxN;
	}

	public void setMoNotesTxN(String moNotesTxN) {
		this.moNotesTxN = moNotesTxN;
	}

	@Column(name = "MoProfileTx_N")
	public String getMoProfileTxN() {
		return this.moProfileTxN;
	}

	public void setMoProfileTxN(String moProfileTxN) {
		this.moProfileTxN = moProfileTxN;
	}

	@Column(name = "MoCurrencyID", nullable = false)
	public short getMoCurrencyId() {
		return this.moCurrencyId;
	}

	public void setMoCurrencyId(short moCurrencyId) {
		this.moCurrencyId = moCurrencyId;
	}

	@Column(name = "MoExchangeRate", nullable = false, precision = 24, scale = 0)
	public float getMoExchangeRate() {
		return this.moExchangeRate;
	}

	public void setMoExchangeRate(float moExchangeRate) {
		this.moExchangeRate = moExchangeRate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MoLastUpdatedDate", nullable = false, length = 23)
	public Date getMoLastUpdatedDate() {
		return this.moLastUpdatedDate;
	}

	public void setMoLastUpdatedDate(Date moLastUpdatedDate) {
		this.moLastUpdatedDate = moLastUpdatedDate;
	}

	@Column(name = "MoRequiredBl", nullable = false)
	public boolean isMoRequiredBl() {
		return this.moRequiredBl;
	}

	public void setMoRequiredBl(boolean moRequiredBl) {
		this.moRequiredBl = moRequiredBl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TMoModule")
	public Set<TCzCustModule> getTCzCustModules() {
		return this.TCzCustModules;
	}

	public void setTCzCustModules(Set<TCzCustModule> TCzCustModules) {
		this.TCzCustModules = TCzCustModules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TMoModule")
	public Set<TEdEmpModule> getTEdEmpModules() {
		return this.TEdEmpModules;
	}

	public void setTEdEmpModules(Set<TEdEmpModule> TEdEmpModules) {
		this.TEdEmpModules = TEdEmpModules;
	}

}
