package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TMsmaritalStatus generated by hbm2java
 */
@Entity
@Table(name = "T_MSMaritalStatus", uniqueConstraints = @UniqueConstraint(columnNames = "MSMaritalStatusTx"))
public class TMsmaritalStatus implements java.io.Serializable {

	private short msmaritalStatusId;
	private String msmaritalStatusTx;
	private boolean msunavailableBl;
	private boolean msrequiredBl;
	private Set<TCuCust> TCuCusts = new HashSet<TCuCust>(0);

	public TMsmaritalStatus() {
	}

	public TMsmaritalStatus(short msmaritalStatusId, String msmaritalStatusTx, boolean msunavailableBl,
			boolean msrequiredBl) {
		this.msmaritalStatusId = msmaritalStatusId;
		this.msmaritalStatusTx = msmaritalStatusTx;
		this.msunavailableBl = msunavailableBl;
		this.msrequiredBl = msrequiredBl;
	}

	public TMsmaritalStatus(short msmaritalStatusId, String msmaritalStatusTx, boolean msunavailableBl,
			boolean msrequiredBl, Set<TCuCust> TCuCusts) {
		this.msmaritalStatusId = msmaritalStatusId;
		this.msmaritalStatusTx = msmaritalStatusTx;
		this.msunavailableBl = msunavailableBl;
		this.msrequiredBl = msrequiredBl;
		this.TCuCusts = TCuCusts;
	}

	@Id

	@Column(name = "MSMaritalStatusID", unique = true, nullable = false)
	public short getMsmaritalStatusId() {
		return this.msmaritalStatusId;
	}

	public void setMsmaritalStatusId(short msmaritalStatusId) {
		this.msmaritalStatusId = msmaritalStatusId;
	}

	@Column(name = "MSMaritalStatusTx", unique = true, nullable = false)
	public String getMsmaritalStatusTx() {
		return this.msmaritalStatusTx;
	}

	public void setMsmaritalStatusTx(String msmaritalStatusTx) {
		this.msmaritalStatusTx = msmaritalStatusTx;
	}

	@Column(name = "MSUnavailableBl", nullable = false)
	public boolean isMsunavailableBl() {
		return this.msunavailableBl;
	}

	public void setMsunavailableBl(boolean msunavailableBl) {
		this.msunavailableBl = msunavailableBl;
	}

	@Column(name = "MSRequiredBl", nullable = false)
	public boolean isMsrequiredBl() {
		return this.msrequiredBl;
	}

	public void setMsrequiredBl(boolean msrequiredBl) {
		this.msrequiredBl = msrequiredBl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TMsmaritalStatus")
	public Set<TCuCust> getTCuCusts() {
		return this.TCuCusts;
	}

	public void setTCuCusts(Set<TCuCust> TCuCusts) {
		this.TCuCusts = TCuCusts;
	}

}
