package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TNmNodeMenu generated by hbm2java
 */
@Entity
@Table(name = "T_NmNodeMenu", uniqueConstraints = @UniqueConstraint(columnNames = { "NmNodeID", "NmMenuID" }))
public class TNmNodeMenu implements java.io.Serializable {

	private int nmNodeMenuId;
	private TNdNode TNdNode;
	private TMnMenu TMnMenu;

	public TNmNodeMenu() {
	}

	public TNmNodeMenu(int nmNodeMenuId, TNdNode TNdNode, TMnMenu TMnMenu) {
		this.nmNodeMenuId = nmNodeMenuId;
		this.TNdNode = TNdNode;
		this.TMnMenu = TMnMenu;
	}

	@Id

	@Column(name = "NmNodeMenuID", unique = true, nullable = false)
	public int getNmNodeMenuId() {
		return this.nmNodeMenuId;
	}

	public void setNmNodeMenuId(int nmNodeMenuId) {
		this.nmNodeMenuId = nmNodeMenuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NmNodeID", nullable = false)
	public TNdNode getTNdNode() {
		return this.TNdNode;
	}

	public void setTNdNode(TNdNode TNdNode) {
		this.TNdNode = TNdNode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NmMenuID", nullable = false)
	public TMnMenu getTMnMenu() {
		return this.TMnMenu;
	}

	public void setTMnMenu(TMnMenu TMnMenu) {
		this.TMnMenu = TMnMenu;
	}

}
