package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TNsnotifStatus generated by hbm2java
 */
@Entity
@Table(name = "T_NSNotifStatus", uniqueConstraints = @UniqueConstraint(columnNames = "NSNotifStatusTx"))
public class TNsnotifStatus implements java.io.Serializable {

	private short nsnotifStatusId;
	private String nsnotifStatusTx;
	private Set<TC1custCourse> TC1custCourses = new HashSet<TC1custCourse>(0);

	public TNsnotifStatus() {
	}

	public TNsnotifStatus(short nsnotifStatusId, String nsnotifStatusTx) {
		this.nsnotifStatusId = nsnotifStatusId;
		this.nsnotifStatusTx = nsnotifStatusTx;
	}

	public TNsnotifStatus(short nsnotifStatusId, String nsnotifStatusTx, Set<TC1custCourse> TC1custCourses) {
		this.nsnotifStatusId = nsnotifStatusId;
		this.nsnotifStatusTx = nsnotifStatusTx;
		this.TC1custCourses = TC1custCourses;
	}

	@Id

	@Column(name = "NSNotifStatusID", unique = true, nullable = false)
	public short getNsnotifStatusId() {
		return this.nsnotifStatusId;
	}

	public void setNsnotifStatusId(short nsnotifStatusId) {
		this.nsnotifStatusId = nsnotifStatusId;
	}

	@Column(name = "NSNotifStatusTx", unique = true, nullable = false)
	public String getNsnotifStatusTx() {
		return this.nsnotifStatusTx;
	}

	public void setNsnotifStatusTx(String nsnotifStatusTx) {
		this.nsnotifStatusTx = nsnotifStatusTx;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TNsnotifStatus")
	public Set<TC1custCourse> getTC1custCourses() {
		return this.TC1custCourses;
	}

	public void setTC1custCourses(Set<TC1custCourse> TC1custCourses) {
		this.TC1custCourses = TC1custCourses;
	}

}
