package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOnOrderNote generated by hbm2java
 */
@Entity
@Table(name = "T_OnOrderNote")
public class TOnOrderNote implements java.io.Serializable {

	private int onNoteId;
	private TInInvoice TInInvoice;
	private String onNoteTx;
	private String onOrderStatusTx;
	private Date onCreatedOnDateN;
	private String onCreatedByTxN;
	private Date onModifiedOnDateN;
	private String onModifiedByTxN;

	public TOnOrderNote() {
	}

	public TOnOrderNote(int onNoteId, TInInvoice TInInvoice, String onNoteTx, String onOrderStatusTx) {
		this.onNoteId = onNoteId;
		this.TInInvoice = TInInvoice;
		this.onNoteTx = onNoteTx;
		this.onOrderStatusTx = onOrderStatusTx;
	}

	public TOnOrderNote(int onNoteId, TInInvoice TInInvoice, String onNoteTx, String onOrderStatusTx,
			Date onCreatedOnDateN, String onCreatedByTxN, Date onModifiedOnDateN, String onModifiedByTxN) {
		this.onNoteId = onNoteId;
		this.TInInvoice = TInInvoice;
		this.onNoteTx = onNoteTx;
		this.onOrderStatusTx = onOrderStatusTx;
		this.onCreatedOnDateN = onCreatedOnDateN;
		this.onCreatedByTxN = onCreatedByTxN;
		this.onModifiedOnDateN = onModifiedOnDateN;
		this.onModifiedByTxN = onModifiedByTxN;
	}

	@Id

	@Column(name = "OnNoteID", unique = true, nullable = false)
	public int getOnNoteId() {
		return this.onNoteId;
	}

	public void setOnNoteId(int onNoteId) {
		this.onNoteId = onNoteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OnInvoiceID", nullable = false)
	public TInInvoice getTInInvoice() {
		return this.TInInvoice;
	}

	public void setTInInvoice(TInInvoice TInInvoice) {
		this.TInInvoice = TInInvoice;
	}

	@Column(name = "OnNoteTx", nullable = false)
	public String getOnNoteTx() {
		return this.onNoteTx;
	}

	public void setOnNoteTx(String onNoteTx) {
		this.onNoteTx = onNoteTx;
	}

	@Column(name = "OnOrderStatusTx", nullable = false)
	public String getOnOrderStatusTx() {
		return this.onOrderStatusTx;
	}

	public void setOnOrderStatusTx(String onOrderStatusTx) {
		this.onOrderStatusTx = onOrderStatusTx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OnCreatedOnDate_N", length = 23)
	public Date getOnCreatedOnDateN() {
		return this.onCreatedOnDateN;
	}

	public void setOnCreatedOnDateN(Date onCreatedOnDateN) {
		this.onCreatedOnDateN = onCreatedOnDateN;
	}

	@Column(name = "OnCreatedByTx_N")
	public String getOnCreatedByTxN() {
		return this.onCreatedByTxN;
	}

	public void setOnCreatedByTxN(String onCreatedByTxN) {
		this.onCreatedByTxN = onCreatedByTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OnModifiedOnDate_N", length = 23)
	public Date getOnModifiedOnDateN() {
		return this.onModifiedOnDateN;
	}

	public void setOnModifiedOnDateN(Date onModifiedOnDateN) {
		this.onModifiedOnDateN = onModifiedOnDateN;
	}

	@Column(name = "OnModifiedByTx_N")
	public String getOnModifiedByTxN() {
		return this.onModifiedByTxN;
	}

	public void setOnModifiedByTxN(String onModifiedByTxN) {
		this.onModifiedByTxN = onModifiedByTxN;
	}

}
