package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPaPodeliveryItem generated by hbm2java
 */
@Entity
@Table(name = "T_PaPODeliveryItem")
public class TPaPodeliveryItem implements java.io.Serializable {

	private int paPodeliveryItemId;
	private TPipoitem TPipoitem;
	private TSistockItem TSistockItem;
	private TPePodelivery TPePodelivery;
	private TSoStore TSoStore;
	private Date paReceivedDate;
	private int paQtyReceivedIn;
	private int paQtyInStockIn;
	private double paCostPriceMn;
	private Integer paAccountingPeriodIdN;
	private Integer paTransferIdN;
	private Set<TP7podeliveryItemDetail> TP7podeliveryItemDetails = new HashSet<TP7podeliveryItemDetail>(0);

	public TPaPodeliveryItem() {
	}

	public TPaPodeliveryItem(int paPodeliveryItemId, TSistockItem TSistockItem, TSoStore TSoStore, Date paReceivedDate,
			int paQtyReceivedIn, int paQtyInStockIn, double paCostPriceMn) {
		this.paPodeliveryItemId = paPodeliveryItemId;
		this.TSistockItem = TSistockItem;
		this.TSoStore = TSoStore;
		this.paReceivedDate = paReceivedDate;
		this.paQtyReceivedIn = paQtyReceivedIn;
		this.paQtyInStockIn = paQtyInStockIn;
		this.paCostPriceMn = paCostPriceMn;
	}

	public TPaPodeliveryItem(int paPodeliveryItemId, TPipoitem TPipoitem, TSistockItem TSistockItem,
			TPePodelivery TPePodelivery, TSoStore TSoStore, Date paReceivedDate, int paQtyReceivedIn,
			int paQtyInStockIn, double paCostPriceMn, Integer paAccountingPeriodIdN, Integer paTransferIdN,
			Set<TP7podeliveryItemDetail> TP7podeliveryItemDetails) {
		this.paPodeliveryItemId = paPodeliveryItemId;
		this.TPipoitem = TPipoitem;
		this.TSistockItem = TSistockItem;
		this.TPePodelivery = TPePodelivery;
		this.TSoStore = TSoStore;
		this.paReceivedDate = paReceivedDate;
		this.paQtyReceivedIn = paQtyReceivedIn;
		this.paQtyInStockIn = paQtyInStockIn;
		this.paCostPriceMn = paCostPriceMn;
		this.paAccountingPeriodIdN = paAccountingPeriodIdN;
		this.paTransferIdN = paTransferIdN;
		this.TP7podeliveryItemDetails = TP7podeliveryItemDetails;
	}

	@Id

	@Column(name = "PaPODeliveryItemID", unique = true, nullable = false)
	public int getPaPodeliveryItemId() {
		return this.paPodeliveryItemId;
	}

	public void setPaPodeliveryItemId(int paPodeliveryItemId) {
		this.paPodeliveryItemId = paPodeliveryItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PaPOItemID_N")
	public TPipoitem getTPipoitem() {
		return this.TPipoitem;
	}

	public void setTPipoitem(TPipoitem TPipoitem) {
		this.TPipoitem = TPipoitem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PaStockItemID", nullable = false)
	public TSistockItem getTSistockItem() {
		return this.TSistockItem;
	}

	public void setTSistockItem(TSistockItem TSistockItem) {
		this.TSistockItem = TSistockItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PaPODeliveryID_N")
	public TPePodelivery getTPePodelivery() {
		return this.TPePodelivery;
	}

	public void setTPePodelivery(TPePodelivery TPePodelivery) {
		this.TPePodelivery = TPePodelivery;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PaStoreID", nullable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PaReceivedDate", nullable = false, length = 23)
	public Date getPaReceivedDate() {
		return this.paReceivedDate;
	}

	public void setPaReceivedDate(Date paReceivedDate) {
		this.paReceivedDate = paReceivedDate;
	}

	@Column(name = "PaQtyReceivedIn", nullable = false)
	public int getPaQtyReceivedIn() {
		return this.paQtyReceivedIn;
	}

	public void setPaQtyReceivedIn(int paQtyReceivedIn) {
		this.paQtyReceivedIn = paQtyReceivedIn;
	}

	@Column(name = "PaQtyInStockIn", nullable = false)
	public int getPaQtyInStockIn() {
		return this.paQtyInStockIn;
	}

	public void setPaQtyInStockIn(int paQtyInStockIn) {
		this.paQtyInStockIn = paQtyInStockIn;
	}

	@Column(name = "PaCostPriceMn", nullable = false, precision = 53, scale = 0)
	public double getPaCostPriceMn() {
		return this.paCostPriceMn;
	}

	public void setPaCostPriceMn(double paCostPriceMn) {
		this.paCostPriceMn = paCostPriceMn;
	}

	@Column(name = "PaAccountingPeriodID_N")
	public Integer getPaAccountingPeriodIdN() {
		return this.paAccountingPeriodIdN;
	}

	public void setPaAccountingPeriodIdN(Integer paAccountingPeriodIdN) {
		this.paAccountingPeriodIdN = paAccountingPeriodIdN;
	}

	@Column(name = "PaTransferID_N")
	public Integer getPaTransferIdN() {
		return this.paTransferIdN;
	}

	public void setPaTransferIdN(Integer paTransferIdN) {
		this.paTransferIdN = paTransferIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPaPodeliveryItem")
	public Set<TP7podeliveryItemDetail> getTP7podeliveryItemDetails() {
		return this.TP7podeliveryItemDetails;
	}

	public void setTP7podeliveryItemDetails(Set<TP7podeliveryItemDetail> TP7podeliveryItemDetails) {
		this.TP7podeliveryItemDetails = TP7podeliveryItemDetails;
	}

}
