package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TPbPccash generated by hbm2java
 */
@Entity
@Table(name = "T_PbPCCash", uniqueConstraints = @UniqueConstraint(columnNames = { "PbPCID", "PbDenominationID" }))
public class TPbPccash implements java.io.Serializable {

	private int pbPccashId;
	private TPcpc TPcpc;
	private TDnDenomination TDnDenomination;
	private int pbQtyStartOfDayIn;
	private int pbQtyEndOfDayIn;
	private int pbDefQtyStartOfDayIn;

	public TPbPccash() {
	}

	public TPbPccash(int pbPccashId, TPcpc TPcpc, TDnDenomination TDnDenomination, int pbQtyStartOfDayIn,
			int pbQtyEndOfDayIn, int pbDefQtyStartOfDayIn) {
		this.pbPccashId = pbPccashId;
		this.TPcpc = TPcpc;
		this.TDnDenomination = TDnDenomination;
		this.pbQtyStartOfDayIn = pbQtyStartOfDayIn;
		this.pbQtyEndOfDayIn = pbQtyEndOfDayIn;
		this.pbDefQtyStartOfDayIn = pbDefQtyStartOfDayIn;
	}

	@Id

	@Column(name = "PbPCCashID", unique = true, nullable = false)
	public int getPbPccashId() {
		return this.pbPccashId;
	}

	public void setPbPccashId(int pbPccashId) {
		this.pbPccashId = pbPccashId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PbPCID", nullable = false)
	public TPcpc getTPcpc() {
		return this.TPcpc;
	}

	public void setTPcpc(TPcpc TPcpc) {
		this.TPcpc = TPcpc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PbDenominationID", nullable = false)
	public TDnDenomination getTDnDenomination() {
		return this.TDnDenomination;
	}

	public void setTDnDenomination(TDnDenomination TDnDenomination) {
		this.TDnDenomination = TDnDenomination;
	}

	@Column(name = "PbQtyStartOfDayIn", nullable = false)
	public int getPbQtyStartOfDayIn() {
		return this.pbQtyStartOfDayIn;
	}

	public void setPbQtyStartOfDayIn(int pbQtyStartOfDayIn) {
		this.pbQtyStartOfDayIn = pbQtyStartOfDayIn;
	}

	@Column(name = "PbQtyEndOfDayIn", nullable = false)
	public int getPbQtyEndOfDayIn() {
		return this.pbQtyEndOfDayIn;
	}

	public void setPbQtyEndOfDayIn(int pbQtyEndOfDayIn) {
		this.pbQtyEndOfDayIn = pbQtyEndOfDayIn;
	}

	@Column(name = "PbDefQtyStartOfDayIn", nullable = false)
	public int getPbDefQtyStartOfDayIn() {
		return this.pbDefQtyStartOfDayIn;
	}

	public void setPbDefQtyStartOfDayIn(int pbDefQtyStartOfDayIn) {
		this.pbDefQtyStartOfDayIn = pbDefQtyStartOfDayIn;
	}

}
