package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TPdPaditerritory generated by hbm2java
 */
@Entity
@Table(name = "T_PdPADITerritory", uniqueConstraints = { @UniqueConstraint(columnNames = "PdShortCodeTx"),
		@UniqueConstraint(columnNames = "PdPADITerritoryTx") })
public class TPdPaditerritory implements java.io.Serializable {

	private short pdPaditerritoryId;
	private String pdShortCodeTx;
	private String pdPaditerritoryTx;
	private String pdContactTxN;
	private String pdAddress1txN;
	private String pdAddress2txN;
	private String pdAddress3txN;
	private String pdAddress4txN;
	private String pdPostcodeTxN;
	private String pdCountryTxN;
	private String pdTelTxN;
	private String pdFaxTxN;
	private String pdEmailTxN;
	private String pdWebTxN;
	private Date pdLastUpdatedDate;
	private boolean pdUnavailableBl;
	private String pdPicurltxN;
	private String pdFtpserverTxN;
	private String pdFtpfolderTxN;
	private String pdFtpfolder2txN;
	private Short pdFtpportInN;
	private String pdFtpuserTxN;
	private String pdFtppasswordTxN;
	private Integer pdFtpserviceInN;
	private Integer pdFtpflagsInN;
	private Integer pdFtpcontextInN;
	private boolean pdRequiredBl;
	private Date pdCreationDate;
	private String pdPtnurltxN;
	private String pdDsdurltxN;
	private Set<TSoStore> TSoStores = new HashSet<TSoStore>(0);

	public TPdPaditerritory() {
	}

	public TPdPaditerritory(short pdPaditerritoryId, String pdShortCodeTx, String pdPaditerritoryTx,
			Date pdLastUpdatedDate, boolean pdUnavailableBl, boolean pdRequiredBl, Date pdCreationDate) {
		this.pdPaditerritoryId = pdPaditerritoryId;
		this.pdShortCodeTx = pdShortCodeTx;
		this.pdPaditerritoryTx = pdPaditerritoryTx;
		this.pdLastUpdatedDate = pdLastUpdatedDate;
		this.pdUnavailableBl = pdUnavailableBl;
		this.pdRequiredBl = pdRequiredBl;
		this.pdCreationDate = pdCreationDate;
	}

	public TPdPaditerritory(short pdPaditerritoryId, String pdShortCodeTx, String pdPaditerritoryTx,
			String pdContactTxN, String pdAddress1txN, String pdAddress2txN,
			String pdAddress3txN, String pdAddress4txN, String pdPostcodeTxN,
			String pdCountryTxN, String pdTelTxN, String pdFaxTxN, String pdEmailTxN,
			String pdWebTxN, Date pdLastUpdatedDate, boolean pdUnavailableBl, String pdPicurltxN,
			String pdFtpserverTxN, String pdFtpfolderTxN, String pdFtpfolder2txN, Short pdFtpportInN,
			String pdFtpuserTxN, String pdFtppasswordTxN, Integer pdFtpserviceInN, Integer pdFtpflagsInN,
			Integer pdFtpcontextInN, boolean pdRequiredBl, Date pdCreationDate, String pdPtnurltxN,
			String pdDsdurltxN, Set<TSoStore> TSoStores) {
		this.pdPaditerritoryId = pdPaditerritoryId;
		this.pdShortCodeTx = pdShortCodeTx;
		this.pdPaditerritoryTx = pdPaditerritoryTx;
		this.pdContactTxN = pdContactTxN;
		this.pdAddress1txN = pdAddress1txN;
		this.pdAddress2txN = pdAddress2txN;
		this.pdAddress3txN = pdAddress3txN;
		this.pdAddress4txN = pdAddress4txN;
		this.pdPostcodeTxN = pdPostcodeTxN;
		this.pdCountryTxN = pdCountryTxN;
		this.pdTelTxN = pdTelTxN;
		this.pdFaxTxN = pdFaxTxN;
		this.pdEmailTxN = pdEmailTxN;
		this.pdWebTxN = pdWebTxN;
		this.pdLastUpdatedDate = pdLastUpdatedDate;
		this.pdUnavailableBl = pdUnavailableBl;
		this.pdPicurltxN = pdPicurltxN;
		this.pdFtpserverTxN = pdFtpserverTxN;
		this.pdFtpfolderTxN = pdFtpfolderTxN;
		this.pdFtpfolder2txN = pdFtpfolder2txN;
		this.pdFtpportInN = pdFtpportInN;
		this.pdFtpuserTxN = pdFtpuserTxN;
		this.pdFtppasswordTxN = pdFtppasswordTxN;
		this.pdFtpserviceInN = pdFtpserviceInN;
		this.pdFtpflagsInN = pdFtpflagsInN;
		this.pdFtpcontextInN = pdFtpcontextInN;
		this.pdRequiredBl = pdRequiredBl;
		this.pdCreationDate = pdCreationDate;
		this.pdPtnurltxN = pdPtnurltxN;
		this.pdDsdurltxN = pdDsdurltxN;
		this.TSoStores = TSoStores;
	}

	@Id

	@Column(name = "PdPADITerritoryID", unique = true, nullable = false)
	public short getPdPaditerritoryId() {
		return this.pdPaditerritoryId;
	}

	public void setPdPaditerritoryId(short pdPaditerritoryId) {
		this.pdPaditerritoryId = pdPaditerritoryId;
	}

	@Column(name = "PdShortCodeTx", unique = true, nullable = false)
	public String getPdShortCodeTx() {
		return this.pdShortCodeTx;
	}

	public void setPdShortCodeTx(String pdShortCodeTx) {
		this.pdShortCodeTx = pdShortCodeTx;
	}

	@Column(name = "PdPADITerritoryTx", unique = true, nullable = false)
	public String getPdPaditerritoryTx() {
		return this.pdPaditerritoryTx;
	}

	public void setPdPaditerritoryTx(String pdPaditerritoryTx) {
		this.pdPaditerritoryTx = pdPaditerritoryTx;
	}

	@Column(name = "PdContactTx_N")
	public String getPdContactTxN() {
		return this.pdContactTxN;
	}

	public void setPdContactTxN(String pdContactTxN) {
		this.pdContactTxN = pdContactTxN;
	}

	@Column(name = "PdAddress1Tx_N")
	public String getPdAddress1txN() {
		return this.pdAddress1txN;
	}

	public void setPdAddress1txN(String pdAddress1txN) {
		this.pdAddress1txN = pdAddress1txN;
	}

	@Column(name = "PdAddress2Tx_N")
	public String getPdAddress2txN() {
		return this.pdAddress2txN;
	}

	public void setPdAddress2txN(String pdAddress2txN) {
		this.pdAddress2txN = pdAddress2txN;
	}

	@Column(name = "PdAddress3Tx_N")
	public String getPdAddress3txN() {
		return this.pdAddress3txN;
	}

	public void setPdAddress3txN(String pdAddress3txN) {
		this.pdAddress3txN = pdAddress3txN;
	}

	@Column(name = "PdAddress4Tx_N")
	public String getPdAddress4txN() {
		return this.pdAddress4txN;
	}

	public void setPdAddress4txN(String pdAddress4txN) {
		this.pdAddress4txN = pdAddress4txN;
	}

	@Column(name = "PdPostcodeTx_N")
	public String getPdPostcodeTxN() {
		return this.pdPostcodeTxN;
	}

	public void setPdPostcodeTxN(String pdPostcodeTxN) {
		this.pdPostcodeTxN = pdPostcodeTxN;
	}

	@Column(name = "PdCountryTx_N")
	public String getPdCountryTxN() {
		return this.pdCountryTxN;
	}

	public void setPdCountryTxN(String pdCountryTxN) {
		this.pdCountryTxN = pdCountryTxN;
	}

	@Column(name = "PdTelTx_N")
	public String getPdTelTxN() {
		return this.pdTelTxN;
	}

	public void setPdTelTxN(String pdTelTxN) {
		this.pdTelTxN = pdTelTxN;
	}

	@Column(name = "PdFaxTx_N")
	public String getPdFaxTxN() {
		return this.pdFaxTxN;
	}

	public void setPdFaxTxN(String pdFaxTxN) {
		this.pdFaxTxN = pdFaxTxN;
	}

	@Column(name = "PdEMailTx_N")
	public String getPdEmailTxN() {
		return this.pdEmailTxN;
	}

	public void setPdEmailTxN(String pdEmailTxN) {
		this.pdEmailTxN = pdEmailTxN;
	}

	@Column(name = "PdWebTx_N")
	public String getPdWebTxN() {
		return this.pdWebTxN;
	}

	public void setPdWebTxN(String pdWebTxN) {
		this.pdWebTxN = pdWebTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PdLastUpdatedDate", nullable = false, length = 23)
	public Date getPdLastUpdatedDate() {
		return this.pdLastUpdatedDate;
	}

	public void setPdLastUpdatedDate(Date pdLastUpdatedDate) {
		this.pdLastUpdatedDate = pdLastUpdatedDate;
	}

	@Column(name = "PdUnavailableBl", nullable = false)
	public boolean isPdUnavailableBl() {
		return this.pdUnavailableBl;
	}

	public void setPdUnavailableBl(boolean pdUnavailableBl) {
		this.pdUnavailableBl = pdUnavailableBl;
	}

	@Column(name = "PdPICURLTx_N")
	public String getPdPicurltxN() {
		return this.pdPicurltxN;
	}

	public void setPdPicurltxN(String pdPicurltxN) {
		this.pdPicurltxN = pdPicurltxN;
	}

	@Column(name = "PdFTPServerTx_N")
	public String getPdFtpserverTxN() {
		return this.pdFtpserverTxN;
	}

	public void setPdFtpserverTxN(String pdFtpserverTxN) {
		this.pdFtpserverTxN = pdFtpserverTxN;
	}

	@Column(name = "PdFTPFolderTx_N")
	public String getPdFtpfolderTxN() {
		return this.pdFtpfolderTxN;
	}

	public void setPdFtpfolderTxN(String pdFtpfolderTxN) {
		this.pdFtpfolderTxN = pdFtpfolderTxN;
	}

	@Column(name = "PdFTPFolder2Tx_N")
	public String getPdFtpfolder2txN() {
		return this.pdFtpfolder2txN;
	}

	public void setPdFtpfolder2txN(String pdFtpfolder2txN) {
		this.pdFtpfolder2txN = pdFtpfolder2txN;
	}

	@Column(name = "PdFTPPortIn_N")
	public Short getPdFtpportInN() {
		return this.pdFtpportInN;
	}

	public void setPdFtpportInN(Short pdFtpportInN) {
		this.pdFtpportInN = pdFtpportInN;
	}

	@Column(name = "PdFTPUserTx_N")
	public String getPdFtpuserTxN() {
		return this.pdFtpuserTxN;
	}

	public void setPdFtpuserTxN(String pdFtpuserTxN) {
		this.pdFtpuserTxN = pdFtpuserTxN;
	}

	@Column(name = "PdFTPPasswordTx_N")
	public String getPdFtppasswordTxN() {
		return this.pdFtppasswordTxN;
	}

	public void setPdFtppasswordTxN(String pdFtppasswordTxN) {
		this.pdFtppasswordTxN = pdFtppasswordTxN;
	}

	@Column(name = "PdFTPServiceIn_N")
	public Integer getPdFtpserviceInN() {
		return this.pdFtpserviceInN;
	}

	public void setPdFtpserviceInN(Integer pdFtpserviceInN) {
		this.pdFtpserviceInN = pdFtpserviceInN;
	}

	@Column(name = "PdFTPFlagsIn_N")
	public Integer getPdFtpflagsInN() {
		return this.pdFtpflagsInN;
	}

	public void setPdFtpflagsInN(Integer pdFtpflagsInN) {
		this.pdFtpflagsInN = pdFtpflagsInN;
	}

	@Column(name = "PdFTPContextIn_N")
	public Integer getPdFtpcontextInN() {
		return this.pdFtpcontextInN;
	}

	public void setPdFtpcontextInN(Integer pdFtpcontextInN) {
		this.pdFtpcontextInN = pdFtpcontextInN;
	}

	@Column(name = "PdRequiredBl", nullable = false)
	public boolean isPdRequiredBl() {
		return this.pdRequiredBl;
	}

	public void setPdRequiredBl(boolean pdRequiredBl) {
		this.pdRequiredBl = pdRequiredBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PdCreationDate", nullable = false, length = 23)
	public Date getPdCreationDate() {
		return this.pdCreationDate;
	}

	public void setPdCreationDate(Date pdCreationDate) {
		this.pdCreationDate = pdCreationDate;
	}

	@Column(name = "PdPTNURLTx_N")
	public String getPdPtnurltxN() {
		return this.pdPtnurltxN;
	}

	public void setPdPtnurltxN(String pdPtnurltxN) {
		this.pdPtnurltxN = pdPtnurltxN;
	}

	@Column(name = "PdDSDURLTx_N")
	public String getPdDsdurltxN() {
		return this.pdDsdurltxN;
	}

	public void setPdDsdurltxN(String pdDsdurltxN) {
		this.pdDsdurltxN = pdDsdurltxN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPdPaditerritory")
	public Set<TSoStore> getTSoStores() {
		return this.TSoStores;
	}

	public void setTSoStores(Set<TSoStore> TSoStores) {
		this.TSoStores = TSoStores;
	}

}
