package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPePodelivery generated by hbm2java
 */
@Entity
@Table(name = "T_PePODelivery")
public class TPePodelivery implements java.io.Serializable {

	private int pePodeliveryId;
	private TPopo TPopo;
	private TEmEmp TEmEmp;
	private Date peDate;
	private String peNotesTxN;
	private Date peCreationDate;
	private Date peLastUpdatedDate;
	private String peDeliveryNoteNoTxN;
	private Set<TPaPodeliveryItem> TPaPodeliveryItems = new HashSet<TPaPodeliveryItem>(0);

	public TPePodelivery() {
	}

	public TPePodelivery(int pePodeliveryId, TPopo TPopo, TEmEmp TEmEmp, Date peDate, Date peCreationDate,
			Date peLastUpdatedDate) {
		this.pePodeliveryId = pePodeliveryId;
		this.TPopo = TPopo;
		this.TEmEmp = TEmEmp;
		this.peDate = peDate;
		this.peCreationDate = peCreationDate;
		this.peLastUpdatedDate = peLastUpdatedDate;
	}

	public TPePodelivery(int pePodeliveryId, TPopo TPopo, TEmEmp TEmEmp, Date peDate, String peNotesTxN,
			Date peCreationDate, Date peLastUpdatedDate, String peDeliveryNoteNoTxN,
			Set<TPaPodeliveryItem> TPaPodeliveryItems) {
		this.pePodeliveryId = pePodeliveryId;
		this.TPopo = TPopo;
		this.TEmEmp = TEmEmp;
		this.peDate = peDate;
		this.peNotesTxN = peNotesTxN;
		this.peCreationDate = peCreationDate;
		this.peLastUpdatedDate = peLastUpdatedDate;
		this.peDeliveryNoteNoTxN = peDeliveryNoteNoTxN;
		this.TPaPodeliveryItems = TPaPodeliveryItems;
	}

	@Id

	@Column(name = "PePODeliveryID", unique = true, nullable = false)
	public int getPePodeliveryId() {
		return this.pePodeliveryId;
	}

	public void setPePodeliveryId(int pePodeliveryId) {
		this.pePodeliveryId = pePodeliveryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PePOID", nullable = false)
	public TPopo getTPopo() {
		return this.TPopo;
	}

	public void setTPopo(TPopo TPopo) {
		this.TPopo = TPopo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PeReceivedByID", nullable = false)
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PeDate", nullable = false, length = 23)
	public Date getPeDate() {
		return this.peDate;
	}

	public void setPeDate(Date peDate) {
		this.peDate = peDate;
	}

	@Column(name = "PeNotesTx_N")
	public String getPeNotesTxN() {
		return this.peNotesTxN;
	}

	public void setPeNotesTxN(String peNotesTxN) {
		this.peNotesTxN = peNotesTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PeCreationDate", nullable = false, length = 23)
	public Date getPeCreationDate() {
		return this.peCreationDate;
	}

	public void setPeCreationDate(Date peCreationDate) {
		this.peCreationDate = peCreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PeLastUpdatedDate", nullable = false, length = 23)
	public Date getPeLastUpdatedDate() {
		return this.peLastUpdatedDate;
	}

	public void setPeLastUpdatedDate(Date peLastUpdatedDate) {
		this.peLastUpdatedDate = peLastUpdatedDate;
	}

	@Column(name = "PeDeliveryNoteNoTx_N")
	public String getPeDeliveryNoteNoTxN() {
		return this.peDeliveryNoteNoTxN;
	}

	public void setPeDeliveryNoteNoTxN(String peDeliveryNoteNoTxN) {
		this.peDeliveryNoteNoTxN = peDeliveryNoteNoTxN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPePodelivery")
	public Set<TPaPodeliveryItem> getTPaPodeliveryItems() {
		return this.TPaPodeliveryItems;
	}

	public void setTPaPodeliveryItems(Set<TPaPodeliveryItem> TPaPodeliveryItems) {
		this.TPaPodeliveryItems = TPaPodeliveryItems;
	}

}
