package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TPjPrivilegeModules generated by hbm2java
 */
@Entity
@Table(name = "T_PjPrivilegeModules", uniqueConstraints = @UniqueConstraint(columnNames = { "PjPrivilegeID",
		"PjModuleID", "PjRelatedModuleID" }))
public class TPjPrivilegeModules implements java.io.Serializable {

	private int pjPrivilegeModuleId;
	private TPiPrivilege TPiPrivilege;
	private short pjModuleId;
	private short pjRelatedModuleId;

	public TPjPrivilegeModules() {
	}

	public TPjPrivilegeModules(int pjPrivilegeModuleId, TPiPrivilege TPiPrivilege, short pjModuleId,
			short pjRelatedModuleId) {
		this.pjPrivilegeModuleId = pjPrivilegeModuleId;
		this.TPiPrivilege = TPiPrivilege;
		this.pjModuleId = pjModuleId;
		this.pjRelatedModuleId = pjRelatedModuleId;
	}

	@Id

	@Column(name = "PjPrivilegeModuleID", unique = true, nullable = false)
	public int getPjPrivilegeModuleId() {
		return this.pjPrivilegeModuleId;
	}

	public void setPjPrivilegeModuleId(int pjPrivilegeModuleId) {
		this.pjPrivilegeModuleId = pjPrivilegeModuleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PjPrivilegeID", nullable = false)
	public TPiPrivilege getTPiPrivilege() {
		return this.TPiPrivilege;
	}

	public void setTPiPrivilege(TPiPrivilege TPiPrivilege) {
		this.TPiPrivilege = TPiPrivilege;
	}

	@Column(name = "PjModuleID", nullable = false)
	public short getPjModuleId() {
		return this.pjModuleId;
	}

	public void setPjModuleId(short pjModuleId) {
		this.pjModuleId = pjModuleId;
	}

	@Column(name = "PjRelatedModuleID", nullable = false)
	public short getPjRelatedModuleId() {
		return this.pjRelatedModuleId;
	}

	public void setPjRelatedModuleId(short pjRelatedModuleId) {
		this.pjRelatedModuleId = pjRelatedModuleId;
	}

}
