package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TPmpaymentMethod generated by hbm2java
 */
@Entity
@Table(name = "T_PMPaymentMethod", uniqueConstraints = @UniqueConstraint(columnNames = "PMPaymentMethodTx"))
public class TPmpaymentMethod implements java.io.Serializable {

	private int pmpaymentMethodId;
	private TGlaccount TGlaccount;
	private String pmpaymentMethodTx;
	private boolean pmccpromptBl;
	private boolean pmopenCashDrawerBl;
	private boolean pmauthorizationRequiredBl;
	private boolean pmcustomerRequiredBl;
	private boolean pmidrequiredBl;
	private boolean pmchqNoPromptBl;
	private boolean pmchqNoMandatoryBl;
	private boolean pmgiftCardPromptBl;
	private boolean pmunavailableBl;
	private Date pmlastUpdatedDate;
	private boolean pmrequiredBl;
	private boolean pmccrequiredOnFileBl;
	private String pmccprefixTxN;
	private String pmccallowedLenTxN;
	private Date pmcreationDate;
	private String pmgraphicTxN;
	private boolean pmccnoMandatoryBl;
	private boolean pmexpDateMandatoryBl;
	private boolean pmauthNoMandatoryBl;
	private boolean pmgiftCertPromptBl;
	private boolean pmvoucherPromptBl;
	private boolean pmaccountPromptBl;
	private String pminvoiceTextTxN;
	private boolean pmtransmitCcbl;
	private boolean pmtransmitDcbl;
	private boolean pmcreditCardBl;
	private short pmadditionalPrintCopiesIn;
	private boolean pmvalidFromAndIssueNoMandatoryBl;
	private Integer pmnonSalesAccountIdN;
	private Integer pmsurchargeStockItemIdN;
	private Double pmsurchargeAmountMnN;
	private Double pmsurchargePercentFlN;
	private boolean pmquickPayBl;
	private Set<TPyPayment> TPyPayments = new HashSet<TPyPayment>(0);
	private Set<TC3custCreditCard> TC3custCreditCards = new HashSet<TC3custCreditCard>(0);
	private Set<TPpPaymentProvider> TPpPaymentProviders = new HashSet<TPpPaymentProvider>(0);
	private Set<TPppopayment> TPppopayments = new HashSet<TPppopayment>(0);
	private Set<TSoStore> TSoStores = new HashSet<TSoStore>(0);

	public TPmpaymentMethod() {
	}

	public TPmpaymentMethod(int pmpaymentMethodId, String pmpaymentMethodTx, boolean pmccpromptBl,
			boolean pmopenCashDrawerBl, boolean pmauthorizationRequiredBl, boolean pmcustomerRequiredBl,
			boolean pmidrequiredBl, boolean pmchqNoPromptBl, boolean pmchqNoMandatoryBl, boolean pmgiftCardPromptBl,
			boolean pmunavailableBl, Date pmlastUpdatedDate, boolean pmrequiredBl, boolean pmccrequiredOnFileBl,
			Date pmcreationDate, boolean pmccnoMandatoryBl, boolean pmexpDateMandatoryBl, boolean pmauthNoMandatoryBl,
			boolean pmgiftCertPromptBl, boolean pmvoucherPromptBl, boolean pmaccountPromptBl, boolean pmtransmitCcbl,
			boolean pmtransmitDcbl, boolean pmcreditCardBl, short pmadditionalPrintCopiesIn,
			boolean pmvalidFromAndIssueNoMandatoryBl, boolean pmquickPayBl) {
		this.pmpaymentMethodId = pmpaymentMethodId;
		this.pmpaymentMethodTx = pmpaymentMethodTx;
		this.pmccpromptBl = pmccpromptBl;
		this.pmopenCashDrawerBl = pmopenCashDrawerBl;
		this.pmauthorizationRequiredBl = pmauthorizationRequiredBl;
		this.pmcustomerRequiredBl = pmcustomerRequiredBl;
		this.pmidrequiredBl = pmidrequiredBl;
		this.pmchqNoPromptBl = pmchqNoPromptBl;
		this.pmchqNoMandatoryBl = pmchqNoMandatoryBl;
		this.pmgiftCardPromptBl = pmgiftCardPromptBl;
		this.pmunavailableBl = pmunavailableBl;
		this.pmlastUpdatedDate = pmlastUpdatedDate;
		this.pmrequiredBl = pmrequiredBl;
		this.pmccrequiredOnFileBl = pmccrequiredOnFileBl;
		this.pmcreationDate = pmcreationDate;
		this.pmccnoMandatoryBl = pmccnoMandatoryBl;
		this.pmexpDateMandatoryBl = pmexpDateMandatoryBl;
		this.pmauthNoMandatoryBl = pmauthNoMandatoryBl;
		this.pmgiftCertPromptBl = pmgiftCertPromptBl;
		this.pmvoucherPromptBl = pmvoucherPromptBl;
		this.pmaccountPromptBl = pmaccountPromptBl;
		this.pmtransmitCcbl = pmtransmitCcbl;
		this.pmtransmitDcbl = pmtransmitDcbl;
		this.pmcreditCardBl = pmcreditCardBl;
		this.pmadditionalPrintCopiesIn = pmadditionalPrintCopiesIn;
		this.pmvalidFromAndIssueNoMandatoryBl = pmvalidFromAndIssueNoMandatoryBl;
		this.pmquickPayBl = pmquickPayBl;
	}

	public TPmpaymentMethod(int pmpaymentMethodId, TGlaccount TGlaccount, String pmpaymentMethodTx,
			boolean pmccpromptBl, boolean pmopenCashDrawerBl, boolean pmauthorizationRequiredBl,
			boolean pmcustomerRequiredBl, boolean pmidrequiredBl, boolean pmchqNoPromptBl, boolean pmchqNoMandatoryBl,
			boolean pmgiftCardPromptBl, boolean pmunavailableBl, Date pmlastUpdatedDate, boolean pmrequiredBl,
			boolean pmccrequiredOnFileBl, String pmccprefixTxN, String pmccallowedLenTxN,
			Date pmcreationDate, String pmgraphicTxN, boolean pmccnoMandatoryBl, boolean pmexpDateMandatoryBl,
			boolean pmauthNoMandatoryBl, boolean pmgiftCertPromptBl, boolean pmvoucherPromptBl,
			boolean pmaccountPromptBl, String pminvoiceTextTxN, boolean pmtransmitCcbl, boolean pmtransmitDcbl,
			boolean pmcreditCardBl, short pmadditionalPrintCopiesIn, boolean pmvalidFromAndIssueNoMandatoryBl,
			Integer pmnonSalesAccountIdN, Integer pmsurchargeStockItemIdN, Double pmsurchargeAmountMnN,
			Double pmsurchargePercentFlN, boolean pmquickPayBl, Set<TPyPayment> TPyPayments,
			Set<TC3custCreditCard> TC3custCreditCards, Set<TPpPaymentProvider> TPpPaymentProviders,
			Set<TPppopayment> TPppopayments, Set<TSoStore> TSoStores) {
		this.pmpaymentMethodId = pmpaymentMethodId;
		this.TGlaccount = TGlaccount;
		this.pmpaymentMethodTx = pmpaymentMethodTx;
		this.pmccpromptBl = pmccpromptBl;
		this.pmopenCashDrawerBl = pmopenCashDrawerBl;
		this.pmauthorizationRequiredBl = pmauthorizationRequiredBl;
		this.pmcustomerRequiredBl = pmcustomerRequiredBl;
		this.pmidrequiredBl = pmidrequiredBl;
		this.pmchqNoPromptBl = pmchqNoPromptBl;
		this.pmchqNoMandatoryBl = pmchqNoMandatoryBl;
		this.pmgiftCardPromptBl = pmgiftCardPromptBl;
		this.pmunavailableBl = pmunavailableBl;
		this.pmlastUpdatedDate = pmlastUpdatedDate;
		this.pmrequiredBl = pmrequiredBl;
		this.pmccrequiredOnFileBl = pmccrequiredOnFileBl;
		this.pmccprefixTxN = pmccprefixTxN;
		this.pmccallowedLenTxN = pmccallowedLenTxN;
		this.pmcreationDate = pmcreationDate;
		this.pmgraphicTxN = pmgraphicTxN;
		this.pmccnoMandatoryBl = pmccnoMandatoryBl;
		this.pmexpDateMandatoryBl = pmexpDateMandatoryBl;
		this.pmauthNoMandatoryBl = pmauthNoMandatoryBl;
		this.pmgiftCertPromptBl = pmgiftCertPromptBl;
		this.pmvoucherPromptBl = pmvoucherPromptBl;
		this.pmaccountPromptBl = pmaccountPromptBl;
		this.pminvoiceTextTxN = pminvoiceTextTxN;
		this.pmtransmitCcbl = pmtransmitCcbl;
		this.pmtransmitDcbl = pmtransmitDcbl;
		this.pmcreditCardBl = pmcreditCardBl;
		this.pmadditionalPrintCopiesIn = pmadditionalPrintCopiesIn;
		this.pmvalidFromAndIssueNoMandatoryBl = pmvalidFromAndIssueNoMandatoryBl;
		this.pmnonSalesAccountIdN = pmnonSalesAccountIdN;
		this.pmsurchargeStockItemIdN = pmsurchargeStockItemIdN;
		this.pmsurchargeAmountMnN = pmsurchargeAmountMnN;
		this.pmsurchargePercentFlN = pmsurchargePercentFlN;
		this.pmquickPayBl = pmquickPayBl;
		this.TPyPayments = TPyPayments;
		this.TC3custCreditCards = TC3custCreditCards;
		this.TPpPaymentProviders = TPpPaymentProviders;
		this.TPppopayments = TPppopayments;
		this.TSoStores = TSoStores;
	}

	@Id

	@Column(name = "PMPaymentMethodID", unique = true, nullable = false)
	public int getPmpaymentMethodId() {
		return this.pmpaymentMethodId;
	}

	public void setPmpaymentMethodId(int pmpaymentMethodId) {
		this.pmpaymentMethodId = pmpaymentMethodId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PMGLAccountID_N")
	public TGlaccount getTGlaccount() {
		return this.TGlaccount;
	}

	public void setTGlaccount(TGlaccount TGlaccount) {
		this.TGlaccount = TGlaccount;
	}

	@Column(name = "PMPaymentMethodTx", unique = true, nullable = false)
	public String getPmpaymentMethodTx() {
		return this.pmpaymentMethodTx;
	}

	public void setPmpaymentMethodTx(String pmpaymentMethodTx) {
		this.pmpaymentMethodTx = pmpaymentMethodTx;
	}

	@Column(name = "PMCCPromptBl", nullable = false)
	public boolean isPmccpromptBl() {
		return this.pmccpromptBl;
	}

	public void setPmccpromptBl(boolean pmccpromptBl) {
		this.pmccpromptBl = pmccpromptBl;
	}

	@Column(name = "PMOpenCashDrawerBl", nullable = false)
	public boolean isPmopenCashDrawerBl() {
		return this.pmopenCashDrawerBl;
	}

	public void setPmopenCashDrawerBl(boolean pmopenCashDrawerBl) {
		this.pmopenCashDrawerBl = pmopenCashDrawerBl;
	}

	@Column(name = "PMAuthorizationRequiredBl", nullable = false)
	public boolean isPmauthorizationRequiredBl() {
		return this.pmauthorizationRequiredBl;
	}

	public void setPmauthorizationRequiredBl(boolean pmauthorizationRequiredBl) {
		this.pmauthorizationRequiredBl = pmauthorizationRequiredBl;
	}

	@Column(name = "PMCustomerRequiredBl", nullable = false)
	public boolean isPmcustomerRequiredBl() {
		return this.pmcustomerRequiredBl;
	}

	public void setPmcustomerRequiredBl(boolean pmcustomerRequiredBl) {
		this.pmcustomerRequiredBl = pmcustomerRequiredBl;
	}

	@Column(name = "PMIDRequiredBl", nullable = false)
	public boolean isPmidrequiredBl() {
		return this.pmidrequiredBl;
	}

	public void setPmidrequiredBl(boolean pmidrequiredBl) {
		this.pmidrequiredBl = pmidrequiredBl;
	}

	@Column(name = "PMChqNoPromptBl", nullable = false)
	public boolean isPmchqNoPromptBl() {
		return this.pmchqNoPromptBl;
	}

	public void setPmchqNoPromptBl(boolean pmchqNoPromptBl) {
		this.pmchqNoPromptBl = pmchqNoPromptBl;
	}

	@Column(name = "PMChqNoMandatoryBl", nullable = false)
	public boolean isPmchqNoMandatoryBl() {
		return this.pmchqNoMandatoryBl;
	}

	public void setPmchqNoMandatoryBl(boolean pmchqNoMandatoryBl) {
		this.pmchqNoMandatoryBl = pmchqNoMandatoryBl;
	}

	@Column(name = "PMGiftCardPromptBl", nullable = false)
	public boolean isPmgiftCardPromptBl() {
		return this.pmgiftCardPromptBl;
	}

	public void setPmgiftCardPromptBl(boolean pmgiftCardPromptBl) {
		this.pmgiftCardPromptBl = pmgiftCardPromptBl;
	}

	@Column(name = "PMUnavailableBl", nullable = false)
	public boolean isPmunavailableBl() {
		return this.pmunavailableBl;
	}

	public void setPmunavailableBl(boolean pmunavailableBl) {
		this.pmunavailableBl = pmunavailableBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PMLastUpdatedDate", nullable = false, length = 23)
	public Date getPmlastUpdatedDate() {
		return this.pmlastUpdatedDate;
	}

	public void setPmlastUpdatedDate(Date pmlastUpdatedDate) {
		this.pmlastUpdatedDate = pmlastUpdatedDate;
	}

	@Column(name = "PMRequiredBl", nullable = false)
	public boolean isPmrequiredBl() {
		return this.pmrequiredBl;
	}

	public void setPmrequiredBl(boolean pmrequiredBl) {
		this.pmrequiredBl = pmrequiredBl;
	}

	@Column(name = "PMCCRequiredOnFileBl", nullable = false)
	public boolean isPmccrequiredOnFileBl() {
		return this.pmccrequiredOnFileBl;
	}

	public void setPmccrequiredOnFileBl(boolean pmccrequiredOnFileBl) {
		this.pmccrequiredOnFileBl = pmccrequiredOnFileBl;
	}

	@Column(name = "PMCCPrefixTx_N")
	public String getPmccprefixTxN() {
		return this.pmccprefixTxN;
	}

	public void setPmccprefixTxN(String pmccprefixTxN) {
		this.pmccprefixTxN = pmccprefixTxN;
	}

	@Column(name = "PMCCAllowedLenTx_N")
	public String getPmccallowedLenTxN() {
		return this.pmccallowedLenTxN;
	}

	public void setPmccallowedLenTxN(String pmccallowedLenTxN) {
		this.pmccallowedLenTxN = pmccallowedLenTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PMCreationDate", nullable = false, length = 23)
	public Date getPmcreationDate() {
		return this.pmcreationDate;
	}

	public void setPmcreationDate(Date pmcreationDate) {
		this.pmcreationDate = pmcreationDate;
	}

	@Column(name = "PMGraphicTx_N")
	public String getPmgraphicTxN() {
		return this.pmgraphicTxN;
	}

	public void setPmgraphicTxN(String pmgraphicTxN) {
		this.pmgraphicTxN = pmgraphicTxN;
	}

	@Column(name = "PMCCNoMandatoryBl", nullable = false)
	public boolean isPmccnoMandatoryBl() {
		return this.pmccnoMandatoryBl;
	}

	public void setPmccnoMandatoryBl(boolean pmccnoMandatoryBl) {
		this.pmccnoMandatoryBl = pmccnoMandatoryBl;
	}

	@Column(name = "PMExpDateMandatoryBl", nullable = false)
	public boolean isPmexpDateMandatoryBl() {
		return this.pmexpDateMandatoryBl;
	}

	public void setPmexpDateMandatoryBl(boolean pmexpDateMandatoryBl) {
		this.pmexpDateMandatoryBl = pmexpDateMandatoryBl;
	}

	@Column(name = "PMAuthNoMandatoryBl", nullable = false)
	public boolean isPmauthNoMandatoryBl() {
		return this.pmauthNoMandatoryBl;
	}

	public void setPmauthNoMandatoryBl(boolean pmauthNoMandatoryBl) {
		this.pmauthNoMandatoryBl = pmauthNoMandatoryBl;
	}

	@Column(name = "PMGiftCertPromptBl", nullable = false)
	public boolean isPmgiftCertPromptBl() {
		return this.pmgiftCertPromptBl;
	}

	public void setPmgiftCertPromptBl(boolean pmgiftCertPromptBl) {
		this.pmgiftCertPromptBl = pmgiftCertPromptBl;
	}

	@Column(name = "PMVoucherPromptBl", nullable = false)
	public boolean isPmvoucherPromptBl() {
		return this.pmvoucherPromptBl;
	}

	public void setPmvoucherPromptBl(boolean pmvoucherPromptBl) {
		this.pmvoucherPromptBl = pmvoucherPromptBl;
	}

	@Column(name = "PMAccountPromptBl", nullable = false)
	public boolean isPmaccountPromptBl() {
		return this.pmaccountPromptBl;
	}

	public void setPmaccountPromptBl(boolean pmaccountPromptBl) {
		this.pmaccountPromptBl = pmaccountPromptBl;
	}

	@Column(name = "PMInvoiceTextTx_N")
	public String getPminvoiceTextTxN() {
		return this.pminvoiceTextTxN;
	}

	public void setPminvoiceTextTxN(String pminvoiceTextTxN) {
		this.pminvoiceTextTxN = pminvoiceTextTxN;
	}

	@Column(name = "PMTransmitCCBl", nullable = false)
	public boolean isPmtransmitCcbl() {
		return this.pmtransmitCcbl;
	}

	public void setPmtransmitCcbl(boolean pmtransmitCcbl) {
		this.pmtransmitCcbl = pmtransmitCcbl;
	}

	@Column(name = "PMTransmitDCBl", nullable = false)
	public boolean isPmtransmitDcbl() {
		return this.pmtransmitDcbl;
	}

	public void setPmtransmitDcbl(boolean pmtransmitDcbl) {
		this.pmtransmitDcbl = pmtransmitDcbl;
	}

	@Column(name = "PMCreditCardBl", nullable = false)
	public boolean isPmcreditCardBl() {
		return this.pmcreditCardBl;
	}

	public void setPmcreditCardBl(boolean pmcreditCardBl) {
		this.pmcreditCardBl = pmcreditCardBl;
	}

	@Column(name = "PMAdditionalPrintCopiesIn", nullable = false)
	public short getPmadditionalPrintCopiesIn() {
		return this.pmadditionalPrintCopiesIn;
	}

	public void setPmadditionalPrintCopiesIn(short pmadditionalPrintCopiesIn) {
		this.pmadditionalPrintCopiesIn = pmadditionalPrintCopiesIn;
	}

	@Column(name = "PMValidFromAndIssueNoMandatoryBl", nullable = false)
	public boolean isPmvalidFromAndIssueNoMandatoryBl() {
		return this.pmvalidFromAndIssueNoMandatoryBl;
	}

	public void setPmvalidFromAndIssueNoMandatoryBl(boolean pmvalidFromAndIssueNoMandatoryBl) {
		this.pmvalidFromAndIssueNoMandatoryBl = pmvalidFromAndIssueNoMandatoryBl;
	}

	@Column(name = "PMNonSalesAccountID_N")
	public Integer getPmnonSalesAccountIdN() {
		return this.pmnonSalesAccountIdN;
	}

	public void setPmnonSalesAccountIdN(Integer pmnonSalesAccountIdN) {
		this.pmnonSalesAccountIdN = pmnonSalesAccountIdN;
	}

	@Column(name = "PMSurchargeStockItemID_N")
	public Integer getPmsurchargeStockItemIdN() {
		return this.pmsurchargeStockItemIdN;
	}

	public void setPmsurchargeStockItemIdN(Integer pmsurchargeStockItemIdN) {
		this.pmsurchargeStockItemIdN = pmsurchargeStockItemIdN;
	}

	@Column(name = "PMSurchargeAmountMn_N", precision = 53, scale = 0)
	public Double getPmsurchargeAmountMnN() {
		return this.pmsurchargeAmountMnN;
	}

	public void setPmsurchargeAmountMnN(Double pmsurchargeAmountMnN) {
		this.pmsurchargeAmountMnN = pmsurchargeAmountMnN;
	}

	@Column(name = "PMSurchargePercentFl_N", precision = 53, scale = 0)
	public Double getPmsurchargePercentFlN() {
		return this.pmsurchargePercentFlN;
	}

	public void setPmsurchargePercentFlN(Double pmsurchargePercentFlN) {
		this.pmsurchargePercentFlN = pmsurchargePercentFlN;
	}

	@Column(name = "PMQuickPayBl", nullable = false)
	public boolean isPmquickPayBl() {
		return this.pmquickPayBl;
	}

	public void setPmquickPayBl(boolean pmquickPayBl) {
		this.pmquickPayBl = pmquickPayBl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPmpaymentMethod")
	public Set<TPyPayment> getTPyPayments() {
		return this.TPyPayments;
	}

	public void setTPyPayments(Set<TPyPayment> TPyPayments) {
		this.TPyPayments = TPyPayments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPmpaymentMethod")
	public Set<TC3custCreditCard> getTC3custCreditCards() {
		return this.TC3custCreditCards;
	}

	public void setTC3custCreditCards(Set<TC3custCreditCard> TC3custCreditCards) {
		this.TC3custCreditCards = TC3custCreditCards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPmpaymentMethod")
	public Set<TPpPaymentProvider> getTPpPaymentProviders() {
		return this.TPpPaymentProviders;
	}

	public void setTPpPaymentProviders(Set<TPpPaymentProvider> TPpPaymentProviders) {
		this.TPpPaymentProviders = TPpPaymentProviders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPmpaymentMethod")
	public Set<TPppopayment> getTPppopayments() {
		return this.TPppopayments;
	}

	public void setTPppopayments(Set<TPppopayment> TPppopayments) {
		this.TPppopayments = TPppopayments;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZhStorePaymentMethod", joinColumns = {
			@JoinColumn(name = "ZhPaymentMethodID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZhStoreID", nullable = false, updatable = false) })
	public Set<TSoStore> getTSoStores() {
		return this.TSoStores;
	}

	public void setTSoStores(Set<TSoStore> TSoStores) {
		this.TSoStores = TSoStores;
	}

}
