package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TPnPcprinter generated by hbm2java
 */
@Entity
@Table(name = "T_PnPCPrinter", uniqueConstraints = @UniqueConstraint(columnNames = { "PnReportLayoutID", "PnPCID" }))
public class TPnPcprinter implements java.io.Serializable {

	private int pnPcprinterId;
	private TPcpc TPcpc;
	private int pnReportLayoutId;
	private String pnPrinterNameTx;

	public TPnPcprinter() {
	}

	public TPnPcprinter(int pnPcprinterId, TPcpc TPcpc, int pnReportLayoutId) {
		this.pnPcprinterId = pnPcprinterId;
		this.TPcpc = TPcpc;
		this.pnReportLayoutId = pnReportLayoutId;
	}

	public TPnPcprinter(int pnPcprinterId, TPcpc TPcpc, int pnReportLayoutId, String pnPrinterNameTx) {
		this.pnPcprinterId = pnPcprinterId;
		this.TPcpc = TPcpc;
		this.pnReportLayoutId = pnReportLayoutId;
		this.pnPrinterNameTx = pnPrinterNameTx;
	}

	@Id

	@Column(name = "PnPCPrinterID", unique = true, nullable = false)
	public int getPnPcprinterId() {
		return this.pnPcprinterId;
	}

	public void setPnPcprinterId(int pnPcprinterId) {
		this.pnPcprinterId = pnPcprinterId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PnPCID", nullable = false)
	public TPcpc getTPcpc() {
		return this.TPcpc;
	}

	public void setTPcpc(TPcpc TPcpc) {
		this.TPcpc = TPcpc;
	}

	@Column(name = "PnReportLayoutID", nullable = false)
	public int getPnReportLayoutId() {
		return this.pnReportLayoutId;
	}

	public void setPnReportLayoutId(int pnReportLayoutId) {
		this.pnReportLayoutId = pnReportLayoutId;
	}

	@Column(name = "PnPrinterNameTx")
	public String getPnPrinterNameTx() {
		return this.pnPrinterNameTx;
	}

	public void setPnPrinterNameTx(String pnPrinterNameTx) {
		this.pnPrinterNameTx = pnPrinterNameTx;
	}

}
