package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPppopayment generated by hbm2java
 */
@Entity
@Table(name = "T_PPPOPayment")
public class TPppopayment implements java.io.Serializable {

	private int pppopaymentId;
	private TPmpaymentMethod TPmpaymentMethod;
	private TPvPoinvoice TPvPoinvoice;
	private double ppamountMn;
	private short ppcurrencyId;
	private float ppexchangeRateFl;
	private Date pppaymentDate;
	private Date pplastUpdatedDate;
	private String pppaymentNumberTxN;
	private Integer ppaccountingPeriodIdN;

	public TPppopayment() {
	}

	public TPppopayment(int pppopaymentId, TPmpaymentMethod TPmpaymentMethod, TPvPoinvoice TPvPoinvoice,
			double ppamountMn, short ppcurrencyId, float ppexchangeRateFl, Date pppaymentDate, Date pplastUpdatedDate) {
		this.pppopaymentId = pppopaymentId;
		this.TPmpaymentMethod = TPmpaymentMethod;
		this.TPvPoinvoice = TPvPoinvoice;
		this.ppamountMn = ppamountMn;
		this.ppcurrencyId = ppcurrencyId;
		this.ppexchangeRateFl = ppexchangeRateFl;
		this.pppaymentDate = pppaymentDate;
		this.pplastUpdatedDate = pplastUpdatedDate;
	}

	public TPppopayment(int pppopaymentId, TPmpaymentMethod TPmpaymentMethod, TPvPoinvoice TPvPoinvoice,
			double ppamountMn, short ppcurrencyId, float ppexchangeRateFl, Date pppaymentDate, Date pplastUpdatedDate,
			String pppaymentNumberTxN, Integer ppaccountingPeriodIdN) {
		this.pppopaymentId = pppopaymentId;
		this.TPmpaymentMethod = TPmpaymentMethod;
		this.TPvPoinvoice = TPvPoinvoice;
		this.ppamountMn = ppamountMn;
		this.ppcurrencyId = ppcurrencyId;
		this.ppexchangeRateFl = ppexchangeRateFl;
		this.pppaymentDate = pppaymentDate;
		this.pplastUpdatedDate = pplastUpdatedDate;
		this.pppaymentNumberTxN = pppaymentNumberTxN;
		this.ppaccountingPeriodIdN = ppaccountingPeriodIdN;
	}

	@Id

	@Column(name = "PPPOPaymentID", unique = true, nullable = false)
	public int getPppopaymentId() {
		return this.pppopaymentId;
	}

	public void setPppopaymentId(int pppopaymentId) {
		this.pppopaymentId = pppopaymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PPPaymentMethodID", nullable = false)
	public TPmpaymentMethod getTPmpaymentMethod() {
		return this.TPmpaymentMethod;
	}

	public void setTPmpaymentMethod(TPmpaymentMethod TPmpaymentMethod) {
		this.TPmpaymentMethod = TPmpaymentMethod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PPPOInvoiceID", nullable = false)
	public TPvPoinvoice getTPvPoinvoice() {
		return this.TPvPoinvoice;
	}

	public void setTPvPoinvoice(TPvPoinvoice TPvPoinvoice) {
		this.TPvPoinvoice = TPvPoinvoice;
	}

	@Column(name = "PPAmountMn", nullable = false, precision = 53, scale = 0)
	public double getPpamountMn() {
		return this.ppamountMn;
	}

	public void setPpamountMn(double ppamountMn) {
		this.ppamountMn = ppamountMn;
	}

	@Column(name = "PPCurrencyID", nullable = false)
	public short getPpcurrencyId() {
		return this.ppcurrencyId;
	}

	public void setPpcurrencyId(short ppcurrencyId) {
		this.ppcurrencyId = ppcurrencyId;
	}

	@Column(name = "PPExchangeRateFl", nullable = false, precision = 24, scale = 0)
	public float getPpexchangeRateFl() {
		return this.ppexchangeRateFl;
	}

	public void setPpexchangeRateFl(float ppexchangeRateFl) {
		this.ppexchangeRateFl = ppexchangeRateFl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PPPaymentDate", nullable = false, length = 23)
	public Date getPppaymentDate() {
		return this.pppaymentDate;
	}

	public void setPppaymentDate(Date pppaymentDate) {
		this.pppaymentDate = pppaymentDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PPLastUpdatedDate", nullable = false, length = 23)
	public Date getPplastUpdatedDate() {
		return this.pplastUpdatedDate;
	}

	public void setPplastUpdatedDate(Date pplastUpdatedDate) {
		this.pplastUpdatedDate = pplastUpdatedDate;
	}

	@Column(name = "PPPaymentNumberTx_N")
	public String getPppaymentNumberTxN() {
		return this.pppaymentNumberTxN;
	}

	public void setPppaymentNumberTxN(String pppaymentNumberTxN) {
		this.pppaymentNumberTxN = pppaymentNumberTxN;
	}

	@Column(name = "PPAccountingPeriodID_N")
	public Integer getPpaccountingPeriodIdN() {
		return this.ppaccountingPeriodIdN;
	}

	public void setPpaccountingPeriodIdN(Integer ppaccountingPeriodIdN) {
		this.ppaccountingPeriodIdN = ppaccountingPeriodIdN;
	}

}
