package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TPqPackage generated by hbm2java
 */
@Entity
@Table(name = "T_PqPackage")
public class TPqPackage implements java.io.Serializable {

	private int pqPackageId;
	private TEqEquipment TEqEquipmentByPqParentEquipmentId;
	private TEqEquipment TEqEquipmentByPqChildEquipmentId;

	public TPqPackage() {
	}

	public TPqPackage(int pqPackageId, TEqEquipment TEqEquipmentByPqParentEquipmentId,
			TEqEquipment TEqEquipmentByPqChildEquipmentId) {
		this.pqPackageId = pqPackageId;
		this.TEqEquipmentByPqParentEquipmentId = TEqEquipmentByPqParentEquipmentId;
		this.TEqEquipmentByPqChildEquipmentId = TEqEquipmentByPqChildEquipmentId;
	}

	@Id

	@Column(name = "PqPackageID", unique = true, nullable = false)
	public int getPqPackageId() {
		return this.pqPackageId;
	}

	public void setPqPackageId(int pqPackageId) {
		this.pqPackageId = pqPackageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PqParentEquipmentID", nullable = false)
	public TEqEquipment getTEqEquipmentByPqParentEquipmentId() {
		return this.TEqEquipmentByPqParentEquipmentId;
	}

	public void setTEqEquipmentByPqParentEquipmentId(TEqEquipment TEqEquipmentByPqParentEquipmentId) {
		this.TEqEquipmentByPqParentEquipmentId = TEqEquipmentByPqParentEquipmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PqChildEquipmentID", nullable = false)
	public TEqEquipment getTEqEquipmentByPqChildEquipmentId() {
		return this.TEqEquipmentByPqChildEquipmentId;
	}

	public void setTEqEquipmentByPqChildEquipmentId(TEqEquipment TEqEquipmentByPqChildEquipmentId) {
		this.TEqEquipmentByPqChildEquipmentId = TEqEquipmentByPqChildEquipmentId;
	}

}
