package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TPrProfile generated by hbm2java
 */
@Entity
@Table(name = "T_PrProfile", uniqueConstraints = @UniqueConstraint(columnNames = { "PrCustID", "PrStockTypeID" }))
public class TPrProfile implements java.io.Serializable {

	private int prProfileId;
	private TEzSize TEzSize;
	private TStstockType TStstockType;
	private TCuCust TCuCust;
	private Date prLastUpdatedDate;
	private Date prCreationDate;
	private String prNotesTxN;

	public TPrProfile() {
	}

	public TPrProfile(int prProfileId, TStstockType TStstockType, TCuCust TCuCust, Date prLastUpdatedDate,
			Date prCreationDate) {
		this.prProfileId = prProfileId;
		this.TStstockType = TStstockType;
		this.TCuCust = TCuCust;
		this.prLastUpdatedDate = prLastUpdatedDate;
		this.prCreationDate = prCreationDate;
	}

	public TPrProfile(int prProfileId, TEzSize TEzSize, TStstockType TStstockType, TCuCust TCuCust,
			Date prLastUpdatedDate, Date prCreationDate, String prNotesTxN) {
		this.prProfileId = prProfileId;
		this.TEzSize = TEzSize;
		this.TStstockType = TStstockType;
		this.TCuCust = TCuCust;
		this.prLastUpdatedDate = prLastUpdatedDate;
		this.prCreationDate = prCreationDate;
		this.prNotesTxN = prNotesTxN;
	}

	@Id

	@Column(name = "PrProfileID", unique = true, nullable = false)
	public int getPrProfileId() {
		return this.prProfileId;
	}

	public void setPrProfileId(int prProfileId) {
		this.prProfileId = prProfileId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PrSizeID_N")
	public TEzSize getTEzSize() {
		return this.TEzSize;
	}

	public void setTEzSize(TEzSize TEzSize) {
		this.TEzSize = TEzSize;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PrStockTypeID", nullable = false)
	public TStstockType getTStstockType() {
		return this.TStstockType;
	}

	public void setTStstockType(TStstockType TStstockType) {
		this.TStstockType = TStstockType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PrCustID", nullable = false)
	public TCuCust getTCuCust() {
		return this.TCuCust;
	}

	public void setTCuCust(TCuCust TCuCust) {
		this.TCuCust = TCuCust;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PrLastUpdatedDate", nullable = false, length = 23)
	public Date getPrLastUpdatedDate() {
		return this.prLastUpdatedDate;
	}

	public void setPrLastUpdatedDate(Date prLastUpdatedDate) {
		this.prLastUpdatedDate = prLastUpdatedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PrCreationDate", nullable = false, length = 23)
	public Date getPrCreationDate() {
		return this.prCreationDate;
	}

	public void setPrCreationDate(Date prCreationDate) {
		this.prCreationDate = prCreationDate;
	}

	@Column(name = "PrNotesTx_N")
	public String getPrNotesTxN() {
		return this.prNotesTxN;
	}

	public void setPrNotesTxN(String prNotesTxN) {
		this.prNotesTxN = prNotesTxN;
	}

}
