package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TPsPaymentProviderSettings generated by hbm2java
 */
@Entity
@Table(name = "T_PsPaymentProviderSettings")
public class TPsPaymentProviderSettings implements java.io.Serializable {

	private int psPaymentProviderSettingId;
	private TPpPaymentProvider TPpPaymentProvider;
	private String psSettingName;
	private String psSettingValue;

	public TPsPaymentProviderSettings() {
	}

	public TPsPaymentProviderSettings(int psPaymentProviderSettingId, TPpPaymentProvider TPpPaymentProvider,
			String psSettingName, String psSettingValue) {
		this.psPaymentProviderSettingId = psPaymentProviderSettingId;
		this.TPpPaymentProvider = TPpPaymentProvider;
		this.psSettingName = psSettingName;
		this.psSettingValue = psSettingValue;
	}

	@Id

	@Column(name = "PsPaymentProviderSettingId", unique = true, nullable = false)
	public int getPsPaymentProviderSettingId() {
		return this.psPaymentProviderSettingId;
	}

	public void setPsPaymentProviderSettingId(int psPaymentProviderSettingId) {
		this.psPaymentProviderSettingId = psPaymentProviderSettingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PsPaymentProviderId", nullable = false)
	public TPpPaymentProvider getTPpPaymentProvider() {
		return this.TPpPaymentProvider;
	}

	public void setTPpPaymentProvider(TPpPaymentProvider TPpPaymentProvider) {
		this.TPpPaymentProvider = TPpPaymentProvider;
	}

	@Column(name = "PsSettingName", nullable = false, length = 200)
	public String getPsSettingName() {
		return this.psSettingName;
	}

	public void setPsSettingName(String psSettingName) {
		this.psSettingName = psSettingName;
	}

	@Column(name = "PsSettingValue", nullable = false, length = 5000)
	public String getPsSettingValue() {
		return this.psSettingValue;
	}

	public void setPsSettingValue(String psSettingValue) {
		this.psSettingValue = psSettingValue;
	}

}
