package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPvPoinvoice generated by hbm2java
 */
@Entity
@Table(name = "T_PvPOInvoice")
public class TPvPoinvoice implements java.io.Serializable {

	private int pvPoinvoiceId;
	private TEmEmp TEmEmp;
	private TPopo TPopo;
	private String pvInvoiceNoTx;
	private double pvSubTotalMn;
	private double pvTaxMn;
	private double pvFreightMn;
	private short pvCurrencyId;
	private float pvExchangeRateFl;
	private Date pvInvoiceDate;
	private Date pvLastUpdatedDate;
	private String pvCommentsTxN;
	private Date pvCreationDate;
	private Integer pvAccountingPeriodIdN;
	private Date pvPaymentDueDate;
	private Set<TPppopayment> TPppopayments = new HashSet<TPppopayment>(0);

	public TPvPoinvoice() {
	}

	public TPvPoinvoice(int pvPoinvoiceId, TEmEmp TEmEmp, TPopo TPopo, String pvInvoiceNoTx, double pvSubTotalMn,
			double pvTaxMn, double pvFreightMn, short pvCurrencyId, float pvExchangeRateFl, Date pvInvoiceDate,
			Date pvLastUpdatedDate, Date pvCreationDate, Date pvPaymentDueDate) {
		this.pvPoinvoiceId = pvPoinvoiceId;
		this.TEmEmp = TEmEmp;
		this.TPopo = TPopo;
		this.pvInvoiceNoTx = pvInvoiceNoTx;
		this.pvSubTotalMn = pvSubTotalMn;
		this.pvTaxMn = pvTaxMn;
		this.pvFreightMn = pvFreightMn;
		this.pvCurrencyId = pvCurrencyId;
		this.pvExchangeRateFl = pvExchangeRateFl;
		this.pvInvoiceDate = pvInvoiceDate;
		this.pvLastUpdatedDate = pvLastUpdatedDate;
		this.pvCreationDate = pvCreationDate;
		this.pvPaymentDueDate = pvPaymentDueDate;
	}

	public TPvPoinvoice(int pvPoinvoiceId, TEmEmp TEmEmp, TPopo TPopo, String pvInvoiceNoTx, double pvSubTotalMn,
			double pvTaxMn, double pvFreightMn, short pvCurrencyId, float pvExchangeRateFl, Date pvInvoiceDate,
			Date pvLastUpdatedDate, String pvCommentsTxN, Date pvCreationDate, Integer pvAccountingPeriodIdN,
			Date pvPaymentDueDate, Set<TPppopayment> TPppopayments) {
		this.pvPoinvoiceId = pvPoinvoiceId;
		this.TEmEmp = TEmEmp;
		this.TPopo = TPopo;
		this.pvInvoiceNoTx = pvInvoiceNoTx;
		this.pvSubTotalMn = pvSubTotalMn;
		this.pvTaxMn = pvTaxMn;
		this.pvFreightMn = pvFreightMn;
		this.pvCurrencyId = pvCurrencyId;
		this.pvExchangeRateFl = pvExchangeRateFl;
		this.pvInvoiceDate = pvInvoiceDate;
		this.pvLastUpdatedDate = pvLastUpdatedDate;
		this.pvCommentsTxN = pvCommentsTxN;
		this.pvCreationDate = pvCreationDate;
		this.pvAccountingPeriodIdN = pvAccountingPeriodIdN;
		this.pvPaymentDueDate = pvPaymentDueDate;
		this.TPppopayments = TPppopayments;
	}

	@Id

	@Column(name = "PvPOInvoiceID", unique = true, nullable = false)
	public int getPvPoinvoiceId() {
		return this.pvPoinvoiceId;
	}

	public void setPvPoinvoiceId(int pvPoinvoiceId) {
		this.pvPoinvoiceId = pvPoinvoiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PvEmpID", nullable = false)
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PvPOID", nullable = false)
	public TPopo getTPopo() {
		return this.TPopo;
	}

	public void setTPopo(TPopo TPopo) {
		this.TPopo = TPopo;
	}

	@Column(name = "PvInvoiceNoTx", nullable = false)
	public String getPvInvoiceNoTx() {
		return this.pvInvoiceNoTx;
	}

	public void setPvInvoiceNoTx(String pvInvoiceNoTx) {
		this.pvInvoiceNoTx = pvInvoiceNoTx;
	}

	@Column(name = "PvSubTotalMn", nullable = false, precision = 53, scale = 0)
	public double getPvSubTotalMn() {
		return this.pvSubTotalMn;
	}

	public void setPvSubTotalMn(double pvSubTotalMn) {
		this.pvSubTotalMn = pvSubTotalMn;
	}

	@Column(name = "PvTaxMn", nullable = false, precision = 53, scale = 0)
	public double getPvTaxMn() {
		return this.pvTaxMn;
	}

	public void setPvTaxMn(double pvTaxMn) {
		this.pvTaxMn = pvTaxMn;
	}

	@Column(name = "PvFreightMn", nullable = false, precision = 53, scale = 0)
	public double getPvFreightMn() {
		return this.pvFreightMn;
	}

	public void setPvFreightMn(double pvFreightMn) {
		this.pvFreightMn = pvFreightMn;
	}

	@Column(name = "PvCurrencyID", nullable = false)
	public short getPvCurrencyId() {
		return this.pvCurrencyId;
	}

	public void setPvCurrencyId(short pvCurrencyId) {
		this.pvCurrencyId = pvCurrencyId;
	}

	@Column(name = "PvExchangeRateFl", nullable = false, precision = 24, scale = 0)
	public float getPvExchangeRateFl() {
		return this.pvExchangeRateFl;
	}

	public void setPvExchangeRateFl(float pvExchangeRateFl) {
		this.pvExchangeRateFl = pvExchangeRateFl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PvInvoiceDate", nullable = false, length = 23)
	public Date getPvInvoiceDate() {
		return this.pvInvoiceDate;
	}

	public void setPvInvoiceDate(Date pvInvoiceDate) {
		this.pvInvoiceDate = pvInvoiceDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PvLastUpdatedDate", nullable = false, length = 23)
	public Date getPvLastUpdatedDate() {
		return this.pvLastUpdatedDate;
	}

	public void setPvLastUpdatedDate(Date pvLastUpdatedDate) {
		this.pvLastUpdatedDate = pvLastUpdatedDate;
	}

	@Column(name = "PvCommentsTx_N")
	public String getPvCommentsTxN() {
		return this.pvCommentsTxN;
	}

	public void setPvCommentsTxN(String pvCommentsTxN) {
		this.pvCommentsTxN = pvCommentsTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PvCreationDate", nullable = false, length = 23)
	public Date getPvCreationDate() {
		return this.pvCreationDate;
	}

	public void setPvCreationDate(Date pvCreationDate) {
		this.pvCreationDate = pvCreationDate;
	}

	@Column(name = "PvAccountingPeriodID_N")
	public Integer getPvAccountingPeriodIdN() {
		return this.pvAccountingPeriodIdN;
	}

	public void setPvAccountingPeriodIdN(Integer pvAccountingPeriodIdN) {
		this.pvAccountingPeriodIdN = pvAccountingPeriodIdN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PvPaymentDueDate", nullable = false, length = 23)
	public Date getPvPaymentDueDate() {
		return this.pvPaymentDueDate;
	}

	public void setPvPaymentDueDate(Date pvPaymentDueDate) {
		this.pvPaymentDueDate = pvPaymentDueDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPvPoinvoice")
	public Set<TPppopayment> getTPppopayments() {
		return this.TPppopayments;
	}

	public void setTPppopayments(Set<TPppopayment> TPppopayments) {
		this.TPppopayments = TPppopayments;
	}

}
