package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPyPayment generated by hbm2java
 */
@Entity
@Table(name = "T_PyPayment")
public class TPyPayment implements java.io.Serializable {

	private int pyPaymentId;
	private TGcgiftCert TGcgiftCert;
	private TAnClosing TAnClosing;
	private TInInvoice TInInvoice;
	private TGdGiftCard TGdGiftCard;
	private TApaccountingPeriod TApaccountingPeriod;
	private TPpPaymentProvider TPpPaymentProvider;
	private TAcAccount TAcAccount;
	private TPmpaymentMethod TPmpaymentMethod;
	private TVoVoucher TVoVoucher;
	private short pyPaymentTypeId;
	private double pyAmountMn;
	private short pyCurrencyId;
	private float pyExchangeRateFl;
	private Date pyPaymentDate;
	private String pyPaymentNumberTxN;
	private String pyCreditCardNoTxN;
	private String pyExpiryDateTxN;
	private String pyAuthCodeTxN;
	private Date pyLastUpdatedDate;
	private Boolean pyTransmittedBl;
	private String pyTroutDtxN;
	private String pyReferenceTxN;
	private String pyTicketNoTxN;
	private String pyCvv2codeTxN;
	private String pyGateWayResponseTxN;
	private String pyTransactionNotesTxN;
	private Integer pyOnlineProcessorId;
	private double pyCardBalanceMn;
	private Integer pyEntryModeInN;
	private Set<TAyAccountPayment> TAyAccountPayments = new HashSet<TAyAccountPayment>(0);

	public TPyPayment() {
	}

	public TPyPayment(int pyPaymentId, TInInvoice TInInvoice, TPmpaymentMethod TPmpaymentMethod, short pyPaymentTypeId,
			double pyAmountMn, short pyCurrencyId, float pyExchangeRateFl, Date pyPaymentDate, Date pyLastUpdatedDate,
			double pyCardBalanceMn) {
		this.pyPaymentId = pyPaymentId;
		this.TInInvoice = TInInvoice;
		this.TPmpaymentMethod = TPmpaymentMethod;
		this.pyPaymentTypeId = pyPaymentTypeId;
		this.pyAmountMn = pyAmountMn;
		this.pyCurrencyId = pyCurrencyId;
		this.pyExchangeRateFl = pyExchangeRateFl;
		this.pyPaymentDate = pyPaymentDate;
		this.pyLastUpdatedDate = pyLastUpdatedDate;
		this.pyCardBalanceMn = pyCardBalanceMn;
	}

	public TPyPayment(int pyPaymentId, TGcgiftCert TGcgiftCert, TAnClosing TAnClosing, TInInvoice TInInvoice,
			TGdGiftCard TGdGiftCard, TApaccountingPeriod TApaccountingPeriod, TPpPaymentProvider TPpPaymentProvider,
			TAcAccount TAcAccount, TPmpaymentMethod TPmpaymentMethod, TVoVoucher TVoVoucher, short pyPaymentTypeId,
			double pyAmountMn, short pyCurrencyId, float pyExchangeRateFl, Date pyPaymentDate,
			String pyPaymentNumberTxN, String pyCreditCardNoTxN, String pyExpiryDateTxN,
			String pyAuthCodeTxN, Date pyLastUpdatedDate, Boolean pyTransmittedBl, String pyTroutDtxN,
			String pyReferenceTxN, String pyTicketNoTxN, String pyCvv2codeTxN, String pyGateWayResponseTxN,
			String pyTransactionNotesTxN, Integer pyOnlineProcessorId, double pyCardBalanceMn, Integer pyEntryModeInN,
			Set<TAyAccountPayment> TAyAccountPayments) {
		this.pyPaymentId = pyPaymentId;
		this.TGcgiftCert = TGcgiftCert;
		this.TAnClosing = TAnClosing;
		this.TInInvoice = TInInvoice;
		this.TGdGiftCard = TGdGiftCard;
		this.TApaccountingPeriod = TApaccountingPeriod;
		this.TPpPaymentProvider = TPpPaymentProvider;
		this.TAcAccount = TAcAccount;
		this.TPmpaymentMethod = TPmpaymentMethod;
		this.TVoVoucher = TVoVoucher;
		this.pyPaymentTypeId = pyPaymentTypeId;
		this.pyAmountMn = pyAmountMn;
		this.pyCurrencyId = pyCurrencyId;
		this.pyExchangeRateFl = pyExchangeRateFl;
		this.pyPaymentDate = pyPaymentDate;
		this.pyPaymentNumberTxN = pyPaymentNumberTxN;
		this.pyCreditCardNoTxN = pyCreditCardNoTxN;
		this.pyExpiryDateTxN = pyExpiryDateTxN;
		this.pyAuthCodeTxN = pyAuthCodeTxN;
		this.pyLastUpdatedDate = pyLastUpdatedDate;
		this.pyTransmittedBl = pyTransmittedBl;
		this.pyTroutDtxN = pyTroutDtxN;
		this.pyReferenceTxN = pyReferenceTxN;
		this.pyTicketNoTxN = pyTicketNoTxN;
		this.pyCvv2codeTxN = pyCvv2codeTxN;
		this.pyGateWayResponseTxN = pyGateWayResponseTxN;
		this.pyTransactionNotesTxN = pyTransactionNotesTxN;
		this.pyOnlineProcessorId = pyOnlineProcessorId;
		this.pyCardBalanceMn = pyCardBalanceMn;
		this.pyEntryModeInN = pyEntryModeInN;
		this.TAyAccountPayments = TAyAccountPayments;
	}

	@Id

	@Column(name = "PyPaymentID", unique = true, nullable = false)
	public int getPyPaymentId() {
		return this.pyPaymentId;
	}

	public void setPyPaymentId(int pyPaymentId) {
		this.pyPaymentId = pyPaymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PyGiftCertID_N")
	public TGcgiftCert getTGcgiftCert() {
		return this.TGcgiftCert;
	}

	public void setTGcgiftCert(TGcgiftCert TGcgiftCert) {
		this.TGcgiftCert = TGcgiftCert;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PyClosingID_N")
	public TAnClosing getTAnClosing() {
		return this.TAnClosing;
	}

	public void setTAnClosing(TAnClosing TAnClosing) {
		this.TAnClosing = TAnClosing;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PyInvoiceID", nullable = false)
	public TInInvoice getTInInvoice() {
		return this.TInInvoice;
	}

	public void setTInInvoice(TInInvoice TInInvoice) {
		this.TInInvoice = TInInvoice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PyGiftCardID_N")
	public TGdGiftCard getTGdGiftCard() {
		return this.TGdGiftCard;
	}

	public void setTGdGiftCard(TGdGiftCard TGdGiftCard) {
		this.TGdGiftCard = TGdGiftCard;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PyAccountingPeriodID_N")
	public TApaccountingPeriod getTApaccountingPeriod() {
		return this.TApaccountingPeriod;
	}

	public void setTApaccountingPeriod(TApaccountingPeriod TApaccountingPeriod) {
		this.TApaccountingPeriod = TApaccountingPeriod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PyPaymentProviderId_N")
	public TPpPaymentProvider getTPpPaymentProvider() {
		return this.TPpPaymentProvider;
	}

	public void setTPpPaymentProvider(TPpPaymentProvider TPpPaymentProvider) {
		this.TPpPaymentProvider = TPpPaymentProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PyAccountID_N")
	public TAcAccount getTAcAccount() {
		return this.TAcAccount;
	}

	public void setTAcAccount(TAcAccount TAcAccount) {
		this.TAcAccount = TAcAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PyPaymentMethodID", nullable = false)
	public TPmpaymentMethod getTPmpaymentMethod() {
		return this.TPmpaymentMethod;
	}

	public void setTPmpaymentMethod(TPmpaymentMethod TPmpaymentMethod) {
		this.TPmpaymentMethod = TPmpaymentMethod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PyVoucherID_N")
	public TVoVoucher getTVoVoucher() {
		return this.TVoVoucher;
	}

	public void setTVoVoucher(TVoVoucher TVoVoucher) {
		this.TVoVoucher = TVoVoucher;
	}

	@Column(name = "PyPaymentTypeID", nullable = false)
	public short getPyPaymentTypeId() {
		return this.pyPaymentTypeId;
	}

	public void setPyPaymentTypeId(short pyPaymentTypeId) {
		this.pyPaymentTypeId = pyPaymentTypeId;
	}

	@Column(name = "PyAmountMn", nullable = false, precision = 53, scale = 0)
	public double getPyAmountMn() {
		return this.pyAmountMn;
	}

	public void setPyAmountMn(double pyAmountMn) {
		this.pyAmountMn = pyAmountMn;
	}

	@Column(name = "PyCurrencyID", nullable = false)
	public short getPyCurrencyId() {
		return this.pyCurrencyId;
	}

	public void setPyCurrencyId(short pyCurrencyId) {
		this.pyCurrencyId = pyCurrencyId;
	}

	@Column(name = "PyExchangeRateFl", nullable = false, precision = 24, scale = 0)
	public float getPyExchangeRateFl() {
		return this.pyExchangeRateFl;
	}

	public void setPyExchangeRateFl(float pyExchangeRateFl) {
		this.pyExchangeRateFl = pyExchangeRateFl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PyPaymentDate", nullable = false, length = 23)
	public Date getPyPaymentDate() {
		return this.pyPaymentDate;
	}

	public void setPyPaymentDate(Date pyPaymentDate) {
		this.pyPaymentDate = pyPaymentDate;
	}

	@Column(name = "PyPaymentNumberTx_N")
	public String getPyPaymentNumberTxN() {
		return this.pyPaymentNumberTxN;
	}

	public void setPyPaymentNumberTxN(String pyPaymentNumberTxN) {
		this.pyPaymentNumberTxN = pyPaymentNumberTxN;
	}

	@Column(name = "PyCreditCardNoTx_N")
	public String getPyCreditCardNoTxN() {
		return this.pyCreditCardNoTxN;
	}

	public void setPyCreditCardNoTxN(String pyCreditCardNoTxN) {
		this.pyCreditCardNoTxN = pyCreditCardNoTxN;
	}

	@Column(name = "PyExpiryDateTx_N")
	public String getPyExpiryDateTxN() {
		return this.pyExpiryDateTxN;
	}

	public void setPyExpiryDateTxN(String pyExpiryDateTxN) {
		this.pyExpiryDateTxN = pyExpiryDateTxN;
	}

	@Column(name = "PyAuthCodeTx_N")
	public String getPyAuthCodeTxN() {
		return this.pyAuthCodeTxN;
	}

	public void setPyAuthCodeTxN(String pyAuthCodeTxN) {
		this.pyAuthCodeTxN = pyAuthCodeTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PyLastUpdatedDate", nullable = false, length = 23)
	public Date getPyLastUpdatedDate() {
		return this.pyLastUpdatedDate;
	}

	public void setPyLastUpdatedDate(Date pyLastUpdatedDate) {
		this.pyLastUpdatedDate = pyLastUpdatedDate;
	}

	@Column(name = "PyTransmittedBl")
	public Boolean getPyTransmittedBl() {
		return this.pyTransmittedBl;
	}

	public void setPyTransmittedBl(Boolean pyTransmittedBl) {
		this.pyTransmittedBl = pyTransmittedBl;
	}

	@Column(name = "PyTroutDTx_N")
	public String getPyTroutDtxN() {
		return this.pyTroutDtxN;
	}

	public void setPyTroutDtxN(String pyTroutDtxN) {
		this.pyTroutDtxN = pyTroutDtxN;
	}

	@Column(name = "PyReferenceTx_N")
	public String getPyReferenceTxN() {
		return this.pyReferenceTxN;
	}

	public void setPyReferenceTxN(String pyReferenceTxN) {
		this.pyReferenceTxN = pyReferenceTxN;
	}

	@Column(name = "PyTicketNoTx_N")
	public String getPyTicketNoTxN() {
		return this.pyTicketNoTxN;
	}

	public void setPyTicketNoTxN(String pyTicketNoTxN) {
		this.pyTicketNoTxN = pyTicketNoTxN;
	}

	@Column(name = "PyCVV2CodeTx_N", length = 100)
	public String getPyCvv2codeTxN() {
		return this.pyCvv2codeTxN;
	}

	public void setPyCvv2codeTxN(String pyCvv2codeTxN) {
		this.pyCvv2codeTxN = pyCvv2codeTxN;
	}

	@Column(name = "PyGateWayResponseTx_N")
	public String getPyGateWayResponseTxN() {
		return this.pyGateWayResponseTxN;
	}

	public void setPyGateWayResponseTxN(String pyGateWayResponseTxN) {
		this.pyGateWayResponseTxN = pyGateWayResponseTxN;
	}

	@Column(name = "PyTransactionNotesTx_N", length = 512)
	public String getPyTransactionNotesTxN() {
		return this.pyTransactionNotesTxN;
	}

	public void setPyTransactionNotesTxN(String pyTransactionNotesTxN) {
		this.pyTransactionNotesTxN = pyTransactionNotesTxN;
	}

	@Column(name = "PyOnlineProcessorId")
	public Integer getPyOnlineProcessorId() {
		return this.pyOnlineProcessorId;
	}

	public void setPyOnlineProcessorId(Integer pyOnlineProcessorId) {
		this.pyOnlineProcessorId = pyOnlineProcessorId;
	}

	@Column(name = "PyCardBalanceMn", nullable = false, precision = 53, scale = 0)
	public double getPyCardBalanceMn() {
		return this.pyCardBalanceMn;
	}

	public void setPyCardBalanceMn(double pyCardBalanceMn) {
		this.pyCardBalanceMn = pyCardBalanceMn;
	}

	@Column(name = "PyEntryModeIn_N")
	public Integer getPyEntryModeInN() {
		return this.pyEntryModeInN;
	}

	public void setPyEntryModeInN(Integer pyEntryModeInN) {
		this.pyEntryModeInN = pyEntryModeInN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPyPayment")
	public Set<TAyAccountPayment> getTAyAccountPayments() {
		return this.TAyAccountPayments;
	}

	public void setTAyAccountPayments(Set<TAyAccountPayment> TAyAccountPayments) {
		this.TAyAccountPayments = TAyAccountPayments;
	}

}
