package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TPzPaperSize generated by hbm2java
 */
@Entity
@Table(name = "T_PzPaperSize", uniqueConstraints = @UniqueConstraint(columnNames = "PzPaperSizeTx"))
public class TPzPaperSize implements java.io.Serializable {

	private int pzPaperSizeId;
	private String pzPaperSizeTx;
	private int pzWidthIn;
	private int pzHeightIn;
	private boolean pzUnavailable;
	private Date pzCreationDate;
	private Date pzLastUpdatedDate;
	private boolean pzRequiredBl;
	private int pzTypeIn;
	private int pzLabelGapIn;
	private Set<TRlreportLayout> TRlreportLayouts = new HashSet<TRlreportLayout>(0);

	public TPzPaperSize() {
	}

	public TPzPaperSize(int pzPaperSizeId, String pzPaperSizeTx, int pzWidthIn, int pzHeightIn,
			boolean pzUnavailable, Date pzCreationDate, Date pzLastUpdatedDate, boolean pzRequiredBl, int pzTypeIn,
			int pzLabelGapIn) {
		this.pzPaperSizeId = pzPaperSizeId;
		this.pzPaperSizeTx = pzPaperSizeTx;
		this.pzWidthIn = pzWidthIn;
		this.pzHeightIn = pzHeightIn;
		this.pzUnavailable = pzUnavailable;
		this.pzCreationDate = pzCreationDate;
		this.pzLastUpdatedDate = pzLastUpdatedDate;
		this.pzRequiredBl = pzRequiredBl;
		this.pzTypeIn = pzTypeIn;
		this.pzLabelGapIn = pzLabelGapIn;
	}

	public TPzPaperSize(int pzPaperSizeId, String pzPaperSizeTx, int pzWidthIn, int pzHeightIn,
			boolean pzUnavailable, Date pzCreationDate, Date pzLastUpdatedDate, boolean pzRequiredBl, int pzTypeIn,
			int pzLabelGapIn, Set<TRlreportLayout> TRlreportLayouts) {
		this.pzPaperSizeId = pzPaperSizeId;
		this.pzPaperSizeTx = pzPaperSizeTx;
		this.pzWidthIn = pzWidthIn;
		this.pzHeightIn = pzHeightIn;
		this.pzUnavailable = pzUnavailable;
		this.pzCreationDate = pzCreationDate;
		this.pzLastUpdatedDate = pzLastUpdatedDate;
		this.pzRequiredBl = pzRequiredBl;
		this.pzTypeIn = pzTypeIn;
		this.pzLabelGapIn = pzLabelGapIn;
		this.TRlreportLayouts = TRlreportLayouts;
	}

	@Id

	@Column(name = "PzPaperSizeID", unique = true, nullable = false)
	public int getPzPaperSizeId() {
		return this.pzPaperSizeId;
	}

	public void setPzPaperSizeId(int pzPaperSizeId) {
		this.pzPaperSizeId = pzPaperSizeId;
	}

	@Column(name = "PzPaperSizeTx", unique = true, nullable = false)
	public String getPzPaperSizeTx() {
		return this.pzPaperSizeTx;
	}

	public void setPzPaperSizeTx(String pzPaperSizeTx) {
		this.pzPaperSizeTx = pzPaperSizeTx;
	}

	@Column(name = "PzWidthIn", nullable = false)
	public int getPzWidthIn() {
		return this.pzWidthIn;
	}

	public void setPzWidthIn(int pzWidthIn) {
		this.pzWidthIn = pzWidthIn;
	}

	@Column(name = "PzHeightIn", nullable = false)
	public int getPzHeightIn() {
		return this.pzHeightIn;
	}

	public void setPzHeightIn(int pzHeightIn) {
		this.pzHeightIn = pzHeightIn;
	}

	@Column(name = "PzUnavailable", nullable = false)
	public boolean isPzUnavailable() {
		return this.pzUnavailable;
	}

	public void setPzUnavailable(boolean pzUnavailable) {
		this.pzUnavailable = pzUnavailable;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PzCreationDate", nullable = false, length = 23)
	public Date getPzCreationDate() {
		return this.pzCreationDate;
	}

	public void setPzCreationDate(Date pzCreationDate) {
		this.pzCreationDate = pzCreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PzLastUpdatedDate", nullable = false, length = 23)
	public Date getPzLastUpdatedDate() {
		return this.pzLastUpdatedDate;
	}

	public void setPzLastUpdatedDate(Date pzLastUpdatedDate) {
		this.pzLastUpdatedDate = pzLastUpdatedDate;
	}

	@Column(name = "PzRequiredBl", nullable = false)
	public boolean isPzRequiredBl() {
		return this.pzRequiredBl;
	}

	public void setPzRequiredBl(boolean pzRequiredBl) {
		this.pzRequiredBl = pzRequiredBl;
	}

	@Column(name = "PzTypeIn", nullable = false)
	public int getPzTypeIn() {
		return this.pzTypeIn;
	}

	public void setPzTypeIn(int pzTypeIn) {
		this.pzTypeIn = pzTypeIn;
	}

	@Column(name = "PzLabelGapIn", nullable = false)
	public int getPzLabelGapIn() {
		return this.pzLabelGapIn;
	}

	public void setPzLabelGapIn(int pzLabelGapIn) {
		this.pzLabelGapIn = pzLabelGapIn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPzPaperSize")
	public Set<TRlreportLayout> getTRlreportLayouts() {
		return this.TRlreportLayouts;
	}

	public void setTRlreportLayouts(Set<TRlreportLayout> TRlreportLayouts) {
		this.TRlreportLayouts = TRlreportLayouts;
	}

}
