package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TQ2internalExamSt generated by hbm2java
 */
@Entity
@Table(name = "T_Q2InternalExamSt", uniqueConstraints = @UniqueConstraint(columnNames = "Q2InternalExamStTx"))
public class TQ2internalExamSt implements java.io.Serializable {

	private int q2internalExamStId;
	private String q2internalExamStTx;
	private Date q2creationDate;
	private Date q2lastUpdatedDate;
	private boolean q2unavailableBl;

	public TQ2internalExamSt() {
	}

	public TQ2internalExamSt(int q2internalExamStId, String q2internalExamStTx, Date q2creationDate,
			Date q2lastUpdatedDate, boolean q2unavailableBl) {
		this.q2internalExamStId = q2internalExamStId;
		this.q2internalExamStTx = q2internalExamStTx;
		this.q2creationDate = q2creationDate;
		this.q2lastUpdatedDate = q2lastUpdatedDate;
		this.q2unavailableBl = q2unavailableBl;
	}

	@Id

	@Column(name = "Q2InternalExamStID", unique = true, nullable = false)
	public int getQ2internalExamStId() {
		return this.q2internalExamStId;
	}

	public void setQ2internalExamStId(int q2internalExamStId) {
		this.q2internalExamStId = q2internalExamStId;
	}

	@Column(name = "Q2InternalExamStTx", unique = true, nullable = false)
	public String getQ2internalExamStTx() {
		return this.q2internalExamStTx;
	}

	public void setQ2internalExamStTx(String q2internalExamStTx) {
		this.q2internalExamStTx = q2internalExamStTx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Q2CreationDate", nullable = false, length = 23)
	public Date getQ2creationDate() {
		return this.q2creationDate;
	}

	public void setQ2creationDate(Date q2creationDate) {
		this.q2creationDate = q2creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Q2LastUpdatedDate", nullable = false, length = 23)
	public Date getQ2lastUpdatedDate() {
		return this.q2lastUpdatedDate;
	}

	public void setQ2lastUpdatedDate(Date q2lastUpdatedDate) {
		this.q2lastUpdatedDate = q2lastUpdatedDate;
	}

	@Column(name = "Q2UnavailableBl", nullable = false)
	public boolean isQ2unavailableBl() {
		return this.q2unavailableBl;
	}

	public void setQ2unavailableBl(boolean q2unavailableBl) {
		this.q2unavailableBl = q2unavailableBl;
	}

}
