package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TQiquoteItem generated by hbm2java
 */
@Entity
@Table(name = "T_QIQuoteItem")
public class TQiquoteItem implements java.io.Serializable {

	private int qiquoteItemId;
	private TC1custCourse TC1custCourse;
	private TStstockType TStstockType;
	private TQuQuote TQuQuote;
	private TPfProfitCenter TPfProfitCenter;
	private TSuSupplier TSuSupplier;
	private TDbdiscountBand TDbdiscountBand;
	private TCpCustTrip TCpCustTrip;
	private TRkRoomBooking TRkRoomBooking;
	private TSistockItem TSistockItem;
	private short qiqtyIn;
	private double qiunitPriceMn;
	private double qipriceMn;
	private double qitaxMn;
	private String qitaxBandIdsTx;
	private String qitaxRatesTx;
	private short qicurrencyId;
	private float qiexchangeRateFl;
	private Date qilastUpdatedDate;
	private String qistockNoTx;
	private String qistockItemTx;
	private String qistockTypeTx;
	private String qimanufacturerTx;
	private String qiprimaryColorTxN;
	private String qisecondaryColorTxN;
	private String qisizeTxN;
	private String qinotesTxN;
	private boolean qicourseRelatedBl;
	private boolean qitripRelatedBl;
	private Integer qiparentIdN;

	public TQiquoteItem() {
	}

	public TQiquoteItem(int qiquoteItemId, TStstockType TStstockType, TQuQuote TQuQuote,
			TPfProfitCenter TPfProfitCenter, TSuSupplier TSuSupplier, TSistockItem TSistockItem, short qiqtyIn,
			double qiunitPriceMn, double qipriceMn, double qitaxMn, String qitaxBandIdsTx,
			String qitaxRatesTx, short qicurrencyId, float qiexchangeRateFl, Date qilastUpdatedDate,
			String qistockNoTx, String qistockItemTx, String qistockTypeTx,
			String qimanufacturerTx, boolean qicourseRelatedBl, boolean qitripRelatedBl) {
		this.qiquoteItemId = qiquoteItemId;
		this.TStstockType = TStstockType;
		this.TQuQuote = TQuQuote;
		this.TPfProfitCenter = TPfProfitCenter;
		this.TSuSupplier = TSuSupplier;
		this.TSistockItem = TSistockItem;
		this.qiqtyIn = qiqtyIn;
		this.qiunitPriceMn = qiunitPriceMn;
		this.qipriceMn = qipriceMn;
		this.qitaxMn = qitaxMn;
		this.qitaxBandIdsTx = qitaxBandIdsTx;
		this.qitaxRatesTx = qitaxRatesTx;
		this.qicurrencyId = qicurrencyId;
		this.qiexchangeRateFl = qiexchangeRateFl;
		this.qilastUpdatedDate = qilastUpdatedDate;
		this.qistockNoTx = qistockNoTx;
		this.qistockItemTx = qistockItemTx;
		this.qistockTypeTx = qistockTypeTx;
		this.qimanufacturerTx = qimanufacturerTx;
		this.qicourseRelatedBl = qicourseRelatedBl;
		this.qitripRelatedBl = qitripRelatedBl;
	}

	public TQiquoteItem(int qiquoteItemId, TC1custCourse TC1custCourse, TStstockType TStstockType, TQuQuote TQuQuote,
			TPfProfitCenter TPfProfitCenter, TSuSupplier TSuSupplier, TDbdiscountBand TDbdiscountBand,
			TCpCustTrip TCpCustTrip, TRkRoomBooking TRkRoomBooking, TSistockItem TSistockItem, short qiqtyIn,
			double qiunitPriceMn, double qipriceMn, double qitaxMn, String qitaxBandIdsTx,
			String qitaxRatesTx, short qicurrencyId, float qiexchangeRateFl, Date qilastUpdatedDate,
			String qistockNoTx, String qistockItemTx, String qistockTypeTx,
			String qimanufacturerTx, String qiprimaryColorTxN, String qisecondaryColorTxN,
			String qisizeTxN, String qinotesTxN, boolean qicourseRelatedBl, boolean qitripRelatedBl,
			Integer qiparentIdN) {
		this.qiquoteItemId = qiquoteItemId;
		this.TC1custCourse = TC1custCourse;
		this.TStstockType = TStstockType;
		this.TQuQuote = TQuQuote;
		this.TPfProfitCenter = TPfProfitCenter;
		this.TSuSupplier = TSuSupplier;
		this.TDbdiscountBand = TDbdiscountBand;
		this.TCpCustTrip = TCpCustTrip;
		this.TRkRoomBooking = TRkRoomBooking;
		this.TSistockItem = TSistockItem;
		this.qiqtyIn = qiqtyIn;
		this.qiunitPriceMn = qiunitPriceMn;
		this.qipriceMn = qipriceMn;
		this.qitaxMn = qitaxMn;
		this.qitaxBandIdsTx = qitaxBandIdsTx;
		this.qitaxRatesTx = qitaxRatesTx;
		this.qicurrencyId = qicurrencyId;
		this.qiexchangeRateFl = qiexchangeRateFl;
		this.qilastUpdatedDate = qilastUpdatedDate;
		this.qistockNoTx = qistockNoTx;
		this.qistockItemTx = qistockItemTx;
		this.qistockTypeTx = qistockTypeTx;
		this.qimanufacturerTx = qimanufacturerTx;
		this.qiprimaryColorTxN = qiprimaryColorTxN;
		this.qisecondaryColorTxN = qisecondaryColorTxN;
		this.qisizeTxN = qisizeTxN;
		this.qinotesTxN = qinotesTxN;
		this.qicourseRelatedBl = qicourseRelatedBl;
		this.qitripRelatedBl = qitripRelatedBl;
		this.qiparentIdN = qiparentIdN;
	}

	@Id

	@Column(name = "QIQuoteItemID", unique = true, nullable = false)
	public int getQiquoteItemId() {
		return this.qiquoteItemId;
	}

	public void setQiquoteItemId(int qiquoteItemId) {
		this.qiquoteItemId = qiquoteItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QICustCourseID_N")
	public TC1custCourse getTC1custCourse() {
		return this.TC1custCourse;
	}

	public void setTC1custCourse(TC1custCourse TC1custCourse) {
		this.TC1custCourse = TC1custCourse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QIStockTypeID", nullable = false)
	public TStstockType getTStstockType() {
		return this.TStstockType;
	}

	public void setTStstockType(TStstockType TStstockType) {
		this.TStstockType = TStstockType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QIQuoteID", nullable = false)
	public TQuQuote getTQuQuote() {
		return this.TQuQuote;
	}

	public void setTQuQuote(TQuQuote TQuQuote) {
		this.TQuQuote = TQuQuote;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QIProfitCenterID", nullable = false)
	public TPfProfitCenter getTPfProfitCenter() {
		return this.TPfProfitCenter;
	}

	public void setTPfProfitCenter(TPfProfitCenter TPfProfitCenter) {
		this.TPfProfitCenter = TPfProfitCenter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QIManufacturerID", nullable = false)
	public TSuSupplier getTSuSupplier() {
		return this.TSuSupplier;
	}

	public void setTSuSupplier(TSuSupplier TSuSupplier) {
		this.TSuSupplier = TSuSupplier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QIDiscountBandID_N")
	public TDbdiscountBand getTDbdiscountBand() {
		return this.TDbdiscountBand;
	}

	public void setTDbdiscountBand(TDbdiscountBand TDbdiscountBand) {
		this.TDbdiscountBand = TDbdiscountBand;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QICustTripID_N")
	public TCpCustTrip getTCpCustTrip() {
		return this.TCpCustTrip;
	}

	public void setTCpCustTrip(TCpCustTrip TCpCustTrip) {
		this.TCpCustTrip = TCpCustTrip;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QIRoomBookingID_N")
	public TRkRoomBooking getTRkRoomBooking() {
		return this.TRkRoomBooking;
	}

	public void setTRkRoomBooking(TRkRoomBooking TRkRoomBooking) {
		this.TRkRoomBooking = TRkRoomBooking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QIStockItemID", nullable = false)
	public TSistockItem getTSistockItem() {
		return this.TSistockItem;
	}

	public void setTSistockItem(TSistockItem TSistockItem) {
		this.TSistockItem = TSistockItem;
	}

	@Column(name = "QIQtyIn", nullable = false)
	public short getQiqtyIn() {
		return this.qiqtyIn;
	}

	public void setQiqtyIn(short qiqtyIn) {
		this.qiqtyIn = qiqtyIn;
	}

	@Column(name = "QIUnitPriceMn", nullable = false, precision = 53, scale = 0)
	public double getQiunitPriceMn() {
		return this.qiunitPriceMn;
	}

	public void setQiunitPriceMn(double qiunitPriceMn) {
		this.qiunitPriceMn = qiunitPriceMn;
	}

	@Column(name = "QIPriceMn", nullable = false, precision = 53, scale = 0)
	public double getQipriceMn() {
		return this.qipriceMn;
	}

	public void setQipriceMn(double qipriceMn) {
		this.qipriceMn = qipriceMn;
	}

	@Column(name = "QITaxMn", nullable = false, precision = 53, scale = 0)
	public double getQitaxMn() {
		return this.qitaxMn;
	}

	public void setQitaxMn(double qitaxMn) {
		this.qitaxMn = qitaxMn;
	}

	@Column(name = "QITaxBandIDsTx", nullable = false)
	public String getQitaxBandIdsTx() {
		return this.qitaxBandIdsTx;
	}

	public void setQitaxBandIdsTx(String qitaxBandIdsTx) {
		this.qitaxBandIdsTx = qitaxBandIdsTx;
	}

	@Column(name = "QITaxRatesTx", nullable = false)
	public String getQitaxRatesTx() {
		return this.qitaxRatesTx;
	}

	public void setQitaxRatesTx(String qitaxRatesTx) {
		this.qitaxRatesTx = qitaxRatesTx;
	}

	@Column(name = "QICurrencyID", nullable = false)
	public short getQicurrencyId() {
		return this.qicurrencyId;
	}

	public void setQicurrencyId(short qicurrencyId) {
		this.qicurrencyId = qicurrencyId;
	}

	@Column(name = "QIExchangeRateFl", nullable = false, precision = 24, scale = 0)
	public float getQiexchangeRateFl() {
		return this.qiexchangeRateFl;
	}

	public void setQiexchangeRateFl(float qiexchangeRateFl) {
		this.qiexchangeRateFl = qiexchangeRateFl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QILastUpdatedDate", nullable = false, length = 23)
	public Date getQilastUpdatedDate() {
		return this.qilastUpdatedDate;
	}

	public void setQilastUpdatedDate(Date qilastUpdatedDate) {
		this.qilastUpdatedDate = qilastUpdatedDate;
	}

	@Column(name = "QIStockNoTx", nullable = false)
	public String getQistockNoTx() {
		return this.qistockNoTx;
	}

	public void setQistockNoTx(String qistockNoTx) {
		this.qistockNoTx = qistockNoTx;
	}

	@Column(name = "QIStockItemTx", nullable = false)
	public String getQistockItemTx() {
		return this.qistockItemTx;
	}

	public void setQistockItemTx(String qistockItemTx) {
		this.qistockItemTx = qistockItemTx;
	}

	@Column(name = "QIStockTypeTx", nullable = false)
	public String getQistockTypeTx() {
		return this.qistockTypeTx;
	}

	public void setQistockTypeTx(String qistockTypeTx) {
		this.qistockTypeTx = qistockTypeTx;
	}

	@Column(name = "QIManufacturerTx", nullable = false)
	public String getQimanufacturerTx() {
		return this.qimanufacturerTx;
	}

	public void setQimanufacturerTx(String qimanufacturerTx) {
		this.qimanufacturerTx = qimanufacturerTx;
	}

	@Column(name = "QIPrimaryColorTx_N")
	public String getQiprimaryColorTxN() {
		return this.qiprimaryColorTxN;
	}

	public void setQiprimaryColorTxN(String qiprimaryColorTxN) {
		this.qiprimaryColorTxN = qiprimaryColorTxN;
	}

	@Column(name = "QISecondaryColorTx_N")
	public String getQisecondaryColorTxN() {
		return this.qisecondaryColorTxN;
	}

	public void setQisecondaryColorTxN(String qisecondaryColorTxN) {
		this.qisecondaryColorTxN = qisecondaryColorTxN;
	}

	@Column(name = "QISizeTx_N")
	public String getQisizeTxN() {
		return this.qisizeTxN;
	}

	public void setQisizeTxN(String qisizeTxN) {
		this.qisizeTxN = qisizeTxN;
	}

	@Column(name = "QINotesTx_N")
	public String getQinotesTxN() {
		return this.qinotesTxN;
	}

	public void setQinotesTxN(String qinotesTxN) {
		this.qinotesTxN = qinotesTxN;
	}

	@Column(name = "QICourseRelatedBl", nullable = false)
	public boolean isQicourseRelatedBl() {
		return this.qicourseRelatedBl;
	}

	public void setQicourseRelatedBl(boolean qicourseRelatedBl) {
		this.qicourseRelatedBl = qicourseRelatedBl;
	}

	@Column(name = "QITripRelatedBl", nullable = false)
	public boolean isQitripRelatedBl() {
		return this.qitripRelatedBl;
	}

	public void setQitripRelatedBl(boolean qitripRelatedBl) {
		this.qitripRelatedBl = qitripRelatedBl;
	}

	@Column(name = "QIParentID_N")
	public Integer getQiparentIdN() {
		return this.qiparentIdN;
	}

	public void setQiparentIdN(Integer qiparentIdN) {
		this.qiparentIdN = qiparentIdN;
	}

}
