package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TQssql generated by hbm2java
 */
@Entity
@Table(name = "T_QSSQL")
public class TQssql implements java.io.Serializable {

	private String qssqlnameTx;
	private String qssqltx;

	public TQssql() {
	}

	public TQssql(String qssqlnameTx, String qssqltx) {
		this.qssqlnameTx = qssqlnameTx;
		this.qssqltx = qssqltx;
	}

	@Id

	@Column(name = "QSSQLNameTx", unique = true, nullable = false)
	public String getQssqlnameTx() {
		return this.qssqlnameTx;
	}

	public void setQssqlnameTx(String qssqlnameTx) {
		this.qssqlnameTx = qssqlnameTx;
	}

	@Column(name = "QSSQLTx", nullable = false)
	public String getQssqltx() {
		return this.qssqltx;
	}

	public void setQssqltx(String qssqltx) {
		this.qssqltx = qssqltx;
	}

}
