package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TRbrentalBooking generated by hbm2java
 */
@Entity
@Table(name = "T_RBRentalBooking")
public class TRbrentalBooking implements java.io.Serializable {

	private int rbrentalBookingId;
	private TCccostCenter TCccostCenter;
	private TEmEmp TEmEmp;
	private TSoStore TSoStore;
	private TTstransStatus TTstransStatus;
	private TInInvoice TInInvoice;
	private TCuCust TCuCust;
	private Date rbcreationDate;
	private BigDecimal rbbookingAmountMn;
	private BigDecimal rbbookingTaxMn;
	private short rbcurrencyId;
	private float rbexchangeRateFl;
	private Date rblastUpdatedDate;
	private String rbnotesTxN;
	private Date rbvoidDateN;
	private String rbvoidReasonTxN;
	private Date rbdueStartDate;
	private Date rbdueEndDate;
	private Short rbbagNoInN;
	private boolean rbpenaltyBl;
	private Set<TVivoucherItem> TVivoucherItems = new HashSet<TVivoucherItem>(0);
	private Set<TRirentalBookingItem> TRirentalBookingItems = new HashSet<TRirentalBookingItem>(0);
	private Set<TIiinvoiceItem> TIiinvoiceItems = new HashSet<TIiinvoiceItem>(0);

	public TRbrentalBooking() {
	}

	public TRbrentalBooking(int rbrentalBookingId, TEmEmp TEmEmp, TSoStore TSoStore, TTstransStatus TTstransStatus,
			TCuCust TCuCust, Date rbcreationDate, BigDecimal rbbookingAmountMn, BigDecimal rbbookingTaxMn,
			short rbcurrencyId, float rbexchangeRateFl, Date rblastUpdatedDate, Date rbdueStartDate, Date rbdueEndDate,
			boolean rbpenaltyBl) {
		this.rbrentalBookingId = rbrentalBookingId;
		this.TEmEmp = TEmEmp;
		this.TSoStore = TSoStore;
		this.TTstransStatus = TTstransStatus;
		this.TCuCust = TCuCust;
		this.rbcreationDate = rbcreationDate;
		this.rbbookingAmountMn = rbbookingAmountMn;
		this.rbbookingTaxMn = rbbookingTaxMn;
		this.rbcurrencyId = rbcurrencyId;
		this.rbexchangeRateFl = rbexchangeRateFl;
		this.rblastUpdatedDate = rblastUpdatedDate;
		this.rbdueStartDate = rbdueStartDate;
		this.rbdueEndDate = rbdueEndDate;
		this.rbpenaltyBl = rbpenaltyBl;
	}

	public TRbrentalBooking(int rbrentalBookingId, TCccostCenter TCccostCenter, TEmEmp TEmEmp, TSoStore TSoStore,
			TTstransStatus TTstransStatus, TInInvoice TInInvoice, TCuCust TCuCust, Date rbcreationDate,
			BigDecimal rbbookingAmountMn, BigDecimal rbbookingTaxMn, short rbcurrencyId, float rbexchangeRateFl,
			Date rblastUpdatedDate, String rbnotesTxN, Date rbvoidDateN, String rbvoidReasonTxN,
			Date rbdueStartDate, Date rbdueEndDate, Short rbbagNoInN, boolean rbpenaltyBl,
			Set<TVivoucherItem> TVivoucherItems, Set<TRirentalBookingItem> TRirentalBookingItems,
			Set<TIiinvoiceItem> TIiinvoiceItems) {
		this.rbrentalBookingId = rbrentalBookingId;
		this.TCccostCenter = TCccostCenter;
		this.TEmEmp = TEmEmp;
		this.TSoStore = TSoStore;
		this.TTstransStatus = TTstransStatus;
		this.TInInvoice = TInInvoice;
		this.TCuCust = TCuCust;
		this.rbcreationDate = rbcreationDate;
		this.rbbookingAmountMn = rbbookingAmountMn;
		this.rbbookingTaxMn = rbbookingTaxMn;
		this.rbcurrencyId = rbcurrencyId;
		this.rbexchangeRateFl = rbexchangeRateFl;
		this.rblastUpdatedDate = rblastUpdatedDate;
		this.rbnotesTxN = rbnotesTxN;
		this.rbvoidDateN = rbvoidDateN;
		this.rbvoidReasonTxN = rbvoidReasonTxN;
		this.rbdueStartDate = rbdueStartDate;
		this.rbdueEndDate = rbdueEndDate;
		this.rbbagNoInN = rbbagNoInN;
		this.rbpenaltyBl = rbpenaltyBl;
		this.TVivoucherItems = TVivoucherItems;
		this.TRirentalBookingItems = TRirentalBookingItems;
		this.TIiinvoiceItems = TIiinvoiceItems;
	}

	@Id

	@Column(name = "RBRentalBookingID", unique = true, nullable = false)
	public int getRbrentalBookingId() {
		return this.rbrentalBookingId;
	}

	public void setRbrentalBookingId(int rbrentalBookingId) {
		this.rbrentalBookingId = rbrentalBookingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RBCostCenterID_N")
	public TCccostCenter getTCccostCenter() {
		return this.TCccostCenter;
	}

	public void setTCccostCenter(TCccostCenter TCccostCenter) {
		this.TCccostCenter = TCccostCenter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RBEmpID", nullable = false)
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RBStoreID", nullable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RBStatusID", nullable = false)
	public TTstransStatus getTTstransStatus() {
		return this.TTstransStatus;
	}

	public void setTTstransStatus(TTstransStatus TTstransStatus) {
		this.TTstransStatus = TTstransStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RBInvoiceID_N")
	public TInInvoice getTInInvoice() {
		return this.TInInvoice;
	}

	public void setTInInvoice(TInInvoice TInInvoice) {
		this.TInInvoice = TInInvoice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RBCustID", nullable = false)
	public TCuCust getTCuCust() {
		return this.TCuCust;
	}

	public void setTCuCust(TCuCust TCuCust) {
		this.TCuCust = TCuCust;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RBCreationDate", nullable = false, length = 23)
	public Date getRbcreationDate() {
		return this.rbcreationDate;
	}

	public void setRbcreationDate(Date rbcreationDate) {
		this.rbcreationDate = rbcreationDate;
	}

	@Column(name = "RBBookingAmountMn", nullable = false, scale = 4)
	public BigDecimal getRbbookingAmountMn() {
		return this.rbbookingAmountMn;
	}

	public void setRbbookingAmountMn(BigDecimal rbbookingAmountMn) {
		this.rbbookingAmountMn = rbbookingAmountMn;
	}

	@Column(name = "RBBookingTaxMn", nullable = false, scale = 4)
	public BigDecimal getRbbookingTaxMn() {
		return this.rbbookingTaxMn;
	}

	public void setRbbookingTaxMn(BigDecimal rbbookingTaxMn) {
		this.rbbookingTaxMn = rbbookingTaxMn;
	}

	@Column(name = "RBCurrencyID", nullable = false)
	public short getRbcurrencyId() {
		return this.rbcurrencyId;
	}

	public void setRbcurrencyId(short rbcurrencyId) {
		this.rbcurrencyId = rbcurrencyId;
	}

	@Column(name = "RBExchangeRateFl", nullable = false, precision = 24, scale = 0)
	public float getRbexchangeRateFl() {
		return this.rbexchangeRateFl;
	}

	public void setRbexchangeRateFl(float rbexchangeRateFl) {
		this.rbexchangeRateFl = rbexchangeRateFl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RBLastUpdatedDate", nullable = false, length = 23)
	public Date getRblastUpdatedDate() {
		return this.rblastUpdatedDate;
	}

	public void setRblastUpdatedDate(Date rblastUpdatedDate) {
		this.rblastUpdatedDate = rblastUpdatedDate;
	}

	@Column(name = "RBNotesTx_N")
	public String getRbnotesTxN() {
		return this.rbnotesTxN;
	}

	public void setRbnotesTxN(String rbnotesTxN) {
		this.rbnotesTxN = rbnotesTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RBVoidDate_N", length = 23)
	public Date getRbvoidDateN() {
		return this.rbvoidDateN;
	}

	public void setRbvoidDateN(Date rbvoidDateN) {
		this.rbvoidDateN = rbvoidDateN;
	}

	@Column(name = "RBVoidReasonTx_N")
	public String getRbvoidReasonTxN() {
		return this.rbvoidReasonTxN;
	}

	public void setRbvoidReasonTxN(String rbvoidReasonTxN) {
		this.rbvoidReasonTxN = rbvoidReasonTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RBDueStartDate", nullable = false, length = 23)
	public Date getRbdueStartDate() {
		return this.rbdueStartDate;
	}

	public void setRbdueStartDate(Date rbdueStartDate) {
		this.rbdueStartDate = rbdueStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RBDueEndDate", nullable = false, length = 23)
	public Date getRbdueEndDate() {
		return this.rbdueEndDate;
	}

	public void setRbdueEndDate(Date rbdueEndDate) {
		this.rbdueEndDate = rbdueEndDate;
	}

	@Column(name = "RBBagNoIn_N")
	public Short getRbbagNoInN() {
		return this.rbbagNoInN;
	}

	public void setRbbagNoInN(Short rbbagNoInN) {
		this.rbbagNoInN = rbbagNoInN;
	}

	@Column(name = "RBPenaltyBl", nullable = false)
	public boolean isRbpenaltyBl() {
		return this.rbpenaltyBl;
	}

	public void setRbpenaltyBl(boolean rbpenaltyBl) {
		this.rbpenaltyBl = rbpenaltyBl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRbrentalBooking")
	public Set<TVivoucherItem> getTVivoucherItems() {
		return this.TVivoucherItems;
	}

	public void setTVivoucherItems(Set<TVivoucherItem> TVivoucherItems) {
		this.TVivoucherItems = TVivoucherItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRbrentalBooking")
	public Set<TRirentalBookingItem> getTRirentalBookingItems() {
		return this.TRirentalBookingItems;
	}

	public void setTRirentalBookingItems(Set<TRirentalBookingItem> TRirentalBookingItems) {
		this.TRirentalBookingItems = TRirentalBookingItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRbrentalBooking")
	public Set<TIiinvoiceItem> getTIiinvoiceItems() {
		return this.TIiinvoiceItems;
	}

	public void setTIiinvoiceItems(Set<TIiinvoiceItem> TIiinvoiceItems) {
		this.TIiinvoiceItems = TIiinvoiceItems;
	}

}
