package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TReRoomType generated by hbm2java
 */
@Entity
@Table(name = "T_ReRoomType", uniqueConstraints = @UniqueConstraint(columnNames = "ReRoomTypeTx"))
public class TReRoomType implements java.io.Serializable {

	private int reRoomTypeId;
	private String reRoomTypeTx;
	private Date reCreationDate;
	private Date reLastUpdatedDate;
	private boolean reUnavailableBl;
	private boolean reRequiredBl;
	private Set<TRmRoom> TRmRooms = new HashSet<TRmRoom>(0);
	private Set<TSvStockRoom> TSvStockRooms = new HashSet<TSvStockRoom>(0);

	public TReRoomType() {
	}

	public TReRoomType(int reRoomTypeId, String reRoomTypeTx, Date reCreationDate, Date reLastUpdatedDate,
			boolean reUnavailableBl, boolean reRequiredBl) {
		this.reRoomTypeId = reRoomTypeId;
		this.reRoomTypeTx = reRoomTypeTx;
		this.reCreationDate = reCreationDate;
		this.reLastUpdatedDate = reLastUpdatedDate;
		this.reUnavailableBl = reUnavailableBl;
		this.reRequiredBl = reRequiredBl;
	}

	public TReRoomType(int reRoomTypeId, String reRoomTypeTx, Date reCreationDate, Date reLastUpdatedDate,
			boolean reUnavailableBl, boolean reRequiredBl, Set<TRmRoom> TRmRooms, Set<TSvStockRoom> TSvStockRooms) {
		this.reRoomTypeId = reRoomTypeId;
		this.reRoomTypeTx = reRoomTypeTx;
		this.reCreationDate = reCreationDate;
		this.reLastUpdatedDate = reLastUpdatedDate;
		this.reUnavailableBl = reUnavailableBl;
		this.reRequiredBl = reRequiredBl;
		this.TRmRooms = TRmRooms;
		this.TSvStockRooms = TSvStockRooms;
	}

	@Id

	@Column(name = "ReRoomTypeID", unique = true, nullable = false)
	public int getReRoomTypeId() {
		return this.reRoomTypeId;
	}

	public void setReRoomTypeId(int reRoomTypeId) {
		this.reRoomTypeId = reRoomTypeId;
	}

	@Column(name = "ReRoomTypeTx", unique = true, nullable = false)
	public String getReRoomTypeTx() {
		return this.reRoomTypeTx;
	}

	public void setReRoomTypeTx(String reRoomTypeTx) {
		this.reRoomTypeTx = reRoomTypeTx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ReCreationDate", nullable = false, length = 23)
	public Date getReCreationDate() {
		return this.reCreationDate;
	}

	public void setReCreationDate(Date reCreationDate) {
		this.reCreationDate = reCreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ReLastUpdatedDate", nullable = false, length = 23)
	public Date getReLastUpdatedDate() {
		return this.reLastUpdatedDate;
	}

	public void setReLastUpdatedDate(Date reLastUpdatedDate) {
		this.reLastUpdatedDate = reLastUpdatedDate;
	}

	@Column(name = "ReUnavailableBl", nullable = false)
	public boolean isReUnavailableBl() {
		return this.reUnavailableBl;
	}

	public void setReUnavailableBl(boolean reUnavailableBl) {
		this.reUnavailableBl = reUnavailableBl;
	}

	@Column(name = "ReRequiredBl", nullable = false)
	public boolean isReRequiredBl() {
		return this.reRequiredBl;
	}

	public void setReRequiredBl(boolean reRequiredBl) {
		this.reRequiredBl = reRequiredBl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TReRoomType")
	public Set<TRmRoom> getTRmRooms() {
		return this.TRmRooms;
	}

	public void setTRmRooms(Set<TRmRoom> TRmRooms) {
		this.TRmRooms = TRmRooms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TReRoomType")
	public Set<TSvStockRoom> getTSvStockRooms() {
		return this.TSvStockRooms;
	}

	public void setTSvStockRooms(Set<TSvStockRoom> TSvStockRooms) {
		this.TSvStockRooms = TSvStockRooms;
	}

}
