package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TRfreportFieldDefaults generated by hbm2java
 */
@Entity
@Table(name = "T_RFReportFieldDefaults")
public class TRfreportFieldDefaults implements java.io.Serializable {

	private TRfreportFieldDefaultsId id;

	public TRfreportFieldDefaults() {
	}

	public TRfreportFieldDefaults(TRfreportFieldDefaultsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rfreportFieldId", column = @Column(name = "RFReportFieldID", nullable = false)),
			@AttributeOverride(name = "rfreportLayoutId", column = @Column(name = "RFReportLayoutID", nullable = false)),
			@AttributeOverride(name = "rffieldTx", column = @Column(name = "RFFieldTx", nullable = false)),
			@AttributeOverride(name = "rffieldTypeId", column = @Column(name = "RFFieldTypeID", nullable = false)),
			@AttributeOverride(name = "rfreportSectionId", column = @Column(name = "RFReportSectionID", nullable = false)),
			@AttributeOverride(name = "rffontNameTx", column = @Column(name = "RFFontNameTx", nullable = false)),
			@AttributeOverride(name = "rffontSizeFl", column = @Column(name = "RFFontSizeFl", nullable = false, precision = 24, scale = 0)),
			@AttributeOverride(name = "rffontItalicBl", column = @Column(name = "RFFontItalicBl", nullable = false)),
			@AttributeOverride(name = "rffontBoldBl", column = @Column(name = "RFFontBoldBl", nullable = false)),
			@AttributeOverride(name = "rffontUnderlinedBl", column = @Column(name = "RFFontUnderlinedBl", nullable = false)),
			@AttributeOverride(name = "rfxin", column = @Column(name = "RFXIn", nullable = false)),
			@AttributeOverride(name = "rfyin", column = @Column(name = "RFYIn", nullable = false)),
			@AttributeOverride(name = "rfwidthIn", column = @Column(name = "RFWidthIn", nullable = false)),
			@AttributeOverride(name = "rfheightIn", column = @Column(name = "RFHeightIn", nullable = false)),
			@AttributeOverride(name = "rfcentredBl", column = @Column(name = "RFCentredBl", nullable = false)),
			@AttributeOverride(name = "rfalignmentTx", column = @Column(name = "RFAlignmentTx", nullable = false)),
			@AttributeOverride(name = "rfforeColorIn", column = @Column(name = "RFForeColorIn", nullable = false)),
			@AttributeOverride(name = "rfvisibleBl", column = @Column(name = "RFVisibleBl", nullable = false)),
			@AttributeOverride(name = "rffilenameTxN", column = @Column(name = "RFFilenameTx_N")),
			@AttributeOverride(name = "rfformatTxN", column = @Column(name = "RFFormatTx_N")),
			@AttributeOverride(name = "rfcanGrowBl", column = @Column(name = "RFCanGrowBl", nullable = false)),
			@AttributeOverride(name = "rfunavailableBl", column = @Column(name = "RFUnavailableBl", nullable = false)),
			@AttributeOverride(name = "rflinkedFieldId", column = @Column(name = "RFLinkedFieldID", nullable = false)),
			@AttributeOverride(name = "rfmemoTxN", column = @Column(name = "RFMemoTx_N")),
			@AttributeOverride(name = "rfbackColorIn", column = @Column(name = "RFBackColorIn")),
			@AttributeOverride(name = "rfruleTxN", column = @Column(name = "RFRuleTx_N")),
			@AttributeOverride(name = "rfbarcodeTypeIdN", column = @Column(name = "RFBarcodeTypeID_N")),
			@AttributeOverride(name = "rfnarrowBarWidthInN", column = @Column(name = "RFNarrowBarWidthIn_N")),
			@AttributeOverride(name = "rfwideBarWidthInN", column = @Column(name = "RFWideBarWidthIn_N")),
			@AttributeOverride(name = "rfhumanReadableBl", column = @Column(name = "RFHumanReadableBl", nullable = false)),
			@AttributeOverride(name = "rfmaxCharsIn", column = @Column(name = "RFMaxCharsIn", nullable = false)) })
	public TRfreportFieldDefaultsId getId() {
		return this.id;
	}

	public void setId(TRfreportFieldDefaultsId id) {
		this.id = id;
	}

}
