package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TRirentalBookingItem generated by hbm2java
 */
@Entity
@Table(name = "T_RIRentalBookingItem")
public class TRirentalBookingItem implements java.io.Serializable {

	private int rirentalBookingItemId;
	private TRbrentalBooking TRbrentalBooking;
	private TEqEquipment TEqEquipment;
	private TTbtaxBand TTbtaxBand;
	private double ripriceMn;
	private double ritaxMn;
	private float ritaxRateFl;
	private short ricurrencyId;
	private float riexchangeRateFl;
	private Date rilastUpdatedDate;
	private Date riactualStartDateN;
	private Date riactualEndDateN;

	public TRirentalBookingItem() {
	}

	public TRirentalBookingItem(int rirentalBookingItemId, TRbrentalBooking TRbrentalBooking, TEqEquipment TEqEquipment,
			TTbtaxBand TTbtaxBand, double ripriceMn, double ritaxMn, float ritaxRateFl, short ricurrencyId,
			float riexchangeRateFl, Date rilastUpdatedDate) {
		this.rirentalBookingItemId = rirentalBookingItemId;
		this.TRbrentalBooking = TRbrentalBooking;
		this.TEqEquipment = TEqEquipment;
		this.TTbtaxBand = TTbtaxBand;
		this.ripriceMn = ripriceMn;
		this.ritaxMn = ritaxMn;
		this.ritaxRateFl = ritaxRateFl;
		this.ricurrencyId = ricurrencyId;
		this.riexchangeRateFl = riexchangeRateFl;
		this.rilastUpdatedDate = rilastUpdatedDate;
	}

	public TRirentalBookingItem(int rirentalBookingItemId, TRbrentalBooking TRbrentalBooking, TEqEquipment TEqEquipment,
			TTbtaxBand TTbtaxBand, double ripriceMn, double ritaxMn, float ritaxRateFl, short ricurrencyId,
			float riexchangeRateFl, Date rilastUpdatedDate, Date riactualStartDateN, Date riactualEndDateN) {
		this.rirentalBookingItemId = rirentalBookingItemId;
		this.TRbrentalBooking = TRbrentalBooking;
		this.TEqEquipment = TEqEquipment;
		this.TTbtaxBand = TTbtaxBand;
		this.ripriceMn = ripriceMn;
		this.ritaxMn = ritaxMn;
		this.ritaxRateFl = ritaxRateFl;
		this.ricurrencyId = ricurrencyId;
		this.riexchangeRateFl = riexchangeRateFl;
		this.rilastUpdatedDate = rilastUpdatedDate;
		this.riactualStartDateN = riactualStartDateN;
		this.riactualEndDateN = riactualEndDateN;
	}

	@Id

	@Column(name = "RIRentalBookingItemID", unique = true, nullable = false)
	public int getRirentalBookingItemId() {
		return this.rirentalBookingItemId;
	}

	public void setRirentalBookingItemId(int rirentalBookingItemId) {
		this.rirentalBookingItemId = rirentalBookingItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RIRentalBookingID", nullable = false)
	public TRbrentalBooking getTRbrentalBooking() {
		return this.TRbrentalBooking;
	}

	public void setTRbrentalBooking(TRbrentalBooking TRbrentalBooking) {
		this.TRbrentalBooking = TRbrentalBooking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RIEquipmentID", nullable = false)
	public TEqEquipment getTEqEquipment() {
		return this.TEqEquipment;
	}

	public void setTEqEquipment(TEqEquipment TEqEquipment) {
		this.TEqEquipment = TEqEquipment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RITaxBandID", nullable = false)
	public TTbtaxBand getTTbtaxBand() {
		return this.TTbtaxBand;
	}

	public void setTTbtaxBand(TTbtaxBand TTbtaxBand) {
		this.TTbtaxBand = TTbtaxBand;
	}

	@Column(name = "RIPriceMn", nullable = false, precision = 53, scale = 0)
	public double getRipriceMn() {
		return this.ripriceMn;
	}

	public void setRipriceMn(double ripriceMn) {
		this.ripriceMn = ripriceMn;
	}

	@Column(name = "RITaxMn", nullable = false, precision = 53, scale = 0)
	public double getRitaxMn() {
		return this.ritaxMn;
	}

	public void setRitaxMn(double ritaxMn) {
		this.ritaxMn = ritaxMn;
	}

	@Column(name = "RITaxRateFl", nullable = false, precision = 24, scale = 0)
	public float getRitaxRateFl() {
		return this.ritaxRateFl;
	}

	public void setRitaxRateFl(float ritaxRateFl) {
		this.ritaxRateFl = ritaxRateFl;
	}

	@Column(name = "RICurrencyID", nullable = false)
	public short getRicurrencyId() {
		return this.ricurrencyId;
	}

	public void setRicurrencyId(short ricurrencyId) {
		this.ricurrencyId = ricurrencyId;
	}

	@Column(name = "RIExchangeRateFl", nullable = false, precision = 24, scale = 0)
	public float getRiexchangeRateFl() {
		return this.riexchangeRateFl;
	}

	public void setRiexchangeRateFl(float riexchangeRateFl) {
		this.riexchangeRateFl = riexchangeRateFl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RILastUpdatedDate", nullable = false, length = 23)
	public Date getRilastUpdatedDate() {
		return this.rilastUpdatedDate;
	}

	public void setRilastUpdatedDate(Date rilastUpdatedDate) {
		this.rilastUpdatedDate = rilastUpdatedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RIActualStartDate_N", length = 23)
	public Date getRiactualStartDateN() {
		return this.riactualStartDateN;
	}

	public void setRiactualStartDateN(Date riactualStartDateN) {
		this.riactualStartDateN = riactualStartDateN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RIActualEndDate_N", length = 23)
	public Date getRiactualEndDateN() {
		return this.riactualEndDateN;
	}

	public void setRiactualEndDateN(Date riactualEndDateN) {
		this.riactualEndDateN = riactualEndDateN;
	}

}
