package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TRlreportLayoutDefaults generated by hbm2java
 */
@Entity
@Table(name = "T_RLReportLayoutDefaults")
public class TRlreportLayoutDefaults implements java.io.Serializable {

	private TRlreportLayoutDefaultsId id;

	public TRlreportLayoutDefaults() {
	}

	public TRlreportLayoutDefaults(TRlreportLayoutDefaultsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rlreportLayoutId", column = @Column(name = "RLReportLayoutID", nullable = false)),
			@AttributeOverride(name = "rlreportLayoutTx", column = @Column(name = "RLReportLayoutTx", nullable = false)),
			@AttributeOverride(name = "rlreportTypeId", column = @Column(name = "RLReportTypeID", nullable = false)),
			@AttributeOverride(name = "rlpaperSizeId", column = @Column(name = "RLPaperSizeID", nullable = false)),
			@AttributeOverride(name = "rldestinationId", column = @Column(name = "RLDestinationID", nullable = false)),
			@AttributeOverride(name = "rlcopiesIn", column = @Column(name = "RLCopiesIn", nullable = false)),
			@AttributeOverride(name = "rllandscapeBl", column = @Column(name = "RLLandscapeBl", nullable = false)),
			@AttributeOverride(name = "rluseMarginsBl", column = @Column(name = "RLUseMarginsBl", nullable = false)),
			@AttributeOverride(name = "rlunavailableBl", column = @Column(name = "RLUnavailableBl", nullable = false)),
			@AttributeOverride(name = "rlscaleToFitXbl", column = @Column(name = "RLScaleToFitXBl", nullable = false)),
			@AttributeOverride(name = "rlscaleToFitYbl", column = @Column(name = "RLScaleToFitYBl", nullable = false)),
			@AttributeOverride(name = "rluseDbpaperSizeBl", column = @Column(name = "RLUseDBPaperSizeBl", nullable = false)) })
	public TRlreportLayoutDefaultsId getId() {
		return this.id;
	}

	public void setId(TRlreportLayoutDefaultsId id) {
		this.id = id;
	}

}
