package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TRqqtyBand generated by hbm2java
 */
@Entity
@Table(name = "T_RQQtyBand")
public class TRqqtyBand implements java.io.Serializable {

	private int rqqtyBandId;
	private TSistockItem TSistockItem;
	private int rqminIn;
	private int rqmaxIn;
	private String rqnotesTxN;
	private Set<TRpretailPrice> TRpretailPrices = new HashSet<TRpretailPrice>(0);

	public TRqqtyBand() {
	}

	public TRqqtyBand(int rqqtyBandId, TSistockItem TSistockItem, int rqminIn, int rqmaxIn) {
		this.rqqtyBandId = rqqtyBandId;
		this.TSistockItem = TSistockItem;
		this.rqminIn = rqminIn;
		this.rqmaxIn = rqmaxIn;
	}

	public TRqqtyBand(int rqqtyBandId, TSistockItem TSistockItem, int rqminIn, int rqmaxIn, String rqnotesTxN,
			Set<TRpretailPrice> TRpretailPrices) {
		this.rqqtyBandId = rqqtyBandId;
		this.TSistockItem = TSistockItem;
		this.rqminIn = rqminIn;
		this.rqmaxIn = rqmaxIn;
		this.rqnotesTxN = rqnotesTxN;
		this.TRpretailPrices = TRpretailPrices;
	}

	@Id

	@Column(name = "RQQtyBandID", unique = true, nullable = false)
	public int getRqqtyBandId() {
		return this.rqqtyBandId;
	}

	public void setRqqtyBandId(int rqqtyBandId) {
		this.rqqtyBandId = rqqtyBandId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RQStockItemID", nullable = false)
	public TSistockItem getTSistockItem() {
		return this.TSistockItem;
	}

	public void setTSistockItem(TSistockItem TSistockItem) {
		this.TSistockItem = TSistockItem;
	}

	@Column(name = "RQMinIn", nullable = false)
	public int getRqminIn() {
		return this.rqminIn;
	}

	public void setRqminIn(int rqminIn) {
		this.rqminIn = rqminIn;
	}

	@Column(name = "RQMaxIn", nullable = false)
	public int getRqmaxIn() {
		return this.rqmaxIn;
	}

	public void setRqmaxIn(int rqmaxIn) {
		this.rqmaxIn = rqmaxIn;
	}

	@Column(name = "RQNotesTx_N")
	public String getRqnotesTxN() {
		return this.rqnotesTxN;
	}

	public void setRqnotesTxN(String rqnotesTxN) {
		this.rqnotesTxN = rqnotesTxN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRqqtyBand")
	public Set<TRpretailPrice> getTRpretailPrices() {
		return this.TRpretailPrices;
	}

	public void setTRpretailPrices(Set<TRpretailPrice> TRpretailPrices) {
		this.TRpretailPrices = TRpretailPrices;
	}

}
