package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TRrreportRun generated by hbm2java
 */
@Entity
@Table(name = "T_RRReportRun")
public class TRrreportRun implements java.io.Serializable {

	private int rrreportRunId;
	private TEmEmp TEmEmp;
	private TRgreportGroup TRgreportGroup;
	private TSoStore TSoStore;
	private Date rrlastRunDate;

	public TRrreportRun() {
	}

	public TRrreportRun(int rrreportRunId, TEmEmp TEmEmp, TRgreportGroup TRgreportGroup, TSoStore TSoStore,
			Date rrlastRunDate) {
		this.rrreportRunId = rrreportRunId;
		this.TEmEmp = TEmEmp;
		this.TRgreportGroup = TRgreportGroup;
		this.TSoStore = TSoStore;
		this.rrlastRunDate = rrlastRunDate;
	}

	@Id

	@Column(name = "RRReportRunID", unique = true, nullable = false)
	public int getRrreportRunId() {
		return this.rrreportRunId;
	}

	public void setRrreportRunId(int rrreportRunId) {
		this.rrreportRunId = rrreportRunId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RREmpID", nullable = false)
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RRReportGroupID", nullable = false)
	public TRgreportGroup getTRgreportGroup() {
		return this.TRgreportGroup;
	}

	public void setTRgreportGroup(TRgreportGroup TRgreportGroup) {
		this.TRgreportGroup = TRgreportGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RRStoreID", nullable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RRLastRunDate", nullable = false, length = 23)
	public Date getRrlastRunDate() {
		return this.rrlastRunDate;
	}

	public void setRrlastRunDate(Date rrlastRunDate) {
		this.rrlastRunDate = rrlastRunDate;
	}

}
