package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TRsreportSection generated by hbm2java
 */
@Entity
@Table(name = "T_RSReportSection")
public class TRsreportSection implements java.io.Serializable {

	private int rsreportSectionId;
	private String rsreportSectionTx;
	private int rsreportLayoutId;
	private short rssectionTypeId;
	private short rsdesignOrderIn;
	private short rsruntimeOrderIn;
	private int rsheightIn;
	private boolean rsunavailableBl;
	private String xcxcxc;
	private int rssectionHeaderId;
	private String rstmpNameTxN;
	private int rstmpId;
	private Set<TRfreportField> TRfreportFields = new HashSet<TRfreportField>(0);

	public TRsreportSection() {
	}

	public TRsreportSection(int rsreportSectionId, String rsreportSectionTx, int rsreportLayoutId,
			short rssectionTypeId, short rsdesignOrderIn, short rsruntimeOrderIn, int rsheightIn,
			boolean rsunavailableBl, int rssectionHeaderId, int rstmpId) {
		this.rsreportSectionId = rsreportSectionId;
		this.rsreportSectionTx = rsreportSectionTx;
		this.rsreportLayoutId = rsreportLayoutId;
		this.rssectionTypeId = rssectionTypeId;
		this.rsdesignOrderIn = rsdesignOrderIn;
		this.rsruntimeOrderIn = rsruntimeOrderIn;
		this.rsheightIn = rsheightIn;
		this.rsunavailableBl = rsunavailableBl;
		this.rssectionHeaderId = rssectionHeaderId;
		this.rstmpId = rstmpId;
	}

	public TRsreportSection(int rsreportSectionId, String rsreportSectionTx, int rsreportLayoutId,
			short rssectionTypeId, short rsdesignOrderIn, short rsruntimeOrderIn, int rsheightIn,
			boolean rsunavailableBl, String xcxcxc, int rssectionHeaderId, String rstmpNameTxN, int rstmpId,
			Set<TRfreportField> TRfreportFields) {
		this.rsreportSectionId = rsreportSectionId;
		this.rsreportSectionTx = rsreportSectionTx;
		this.rsreportLayoutId = rsreportLayoutId;
		this.rssectionTypeId = rssectionTypeId;
		this.rsdesignOrderIn = rsdesignOrderIn;
		this.rsruntimeOrderIn = rsruntimeOrderIn;
		this.rsheightIn = rsheightIn;
		this.rsunavailableBl = rsunavailableBl;
		this.xcxcxc = xcxcxc;
		this.rssectionHeaderId = rssectionHeaderId;
		this.rstmpNameTxN = rstmpNameTxN;
		this.rstmpId = rstmpId;
		this.TRfreportFields = TRfreportFields;
	}

	@Id

	@Column(name = "RSReportSectionID", unique = true, nullable = false)
	public int getRsreportSectionId() {
		return this.rsreportSectionId;
	}

	public void setRsreportSectionId(int rsreportSectionId) {
		this.rsreportSectionId = rsreportSectionId;
	}

	@Column(name = "RSReportSectionTx", nullable = false)
	public String getRsreportSectionTx() {
		return this.rsreportSectionTx;
	}

	public void setRsreportSectionTx(String rsreportSectionTx) {
		this.rsreportSectionTx = rsreportSectionTx;
	}

	@Column(name = "RSReportLayoutID", nullable = false)
	public int getRsreportLayoutId() {
		return this.rsreportLayoutId;
	}

	public void setRsreportLayoutId(int rsreportLayoutId) {
		this.rsreportLayoutId = rsreportLayoutId;
	}

	@Column(name = "RSSectionTypeID", nullable = false)
	public short getRssectionTypeId() {
		return this.rssectionTypeId;
	}

	public void setRssectionTypeId(short rssectionTypeId) {
		this.rssectionTypeId = rssectionTypeId;
	}

	@Column(name = "RSDesignOrderIn", nullable = false)
	public short getRsdesignOrderIn() {
		return this.rsdesignOrderIn;
	}

	public void setRsdesignOrderIn(short rsdesignOrderIn) {
		this.rsdesignOrderIn = rsdesignOrderIn;
	}

	@Column(name = "RSRuntimeOrderIn", nullable = false)
	public short getRsruntimeOrderIn() {
		return this.rsruntimeOrderIn;
	}

	public void setRsruntimeOrderIn(short rsruntimeOrderIn) {
		this.rsruntimeOrderIn = rsruntimeOrderIn;
	}

	@Column(name = "RSHeightIn", nullable = false)
	public int getRsheightIn() {
		return this.rsheightIn;
	}

	public void setRsheightIn(int rsheightIn) {
		this.rsheightIn = rsheightIn;
	}

	@Column(name = "RSUnavailableBl", nullable = false)
	public boolean isRsunavailableBl() {
		return this.rsunavailableBl;
	}

	public void setRsunavailableBl(boolean rsunavailableBl) {
		this.rsunavailableBl = rsunavailableBl;
	}

	@Column(name = "XCXCXC")
	public String getXcxcxc() {
		return this.xcxcxc;
	}

	public void setXcxcxc(String xcxcxc) {
		this.xcxcxc = xcxcxc;
	}

	@Column(name = "RSSectionHeaderID", nullable = false)
	public int getRssectionHeaderId() {
		return this.rssectionHeaderId;
	}

	public void setRssectionHeaderId(int rssectionHeaderId) {
		this.rssectionHeaderId = rssectionHeaderId;
	}

	@Column(name = "RSTmpNameTx_N")
	public String getRstmpNameTxN() {
		return this.rstmpNameTxN;
	}

	public void setRstmpNameTxN(String rstmpNameTxN) {
		this.rstmpNameTxN = rstmpNameTxN;
	}

	@Column(name = "RSTmpID", nullable = false)
	public int getRstmpId() {
		return this.rstmpId;
	}

	public void setRstmpId(int rstmpId) {
		this.rstmpId = rstmpId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRsreportSection")
	public Set<TRfreportField> getTRfreportFields() {
		return this.TRfreportFields;
	}

	public void setTRfreportFields(Set<TRfreportField> TRfreportFields) {
		this.TRfreportFields = TRfreportFields;
	}

}
