package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TS1salesSearch generated by hbm2java
 */
@Entity
@Table(name = "T_S1SalesSearch", uniqueConstraints = @UniqueConstraint(columnNames = "S1DescriptionTx"))
public class TS1salesSearch implements java.io.Serializable {

	private int s1salesSearchId;
	private String s1descriptionTx;
	private short s1searchTypeIn;
	private boolean s1useDatesBl;
	private Short s1yearInN;
	private Short s1periodInN;
	private Date s1rangeStartDateN;
	private Date s1rangeEndDateN;
	private Short s1levelOfDetailInN;
	private boolean s1includeInvoicesBl;
	private boolean s1includeRefundsBl;
	private boolean s1includeVouchersBl;
	private boolean s1includeCnsBl;
	private boolean s1includeAccPaysBl;
	private boolean s1includeGiftCertsBl;
	private boolean s1useStockBl;
	private Integer s1costCentreIdN;
	private Integer s1profitCentreIdN;
	private Integer s1stockTypeIdN;
	private Integer s1manufacturerIdN;
	private String s1barcodeNoTxN;
	private String s1stockNoTxN;
	private boolean s1usePaymentsBl;
	private boolean s1includeStdPaymentsBl;
	private boolean s1includeDepositsBl;
	private boolean s1useCustomerBl;
	private Integer s1customerIdN;
	private String s1custSearchTxN;
	private String s1firstNameTxN;
	private String s1lastNameTxN;
	private String s1address1txN;
	private String s1address2txN;
	private String s1address3txN;
	private String s1address4txN;
	private Integer s1stateIdN;
	private String s1postcodeTxN;
	private Integer s1countryIdN;
	private String s1emailTxN;
	private String s1suggestionTxN;
	private Date s1lastPurchStartDateN;
	private Date s1lastPurchEndDateN;
	private Integer s1storeIdN;
	private String s1computerNameTxN;
	private Integer s1employeeIdN;
	private Integer s1statusIdN;
	private String s1accountNoTxN;
	private String s1transactionNoTxN;
	private Integer s1taxBandIdN;
	private Integer s1discountBandIdN;
	private String s1orderByTxN;
	private String s1accountingPeriodIdN;
	private boolean s1includeQuotesBl;

	public TS1salesSearch() {
	}

	public TS1salesSearch(int s1salesSearchId, String s1descriptionTx, short s1searchTypeIn, boolean s1useDatesBl,
			boolean s1includeInvoicesBl, boolean s1includeRefundsBl, boolean s1includeVouchersBl,
			boolean s1includeCnsBl, boolean s1includeAccPaysBl, boolean s1includeGiftCertsBl, boolean s1useStockBl,
			boolean s1usePaymentsBl, boolean s1includeStdPaymentsBl, boolean s1includeDepositsBl,
			boolean s1useCustomerBl, boolean s1includeQuotesBl) {
		this.s1salesSearchId = s1salesSearchId;
		this.s1descriptionTx = s1descriptionTx;
		this.s1searchTypeIn = s1searchTypeIn;
		this.s1useDatesBl = s1useDatesBl;
		this.s1includeInvoicesBl = s1includeInvoicesBl;
		this.s1includeRefundsBl = s1includeRefundsBl;
		this.s1includeVouchersBl = s1includeVouchersBl;
		this.s1includeCnsBl = s1includeCnsBl;
		this.s1includeAccPaysBl = s1includeAccPaysBl;
		this.s1includeGiftCertsBl = s1includeGiftCertsBl;
		this.s1useStockBl = s1useStockBl;
		this.s1usePaymentsBl = s1usePaymentsBl;
		this.s1includeStdPaymentsBl = s1includeStdPaymentsBl;
		this.s1includeDepositsBl = s1includeDepositsBl;
		this.s1useCustomerBl = s1useCustomerBl;
		this.s1includeQuotesBl = s1includeQuotesBl;
	}

	public TS1salesSearch(int s1salesSearchId, String s1descriptionTx, short s1searchTypeIn, boolean s1useDatesBl,
			Short s1yearInN, Short s1periodInN, Date s1rangeStartDateN, Date s1rangeEndDateN, Short s1levelOfDetailInN,
			boolean s1includeInvoicesBl, boolean s1includeRefundsBl, boolean s1includeVouchersBl,
			boolean s1includeCnsBl, boolean s1includeAccPaysBl, boolean s1includeGiftCertsBl, boolean s1useStockBl,
			Integer s1costCentreIdN, Integer s1profitCentreIdN, Integer s1stockTypeIdN, Integer s1manufacturerIdN,
			String s1barcodeNoTxN, String s1stockNoTxN, boolean s1usePaymentsBl,
			boolean s1includeStdPaymentsBl, boolean s1includeDepositsBl, boolean s1useCustomerBl, Integer s1customerIdN,
			String s1custSearchTxN, String s1firstNameTxN, String s1lastNameTxN,
			String s1address1txN, String s1address2txN, String s1address3txN,
			String s1address4txN, Integer s1stateIdN, String s1postcodeTxN, Integer s1countryIdN,
			String s1emailTxN, String s1suggestionTxN, Date s1lastPurchStartDateN, Date s1lastPurchEndDateN,
			Integer s1storeIdN, String s1computerNameTxN, Integer s1employeeIdN, Integer s1statusIdN,
			String s1accountNoTxN, String s1transactionNoTxN, Integer s1taxBandIdN,
			Integer s1discountBandIdN, String s1orderByTxN, String s1accountingPeriodIdN,
			boolean s1includeQuotesBl) {
		this.s1salesSearchId = s1salesSearchId;
		this.s1descriptionTx = s1descriptionTx;
		this.s1searchTypeIn = s1searchTypeIn;
		this.s1useDatesBl = s1useDatesBl;
		this.s1yearInN = s1yearInN;
		this.s1periodInN = s1periodInN;
		this.s1rangeStartDateN = s1rangeStartDateN;
		this.s1rangeEndDateN = s1rangeEndDateN;
		this.s1levelOfDetailInN = s1levelOfDetailInN;
		this.s1includeInvoicesBl = s1includeInvoicesBl;
		this.s1includeRefundsBl = s1includeRefundsBl;
		this.s1includeVouchersBl = s1includeVouchersBl;
		this.s1includeCnsBl = s1includeCnsBl;
		this.s1includeAccPaysBl = s1includeAccPaysBl;
		this.s1includeGiftCertsBl = s1includeGiftCertsBl;
		this.s1useStockBl = s1useStockBl;
		this.s1costCentreIdN = s1costCentreIdN;
		this.s1profitCentreIdN = s1profitCentreIdN;
		this.s1stockTypeIdN = s1stockTypeIdN;
		this.s1manufacturerIdN = s1manufacturerIdN;
		this.s1barcodeNoTxN = s1barcodeNoTxN;
		this.s1stockNoTxN = s1stockNoTxN;
		this.s1usePaymentsBl = s1usePaymentsBl;
		this.s1includeStdPaymentsBl = s1includeStdPaymentsBl;
		this.s1includeDepositsBl = s1includeDepositsBl;
		this.s1useCustomerBl = s1useCustomerBl;
		this.s1customerIdN = s1customerIdN;
		this.s1custSearchTxN = s1custSearchTxN;
		this.s1firstNameTxN = s1firstNameTxN;
		this.s1lastNameTxN = s1lastNameTxN;
		this.s1address1txN = s1address1txN;
		this.s1address2txN = s1address2txN;
		this.s1address3txN = s1address3txN;
		this.s1address4txN = s1address4txN;
		this.s1stateIdN = s1stateIdN;
		this.s1postcodeTxN = s1postcodeTxN;
		this.s1countryIdN = s1countryIdN;
		this.s1emailTxN = s1emailTxN;
		this.s1suggestionTxN = s1suggestionTxN;
		this.s1lastPurchStartDateN = s1lastPurchStartDateN;
		this.s1lastPurchEndDateN = s1lastPurchEndDateN;
		this.s1storeIdN = s1storeIdN;
		this.s1computerNameTxN = s1computerNameTxN;
		this.s1employeeIdN = s1employeeIdN;
		this.s1statusIdN = s1statusIdN;
		this.s1accountNoTxN = s1accountNoTxN;
		this.s1transactionNoTxN = s1transactionNoTxN;
		this.s1taxBandIdN = s1taxBandIdN;
		this.s1discountBandIdN = s1discountBandIdN;
		this.s1orderByTxN = s1orderByTxN;
		this.s1accountingPeriodIdN = s1accountingPeriodIdN;
		this.s1includeQuotesBl = s1includeQuotesBl;
	}

	@Id

	@Column(name = "S1SalesSearchID", unique = true, nullable = false)
	public int getS1salesSearchId() {
		return this.s1salesSearchId;
	}

	public void setS1salesSearchId(int s1salesSearchId) {
		this.s1salesSearchId = s1salesSearchId;
	}

	@Column(name = "S1DescriptionTx", unique = true, nullable = false)
	public String getS1descriptionTx() {
		return this.s1descriptionTx;
	}

	public void setS1descriptionTx(String s1descriptionTx) {
		this.s1descriptionTx = s1descriptionTx;
	}

	@Column(name = "S1SearchTypeIn", nullable = false)
	public short getS1searchTypeIn() {
		return this.s1searchTypeIn;
	}

	public void setS1searchTypeIn(short s1searchTypeIn) {
		this.s1searchTypeIn = s1searchTypeIn;
	}

	@Column(name = "S1UseDatesBl", nullable = false)
	public boolean isS1useDatesBl() {
		return this.s1useDatesBl;
	}

	public void setS1useDatesBl(boolean s1useDatesBl) {
		this.s1useDatesBl = s1useDatesBl;
	}

	@Column(name = "S1YearIn_N")
	public Short getS1yearInN() {
		return this.s1yearInN;
	}

	public void setS1yearInN(Short s1yearInN) {
		this.s1yearInN = s1yearInN;
	}

	@Column(name = "S1PeriodIn_N")
	public Short getS1periodInN() {
		return this.s1periodInN;
	}

	public void setS1periodInN(Short s1periodInN) {
		this.s1periodInN = s1periodInN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "S1RangeStartDate_N", length = 23)
	public Date getS1rangeStartDateN() {
		return this.s1rangeStartDateN;
	}

	public void setS1rangeStartDateN(Date s1rangeStartDateN) {
		this.s1rangeStartDateN = s1rangeStartDateN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "S1RangeEndDate_N", length = 23)
	public Date getS1rangeEndDateN() {
		return this.s1rangeEndDateN;
	}

	public void setS1rangeEndDateN(Date s1rangeEndDateN) {
		this.s1rangeEndDateN = s1rangeEndDateN;
	}

	@Column(name = "S1LevelOfDetailIn_N")
	public Short getS1levelOfDetailInN() {
		return this.s1levelOfDetailInN;
	}

	public void setS1levelOfDetailInN(Short s1levelOfDetailInN) {
		this.s1levelOfDetailInN = s1levelOfDetailInN;
	}

	@Column(name = "S1IncludeInvoicesBl", nullable = false)
	public boolean isS1includeInvoicesBl() {
		return this.s1includeInvoicesBl;
	}

	public void setS1includeInvoicesBl(boolean s1includeInvoicesBl) {
		this.s1includeInvoicesBl = s1includeInvoicesBl;
	}

	@Column(name = "S1IncludeRefundsBl", nullable = false)
	public boolean isS1includeRefundsBl() {
		return this.s1includeRefundsBl;
	}

	public void setS1includeRefundsBl(boolean s1includeRefundsBl) {
		this.s1includeRefundsBl = s1includeRefundsBl;
	}

	@Column(name = "S1IncludeVouchersBl", nullable = false)
	public boolean isS1includeVouchersBl() {
		return this.s1includeVouchersBl;
	}

	public void setS1includeVouchersBl(boolean s1includeVouchersBl) {
		this.s1includeVouchersBl = s1includeVouchersBl;
	}

	@Column(name = "S1IncludeCNsBl", nullable = false)
	public boolean isS1includeCnsBl() {
		return this.s1includeCnsBl;
	}

	public void setS1includeCnsBl(boolean s1includeCnsBl) {
		this.s1includeCnsBl = s1includeCnsBl;
	}

	@Column(name = "S1IncludeAccPaysBl", nullable = false)
	public boolean isS1includeAccPaysBl() {
		return this.s1includeAccPaysBl;
	}

	public void setS1includeAccPaysBl(boolean s1includeAccPaysBl) {
		this.s1includeAccPaysBl = s1includeAccPaysBl;
	}

	@Column(name = "S1IncludeGiftCertsBl", nullable = false)
	public boolean isS1includeGiftCertsBl() {
		return this.s1includeGiftCertsBl;
	}

	public void setS1includeGiftCertsBl(boolean s1includeGiftCertsBl) {
		this.s1includeGiftCertsBl = s1includeGiftCertsBl;
	}

	@Column(name = "S1UseStockBl", nullable = false)
	public boolean isS1useStockBl() {
		return this.s1useStockBl;
	}

	public void setS1useStockBl(boolean s1useStockBl) {
		this.s1useStockBl = s1useStockBl;
	}

	@Column(name = "S1CostCentreID_N")
	public Integer getS1costCentreIdN() {
		return this.s1costCentreIdN;
	}

	public void setS1costCentreIdN(Integer s1costCentreIdN) {
		this.s1costCentreIdN = s1costCentreIdN;
	}

	@Column(name = "S1ProfitCentreID_N")
	public Integer getS1profitCentreIdN() {
		return this.s1profitCentreIdN;
	}

	public void setS1profitCentreIdN(Integer s1profitCentreIdN) {
		this.s1profitCentreIdN = s1profitCentreIdN;
	}

	@Column(name = "S1StockTypeID_N")
	public Integer getS1stockTypeIdN() {
		return this.s1stockTypeIdN;
	}

	public void setS1stockTypeIdN(Integer s1stockTypeIdN) {
		this.s1stockTypeIdN = s1stockTypeIdN;
	}

	@Column(name = "S1ManufacturerID_N")
	public Integer getS1manufacturerIdN() {
		return this.s1manufacturerIdN;
	}

	public void setS1manufacturerIdN(Integer s1manufacturerIdN) {
		this.s1manufacturerIdN = s1manufacturerIdN;
	}

	@Column(name = "S1BarcodeNoTx_N")
	public String getS1barcodeNoTxN() {
		return this.s1barcodeNoTxN;
	}

	public void setS1barcodeNoTxN(String s1barcodeNoTxN) {
		this.s1barcodeNoTxN = s1barcodeNoTxN;
	}

	@Column(name = "S1StockNoTx_N")
	public String getS1stockNoTxN() {
		return this.s1stockNoTxN;
	}

	public void setS1stockNoTxN(String s1stockNoTxN) {
		this.s1stockNoTxN = s1stockNoTxN;
	}

	@Column(name = "S1UsePaymentsBl", nullable = false)
	public boolean isS1usePaymentsBl() {
		return this.s1usePaymentsBl;
	}

	public void setS1usePaymentsBl(boolean s1usePaymentsBl) {
		this.s1usePaymentsBl = s1usePaymentsBl;
	}

	@Column(name = "S1IncludeStdPaymentsBl", nullable = false)
	public boolean isS1includeStdPaymentsBl() {
		return this.s1includeStdPaymentsBl;
	}

	public void setS1includeStdPaymentsBl(boolean s1includeStdPaymentsBl) {
		this.s1includeStdPaymentsBl = s1includeStdPaymentsBl;
	}

	@Column(name = "S1IncludeDepositsBl", nullable = false)
	public boolean isS1includeDepositsBl() {
		return this.s1includeDepositsBl;
	}

	public void setS1includeDepositsBl(boolean s1includeDepositsBl) {
		this.s1includeDepositsBl = s1includeDepositsBl;
	}

	@Column(name = "S1UseCustomerBl", nullable = false)
	public boolean isS1useCustomerBl() {
		return this.s1useCustomerBl;
	}

	public void setS1useCustomerBl(boolean s1useCustomerBl) {
		this.s1useCustomerBl = s1useCustomerBl;
	}

	@Column(name = "S1CustomerID_N")
	public Integer getS1customerIdN() {
		return this.s1customerIdN;
	}

	public void setS1customerIdN(Integer s1customerIdN) {
		this.s1customerIdN = s1customerIdN;
	}

	@Column(name = "S1CustSearchTx_N")
	public String getS1custSearchTxN() {
		return this.s1custSearchTxN;
	}

	public void setS1custSearchTxN(String s1custSearchTxN) {
		this.s1custSearchTxN = s1custSearchTxN;
	}

	@Column(name = "S1FirstNameTx_N")
	public String getS1firstNameTxN() {
		return this.s1firstNameTxN;
	}

	public void setS1firstNameTxN(String s1firstNameTxN) {
		this.s1firstNameTxN = s1firstNameTxN;
	}

	@Column(name = "S1LastNameTx_N")
	public String getS1lastNameTxN() {
		return this.s1lastNameTxN;
	}

	public void setS1lastNameTxN(String s1lastNameTxN) {
		this.s1lastNameTxN = s1lastNameTxN;
	}

	@Column(name = "S1Address1Tx_N")
	public String getS1address1txN() {
		return this.s1address1txN;
	}

	public void setS1address1txN(String s1address1txN) {
		this.s1address1txN = s1address1txN;
	}

	@Column(name = "S1Address2Tx_N")
	public String getS1address2txN() {
		return this.s1address2txN;
	}

	public void setS1address2txN(String s1address2txN) {
		this.s1address2txN = s1address2txN;
	}

	@Column(name = "S1Address3Tx_N")
	public String getS1address3txN() {
		return this.s1address3txN;
	}

	public void setS1address3txN(String s1address3txN) {
		this.s1address3txN = s1address3txN;
	}

	@Column(name = "S1Address4Tx_N")
	public String getS1address4txN() {
		return this.s1address4txN;
	}

	public void setS1address4txN(String s1address4txN) {
		this.s1address4txN = s1address4txN;
	}

	@Column(name = "S1StateID_N")
	public Integer getS1stateIdN() {
		return this.s1stateIdN;
	}

	public void setS1stateIdN(Integer s1stateIdN) {
		this.s1stateIdN = s1stateIdN;
	}

	@Column(name = "S1PostcodeTx_N")
	public String getS1postcodeTxN() {
		return this.s1postcodeTxN;
	}

	public void setS1postcodeTxN(String s1postcodeTxN) {
		this.s1postcodeTxN = s1postcodeTxN;
	}

	@Column(name = "S1CountryID_N")
	public Integer getS1countryIdN() {
		return this.s1countryIdN;
	}

	public void setS1countryIdN(Integer s1countryIdN) {
		this.s1countryIdN = s1countryIdN;
	}

	@Column(name = "S1EMailTx_N")
	public String getS1emailTxN() {
		return this.s1emailTxN;
	}

	public void setS1emailTxN(String s1emailTxN) {
		this.s1emailTxN = s1emailTxN;
	}

	@Column(name = "S1SuggestionTx_N")
	public String getS1suggestionTxN() {
		return this.s1suggestionTxN;
	}

	public void setS1suggestionTxN(String s1suggestionTxN) {
		this.s1suggestionTxN = s1suggestionTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "S1LastPurchStartDate_N", length = 23)
	public Date getS1lastPurchStartDateN() {
		return this.s1lastPurchStartDateN;
	}

	public void setS1lastPurchStartDateN(Date s1lastPurchStartDateN) {
		this.s1lastPurchStartDateN = s1lastPurchStartDateN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "S1LastPurchEndDate_N", length = 23)
	public Date getS1lastPurchEndDateN() {
		return this.s1lastPurchEndDateN;
	}

	public void setS1lastPurchEndDateN(Date s1lastPurchEndDateN) {
		this.s1lastPurchEndDateN = s1lastPurchEndDateN;
	}

	@Column(name = "S1StoreID_N")
	public Integer getS1storeIdN() {
		return this.s1storeIdN;
	}

	public void setS1storeIdN(Integer s1storeIdN) {
		this.s1storeIdN = s1storeIdN;
	}

	@Column(name = "S1ComputerNameTx_N")
	public String getS1computerNameTxN() {
		return this.s1computerNameTxN;
	}

	public void setS1computerNameTxN(String s1computerNameTxN) {
		this.s1computerNameTxN = s1computerNameTxN;
	}

	@Column(name = "S1EmployeeID_N")
	public Integer getS1employeeIdN() {
		return this.s1employeeIdN;
	}

	public void setS1employeeIdN(Integer s1employeeIdN) {
		this.s1employeeIdN = s1employeeIdN;
	}

	@Column(name = "S1StatusID_N")
	public Integer getS1statusIdN() {
		return this.s1statusIdN;
	}

	public void setS1statusIdN(Integer s1statusIdN) {
		this.s1statusIdN = s1statusIdN;
	}

	@Column(name = "S1AccountNoTx_N")
	public String getS1accountNoTxN() {
		return this.s1accountNoTxN;
	}

	public void setS1accountNoTxN(String s1accountNoTxN) {
		this.s1accountNoTxN = s1accountNoTxN;
	}

	@Column(name = "S1TransactionNoTx_N")
	public String getS1transactionNoTxN() {
		return this.s1transactionNoTxN;
	}

	public void setS1transactionNoTxN(String s1transactionNoTxN) {
		this.s1transactionNoTxN = s1transactionNoTxN;
	}

	@Column(name = "S1TaxBandID_N")
	public Integer getS1taxBandIdN() {
		return this.s1taxBandIdN;
	}

	public void setS1taxBandIdN(Integer s1taxBandIdN) {
		this.s1taxBandIdN = s1taxBandIdN;
	}

	@Column(name = "S1DiscountBandID_N")
	public Integer getS1discountBandIdN() {
		return this.s1discountBandIdN;
	}

	public void setS1discountBandIdN(Integer s1discountBandIdN) {
		this.s1discountBandIdN = s1discountBandIdN;
	}

	@Column(name = "S1OrderByTx_N")
	public String getS1orderByTxN() {
		return this.s1orderByTxN;
	}

	public void setS1orderByTxN(String s1orderByTxN) {
		this.s1orderByTxN = s1orderByTxN;
	}

	@Column(name = "S1AccountingPeriodID_N")
	public String getS1accountingPeriodIdN() {
		return this.s1accountingPeriodIdN;
	}

	public void setS1accountingPeriodIdN(String s1accountingPeriodIdN) {
		this.s1accountingPeriodIdN = s1accountingPeriodIdN;
	}

	@Column(name = "S1IncludeQuotesBl", nullable = false)
	public boolean isS1includeQuotesBl() {
		return this.s1includeQuotesBl;
	}

	public void setS1includeQuotesBl(boolean s1includeQuotesBl) {
		this.s1includeQuotesBl = s1includeQuotesBl;
	}

}
