package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TS2salesSearchCol generated by hbm2java
 */
@Entity
@Table(name = "T_S2SalesSearchCol")
public class TS2salesSearchCol implements java.io.Serializable {

	private TS2salesSearchColId id;

	public TS2salesSearchCol() {
	}

	public TS2salesSearchCol(TS2salesSearchColId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "s2salesSearchId", column = @Column(name = "S2SalesSearchID", nullable = false)),
			@AttributeOverride(name = "s2colInvisible", column = @Column(name = "S2ColInvisible", nullable = false)) })
	public TS2salesSearchColId getId() {
		return this.id;
	}

	public void setId(TS2salesSearchColId id) {
		this.id = id;
	}

}
