package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TS4salesSearchStockItem generated by hbm2java
 */
@Entity
@Table(name = "T_S4SalesSearchStockItem")
public class TS4salesSearchStockItem implements java.io.Serializable {

	private TS4salesSearchStockItemId id;

	public TS4salesSearchStockItem() {
	}

	public TS4salesSearchStockItem(TS4salesSearchStockItemId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "s4salesSearchId", column = @Column(name = "S4SalesSearchID", nullable = false)),
			@AttributeOverride(name = "s4stockId", column = @Column(name = "S4StockID", nullable = false)) })
	public TS4salesSearchStockItemId getId() {
		return this.id;
	}

	public void setId(TS4salesSearchStockItemId id) {
		this.id = id;
	}

}
