package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TS6storeConfig generated by hbm2java
 */
@Entity
@Table(name = "T_S6StoreConfig")
public class TS6storeConfig implements java.io.Serializable {

	private TS6storeConfigId id;
	private TSoStore TSoStoreByS6parentStoreId;
	private TSoStore TSoStoreByS6childStoreId;
	private TDtdataType TDtdataType;

	public TS6storeConfig() {
	}

	public TS6storeConfig(TS6storeConfigId id, TSoStore TSoStoreByS6parentStoreId, TSoStore TSoStoreByS6childStoreId,
			TDtdataType TDtdataType) {
		this.id = id;
		this.TSoStoreByS6parentStoreId = TSoStoreByS6parentStoreId;
		this.TSoStoreByS6childStoreId = TSoStoreByS6childStoreId;
		this.TDtdataType = TDtdataType;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "s6parentStoreId", column = @Column(name = "S6ParentStoreID", nullable = false)),
			@AttributeOverride(name = "s6childStoreId", column = @Column(name = "S6ChildStoreID", nullable = false)),
			@AttributeOverride(name = "s6dataTypeId", column = @Column(name = "S6DataTypeID", nullable = false)) })
	public TS6storeConfigId getId() {
		return this.id;
	}

	public void setId(TS6storeConfigId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "S6ParentStoreID", nullable = false, insertable = false, updatable = false)
	public TSoStore getTSoStoreByS6parentStoreId() {
		return this.TSoStoreByS6parentStoreId;
	}

	public void setTSoStoreByS6parentStoreId(TSoStore TSoStoreByS6parentStoreId) {
		this.TSoStoreByS6parentStoreId = TSoStoreByS6parentStoreId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "S6ChildStoreID", nullable = false, insertable = false, updatable = false)
	public TSoStore getTSoStoreByS6childStoreId() {
		return this.TSoStoreByS6childStoreId;
	}

	public void setTSoStoreByS6childStoreId(TSoStore TSoStoreByS6childStoreId) {
		this.TSoStoreByS6childStoreId = TSoStoreByS6childStoreId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "S6DataTypeID", nullable = false, insertable = false, updatable = false)
	public TDtdataType getTDtdataType() {
		return this.TDtdataType;
	}

	public void setTDtdataType(TDtdataType TDtdataType) {
		this.TDtdataType = TDtdataType;
	}

}
