package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TS9swtax generated by hbm2java
 */
@Entity
@Table(name = "T_S9SWTax")
public class TS9swtax implements java.io.Serializable {

	private TS9swtaxId id;

	public TS9swtax() {
	}

	public TS9swtax(TS9swtaxId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "s9invoiceType", column = @Column(name = "S9InvoiceType")),
			@AttributeOverride(name = "s9department", column = @Column(name = "S9Department")),
			@AttributeOverride(name = "s9taxTypeId", column = @Column(name = "S9TaxTypeID")) })
	public TS9swtaxId getId() {
		return this.id;
	}

	public void setId(TS9swtaxId id) {
		this.id = id;
	}

}
