package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TSbserviceBooking generated by hbm2java
 */
@Entity
@Table(name = "T_SBServiceBooking")
public class TSbserviceBooking implements java.io.Serializable {

	private int sbserviceBookingId;
	private TTstransStatus TTstransStatus;
	private TCccostCenter TCccostCenter;
	private TSoStore TSoStore;
	private TInInvoice TInInvoice;
	private TCuCust TCuCust;
	private TEmEmp TEmEmp;
	private Date sbcreationDate;
	private short sbcurrencyId;
	private float sbexchangeRateFl;
	private Date sblastUpdatedDate;
	private String sbnotesTxN;
	private Date sbvoidDateN;
	private String sbvoidReasonTxN;
	private BigDecimal sbpartsAmountMn;
	private BigDecimal sbpartTaxMn;
	private BigDecimal sbbookingLaborMn;
	private BigDecimal sbbookingLaborTaxMn;
	private BigDecimal sbbookingHandlingMn;
	private BigDecimal sbbookingHandlingTaxMn;
	private Date sbdueStartDate;
	private Date sbdueEndDate;
	private Integer sbticketNoInN;
	private Set<TIiinvoiceItem> TIiinvoiceItems = new HashSet<TIiinvoiceItem>(0);
	private Set<TSgServiceBookingItem> TSgServiceBookingItems = new HashSet<TSgServiceBookingItem>(0);
	private Set<TVivoucherItem> TVivoucherItems = new HashSet<TVivoucherItem>(0);

	public TSbserviceBooking() {
	}

	public TSbserviceBooking(int sbserviceBookingId, TTstransStatus TTstransStatus, TCccostCenter TCccostCenter,
			TSoStore TSoStore, TCuCust TCuCust, TEmEmp TEmEmp, Date sbcreationDate, short sbcurrencyId,
			float sbexchangeRateFl, Date sblastUpdatedDate, BigDecimal sbpartsAmountMn, BigDecimal sbpartTaxMn,
			BigDecimal sbbookingLaborMn, BigDecimal sbbookingLaborTaxMn, BigDecimal sbbookingHandlingMn,
			BigDecimal sbbookingHandlingTaxMn, Date sbdueStartDate, Date sbdueEndDate) {
		this.sbserviceBookingId = sbserviceBookingId;
		this.TTstransStatus = TTstransStatus;
		this.TCccostCenter = TCccostCenter;
		this.TSoStore = TSoStore;
		this.TCuCust = TCuCust;
		this.TEmEmp = TEmEmp;
		this.sbcreationDate = sbcreationDate;
		this.sbcurrencyId = sbcurrencyId;
		this.sbexchangeRateFl = sbexchangeRateFl;
		this.sblastUpdatedDate = sblastUpdatedDate;
		this.sbpartsAmountMn = sbpartsAmountMn;
		this.sbpartTaxMn = sbpartTaxMn;
		this.sbbookingLaborMn = sbbookingLaborMn;
		this.sbbookingLaborTaxMn = sbbookingLaborTaxMn;
		this.sbbookingHandlingMn = sbbookingHandlingMn;
		this.sbbookingHandlingTaxMn = sbbookingHandlingTaxMn;
		this.sbdueStartDate = sbdueStartDate;
		this.sbdueEndDate = sbdueEndDate;
	}

	public TSbserviceBooking(int sbserviceBookingId, TTstransStatus TTstransStatus, TCccostCenter TCccostCenter,
			TSoStore TSoStore, TInInvoice TInInvoice, TCuCust TCuCust, TEmEmp TEmEmp, Date sbcreationDate,
			short sbcurrencyId, float sbexchangeRateFl, Date sblastUpdatedDate, String sbnotesTxN,
			Date sbvoidDateN, String sbvoidReasonTxN, BigDecimal sbpartsAmountMn, BigDecimal sbpartTaxMn,
			BigDecimal sbbookingLaborMn, BigDecimal sbbookingLaborTaxMn, BigDecimal sbbookingHandlingMn,
			BigDecimal sbbookingHandlingTaxMn, Date sbdueStartDate, Date sbdueEndDate, Integer sbticketNoInN,
			Set<TIiinvoiceItem> TIiinvoiceItems, Set<TSgServiceBookingItem> TSgServiceBookingItems,
			Set<TVivoucherItem> TVivoucherItems) {
		this.sbserviceBookingId = sbserviceBookingId;
		this.TTstransStatus = TTstransStatus;
		this.TCccostCenter = TCccostCenter;
		this.TSoStore = TSoStore;
		this.TInInvoice = TInInvoice;
		this.TCuCust = TCuCust;
		this.TEmEmp = TEmEmp;
		this.sbcreationDate = sbcreationDate;
		this.sbcurrencyId = sbcurrencyId;
		this.sbexchangeRateFl = sbexchangeRateFl;
		this.sblastUpdatedDate = sblastUpdatedDate;
		this.sbnotesTxN = sbnotesTxN;
		this.sbvoidDateN = sbvoidDateN;
		this.sbvoidReasonTxN = sbvoidReasonTxN;
		this.sbpartsAmountMn = sbpartsAmountMn;
		this.sbpartTaxMn = sbpartTaxMn;
		this.sbbookingLaborMn = sbbookingLaborMn;
		this.sbbookingLaborTaxMn = sbbookingLaborTaxMn;
		this.sbbookingHandlingMn = sbbookingHandlingMn;
		this.sbbookingHandlingTaxMn = sbbookingHandlingTaxMn;
		this.sbdueStartDate = sbdueStartDate;
		this.sbdueEndDate = sbdueEndDate;
		this.sbticketNoInN = sbticketNoInN;
		this.TIiinvoiceItems = TIiinvoiceItems;
		this.TSgServiceBookingItems = TSgServiceBookingItems;
		this.TVivoucherItems = TVivoucherItems;
	}

	@Id

	@Column(name = "SBServiceBookingID", unique = true, nullable = false)
	public int getSbserviceBookingId() {
		return this.sbserviceBookingId;
	}

	public void setSbserviceBookingId(int sbserviceBookingId) {
		this.sbserviceBookingId = sbserviceBookingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SBStatusID", nullable = false)
	public TTstransStatus getTTstransStatus() {
		return this.TTstransStatus;
	}

	public void setTTstransStatus(TTstransStatus TTstransStatus) {
		this.TTstransStatus = TTstransStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SBCostCenterID", nullable = false)
	public TCccostCenter getTCccostCenter() {
		return this.TCccostCenter;
	}

	public void setTCccostCenter(TCccostCenter TCccostCenter) {
		this.TCccostCenter = TCccostCenter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SBStoreID", nullable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SBInvoiceID_N")
	public TInInvoice getTInInvoice() {
		return this.TInInvoice;
	}

	public void setTInInvoice(TInInvoice TInInvoice) {
		this.TInInvoice = TInInvoice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SBCustID", nullable = false)
	public TCuCust getTCuCust() {
		return this.TCuCust;
	}

	public void setTCuCust(TCuCust TCuCust) {
		this.TCuCust = TCuCust;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SBEmpID", nullable = false)
	public TEmEmp getTEmEmp() {
		return this.TEmEmp;
	}

	public void setTEmEmp(TEmEmp TEmEmp) {
		this.TEmEmp = TEmEmp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SBCreationDate", nullable = false, length = 23)
	public Date getSbcreationDate() {
		return this.sbcreationDate;
	}

	public void setSbcreationDate(Date sbcreationDate) {
		this.sbcreationDate = sbcreationDate;
	}

	@Column(name = "SBCurrencyID", nullable = false)
	public short getSbcurrencyId() {
		return this.sbcurrencyId;
	}

	public void setSbcurrencyId(short sbcurrencyId) {
		this.sbcurrencyId = sbcurrencyId;
	}

	@Column(name = "SBExchangeRateFl", nullable = false, precision = 24, scale = 0)
	public float getSbexchangeRateFl() {
		return this.sbexchangeRateFl;
	}

	public void setSbexchangeRateFl(float sbexchangeRateFl) {
		this.sbexchangeRateFl = sbexchangeRateFl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SBLastUpdatedDate", nullable = false, length = 23)
	public Date getSblastUpdatedDate() {
		return this.sblastUpdatedDate;
	}

	public void setSblastUpdatedDate(Date sblastUpdatedDate) {
		this.sblastUpdatedDate = sblastUpdatedDate;
	}

	@Column(name = "SBNotesTx_N")
	public String getSbnotesTxN() {
		return this.sbnotesTxN;
	}

	public void setSbnotesTxN(String sbnotesTxN) {
		this.sbnotesTxN = sbnotesTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SBVoidDate_N", length = 23)
	public Date getSbvoidDateN() {
		return this.sbvoidDateN;
	}

	public void setSbvoidDateN(Date sbvoidDateN) {
		this.sbvoidDateN = sbvoidDateN;
	}

	@Column(name = "SBVoidReasonTx_N")
	public String getSbvoidReasonTxN() {
		return this.sbvoidReasonTxN;
	}

	public void setSbvoidReasonTxN(String sbvoidReasonTxN) {
		this.sbvoidReasonTxN = sbvoidReasonTxN;
	}

	@Column(name = "SBPartsAmountMn", nullable = false, scale = 4)
	public BigDecimal getSbpartsAmountMn() {
		return this.sbpartsAmountMn;
	}

	public void setSbpartsAmountMn(BigDecimal sbpartsAmountMn) {
		this.sbpartsAmountMn = sbpartsAmountMn;
	}

	@Column(name = "SBPartTaxMn", nullable = false, scale = 4)
	public BigDecimal getSbpartTaxMn() {
		return this.sbpartTaxMn;
	}

	public void setSbpartTaxMn(BigDecimal sbpartTaxMn) {
		this.sbpartTaxMn = sbpartTaxMn;
	}

	@Column(name = "SBBookingLaborMn", nullable = false, scale = 4)
	public BigDecimal getSbbookingLaborMn() {
		return this.sbbookingLaborMn;
	}

	public void setSbbookingLaborMn(BigDecimal sbbookingLaborMn) {
		this.sbbookingLaborMn = sbbookingLaborMn;
	}

	@Column(name = "SBBookingLaborTaxMn", nullable = false, scale = 4)
	public BigDecimal getSbbookingLaborTaxMn() {
		return this.sbbookingLaborTaxMn;
	}

	public void setSbbookingLaborTaxMn(BigDecimal sbbookingLaborTaxMn) {
		this.sbbookingLaborTaxMn = sbbookingLaborTaxMn;
	}

	@Column(name = "SBBookingHandlingMn", nullable = false, scale = 4)
	public BigDecimal getSbbookingHandlingMn() {
		return this.sbbookingHandlingMn;
	}

	public void setSbbookingHandlingMn(BigDecimal sbbookingHandlingMn) {
		this.sbbookingHandlingMn = sbbookingHandlingMn;
	}

	@Column(name = "SBBookingHandlingTaxMn", nullable = false, scale = 4)
	public BigDecimal getSbbookingHandlingTaxMn() {
		return this.sbbookingHandlingTaxMn;
	}

	public void setSbbookingHandlingTaxMn(BigDecimal sbbookingHandlingTaxMn) {
		this.sbbookingHandlingTaxMn = sbbookingHandlingTaxMn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SBDueStartDate", nullable = false, length = 23)
	public Date getSbdueStartDate() {
		return this.sbdueStartDate;
	}

	public void setSbdueStartDate(Date sbdueStartDate) {
		this.sbdueStartDate = sbdueStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SBDueEndDate", nullable = false, length = 23)
	public Date getSbdueEndDate() {
		return this.sbdueEndDate;
	}

	public void setSbdueEndDate(Date sbdueEndDate) {
		this.sbdueEndDate = sbdueEndDate;
	}

	@Column(name = "SBTicketNoIn_N")
	public Integer getSbticketNoInN() {
		return this.sbticketNoInN;
	}

	public void setSbticketNoInN(Integer sbticketNoInN) {
		this.sbticketNoInN = sbticketNoInN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSbserviceBooking")
	public Set<TIiinvoiceItem> getTIiinvoiceItems() {
		return this.TIiinvoiceItems;
	}

	public void setTIiinvoiceItems(Set<TIiinvoiceItem> TIiinvoiceItems) {
		this.TIiinvoiceItems = TIiinvoiceItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSbserviceBooking")
	public Set<TSgServiceBookingItem> getTSgServiceBookingItems() {
		return this.TSgServiceBookingItems;
	}

	public void setTSgServiceBookingItems(Set<TSgServiceBookingItem> TSgServiceBookingItems) {
		this.TSgServiceBookingItems = TSgServiceBookingItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSbserviceBooking")
	public Set<TVivoucherItem> getTVivoucherItems() {
		return this.TVivoucherItems;
	}

	public void setTVivoucherItems(Set<TVivoucherItem> TVivoucherItems) {
		this.TVivoucherItems = TVivoucherItems;
	}

}
