package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TSeState generated by hbm2java
 */
@Entity
@Table(name = "T_SeState", uniqueConstraints = { @UniqueConstraint(columnNames = { "SeShortNameTx", "SeCountryID" }),
		@UniqueConstraint(columnNames = "SePADIKeyTx"),
		@UniqueConstraint(columnNames = { "SeStateTx", "SeCountryID" }) })
public class TSeState implements java.io.Serializable {

	private int seStateId;
	private TCyCountry TCyCountry;
	private String seStateTx;
	private String seShortNameTx;
	private boolean seUnavailableBl;
	private Date seLastUpdatedDate;
	private String sePadikeyTx;
	private Integer seNewPadikeyInN;
	private Set<TVsvalidState> TVsvalidStates = new HashSet<TVsvalidState>(0);
	private Set<TXcshippingCountry> TXcshippingCountries = new HashSet<TXcshippingCountry>(0);
	private Set<TCuCust> TCuCustsForCuStateIdN = new HashSet<TCuCust>(0);
	private Set<TSoStore> TSoStores = new HashSet<TSoStore>(0);
	private Set<TCuCust> TCuCustsForCuWstateIdN = new HashSet<TCuCust>(0);
	private Set<TLcLocation> TLcLocations = new HashSet<TLcLocation>(0);

	public TSeState() {
	}

	public TSeState(int seStateId, TCyCountry TCyCountry, String seStateTx, String seShortNameTx,
			boolean seUnavailableBl, Date seLastUpdatedDate, String sePadikeyTx) {
		this.seStateId = seStateId;
		this.TCyCountry = TCyCountry;
		this.seStateTx = seStateTx;
		this.seShortNameTx = seShortNameTx;
		this.seUnavailableBl = seUnavailableBl;
		this.seLastUpdatedDate = seLastUpdatedDate;
		this.sePadikeyTx = sePadikeyTx;
	}

	public TSeState(int seStateId, TCyCountry TCyCountry, String seStateTx, String seShortNameTx,
			boolean seUnavailableBl, Date seLastUpdatedDate, String sePadikeyTx, Integer seNewPadikeyInN,
			Set<TVsvalidState> TVsvalidStates, Set<TXcshippingCountry> TXcshippingCountries,
			Set<TCuCust> TCuCustsForCuStateIdN, Set<TSoStore> TSoStores, Set<TCuCust> TCuCustsForCuWstateIdN,
			Set<TLcLocation> TLcLocations) {
		this.seStateId = seStateId;
		this.TCyCountry = TCyCountry;
		this.seStateTx = seStateTx;
		this.seShortNameTx = seShortNameTx;
		this.seUnavailableBl = seUnavailableBl;
		this.seLastUpdatedDate = seLastUpdatedDate;
		this.sePadikeyTx = sePadikeyTx;
		this.seNewPadikeyInN = seNewPadikeyInN;
		this.TVsvalidStates = TVsvalidStates;
		this.TXcshippingCountries = TXcshippingCountries;
		this.TCuCustsForCuStateIdN = TCuCustsForCuStateIdN;
		this.TSoStores = TSoStores;
		this.TCuCustsForCuWstateIdN = TCuCustsForCuWstateIdN;
		this.TLcLocations = TLcLocations;
	}

	@Id

	@Column(name = "SeStateID", unique = true, nullable = false)
	public int getSeStateId() {
		return this.seStateId;
	}

	public void setSeStateId(int seStateId) {
		this.seStateId = seStateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SeCountryID", nullable = false)
	public TCyCountry getTCyCountry() {
		return this.TCyCountry;
	}

	public void setTCyCountry(TCyCountry TCyCountry) {
		this.TCyCountry = TCyCountry;
	}

	@Column(name = "SeStateTx", nullable = false)
	public String getSeStateTx() {
		return this.seStateTx;
	}

	public void setSeStateTx(String seStateTx) {
		this.seStateTx = seStateTx;
	}

	@Column(name = "SeShortNameTx", nullable = false)
	public String getSeShortNameTx() {
		return this.seShortNameTx;
	}

	public void setSeShortNameTx(String seShortNameTx) {
		this.seShortNameTx = seShortNameTx;
	}

	@Column(name = "SeUnavailableBl", nullable = false)
	public boolean isSeUnavailableBl() {
		return this.seUnavailableBl;
	}

	public void setSeUnavailableBl(boolean seUnavailableBl) {
		this.seUnavailableBl = seUnavailableBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SeLastUpdatedDate", nullable = false, length = 23)
	public Date getSeLastUpdatedDate() {
		return this.seLastUpdatedDate;
	}

	public void setSeLastUpdatedDate(Date seLastUpdatedDate) {
		this.seLastUpdatedDate = seLastUpdatedDate;
	}

	@Column(name = "SePADIKeyTx", unique = true, nullable = false)
	public String getSePadikeyTx() {
		return this.sePadikeyTx;
	}

	public void setSePadikeyTx(String sePadikeyTx) {
		this.sePadikeyTx = sePadikeyTx;
	}

	@Column(name = "SeNewPADIKeyIn_N")
	public Integer getSeNewPadikeyInN() {
		return this.seNewPadikeyInN;
	}

	public void setSeNewPadikeyInN(Integer seNewPadikeyInN) {
		this.seNewPadikeyInN = seNewPadikeyInN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSeState")
	public Set<TVsvalidState> getTVsvalidStates() {
		return this.TVsvalidStates;
	}

	public void setTVsvalidStates(Set<TVsvalidState> TVsvalidStates) {
		this.TVsvalidStates = TVsvalidStates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSeState")
	public Set<TXcshippingCountry> getTXcshippingCountries() {
		return this.TXcshippingCountries;
	}

	public void setTXcshippingCountries(Set<TXcshippingCountry> TXcshippingCountries) {
		this.TXcshippingCountries = TXcshippingCountries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSeStateByCuStateIdN")
	public Set<TCuCust> getTCuCustsForCuStateIdN() {
		return this.TCuCustsForCuStateIdN;
	}

	public void setTCuCustsForCuStateIdN(Set<TCuCust> TCuCustsForCuStateIdN) {
		this.TCuCustsForCuStateIdN = TCuCustsForCuStateIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSeState")
	public Set<TSoStore> getTSoStores() {
		return this.TSoStores;
	}

	public void setTSoStores(Set<TSoStore> TSoStores) {
		this.TSoStores = TSoStores;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSeStateByCuWstateIdN")
	public Set<TCuCust> getTCuCustsForCuWstateIdN() {
		return this.TCuCustsForCuWstateIdN;
	}

	public void setTCuCustsForCuWstateIdN(Set<TCuCust> TCuCustsForCuWstateIdN) {
		this.TCuCustsForCuWstateIdN = TCuCustsForCuWstateIdN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSeState")
	public Set<TLcLocation> getTLcLocations() {
		return this.TLcLocations;
	}

	public void setTLcLocations(Set<TLcLocation> TLcLocations) {
		this.TLcLocations = TLcLocations;
	}

}
