package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TSfStockOffer generated by hbm2java
 */
@Entity
@Table(name = "T_SfStockOffer")
public class TSfStockOffer implements java.io.Serializable {

	private int sfOfferId;
	private TSistockItem TSistockItem;
	private Date sfStartDateN;
	private Date sfEndDateN;
	private Set<TSmStockOfferItem> TSmStockOfferItems = new HashSet<TSmStockOfferItem>(0);

	public TSfStockOffer() {
	}

	public TSfStockOffer(int sfOfferId, TSistockItem TSistockItem) {
		this.sfOfferId = sfOfferId;
		this.TSistockItem = TSistockItem;
	}

	public TSfStockOffer(int sfOfferId, TSistockItem TSistockItem, Date sfStartDateN, Date sfEndDateN,
			Set<TSmStockOfferItem> TSmStockOfferItems) {
		this.sfOfferId = sfOfferId;
		this.TSistockItem = TSistockItem;
		this.sfStartDateN = sfStartDateN;
		this.sfEndDateN = sfEndDateN;
		this.TSmStockOfferItems = TSmStockOfferItems;
	}

	@Id

	@Column(name = "SfOfferID", unique = true, nullable = false)
	public int getSfOfferId() {
		return this.sfOfferId;
	}

	public void setSfOfferId(int sfOfferId) {
		this.sfOfferId = sfOfferId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SfStockItemID", nullable = false)
	public TSistockItem getTSistockItem() {
		return this.TSistockItem;
	}

	public void setTSistockItem(TSistockItem TSistockItem) {
		this.TSistockItem = TSistockItem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SfStartDate_N", length = 23)
	public Date getSfStartDateN() {
		return this.sfStartDateN;
	}

	public void setSfStartDateN(Date sfStartDateN) {
		this.sfStartDateN = sfStartDateN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SfEndDate_N", length = 23)
	public Date getSfEndDateN() {
		return this.sfEndDateN;
	}

	public void setSfEndDateN(Date sfEndDateN) {
		this.sfEndDateN = sfEndDateN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSfStockOffer")
	public Set<TSmStockOfferItem> getTSmStockOfferItems() {
		return this.TSmStockOfferItems;
	}

	public void setTSmStockOfferItems(Set<TSmStockOfferItem> TSmStockOfferItems) {
		this.TSmStockOfferItems = TSmStockOfferItems;
	}

}
