package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TSistockItem generated by hbm2java
 */
@Entity
@Table(name = "T_SIStockItem")
public class TSistockItem implements java.io.Serializable {

	private int sistockItemId;
	private TClColor TClColorBySisecondaryColorIdN;
	private TClColor TClColorBySiprimaryColorIdN;
	private TEzSize TEzSize;
	private TSuSupplier TSuSupplier;
	private TStstockType TStstockType;
	private TDtdataType TDtdataType;
	private String sistockItemTx;
	private String sistockNoTx;
	private Integer sisubStockTypeIdN;
	private boolean siunavailableBl;
	private String sibarcodeNoTxN;
	private String sivideoTxN;
	private Date silastUpdatedDate;
	private float sicommissionRateFl;
	private boolean siserialNosBl;
	private boolean simaintainStockLevelBl;
	private boolean sipackageBl;
	private boolean sipackageItemsIncludedBl;
	private boolean sirequiredBl;
	private String siimageTxN;
	private String siponotesTxN;
	private boolean simultiSaleBl;
	private short simultiSaleQtyIn;
	private double sidepositMn;
	private Date sicreationDate;
	private boolean siinheritFromMasterBl;
	private boolean siroomBookRelatedBl;
	private boolean siclubRelatedBl;
	private String sistockItem2txN;
	private String sinotesTxN;
	private boolean siforPobl;
	private String sidescriptionTxN;
	private String sispecialOfferTxN;
	private Double siweightFlN;
	private boolean sishowPriceInEolbl;
	private boolean sicalcTaxOnShippingAddressBl;
	private int sishippingPeriodIn;
	private Integer siparentIdN;
	private int sidisplayOrderIn;
	private String siimage2txN;
	private String siimage3txN;
	private boolean siuseEventRulesBl;
	private int siclickActionId;
	private String siclickUrlTextTxN;
	private String siclickActionParamsTxN;
	private String siclickActionPromptTxN;
	private boolean sideliverToRoomBl;
	private boolean sieolshowPackagePageBl;
	private int sirelatedProductsIn;
	private String siimage4txN;
	private String siimage5txN;
	private int siforeColorIn;
	private int sibackColorIn;
	private double silengthFl;
	private double siwidthFl;
	private double siheightFl;
	private int sipricingMethodId;
	private Float siloyaltyRateFl;
	private String sieoltabCaptionTxN;
	private String sieoltabCaption2txN;
	private String sieoltabCaption3txN;
	private String sieoltabCaption4txN;
	private String sieoldescription2txN;
	private String sieoldescription3txN;
	private String sieoldescription4txN;
	private Set<TCdCustOrder> TCdCustOrders = new HashSet<TCdCustOrder>(0);
	private Set<TPipoitem> TPipoitems = new HashSet<TPipoitem>(0);
	private Set<TSistockItem> TSistockItemsForR1parentStockItemId = new HashSet<TSistockItem>(0);
	private Set<TVivoucherItem> TVivoucherItems = new HashSet<TVivoucherItem>(0);
	private Set<TPgPackage> TPgPackages = new HashSet<TPgPackage>(0);
	private Set<TPaPodeliveryItem> TPaPodeliveryItems = new HashSet<TPaPodeliveryItem>(0);
	private Set<TA4propertyValue> TA4propertyValues = new HashSet<TA4propertyValue>(0);
	private Set<TGrgiftRegistry> TGrgiftRegistries = new HashSet<TGrgiftRegistry>(0);
	private Set<TQiquoteItem> TQiquoteItems = new HashSet<TQiquoteItem>(0);
	private Set<TRqqtyBand> TRqqtyBands = new HashSet<TRqqtyBand>(0);
	private Set<TSzStockCourseType> TSzStockCourseTypes = new HashSet<TSzStockCourseType>(0);
	private Set<TSistockItem> TSistockItemsForR1childStockItemId = new HashSet<TSistockItem>(0);
	private Set<TLcLocation> TLcLocations = new HashSet<TLcLocation>(0);
	private Set<TSjShippingPrice> TSjShippingPrices = new HashSet<TSjShippingPrice>(0);
	private Set<TSnserialNo> TSnserialNos = new HashSet<TSnserialNo>(0);
	private Set<TCbClub> TCbClubs = new HashSet<TCbClub>(0);
	private Set<TRpretailPrice> TRpretailPrices = new HashSet<TRpretailPrice>(0);
	private Set<TSqstockTrip> TSqstockTrips = new HashSet<TSqstockTrip>(0);
	private Set<TIiinvoiceItem> TIiinvoiceItems = new HashSet<TIiinvoiceItem>(0);
	private Set<TSpservicePart> TSpserviceParts = new HashSet<TSpservicePart>(0);
	private Set<TSvStockRoom> TSvStockRooms = new HashSet<TSvStockRoom>(0);
	private TS0stockClub TS0stockClub;
	private Set<TSyStockTrip> TSyStockTrips = new HashSet<TSyStockTrip>(0);
	private Set<TSlstockCourse> TSlstockCourses = new HashSet<TSlstockCourse>(0);
	private Set<TP3packageGroup> TP3packageGroups = new HashSet<TP3packageGroup>(0);
	private Set<TSkSupplierStockItem> TSkSupplierStockItems = new HashSet<TSkSupplierStockItem>(0);
	private Set<TTitransferItem> TTitransferItems = new HashSet<TTitransferItem>(0);
	private Set<TExExpense> TExExpenses = new HashSet<TExExpense>(0);
	private Set<TSfStockOffer> TSfStockOffers = new HashSet<TSfStockOffer>(0);
	private Set<TZlStoreStockItem> TZlStoreStockItems = new HashSet<TZlStoreStockItem>(0);
	private Set<TTttaskType> TTttaskTypes = new HashSet<TTttaskType>(0);
	private Set<TCeCostPrice> TCeCostPrices = new HashSet<TCeCostPrice>(0);

	public TSistockItem() {
	}

	public TSistockItem(int sistockItemId, TSuSupplier TSuSupplier, TStstockType TStstockType,
			String sistockItemTx, String sistockNoTx, boolean siunavailableBl, Date silastUpdatedDate,
			float sicommissionRateFl, boolean siserialNosBl, boolean simaintainStockLevelBl, boolean sipackageBl,
			boolean sipackageItemsIncludedBl, boolean sirequiredBl, boolean simultiSaleBl, short simultiSaleQtyIn,
			double sidepositMn, Date sicreationDate, boolean siinheritFromMasterBl, boolean siroomBookRelatedBl,
			boolean siclubRelatedBl, boolean siforPobl, boolean sishowPriceInEolbl,
			boolean sicalcTaxOnShippingAddressBl, int sishippingPeriodIn, int sidisplayOrderIn,
			boolean siuseEventRulesBl, int siclickActionId, boolean sideliverToRoomBl, boolean sieolshowPackagePageBl,
			int sirelatedProductsIn, int siforeColorIn, int sibackColorIn, double silengthFl, double siwidthFl,
			double siheightFl, int sipricingMethodId) {
		this.sistockItemId = sistockItemId;
		this.TSuSupplier = TSuSupplier;
		this.TStstockType = TStstockType;
		this.sistockItemTx = sistockItemTx;
		this.sistockNoTx = sistockNoTx;
		this.siunavailableBl = siunavailableBl;
		this.silastUpdatedDate = silastUpdatedDate;
		this.sicommissionRateFl = sicommissionRateFl;
		this.siserialNosBl = siserialNosBl;
		this.simaintainStockLevelBl = simaintainStockLevelBl;
		this.sipackageBl = sipackageBl;
		this.sipackageItemsIncludedBl = sipackageItemsIncludedBl;
		this.sirequiredBl = sirequiredBl;
		this.simultiSaleBl = simultiSaleBl;
		this.simultiSaleQtyIn = simultiSaleQtyIn;
		this.sidepositMn = sidepositMn;
		this.sicreationDate = sicreationDate;
		this.siinheritFromMasterBl = siinheritFromMasterBl;
		this.siroomBookRelatedBl = siroomBookRelatedBl;
		this.siclubRelatedBl = siclubRelatedBl;
		this.siforPobl = siforPobl;
		this.sishowPriceInEolbl = sishowPriceInEolbl;
		this.sicalcTaxOnShippingAddressBl = sicalcTaxOnShippingAddressBl;
		this.sishippingPeriodIn = sishippingPeriodIn;
		this.sidisplayOrderIn = sidisplayOrderIn;
		this.siuseEventRulesBl = siuseEventRulesBl;
		this.siclickActionId = siclickActionId;
		this.sideliverToRoomBl = sideliverToRoomBl;
		this.sieolshowPackagePageBl = sieolshowPackagePageBl;
		this.sirelatedProductsIn = sirelatedProductsIn;
		this.siforeColorIn = siforeColorIn;
		this.sibackColorIn = sibackColorIn;
		this.silengthFl = silengthFl;
		this.siwidthFl = siwidthFl;
		this.siheightFl = siheightFl;
		this.sipricingMethodId = sipricingMethodId;
	}

	public TSistockItem(int sistockItemId, TClColor TClColorBySisecondaryColorIdN, TClColor TClColorBySiprimaryColorIdN,
			TEzSize TEzSize, TSuSupplier TSuSupplier, TStstockType TStstockType, TDtdataType TDtdataType,
			String sistockItemTx, String sistockNoTx, Integer sisubStockTypeIdN, boolean siunavailableBl,
			String sibarcodeNoTxN, String sivideoTxN, Date silastUpdatedDate, float sicommissionRateFl,
			boolean siserialNosBl, boolean simaintainStockLevelBl, boolean sipackageBl,
			boolean sipackageItemsIncludedBl, boolean sirequiredBl, String siimageTxN, String siponotesTxN,
			boolean simultiSaleBl, short simultiSaleQtyIn, double sidepositMn, Date sicreationDate,
			boolean siinheritFromMasterBl, boolean siroomBookRelatedBl, boolean siclubRelatedBl,
			String sistockItem2txN, String sinotesTxN, boolean siforPobl, String sidescriptionTxN,
			String sispecialOfferTxN, Double siweightFlN, boolean sishowPriceInEolbl,
			boolean sicalcTaxOnShippingAddressBl, int sishippingPeriodIn, Integer siparentIdN, int sidisplayOrderIn,
			String siimage2txN, String siimage3txN, boolean siuseEventRulesBl, int siclickActionId,
			String siclickUrlTextTxN, String siclickActionParamsTxN, String siclickActionPromptTxN,
			boolean sideliverToRoomBl, boolean sieolshowPackagePageBl, int sirelatedProductsIn,
			String siimage4txN, String siimage5txN, int siforeColorIn, int sibackColorIn, double silengthFl,
			double siwidthFl, double siheightFl, int sipricingMethodId, Float siloyaltyRateFl,
			String sieoltabCaptionTxN, String sieoltabCaption2txN, String sieoltabCaption3txN,
			String sieoltabCaption4txN, String sieoldescription2txN, String sieoldescription3txN,
			String sieoldescription4txN, Set<TCdCustOrder> TCdCustOrders, Set<TPipoitem> TPipoitems,
			Set<TSistockItem> TSistockItemsForR1parentStockItemId, Set<TVivoucherItem> TVivoucherItems,
			Set<TPgPackage> TPgPackages, Set<TPaPodeliveryItem> TPaPodeliveryItems,
			Set<TA4propertyValue> TA4propertyValues, Set<TGrgiftRegistry> TGrgiftRegistries,
			Set<TQiquoteItem> TQiquoteItems, Set<TRqqtyBand> TRqqtyBands, Set<TSzStockCourseType> TSzStockCourseTypes,
			Set<TSistockItem> TSistockItemsForR1childStockItemId, Set<TLcLocation> TLcLocations,
			Set<TSjShippingPrice> TSjShippingPrices, Set<TSnserialNo> TSnserialNos, Set<TCbClub> TCbClubs,
			Set<TRpretailPrice> TRpretailPrices, Set<TSqstockTrip> TSqstockTrips, Set<TIiinvoiceItem> TIiinvoiceItems,
			Set<TSpservicePart> TSpserviceParts, Set<TSvStockRoom> TSvStockRooms, TS0stockClub TS0stockClub,
			Set<TSyStockTrip> TSyStockTrips, Set<TSlstockCourse> TSlstockCourses, Set<TP3packageGroup> TP3packageGroups,
			Set<TSkSupplierStockItem> TSkSupplierStockItems, Set<TTitransferItem> TTitransferItems,
			Set<TExExpense> TExExpenses, Set<TSfStockOffer> TSfStockOffers, Set<TZlStoreStockItem> TZlStoreStockItems,
			Set<TTttaskType> TTttaskTypes, Set<TCeCostPrice> TCeCostPrices) {
		this.sistockItemId = sistockItemId;
		this.TClColorBySisecondaryColorIdN = TClColorBySisecondaryColorIdN;
		this.TClColorBySiprimaryColorIdN = TClColorBySiprimaryColorIdN;
		this.TEzSize = TEzSize;
		this.TSuSupplier = TSuSupplier;
		this.TStstockType = TStstockType;
		this.TDtdataType = TDtdataType;
		this.sistockItemTx = sistockItemTx;
		this.sistockNoTx = sistockNoTx;
		this.sisubStockTypeIdN = sisubStockTypeIdN;
		this.siunavailableBl = siunavailableBl;
		this.sibarcodeNoTxN = sibarcodeNoTxN;
		this.sivideoTxN = sivideoTxN;
		this.silastUpdatedDate = silastUpdatedDate;
		this.sicommissionRateFl = sicommissionRateFl;
		this.siserialNosBl = siserialNosBl;
		this.simaintainStockLevelBl = simaintainStockLevelBl;
		this.sipackageBl = sipackageBl;
		this.sipackageItemsIncludedBl = sipackageItemsIncludedBl;
		this.sirequiredBl = sirequiredBl;
		this.siimageTxN = siimageTxN;
		this.siponotesTxN = siponotesTxN;
		this.simultiSaleBl = simultiSaleBl;
		this.simultiSaleQtyIn = simultiSaleQtyIn;
		this.sidepositMn = sidepositMn;
		this.sicreationDate = sicreationDate;
		this.siinheritFromMasterBl = siinheritFromMasterBl;
		this.siroomBookRelatedBl = siroomBookRelatedBl;
		this.siclubRelatedBl = siclubRelatedBl;
		this.sistockItem2txN = sistockItem2txN;
		this.sinotesTxN = sinotesTxN;
		this.siforPobl = siforPobl;
		this.sidescriptionTxN = sidescriptionTxN;
		this.sispecialOfferTxN = sispecialOfferTxN;
		this.siweightFlN = siweightFlN;
		this.sishowPriceInEolbl = sishowPriceInEolbl;
		this.sicalcTaxOnShippingAddressBl = sicalcTaxOnShippingAddressBl;
		this.sishippingPeriodIn = sishippingPeriodIn;
		this.siparentIdN = siparentIdN;
		this.sidisplayOrderIn = sidisplayOrderIn;
		this.siimage2txN = siimage2txN;
		this.siimage3txN = siimage3txN;
		this.siuseEventRulesBl = siuseEventRulesBl;
		this.siclickActionId = siclickActionId;
		this.siclickUrlTextTxN = siclickUrlTextTxN;
		this.siclickActionParamsTxN = siclickActionParamsTxN;
		this.siclickActionPromptTxN = siclickActionPromptTxN;
		this.sideliverToRoomBl = sideliverToRoomBl;
		this.sieolshowPackagePageBl = sieolshowPackagePageBl;
		this.sirelatedProductsIn = sirelatedProductsIn;
		this.siimage4txN = siimage4txN;
		this.siimage5txN = siimage5txN;
		this.siforeColorIn = siforeColorIn;
		this.sibackColorIn = sibackColorIn;
		this.silengthFl = silengthFl;
		this.siwidthFl = siwidthFl;
		this.siheightFl = siheightFl;
		this.sipricingMethodId = sipricingMethodId;
		this.siloyaltyRateFl = siloyaltyRateFl;
		this.sieoltabCaptionTxN = sieoltabCaptionTxN;
		this.sieoltabCaption2txN = sieoltabCaption2txN;
		this.sieoltabCaption3txN = sieoltabCaption3txN;
		this.sieoltabCaption4txN = sieoltabCaption4txN;
		this.sieoldescription2txN = sieoldescription2txN;
		this.sieoldescription3txN = sieoldescription3txN;
		this.sieoldescription4txN = sieoldescription4txN;
		this.TCdCustOrders = TCdCustOrders;
		this.TPipoitems = TPipoitems;
		this.TSistockItemsForR1parentStockItemId = TSistockItemsForR1parentStockItemId;
		this.TVivoucherItems = TVivoucherItems;
		this.TPgPackages = TPgPackages;
		this.TPaPodeliveryItems = TPaPodeliveryItems;
		this.TA4propertyValues = TA4propertyValues;
		this.TGrgiftRegistries = TGrgiftRegistries;
		this.TQiquoteItems = TQiquoteItems;
		this.TRqqtyBands = TRqqtyBands;
		this.TSzStockCourseTypes = TSzStockCourseTypes;
		this.TSistockItemsForR1childStockItemId = TSistockItemsForR1childStockItemId;
		this.TLcLocations = TLcLocations;
		this.TSjShippingPrices = TSjShippingPrices;
		this.TSnserialNos = TSnserialNos;
		this.TCbClubs = TCbClubs;
		this.TRpretailPrices = TRpretailPrices;
		this.TSqstockTrips = TSqstockTrips;
		this.TIiinvoiceItems = TIiinvoiceItems;
		this.TSpserviceParts = TSpserviceParts;
		this.TSvStockRooms = TSvStockRooms;
		this.TS0stockClub = TS0stockClub;
		this.TSyStockTrips = TSyStockTrips;
		this.TSlstockCourses = TSlstockCourses;
		this.TP3packageGroups = TP3packageGroups;
		this.TSkSupplierStockItems = TSkSupplierStockItems;
		this.TTitransferItems = TTitransferItems;
		this.TExExpenses = TExExpenses;
		this.TSfStockOffers = TSfStockOffers;
		this.TZlStoreStockItems = TZlStoreStockItems;
		this.TTttaskTypes = TTttaskTypes;
		this.TCeCostPrices = TCeCostPrices;
	}

	@Id

	@Column(name = "SIStockItemID", unique = true, nullable = false)
	public int getSistockItemId() {
		return this.sistockItemId;
	}

	public void setSistockItemId(int sistockItemId) {
		this.sistockItemId = sistockItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SISecondaryColorID_N")
	public TClColor getTClColorBySisecondaryColorIdN() {
		return this.TClColorBySisecondaryColorIdN;
	}

	public void setTClColorBySisecondaryColorIdN(TClColor TClColorBySisecondaryColorIdN) {
		this.TClColorBySisecondaryColorIdN = TClColorBySisecondaryColorIdN;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SIPrimaryColorID_N")
	public TClColor getTClColorBySiprimaryColorIdN() {
		return this.TClColorBySiprimaryColorIdN;
	}

	public void setTClColorBySiprimaryColorIdN(TClColor TClColorBySiprimaryColorIdN) {
		this.TClColorBySiprimaryColorIdN = TClColorBySiprimaryColorIdN;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SISizeID_N")
	public TEzSize getTEzSize() {
		return this.TEzSize;
	}

	public void setTEzSize(TEzSize TEzSize) {
		this.TEzSize = TEzSize;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SIManufacturerID", nullable = false)
	public TSuSupplier getTSuSupplier() {
		return this.TSuSupplier;
	}

	public void setTSuSupplier(TSuSupplier TSuSupplier) {
		this.TSuSupplier = TSuSupplier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SIStockTypeID", nullable = false)
	public TStstockType getTStstockType() {
		return this.TStstockType;
	}

	public void setTStstockType(TStstockType TStstockType) {
		this.TStstockType = TStstockType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SIEventDataTypeID_N")
	public TDtdataType getTDtdataType() {
		return this.TDtdataType;
	}

	public void setTDtdataType(TDtdataType TDtdataType) {
		this.TDtdataType = TDtdataType;
	}

	@Column(name = "SIStockItemTx", nullable = false)
	public String getSistockItemTx() {
		return this.sistockItemTx;
	}

	public void setSistockItemTx(String sistockItemTx) {
		this.sistockItemTx = sistockItemTx;
	}

	@Column(name = "SIStockNoTx", nullable = false)
	public String getSistockNoTx() {
		return this.sistockNoTx;
	}

	public void setSistockNoTx(String sistockNoTx) {
		this.sistockNoTx = sistockNoTx;
	}

	@Column(name = "SISubStockTypeID_N")
	public Integer getSisubStockTypeIdN() {
		return this.sisubStockTypeIdN;
	}

	public void setSisubStockTypeIdN(Integer sisubStockTypeIdN) {
		this.sisubStockTypeIdN = sisubStockTypeIdN;
	}

	@Column(name = "SIUnavailableBl", nullable = false)
	public boolean isSiunavailableBl() {
		return this.siunavailableBl;
	}

	public void setSiunavailableBl(boolean siunavailableBl) {
		this.siunavailableBl = siunavailableBl;
	}

	@Column(name = "SIBarcodeNoTx_N")
	public String getSibarcodeNoTxN() {
		return this.sibarcodeNoTxN;
	}

	public void setSibarcodeNoTxN(String sibarcodeNoTxN) {
		this.sibarcodeNoTxN = sibarcodeNoTxN;
	}

	@Column(name = "SIVideoTx_N")
	public String getSivideoTxN() {
		return this.sivideoTxN;
	}

	public void setSivideoTxN(String sivideoTxN) {
		this.sivideoTxN = sivideoTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SILastUpdatedDate", nullable = false, length = 23)
	public Date getSilastUpdatedDate() {
		return this.silastUpdatedDate;
	}

	public void setSilastUpdatedDate(Date silastUpdatedDate) {
		this.silastUpdatedDate = silastUpdatedDate;
	}

	@Column(name = "SICommissionRateFl", nullable = false, precision = 24, scale = 0)
	public float getSicommissionRateFl() {
		return this.sicommissionRateFl;
	}

	public void setSicommissionRateFl(float sicommissionRateFl) {
		this.sicommissionRateFl = sicommissionRateFl;
	}

	@Column(name = "SISerialNosBl", nullable = false)
	public boolean isSiserialNosBl() {
		return this.siserialNosBl;
	}

	public void setSiserialNosBl(boolean siserialNosBl) {
		this.siserialNosBl = siserialNosBl;
	}

	@Column(name = "SIMaintainStockLevelBl", nullable = false)
	public boolean isSimaintainStockLevelBl() {
		return this.simaintainStockLevelBl;
	}

	public void setSimaintainStockLevelBl(boolean simaintainStockLevelBl) {
		this.simaintainStockLevelBl = simaintainStockLevelBl;
	}

	@Column(name = "SIPackageBl", nullable = false)
	public boolean isSipackageBl() {
		return this.sipackageBl;
	}

	public void setSipackageBl(boolean sipackageBl) {
		this.sipackageBl = sipackageBl;
	}

	@Column(name = "SIPackageItemsIncludedBl", nullable = false)
	public boolean isSipackageItemsIncludedBl() {
		return this.sipackageItemsIncludedBl;
	}

	public void setSipackageItemsIncludedBl(boolean sipackageItemsIncludedBl) {
		this.sipackageItemsIncludedBl = sipackageItemsIncludedBl;
	}

	@Column(name = "SIRequiredBl", nullable = false)
	public boolean isSirequiredBl() {
		return this.sirequiredBl;
	}

	public void setSirequiredBl(boolean sirequiredBl) {
		this.sirequiredBl = sirequiredBl;
	}

	@Column(name = "SIImageTx_N")
	public String getSiimageTxN() {
		return this.siimageTxN;
	}

	public void setSiimageTxN(String siimageTxN) {
		this.siimageTxN = siimageTxN;
	}

	@Column(name = "SIPONotesTx_N")
	public String getSiponotesTxN() {
		return this.siponotesTxN;
	}

	public void setSiponotesTxN(String siponotesTxN) {
		this.siponotesTxN = siponotesTxN;
	}

	@Column(name = "SIMultiSaleBl", nullable = false)
	public boolean isSimultiSaleBl() {
		return this.simultiSaleBl;
	}

	public void setSimultiSaleBl(boolean simultiSaleBl) {
		this.simultiSaleBl = simultiSaleBl;
	}

	@Column(name = "SIMultiSaleQtyIn", nullable = false)
	public short getSimultiSaleQtyIn() {
		return this.simultiSaleQtyIn;
	}

	public void setSimultiSaleQtyIn(short simultiSaleQtyIn) {
		this.simultiSaleQtyIn = simultiSaleQtyIn;
	}

	@Column(name = "SIDepositMn", nullable = false, precision = 53, scale = 0)
	public double getSidepositMn() {
		return this.sidepositMn;
	}

	public void setSidepositMn(double sidepositMn) {
		this.sidepositMn = sidepositMn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SICreationDate", nullable = false, length = 23)
	public Date getSicreationDate() {
		return this.sicreationDate;
	}

	public void setSicreationDate(Date sicreationDate) {
		this.sicreationDate = sicreationDate;
	}

	@Column(name = "SIInheritFromMasterBl", nullable = false)
	public boolean isSiinheritFromMasterBl() {
		return this.siinheritFromMasterBl;
	}

	public void setSiinheritFromMasterBl(boolean siinheritFromMasterBl) {
		this.siinheritFromMasterBl = siinheritFromMasterBl;
	}

	@Column(name = "SIRoomBookRelatedBl", nullable = false)
	public boolean isSiroomBookRelatedBl() {
		return this.siroomBookRelatedBl;
	}

	public void setSiroomBookRelatedBl(boolean siroomBookRelatedBl) {
		this.siroomBookRelatedBl = siroomBookRelatedBl;
	}

	@Column(name = "SIClubRelatedBl", nullable = false)
	public boolean isSiclubRelatedBl() {
		return this.siclubRelatedBl;
	}

	public void setSiclubRelatedBl(boolean siclubRelatedBl) {
		this.siclubRelatedBl = siclubRelatedBl;
	}

	@Column(name = "SIStockItem2Tx_N")
	public String getSistockItem2txN() {
		return this.sistockItem2txN;
	}

	public void setSistockItem2txN(String sistockItem2txN) {
		this.sistockItem2txN = sistockItem2txN;
	}

	@Column(name = "SINotesTx_N")
	public String getSinotesTxN() {
		return this.sinotesTxN;
	}

	public void setSinotesTxN(String sinotesTxN) {
		this.sinotesTxN = sinotesTxN;
	}

	@Column(name = "SIForPOBl", nullable = false)
	public boolean isSiforPobl() {
		return this.siforPobl;
	}

	public void setSiforPobl(boolean siforPobl) {
		this.siforPobl = siforPobl;
	}

	@Column(name = "SIDescriptionTx_N")
	public String getSidescriptionTxN() {
		return this.sidescriptionTxN;
	}

	public void setSidescriptionTxN(String sidescriptionTxN) {
		this.sidescriptionTxN = sidescriptionTxN;
	}

	@Column(name = "SISpecialOfferTx_N")
	public String getSispecialOfferTxN() {
		return this.sispecialOfferTxN;
	}

	public void setSispecialOfferTxN(String sispecialOfferTxN) {
		this.sispecialOfferTxN = sispecialOfferTxN;
	}

	@Column(name = "SIWeightFl_N", precision = 53, scale = 0)
	public Double getSiweightFlN() {
		return this.siweightFlN;
	}

	public void setSiweightFlN(Double siweightFlN) {
		this.siweightFlN = siweightFlN;
	}

	@Column(name = "SIShowPriceInEOLBl", nullable = false)
	public boolean isSishowPriceInEolbl() {
		return this.sishowPriceInEolbl;
	}

	public void setSishowPriceInEolbl(boolean sishowPriceInEolbl) {
		this.sishowPriceInEolbl = sishowPriceInEolbl;
	}

	@Column(name = "SICalcTaxOnShippingAddressBl", nullable = false)
	public boolean isSicalcTaxOnShippingAddressBl() {
		return this.sicalcTaxOnShippingAddressBl;
	}

	public void setSicalcTaxOnShippingAddressBl(boolean sicalcTaxOnShippingAddressBl) {
		this.sicalcTaxOnShippingAddressBl = sicalcTaxOnShippingAddressBl;
	}

	@Column(name = "SIShippingPeriodIn", nullable = false)
	public int getSishippingPeriodIn() {
		return this.sishippingPeriodIn;
	}

	public void setSishippingPeriodIn(int sishippingPeriodIn) {
		this.sishippingPeriodIn = sishippingPeriodIn;
	}

	@Column(name = "SIParentID_N")
	public Integer getSiparentIdN() {
		return this.siparentIdN;
	}

	public void setSiparentIdN(Integer siparentIdN) {
		this.siparentIdN = siparentIdN;
	}

	@Column(name = "SIDisplayOrderIn", nullable = false)
	public int getSidisplayOrderIn() {
		return this.sidisplayOrderIn;
	}

	public void setSidisplayOrderIn(int sidisplayOrderIn) {
		this.sidisplayOrderIn = sidisplayOrderIn;
	}

	@Column(name = "SIImage2Tx_N")
	public String getSiimage2txN() {
		return this.siimage2txN;
	}

	public void setSiimage2txN(String siimage2txN) {
		this.siimage2txN = siimage2txN;
	}

	@Column(name = "SIImage3Tx_N")
	public String getSiimage3txN() {
		return this.siimage3txN;
	}

	public void setSiimage3txN(String siimage3txN) {
		this.siimage3txN = siimage3txN;
	}

	@Column(name = "SIUseEventRulesBl", nullable = false)
	public boolean isSiuseEventRulesBl() {
		return this.siuseEventRulesBl;
	}

	public void setSiuseEventRulesBl(boolean siuseEventRulesBl) {
		this.siuseEventRulesBl = siuseEventRulesBl;
	}

	@Column(name = "SIClickActionID", nullable = false)
	public int getSiclickActionId() {
		return this.siclickActionId;
	}

	public void setSiclickActionId(int siclickActionId) {
		this.siclickActionId = siclickActionId;
	}

	@Column(name = "SIClickUrlTextTx_N")
	public String getSiclickUrlTextTxN() {
		return this.siclickUrlTextTxN;
	}

	public void setSiclickUrlTextTxN(String siclickUrlTextTxN) {
		this.siclickUrlTextTxN = siclickUrlTextTxN;
	}

	@Column(name = "SIClickActionParamsTx_N")
	public String getSiclickActionParamsTxN() {
		return this.siclickActionParamsTxN;
	}

	public void setSiclickActionParamsTxN(String siclickActionParamsTxN) {
		this.siclickActionParamsTxN = siclickActionParamsTxN;
	}

	@Column(name = "SIClickActionPromptTx_N")
	public String getSiclickActionPromptTxN() {
		return this.siclickActionPromptTxN;
	}

	public void setSiclickActionPromptTxN(String siclickActionPromptTxN) {
		this.siclickActionPromptTxN = siclickActionPromptTxN;
	}

	@Column(name = "SIDeliverToRoomBl", nullable = false)
	public boolean isSideliverToRoomBl() {
		return this.sideliverToRoomBl;
	}

	public void setSideliverToRoomBl(boolean sideliverToRoomBl) {
		this.sideliverToRoomBl = sideliverToRoomBl;
	}

	@Column(name = "SIEOLShowPackagePageBl", nullable = false)
	public boolean isSieolshowPackagePageBl() {
		return this.sieolshowPackagePageBl;
	}

	public void setSieolshowPackagePageBl(boolean sieolshowPackagePageBl) {
		this.sieolshowPackagePageBl = sieolshowPackagePageBl;
	}

	@Column(name = "SIRelatedProductsIn", nullable = false)
	public int getSirelatedProductsIn() {
		return this.sirelatedProductsIn;
	}

	public void setSirelatedProductsIn(int sirelatedProductsIn) {
		this.sirelatedProductsIn = sirelatedProductsIn;
	}

	@Column(name = "SIImage4Tx_N")
	public String getSiimage4txN() {
		return this.siimage4txN;
	}

	public void setSiimage4txN(String siimage4txN) {
		this.siimage4txN = siimage4txN;
	}

	@Column(name = "SIImage5Tx_N")
	public String getSiimage5txN() {
		return this.siimage5txN;
	}

	public void setSiimage5txN(String siimage5txN) {
		this.siimage5txN = siimage5txN;
	}

	@Column(name = "SIForeColorIn", nullable = false)
	public int getSiforeColorIn() {
		return this.siforeColorIn;
	}

	public void setSiforeColorIn(int siforeColorIn) {
		this.siforeColorIn = siforeColorIn;
	}

	@Column(name = "SIBackColorIn", nullable = false)
	public int getSibackColorIn() {
		return this.sibackColorIn;
	}

	public void setSibackColorIn(int sibackColorIn) {
		this.sibackColorIn = sibackColorIn;
	}

	@Column(name = "SILengthFl", nullable = false, precision = 53, scale = 0)
	public double getSilengthFl() {
		return this.silengthFl;
	}

	public void setSilengthFl(double silengthFl) {
		this.silengthFl = silengthFl;
	}

	@Column(name = "SIWidthFl", nullable = false, precision = 53, scale = 0)
	public double getSiwidthFl() {
		return this.siwidthFl;
	}

	public void setSiwidthFl(double siwidthFl) {
		this.siwidthFl = siwidthFl;
	}

	@Column(name = "SIHeightFl", nullable = false, precision = 53, scale = 0)
	public double getSiheightFl() {
		return this.siheightFl;
	}

	public void setSiheightFl(double siheightFl) {
		this.siheightFl = siheightFl;
	}

	@Column(name = "SIPricingMethodID", nullable = false)
	public int getSipricingMethodId() {
		return this.sipricingMethodId;
	}

	public void setSipricingMethodId(int sipricingMethodId) {
		this.sipricingMethodId = sipricingMethodId;
	}

	@Column(name = "SILoyaltyRateFl", precision = 24, scale = 0)
	public Float getSiloyaltyRateFl() {
		return this.siloyaltyRateFl;
	}

	public void setSiloyaltyRateFl(Float siloyaltyRateFl) {
		this.siloyaltyRateFl = siloyaltyRateFl;
	}

	@Column(name = "SIEOLTabCaptionTx_N")
	public String getSieoltabCaptionTxN() {
		return this.sieoltabCaptionTxN;
	}

	public void setSieoltabCaptionTxN(String sieoltabCaptionTxN) {
		this.sieoltabCaptionTxN = sieoltabCaptionTxN;
	}

	@Column(name = "SIEOLTabCaption2Tx_N")
	public String getSieoltabCaption2txN() {
		return this.sieoltabCaption2txN;
	}

	public void setSieoltabCaption2txN(String sieoltabCaption2txN) {
		this.sieoltabCaption2txN = sieoltabCaption2txN;
	}

	@Column(name = "SIEOLTabCaption3Tx_N")
	public String getSieoltabCaption3txN() {
		return this.sieoltabCaption3txN;
	}

	public void setSieoltabCaption3txN(String sieoltabCaption3txN) {
		this.sieoltabCaption3txN = sieoltabCaption3txN;
	}

	@Column(name = "SIEOLTabCaption4Tx_N")
	public String getSieoltabCaption4txN() {
		return this.sieoltabCaption4txN;
	}

	public void setSieoltabCaption4txN(String sieoltabCaption4txN) {
		this.sieoltabCaption4txN = sieoltabCaption4txN;
	}

	@Column(name = "SIEOLDescription2Tx_N")
	public String getSieoldescription2txN() {
		return this.sieoldescription2txN;
	}

	public void setSieoldescription2txN(String sieoldescription2txN) {
		this.sieoldescription2txN = sieoldescription2txN;
	}

	@Column(name = "SIEOLDescription3Tx_N")
	public String getSieoldescription3txN() {
		return this.sieoldescription3txN;
	}

	public void setSieoldescription3txN(String sieoldescription3txN) {
		this.sieoldescription3txN = sieoldescription3txN;
	}

	@Column(name = "SIEOLDescription4Tx_N")
	public String getSieoldescription4txN() {
		return this.sieoldescription4txN;
	}

	public void setSieoldescription4txN(String sieoldescription4txN) {
		this.sieoldescription4txN = sieoldescription4txN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TCdCustOrder> getTCdCustOrders() {
		return this.TCdCustOrders;
	}

	public void setTCdCustOrders(Set<TCdCustOrder> TCdCustOrders) {
		this.TCdCustOrders = TCdCustOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TPipoitem> getTPipoitems() {
		return this.TPipoitems;
	}

	public void setTPipoitems(Set<TPipoitem> TPipoitems) {
		this.TPipoitems = TPipoitems;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_R1RelatedProduct", joinColumns = {
			@JoinColumn(name = "R1ChildStockItemID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "R1ParentStockItemID", nullable = false, updatable = false) })
	public Set<TSistockItem> getTSistockItemsForR1parentStockItemId() {
		return this.TSistockItemsForR1parentStockItemId;
	}

	public void setTSistockItemsForR1parentStockItemId(Set<TSistockItem> TSistockItemsForR1parentStockItemId) {
		this.TSistockItemsForR1parentStockItemId = TSistockItemsForR1parentStockItemId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TVivoucherItem> getTVivoucherItems() {
		return this.TVivoucherItems;
	}

	public void setTVivoucherItems(Set<TVivoucherItem> TVivoucherItems) {
		this.TVivoucherItems = TVivoucherItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TPgPackage> getTPgPackages() {
		return this.TPgPackages;
	}

	public void setTPgPackages(Set<TPgPackage> TPgPackages) {
		this.TPgPackages = TPgPackages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TPaPodeliveryItem> getTPaPodeliveryItems() {
		return this.TPaPodeliveryItems;
	}

	public void setTPaPodeliveryItems(Set<TPaPodeliveryItem> TPaPodeliveryItems) {
		this.TPaPodeliveryItems = TPaPodeliveryItems;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_A5StockItemPropertyValue", joinColumns = {
			@JoinColumn(name = "A5StockItemID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "A5PropertyValueID", nullable = false, updatable = false) })
	public Set<TA4propertyValue> getTA4propertyValues() {
		return this.TA4propertyValues;
	}

	public void setTA4propertyValues(Set<TA4propertyValue> TA4propertyValues) {
		this.TA4propertyValues = TA4propertyValues;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TGrgiftRegistry> getTGrgiftRegistries() {
		return this.TGrgiftRegistries;
	}

	public void setTGrgiftRegistries(Set<TGrgiftRegistry> TGrgiftRegistries) {
		this.TGrgiftRegistries = TGrgiftRegistries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TQiquoteItem> getTQiquoteItems() {
		return this.TQiquoteItems;
	}

	public void setTQiquoteItems(Set<TQiquoteItem> TQiquoteItems) {
		this.TQiquoteItems = TQiquoteItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TRqqtyBand> getTRqqtyBands() {
		return this.TRqqtyBands;
	}

	public void setTRqqtyBands(Set<TRqqtyBand> TRqqtyBands) {
		this.TRqqtyBands = TRqqtyBands;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TSzStockCourseType> getTSzStockCourseTypes() {
		return this.TSzStockCourseTypes;
	}

	public void setTSzStockCourseTypes(Set<TSzStockCourseType> TSzStockCourseTypes) {
		this.TSzStockCourseTypes = TSzStockCourseTypes;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_R1RelatedProduct", joinColumns = {
			@JoinColumn(name = "R1ParentStockItemID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "R1ChildStockItemID", nullable = false, updatable = false) })
	public Set<TSistockItem> getTSistockItemsForR1childStockItemId() {
		return this.TSistockItemsForR1childStockItemId;
	}

	public void setTSistockItemsForR1childStockItemId(Set<TSistockItem> TSistockItemsForR1childStockItemId) {
		this.TSistockItemsForR1childStockItemId = TSistockItemsForR1childStockItemId;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_LSLocationStockItem", joinColumns = {
			@JoinColumn(name = "LSStockItemId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "LSLocationId", nullable = false, updatable = false) })
	public Set<TLcLocation> getTLcLocations() {
		return this.TLcLocations;
	}

	public void setTLcLocations(Set<TLcLocation> TLcLocations) {
		this.TLcLocations = TLcLocations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TSjShippingPrice> getTSjShippingPrices() {
		return this.TSjShippingPrices;
	}

	public void setTSjShippingPrices(Set<TSjShippingPrice> TSjShippingPrices) {
		this.TSjShippingPrices = TSjShippingPrices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TSnserialNo> getTSnserialNos() {
		return this.TSnserialNos;
	}

	public void setTSnserialNos(Set<TSnserialNo> TSnserialNos) {
		this.TSnserialNos = TSnserialNos;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_CQClubStockItem", joinColumns = {
			@JoinColumn(name = "CQStockItemId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "CQClubId", nullable = false, updatable = false) })
	public Set<TCbClub> getTCbClubs() {
		return this.TCbClubs;
	}

	public void setTCbClubs(Set<TCbClub> TCbClubs) {
		this.TCbClubs = TCbClubs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TRpretailPrice> getTRpretailPrices() {
		return this.TRpretailPrices;
	}

	public void setTRpretailPrices(Set<TRpretailPrice> TRpretailPrices) {
		this.TRpretailPrices = TRpretailPrices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TSqstockTrip> getTSqstockTrips() {
		return this.TSqstockTrips;
	}

	public void setTSqstockTrips(Set<TSqstockTrip> TSqstockTrips) {
		this.TSqstockTrips = TSqstockTrips;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TIiinvoiceItem> getTIiinvoiceItems() {
		return this.TIiinvoiceItems;
	}

	public void setTIiinvoiceItems(Set<TIiinvoiceItem> TIiinvoiceItems) {
		this.TIiinvoiceItems = TIiinvoiceItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TSpservicePart> getTSpserviceParts() {
		return this.TSpserviceParts;
	}

	public void setTSpserviceParts(Set<TSpservicePart> TSpserviceParts) {
		this.TSpserviceParts = TSpserviceParts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TSvStockRoom> getTSvStockRooms() {
		return this.TSvStockRooms;
	}

	public void setTSvStockRooms(Set<TSvStockRoom> TSvStockRooms) {
		this.TSvStockRooms = TSvStockRooms;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public TS0stockClub getTS0stockClub() {
		return this.TS0stockClub;
	}

	public void setTS0stockClub(TS0stockClub TS0stockClub) {
		this.TS0stockClub = TS0stockClub;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TSyStockTrip> getTSyStockTrips() {
		return this.TSyStockTrips;
	}

	public void setTSyStockTrips(Set<TSyStockTrip> TSyStockTrips) {
		this.TSyStockTrips = TSyStockTrips;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TSlstockCourse> getTSlstockCourses() {
		return this.TSlstockCourses;
	}

	public void setTSlstockCourses(Set<TSlstockCourse> TSlstockCourses) {
		this.TSlstockCourses = TSlstockCourses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TP3packageGroup> getTP3packageGroups() {
		return this.TP3packageGroups;
	}

	public void setTP3packageGroups(Set<TP3packageGroup> TP3packageGroups) {
		this.TP3packageGroups = TP3packageGroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TSkSupplierStockItem> getTSkSupplierStockItems() {
		return this.TSkSupplierStockItems;
	}

	public void setTSkSupplierStockItems(Set<TSkSupplierStockItem> TSkSupplierStockItems) {
		this.TSkSupplierStockItems = TSkSupplierStockItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TTitransferItem> getTTitransferItems() {
		return this.TTitransferItems;
	}

	public void setTTitransferItems(Set<TTitransferItem> TTitransferItems) {
		this.TTitransferItems = TTitransferItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TExExpense> getTExExpenses() {
		return this.TExExpenses;
	}

	public void setTExExpenses(Set<TExExpense> TExExpenses) {
		this.TExExpenses = TExExpenses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TSfStockOffer> getTSfStockOffers() {
		return this.TSfStockOffers;
	}

	public void setTSfStockOffers(Set<TSfStockOffer> TSfStockOffers) {
		this.TSfStockOffers = TSfStockOffers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TZlStoreStockItem> getTZlStoreStockItems() {
		return this.TZlStoreStockItems;
	}

	public void setTZlStoreStockItems(Set<TZlStoreStockItem> TZlStoreStockItems) {
		this.TZlStoreStockItems = TZlStoreStockItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TTttaskType> getTTttaskTypes() {
		return this.TTttaskTypes;
	}

	public void setTTttaskTypes(Set<TTttaskType> TTttaskTypes) {
		this.TTttaskTypes = TTttaskTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSistockItem")
	public Set<TCeCostPrice> getTCeCostPrices() {
		return this.TCeCostPrices;
	}

	public void setTCeCostPrices(Set<TCeCostPrice> TCeCostPrices) {
		this.TCeCostPrices = TCeCostPrices;
	}

}
