package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TSjShippingPrice generated by hbm2java
 */
@Entity
@Table(name = "T_SjShippingPrice")
public class TSjShippingPrice implements java.io.Serializable {

	private int sjShippingPriceId;
	private TSistockItem TSistockItem;
	private TSoStore TSoStore;
	private TXzshippingZone TXzshippingZone;
	private double sjLowerBoundsFl;
	private double sjUpperBoundsFl;
	private double sjPriceMn;
	private Date sjCreationDate;
	private Date sjLastUpdatedDate;
	private boolean sjUnavailableBl;

	public TSjShippingPrice() {
	}

	public TSjShippingPrice(int sjShippingPriceId, TSistockItem TSistockItem, TSoStore TSoStore,
			TXzshippingZone TXzshippingZone, double sjLowerBoundsFl, double sjUpperBoundsFl, double sjPriceMn,
			Date sjCreationDate, Date sjLastUpdatedDate, boolean sjUnavailableBl) {
		this.sjShippingPriceId = sjShippingPriceId;
		this.TSistockItem = TSistockItem;
		this.TSoStore = TSoStore;
		this.TXzshippingZone = TXzshippingZone;
		this.sjLowerBoundsFl = sjLowerBoundsFl;
		this.sjUpperBoundsFl = sjUpperBoundsFl;
		this.sjPriceMn = sjPriceMn;
		this.sjCreationDate = sjCreationDate;
		this.sjLastUpdatedDate = sjLastUpdatedDate;
		this.sjUnavailableBl = sjUnavailableBl;
	}

	@Id

	@Column(name = "SjShippingPriceID", unique = true, nullable = false)
	public int getSjShippingPriceId() {
		return this.sjShippingPriceId;
	}

	public void setSjShippingPriceId(int sjShippingPriceId) {
		this.sjShippingPriceId = sjShippingPriceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SjStockItemID", nullable = false)
	public TSistockItem getTSistockItem() {
		return this.TSistockItem;
	}

	public void setTSistockItem(TSistockItem TSistockItem) {
		this.TSistockItem = TSistockItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SjStoreID", nullable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SjShippingZoneID", nullable = false)
	public TXzshippingZone getTXzshippingZone() {
		return this.TXzshippingZone;
	}

	public void setTXzshippingZone(TXzshippingZone TXzshippingZone) {
		this.TXzshippingZone = TXzshippingZone;
	}

	@Column(name = "SjLowerBoundsFl", nullable = false, precision = 53, scale = 0)
	public double getSjLowerBoundsFl() {
		return this.sjLowerBoundsFl;
	}

	public void setSjLowerBoundsFl(double sjLowerBoundsFl) {
		this.sjLowerBoundsFl = sjLowerBoundsFl;
	}

	@Column(name = "SjUpperBoundsFl", nullable = false, precision = 53, scale = 0)
	public double getSjUpperBoundsFl() {
		return this.sjUpperBoundsFl;
	}

	public void setSjUpperBoundsFl(double sjUpperBoundsFl) {
		this.sjUpperBoundsFl = sjUpperBoundsFl;
	}

	@Column(name = "SjPriceMn", nullable = false, precision = 53, scale = 0)
	public double getSjPriceMn() {
		return this.sjPriceMn;
	}

	public void setSjPriceMn(double sjPriceMn) {
		this.sjPriceMn = sjPriceMn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SjCreationDate", nullable = false, length = 23)
	public Date getSjCreationDate() {
		return this.sjCreationDate;
	}

	public void setSjCreationDate(Date sjCreationDate) {
		this.sjCreationDate = sjCreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SjLastUpdatedDate", nullable = false, length = 23)
	public Date getSjLastUpdatedDate() {
		return this.sjLastUpdatedDate;
	}

	public void setSjLastUpdatedDate(Date sjLastUpdatedDate) {
		this.sjLastUpdatedDate = sjLastUpdatedDate;
	}

	@Column(name = "SjUnavailableBl", nullable = false)
	public boolean isSjUnavailableBl() {
		return this.sjUnavailableBl;
	}

	public void setSjUnavailableBl(boolean sjUnavailableBl) {
		this.sjUnavailableBl = sjUnavailableBl;
	}

}
