package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TSmStockOfferItem generated by hbm2java
 */
@Entity
@Table(name = "T_SmStockOfferItem")
public class TSmStockOfferItem implements java.io.Serializable {

	private TSmStockOfferItemId id;
	private TSfStockOffer TSfStockOffer;
	private int smQuantityIn;

	public TSmStockOfferItem() {
	}

	public TSmStockOfferItem(TSmStockOfferItemId id, TSfStockOffer TSfStockOffer, int smQuantityIn) {
		this.id = id;
		this.TSfStockOffer = TSfStockOffer;
		this.smQuantityIn = smQuantityIn;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "smOfferId", column = @Column(name = "SmOfferID", nullable = false)),
			@AttributeOverride(name = "smDiscountPercentFl", column = @Column(name = "SmDiscountPercentFl", nullable = false, precision = 24, scale = 0)) })
	public TSmStockOfferItemId getId() {
		return this.id;
	}

	public void setId(TSmStockOfferItemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SmOfferID", nullable = false, insertable = false, updatable = false)
	public TSfStockOffer getTSfStockOffer() {
		return this.TSfStockOffer;
	}

	public void setTSfStockOffer(TSfStockOffer TSfStockOffer) {
		this.TSfStockOffer = TSfStockOffer;
	}

	@Column(name = "SmQuantityIn", nullable = false)
	public int getSmQuantityIn() {
		return this.smQuantityIn;
	}

	public void setSmQuantityIn(int smQuantityIn) {
		this.smQuantityIn = smQuantityIn;
	}

}
