package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TSoStore generated by hbm2java
 */
@Entity
@Table(name = "T_SoStore", uniqueConstraints = { @UniqueConstraint(columnNames = "SoStoreNoTx"),
		@UniqueConstraint(columnNames = "SoStoreNameTx") })
public class TSoStore implements java.io.Serializable {

	private short soStoreId;
	private TPdPaditerritory TPdPaditerritory;
	private TCyCountry TCyCountry;
	private TSeState TSeState;
	private String soStoreNameTx;
	private String soResortTxN;
	private String soStoreNoTx;
	private String soAddress1txN;
	private String soAddress2txN;
	private String soAddress3txN;
	private String soAddress4txN;
	private String soPostcodeTxN;
	private String soTelephone1txN;
	private String soTelephone2txN;
	private String soFaxTxN;
	private String soEmailTxN;
	private String soWebTxN;
	private String soDiveCheckNoTxN;
	private boolean soUnavailableBl;
	private Date soLastUpdatedDate;
	private boolean soRequiredBl;
	private String soOpeningTimeTxN;
	private String soClosingTimeTxN;
	private boolean soMasterBl;
	private Date soCreationDate;
	private String soPoleDisplayTxN;
	private Date soLastUploadDateN;
	private String soAccountNameTxN;
	private String soPasswordTxN;
	private String soRentalStartTimeTxN;
	private String soRentalEndTimeTxN;
	private Date soTaxDateN;
	private Integer soWebCurrencyIdN;
	private String soCountryTaxExemptIdsTxN;
	private String soStateTaxExemptIdsTxN;
	private String soGenericTaxExemptIdsTxN;
	private boolean soOnLineStoreBl;
	private String soEolproductImagesDirTxN;
	private String soEolproductThumbsDirTxN;
	private String soEolmediaDirTxN;
	private String soEolproductXmlPathTxN;
	private String soEolshopEmailRecipientListTxN;
	private short soEolterrestrialStoreId;
	private int soEolcostCenterId;
	private int soEolempId;
	private short soEolpcid;
	private boolean soEoluseQsstoreParamsBl;
	private int soEolshippingStockTypeId;
	private boolean soEolreadOnlyBl;
	private Integer soEolcourseEnrollStatusIdN;
	private Integer soEoltripEnrollStatusIdN;
	private String soCultureTxN;
	private String soPadiuserIdtxN;
	private String soPadipwtxN;
	private String soUserDefined1txN;
	private String soUserDefined2txN;
	private String soUserDefined3txN;
	private int soEolcustTypeIdeolpriceIn;
	private int soEolcustTypeIdregularPriceIn;
	private int soEolcustTypeIdminPriceIn;
	private Short soPicstoreIdN;
	private String soImageTxN;
	private String soFacebookTxN;
	private String soCheckInTimeTxN;
	private String soCheckOutTimeTxN;
	private Set<TTkTask> TTkTasks = new HashSet<TTkTask>(0);
	private Set<TPaPodeliveryItem> TPaPodeliveryItems = new HashSet<TPaPodeliveryItem>(0);
	private Set<TZlStoreStockItem> TZlStoreStockItems = new HashSet<TZlStoreStockItem>(0);
	private Set<TCccostCenter> TCccostCenters = new HashSet<TCccostCenter>(0);
	private Set<TPopo> TPoposForPostoreId = new HashSet<TPopo>(0);
	private Set<TC8custInterest> TC8custInterests = new HashSet<TC8custInterest>(0);
	private Set<TRbrentalBooking> TRbrentalBookings = new HashSet<TRbrentalBooking>(0);
	private Set<TGlaccount> TGlaccounts = new HashSet<TGlaccount>(0);
	private Set<TPopo> TPoposForPoshipToStoreId = new HashSet<TPopo>(0);
	private Set<TMlmailingList> TMlmailingLists = new HashSet<TMlmailingList>(0);
	private Set<TDnDenomination> TDnDenominations = new HashSet<TDnDenomination>(0);
	private Set<TQuQuote> TQuQuotes = new HashSet<TQuQuote>(0);
	private Set<TCbClub> TCbClubs = new HashSet<TCbClub>(0);
	private Set<TChCustType> TChCustTypes = new HashSet<TChCustType>(0);
	private Set<TCsCourse> TCsCourses = new HashSet<TCsCourse>(0);
	private Set<TZoStoreDataType> TZoStoreDataTypes = new HashSet<TZoStoreDataType>(0);
	private Set<TCeCostPrice> TCeCostPrices = new HashSet<TCeCostPrice>(0);
	private Set<TIsinvoiceTypeStore> TIsinvoiceTypeStores = new HashSet<TIsinvoiceTypeStore>(0);
	private Set<TVsvalidState> TVsvalidStates = new HashSet<TVsvalidState>(0);
	private Set<TDfDefault> TDfDefaults = new HashSet<TDfDefault>(0);
	private Set<TEmEmp> TEmEmps = new HashSet<TEmEmp>(0);
	private Set<THtHotel> THtHotels = new HashSet<THtHotel>(0);
	private Set<TSbserviceBooking> TSbserviceBookings = new HashSet<TSbserviceBooking>(0);
	private Set<TTpTrip> TTpTrips = new HashSet<TTpTrip>(0);
	private Set<TAnClosing> TAnClosings = new HashSet<TAnClosing>(0);
	private Set<TScSource> TScSources = new HashSet<TScSource>(0);
	private Set<TS6storeConfig> TS6storeConfigsForS6childStoreId = new HashSet<TS6storeConfig>(0);
	private Set<TTrTransfer> TTrTransfersForTrSourceStoreId = new HashSet<TTrTransfer>(0);
	private Set<TEkEmpClockIn> TEkEmpClockIns = new HashSet<TEkEmpClockIn>(0);
	private Set<TTrTransfer> TTrTransfersForTrDestStoreId = new HashSet<TTrTransfer>(0);
	private Set<TPpPaymentProvider> TPpPaymentProviders = new HashSet<TPpPaymentProvider>(0);
	private Set<TCuCust> TCuCusts = new HashSet<TCuCust>(0);
	private Set<TAoCommissionClosing> TAoCommissionClosings = new HashSet<TAoCommissionClosing>(0);
	private Set<TCtcourseType> TCtcourseTypes = new HashSet<TCtcourseType>(0);
	private Set<TDtDestination> TDtDestinations = new HashSet<TDtDestination>(0);
	private Set<TPmpaymentMethod> TPmpaymentMethods = new HashSet<TPmpaymentMethod>(0);
	private Set<TVoVoucher> TVoVouchers = new HashSet<TVoVoucher>(0);
	private Set<TVnVan> TVnVans = new HashSet<TVnVan>(0);
	private Set<TPcpc> TPcpcs = new HashSet<TPcpc>(0);
	private Set<TS7specialInterest> TS7specialInterests = new HashSet<TS7specialInterest>(0);
	private Set<TVcvalidCountry> TVcvalidCountries = new HashSet<TVcvalidCountry>(0);
	private Set<TAcAccount> TAcAccounts = new HashSet<TAcAccount>(0);
	private Set<TC1custCourse> TC1custCourses = new HashSet<TC1custCourse>(0);
	private Set<TCacertAgency> TCacertAgencies = new HashSet<TCacertAgency>(0);
	private Set<TTbtaxBand> TTbtaxBands = new HashSet<TTbtaxBand>(0);
	private Set<TGdGiftCard> TGdGiftCards = new HashSet<TGdGiftCard>(0);
	private Set<TSkSupplierStockItem> TSkSupplierStockItems = new HashSet<TSkSupplierStockItem>(0);
	private Set<TInInvoice> TInInvoices = new HashSet<TInInvoice>(0);
	private Set<TMmMembershipType> TMmMembershipTypes = new HashSet<TMmMembershipType>(0);
	private Set<TLqlabelQueue> TLqlabelQueues = new HashSet<TLqlabelQueue>(0);
	private Set<TLcLocation> TLcLocations = new HashSet<TLcLocation>(0);
	private Set<TBtBoat> TBtBoats = new HashSet<TBtBoat>(0);
	private Set<TCdCustOrder> TCdCustOrders = new HashSet<TCdCustOrder>(0);
	private Set<TSnserialNo> TSnserialNos = new HashSet<TSnserialNo>(0);
	private Set<TRrreportRun> TRrreportRuns = new HashSet<TRrreportRun>(0);
	private Set<TSjShippingPrice> TSjShippingPrices = new HashSet<TSjShippingPrice>(0);
	private Set<TGcgiftCert> TGcgiftCerts = new HashSet<TGcgiftCert>(0);
	private Set<TPfProfitCenter> TPfProfitCenters = new HashSet<TPfProfitCenter>(0);
	private Set<TRkRoomBooking> TRkRoomBookings = new HashSet<TRkRoomBooking>(0);
	private Set<TCnContact> TCnContacts = new HashSet<TCnContact>(0);
	private Set<TZ5storeSupplier> TZ5storeSuppliers = new HashSet<TZ5storeSupplier>(0);
	private Set<TEqEquipment> TEqEquipments = new HashSet<TEqEquipment>(0);
	private Set<TS6storeConfig> TS6storeConfigsForS6parentStoreId = new HashSet<TS6storeConfig>(0);
	private Set<TStstockType> TStstockTypes = new HashSet<TStstockType>(0);
	private Set<TShShortcut> TShShortcuts = new HashSet<TShShortcut>(0);
	private Set<TIcInventoryLocation> TIcInventoryLocations = new HashSet<TIcInventoryLocation>(0);
	private Set<TRlreportLayout> TRlreportLayouts = new HashSet<TRlreportLayout>(0);

	public TSoStore() {
	}

	public TSoStore(short soStoreId, String soStoreNameTx, boolean soUnavailableBl, Date soLastUpdatedDate,
			boolean soRequiredBl, boolean soMasterBl, Date soCreationDate, boolean soOnLineStoreBl,
			short soEolterrestrialStoreId, int soEolcostCenterId, int soEolempId, short soEolpcid,
			boolean soEoluseQsstoreParamsBl, int soEolshippingStockTypeId, boolean soEolreadOnlyBl,
			int soEolcustTypeIdeolpriceIn, int soEolcustTypeIdregularPriceIn, int soEolcustTypeIdminPriceIn) {
		this.soStoreId = soStoreId;
		this.soStoreNameTx = soStoreNameTx;
		this.soUnavailableBl = soUnavailableBl;
		this.soLastUpdatedDate = soLastUpdatedDate;
		this.soRequiredBl = soRequiredBl;
		this.soMasterBl = soMasterBl;
		this.soCreationDate = soCreationDate;
		this.soOnLineStoreBl = soOnLineStoreBl;
		this.soEolterrestrialStoreId = soEolterrestrialStoreId;
		this.soEolcostCenterId = soEolcostCenterId;
		this.soEolempId = soEolempId;
		this.soEolpcid = soEolpcid;
		this.soEoluseQsstoreParamsBl = soEoluseQsstoreParamsBl;
		this.soEolshippingStockTypeId = soEolshippingStockTypeId;
		this.soEolreadOnlyBl = soEolreadOnlyBl;
		this.soEolcustTypeIdeolpriceIn = soEolcustTypeIdeolpriceIn;
		this.soEolcustTypeIdregularPriceIn = soEolcustTypeIdregularPriceIn;
		this.soEolcustTypeIdminPriceIn = soEolcustTypeIdminPriceIn;
	}

	public TSoStore(short soStoreId, TPdPaditerritory TPdPaditerritory, TCyCountry TCyCountry, TSeState TSeState,
			String soStoreNameTx, String soResortTxN, String soStoreNoTx, String soAddress1txN,
			String soAddress2txN, String soAddress3txN, String soAddress4txN,
			String soPostcodeTxN, String soTelephone1txN, String soTelephone2txN,
			String soFaxTxN, String soEmailTxN, String soWebTxN, String soDiveCheckNoTxN,
			boolean soUnavailableBl, Date soLastUpdatedDate, boolean soRequiredBl, String soOpeningTimeTxN,
			String soClosingTimeTxN, boolean soMasterBl, Date soCreationDate, String soPoleDisplayTxN,
			Date soLastUploadDateN, String soAccountNameTxN, String soPasswordTxN,
			String soRentalStartTimeTxN, String soRentalEndTimeTxN, Date soTaxDateN,
			Integer soWebCurrencyIdN, String soCountryTaxExemptIdsTxN, String soStateTaxExemptIdsTxN,
			String soGenericTaxExemptIdsTxN, boolean soOnLineStoreBl, String soEolproductImagesDirTxN,
			String soEolproductThumbsDirTxN, String soEolmediaDirTxN, String soEolproductXmlPathTxN,
			String soEolshopEmailRecipientListTxN, short soEolterrestrialStoreId, int soEolcostCenterId,
			int soEolempId, short soEolpcid, boolean soEoluseQsstoreParamsBl, int soEolshippingStockTypeId,
			boolean soEolreadOnlyBl, Integer soEolcourseEnrollStatusIdN, Integer soEoltripEnrollStatusIdN,
			String soCultureTxN, String soPadiuserIdtxN, String soPadipwtxN,
			String soUserDefined1txN, String soUserDefined2txN, String soUserDefined3txN,
			int soEolcustTypeIdeolpriceIn, int soEolcustTypeIdregularPriceIn, int soEolcustTypeIdminPriceIn,
			Short soPicstoreIdN, String soImageTxN, String soFacebookTxN, String soCheckInTimeTxN,
			String soCheckOutTimeTxN, Set<TTkTask> TTkTasks, Set<TPaPodeliveryItem> TPaPodeliveryItems,
			Set<TZlStoreStockItem> TZlStoreStockItems, Set<TCccostCenter> TCccostCenters, Set<TPopo> TPoposForPostoreId,
			Set<TC8custInterest> TC8custInterests, Set<TRbrentalBooking> TRbrentalBookings, Set<TGlaccount> TGlaccounts,
			Set<TPopo> TPoposForPoshipToStoreId, Set<TMlmailingList> TMlmailingLists,
			Set<TDnDenomination> TDnDenominations, Set<TQuQuote> TQuQuotes, Set<TCbClub> TCbClubs,
			Set<TChCustType> TChCustTypes, Set<TCsCourse> TCsCourses, Set<TZoStoreDataType> TZoStoreDataTypes,
			Set<TCeCostPrice> TCeCostPrices, Set<TIsinvoiceTypeStore> TIsinvoiceTypeStores,
			Set<TVsvalidState> TVsvalidStates, Set<TDfDefault> TDfDefaults, Set<TEmEmp> TEmEmps,
			Set<THtHotel> THtHotels, Set<TSbserviceBooking> TSbserviceBookings, Set<TTpTrip> TTpTrips,
			Set<TAnClosing> TAnClosings, Set<TScSource> TScSources,
			Set<TS6storeConfig> TS6storeConfigsForS6childStoreId, Set<TTrTransfer> TTrTransfersForTrSourceStoreId,
			Set<TEkEmpClockIn> TEkEmpClockIns, Set<TTrTransfer> TTrTransfersForTrDestStoreId,
			Set<TPpPaymentProvider> TPpPaymentProviders, Set<TCuCust> TCuCusts,
			Set<TAoCommissionClosing> TAoCommissionClosings, Set<TCtcourseType> TCtcourseTypes,
			Set<TDtDestination> TDtDestinations, Set<TPmpaymentMethod> TPmpaymentMethods, Set<TVoVoucher> TVoVouchers,
			Set<TVnVan> TVnVans, Set<TPcpc> TPcpcs, Set<TS7specialInterest> TS7specialInterests,
			Set<TVcvalidCountry> TVcvalidCountries, Set<TAcAccount> TAcAccounts, Set<TC1custCourse> TC1custCourses,
			Set<TCacertAgency> TCacertAgencies, Set<TTbtaxBand> TTbtaxBands, Set<TGdGiftCard> TGdGiftCards,
			Set<TSkSupplierStockItem> TSkSupplierStockItems, Set<TInInvoice> TInInvoices,
			Set<TMmMembershipType> TMmMembershipTypes, Set<TLqlabelQueue> TLqlabelQueues, Set<TLcLocation> TLcLocations,
			Set<TBtBoat> TBtBoats, Set<TCdCustOrder> TCdCustOrders, Set<TSnserialNo> TSnserialNos,
			Set<TRrreportRun> TRrreportRuns, Set<TSjShippingPrice> TSjShippingPrices, Set<TGcgiftCert> TGcgiftCerts,
			Set<TPfProfitCenter> TPfProfitCenters, Set<TRkRoomBooking> TRkRoomBookings, Set<TCnContact> TCnContacts,
			Set<TZ5storeSupplier> TZ5storeSuppliers, Set<TEqEquipment> TEqEquipments,
			Set<TS6storeConfig> TS6storeConfigsForS6parentStoreId, Set<TStstockType> TStstockTypes,
			Set<TShShortcut> TShShortcuts, Set<TIcInventoryLocation> TIcInventoryLocations,
			Set<TRlreportLayout> TRlreportLayouts) {
		this.soStoreId = soStoreId;
		this.TPdPaditerritory = TPdPaditerritory;
		this.TCyCountry = TCyCountry;
		this.TSeState = TSeState;
		this.soStoreNameTx = soStoreNameTx;
		this.soResortTxN = soResortTxN;
		this.soStoreNoTx = soStoreNoTx;
		this.soAddress1txN = soAddress1txN;
		this.soAddress2txN = soAddress2txN;
		this.soAddress3txN = soAddress3txN;
		this.soAddress4txN = soAddress4txN;
		this.soPostcodeTxN = soPostcodeTxN;
		this.soTelephone1txN = soTelephone1txN;
		this.soTelephone2txN = soTelephone2txN;
		this.soFaxTxN = soFaxTxN;
		this.soEmailTxN = soEmailTxN;
		this.soWebTxN = soWebTxN;
		this.soDiveCheckNoTxN = soDiveCheckNoTxN;
		this.soUnavailableBl = soUnavailableBl;
		this.soLastUpdatedDate = soLastUpdatedDate;
		this.soRequiredBl = soRequiredBl;
		this.soOpeningTimeTxN = soOpeningTimeTxN;
		this.soClosingTimeTxN = soClosingTimeTxN;
		this.soMasterBl = soMasterBl;
		this.soCreationDate = soCreationDate;
		this.soPoleDisplayTxN = soPoleDisplayTxN;
		this.soLastUploadDateN = soLastUploadDateN;
		this.soAccountNameTxN = soAccountNameTxN;
		this.soPasswordTxN = soPasswordTxN;
		this.soRentalStartTimeTxN = soRentalStartTimeTxN;
		this.soRentalEndTimeTxN = soRentalEndTimeTxN;
		this.soTaxDateN = soTaxDateN;
		this.soWebCurrencyIdN = soWebCurrencyIdN;
		this.soCountryTaxExemptIdsTxN = soCountryTaxExemptIdsTxN;
		this.soStateTaxExemptIdsTxN = soStateTaxExemptIdsTxN;
		this.soGenericTaxExemptIdsTxN = soGenericTaxExemptIdsTxN;
		this.soOnLineStoreBl = soOnLineStoreBl;
		this.soEolproductImagesDirTxN = soEolproductImagesDirTxN;
		this.soEolproductThumbsDirTxN = soEolproductThumbsDirTxN;
		this.soEolmediaDirTxN = soEolmediaDirTxN;
		this.soEolproductXmlPathTxN = soEolproductXmlPathTxN;
		this.soEolshopEmailRecipientListTxN = soEolshopEmailRecipientListTxN;
		this.soEolterrestrialStoreId = soEolterrestrialStoreId;
		this.soEolcostCenterId = soEolcostCenterId;
		this.soEolempId = soEolempId;
		this.soEolpcid = soEolpcid;
		this.soEoluseQsstoreParamsBl = soEoluseQsstoreParamsBl;
		this.soEolshippingStockTypeId = soEolshippingStockTypeId;
		this.soEolreadOnlyBl = soEolreadOnlyBl;
		this.soEolcourseEnrollStatusIdN = soEolcourseEnrollStatusIdN;
		this.soEoltripEnrollStatusIdN = soEoltripEnrollStatusIdN;
		this.soCultureTxN = soCultureTxN;
		this.soPadiuserIdtxN = soPadiuserIdtxN;
		this.soPadipwtxN = soPadipwtxN;
		this.soUserDefined1txN = soUserDefined1txN;
		this.soUserDefined2txN = soUserDefined2txN;
		this.soUserDefined3txN = soUserDefined3txN;
		this.soEolcustTypeIdeolpriceIn = soEolcustTypeIdeolpriceIn;
		this.soEolcustTypeIdregularPriceIn = soEolcustTypeIdregularPriceIn;
		this.soEolcustTypeIdminPriceIn = soEolcustTypeIdminPriceIn;
		this.soPicstoreIdN = soPicstoreIdN;
		this.soImageTxN = soImageTxN;
		this.soFacebookTxN = soFacebookTxN;
		this.soCheckInTimeTxN = soCheckInTimeTxN;
		this.soCheckOutTimeTxN = soCheckOutTimeTxN;
		this.TTkTasks = TTkTasks;
		this.TPaPodeliveryItems = TPaPodeliveryItems;
		this.TZlStoreStockItems = TZlStoreStockItems;
		this.TCccostCenters = TCccostCenters;
		this.TPoposForPostoreId = TPoposForPostoreId;
		this.TC8custInterests = TC8custInterests;
		this.TRbrentalBookings = TRbrentalBookings;
		this.TGlaccounts = TGlaccounts;
		this.TPoposForPoshipToStoreId = TPoposForPoshipToStoreId;
		this.TMlmailingLists = TMlmailingLists;
		this.TDnDenominations = TDnDenominations;
		this.TQuQuotes = TQuQuotes;
		this.TCbClubs = TCbClubs;
		this.TChCustTypes = TChCustTypes;
		this.TCsCourses = TCsCourses;
		this.TZoStoreDataTypes = TZoStoreDataTypes;
		this.TCeCostPrices = TCeCostPrices;
		this.TIsinvoiceTypeStores = TIsinvoiceTypeStores;
		this.TVsvalidStates = TVsvalidStates;
		this.TDfDefaults = TDfDefaults;
		this.TEmEmps = TEmEmps;
		this.THtHotels = THtHotels;
		this.TSbserviceBookings = TSbserviceBookings;
		this.TTpTrips = TTpTrips;
		this.TAnClosings = TAnClosings;
		this.TScSources = TScSources;
		this.TS6storeConfigsForS6childStoreId = TS6storeConfigsForS6childStoreId;
		this.TTrTransfersForTrSourceStoreId = TTrTransfersForTrSourceStoreId;
		this.TEkEmpClockIns = TEkEmpClockIns;
		this.TTrTransfersForTrDestStoreId = TTrTransfersForTrDestStoreId;
		this.TPpPaymentProviders = TPpPaymentProviders;
		this.TCuCusts = TCuCusts;
		this.TAoCommissionClosings = TAoCommissionClosings;
		this.TCtcourseTypes = TCtcourseTypes;
		this.TDtDestinations = TDtDestinations;
		this.TPmpaymentMethods = TPmpaymentMethods;
		this.TVoVouchers = TVoVouchers;
		this.TVnVans = TVnVans;
		this.TPcpcs = TPcpcs;
		this.TS7specialInterests = TS7specialInterests;
		this.TVcvalidCountries = TVcvalidCountries;
		this.TAcAccounts = TAcAccounts;
		this.TC1custCourses = TC1custCourses;
		this.TCacertAgencies = TCacertAgencies;
		this.TTbtaxBands = TTbtaxBands;
		this.TGdGiftCards = TGdGiftCards;
		this.TSkSupplierStockItems = TSkSupplierStockItems;
		this.TInInvoices = TInInvoices;
		this.TMmMembershipTypes = TMmMembershipTypes;
		this.TLqlabelQueues = TLqlabelQueues;
		this.TLcLocations = TLcLocations;
		this.TBtBoats = TBtBoats;
		this.TCdCustOrders = TCdCustOrders;
		this.TSnserialNos = TSnserialNos;
		this.TRrreportRuns = TRrreportRuns;
		this.TSjShippingPrices = TSjShippingPrices;
		this.TGcgiftCerts = TGcgiftCerts;
		this.TPfProfitCenters = TPfProfitCenters;
		this.TRkRoomBookings = TRkRoomBookings;
		this.TCnContacts = TCnContacts;
		this.TZ5storeSuppliers = TZ5storeSuppliers;
		this.TEqEquipments = TEqEquipments;
		this.TS6storeConfigsForS6parentStoreId = TS6storeConfigsForS6parentStoreId;
		this.TStstockTypes = TStstockTypes;
		this.TShShortcuts = TShShortcuts;
		this.TIcInventoryLocations = TIcInventoryLocations;
		this.TRlreportLayouts = TRlreportLayouts;
	}

	@Id

	@Column(name = "SoStoreID", unique = true, nullable = false)
	public short getSoStoreId() {
		return this.soStoreId;
	}

	public void setSoStoreId(short soStoreId) {
		this.soStoreId = soStoreId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SoPADITerritoryID_N")
	public TPdPaditerritory getTPdPaditerritory() {
		return this.TPdPaditerritory;
	}

	public void setTPdPaditerritory(TPdPaditerritory TPdPaditerritory) {
		this.TPdPaditerritory = TPdPaditerritory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SoCountryID_N")
	public TCyCountry getTCyCountry() {
		return this.TCyCountry;
	}

	public void setTCyCountry(TCyCountry TCyCountry) {
		this.TCyCountry = TCyCountry;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SoStateID_N")
	public TSeState getTSeState() {
		return this.TSeState;
	}

	public void setTSeState(TSeState TSeState) {
		this.TSeState = TSeState;
	}

	@Column(name = "SoStoreNameTx", unique = true, nullable = false)
	public String getSoStoreNameTx() {
		return this.soStoreNameTx;
	}

	public void setSoStoreNameTx(String soStoreNameTx) {
		this.soStoreNameTx = soStoreNameTx;
	}

	@Column(name = "SoResortTx_N")
	public String getSoResortTxN() {
		return this.soResortTxN;
	}

	public void setSoResortTxN(String soResortTxN) {
		this.soResortTxN = soResortTxN;
	}

	@Column(name = "SoStoreNoTx", unique = true)
	public String getSoStoreNoTx() {
		return this.soStoreNoTx;
	}

	public void setSoStoreNoTx(String soStoreNoTx) {
		this.soStoreNoTx = soStoreNoTx;
	}

	@Column(name = "SoAddress1Tx_N")
	public String getSoAddress1txN() {
		return this.soAddress1txN;
	}

	public void setSoAddress1txN(String soAddress1txN) {
		this.soAddress1txN = soAddress1txN;
	}

	@Column(name = "SoAddress2Tx_N")
	public String getSoAddress2txN() {
		return this.soAddress2txN;
	}

	public void setSoAddress2txN(String soAddress2txN) {
		this.soAddress2txN = soAddress2txN;
	}

	@Column(name = "SoAddress3Tx_N")
	public String getSoAddress3txN() {
		return this.soAddress3txN;
	}

	public void setSoAddress3txN(String soAddress3txN) {
		this.soAddress3txN = soAddress3txN;
	}

	@Column(name = "SoAddress4Tx_N")
	public String getSoAddress4txN() {
		return this.soAddress4txN;
	}

	public void setSoAddress4txN(String soAddress4txN) {
		this.soAddress4txN = soAddress4txN;
	}

	@Column(name = "SoPostcodeTx_N")
	public String getSoPostcodeTxN() {
		return this.soPostcodeTxN;
	}

	public void setSoPostcodeTxN(String soPostcodeTxN) {
		this.soPostcodeTxN = soPostcodeTxN;
	}

	@Column(name = "SoTelephone1Tx_N")
	public String getSoTelephone1txN() {
		return this.soTelephone1txN;
	}

	public void setSoTelephone1txN(String soTelephone1txN) {
		this.soTelephone1txN = soTelephone1txN;
	}

	@Column(name = "SoTelephone2Tx_N")
	public String getSoTelephone2txN() {
		return this.soTelephone2txN;
	}

	public void setSoTelephone2txN(String soTelephone2txN) {
		this.soTelephone2txN = soTelephone2txN;
	}

	@Column(name = "SoFaxTx_N")
	public String getSoFaxTxN() {
		return this.soFaxTxN;
	}

	public void setSoFaxTxN(String soFaxTxN) {
		this.soFaxTxN = soFaxTxN;
	}

	@Column(name = "SoEMailTx_N")
	public String getSoEmailTxN() {
		return this.soEmailTxN;
	}

	public void setSoEmailTxN(String soEmailTxN) {
		this.soEmailTxN = soEmailTxN;
	}

	@Column(name = "SoWebTx_N")
	public String getSoWebTxN() {
		return this.soWebTxN;
	}

	public void setSoWebTxN(String soWebTxN) {
		this.soWebTxN = soWebTxN;
	}

	@Column(name = "SoDiveCheckNoTx_N")
	public String getSoDiveCheckNoTxN() {
		return this.soDiveCheckNoTxN;
	}

	public void setSoDiveCheckNoTxN(String soDiveCheckNoTxN) {
		this.soDiveCheckNoTxN = soDiveCheckNoTxN;
	}

	@Column(name = "SoUnavailableBl", nullable = false)
	public boolean isSoUnavailableBl() {
		return this.soUnavailableBl;
	}

	public void setSoUnavailableBl(boolean soUnavailableBl) {
		this.soUnavailableBl = soUnavailableBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SoLastUpdatedDate", nullable = false, length = 23)
	public Date getSoLastUpdatedDate() {
		return this.soLastUpdatedDate;
	}

	public void setSoLastUpdatedDate(Date soLastUpdatedDate) {
		this.soLastUpdatedDate = soLastUpdatedDate;
	}

	@Column(name = "SoRequiredBl", nullable = false)
	public boolean isSoRequiredBl() {
		return this.soRequiredBl;
	}

	public void setSoRequiredBl(boolean soRequiredBl) {
		this.soRequiredBl = soRequiredBl;
	}

	@Column(name = "SoOpeningTimeTx_N")
	public String getSoOpeningTimeTxN() {
		return this.soOpeningTimeTxN;
	}

	public void setSoOpeningTimeTxN(String soOpeningTimeTxN) {
		this.soOpeningTimeTxN = soOpeningTimeTxN;
	}

	@Column(name = "SoClosingTimeTx_N")
	public String getSoClosingTimeTxN() {
		return this.soClosingTimeTxN;
	}

	public void setSoClosingTimeTxN(String soClosingTimeTxN) {
		this.soClosingTimeTxN = soClosingTimeTxN;
	}

	@Column(name = "SoMasterBl", nullable = false)
	public boolean isSoMasterBl() {
		return this.soMasterBl;
	}

	public void setSoMasterBl(boolean soMasterBl) {
		this.soMasterBl = soMasterBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SoCreationDate", nullable = false, length = 23)
	public Date getSoCreationDate() {
		return this.soCreationDate;
	}

	public void setSoCreationDate(Date soCreationDate) {
		this.soCreationDate = soCreationDate;
	}

	@Column(name = "SoPoleDisplayTx_N")
	public String getSoPoleDisplayTxN() {
		return this.soPoleDisplayTxN;
	}

	public void setSoPoleDisplayTxN(String soPoleDisplayTxN) {
		this.soPoleDisplayTxN = soPoleDisplayTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SoLastUploadDate_N", length = 23)
	public Date getSoLastUploadDateN() {
		return this.soLastUploadDateN;
	}

	public void setSoLastUploadDateN(Date soLastUploadDateN) {
		this.soLastUploadDateN = soLastUploadDateN;
	}

	@Column(name = "SoAccountNameTx_N")
	public String getSoAccountNameTxN() {
		return this.soAccountNameTxN;
	}

	public void setSoAccountNameTxN(String soAccountNameTxN) {
		this.soAccountNameTxN = soAccountNameTxN;
	}

	@Column(name = "SoPasswordTx_N")
	public String getSoPasswordTxN() {
		return this.soPasswordTxN;
	}

	public void setSoPasswordTxN(String soPasswordTxN) {
		this.soPasswordTxN = soPasswordTxN;
	}

	@Column(name = "SoRentalStartTimeTx_N")
	public String getSoRentalStartTimeTxN() {
		return this.soRentalStartTimeTxN;
	}

	public void setSoRentalStartTimeTxN(String soRentalStartTimeTxN) {
		this.soRentalStartTimeTxN = soRentalStartTimeTxN;
	}

	@Column(name = "SoRentalEndTimeTx_N")
	public String getSoRentalEndTimeTxN() {
		return this.soRentalEndTimeTxN;
	}

	public void setSoRentalEndTimeTxN(String soRentalEndTimeTxN) {
		this.soRentalEndTimeTxN = soRentalEndTimeTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SoTaxDate_N", length = 23)
	public Date getSoTaxDateN() {
		return this.soTaxDateN;
	}

	public void setSoTaxDateN(Date soTaxDateN) {
		this.soTaxDateN = soTaxDateN;
	}

	@Column(name = "SoWebCurrencyID_N")
	public Integer getSoWebCurrencyIdN() {
		return this.soWebCurrencyIdN;
	}

	public void setSoWebCurrencyIdN(Integer soWebCurrencyIdN) {
		this.soWebCurrencyIdN = soWebCurrencyIdN;
	}

	@Column(name = "SoCountryTaxExemptIDsTx_N")
	public String getSoCountryTaxExemptIdsTxN() {
		return this.soCountryTaxExemptIdsTxN;
	}

	public void setSoCountryTaxExemptIdsTxN(String soCountryTaxExemptIdsTxN) {
		this.soCountryTaxExemptIdsTxN = soCountryTaxExemptIdsTxN;
	}

	@Column(name = "SoStateTaxExemptIDsTx_N")
	public String getSoStateTaxExemptIdsTxN() {
		return this.soStateTaxExemptIdsTxN;
	}

	public void setSoStateTaxExemptIdsTxN(String soStateTaxExemptIdsTxN) {
		this.soStateTaxExemptIdsTxN = soStateTaxExemptIdsTxN;
	}

	@Column(name = "SoGenericTaxExemptIDsTx_N")
	public String getSoGenericTaxExemptIdsTxN() {
		return this.soGenericTaxExemptIdsTxN;
	}

	public void setSoGenericTaxExemptIdsTxN(String soGenericTaxExemptIdsTxN) {
		this.soGenericTaxExemptIdsTxN = soGenericTaxExemptIdsTxN;
	}

	@Column(name = "SoOnLineStoreBl", nullable = false)
	public boolean isSoOnLineStoreBl() {
		return this.soOnLineStoreBl;
	}

	public void setSoOnLineStoreBl(boolean soOnLineStoreBl) {
		this.soOnLineStoreBl = soOnLineStoreBl;
	}

	@Column(name = "SoEOLProductImagesDirTx_N")
	public String getSoEolproductImagesDirTxN() {
		return this.soEolproductImagesDirTxN;
	}

	public void setSoEolproductImagesDirTxN(String soEolproductImagesDirTxN) {
		this.soEolproductImagesDirTxN = soEolproductImagesDirTxN;
	}

	@Column(name = "SoEOLProductThumbsDirTx_N")
	public String getSoEolproductThumbsDirTxN() {
		return this.soEolproductThumbsDirTxN;
	}

	public void setSoEolproductThumbsDirTxN(String soEolproductThumbsDirTxN) {
		this.soEolproductThumbsDirTxN = soEolproductThumbsDirTxN;
	}

	@Column(name = "SoEOLMediaDirTx_N")
	public String getSoEolmediaDirTxN() {
		return this.soEolmediaDirTxN;
	}

	public void setSoEolmediaDirTxN(String soEolmediaDirTxN) {
		this.soEolmediaDirTxN = soEolmediaDirTxN;
	}

	@Column(name = "SoEOLProductXmlPathTx_N")
	public String getSoEolproductXmlPathTxN() {
		return this.soEolproductXmlPathTxN;
	}

	public void setSoEolproductXmlPathTxN(String soEolproductXmlPathTxN) {
		this.soEolproductXmlPathTxN = soEolproductXmlPathTxN;
	}

	@Column(name = "SoEOLShopEmailRecipientListTx_N")
	public String getSoEolshopEmailRecipientListTxN() {
		return this.soEolshopEmailRecipientListTxN;
	}

	public void setSoEolshopEmailRecipientListTxN(String soEolshopEmailRecipientListTxN) {
		this.soEolshopEmailRecipientListTxN = soEolshopEmailRecipientListTxN;
	}

	@Column(name = "SoEOLTerrestrialStoreID", nullable = false)
	public short getSoEolterrestrialStoreId() {
		return this.soEolterrestrialStoreId;
	}

	public void setSoEolterrestrialStoreId(short soEolterrestrialStoreId) {
		this.soEolterrestrialStoreId = soEolterrestrialStoreId;
	}

	@Column(name = "SoEOLCostCenterID", nullable = false)
	public int getSoEolcostCenterId() {
		return this.soEolcostCenterId;
	}

	public void setSoEolcostCenterId(int soEolcostCenterId) {
		this.soEolcostCenterId = soEolcostCenterId;
	}

	@Column(name = "SoEOLEmpID", nullable = false)
	public int getSoEolempId() {
		return this.soEolempId;
	}

	public void setSoEolempId(int soEolempId) {
		this.soEolempId = soEolempId;
	}

	@Column(name = "SoEOLPCID", nullable = false)
	public short getSoEolpcid() {
		return this.soEolpcid;
	}

	public void setSoEolpcid(short soEolpcid) {
		this.soEolpcid = soEolpcid;
	}

	@Column(name = "SoEOLUseQSStoreParamsBl", nullable = false)
	public boolean isSoEoluseQsstoreParamsBl() {
		return this.soEoluseQsstoreParamsBl;
	}

	public void setSoEoluseQsstoreParamsBl(boolean soEoluseQsstoreParamsBl) {
		this.soEoluseQsstoreParamsBl = soEoluseQsstoreParamsBl;
	}

	@Column(name = "SoEOLShippingStockTypeID", nullable = false)
	public int getSoEolshippingStockTypeId() {
		return this.soEolshippingStockTypeId;
	}

	public void setSoEolshippingStockTypeId(int soEolshippingStockTypeId) {
		this.soEolshippingStockTypeId = soEolshippingStockTypeId;
	}

	@Column(name = "SoEOLReadOnlyBl", nullable = false)
	public boolean isSoEolreadOnlyBl() {
		return this.soEolreadOnlyBl;
	}

	public void setSoEolreadOnlyBl(boolean soEolreadOnlyBl) {
		this.soEolreadOnlyBl = soEolreadOnlyBl;
	}

	@Column(name = "SoEOLCourseEnrollStatusID_N")
	public Integer getSoEolcourseEnrollStatusIdN() {
		return this.soEolcourseEnrollStatusIdN;
	}

	public void setSoEolcourseEnrollStatusIdN(Integer soEolcourseEnrollStatusIdN) {
		this.soEolcourseEnrollStatusIdN = soEolcourseEnrollStatusIdN;
	}

	@Column(name = "SoEOLTripEnrollStatusID_N")
	public Integer getSoEoltripEnrollStatusIdN() {
		return this.soEoltripEnrollStatusIdN;
	}

	public void setSoEoltripEnrollStatusIdN(Integer soEoltripEnrollStatusIdN) {
		this.soEoltripEnrollStatusIdN = soEoltripEnrollStatusIdN;
	}

	@Column(name = "SoCultureTx_N")
	public String getSoCultureTxN() {
		return this.soCultureTxN;
	}

	public void setSoCultureTxN(String soCultureTxN) {
		this.soCultureTxN = soCultureTxN;
	}

	@Column(name = "SoPADIUserIDTx_N")
	public String getSoPadiuserIdtxN() {
		return this.soPadiuserIdtxN;
	}

	public void setSoPadiuserIdtxN(String soPadiuserIdtxN) {
		this.soPadiuserIdtxN = soPadiuserIdtxN;
	}

	@Column(name = "SoPADIPWTx_N")
	public String getSoPadipwtxN() {
		return this.soPadipwtxN;
	}

	public void setSoPadipwtxN(String soPadipwtxN) {
		this.soPadipwtxN = soPadipwtxN;
	}

	@Column(name = "SoUserDefined1Tx_N")
	public String getSoUserDefined1txN() {
		return this.soUserDefined1txN;
	}

	public void setSoUserDefined1txN(String soUserDefined1txN) {
		this.soUserDefined1txN = soUserDefined1txN;
	}

	@Column(name = "SoUserDefined2Tx_N")
	public String getSoUserDefined2txN() {
		return this.soUserDefined2txN;
	}

	public void setSoUserDefined2txN(String soUserDefined2txN) {
		this.soUserDefined2txN = soUserDefined2txN;
	}

	@Column(name = "SoUserDefined3Tx_N")
	public String getSoUserDefined3txN() {
		return this.soUserDefined3txN;
	}

	public void setSoUserDefined3txN(String soUserDefined3txN) {
		this.soUserDefined3txN = soUserDefined3txN;
	}

	@Column(name = "SoEOLCustTypeIDEOLPriceIn", nullable = false)
	public int getSoEolcustTypeIdeolpriceIn() {
		return this.soEolcustTypeIdeolpriceIn;
	}

	public void setSoEolcustTypeIdeolpriceIn(int soEolcustTypeIdeolpriceIn) {
		this.soEolcustTypeIdeolpriceIn = soEolcustTypeIdeolpriceIn;
	}

	@Column(name = "SoEOLCustTypeIDRegularPriceIn", nullable = false)
	public int getSoEolcustTypeIdregularPriceIn() {
		return this.soEolcustTypeIdregularPriceIn;
	}

	public void setSoEolcustTypeIdregularPriceIn(int soEolcustTypeIdregularPriceIn) {
		this.soEolcustTypeIdregularPriceIn = soEolcustTypeIdregularPriceIn;
	}

	@Column(name = "SoEOLCustTypeIDMinPriceIn", nullable = false)
	public int getSoEolcustTypeIdminPriceIn() {
		return this.soEolcustTypeIdminPriceIn;
	}

	public void setSoEolcustTypeIdminPriceIn(int soEolcustTypeIdminPriceIn) {
		this.soEolcustTypeIdminPriceIn = soEolcustTypeIdminPriceIn;
	}

	@Column(name = "SoPICStoreID_N")
	public Short getSoPicstoreIdN() {
		return this.soPicstoreIdN;
	}

	public void setSoPicstoreIdN(Short soPicstoreIdN) {
		this.soPicstoreIdN = soPicstoreIdN;
	}

	@Column(name = "SoImageTx_N")
	public String getSoImageTxN() {
		return this.soImageTxN;
	}

	public void setSoImageTxN(String soImageTxN) {
		this.soImageTxN = soImageTxN;
	}

	@Column(name = "SoFacebookTx_N")
	public String getSoFacebookTxN() {
		return this.soFacebookTxN;
	}

	public void setSoFacebookTxN(String soFacebookTxN) {
		this.soFacebookTxN = soFacebookTxN;
	}

	@Column(name = "SoCheckInTimeTx_N")
	public String getSoCheckInTimeTxN() {
		return this.soCheckInTimeTxN;
	}

	public void setSoCheckInTimeTxN(String soCheckInTimeTxN) {
		this.soCheckInTimeTxN = soCheckInTimeTxN;
	}

	@Column(name = "SoCheckOutTimeTx_N")
	public String getSoCheckOutTimeTxN() {
		return this.soCheckOutTimeTxN;
	}

	public void setSoCheckOutTimeTxN(String soCheckOutTimeTxN) {
		this.soCheckOutTimeTxN = soCheckOutTimeTxN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TTkTask> getTTkTasks() {
		return this.TTkTasks;
	}

	public void setTTkTasks(Set<TTkTask> TTkTasks) {
		this.TTkTasks = TTkTasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TPaPodeliveryItem> getTPaPodeliveryItems() {
		return this.TPaPodeliveryItems;
	}

	public void setTPaPodeliveryItems(Set<TPaPodeliveryItem> TPaPodeliveryItems) {
		this.TPaPodeliveryItems = TPaPodeliveryItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TZlStoreStockItem> getTZlStoreStockItems() {
		return this.TZlStoreStockItems;
	}

	public void setTZlStoreStockItems(Set<TZlStoreStockItem> TZlStoreStockItems) {
		this.TZlStoreStockItems = TZlStoreStockItems;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_Z4StoreCostCenter", joinColumns = {
			@JoinColumn(name = "Z4StoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Z4CostCenterID", nullable = false, updatable = false) })
	public Set<TCccostCenter> getTCccostCenters() {
		return this.TCccostCenters;
	}

	public void setTCccostCenters(Set<TCccostCenter> TCccostCenters) {
		this.TCccostCenters = TCccostCenters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStoreByPostoreId")
	public Set<TPopo> getTPoposForPostoreId() {
		return this.TPoposForPostoreId;
	}

	public void setTPoposForPostoreId(Set<TPopo> TPoposForPostoreId) {
		this.TPoposForPostoreId = TPoposForPostoreId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TC8custInterest> getTC8custInterests() {
		return this.TC8custInterests;
	}

	public void setTC8custInterests(Set<TC8custInterest> TC8custInterests) {
		this.TC8custInterests = TC8custInterests;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TRbrentalBooking> getTRbrentalBookings() {
		return this.TRbrentalBookings;
	}

	public void setTRbrentalBookings(Set<TRbrentalBooking> TRbrentalBookings) {
		this.TRbrentalBookings = TRbrentalBookings;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZaStoreGLAccount", joinColumns = {
			@JoinColumn(name = "ZaStoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZaGLAccountID", nullable = false, updatable = false) })
	public Set<TGlaccount> getTGlaccounts() {
		return this.TGlaccounts;
	}

	public void setTGlaccounts(Set<TGlaccount> TGlaccounts) {
		this.TGlaccounts = TGlaccounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStoreByPoshipToStoreId")
	public Set<TPopo> getTPoposForPoshipToStoreId() {
		return this.TPoposForPoshipToStoreId;
	}

	public void setTPoposForPoshipToStoreId(Set<TPopo> TPoposForPoshipToStoreId) {
		this.TPoposForPoshipToStoreId = TPoposForPoshipToStoreId;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZfStoreMailingList", joinColumns = {
			@JoinColumn(name = "ZfStoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZfMailingListID", nullable = false, updatable = false) })
	public Set<TMlmailingList> getTMlmailingLists() {
		return this.TMlmailingLists;
	}

	public void setTMlmailingLists(Set<TMlmailingList> TMlmailingLists) {
		this.TMlmailingLists = TMlmailingLists;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_Z8StoreDenomination", joinColumns = {
			@JoinColumn(name = "Z8StoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Z8DenominationID", nullable = false, updatable = false) })
	public Set<TDnDenomination> getTDnDenominations() {
		return this.TDnDenominations;
	}

	public void setTDnDenominations(Set<TDnDenomination> TDnDenominations) {
		this.TDnDenominations = TDnDenominations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TQuQuote> getTQuQuotes() {
		return this.TQuQuotes;
	}

	public void setTQuQuotes(Set<TQuQuote> TQuQuotes) {
		this.TQuQuotes = TQuQuotes;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_Z3StoreClub", joinColumns = {
			@JoinColumn(name = "Z3StoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Z3ClubID", nullable = false, updatable = false) })
	public Set<TCbClub> getTCbClubs() {
		return this.TCbClubs;
	}

	public void setTCbClubs(Set<TCbClub> TCbClubs) {
		this.TCbClubs = TCbClubs;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_Z7StoreCustType", joinColumns = {
			@JoinColumn(name = "Z7StoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Z7CustTypeID", nullable = false, updatable = false) })
	public Set<TChCustType> getTChCustTypes() {
		return this.TChCustTypes;
	}

	public void setTChCustTypes(Set<TChCustType> TChCustTypes) {
		this.TChCustTypes = TChCustTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TCsCourse> getTCsCourses() {
		return this.TCsCourses;
	}

	public void setTCsCourses(Set<TCsCourse> TCsCourses) {
		this.TCsCourses = TCsCourses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TZoStoreDataType> getTZoStoreDataTypes() {
		return this.TZoStoreDataTypes;
	}

	public void setTZoStoreDataTypes(Set<TZoStoreDataType> TZoStoreDataTypes) {
		this.TZoStoreDataTypes = TZoStoreDataTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TCeCostPrice> getTCeCostPrices() {
		return this.TCeCostPrices;
	}

	public void setTCeCostPrices(Set<TCeCostPrice> TCeCostPrices) {
		this.TCeCostPrices = TCeCostPrices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TIsinvoiceTypeStore> getTIsinvoiceTypeStores() {
		return this.TIsinvoiceTypeStores;
	}

	public void setTIsinvoiceTypeStores(Set<TIsinvoiceTypeStore> TIsinvoiceTypeStores) {
		this.TIsinvoiceTypeStores = TIsinvoiceTypeStores;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TVsvalidState> getTVsvalidStates() {
		return this.TVsvalidStates;
	}

	public void setTVsvalidStates(Set<TVsvalidState> TVsvalidStates) {
		this.TVsvalidStates = TVsvalidStates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TDfDefault> getTDfDefaults() {
		return this.TDfDefaults;
	}

	public void setTDfDefaults(Set<TDfDefault> TDfDefaults) {
		this.TDfDefaults = TDfDefaults;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_Z0StoreEmp", joinColumns = {
			@JoinColumn(name = "Z0StoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Z0EmpID", nullable = false, updatable = false) })
	public Set<TEmEmp> getTEmEmps() {
		return this.TEmEmps;
	}

	public void setTEmEmps(Set<TEmEmp> TEmEmps) {
		this.TEmEmps = TEmEmps;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZdStoreHotel", joinColumns = {
			@JoinColumn(name = "ZdStoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZdHotelID", nullable = false, updatable = false) })
	public Set<THtHotel> getTHtHotels() {
		return this.THtHotels;
	}

	public void setTHtHotels(Set<THtHotel> THtHotels) {
		this.THtHotels = THtHotels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TSbserviceBooking> getTSbserviceBookings() {
		return this.TSbserviceBookings;
	}

	public void setTSbserviceBookings(Set<TSbserviceBooking> TSbserviceBookings) {
		this.TSbserviceBookings = TSbserviceBookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TTpTrip> getTTpTrips() {
		return this.TTpTrips;
	}

	public void setTTpTrips(Set<TTpTrip> TTpTrips) {
		this.TTpTrips = TTpTrips;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TAnClosing> getTAnClosings() {
		return this.TAnClosings;
	}

	public void setTAnClosings(Set<TAnClosing> TAnClosings) {
		this.TAnClosings = TAnClosings;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZjStoreSource", joinColumns = {
			@JoinColumn(name = "ZjStoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZjSourceID", nullable = false, updatable = false) })
	public Set<TScSource> getTScSources() {
		return this.TScSources;
	}

	public void setTScSources(Set<TScSource> TScSources) {
		this.TScSources = TScSources;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStoreByS6childStoreId")
	public Set<TS6storeConfig> getTS6storeConfigsForS6childStoreId() {
		return this.TS6storeConfigsForS6childStoreId;
	}

	public void setTS6storeConfigsForS6childStoreId(Set<TS6storeConfig> TS6storeConfigsForS6childStoreId) {
		this.TS6storeConfigsForS6childStoreId = TS6storeConfigsForS6childStoreId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStoreByTrSourceStoreId")
	public Set<TTrTransfer> getTTrTransfersForTrSourceStoreId() {
		return this.TTrTransfersForTrSourceStoreId;
	}

	public void setTTrTransfersForTrSourceStoreId(Set<TTrTransfer> TTrTransfersForTrSourceStoreId) {
		this.TTrTransfersForTrSourceStoreId = TTrTransfersForTrSourceStoreId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TEkEmpClockIn> getTEkEmpClockIns() {
		return this.TEkEmpClockIns;
	}

	public void setTEkEmpClockIns(Set<TEkEmpClockIn> TEkEmpClockIns) {
		this.TEkEmpClockIns = TEkEmpClockIns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStoreByTrDestStoreId")
	public Set<TTrTransfer> getTTrTransfersForTrDestStoreId() {
		return this.TTrTransfersForTrDestStoreId;
	}

	public void setTTrTransfersForTrDestStoreId(Set<TTrTransfer> TTrTransfersForTrDestStoreId) {
		this.TTrTransfersForTrDestStoreId = TTrTransfersForTrDestStoreId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TPpPaymentProvider> getTPpPaymentProviders() {
		return this.TPpPaymentProviders;
	}

	public void setTPpPaymentProviders(Set<TPpPaymentProvider> TPpPaymentProviders) {
		this.TPpPaymentProviders = TPpPaymentProviders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TCuCust> getTCuCusts() {
		return this.TCuCusts;
	}

	public void setTCuCusts(Set<TCuCust> TCuCusts) {
		this.TCuCusts = TCuCusts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TAoCommissionClosing> getTAoCommissionClosings() {
		return this.TAoCommissionClosings;
	}

	public void setTAoCommissionClosings(Set<TAoCommissionClosing> TAoCommissionClosings) {
		this.TAoCommissionClosings = TAoCommissionClosings;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_Z6StoreCourseType", joinColumns = {
			@JoinColumn(name = "Z6StoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Z6CourseTypeID", nullable = false, updatable = false) })
	public Set<TCtcourseType> getTCtcourseTypes() {
		return this.TCtcourseTypes;
	}

	public void setTCtcourseTypes(Set<TCtcourseType> TCtcourseTypes) {
		this.TCtcourseTypes = TCtcourseTypes;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_Z9StoreDestination", joinColumns = {
			@JoinColumn(name = "Z9StoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Z9DestinationID", nullable = false, updatable = false) })
	public Set<TDtDestination> getTDtDestinations() {
		return this.TDtDestinations;
	}

	public void setTDtDestinations(Set<TDtDestination> TDtDestinations) {
		this.TDtDestinations = TDtDestinations;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZhStorePaymentMethod", joinColumns = {
			@JoinColumn(name = "ZhStoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZhPaymentMethodID", nullable = false, updatable = false) })
	public Set<TPmpaymentMethod> getTPmpaymentMethods() {
		return this.TPmpaymentMethods;
	}

	public void setTPmpaymentMethods(Set<TPmpaymentMethod> TPmpaymentMethods) {
		this.TPmpaymentMethods = TPmpaymentMethods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TVoVoucher> getTVoVouchers() {
		return this.TVoVouchers;
	}

	public void setTVoVouchers(Set<TVoVoucher> TVoVouchers) {
		this.TVoVouchers = TVoVouchers;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZVStoreVan", joinColumns = {
			@JoinColumn(name = "ZVStoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZVVanID", nullable = false, updatable = false) })
	public Set<TVnVan> getTVnVans() {
		return this.TVnVans;
	}

	public void setTVnVans(Set<TVnVan> TVnVans) {
		this.TVnVans = TVnVans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TPcpc> getTPcpcs() {
		return this.TPcpcs;
	}

	public void setTPcpcs(Set<TPcpc> TPcpcs) {
		this.TPcpcs = TPcpcs;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZkStoreSpecialInterest", joinColumns = {
			@JoinColumn(name = "ZkStoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZkSpecialInterestID", nullable = false, updatable = false) })
	public Set<TS7specialInterest> getTS7specialInterests() {
		return this.TS7specialInterests;
	}

	public void setTS7specialInterests(Set<TS7specialInterest> TS7specialInterests) {
		this.TS7specialInterests = TS7specialInterests;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TVcvalidCountry> getTVcvalidCountries() {
		return this.TVcvalidCountries;
	}

	public void setTVcvalidCountries(Set<TVcvalidCountry> TVcvalidCountries) {
		this.TVcvalidCountries = TVcvalidCountries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TAcAccount> getTAcAccounts() {
		return this.TAcAccounts;
	}

	public void setTAcAccounts(Set<TAcAccount> TAcAccounts) {
		this.TAcAccounts = TAcAccounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TC1custCourse> getTC1custCourses() {
		return this.TC1custCourses;
	}

	public void setTC1custCourses(Set<TC1custCourse> TC1custCourses) {
		this.TC1custCourses = TC1custCourses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_Z2StoreCertAgency", joinColumns = {
			@JoinColumn(name = "Z2StoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Z2CertAgencyID", nullable = false, updatable = false) })
	public Set<TCacertAgency> getTCacertAgencies() {
		return this.TCacertAgencies;
	}

	public void setTCacertAgencies(Set<TCacertAgency> TCacertAgencies) {
		this.TCacertAgencies = TCacertAgencies;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZnStoreTaxBand", joinColumns = {
			@JoinColumn(name = "ZnStoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZnTaxBandID", nullable = false, updatable = false) })
	public Set<TTbtaxBand> getTTbtaxBands() {
		return this.TTbtaxBands;
	}

	public void setTTbtaxBands(Set<TTbtaxBand> TTbtaxBands) {
		this.TTbtaxBands = TTbtaxBands;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TGdGiftCard> getTGdGiftCards() {
		return this.TGdGiftCards;
	}

	public void setTGdGiftCards(Set<TGdGiftCard> TGdGiftCards) {
		this.TGdGiftCards = TGdGiftCards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TSkSupplierStockItem> getTSkSupplierStockItems() {
		return this.TSkSupplierStockItems;
	}

	public void setTSkSupplierStockItems(Set<TSkSupplierStockItem> TSkSupplierStockItems) {
		this.TSkSupplierStockItems = TSkSupplierStockItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TInInvoice> getTInInvoices() {
		return this.TInInvoices;
	}

	public void setTInInvoices(Set<TInInvoice> TInInvoices) {
		this.TInInvoices = TInInvoices;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZgStoreMembershipType", joinColumns = {
			@JoinColumn(name = "ZgStoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZgMembershipTypeID", nullable = false, updatable = false) })
	public Set<TMmMembershipType> getTMmMembershipTypes() {
		return this.TMmMembershipTypes;
	}

	public void setTMmMembershipTypes(Set<TMmMembershipType> TMmMembershipTypes) {
		this.TMmMembershipTypes = TMmMembershipTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TLqlabelQueue> getTLqlabelQueues() {
		return this.TLqlabelQueues;
	}

	public void setTLqlabelQueues(Set<TLqlabelQueue> TLqlabelQueues) {
		this.TLqlabelQueues = TLqlabelQueues;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZeStoreLocation", joinColumns = {
			@JoinColumn(name = "ZeStoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZeLocationID", nullable = false, updatable = false) })
	public Set<TLcLocation> getTLcLocations() {
		return this.TLcLocations;
	}

	public void setTLcLocations(Set<TLcLocation> TLcLocations) {
		this.TLcLocations = TLcLocations;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_Z1StoreBoat", joinColumns = {
			@JoinColumn(name = "Z1StoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Z1BoatID", nullable = false, updatable = false) })
	public Set<TBtBoat> getTBtBoats() {
		return this.TBtBoats;
	}

	public void setTBtBoats(Set<TBtBoat> TBtBoats) {
		this.TBtBoats = TBtBoats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TCdCustOrder> getTCdCustOrders() {
		return this.TCdCustOrders;
	}

	public void setTCdCustOrders(Set<TCdCustOrder> TCdCustOrders) {
		this.TCdCustOrders = TCdCustOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TSnserialNo> getTSnserialNos() {
		return this.TSnserialNos;
	}

	public void setTSnserialNos(Set<TSnserialNo> TSnserialNos) {
		this.TSnserialNos = TSnserialNos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TRrreportRun> getTRrreportRuns() {
		return this.TRrreportRuns;
	}

	public void setTRrreportRuns(Set<TRrreportRun> TRrreportRuns) {
		this.TRrreportRuns = TRrreportRuns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TSjShippingPrice> getTSjShippingPrices() {
		return this.TSjShippingPrices;
	}

	public void setTSjShippingPrices(Set<TSjShippingPrice> TSjShippingPrices) {
		this.TSjShippingPrices = TSjShippingPrices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TGcgiftCert> getTGcgiftCerts() {
		return this.TGcgiftCerts;
	}

	public void setTGcgiftCerts(Set<TGcgiftCert> TGcgiftCerts) {
		this.TGcgiftCerts = TGcgiftCerts;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZiStoreProfitCenter", joinColumns = {
			@JoinColumn(name = "ZiStoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZiProfitCenterID", nullable = false, updatable = false) })
	public Set<TPfProfitCenter> getTPfProfitCenters() {
		return this.TPfProfitCenters;
	}

	public void setTPfProfitCenters(Set<TPfProfitCenter> TPfProfitCenters) {
		this.TPfProfitCenters = TPfProfitCenters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TRkRoomBooking> getTRkRoomBookings() {
		return this.TRkRoomBookings;
	}

	public void setTRkRoomBookings(Set<TRkRoomBooking> TRkRoomBookings) {
		this.TRkRoomBookings = TRkRoomBookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TCnContact> getTCnContacts() {
		return this.TCnContacts;
	}

	public void setTCnContacts(Set<TCnContact> TCnContacts) {
		this.TCnContacts = TCnContacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TZ5storeSupplier> getTZ5storeSuppliers() {
		return this.TZ5storeSuppliers;
	}

	public void setTZ5storeSuppliers(Set<TZ5storeSupplier> TZ5storeSuppliers) {
		this.TZ5storeSuppliers = TZ5storeSuppliers;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZbStoreEquipment", joinColumns = {
			@JoinColumn(name = "ZbStoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZbEquipmentID", nullable = false, updatable = false) })
	public Set<TEqEquipment> getTEqEquipments() {
		return this.TEqEquipments;
	}

	public void setTEqEquipments(Set<TEqEquipment> TEqEquipments) {
		this.TEqEquipments = TEqEquipments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStoreByS6parentStoreId")
	public Set<TS6storeConfig> getTS6storeConfigsForS6parentStoreId() {
		return this.TS6storeConfigsForS6parentStoreId;
	}

	public void setTS6storeConfigsForS6parentStoreId(Set<TS6storeConfig> TS6storeConfigsForS6parentStoreId) {
		this.TS6storeConfigsForS6parentStoreId = TS6storeConfigsForS6parentStoreId;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZmStoreStockType", joinColumns = {
			@JoinColumn(name = "ZmStoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZmStockTypeID", nullable = false, updatable = false) })
	public Set<TStstockType> getTStstockTypes() {
		return this.TStstockTypes;
	}

	public void setTStstockTypes(Set<TStstockType> TStstockTypes) {
		this.TStstockTypes = TStstockTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSoStore")
	public Set<TShShortcut> getTShShortcuts() {
		return this.TShShortcuts;
	}

	public void setTShShortcuts(Set<TShShortcut> TShShortcuts) {
		this.TShShortcuts = TShShortcuts;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZpStoreInventoryLocation", joinColumns = {
			@JoinColumn(name = "ZpStoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZpInventoryLocationID", nullable = false, updatable = false) })
	public Set<TIcInventoryLocation> getTIcInventoryLocations() {
		return this.TIcInventoryLocations;
	}

	public void setTIcInventoryLocations(Set<TIcInventoryLocation> TIcInventoryLocations) {
		this.TIcInventoryLocations = TIcInventoryLocations;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZQStoreReportLayout", joinColumns = {
			@JoinColumn(name = "ZQStoreID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZQReportLayoutID", nullable = false, updatable = false) })
	public Set<TRlreportLayout> getTRlreportLayouts() {
		return this.TRlreportLayouts;
	}

	public void setTRlreportLayouts(Set<TRlreportLayout> TRlreportLayouts) {
		this.TRlreportLayouts = TRlreportLayouts;
	}

}
