package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TSrshippingRate generated by hbm2java
 */
@Entity
@Table(name = "T_SRShippingRate")
public class TSrshippingRate implements java.io.Serializable {

	private int srShippingRateId;
	private String srService;
	private BigDecimal srRate;
	private BigDecimal srAmountPerUnit;
	private boolean srIsAirOnly;
	private boolean srIsGroundOnly;
	private Date srCreatedOn;
	private String srCreatedBy;
	private Date srModifiedOn;
	private String srModifiedBy;

	public TSrshippingRate() {
	}

	public TSrshippingRate(int srShippingRateId, String srService, BigDecimal srAmountPerUnit, boolean srIsAirOnly,
			boolean srIsGroundOnly) {
		this.srShippingRateId = srShippingRateId;
		this.srService = srService;
		this.srAmountPerUnit = srAmountPerUnit;
		this.srIsAirOnly = srIsAirOnly;
		this.srIsGroundOnly = srIsGroundOnly;
	}

	public TSrshippingRate(int srShippingRateId, String srService, BigDecimal srRate, BigDecimal srAmountPerUnit,
			boolean srIsAirOnly, boolean srIsGroundOnly, Date srCreatedOn, String srCreatedBy, Date srModifiedOn,
			String srModifiedBy) {
		this.srShippingRateId = srShippingRateId;
		this.srService = srService;
		this.srRate = srRate;
		this.srAmountPerUnit = srAmountPerUnit;
		this.srIsAirOnly = srIsAirOnly;
		this.srIsGroundOnly = srIsGroundOnly;
		this.srCreatedOn = srCreatedOn;
		this.srCreatedBy = srCreatedBy;
		this.srModifiedOn = srModifiedOn;
		this.srModifiedBy = srModifiedBy;
	}

	@Id

	@Column(name = "SrShippingRateID", unique = true, nullable = false)
	public int getSrShippingRateId() {
		return this.srShippingRateId;
	}

	public void setSrShippingRateId(int srShippingRateId) {
		this.srShippingRateId = srShippingRateId;
	}

	@Column(name = "SrService", nullable = false, length = 50)
	public String getSrService() {
		return this.srService;
	}

	public void setSrService(String srService) {
		this.srService = srService;
	}

	@Column(name = "SrRate", scale = 4)
	public BigDecimal getSrRate() {
		return this.srRate;
	}

	public void setSrRate(BigDecimal srRate) {
		this.srRate = srRate;
	}

	@Column(name = "SrAmountPerUnit", nullable = false, scale = 4)
	public BigDecimal getSrAmountPerUnit() {
		return this.srAmountPerUnit;
	}

	public void setSrAmountPerUnit(BigDecimal srAmountPerUnit) {
		this.srAmountPerUnit = srAmountPerUnit;
	}

	@Column(name = "SrIsAirOnly", nullable = false)
	public boolean isSrIsAirOnly() {
		return this.srIsAirOnly;
	}

	public void setSrIsAirOnly(boolean srIsAirOnly) {
		this.srIsAirOnly = srIsAirOnly;
	}

	@Column(name = "SrIsGroundOnly", nullable = false)
	public boolean isSrIsGroundOnly() {
		return this.srIsGroundOnly;
	}

	public void setSrIsGroundOnly(boolean srIsGroundOnly) {
		this.srIsGroundOnly = srIsGroundOnly;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SrCreatedOn", length = 23)
	public Date getSrCreatedOn() {
		return this.srCreatedOn;
	}

	public void setSrCreatedOn(Date srCreatedOn) {
		this.srCreatedOn = srCreatedOn;
	}

	@Column(name = "SrCreatedBy")
	public String getSrCreatedBy() {
		return this.srCreatedBy;
	}

	public void setSrCreatedBy(String srCreatedBy) {
		this.srCreatedBy = srCreatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SrModifiedOn", length = 23)
	public Date getSrModifiedOn() {
		return this.srModifiedOn;
	}

	public void setSrModifiedOn(Date srModifiedOn) {
		this.srModifiedOn = srModifiedOn;
	}

	@Column(name = "SrModifiedBy")
	public String getSrModifiedBy() {
		return this.srModifiedBy;
	}

	public void setSrModifiedBy(String srModifiedBy) {
		this.srModifiedBy = srModifiedBy;
	}

}
