package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TSrsalesReport generated by hbm2java
 */
@Entity
@Table(name = "T_SRSalesReport", uniqueConstraints = @UniqueConstraint(columnNames = "SRDescriptionTx"))
public class TSrsalesReport implements java.io.Serializable {

	private int srsalesReportId;
	private String srdescriptionTx;
	private short srreportTypeIn;
	private Short srstoreIdN;
	private Integer srcostCenterIdN;
	private Integer srprofitCenterIdN;
	private Short srpcidN;
	private Integer sremployeeIdN;
	private short srreportGroupId;
	private boolean srincludePieBl;
	private boolean srshowTillFormBl;
	private boolean srrequiredBl;
	private boolean srcalcCommissionOnNetSalesBl;

	public TSrsalesReport() {
	}

	public TSrsalesReport(int srsalesReportId, String srdescriptionTx, short srreportTypeIn,
			short srreportGroupId, boolean srincludePieBl, boolean srshowTillFormBl, boolean srrequiredBl,
			boolean srcalcCommissionOnNetSalesBl) {
		this.srsalesReportId = srsalesReportId;
		this.srdescriptionTx = srdescriptionTx;
		this.srreportTypeIn = srreportTypeIn;
		this.srreportGroupId = srreportGroupId;
		this.srincludePieBl = srincludePieBl;
		this.srshowTillFormBl = srshowTillFormBl;
		this.srrequiredBl = srrequiredBl;
		this.srcalcCommissionOnNetSalesBl = srcalcCommissionOnNetSalesBl;
	}

	public TSrsalesReport(int srsalesReportId, String srdescriptionTx, short srreportTypeIn, Short srstoreIdN,
			Integer srcostCenterIdN, Integer srprofitCenterIdN, Short srpcidN, Integer sremployeeIdN,
			short srreportGroupId, boolean srincludePieBl, boolean srshowTillFormBl, boolean srrequiredBl,
			boolean srcalcCommissionOnNetSalesBl) {
		this.srsalesReportId = srsalesReportId;
		this.srdescriptionTx = srdescriptionTx;
		this.srreportTypeIn = srreportTypeIn;
		this.srstoreIdN = srstoreIdN;
		this.srcostCenterIdN = srcostCenterIdN;
		this.srprofitCenterIdN = srprofitCenterIdN;
		this.srpcidN = srpcidN;
		this.sremployeeIdN = sremployeeIdN;
		this.srreportGroupId = srreportGroupId;
		this.srincludePieBl = srincludePieBl;
		this.srshowTillFormBl = srshowTillFormBl;
		this.srrequiredBl = srrequiredBl;
		this.srcalcCommissionOnNetSalesBl = srcalcCommissionOnNetSalesBl;
	}

	@Id

	@Column(name = "SRSalesReportID", unique = true, nullable = false)
	public int getSrsalesReportId() {
		return this.srsalesReportId;
	}

	public void setSrsalesReportId(int srsalesReportId) {
		this.srsalesReportId = srsalesReportId;
	}

	@Column(name = "SRDescriptionTx", unique = true, nullable = false)
	public String getSrdescriptionTx() {
		return this.srdescriptionTx;
	}

	public void setSrdescriptionTx(String srdescriptionTx) {
		this.srdescriptionTx = srdescriptionTx;
	}

	@Column(name = "SRReportTypeIn", nullable = false)
	public short getSrreportTypeIn() {
		return this.srreportTypeIn;
	}

	public void setSrreportTypeIn(short srreportTypeIn) {
		this.srreportTypeIn = srreportTypeIn;
	}

	@Column(name = "SRStoreID_N")
	public Short getSrstoreIdN() {
		return this.srstoreIdN;
	}

	public void setSrstoreIdN(Short srstoreIdN) {
		this.srstoreIdN = srstoreIdN;
	}

	@Column(name = "SRCostCenterID_N")
	public Integer getSrcostCenterIdN() {
		return this.srcostCenterIdN;
	}

	public void setSrcostCenterIdN(Integer srcostCenterIdN) {
		this.srcostCenterIdN = srcostCenterIdN;
	}

	@Column(name = "SRProfitCenterID_N")
	public Integer getSrprofitCenterIdN() {
		return this.srprofitCenterIdN;
	}

	public void setSrprofitCenterIdN(Integer srprofitCenterIdN) {
		this.srprofitCenterIdN = srprofitCenterIdN;
	}

	@Column(name = "SRPCID_N")
	public Short getSrpcidN() {
		return this.srpcidN;
	}

	public void setSrpcidN(Short srpcidN) {
		this.srpcidN = srpcidN;
	}

	@Column(name = "SREmployeeID_N")
	public Integer getSremployeeIdN() {
		return this.sremployeeIdN;
	}

	public void setSremployeeIdN(Integer sremployeeIdN) {
		this.sremployeeIdN = sremployeeIdN;
	}

	@Column(name = "SRReportGroupID", nullable = false)
	public short getSrreportGroupId() {
		return this.srreportGroupId;
	}

	public void setSrreportGroupId(short srreportGroupId) {
		this.srreportGroupId = srreportGroupId;
	}

	@Column(name = "SRIncludePieBl", nullable = false)
	public boolean isSrincludePieBl() {
		return this.srincludePieBl;
	}

	public void setSrincludePieBl(boolean srincludePieBl) {
		this.srincludePieBl = srincludePieBl;
	}

	@Column(name = "SRShowTillFormBl", nullable = false)
	public boolean isSrshowTillFormBl() {
		return this.srshowTillFormBl;
	}

	public void setSrshowTillFormBl(boolean srshowTillFormBl) {
		this.srshowTillFormBl = srshowTillFormBl;
	}

	@Column(name = "SRRequiredBl", nullable = false)
	public boolean isSrrequiredBl() {
		return this.srrequiredBl;
	}

	public void setSrrequiredBl(boolean srrequiredBl) {
		this.srrequiredBl = srrequiredBl;
	}

	@Column(name = "SRCalcCommissionOnNetSalesBl", nullable = false)
	public boolean isSrcalcCommissionOnNetSalesBl() {
		return this.srcalcCommissionOnNetSalesBl;
	}

	public void setSrcalcCommissionOnNetSalesBl(boolean srcalcCommissionOnNetSalesBl) {
		this.srcalcCommissionOnNetSalesBl = srcalcCommissionOnNetSalesBl;
	}

}
