package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TStstockType generated by hbm2java
 */
@Entity
@Table(name = "T_STStockType", uniqueConstraints = @UniqueConstraint(columnNames = "STStockTypeTx"))
public class TStstockType implements java.io.Serializable {

	private int ststockTypeId;
	private TDbdiscountBand TDbdiscountBand;
	private TPfProfitCenter TPfProfitCenter;
	private String ststockTypeTx;
	private boolean stprofileBl;
	private boolean stforRentBl;
	private boolean stforServiceBl;
	private boolean stforServicePartsBl;
	private boolean stforSaleBl;
	private boolean sttrackOwnershipBl;
	private boolean stforChecklistBl;
	private boolean stcustomerRequiredBl;
	private boolean stunavailableBl;
	private Date stlastUpdatedDate;
	private float stcommissionRateFl;
	private boolean strequiredBl;
	private String stinvoiceTextTxN;
	private short stservicePeriodIn;
	private Date stcreationDate;
	private boolean stgiftCertPromptBl;
	private boolean stgiftCardPromptBl;
	private boolean stroomBookingPromptBl;
	private Integer strebiidN;
	private boolean stwebAdminEntryBl;
	private boolean stwebAdminDeletedBl;
	private boolean sttechnicianActivityBl;
	private int stdisplayOrderIn;
	private Short steventDataTypeIdN;
	private String stseotagTxN;
	private boolean stshowCylinderInfoBl;
	private String stclassNameTxN;
	private String steolstockTypeTxN;
	private int steolheaderId;
	private boolean stallowPriceUpdatesBl;
	private String stqtyBasedDiscountsTxN;
	private boolean stallowPaymentSurchargeBl;
	private Set<TEzSize> TEzSizes = new HashSet<TEzSize>(0);
	private Set<TVivoucherItem> TVivoucherItems = new HashSet<TVivoucherItem>(0);
	private Set<TSoStore> TSoStores = new HashSet<TSoStore>(0);
	private Set<TPrProfile> TPrProfiles = new HashSet<TPrProfile>(0);
	private Set<TCvCustTypeDiscountBand> TCvCustTypeDiscountBands = new HashSet<TCvCustTypeDiscountBand>(0);
	private Set<TC7costCenterStockType> TC7costCenterStockTypes = new HashSet<TC7costCenterStockType>(0);
	private Set<TCkCustTripChecklist> TCkCustTripChecklists = new HashSet<TCkCustTripChecklist>(0);
	private Set<TPipoitem> TPipoitems = new HashSet<TPipoitem>(0);
	private Set<TSistockItem> TSistockItems = new HashSet<TSistockItem>(0);
	private Set<TCiCustCourseChecklist> TCiCustCourseChecklists = new HashSet<TCiCustCourseChecklist>(0);
	private Set<TFvFavorite> TFvFavorites = new HashSet<TFvFavorite>(0);
	private Set<TQiquoteItem> TQiquoteItems = new HashSet<TQiquoteItem>(0);
	private Set<TIiinvoiceItem> TIiinvoiceItems = new HashSet<TIiinvoiceItem>(0);
	private Set<TS5stockTypeRentalPrice> TS5stockTypeRentalPrices = new HashSet<TS5stockTypeRentalPrice>(0);
	private Set<TEqEquipment> TEqEquipments = new HashSet<TEqEquipment>(0);
	private Set<TC5custEquipment> TC5custEquipments = new HashSet<TC5custEquipment>(0);

	public TStstockType() {
	}

	public TStstockType(int ststockTypeId, TPfProfitCenter TPfProfitCenter, String ststockTypeTx,
			boolean stprofileBl, boolean stforRentBl, boolean stforServiceBl, boolean stforServicePartsBl,
			boolean stforSaleBl, boolean sttrackOwnershipBl, boolean stforChecklistBl, boolean stcustomerRequiredBl,
			boolean stunavailableBl, Date stlastUpdatedDate, float stcommissionRateFl, boolean strequiredBl,
			short stservicePeriodIn, Date stcreationDate, boolean stgiftCertPromptBl, boolean stgiftCardPromptBl,
			boolean stroomBookingPromptBl, boolean stwebAdminEntryBl, boolean stwebAdminDeletedBl,
			boolean sttechnicianActivityBl, int stdisplayOrderIn, boolean stshowCylinderInfoBl, int steolheaderId,
			boolean stallowPriceUpdatesBl, boolean stallowPaymentSurchargeBl) {
		this.ststockTypeId = ststockTypeId;
		this.TPfProfitCenter = TPfProfitCenter;
		this.ststockTypeTx = ststockTypeTx;
		this.stprofileBl = stprofileBl;
		this.stforRentBl = stforRentBl;
		this.stforServiceBl = stforServiceBl;
		this.stforServicePartsBl = stforServicePartsBl;
		this.stforSaleBl = stforSaleBl;
		this.sttrackOwnershipBl = sttrackOwnershipBl;
		this.stforChecklistBl = stforChecklistBl;
		this.stcustomerRequiredBl = stcustomerRequiredBl;
		this.stunavailableBl = stunavailableBl;
		this.stlastUpdatedDate = stlastUpdatedDate;
		this.stcommissionRateFl = stcommissionRateFl;
		this.strequiredBl = strequiredBl;
		this.stservicePeriodIn = stservicePeriodIn;
		this.stcreationDate = stcreationDate;
		this.stgiftCertPromptBl = stgiftCertPromptBl;
		this.stgiftCardPromptBl = stgiftCardPromptBl;
		this.stroomBookingPromptBl = stroomBookingPromptBl;
		this.stwebAdminEntryBl = stwebAdminEntryBl;
		this.stwebAdminDeletedBl = stwebAdminDeletedBl;
		this.sttechnicianActivityBl = sttechnicianActivityBl;
		this.stdisplayOrderIn = stdisplayOrderIn;
		this.stshowCylinderInfoBl = stshowCylinderInfoBl;
		this.steolheaderId = steolheaderId;
		this.stallowPriceUpdatesBl = stallowPriceUpdatesBl;
		this.stallowPaymentSurchargeBl = stallowPaymentSurchargeBl;
	}

	public TStstockType(int ststockTypeId, TDbdiscountBand TDbdiscountBand, TPfProfitCenter TPfProfitCenter,
			String ststockTypeTx, boolean stprofileBl, boolean stforRentBl, boolean stforServiceBl,
			boolean stforServicePartsBl, boolean stforSaleBl, boolean sttrackOwnershipBl, boolean stforChecklistBl,
			boolean stcustomerRequiredBl, boolean stunavailableBl, Date stlastUpdatedDate, float stcommissionRateFl,
			boolean strequiredBl, String stinvoiceTextTxN, short stservicePeriodIn, Date stcreationDate,
			boolean stgiftCertPromptBl, boolean stgiftCardPromptBl, boolean stroomBookingPromptBl, Integer strebiidN,
			boolean stwebAdminEntryBl, boolean stwebAdminDeletedBl, boolean sttechnicianActivityBl,
			int stdisplayOrderIn, Short steventDataTypeIdN, String stseotagTxN, boolean stshowCylinderInfoBl,
			String stclassNameTxN, String steolstockTypeTxN, int steolheaderId, boolean stallowPriceUpdatesBl,
			String stqtyBasedDiscountsTxN, boolean stallowPaymentSurchargeBl, Set<TEzSize> TEzSizes,
			Set<TVivoucherItem> TVivoucherItems, Set<TSoStore> TSoStores, Set<TPrProfile> TPrProfiles,
			Set<TCvCustTypeDiscountBand> TCvCustTypeDiscountBands, Set<TC7costCenterStockType> TC7costCenterStockTypes,
			Set<TCkCustTripChecklist> TCkCustTripChecklists, Set<TPipoitem> TPipoitems, Set<TSistockItem> TSistockItems,
			Set<TCiCustCourseChecklist> TCiCustCourseChecklists, Set<TFvFavorite> TFvFavorites,
			Set<TQiquoteItem> TQiquoteItems, Set<TIiinvoiceItem> TIiinvoiceItems,
			Set<TS5stockTypeRentalPrice> TS5stockTypeRentalPrices, Set<TEqEquipment> TEqEquipments,
			Set<TC5custEquipment> TC5custEquipments) {
		this.ststockTypeId = ststockTypeId;
		this.TDbdiscountBand = TDbdiscountBand;
		this.TPfProfitCenter = TPfProfitCenter;
		this.ststockTypeTx = ststockTypeTx;
		this.stprofileBl = stprofileBl;
		this.stforRentBl = stforRentBl;
		this.stforServiceBl = stforServiceBl;
		this.stforServicePartsBl = stforServicePartsBl;
		this.stforSaleBl = stforSaleBl;
		this.sttrackOwnershipBl = sttrackOwnershipBl;
		this.stforChecklistBl = stforChecklistBl;
		this.stcustomerRequiredBl = stcustomerRequiredBl;
		this.stunavailableBl = stunavailableBl;
		this.stlastUpdatedDate = stlastUpdatedDate;
		this.stcommissionRateFl = stcommissionRateFl;
		this.strequiredBl = strequiredBl;
		this.stinvoiceTextTxN = stinvoiceTextTxN;
		this.stservicePeriodIn = stservicePeriodIn;
		this.stcreationDate = stcreationDate;
		this.stgiftCertPromptBl = stgiftCertPromptBl;
		this.stgiftCardPromptBl = stgiftCardPromptBl;
		this.stroomBookingPromptBl = stroomBookingPromptBl;
		this.strebiidN = strebiidN;
		this.stwebAdminEntryBl = stwebAdminEntryBl;
		this.stwebAdminDeletedBl = stwebAdminDeletedBl;
		this.sttechnicianActivityBl = sttechnicianActivityBl;
		this.stdisplayOrderIn = stdisplayOrderIn;
		this.steventDataTypeIdN = steventDataTypeIdN;
		this.stseotagTxN = stseotagTxN;
		this.stshowCylinderInfoBl = stshowCylinderInfoBl;
		this.stclassNameTxN = stclassNameTxN;
		this.steolstockTypeTxN = steolstockTypeTxN;
		this.steolheaderId = steolheaderId;
		this.stallowPriceUpdatesBl = stallowPriceUpdatesBl;
		this.stqtyBasedDiscountsTxN = stqtyBasedDiscountsTxN;
		this.stallowPaymentSurchargeBl = stallowPaymentSurchargeBl;
		this.TEzSizes = TEzSizes;
		this.TVivoucherItems = TVivoucherItems;
		this.TSoStores = TSoStores;
		this.TPrProfiles = TPrProfiles;
		this.TCvCustTypeDiscountBands = TCvCustTypeDiscountBands;
		this.TC7costCenterStockTypes = TC7costCenterStockTypes;
		this.TCkCustTripChecklists = TCkCustTripChecklists;
		this.TPipoitems = TPipoitems;
		this.TSistockItems = TSistockItems;
		this.TCiCustCourseChecklists = TCiCustCourseChecklists;
		this.TFvFavorites = TFvFavorites;
		this.TQiquoteItems = TQiquoteItems;
		this.TIiinvoiceItems = TIiinvoiceItems;
		this.TS5stockTypeRentalPrices = TS5stockTypeRentalPrices;
		this.TEqEquipments = TEqEquipments;
		this.TC5custEquipments = TC5custEquipments;
	}

	@Id

	@Column(name = "STStockTypeID", unique = true, nullable = false)
	public int getStstockTypeId() {
		return this.ststockTypeId;
	}

	public void setStstockTypeId(int ststockTypeId) {
		this.ststockTypeId = ststockTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STSaleDiscountBandID_N")
	public TDbdiscountBand getTDbdiscountBand() {
		return this.TDbdiscountBand;
	}

	public void setTDbdiscountBand(TDbdiscountBand TDbdiscountBand) {
		this.TDbdiscountBand = TDbdiscountBand;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STProfitCenterID", nullable = false)
	public TPfProfitCenter getTPfProfitCenter() {
		return this.TPfProfitCenter;
	}

	public void setTPfProfitCenter(TPfProfitCenter TPfProfitCenter) {
		this.TPfProfitCenter = TPfProfitCenter;
	}

	@Column(name = "STStockTypeTx", unique = true, nullable = false)
	public String getStstockTypeTx() {
		return this.ststockTypeTx;
	}

	public void setStstockTypeTx(String ststockTypeTx) {
		this.ststockTypeTx = ststockTypeTx;
	}

	@Column(name = "STProfileBl", nullable = false)
	public boolean isStprofileBl() {
		return this.stprofileBl;
	}

	public void setStprofileBl(boolean stprofileBl) {
		this.stprofileBl = stprofileBl;
	}

	@Column(name = "STForRentBl", nullable = false)
	public boolean isStforRentBl() {
		return this.stforRentBl;
	}

	public void setStforRentBl(boolean stforRentBl) {
		this.stforRentBl = stforRentBl;
	}

	@Column(name = "STForServiceBl", nullable = false)
	public boolean isStforServiceBl() {
		return this.stforServiceBl;
	}

	public void setStforServiceBl(boolean stforServiceBl) {
		this.stforServiceBl = stforServiceBl;
	}

	@Column(name = "STForServicePartsBl", nullable = false)
	public boolean isStforServicePartsBl() {
		return this.stforServicePartsBl;
	}

	public void setStforServicePartsBl(boolean stforServicePartsBl) {
		this.stforServicePartsBl = stforServicePartsBl;
	}

	@Column(name = "STForSaleBl", nullable = false)
	public boolean isStforSaleBl() {
		return this.stforSaleBl;
	}

	public void setStforSaleBl(boolean stforSaleBl) {
		this.stforSaleBl = stforSaleBl;
	}

	@Column(name = "STTrackOwnershipBl", nullable = false)
	public boolean isSttrackOwnershipBl() {
		return this.sttrackOwnershipBl;
	}

	public void setSttrackOwnershipBl(boolean sttrackOwnershipBl) {
		this.sttrackOwnershipBl = sttrackOwnershipBl;
	}

	@Column(name = "STForChecklistBl", nullable = false)
	public boolean isStforChecklistBl() {
		return this.stforChecklistBl;
	}

	public void setStforChecklistBl(boolean stforChecklistBl) {
		this.stforChecklistBl = stforChecklistBl;
	}

	@Column(name = "STCustomerRequiredBl", nullable = false)
	public boolean isStcustomerRequiredBl() {
		return this.stcustomerRequiredBl;
	}

	public void setStcustomerRequiredBl(boolean stcustomerRequiredBl) {
		this.stcustomerRequiredBl = stcustomerRequiredBl;
	}

	@Column(name = "STUnavailableBl", nullable = false)
	public boolean isStunavailableBl() {
		return this.stunavailableBl;
	}

	public void setStunavailableBl(boolean stunavailableBl) {
		this.stunavailableBl = stunavailableBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STLastUpdatedDate", nullable = false, length = 23)
	public Date getStlastUpdatedDate() {
		return this.stlastUpdatedDate;
	}

	public void setStlastUpdatedDate(Date stlastUpdatedDate) {
		this.stlastUpdatedDate = stlastUpdatedDate;
	}

	@Column(name = "STCommissionRateFl", nullable = false, precision = 24, scale = 0)
	public float getStcommissionRateFl() {
		return this.stcommissionRateFl;
	}

	public void setStcommissionRateFl(float stcommissionRateFl) {
		this.stcommissionRateFl = stcommissionRateFl;
	}

	@Column(name = "STRequiredBl", nullable = false)
	public boolean isStrequiredBl() {
		return this.strequiredBl;
	}

	public void setStrequiredBl(boolean strequiredBl) {
		this.strequiredBl = strequiredBl;
	}

	@Column(name = "STInvoiceTextTx_N")
	public String getStinvoiceTextTxN() {
		return this.stinvoiceTextTxN;
	}

	public void setStinvoiceTextTxN(String stinvoiceTextTxN) {
		this.stinvoiceTextTxN = stinvoiceTextTxN;
	}

	@Column(name = "STServicePeriodIn", nullable = false)
	public short getStservicePeriodIn() {
		return this.stservicePeriodIn;
	}

	public void setStservicePeriodIn(short stservicePeriodIn) {
		this.stservicePeriodIn = stservicePeriodIn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STCreationDate", nullable = false, length = 23)
	public Date getStcreationDate() {
		return this.stcreationDate;
	}

	public void setStcreationDate(Date stcreationDate) {
		this.stcreationDate = stcreationDate;
	}

	@Column(name = "STGiftCertPromptBl", nullable = false)
	public boolean isStgiftCertPromptBl() {
		return this.stgiftCertPromptBl;
	}

	public void setStgiftCertPromptBl(boolean stgiftCertPromptBl) {
		this.stgiftCertPromptBl = stgiftCertPromptBl;
	}

	@Column(name = "STGiftCardPromptBl", nullable = false)
	public boolean isStgiftCardPromptBl() {
		return this.stgiftCardPromptBl;
	}

	public void setStgiftCardPromptBl(boolean stgiftCardPromptBl) {
		this.stgiftCardPromptBl = stgiftCardPromptBl;
	}

	@Column(name = "STRoomBookingPromptBl", nullable = false)
	public boolean isStroomBookingPromptBl() {
		return this.stroomBookingPromptBl;
	}

	public void setStroomBookingPromptBl(boolean stroomBookingPromptBl) {
		this.stroomBookingPromptBl = stroomBookingPromptBl;
	}

	@Column(name = "STREBIID_N")
	public Integer getStrebiidN() {
		return this.strebiidN;
	}

	public void setStrebiidN(Integer strebiidN) {
		this.strebiidN = strebiidN;
	}

	@Column(name = "STWebAdminEntryBl", nullable = false)
	public boolean isStwebAdminEntryBl() {
		return this.stwebAdminEntryBl;
	}

	public void setStwebAdminEntryBl(boolean stwebAdminEntryBl) {
		this.stwebAdminEntryBl = stwebAdminEntryBl;
	}

	@Column(name = "STWebAdminDeletedBl", nullable = false)
	public boolean isStwebAdminDeletedBl() {
		return this.stwebAdminDeletedBl;
	}

	public void setStwebAdminDeletedBl(boolean stwebAdminDeletedBl) {
		this.stwebAdminDeletedBl = stwebAdminDeletedBl;
	}

	@Column(name = "STTechnicianActivityBl", nullable = false)
	public boolean isSttechnicianActivityBl() {
		return this.sttechnicianActivityBl;
	}

	public void setSttechnicianActivityBl(boolean sttechnicianActivityBl) {
		this.sttechnicianActivityBl = sttechnicianActivityBl;
	}

	@Column(name = "STDisplayOrderIn", nullable = false)
	public int getStdisplayOrderIn() {
		return this.stdisplayOrderIn;
	}

	public void setStdisplayOrderIn(int stdisplayOrderIn) {
		this.stdisplayOrderIn = stdisplayOrderIn;
	}

	@Column(name = "STEventDataTypeID_N")
	public Short getSteventDataTypeIdN() {
		return this.steventDataTypeIdN;
	}

	public void setSteventDataTypeIdN(Short steventDataTypeIdN) {
		this.steventDataTypeIdN = steventDataTypeIdN;
	}

	@Column(name = "STSEOTagTx_N")
	public String getStseotagTxN() {
		return this.stseotagTxN;
	}

	public void setStseotagTxN(String stseotagTxN) {
		this.stseotagTxN = stseotagTxN;
	}

	@Column(name = "STShowCylinderInfoBl", nullable = false)
	public boolean isStshowCylinderInfoBl() {
		return this.stshowCylinderInfoBl;
	}

	public void setStshowCylinderInfoBl(boolean stshowCylinderInfoBl) {
		this.stshowCylinderInfoBl = stshowCylinderInfoBl;
	}

	@Column(name = "STClassNameTx_N", length = 50)
	public String getStclassNameTxN() {
		return this.stclassNameTxN;
	}

	public void setStclassNameTxN(String stclassNameTxN) {
		this.stclassNameTxN = stclassNameTxN;
	}

	@Column(name = "STEOLStockTypeTx_N")
	public String getSteolstockTypeTxN() {
		return this.steolstockTypeTxN;
	}

	public void setSteolstockTypeTxN(String steolstockTypeTxN) {
		this.steolstockTypeTxN = steolstockTypeTxN;
	}

	@Column(name = "STEOLHeaderID", nullable = false)
	public int getSteolheaderId() {
		return this.steolheaderId;
	}

	public void setSteolheaderId(int steolheaderId) {
		this.steolheaderId = steolheaderId;
	}

	@Column(name = "STAllowPriceUpdatesBl", nullable = false)
	public boolean isStallowPriceUpdatesBl() {
		return this.stallowPriceUpdatesBl;
	}

	public void setStallowPriceUpdatesBl(boolean stallowPriceUpdatesBl) {
		this.stallowPriceUpdatesBl = stallowPriceUpdatesBl;
	}

	@Column(name = "STQtyBasedDiscountsTx_N")
	public String getStqtyBasedDiscountsTxN() {
		return this.stqtyBasedDiscountsTxN;
	}

	public void setStqtyBasedDiscountsTxN(String stqtyBasedDiscountsTxN) {
		this.stqtyBasedDiscountsTxN = stqtyBasedDiscountsTxN;
	}

	@Column(name = "STAllowPaymentSurchargeBl", nullable = false)
	public boolean isStallowPaymentSurchargeBl() {
		return this.stallowPaymentSurchargeBl;
	}

	public void setStallowPaymentSurchargeBl(boolean stallowPaymentSurchargeBl) {
		this.stallowPaymentSurchargeBl = stallowPaymentSurchargeBl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStstockType")
	public Set<TEzSize> getTEzSizes() {
		return this.TEzSizes;
	}

	public void setTEzSizes(Set<TEzSize> TEzSizes) {
		this.TEzSizes = TEzSizes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStstockType")
	public Set<TVivoucherItem> getTVivoucherItems() {
		return this.TVivoucherItems;
	}

	public void setTVivoucherItems(Set<TVivoucherItem> TVivoucherItems) {
		this.TVivoucherItems = TVivoucherItems;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "T_ZmStoreStockType", joinColumns = {
			@JoinColumn(name = "ZmStockTypeID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ZmStoreID", nullable = false, updatable = false) })
	public Set<TSoStore> getTSoStores() {
		return this.TSoStores;
	}

	public void setTSoStores(Set<TSoStore> TSoStores) {
		this.TSoStores = TSoStores;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStstockType")
	public Set<TPrProfile> getTPrProfiles() {
		return this.TPrProfiles;
	}

	public void setTPrProfiles(Set<TPrProfile> TPrProfiles) {
		this.TPrProfiles = TPrProfiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStstockType")
	public Set<TCvCustTypeDiscountBand> getTCvCustTypeDiscountBands() {
		return this.TCvCustTypeDiscountBands;
	}

	public void setTCvCustTypeDiscountBands(Set<TCvCustTypeDiscountBand> TCvCustTypeDiscountBands) {
		this.TCvCustTypeDiscountBands = TCvCustTypeDiscountBands;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStstockType")
	public Set<TC7costCenterStockType> getTC7costCenterStockTypes() {
		return this.TC7costCenterStockTypes;
	}

	public void setTC7costCenterStockTypes(Set<TC7costCenterStockType> TC7costCenterStockTypes) {
		this.TC7costCenterStockTypes = TC7costCenterStockTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStstockType")
	public Set<TCkCustTripChecklist> getTCkCustTripChecklists() {
		return this.TCkCustTripChecklists;
	}

	public void setTCkCustTripChecklists(Set<TCkCustTripChecklist> TCkCustTripChecklists) {
		this.TCkCustTripChecklists = TCkCustTripChecklists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStstockType")
	public Set<TPipoitem> getTPipoitems() {
		return this.TPipoitems;
	}

	public void setTPipoitems(Set<TPipoitem> TPipoitems) {
		this.TPipoitems = TPipoitems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStstockType")
	public Set<TSistockItem> getTSistockItems() {
		return this.TSistockItems;
	}

	public void setTSistockItems(Set<TSistockItem> TSistockItems) {
		this.TSistockItems = TSistockItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStstockType")
	public Set<TCiCustCourseChecklist> getTCiCustCourseChecklists() {
		return this.TCiCustCourseChecklists;
	}

	public void setTCiCustCourseChecklists(Set<TCiCustCourseChecklist> TCiCustCourseChecklists) {
		this.TCiCustCourseChecklists = TCiCustCourseChecklists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStstockType")
	public Set<TFvFavorite> getTFvFavorites() {
		return this.TFvFavorites;
	}

	public void setTFvFavorites(Set<TFvFavorite> TFvFavorites) {
		this.TFvFavorites = TFvFavorites;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStstockType")
	public Set<TQiquoteItem> getTQiquoteItems() {
		return this.TQiquoteItems;
	}

	public void setTQiquoteItems(Set<TQiquoteItem> TQiquoteItems) {
		this.TQiquoteItems = TQiquoteItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStstockType")
	public Set<TIiinvoiceItem> getTIiinvoiceItems() {
		return this.TIiinvoiceItems;
	}

	public void setTIiinvoiceItems(Set<TIiinvoiceItem> TIiinvoiceItems) {
		this.TIiinvoiceItems = TIiinvoiceItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStstockType")
	public Set<TS5stockTypeRentalPrice> getTS5stockTypeRentalPrices() {
		return this.TS5stockTypeRentalPrices;
	}

	public void setTS5stockTypeRentalPrices(Set<TS5stockTypeRentalPrice> TS5stockTypeRentalPrices) {
		this.TS5stockTypeRentalPrices = TS5stockTypeRentalPrices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStstockType")
	public Set<TEqEquipment> getTEqEquipments() {
		return this.TEqEquipments;
	}

	public void setTEqEquipments(Set<TEqEquipment> TEqEquipments) {
		this.TEqEquipments = TEqEquipments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TStstockType")
	public Set<TC5custEquipment> getTC5custEquipments() {
		return this.TC5custEquipments;
	}

	public void setTC5custEquipments(Set<TC5custEquipment> TC5custEquipments) {
		this.TC5custEquipments = TC5custEquipments;
	}

}
