package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TSwswtax2 generated by hbm2java
 */
@Entity
@Table(name = "T_SWSWTax2")
public class TSwswtax2 implements java.io.Serializable {

	private TSwswtax2Id id;

	public TSwswtax2() {
	}

	public TSwswtax2(TSwswtax2Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "swTaxTypeId", column = @Column(name = "SwTaxTypeID", nullable = false)),
			@AttributeOverride(name = "swTaxType", column = @Column(name = "SwTaxType")),
			@AttributeOverride(name = "swProximaTaxBandId", column = @Column(name = "SwProximaTaxBandID", nullable = false)),
			@AttributeOverride(name = "swProximaSubTaxBandId", column = @Column(name = "SwProximaSubTaxBandID", nullable = false)),
			@AttributeOverride(name = "swSubTaxType", column = @Column(name = "SwSubTaxType")),
			@AttributeOverride(name = "swTaxRate", column = @Column(name = "SwTaxRate", nullable = false, precision = 24, scale = 0)) })
	public TSwswtax2Id getId() {
		return this.id;
	}

	public void setId(TSwswtax2Id id) {
		this.id = id;
	}

}
