package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TSzStockCourseType generated by hbm2java
 */
@Entity
@Table(name = "T_SzStockCourseType", uniqueConstraints = @UniqueConstraint(columnNames = "SzStockItemID"))
public class TSzStockCourseType implements java.io.Serializable {

	private int szStockCourseTypeId;
	private TSistockItem TSistockItem;
	private TCtcourseType TCtcourseType;
	private boolean szOptionBl;
	private boolean szRequiredBl;
	private boolean szSundayBl;
	private boolean szMondayBl;
	private boolean szTuesdayBl;
	private boolean szWednesdayBl;
	private boolean szThursdayBl;
	private boolean szFridayBl;
	private boolean szSaturdayBl;
	private Date szStartDate;
	private Date szEndDate;

	public TSzStockCourseType() {
	}

	public TSzStockCourseType(int szStockCourseTypeId, TSistockItem TSistockItem, TCtcourseType TCtcourseType,
			boolean szOptionBl, boolean szRequiredBl, boolean szSundayBl, boolean szMondayBl, boolean szTuesdayBl,
			boolean szWednesdayBl, boolean szThursdayBl, boolean szFridayBl, boolean szSaturdayBl, Date szStartDate,
			Date szEndDate) {
		this.szStockCourseTypeId = szStockCourseTypeId;
		this.TSistockItem = TSistockItem;
		this.TCtcourseType = TCtcourseType;
		this.szOptionBl = szOptionBl;
		this.szRequiredBl = szRequiredBl;
		this.szSundayBl = szSundayBl;
		this.szMondayBl = szMondayBl;
		this.szTuesdayBl = szTuesdayBl;
		this.szWednesdayBl = szWednesdayBl;
		this.szThursdayBl = szThursdayBl;
		this.szFridayBl = szFridayBl;
		this.szSaturdayBl = szSaturdayBl;
		this.szStartDate = szStartDate;
		this.szEndDate = szEndDate;
	}

	@Id

	@Column(name = "SzStockCourseTypeID", unique = true, nullable = false)
	public int getSzStockCourseTypeId() {
		return this.szStockCourseTypeId;
	}

	public void setSzStockCourseTypeId(int szStockCourseTypeId) {
		this.szStockCourseTypeId = szStockCourseTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SzStockItemID", unique = true, nullable = false)
	public TSistockItem getTSistockItem() {
		return this.TSistockItem;
	}

	public void setTSistockItem(TSistockItem TSistockItem) {
		this.TSistockItem = TSistockItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SzCourseTypeID", nullable = false)
	public TCtcourseType getTCtcourseType() {
		return this.TCtcourseType;
	}

	public void setTCtcourseType(TCtcourseType TCtcourseType) {
		this.TCtcourseType = TCtcourseType;
	}

	@Column(name = "SzOptionBl", nullable = false)
	public boolean isSzOptionBl() {
		return this.szOptionBl;
	}

	public void setSzOptionBl(boolean szOptionBl) {
		this.szOptionBl = szOptionBl;
	}

	@Column(name = "SzRequiredBl", nullable = false)
	public boolean isSzRequiredBl() {
		return this.szRequiredBl;
	}

	public void setSzRequiredBl(boolean szRequiredBl) {
		this.szRequiredBl = szRequiredBl;
	}

	@Column(name = "SzSundayBl", nullable = false)
	public boolean isSzSundayBl() {
		return this.szSundayBl;
	}

	public void setSzSundayBl(boolean szSundayBl) {
		this.szSundayBl = szSundayBl;
	}

	@Column(name = "SzMondayBl", nullable = false)
	public boolean isSzMondayBl() {
		return this.szMondayBl;
	}

	public void setSzMondayBl(boolean szMondayBl) {
		this.szMondayBl = szMondayBl;
	}

	@Column(name = "SzTuesdayBl", nullable = false)
	public boolean isSzTuesdayBl() {
		return this.szTuesdayBl;
	}

	public void setSzTuesdayBl(boolean szTuesdayBl) {
		this.szTuesdayBl = szTuesdayBl;
	}

	@Column(name = "SzWednesdayBl", nullable = false)
	public boolean isSzWednesdayBl() {
		return this.szWednesdayBl;
	}

	public void setSzWednesdayBl(boolean szWednesdayBl) {
		this.szWednesdayBl = szWednesdayBl;
	}

	@Column(name = "SzThursdayBl", nullable = false)
	public boolean isSzThursdayBl() {
		return this.szThursdayBl;
	}

	public void setSzThursdayBl(boolean szThursdayBl) {
		this.szThursdayBl = szThursdayBl;
	}

	@Column(name = "SzFridayBl", nullable = false)
	public boolean isSzFridayBl() {
		return this.szFridayBl;
	}

	public void setSzFridayBl(boolean szFridayBl) {
		this.szFridayBl = szFridayBl;
	}

	@Column(name = "SzSaturdayBl", nullable = false)
	public boolean isSzSaturdayBl() {
		return this.szSaturdayBl;
	}

	public void setSzSaturdayBl(boolean szSaturdayBl) {
		this.szSaturdayBl = szSaturdayBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SzStartDate", nullable = false, length = 23)
	public Date getSzStartDate() {
		return this.szStartDate;
	}

	public void setSzStartDate(Date szStartDate) {
		this.szStartDate = szStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SzEndDate", nullable = false, length = 23)
	public Date getSzEndDate() {
		return this.szEndDate;
	}

	public void setSzEndDate(Date szEndDate) {
		this.szEndDate = szEndDate;
	}

}
