package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TT1tip generated by hbm2java
 */
@Entity
@Table(name = "T_T1Tip", uniqueConstraints = @UniqueConstraint(columnNames = "T1TipTx"))
public class TT1tip implements java.io.Serializable {

	private int t1tipId;
	private String t1tipTx;

	public TT1tip() {
	}

	public TT1tip(int t1tipId) {
		this.t1tipId = t1tipId;
	}

	public TT1tip(int t1tipId, String t1tipTx) {
		this.t1tipId = t1tipId;
		this.t1tipTx = t1tipTx;
	}

	@Id

	@Column(name = "T1TipID", unique = true, nullable = false)
	public int getT1tipId() {
		return this.t1tipId;
	}

	public void setT1tipId(int t1tipId) {
		this.t1tipId = t1tipId;
	}

	@Column(name = "T1TipTx", unique = true)
	public String getT1tipTx() {
		return this.t1tipTx;
	}

	public void setT1tipTx(String t1tipTx) {
		this.t1tipTx = t1tipTx;
	}

}
