package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TT2tripExpense generated by hbm2java
 */
@Entity
@Table(name = "T_T2TripExpense")
public class TT2tripExpense implements java.io.Serializable {

	private int t2tripExpenseId;
	private int t2tripId;
	private int t2stockItemId;
	private double t2amountMn;
	private double t2taxMn;
	private String t2taxBandIdsTx;
	private String t2taxRatesTx;
	private Date t2expenseDate;
	private Date t2lastUpdatedDate;
	private Integer t2invoiceIdN;
	private Integer t2empIdN;
	private Date t2creationDate;
	private String t2notesTxN;
	private Integer t2empTripIdN;

	public TT2tripExpense() {
	}

	public TT2tripExpense(int t2tripExpenseId, int t2tripId, int t2stockItemId, double t2amountMn, double t2taxMn,
			String t2taxBandIdsTx, String t2taxRatesTx, Date t2expenseDate, Date t2lastUpdatedDate,
			Date t2creationDate) {
		this.t2tripExpenseId = t2tripExpenseId;
		this.t2tripId = t2tripId;
		this.t2stockItemId = t2stockItemId;
		this.t2amountMn = t2amountMn;
		this.t2taxMn = t2taxMn;
		this.t2taxBandIdsTx = t2taxBandIdsTx;
		this.t2taxRatesTx = t2taxRatesTx;
		this.t2expenseDate = t2expenseDate;
		this.t2lastUpdatedDate = t2lastUpdatedDate;
		this.t2creationDate = t2creationDate;
	}

	public TT2tripExpense(int t2tripExpenseId, int t2tripId, int t2stockItemId, double t2amountMn, double t2taxMn,
			String t2taxBandIdsTx, String t2taxRatesTx, Date t2expenseDate, Date t2lastUpdatedDate,
			Integer t2invoiceIdN, Integer t2empIdN, Date t2creationDate, String t2notesTxN,
			Integer t2empTripIdN) {
		this.t2tripExpenseId = t2tripExpenseId;
		this.t2tripId = t2tripId;
		this.t2stockItemId = t2stockItemId;
		this.t2amountMn = t2amountMn;
		this.t2taxMn = t2taxMn;
		this.t2taxBandIdsTx = t2taxBandIdsTx;
		this.t2taxRatesTx = t2taxRatesTx;
		this.t2expenseDate = t2expenseDate;
		this.t2lastUpdatedDate = t2lastUpdatedDate;
		this.t2invoiceIdN = t2invoiceIdN;
		this.t2empIdN = t2empIdN;
		this.t2creationDate = t2creationDate;
		this.t2notesTxN = t2notesTxN;
		this.t2empTripIdN = t2empTripIdN;
	}

	@Id

	@Column(name = "T2TripExpenseID", unique = true, nullable = false)
	public int getT2tripExpenseId() {
		return this.t2tripExpenseId;
	}

	public void setT2tripExpenseId(int t2tripExpenseId) {
		this.t2tripExpenseId = t2tripExpenseId;
	}

	@Column(name = "T2TripID", nullable = false)
	public int getT2tripId() {
		return this.t2tripId;
	}

	public void setT2tripId(int t2tripId) {
		this.t2tripId = t2tripId;
	}

	@Column(name = "T2StockItemID", nullable = false)
	public int getT2stockItemId() {
		return this.t2stockItemId;
	}

	public void setT2stockItemId(int t2stockItemId) {
		this.t2stockItemId = t2stockItemId;
	}

	@Column(name = "T2AmountMn", nullable = false, precision = 53, scale = 0)
	public double getT2amountMn() {
		return this.t2amountMn;
	}

	public void setT2amountMn(double t2amountMn) {
		this.t2amountMn = t2amountMn;
	}

	@Column(name = "T2TaxMn", nullable = false, precision = 53, scale = 0)
	public double getT2taxMn() {
		return this.t2taxMn;
	}

	public void setT2taxMn(double t2taxMn) {
		this.t2taxMn = t2taxMn;
	}

	@Column(name = "T2TaxBandIDsTx", nullable = false)
	public String getT2taxBandIdsTx() {
		return this.t2taxBandIdsTx;
	}

	public void setT2taxBandIdsTx(String t2taxBandIdsTx) {
		this.t2taxBandIdsTx = t2taxBandIdsTx;
	}

	@Column(name = "T2TaxRatesTx", nullable = false)
	public String getT2taxRatesTx() {
		return this.t2taxRatesTx;
	}

	public void setT2taxRatesTx(String t2taxRatesTx) {
		this.t2taxRatesTx = t2taxRatesTx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "T2ExpenseDate", nullable = false, length = 23)
	public Date getT2expenseDate() {
		return this.t2expenseDate;
	}

	public void setT2expenseDate(Date t2expenseDate) {
		this.t2expenseDate = t2expenseDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "T2LastUpdatedDate", nullable = false, length = 23)
	public Date getT2lastUpdatedDate() {
		return this.t2lastUpdatedDate;
	}

	public void setT2lastUpdatedDate(Date t2lastUpdatedDate) {
		this.t2lastUpdatedDate = t2lastUpdatedDate;
	}

	@Column(name = "T2InvoiceID_N")
	public Integer getT2invoiceIdN() {
		return this.t2invoiceIdN;
	}

	public void setT2invoiceIdN(Integer t2invoiceIdN) {
		this.t2invoiceIdN = t2invoiceIdN;
	}

	@Column(name = "T2EmpID_N")
	public Integer getT2empIdN() {
		return this.t2empIdN;
	}

	public void setT2empIdN(Integer t2empIdN) {
		this.t2empIdN = t2empIdN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "T2CreationDate", nullable = false, length = 23)
	public Date getT2creationDate() {
		return this.t2creationDate;
	}

	public void setT2creationDate(Date t2creationDate) {
		this.t2creationDate = t2creationDate;
	}

	@Column(name = "T2NotesTx_N")
	public String getT2notesTxN() {
		return this.t2notesTxN;
	}

	public void setT2notesTxN(String t2notesTxN) {
		this.t2notesTxN = t2notesTxN;
	}

	@Column(name = "T2EmpTripID_N")
	public Integer getT2empTripIdN() {
		return this.t2empTripIdN;
	}

	public void setT2empTripIdN(Integer t2empTripIdN) {
		this.t2empTripIdN = t2empTripIdN;
	}

}
