package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TTaTaxBandRelations generated by hbm2java
 */
@Entity
@Table(name = "T_TaTaxBandRelations")
public class TTaTaxBandRelations implements java.io.Serializable {

	private TTaTaxBandRelationsId id;

	public TTaTaxBandRelations() {
	}

	public TTaTaxBandRelations(TTaTaxBandRelationsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "taParentTaxBandId", column = @Column(name = "TaParentTaxBandID", nullable = false)),
			@AttributeOverride(name = "taChildTaxBandId", column = @Column(name = "TaChildTaxBandID", nullable = false)) })
	public TTaTaxBandRelationsId getId() {
		return this.id;
	}

	public void setId(TTaTaxBandRelationsId id) {
		this.id = id;
	}

}
