package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TTdTicketPc generated by hbm2java
 */
@Entity
@Table(name = "T_TdTicketPC")
public class TTdTicketPc implements java.io.Serializable {

	private TTdTicketPcId id;
	private String tdEntryIdtx;

	public TTdTicketPc() {
	}

	public TTdTicketPc(TTdTicketPcId id, String tdEntryIdtx) {
		this.id = id;
		this.tdEntryIdtx = tdEntryIdtx;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tdTicketId", column = @Column(name = "TdTicketID", nullable = false)),
			@AttributeOverride(name = "tdPcid", column = @Column(name = "TdPCID", nullable = false)) })
	public TTdTicketPcId getId() {
		return this.id;
	}

	public void setId(TTdTicketPcId id) {
		this.id = id;
	}

	@Column(name = "TdEntryIDTx", nullable = false)
	public String getTdEntryIdtx() {
		return this.tdEntryIdtx;
	}

	public void setTdEntryIdtx(String tdEntryIdtx) {
		this.tdEntryIdtx = tdEntryIdtx;
	}

}
