package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TTjTripStatus generated by hbm2java
 */
@Entity
@Table(name = "T_TjTripStatus", uniqueConstraints = @UniqueConstraint(columnNames = "TjTripStatusTx"))
public class TTjTripStatus implements java.io.Serializable {

	private int tjTripStatusId;
	private String tjTripStatusTx;
	private Date tjCreationDate;
	private Date tjLastUpdatedDate;
	private boolean tjUnavailableBl;
	private boolean tjRequiredBl;
	private Set<TTpTrip> TTpTrips = new HashSet<TTpTrip>(0);

	public TTjTripStatus() {
	}

	public TTjTripStatus(int tjTripStatusId, String tjTripStatusTx, Date tjCreationDate, Date tjLastUpdatedDate,
			boolean tjUnavailableBl, boolean tjRequiredBl) {
		this.tjTripStatusId = tjTripStatusId;
		this.tjTripStatusTx = tjTripStatusTx;
		this.tjCreationDate = tjCreationDate;
		this.tjLastUpdatedDate = tjLastUpdatedDate;
		this.tjUnavailableBl = tjUnavailableBl;
		this.tjRequiredBl = tjRequiredBl;
	}

	public TTjTripStatus(int tjTripStatusId, String tjTripStatusTx, Date tjCreationDate, Date tjLastUpdatedDate,
			boolean tjUnavailableBl, boolean tjRequiredBl, Set<TTpTrip> TTpTrips) {
		this.tjTripStatusId = tjTripStatusId;
		this.tjTripStatusTx = tjTripStatusTx;
		this.tjCreationDate = tjCreationDate;
		this.tjLastUpdatedDate = tjLastUpdatedDate;
		this.tjUnavailableBl = tjUnavailableBl;
		this.tjRequiredBl = tjRequiredBl;
		this.TTpTrips = TTpTrips;
	}

	@Id

	@Column(name = "TjTripStatusID", unique = true, nullable = false)
	public int getTjTripStatusId() {
		return this.tjTripStatusId;
	}

	public void setTjTripStatusId(int tjTripStatusId) {
		this.tjTripStatusId = tjTripStatusId;
	}

	@Column(name = "TjTripStatusTx", unique = true, nullable = false)
	public String getTjTripStatusTx() {
		return this.tjTripStatusTx;
	}

	public void setTjTripStatusTx(String tjTripStatusTx) {
		this.tjTripStatusTx = tjTripStatusTx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TjCreationDate", nullable = false, length = 23)
	public Date getTjCreationDate() {
		return this.tjCreationDate;
	}

	public void setTjCreationDate(Date tjCreationDate) {
		this.tjCreationDate = tjCreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TjLastUpdatedDate", nullable = false, length = 23)
	public Date getTjLastUpdatedDate() {
		return this.tjLastUpdatedDate;
	}

	public void setTjLastUpdatedDate(Date tjLastUpdatedDate) {
		this.tjLastUpdatedDate = tjLastUpdatedDate;
	}

	@Column(name = "TjUnavailableBl", nullable = false)
	public boolean isTjUnavailableBl() {
		return this.tjUnavailableBl;
	}

	public void setTjUnavailableBl(boolean tjUnavailableBl) {
		this.tjUnavailableBl = tjUnavailableBl;
	}

	@Column(name = "TjRequiredBl", nullable = false)
	public boolean isTjRequiredBl() {
		return this.tjRequiredBl;
	}

	public void setTjRequiredBl(boolean tjRequiredBl) {
		this.tjRequiredBl = tjRequiredBl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTjTripStatus")
	public Set<TTpTrip> getTTpTrips() {
		return this.TTpTrips;
	}

	public void setTTpTrips(Set<TTpTrip> TTpTrips) {
		this.TTpTrips = TTpTrips;
	}

}
