package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TTnTranslation generated by hbm2java
 */
@Entity
@Table(name = "T_TnTranslation", uniqueConstraints = @UniqueConstraint(columnNames = { "TnFormNameTx", "TnLanguageID",
		"TnLabelNameTx" }))
public class TTnTranslation implements java.io.Serializable {

	private int tnTranslationId;
	private String tnFormNameTx;
	private int tnLanguageId;
	private String tnLabelNameTx;
	private String tnTextTx;

	public TTnTranslation() {
	}

	public TTnTranslation(int tnTranslationId, String tnFormNameTx, int tnLanguageId, String tnLabelNameTx,
			String tnTextTx) {
		this.tnTranslationId = tnTranslationId;
		this.tnFormNameTx = tnFormNameTx;
		this.tnLanguageId = tnLanguageId;
		this.tnLabelNameTx = tnLabelNameTx;
		this.tnTextTx = tnTextTx;
	}

	@Id

	@Column(name = "TnTranslationID", unique = true, nullable = false)
	public int getTnTranslationId() {
		return this.tnTranslationId;
	}

	public void setTnTranslationId(int tnTranslationId) {
		this.tnTranslationId = tnTranslationId;
	}

	@Column(name = "TnFormNameTx", nullable = false)
	public String getTnFormNameTx() {
		return this.tnFormNameTx;
	}

	public void setTnFormNameTx(String tnFormNameTx) {
		this.tnFormNameTx = tnFormNameTx;
	}

	@Column(name = "TnLanguageID", nullable = false)
	public int getTnLanguageId() {
		return this.tnLanguageId;
	}

	public void setTnLanguageId(int tnLanguageId) {
		this.tnLanguageId = tnLanguageId;
	}

	@Column(name = "TnLabelNameTx", nullable = false)
	public String getTnLabelNameTx() {
		return this.tnLabelNameTx;
	}

	public void setTnLabelNameTx(String tnLabelNameTx) {
		this.tnLabelNameTx = tnLabelNameTx;
	}

	@Column(name = "TnTextTx", nullable = false)
	public String getTnTextTx() {
		return this.tnTextTx;
	}

	public void setTnTextTx(String tnTextTx) {
		this.tnTextTx = tnTextTx;
	}

}
