package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TTstransStatus generated by hbm2java
 */
@Entity
@Table(name = "T_TSTransStatus", uniqueConstraints = @UniqueConstraint(columnNames = "TSTransStatusTx"))
public class TTstransStatus implements java.io.Serializable {

	private int tstransStatusId;
	private String tstransStatusTx;
	private boolean tsinvoiceBl;
	private boolean tsquoteBl;
	private boolean tsgiftCertBl;
	private boolean tsvoucherBl;
	private boolean tsrentalBookingBl;
	private boolean tsserviceBookingBl;
	private boolean tsunavailableBl;
	private Set<TRbrentalBooking> TRbrentalBookings = new HashSet<TRbrentalBooking>(0);
	private Set<TQuQuote> TQuQuotes = new HashSet<TQuQuote>(0);
	private Set<TTrTransfer> TTrTransfers = new HashSet<TTrTransfer>(0);
	private Set<TVoVoucher> TVoVouchers = new HashSet<TVoVoucher>(0);
	private Set<TInInvoice> TInInvoices = new HashSet<TInInvoice>(0);
	private Set<TGcgiftCert> TGcgiftCerts = new HashSet<TGcgiftCert>(0);
	private Set<TGdGiftCard> TGdGiftCards = new HashSet<TGdGiftCard>(0);
	private Set<TSbserviceBooking> TSbserviceBookings = new HashSet<TSbserviceBooking>(0);

	public TTstransStatus() {
	}

	public TTstransStatus(int tstransStatusId, String tstransStatusTx, boolean tsinvoiceBl, boolean tsquoteBl,
			boolean tsgiftCertBl, boolean tsvoucherBl, boolean tsrentalBookingBl, boolean tsserviceBookingBl,
			boolean tsunavailableBl) {
		this.tstransStatusId = tstransStatusId;
		this.tstransStatusTx = tstransStatusTx;
		this.tsinvoiceBl = tsinvoiceBl;
		this.tsquoteBl = tsquoteBl;
		this.tsgiftCertBl = tsgiftCertBl;
		this.tsvoucherBl = tsvoucherBl;
		this.tsrentalBookingBl = tsrentalBookingBl;
		this.tsserviceBookingBl = tsserviceBookingBl;
		this.tsunavailableBl = tsunavailableBl;
	}

	public TTstransStatus(int tstransStatusId, String tstransStatusTx, boolean tsinvoiceBl, boolean tsquoteBl,
			boolean tsgiftCertBl, boolean tsvoucherBl, boolean tsrentalBookingBl, boolean tsserviceBookingBl,
			boolean tsunavailableBl, Set<TRbrentalBooking> TRbrentalBookings, Set<TQuQuote> TQuQuotes,
			Set<TTrTransfer> TTrTransfers, Set<TVoVoucher> TVoVouchers, Set<TInInvoice> TInInvoices,
			Set<TGcgiftCert> TGcgiftCerts, Set<TGdGiftCard> TGdGiftCards, Set<TSbserviceBooking> TSbserviceBookings) {
		this.tstransStatusId = tstransStatusId;
		this.tstransStatusTx = tstransStatusTx;
		this.tsinvoiceBl = tsinvoiceBl;
		this.tsquoteBl = tsquoteBl;
		this.tsgiftCertBl = tsgiftCertBl;
		this.tsvoucherBl = tsvoucherBl;
		this.tsrentalBookingBl = tsrentalBookingBl;
		this.tsserviceBookingBl = tsserviceBookingBl;
		this.tsunavailableBl = tsunavailableBl;
		this.TRbrentalBookings = TRbrentalBookings;
		this.TQuQuotes = TQuQuotes;
		this.TTrTransfers = TTrTransfers;
		this.TVoVouchers = TVoVouchers;
		this.TInInvoices = TInInvoices;
		this.TGcgiftCerts = TGcgiftCerts;
		this.TGdGiftCards = TGdGiftCards;
		this.TSbserviceBookings = TSbserviceBookings;
	}

	@Id

	@Column(name = "TSTransStatusID", unique = true, nullable = false)
	public int getTstransStatusId() {
		return this.tstransStatusId;
	}

	public void setTstransStatusId(int tstransStatusId) {
		this.tstransStatusId = tstransStatusId;
	}

	@Column(name = "TSTransStatusTx", unique = true, nullable = false)
	public String getTstransStatusTx() {
		return this.tstransStatusTx;
	}

	public void setTstransStatusTx(String tstransStatusTx) {
		this.tstransStatusTx = tstransStatusTx;
	}

	@Column(name = "TSInvoiceBl", nullable = false)
	public boolean isTsinvoiceBl() {
		return this.tsinvoiceBl;
	}

	public void setTsinvoiceBl(boolean tsinvoiceBl) {
		this.tsinvoiceBl = tsinvoiceBl;
	}

	@Column(name = "TSQuoteBl", nullable = false)
	public boolean isTsquoteBl() {
		return this.tsquoteBl;
	}

	public void setTsquoteBl(boolean tsquoteBl) {
		this.tsquoteBl = tsquoteBl;
	}

	@Column(name = "TSGiftCertBl", nullable = false)
	public boolean isTsgiftCertBl() {
		return this.tsgiftCertBl;
	}

	public void setTsgiftCertBl(boolean tsgiftCertBl) {
		this.tsgiftCertBl = tsgiftCertBl;
	}

	@Column(name = "TSVoucherBl", nullable = false)
	public boolean isTsvoucherBl() {
		return this.tsvoucherBl;
	}

	public void setTsvoucherBl(boolean tsvoucherBl) {
		this.tsvoucherBl = tsvoucherBl;
	}

	@Column(name = "TSRentalBookingBl", nullable = false)
	public boolean isTsrentalBookingBl() {
		return this.tsrentalBookingBl;
	}

	public void setTsrentalBookingBl(boolean tsrentalBookingBl) {
		this.tsrentalBookingBl = tsrentalBookingBl;
	}

	@Column(name = "TSServiceBookingBl", nullable = false)
	public boolean isTsserviceBookingBl() {
		return this.tsserviceBookingBl;
	}

	public void setTsserviceBookingBl(boolean tsserviceBookingBl) {
		this.tsserviceBookingBl = tsserviceBookingBl;
	}

	@Column(name = "TSUnavailableBl", nullable = false)
	public boolean isTsunavailableBl() {
		return this.tsunavailableBl;
	}

	public void setTsunavailableBl(boolean tsunavailableBl) {
		this.tsunavailableBl = tsunavailableBl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTstransStatus")
	public Set<TRbrentalBooking> getTRbrentalBookings() {
		return this.TRbrentalBookings;
	}

	public void setTRbrentalBookings(Set<TRbrentalBooking> TRbrentalBookings) {
		this.TRbrentalBookings = TRbrentalBookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTstransStatus")
	public Set<TQuQuote> getTQuQuotes() {
		return this.TQuQuotes;
	}

	public void setTQuQuotes(Set<TQuQuote> TQuQuotes) {
		this.TQuQuotes = TQuQuotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTstransStatus")
	public Set<TTrTransfer> getTTrTransfers() {
		return this.TTrTransfers;
	}

	public void setTTrTransfers(Set<TTrTransfer> TTrTransfers) {
		this.TTrTransfers = TTrTransfers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTstransStatus")
	public Set<TVoVoucher> getTVoVouchers() {
		return this.TVoVouchers;
	}

	public void setTVoVouchers(Set<TVoVoucher> TVoVouchers) {
		this.TVoVouchers = TVoVouchers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTstransStatus")
	public Set<TInInvoice> getTInInvoices() {
		return this.TInInvoices;
	}

	public void setTInInvoices(Set<TInInvoice> TInInvoices) {
		this.TInInvoices = TInInvoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTstransStatus")
	public Set<TGcgiftCert> getTGcgiftCerts() {
		return this.TGcgiftCerts;
	}

	public void setTGcgiftCerts(Set<TGcgiftCert> TGcgiftCerts) {
		this.TGcgiftCerts = TGcgiftCerts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTstransStatus")
	public Set<TGdGiftCard> getTGdGiftCards() {
		return this.TGdGiftCards;
	}

	public void setTGdGiftCards(Set<TGdGiftCard> TGdGiftCards) {
		this.TGdGiftCards = TGdGiftCards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTstransStatus")
	public Set<TSbserviceBooking> getTSbserviceBookings() {
		return this.TSbserviceBookings;
	}

	public void setTSbserviceBookings(Set<TSbserviceBooking> TSbserviceBookings) {
		this.TSbserviceBookings = TSbserviceBookings;
	}

}
