package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TUiconfig generated by hbm2java
 */
@Entity
@Table(name = "T_UIConfig", uniqueConstraints = @UniqueConstraint(columnNames = "UIConfigTx"))
public class TUiconfig implements java.io.Serializable {

	private int uiconfigId;
	private String uiconfigTx;
	private boolean uiunavailableBl;
	private Date uicreationDate;
	private Date uilastUpdatedDate;
	private boolean uitoolbarModulesBl;
	private boolean uitoolbarCoolbarBl;
	private boolean uitoolbarBtnBarBl;
	private boolean uitoolbarStatusBarBl;
	private boolean uitoolbarDetailWndBl;
	private boolean uitoolbarBtnArrayBl;
	private boolean uirequiredBl;
	private boolean uidefaultBl;
	private boolean uitoolbarHierarchyBl;
	private boolean uitoolbarFloaterBl;
	private boolean uifileMenuVisBl;
	private boolean uieditMenuVisBl;
	private boolean uiviewMenuVisBl;
	private boolean uitoolsMenuVisBl;
	private boolean uipadimenuVisBl;
	private boolean uihelpMenuVisBl;
	private boolean uifileNewBl;
	private boolean uifileOpenBl;
	private boolean uifileRecentRecsBl;
	private boolean uifilePrintBl;
	private boolean uifileLine1bl;
	private boolean uifileImportBl;
	private boolean uifileLine2bl;
	private boolean uifileSodtasksBl;
	private boolean uifileEoltasksBl;
	private boolean uifileLine3bl;
	private boolean uifileReportsBl;
	private boolean uifileReportGroupsBl;
	private boolean uifileWizardsBl;
	private boolean uifileLine4bl;
	private boolean uifileRenewBl;
	private boolean uifileLine5bl;
	private boolean uifileSwitchUserBl;
	private boolean uifileLockSystemBl;
	private boolean uifileClockOnBl;
	private boolean uifileClockOffBl;
	private boolean uifileLine6bl;
	private boolean uifileSwitchDbbl;
	private boolean uifileReconnectBl;
	private boolean uifileExitBl;
	private boolean uieditSelectAllBl;
	private boolean uieditLine1bl;
	private boolean uieditFindBl;
	private boolean uieditLine2bl;
	private boolean uieditCopyBl;
	private boolean uieditPasteBl;
	private boolean uieditDeleteBl;
	private boolean uiviewTilesBl;
	private boolean uiviewIconsBl;
	private boolean uiviewListBl;
	private boolean uiviewDetailsBl;
	private boolean uiviewLine1bl;
	private boolean uiviewCalendarBl;
	private boolean uiviewSeatPlanBl;
	private boolean uiviewRoomAvailBl;
	private boolean uiviewAuditLogBl;
	private boolean uiviewRemindersBl;
	private boolean uiviewDesktopBl;
	private boolean uiviewLine2bl;
	private boolean uiviewToolbarsBl;
	private boolean uiviewUisBl;
	private boolean uiviewRefreshBl;
	private boolean uitoolsLabelsBl;
	private boolean uitoolsPrintLayoutsBl;
	private boolean uitoolsWordTempsBl;
	private boolean uitoolsLine1bl;
	private boolean uitoolsQbbl;
	private boolean uitoolsLine2bl;
	private boolean uitoolsCalcsBl;
	private boolean uitoolsRawDataBl;
	private boolean uitoolsRefreshLooksBl;
	private boolean uitoolsAutoEmailBl;
	private boolean uitoolsOptionsBl;
	private boolean uitoolsEvefoldersBl;
	private boolean uipadiaddLinkBl;
	private boolean uipadiorganizeBl;
	private boolean uihelpManualWordBl;
	private boolean uihelpManualPdfbl;
	private boolean uihelpLine1bl;
	private boolean uihelpSkypeUsbl;
	private boolean uihelpSkypeUkbl;
	private boolean uihelpWebsiteBl;
	private boolean uihelpAboutBl;
	private boolean uibtnUpAlevelBl;
	private boolean uibtnRefreshBl;
	private boolean uibtnHomeBl;
	private boolean uibtnCalendarBl;
	private boolean uibtnDesktopBl;
	private boolean uibtnLinksBl;
	private boolean uisearchLargeGraphicBl;
	private int uitoolbarBtnWidthIn;
	private int uitoolbarBtnHeightIn;
	private float uilistFontSizeFl;
	private float uilistViewFontSizeFl;
	private boolean uibuttonPicklistBl;
	private int uiarrayBtnHeightIn;
	private float uiarrayBtnFontSizeFl;
	private int uicoolbarBtnHeightIn;
	private int uigridRowHeightIn;
	private boolean uidblClickRequiredBl;
	private boolean uilvlargeIconsBl;
	private int uiarrayBtnNewWidthIn;
	private int uiarrayBtnFindWidthIn;
	private int uicoolbarHeaderHeightIn;
	private boolean uishowBreadcrumbsBl;
	private int uimoduleButtonWidthIn;
	private int uimoduleButtonHeightIn;
	private int uimoduleBtnXseparationIn;
	private int uimoduleBtnYseparationIn;
	private int uiarrayBtnXseparationIn;
	private int uiarrayBtnYseparationIn;
	private boolean uifancyModuleBtnBl;
	private boolean uibtnEventPlannerBl;
	private Set<TPcpc> TPcpcs = new HashSet<TPcpc>(0);
	private Set<TUnuiconfigNode> TUnuiconfigNodes = new HashSet<TUnuiconfigNode>(0);

	public TUiconfig() {
	}

	public TUiconfig(int uiconfigId, String uiconfigTx, boolean uiunavailableBl, Date uicreationDate,
			Date uilastUpdatedDate, boolean uitoolbarModulesBl, boolean uitoolbarCoolbarBl, boolean uitoolbarBtnBarBl,
			boolean uitoolbarStatusBarBl, boolean uitoolbarDetailWndBl, boolean uitoolbarBtnArrayBl,
			boolean uirequiredBl, boolean uidefaultBl, boolean uitoolbarHierarchyBl, boolean uitoolbarFloaterBl,
			boolean uifileMenuVisBl, boolean uieditMenuVisBl, boolean uiviewMenuVisBl, boolean uitoolsMenuVisBl,
			boolean uipadimenuVisBl, boolean uihelpMenuVisBl, boolean uifileNewBl, boolean uifileOpenBl,
			boolean uifileRecentRecsBl, boolean uifilePrintBl, boolean uifileLine1bl, boolean uifileImportBl,
			boolean uifileLine2bl, boolean uifileSodtasksBl, boolean uifileEoltasksBl, boolean uifileLine3bl,
			boolean uifileReportsBl, boolean uifileReportGroupsBl, boolean uifileWizardsBl, boolean uifileLine4bl,
			boolean uifileRenewBl, boolean uifileLine5bl, boolean uifileSwitchUserBl, boolean uifileLockSystemBl,
			boolean uifileClockOnBl, boolean uifileClockOffBl, boolean uifileLine6bl, boolean uifileSwitchDbbl,
			boolean uifileReconnectBl, boolean uifileExitBl, boolean uieditSelectAllBl, boolean uieditLine1bl,
			boolean uieditFindBl, boolean uieditLine2bl, boolean uieditCopyBl, boolean uieditPasteBl,
			boolean uieditDeleteBl, boolean uiviewTilesBl, boolean uiviewIconsBl, boolean uiviewListBl,
			boolean uiviewDetailsBl, boolean uiviewLine1bl, boolean uiviewCalendarBl, boolean uiviewSeatPlanBl,
			boolean uiviewRoomAvailBl, boolean uiviewAuditLogBl, boolean uiviewRemindersBl, boolean uiviewDesktopBl,
			boolean uiviewLine2bl, boolean uiviewToolbarsBl, boolean uiviewUisBl, boolean uiviewRefreshBl,
			boolean uitoolsLabelsBl, boolean uitoolsPrintLayoutsBl, boolean uitoolsWordTempsBl, boolean uitoolsLine1bl,
			boolean uitoolsQbbl, boolean uitoolsLine2bl, boolean uitoolsCalcsBl, boolean uitoolsRawDataBl,
			boolean uitoolsRefreshLooksBl, boolean uitoolsAutoEmailBl, boolean uitoolsOptionsBl,
			boolean uitoolsEvefoldersBl, boolean uipadiaddLinkBl, boolean uipadiorganizeBl, boolean uihelpManualWordBl,
			boolean uihelpManualPdfbl, boolean uihelpLine1bl, boolean uihelpSkypeUsbl, boolean uihelpSkypeUkbl,
			boolean uihelpWebsiteBl, boolean uihelpAboutBl, boolean uibtnUpAlevelBl, boolean uibtnRefreshBl,
			boolean uibtnHomeBl, boolean uibtnCalendarBl, boolean uibtnDesktopBl, boolean uibtnLinksBl,
			boolean uisearchLargeGraphicBl, int uitoolbarBtnWidthIn, int uitoolbarBtnHeightIn, float uilistFontSizeFl,
			float uilistViewFontSizeFl, boolean uibuttonPicklistBl, int uiarrayBtnHeightIn, float uiarrayBtnFontSizeFl,
			int uicoolbarBtnHeightIn, int uigridRowHeightIn, boolean uidblClickRequiredBl, boolean uilvlargeIconsBl,
			int uiarrayBtnNewWidthIn, int uiarrayBtnFindWidthIn, int uicoolbarHeaderHeightIn,
			boolean uishowBreadcrumbsBl, int uimoduleButtonWidthIn, int uimoduleButtonHeightIn,
			int uimoduleBtnXseparationIn, int uimoduleBtnYseparationIn, int uiarrayBtnXseparationIn,
			int uiarrayBtnYseparationIn, boolean uifancyModuleBtnBl, boolean uibtnEventPlannerBl) {
		this.uiconfigId = uiconfigId;
		this.uiconfigTx = uiconfigTx;
		this.uiunavailableBl = uiunavailableBl;
		this.uicreationDate = uicreationDate;
		this.uilastUpdatedDate = uilastUpdatedDate;
		this.uitoolbarModulesBl = uitoolbarModulesBl;
		this.uitoolbarCoolbarBl = uitoolbarCoolbarBl;
		this.uitoolbarBtnBarBl = uitoolbarBtnBarBl;
		this.uitoolbarStatusBarBl = uitoolbarStatusBarBl;
		this.uitoolbarDetailWndBl = uitoolbarDetailWndBl;
		this.uitoolbarBtnArrayBl = uitoolbarBtnArrayBl;
		this.uirequiredBl = uirequiredBl;
		this.uidefaultBl = uidefaultBl;
		this.uitoolbarHierarchyBl = uitoolbarHierarchyBl;
		this.uitoolbarFloaterBl = uitoolbarFloaterBl;
		this.uifileMenuVisBl = uifileMenuVisBl;
		this.uieditMenuVisBl = uieditMenuVisBl;
		this.uiviewMenuVisBl = uiviewMenuVisBl;
		this.uitoolsMenuVisBl = uitoolsMenuVisBl;
		this.uipadimenuVisBl = uipadimenuVisBl;
		this.uihelpMenuVisBl = uihelpMenuVisBl;
		this.uifileNewBl = uifileNewBl;
		this.uifileOpenBl = uifileOpenBl;
		this.uifileRecentRecsBl = uifileRecentRecsBl;
		this.uifilePrintBl = uifilePrintBl;
		this.uifileLine1bl = uifileLine1bl;
		this.uifileImportBl = uifileImportBl;
		this.uifileLine2bl = uifileLine2bl;
		this.uifileSodtasksBl = uifileSodtasksBl;
		this.uifileEoltasksBl = uifileEoltasksBl;
		this.uifileLine3bl = uifileLine3bl;
		this.uifileReportsBl = uifileReportsBl;
		this.uifileReportGroupsBl = uifileReportGroupsBl;
		this.uifileWizardsBl = uifileWizardsBl;
		this.uifileLine4bl = uifileLine4bl;
		this.uifileRenewBl = uifileRenewBl;
		this.uifileLine5bl = uifileLine5bl;
		this.uifileSwitchUserBl = uifileSwitchUserBl;
		this.uifileLockSystemBl = uifileLockSystemBl;
		this.uifileClockOnBl = uifileClockOnBl;
		this.uifileClockOffBl = uifileClockOffBl;
		this.uifileLine6bl = uifileLine6bl;
		this.uifileSwitchDbbl = uifileSwitchDbbl;
		this.uifileReconnectBl = uifileReconnectBl;
		this.uifileExitBl = uifileExitBl;
		this.uieditSelectAllBl = uieditSelectAllBl;
		this.uieditLine1bl = uieditLine1bl;
		this.uieditFindBl = uieditFindBl;
		this.uieditLine2bl = uieditLine2bl;
		this.uieditCopyBl = uieditCopyBl;
		this.uieditPasteBl = uieditPasteBl;
		this.uieditDeleteBl = uieditDeleteBl;
		this.uiviewTilesBl = uiviewTilesBl;
		this.uiviewIconsBl = uiviewIconsBl;
		this.uiviewListBl = uiviewListBl;
		this.uiviewDetailsBl = uiviewDetailsBl;
		this.uiviewLine1bl = uiviewLine1bl;
		this.uiviewCalendarBl = uiviewCalendarBl;
		this.uiviewSeatPlanBl = uiviewSeatPlanBl;
		this.uiviewRoomAvailBl = uiviewRoomAvailBl;
		this.uiviewAuditLogBl = uiviewAuditLogBl;
		this.uiviewRemindersBl = uiviewRemindersBl;
		this.uiviewDesktopBl = uiviewDesktopBl;
		this.uiviewLine2bl = uiviewLine2bl;
		this.uiviewToolbarsBl = uiviewToolbarsBl;
		this.uiviewUisBl = uiviewUisBl;
		this.uiviewRefreshBl = uiviewRefreshBl;
		this.uitoolsLabelsBl = uitoolsLabelsBl;
		this.uitoolsPrintLayoutsBl = uitoolsPrintLayoutsBl;
		this.uitoolsWordTempsBl = uitoolsWordTempsBl;
		this.uitoolsLine1bl = uitoolsLine1bl;
		this.uitoolsQbbl = uitoolsQbbl;
		this.uitoolsLine2bl = uitoolsLine2bl;
		this.uitoolsCalcsBl = uitoolsCalcsBl;
		this.uitoolsRawDataBl = uitoolsRawDataBl;
		this.uitoolsRefreshLooksBl = uitoolsRefreshLooksBl;
		this.uitoolsAutoEmailBl = uitoolsAutoEmailBl;
		this.uitoolsOptionsBl = uitoolsOptionsBl;
		this.uitoolsEvefoldersBl = uitoolsEvefoldersBl;
		this.uipadiaddLinkBl = uipadiaddLinkBl;
		this.uipadiorganizeBl = uipadiorganizeBl;
		this.uihelpManualWordBl = uihelpManualWordBl;
		this.uihelpManualPdfbl = uihelpManualPdfbl;
		this.uihelpLine1bl = uihelpLine1bl;
		this.uihelpSkypeUsbl = uihelpSkypeUsbl;
		this.uihelpSkypeUkbl = uihelpSkypeUkbl;
		this.uihelpWebsiteBl = uihelpWebsiteBl;
		this.uihelpAboutBl = uihelpAboutBl;
		this.uibtnUpAlevelBl = uibtnUpAlevelBl;
		this.uibtnRefreshBl = uibtnRefreshBl;
		this.uibtnHomeBl = uibtnHomeBl;
		this.uibtnCalendarBl = uibtnCalendarBl;
		this.uibtnDesktopBl = uibtnDesktopBl;
		this.uibtnLinksBl = uibtnLinksBl;
		this.uisearchLargeGraphicBl = uisearchLargeGraphicBl;
		this.uitoolbarBtnWidthIn = uitoolbarBtnWidthIn;
		this.uitoolbarBtnHeightIn = uitoolbarBtnHeightIn;
		this.uilistFontSizeFl = uilistFontSizeFl;
		this.uilistViewFontSizeFl = uilistViewFontSizeFl;
		this.uibuttonPicklistBl = uibuttonPicklistBl;
		this.uiarrayBtnHeightIn = uiarrayBtnHeightIn;
		this.uiarrayBtnFontSizeFl = uiarrayBtnFontSizeFl;
		this.uicoolbarBtnHeightIn = uicoolbarBtnHeightIn;
		this.uigridRowHeightIn = uigridRowHeightIn;
		this.uidblClickRequiredBl = uidblClickRequiredBl;
		this.uilvlargeIconsBl = uilvlargeIconsBl;
		this.uiarrayBtnNewWidthIn = uiarrayBtnNewWidthIn;
		this.uiarrayBtnFindWidthIn = uiarrayBtnFindWidthIn;
		this.uicoolbarHeaderHeightIn = uicoolbarHeaderHeightIn;
		this.uishowBreadcrumbsBl = uishowBreadcrumbsBl;
		this.uimoduleButtonWidthIn = uimoduleButtonWidthIn;
		this.uimoduleButtonHeightIn = uimoduleButtonHeightIn;
		this.uimoduleBtnXseparationIn = uimoduleBtnXseparationIn;
		this.uimoduleBtnYseparationIn = uimoduleBtnYseparationIn;
		this.uiarrayBtnXseparationIn = uiarrayBtnXseparationIn;
		this.uiarrayBtnYseparationIn = uiarrayBtnYseparationIn;
		this.uifancyModuleBtnBl = uifancyModuleBtnBl;
		this.uibtnEventPlannerBl = uibtnEventPlannerBl;
	}

	public TUiconfig(int uiconfigId, String uiconfigTx, boolean uiunavailableBl, Date uicreationDate,
			Date uilastUpdatedDate, boolean uitoolbarModulesBl, boolean uitoolbarCoolbarBl, boolean uitoolbarBtnBarBl,
			boolean uitoolbarStatusBarBl, boolean uitoolbarDetailWndBl, boolean uitoolbarBtnArrayBl,
			boolean uirequiredBl, boolean uidefaultBl, boolean uitoolbarHierarchyBl, boolean uitoolbarFloaterBl,
			boolean uifileMenuVisBl, boolean uieditMenuVisBl, boolean uiviewMenuVisBl, boolean uitoolsMenuVisBl,
			boolean uipadimenuVisBl, boolean uihelpMenuVisBl, boolean uifileNewBl, boolean uifileOpenBl,
			boolean uifileRecentRecsBl, boolean uifilePrintBl, boolean uifileLine1bl, boolean uifileImportBl,
			boolean uifileLine2bl, boolean uifileSodtasksBl, boolean uifileEoltasksBl, boolean uifileLine3bl,
			boolean uifileReportsBl, boolean uifileReportGroupsBl, boolean uifileWizardsBl, boolean uifileLine4bl,
			boolean uifileRenewBl, boolean uifileLine5bl, boolean uifileSwitchUserBl, boolean uifileLockSystemBl,
			boolean uifileClockOnBl, boolean uifileClockOffBl, boolean uifileLine6bl, boolean uifileSwitchDbbl,
			boolean uifileReconnectBl, boolean uifileExitBl, boolean uieditSelectAllBl, boolean uieditLine1bl,
			boolean uieditFindBl, boolean uieditLine2bl, boolean uieditCopyBl, boolean uieditPasteBl,
			boolean uieditDeleteBl, boolean uiviewTilesBl, boolean uiviewIconsBl, boolean uiviewListBl,
			boolean uiviewDetailsBl, boolean uiviewLine1bl, boolean uiviewCalendarBl, boolean uiviewSeatPlanBl,
			boolean uiviewRoomAvailBl, boolean uiviewAuditLogBl, boolean uiviewRemindersBl, boolean uiviewDesktopBl,
			boolean uiviewLine2bl, boolean uiviewToolbarsBl, boolean uiviewUisBl, boolean uiviewRefreshBl,
			boolean uitoolsLabelsBl, boolean uitoolsPrintLayoutsBl, boolean uitoolsWordTempsBl, boolean uitoolsLine1bl,
			boolean uitoolsQbbl, boolean uitoolsLine2bl, boolean uitoolsCalcsBl, boolean uitoolsRawDataBl,
			boolean uitoolsRefreshLooksBl, boolean uitoolsAutoEmailBl, boolean uitoolsOptionsBl,
			boolean uitoolsEvefoldersBl, boolean uipadiaddLinkBl, boolean uipadiorganizeBl, boolean uihelpManualWordBl,
			boolean uihelpManualPdfbl, boolean uihelpLine1bl, boolean uihelpSkypeUsbl, boolean uihelpSkypeUkbl,
			boolean uihelpWebsiteBl, boolean uihelpAboutBl, boolean uibtnUpAlevelBl, boolean uibtnRefreshBl,
			boolean uibtnHomeBl, boolean uibtnCalendarBl, boolean uibtnDesktopBl, boolean uibtnLinksBl,
			boolean uisearchLargeGraphicBl, int uitoolbarBtnWidthIn, int uitoolbarBtnHeightIn, float uilistFontSizeFl,
			float uilistViewFontSizeFl, boolean uibuttonPicklistBl, int uiarrayBtnHeightIn, float uiarrayBtnFontSizeFl,
			int uicoolbarBtnHeightIn, int uigridRowHeightIn, boolean uidblClickRequiredBl, boolean uilvlargeIconsBl,
			int uiarrayBtnNewWidthIn, int uiarrayBtnFindWidthIn, int uicoolbarHeaderHeightIn,
			boolean uishowBreadcrumbsBl, int uimoduleButtonWidthIn, int uimoduleButtonHeightIn,
			int uimoduleBtnXseparationIn, int uimoduleBtnYseparationIn, int uiarrayBtnXseparationIn,
			int uiarrayBtnYseparationIn, boolean uifancyModuleBtnBl, boolean uibtnEventPlannerBl, Set<TPcpc> TPcpcs,
			Set<TUnuiconfigNode> TUnuiconfigNodes) {
		this.uiconfigId = uiconfigId;
		this.uiconfigTx = uiconfigTx;
		this.uiunavailableBl = uiunavailableBl;
		this.uicreationDate = uicreationDate;
		this.uilastUpdatedDate = uilastUpdatedDate;
		this.uitoolbarModulesBl = uitoolbarModulesBl;
		this.uitoolbarCoolbarBl = uitoolbarCoolbarBl;
		this.uitoolbarBtnBarBl = uitoolbarBtnBarBl;
		this.uitoolbarStatusBarBl = uitoolbarStatusBarBl;
		this.uitoolbarDetailWndBl = uitoolbarDetailWndBl;
		this.uitoolbarBtnArrayBl = uitoolbarBtnArrayBl;
		this.uirequiredBl = uirequiredBl;
		this.uidefaultBl = uidefaultBl;
		this.uitoolbarHierarchyBl = uitoolbarHierarchyBl;
		this.uitoolbarFloaterBl = uitoolbarFloaterBl;
		this.uifileMenuVisBl = uifileMenuVisBl;
		this.uieditMenuVisBl = uieditMenuVisBl;
		this.uiviewMenuVisBl = uiviewMenuVisBl;
		this.uitoolsMenuVisBl = uitoolsMenuVisBl;
		this.uipadimenuVisBl = uipadimenuVisBl;
		this.uihelpMenuVisBl = uihelpMenuVisBl;
		this.uifileNewBl = uifileNewBl;
		this.uifileOpenBl = uifileOpenBl;
		this.uifileRecentRecsBl = uifileRecentRecsBl;
		this.uifilePrintBl = uifilePrintBl;
		this.uifileLine1bl = uifileLine1bl;
		this.uifileImportBl = uifileImportBl;
		this.uifileLine2bl = uifileLine2bl;
		this.uifileSodtasksBl = uifileSodtasksBl;
		this.uifileEoltasksBl = uifileEoltasksBl;
		this.uifileLine3bl = uifileLine3bl;
		this.uifileReportsBl = uifileReportsBl;
		this.uifileReportGroupsBl = uifileReportGroupsBl;
		this.uifileWizardsBl = uifileWizardsBl;
		this.uifileLine4bl = uifileLine4bl;
		this.uifileRenewBl = uifileRenewBl;
		this.uifileLine5bl = uifileLine5bl;
		this.uifileSwitchUserBl = uifileSwitchUserBl;
		this.uifileLockSystemBl = uifileLockSystemBl;
		this.uifileClockOnBl = uifileClockOnBl;
		this.uifileClockOffBl = uifileClockOffBl;
		this.uifileLine6bl = uifileLine6bl;
		this.uifileSwitchDbbl = uifileSwitchDbbl;
		this.uifileReconnectBl = uifileReconnectBl;
		this.uifileExitBl = uifileExitBl;
		this.uieditSelectAllBl = uieditSelectAllBl;
		this.uieditLine1bl = uieditLine1bl;
		this.uieditFindBl = uieditFindBl;
		this.uieditLine2bl = uieditLine2bl;
		this.uieditCopyBl = uieditCopyBl;
		this.uieditPasteBl = uieditPasteBl;
		this.uieditDeleteBl = uieditDeleteBl;
		this.uiviewTilesBl = uiviewTilesBl;
		this.uiviewIconsBl = uiviewIconsBl;
		this.uiviewListBl = uiviewListBl;
		this.uiviewDetailsBl = uiviewDetailsBl;
		this.uiviewLine1bl = uiviewLine1bl;
		this.uiviewCalendarBl = uiviewCalendarBl;
		this.uiviewSeatPlanBl = uiviewSeatPlanBl;
		this.uiviewRoomAvailBl = uiviewRoomAvailBl;
		this.uiviewAuditLogBl = uiviewAuditLogBl;
		this.uiviewRemindersBl = uiviewRemindersBl;
		this.uiviewDesktopBl = uiviewDesktopBl;
		this.uiviewLine2bl = uiviewLine2bl;
		this.uiviewToolbarsBl = uiviewToolbarsBl;
		this.uiviewUisBl = uiviewUisBl;
		this.uiviewRefreshBl = uiviewRefreshBl;
		this.uitoolsLabelsBl = uitoolsLabelsBl;
		this.uitoolsPrintLayoutsBl = uitoolsPrintLayoutsBl;
		this.uitoolsWordTempsBl = uitoolsWordTempsBl;
		this.uitoolsLine1bl = uitoolsLine1bl;
		this.uitoolsQbbl = uitoolsQbbl;
		this.uitoolsLine2bl = uitoolsLine2bl;
		this.uitoolsCalcsBl = uitoolsCalcsBl;
		this.uitoolsRawDataBl = uitoolsRawDataBl;
		this.uitoolsRefreshLooksBl = uitoolsRefreshLooksBl;
		this.uitoolsAutoEmailBl = uitoolsAutoEmailBl;
		this.uitoolsOptionsBl = uitoolsOptionsBl;
		this.uitoolsEvefoldersBl = uitoolsEvefoldersBl;
		this.uipadiaddLinkBl = uipadiaddLinkBl;
		this.uipadiorganizeBl = uipadiorganizeBl;
		this.uihelpManualWordBl = uihelpManualWordBl;
		this.uihelpManualPdfbl = uihelpManualPdfbl;
		this.uihelpLine1bl = uihelpLine1bl;
		this.uihelpSkypeUsbl = uihelpSkypeUsbl;
		this.uihelpSkypeUkbl = uihelpSkypeUkbl;
		this.uihelpWebsiteBl = uihelpWebsiteBl;
		this.uihelpAboutBl = uihelpAboutBl;
		this.uibtnUpAlevelBl = uibtnUpAlevelBl;
		this.uibtnRefreshBl = uibtnRefreshBl;
		this.uibtnHomeBl = uibtnHomeBl;
		this.uibtnCalendarBl = uibtnCalendarBl;
		this.uibtnDesktopBl = uibtnDesktopBl;
		this.uibtnLinksBl = uibtnLinksBl;
		this.uisearchLargeGraphicBl = uisearchLargeGraphicBl;
		this.uitoolbarBtnWidthIn = uitoolbarBtnWidthIn;
		this.uitoolbarBtnHeightIn = uitoolbarBtnHeightIn;
		this.uilistFontSizeFl = uilistFontSizeFl;
		this.uilistViewFontSizeFl = uilistViewFontSizeFl;
		this.uibuttonPicklistBl = uibuttonPicklistBl;
		this.uiarrayBtnHeightIn = uiarrayBtnHeightIn;
		this.uiarrayBtnFontSizeFl = uiarrayBtnFontSizeFl;
		this.uicoolbarBtnHeightIn = uicoolbarBtnHeightIn;
		this.uigridRowHeightIn = uigridRowHeightIn;
		this.uidblClickRequiredBl = uidblClickRequiredBl;
		this.uilvlargeIconsBl = uilvlargeIconsBl;
		this.uiarrayBtnNewWidthIn = uiarrayBtnNewWidthIn;
		this.uiarrayBtnFindWidthIn = uiarrayBtnFindWidthIn;
		this.uicoolbarHeaderHeightIn = uicoolbarHeaderHeightIn;
		this.uishowBreadcrumbsBl = uishowBreadcrumbsBl;
		this.uimoduleButtonWidthIn = uimoduleButtonWidthIn;
		this.uimoduleButtonHeightIn = uimoduleButtonHeightIn;
		this.uimoduleBtnXseparationIn = uimoduleBtnXseparationIn;
		this.uimoduleBtnYseparationIn = uimoduleBtnYseparationIn;
		this.uiarrayBtnXseparationIn = uiarrayBtnXseparationIn;
		this.uiarrayBtnYseparationIn = uiarrayBtnYseparationIn;
		this.uifancyModuleBtnBl = uifancyModuleBtnBl;
		this.uibtnEventPlannerBl = uibtnEventPlannerBl;
		this.TPcpcs = TPcpcs;
		this.TUnuiconfigNodes = TUnuiconfigNodes;
	}

	@Id

	@Column(name = "UIConfigID", unique = true, nullable = false)
	public int getUiconfigId() {
		return this.uiconfigId;
	}

	public void setUiconfigId(int uiconfigId) {
		this.uiconfigId = uiconfigId;
	}

	@Column(name = "UIConfigTx", unique = true, nullable = false)
	public String getUiconfigTx() {
		return this.uiconfigTx;
	}

	public void setUiconfigTx(String uiconfigTx) {
		this.uiconfigTx = uiconfigTx;
	}

	@Column(name = "UIUnavailableBl", nullable = false)
	public boolean isUiunavailableBl() {
		return this.uiunavailableBl;
	}

	public void setUiunavailableBl(boolean uiunavailableBl) {
		this.uiunavailableBl = uiunavailableBl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UICreationDate", nullable = false, length = 23)
	public Date getUicreationDate() {
		return this.uicreationDate;
	}

	public void setUicreationDate(Date uicreationDate) {
		this.uicreationDate = uicreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UILastUpdatedDate", nullable = false, length = 23)
	public Date getUilastUpdatedDate() {
		return this.uilastUpdatedDate;
	}

	public void setUilastUpdatedDate(Date uilastUpdatedDate) {
		this.uilastUpdatedDate = uilastUpdatedDate;
	}

	@Column(name = "UIToolbarModulesBl", nullable = false)
	public boolean isUitoolbarModulesBl() {
		return this.uitoolbarModulesBl;
	}

	public void setUitoolbarModulesBl(boolean uitoolbarModulesBl) {
		this.uitoolbarModulesBl = uitoolbarModulesBl;
	}

	@Column(name = "UIToolbarCoolbarBl", nullable = false)
	public boolean isUitoolbarCoolbarBl() {
		return this.uitoolbarCoolbarBl;
	}

	public void setUitoolbarCoolbarBl(boolean uitoolbarCoolbarBl) {
		this.uitoolbarCoolbarBl = uitoolbarCoolbarBl;
	}

	@Column(name = "UIToolbarBtnBarBl", nullable = false)
	public boolean isUitoolbarBtnBarBl() {
		return this.uitoolbarBtnBarBl;
	}

	public void setUitoolbarBtnBarBl(boolean uitoolbarBtnBarBl) {
		this.uitoolbarBtnBarBl = uitoolbarBtnBarBl;
	}

	@Column(name = "UIToolbarStatusBarBl", nullable = false)
	public boolean isUitoolbarStatusBarBl() {
		return this.uitoolbarStatusBarBl;
	}

	public void setUitoolbarStatusBarBl(boolean uitoolbarStatusBarBl) {
		this.uitoolbarStatusBarBl = uitoolbarStatusBarBl;
	}

	@Column(name = "UIToolbarDetailWndBl", nullable = false)
	public boolean isUitoolbarDetailWndBl() {
		return this.uitoolbarDetailWndBl;
	}

	public void setUitoolbarDetailWndBl(boolean uitoolbarDetailWndBl) {
		this.uitoolbarDetailWndBl = uitoolbarDetailWndBl;
	}

	@Column(name = "UIToolbarBtnArrayBl", nullable = false)
	public boolean isUitoolbarBtnArrayBl() {
		return this.uitoolbarBtnArrayBl;
	}

	public void setUitoolbarBtnArrayBl(boolean uitoolbarBtnArrayBl) {
		this.uitoolbarBtnArrayBl = uitoolbarBtnArrayBl;
	}

	@Column(name = "UIRequiredBl", nullable = false)
	public boolean isUirequiredBl() {
		return this.uirequiredBl;
	}

	public void setUirequiredBl(boolean uirequiredBl) {
		this.uirequiredBl = uirequiredBl;
	}

	@Column(name = "UIDefaultBl", nullable = false)
	public boolean isUidefaultBl() {
		return this.uidefaultBl;
	}

	public void setUidefaultBl(boolean uidefaultBl) {
		this.uidefaultBl = uidefaultBl;
	}

	@Column(name = "UIToolbarHierarchyBl", nullable = false)
	public boolean isUitoolbarHierarchyBl() {
		return this.uitoolbarHierarchyBl;
	}

	public void setUitoolbarHierarchyBl(boolean uitoolbarHierarchyBl) {
		this.uitoolbarHierarchyBl = uitoolbarHierarchyBl;
	}

	@Column(name = "UIToolbarFloaterBl", nullable = false)
	public boolean isUitoolbarFloaterBl() {
		return this.uitoolbarFloaterBl;
	}

	public void setUitoolbarFloaterBl(boolean uitoolbarFloaterBl) {
		this.uitoolbarFloaterBl = uitoolbarFloaterBl;
	}

	@Column(name = "UIFileMenuVisBl", nullable = false)
	public boolean isUifileMenuVisBl() {
		return this.uifileMenuVisBl;
	}

	public void setUifileMenuVisBl(boolean uifileMenuVisBl) {
		this.uifileMenuVisBl = uifileMenuVisBl;
	}

	@Column(name = "UIEditMenuVisBl", nullable = false)
	public boolean isUieditMenuVisBl() {
		return this.uieditMenuVisBl;
	}

	public void setUieditMenuVisBl(boolean uieditMenuVisBl) {
		this.uieditMenuVisBl = uieditMenuVisBl;
	}

	@Column(name = "UIViewMenuVisBl", nullable = false)
	public boolean isUiviewMenuVisBl() {
		return this.uiviewMenuVisBl;
	}

	public void setUiviewMenuVisBl(boolean uiviewMenuVisBl) {
		this.uiviewMenuVisBl = uiviewMenuVisBl;
	}

	@Column(name = "UIToolsMenuVisBl", nullable = false)
	public boolean isUitoolsMenuVisBl() {
		return this.uitoolsMenuVisBl;
	}

	public void setUitoolsMenuVisBl(boolean uitoolsMenuVisBl) {
		this.uitoolsMenuVisBl = uitoolsMenuVisBl;
	}

	@Column(name = "UIPADIMenuVisBl", nullable = false)
	public boolean isUipadimenuVisBl() {
		return this.uipadimenuVisBl;
	}

	public void setUipadimenuVisBl(boolean uipadimenuVisBl) {
		this.uipadimenuVisBl = uipadimenuVisBl;
	}

	@Column(name = "UIHelpMenuVisBl", nullable = false)
	public boolean isUihelpMenuVisBl() {
		return this.uihelpMenuVisBl;
	}

	public void setUihelpMenuVisBl(boolean uihelpMenuVisBl) {
		this.uihelpMenuVisBl = uihelpMenuVisBl;
	}

	@Column(name = "UIFileNewBl", nullable = false)
	public boolean isUifileNewBl() {
		return this.uifileNewBl;
	}

	public void setUifileNewBl(boolean uifileNewBl) {
		this.uifileNewBl = uifileNewBl;
	}

	@Column(name = "UIFileOpenBl", nullable = false)
	public boolean isUifileOpenBl() {
		return this.uifileOpenBl;
	}

	public void setUifileOpenBl(boolean uifileOpenBl) {
		this.uifileOpenBl = uifileOpenBl;
	}

	@Column(name = "UIFileRecentRecsBl", nullable = false)
	public boolean isUifileRecentRecsBl() {
		return this.uifileRecentRecsBl;
	}

	public void setUifileRecentRecsBl(boolean uifileRecentRecsBl) {
		this.uifileRecentRecsBl = uifileRecentRecsBl;
	}

	@Column(name = "UIFilePrintBl", nullable = false)
	public boolean isUifilePrintBl() {
		return this.uifilePrintBl;
	}

	public void setUifilePrintBl(boolean uifilePrintBl) {
		this.uifilePrintBl = uifilePrintBl;
	}

	@Column(name = "UIFileLine1Bl", nullable = false)
	public boolean isUifileLine1bl() {
		return this.uifileLine1bl;
	}

	public void setUifileLine1bl(boolean uifileLine1bl) {
		this.uifileLine1bl = uifileLine1bl;
	}

	@Column(name = "UIFileImportBl", nullable = false)
	public boolean isUifileImportBl() {
		return this.uifileImportBl;
	}

	public void setUifileImportBl(boolean uifileImportBl) {
		this.uifileImportBl = uifileImportBl;
	}

	@Column(name = "UIFileLine2Bl", nullable = false)
	public boolean isUifileLine2bl() {
		return this.uifileLine2bl;
	}

	public void setUifileLine2bl(boolean uifileLine2bl) {
		this.uifileLine2bl = uifileLine2bl;
	}

	@Column(name = "UIFileSODTasksBl", nullable = false)
	public boolean isUifileSodtasksBl() {
		return this.uifileSodtasksBl;
	}

	public void setUifileSodtasksBl(boolean uifileSodtasksBl) {
		this.uifileSodtasksBl = uifileSodtasksBl;
	}

	@Column(name = "UIFileEOLTasksBl", nullable = false)
	public boolean isUifileEoltasksBl() {
		return this.uifileEoltasksBl;
	}

	public void setUifileEoltasksBl(boolean uifileEoltasksBl) {
		this.uifileEoltasksBl = uifileEoltasksBl;
	}

	@Column(name = "UIFileLine3Bl", nullable = false)
	public boolean isUifileLine3bl() {
		return this.uifileLine3bl;
	}

	public void setUifileLine3bl(boolean uifileLine3bl) {
		this.uifileLine3bl = uifileLine3bl;
	}

	@Column(name = "UIFileReportsBl", nullable = false)
	public boolean isUifileReportsBl() {
		return this.uifileReportsBl;
	}

	public void setUifileReportsBl(boolean uifileReportsBl) {
		this.uifileReportsBl = uifileReportsBl;
	}

	@Column(name = "UIFileReportGroupsBl", nullable = false)
	public boolean isUifileReportGroupsBl() {
		return this.uifileReportGroupsBl;
	}

	public void setUifileReportGroupsBl(boolean uifileReportGroupsBl) {
		this.uifileReportGroupsBl = uifileReportGroupsBl;
	}

	@Column(name = "UIFileWizardsBl", nullable = false)
	public boolean isUifileWizardsBl() {
		return this.uifileWizardsBl;
	}

	public void setUifileWizardsBl(boolean uifileWizardsBl) {
		this.uifileWizardsBl = uifileWizardsBl;
	}

	@Column(name = "UIFileLine4Bl", nullable = false)
	public boolean isUifileLine4bl() {
		return this.uifileLine4bl;
	}

	public void setUifileLine4bl(boolean uifileLine4bl) {
		this.uifileLine4bl = uifileLine4bl;
	}

	@Column(name = "UIFileRenewBl", nullable = false)
	public boolean isUifileRenewBl() {
		return this.uifileRenewBl;
	}

	public void setUifileRenewBl(boolean uifileRenewBl) {
		this.uifileRenewBl = uifileRenewBl;
	}

	@Column(name = "UIFileLine5Bl", nullable = false)
	public boolean isUifileLine5bl() {
		return this.uifileLine5bl;
	}

	public void setUifileLine5bl(boolean uifileLine5bl) {
		this.uifileLine5bl = uifileLine5bl;
	}

	@Column(name = "UIFileSwitchUserBl", nullable = false)
	public boolean isUifileSwitchUserBl() {
		return this.uifileSwitchUserBl;
	}

	public void setUifileSwitchUserBl(boolean uifileSwitchUserBl) {
		this.uifileSwitchUserBl = uifileSwitchUserBl;
	}

	@Column(name = "UIFileLockSystemBl", nullable = false)
	public boolean isUifileLockSystemBl() {
		return this.uifileLockSystemBl;
	}

	public void setUifileLockSystemBl(boolean uifileLockSystemBl) {
		this.uifileLockSystemBl = uifileLockSystemBl;
	}

	@Column(name = "UIFileClockOnBl", nullable = false)
	public boolean isUifileClockOnBl() {
		return this.uifileClockOnBl;
	}

	public void setUifileClockOnBl(boolean uifileClockOnBl) {
		this.uifileClockOnBl = uifileClockOnBl;
	}

	@Column(name = "UIFileClockOffBl", nullable = false)
	public boolean isUifileClockOffBl() {
		return this.uifileClockOffBl;
	}

	public void setUifileClockOffBl(boolean uifileClockOffBl) {
		this.uifileClockOffBl = uifileClockOffBl;
	}

	@Column(name = "UIFileLine6Bl", nullable = false)
	public boolean isUifileLine6bl() {
		return this.uifileLine6bl;
	}

	public void setUifileLine6bl(boolean uifileLine6bl) {
		this.uifileLine6bl = uifileLine6bl;
	}

	@Column(name = "UIFileSwitchDBBl", nullable = false)
	public boolean isUifileSwitchDbbl() {
		return this.uifileSwitchDbbl;
	}

	public void setUifileSwitchDbbl(boolean uifileSwitchDbbl) {
		this.uifileSwitchDbbl = uifileSwitchDbbl;
	}

	@Column(name = "UIFileReconnectBl", nullable = false)
	public boolean isUifileReconnectBl() {
		return this.uifileReconnectBl;
	}

	public void setUifileReconnectBl(boolean uifileReconnectBl) {
		this.uifileReconnectBl = uifileReconnectBl;
	}

	@Column(name = "UIFileExitBl", nullable = false)
	public boolean isUifileExitBl() {
		return this.uifileExitBl;
	}

	public void setUifileExitBl(boolean uifileExitBl) {
		this.uifileExitBl = uifileExitBl;
	}

	@Column(name = "UIEditSelectAllBl", nullable = false)
	public boolean isUieditSelectAllBl() {
		return this.uieditSelectAllBl;
	}

	public void setUieditSelectAllBl(boolean uieditSelectAllBl) {
		this.uieditSelectAllBl = uieditSelectAllBl;
	}

	@Column(name = "UIEditLine1Bl", nullable = false)
	public boolean isUieditLine1bl() {
		return this.uieditLine1bl;
	}

	public void setUieditLine1bl(boolean uieditLine1bl) {
		this.uieditLine1bl = uieditLine1bl;
	}

	@Column(name = "UIEditFindBl", nullable = false)
	public boolean isUieditFindBl() {
		return this.uieditFindBl;
	}

	public void setUieditFindBl(boolean uieditFindBl) {
		this.uieditFindBl = uieditFindBl;
	}

	@Column(name = "UIEditLine2Bl", nullable = false)
	public boolean isUieditLine2bl() {
		return this.uieditLine2bl;
	}

	public void setUieditLine2bl(boolean uieditLine2bl) {
		this.uieditLine2bl = uieditLine2bl;
	}

	@Column(name = "UIEditCopyBl", nullable = false)
	public boolean isUieditCopyBl() {
		return this.uieditCopyBl;
	}

	public void setUieditCopyBl(boolean uieditCopyBl) {
		this.uieditCopyBl = uieditCopyBl;
	}

	@Column(name = "UIEditPasteBl", nullable = false)
	public boolean isUieditPasteBl() {
		return this.uieditPasteBl;
	}

	public void setUieditPasteBl(boolean uieditPasteBl) {
		this.uieditPasteBl = uieditPasteBl;
	}

	@Column(name = "UIEditDeleteBl", nullable = false)
	public boolean isUieditDeleteBl() {
		return this.uieditDeleteBl;
	}

	public void setUieditDeleteBl(boolean uieditDeleteBl) {
		this.uieditDeleteBl = uieditDeleteBl;
	}

	@Column(name = "UIViewTilesBl", nullable = false)
	public boolean isUiviewTilesBl() {
		return this.uiviewTilesBl;
	}

	public void setUiviewTilesBl(boolean uiviewTilesBl) {
		this.uiviewTilesBl = uiviewTilesBl;
	}

	@Column(name = "UIViewIconsBl", nullable = false)
	public boolean isUiviewIconsBl() {
		return this.uiviewIconsBl;
	}

	public void setUiviewIconsBl(boolean uiviewIconsBl) {
		this.uiviewIconsBl = uiviewIconsBl;
	}

	@Column(name = "UIViewListBl", nullable = false)
	public boolean isUiviewListBl() {
		return this.uiviewListBl;
	}

	public void setUiviewListBl(boolean uiviewListBl) {
		this.uiviewListBl = uiviewListBl;
	}

	@Column(name = "UIViewDetailsBl", nullable = false)
	public boolean isUiviewDetailsBl() {
		return this.uiviewDetailsBl;
	}

	public void setUiviewDetailsBl(boolean uiviewDetailsBl) {
		this.uiviewDetailsBl = uiviewDetailsBl;
	}

	@Column(name = "UIViewLine1Bl", nullable = false)
	public boolean isUiviewLine1bl() {
		return this.uiviewLine1bl;
	}

	public void setUiviewLine1bl(boolean uiviewLine1bl) {
		this.uiviewLine1bl = uiviewLine1bl;
	}

	@Column(name = "UIViewCalendarBl", nullable = false)
	public boolean isUiviewCalendarBl() {
		return this.uiviewCalendarBl;
	}

	public void setUiviewCalendarBl(boolean uiviewCalendarBl) {
		this.uiviewCalendarBl = uiviewCalendarBl;
	}

	@Column(name = "UIViewSeatPlanBl", nullable = false)
	public boolean isUiviewSeatPlanBl() {
		return this.uiviewSeatPlanBl;
	}

	public void setUiviewSeatPlanBl(boolean uiviewSeatPlanBl) {
		this.uiviewSeatPlanBl = uiviewSeatPlanBl;
	}

	@Column(name = "UIViewRoomAvailBl", nullable = false)
	public boolean isUiviewRoomAvailBl() {
		return this.uiviewRoomAvailBl;
	}

	public void setUiviewRoomAvailBl(boolean uiviewRoomAvailBl) {
		this.uiviewRoomAvailBl = uiviewRoomAvailBl;
	}

	@Column(name = "UIViewAuditLogBl", nullable = false)
	public boolean isUiviewAuditLogBl() {
		return this.uiviewAuditLogBl;
	}

	public void setUiviewAuditLogBl(boolean uiviewAuditLogBl) {
		this.uiviewAuditLogBl = uiviewAuditLogBl;
	}

	@Column(name = "UIViewRemindersBl", nullable = false)
	public boolean isUiviewRemindersBl() {
		return this.uiviewRemindersBl;
	}

	public void setUiviewRemindersBl(boolean uiviewRemindersBl) {
		this.uiviewRemindersBl = uiviewRemindersBl;
	}

	@Column(name = "UIViewDesktopBl", nullable = false)
	public boolean isUiviewDesktopBl() {
		return this.uiviewDesktopBl;
	}

	public void setUiviewDesktopBl(boolean uiviewDesktopBl) {
		this.uiviewDesktopBl = uiviewDesktopBl;
	}

	@Column(name = "UIViewLine2Bl", nullable = false)
	public boolean isUiviewLine2bl() {
		return this.uiviewLine2bl;
	}

	public void setUiviewLine2bl(boolean uiviewLine2bl) {
		this.uiviewLine2bl = uiviewLine2bl;
	}

	@Column(name = "UIViewToolbarsBl", nullable = false)
	public boolean isUiviewToolbarsBl() {
		return this.uiviewToolbarsBl;
	}

	public void setUiviewToolbarsBl(boolean uiviewToolbarsBl) {
		this.uiviewToolbarsBl = uiviewToolbarsBl;
	}

	@Column(name = "UIViewUIsBl", nullable = false)
	public boolean isUiviewUisBl() {
		return this.uiviewUisBl;
	}

	public void setUiviewUisBl(boolean uiviewUisBl) {
		this.uiviewUisBl = uiviewUisBl;
	}

	@Column(name = "UIViewRefreshBl", nullable = false)
	public boolean isUiviewRefreshBl() {
		return this.uiviewRefreshBl;
	}

	public void setUiviewRefreshBl(boolean uiviewRefreshBl) {
		this.uiviewRefreshBl = uiviewRefreshBl;
	}

	@Column(name = "UIToolsLabelsBl", nullable = false)
	public boolean isUitoolsLabelsBl() {
		return this.uitoolsLabelsBl;
	}

	public void setUitoolsLabelsBl(boolean uitoolsLabelsBl) {
		this.uitoolsLabelsBl = uitoolsLabelsBl;
	}

	@Column(name = "UIToolsPrintLayoutsBl", nullable = false)
	public boolean isUitoolsPrintLayoutsBl() {
		return this.uitoolsPrintLayoutsBl;
	}

	public void setUitoolsPrintLayoutsBl(boolean uitoolsPrintLayoutsBl) {
		this.uitoolsPrintLayoutsBl = uitoolsPrintLayoutsBl;
	}

	@Column(name = "UIToolsWordTempsBl", nullable = false)
	public boolean isUitoolsWordTempsBl() {
		return this.uitoolsWordTempsBl;
	}

	public void setUitoolsWordTempsBl(boolean uitoolsWordTempsBl) {
		this.uitoolsWordTempsBl = uitoolsWordTempsBl;
	}

	@Column(name = "UIToolsLine1Bl", nullable = false)
	public boolean isUitoolsLine1bl() {
		return this.uitoolsLine1bl;
	}

	public void setUitoolsLine1bl(boolean uitoolsLine1bl) {
		this.uitoolsLine1bl = uitoolsLine1bl;
	}

	@Column(name = "UIToolsQBBl", nullable = false)
	public boolean isUitoolsQbbl() {
		return this.uitoolsQbbl;
	}

	public void setUitoolsQbbl(boolean uitoolsQbbl) {
		this.uitoolsQbbl = uitoolsQbbl;
	}

	@Column(name = "UIToolsLine2Bl", nullable = false)
	public boolean isUitoolsLine2bl() {
		return this.uitoolsLine2bl;
	}

	public void setUitoolsLine2bl(boolean uitoolsLine2bl) {
		this.uitoolsLine2bl = uitoolsLine2bl;
	}

	@Column(name = "UIToolsCalcsBl", nullable = false)
	public boolean isUitoolsCalcsBl() {
		return this.uitoolsCalcsBl;
	}

	public void setUitoolsCalcsBl(boolean uitoolsCalcsBl) {
		this.uitoolsCalcsBl = uitoolsCalcsBl;
	}

	@Column(name = "UIToolsRawDataBl", nullable = false)
	public boolean isUitoolsRawDataBl() {
		return this.uitoolsRawDataBl;
	}

	public void setUitoolsRawDataBl(boolean uitoolsRawDataBl) {
		this.uitoolsRawDataBl = uitoolsRawDataBl;
	}

	@Column(name = "UIToolsRefreshLooksBl", nullable = false)
	public boolean isUitoolsRefreshLooksBl() {
		return this.uitoolsRefreshLooksBl;
	}

	public void setUitoolsRefreshLooksBl(boolean uitoolsRefreshLooksBl) {
		this.uitoolsRefreshLooksBl = uitoolsRefreshLooksBl;
	}

	@Column(name = "UIToolsAutoEmailBl", nullable = false)
	public boolean isUitoolsAutoEmailBl() {
		return this.uitoolsAutoEmailBl;
	}

	public void setUitoolsAutoEmailBl(boolean uitoolsAutoEmailBl) {
		this.uitoolsAutoEmailBl = uitoolsAutoEmailBl;
	}

	@Column(name = "UIToolsOptionsBl", nullable = false)
	public boolean isUitoolsOptionsBl() {
		return this.uitoolsOptionsBl;
	}

	public void setUitoolsOptionsBl(boolean uitoolsOptionsBl) {
		this.uitoolsOptionsBl = uitoolsOptionsBl;
	}

	@Column(name = "UIToolsEVEFoldersBl", nullable = false)
	public boolean isUitoolsEvefoldersBl() {
		return this.uitoolsEvefoldersBl;
	}

	public void setUitoolsEvefoldersBl(boolean uitoolsEvefoldersBl) {
		this.uitoolsEvefoldersBl = uitoolsEvefoldersBl;
	}

	@Column(name = "UIPADIAddLinkBl", nullable = false)
	public boolean isUipadiaddLinkBl() {
		return this.uipadiaddLinkBl;
	}

	public void setUipadiaddLinkBl(boolean uipadiaddLinkBl) {
		this.uipadiaddLinkBl = uipadiaddLinkBl;
	}

	@Column(name = "UIPADIOrganizeBl", nullable = false)
	public boolean isUipadiorganizeBl() {
		return this.uipadiorganizeBl;
	}

	public void setUipadiorganizeBl(boolean uipadiorganizeBl) {
		this.uipadiorganizeBl = uipadiorganizeBl;
	}

	@Column(name = "UIHelpManualWordBl", nullable = false)
	public boolean isUihelpManualWordBl() {
		return this.uihelpManualWordBl;
	}

	public void setUihelpManualWordBl(boolean uihelpManualWordBl) {
		this.uihelpManualWordBl = uihelpManualWordBl;
	}

	@Column(name = "UIHelpManualPDFBl", nullable = false)
	public boolean isUihelpManualPdfbl() {
		return this.uihelpManualPdfbl;
	}

	public void setUihelpManualPdfbl(boolean uihelpManualPdfbl) {
		this.uihelpManualPdfbl = uihelpManualPdfbl;
	}

	@Column(name = "UIHelpLine1Bl", nullable = false)
	public boolean isUihelpLine1bl() {
		return this.uihelpLine1bl;
	}

	public void setUihelpLine1bl(boolean uihelpLine1bl) {
		this.uihelpLine1bl = uihelpLine1bl;
	}

	@Column(name = "UIHelpSkypeUSBl", nullable = false)
	public boolean isUihelpSkypeUsbl() {
		return this.uihelpSkypeUsbl;
	}

	public void setUihelpSkypeUsbl(boolean uihelpSkypeUsbl) {
		this.uihelpSkypeUsbl = uihelpSkypeUsbl;
	}

	@Column(name = "UIHelpSkypeUKBl", nullable = false)
	public boolean isUihelpSkypeUkbl() {
		return this.uihelpSkypeUkbl;
	}

	public void setUihelpSkypeUkbl(boolean uihelpSkypeUkbl) {
		this.uihelpSkypeUkbl = uihelpSkypeUkbl;
	}

	@Column(name = "UIHelpWebsiteBl", nullable = false)
	public boolean isUihelpWebsiteBl() {
		return this.uihelpWebsiteBl;
	}

	public void setUihelpWebsiteBl(boolean uihelpWebsiteBl) {
		this.uihelpWebsiteBl = uihelpWebsiteBl;
	}

	@Column(name = "UIHelpAboutBl", nullable = false)
	public boolean isUihelpAboutBl() {
		return this.uihelpAboutBl;
	}

	public void setUihelpAboutBl(boolean uihelpAboutBl) {
		this.uihelpAboutBl = uihelpAboutBl;
	}

	@Column(name = "UIBtnUpALevelBl", nullable = false)
	public boolean isUibtnUpAlevelBl() {
		return this.uibtnUpAlevelBl;
	}

	public void setUibtnUpAlevelBl(boolean uibtnUpAlevelBl) {
		this.uibtnUpAlevelBl = uibtnUpAlevelBl;
	}

	@Column(name = "UIBtnRefreshBl", nullable = false)
	public boolean isUibtnRefreshBl() {
		return this.uibtnRefreshBl;
	}

	public void setUibtnRefreshBl(boolean uibtnRefreshBl) {
		this.uibtnRefreshBl = uibtnRefreshBl;
	}

	@Column(name = "UIBtnHomeBl", nullable = false)
	public boolean isUibtnHomeBl() {
		return this.uibtnHomeBl;
	}

	public void setUibtnHomeBl(boolean uibtnHomeBl) {
		this.uibtnHomeBl = uibtnHomeBl;
	}

	@Column(name = "UIBtnCalendarBl", nullable = false)
	public boolean isUibtnCalendarBl() {
		return this.uibtnCalendarBl;
	}

	public void setUibtnCalendarBl(boolean uibtnCalendarBl) {
		this.uibtnCalendarBl = uibtnCalendarBl;
	}

	@Column(name = "UIBtnDesktopBl", nullable = false)
	public boolean isUibtnDesktopBl() {
		return this.uibtnDesktopBl;
	}

	public void setUibtnDesktopBl(boolean uibtnDesktopBl) {
		this.uibtnDesktopBl = uibtnDesktopBl;
	}

	@Column(name = "UIBtnLinksBl", nullable = false)
	public boolean isUibtnLinksBl() {
		return this.uibtnLinksBl;
	}

	public void setUibtnLinksBl(boolean uibtnLinksBl) {
		this.uibtnLinksBl = uibtnLinksBl;
	}

	@Column(name = "UISearchLargeGraphicBl", nullable = false)
	public boolean isUisearchLargeGraphicBl() {
		return this.uisearchLargeGraphicBl;
	}

	public void setUisearchLargeGraphicBl(boolean uisearchLargeGraphicBl) {
		this.uisearchLargeGraphicBl = uisearchLargeGraphicBl;
	}

	@Column(name = "UIToolbarBtnWidthIn", nullable = false)
	public int getUitoolbarBtnWidthIn() {
		return this.uitoolbarBtnWidthIn;
	}

	public void setUitoolbarBtnWidthIn(int uitoolbarBtnWidthIn) {
		this.uitoolbarBtnWidthIn = uitoolbarBtnWidthIn;
	}

	@Column(name = "UIToolbarBtnHeightIn", nullable = false)
	public int getUitoolbarBtnHeightIn() {
		return this.uitoolbarBtnHeightIn;
	}

	public void setUitoolbarBtnHeightIn(int uitoolbarBtnHeightIn) {
		this.uitoolbarBtnHeightIn = uitoolbarBtnHeightIn;
	}

	@Column(name = "UIListFontSizeFl", nullable = false, precision = 24, scale = 0)
	public float getUilistFontSizeFl() {
		return this.uilistFontSizeFl;
	}

	public void setUilistFontSizeFl(float uilistFontSizeFl) {
		this.uilistFontSizeFl = uilistFontSizeFl;
	}

	@Column(name = "UIListViewFontSizeFl", nullable = false, precision = 24, scale = 0)
	public float getUilistViewFontSizeFl() {
		return this.uilistViewFontSizeFl;
	}

	public void setUilistViewFontSizeFl(float uilistViewFontSizeFl) {
		this.uilistViewFontSizeFl = uilistViewFontSizeFl;
	}

	@Column(name = "UIButtonPicklistBl", nullable = false)
	public boolean isUibuttonPicklistBl() {
		return this.uibuttonPicklistBl;
	}

	public void setUibuttonPicklistBl(boolean uibuttonPicklistBl) {
		this.uibuttonPicklistBl = uibuttonPicklistBl;
	}

	@Column(name = "UIArrayBtnHeightIn", nullable = false)
	public int getUiarrayBtnHeightIn() {
		return this.uiarrayBtnHeightIn;
	}

	public void setUiarrayBtnHeightIn(int uiarrayBtnHeightIn) {
		this.uiarrayBtnHeightIn = uiarrayBtnHeightIn;
	}

	@Column(name = "UIArrayBtnFontSizeFl", nullable = false, precision = 24, scale = 0)
	public float getUiarrayBtnFontSizeFl() {
		return this.uiarrayBtnFontSizeFl;
	}

	public void setUiarrayBtnFontSizeFl(float uiarrayBtnFontSizeFl) {
		this.uiarrayBtnFontSizeFl = uiarrayBtnFontSizeFl;
	}

	@Column(name = "UICoolbarBtnHeightIn", nullable = false)
	public int getUicoolbarBtnHeightIn() {
		return this.uicoolbarBtnHeightIn;
	}

	public void setUicoolbarBtnHeightIn(int uicoolbarBtnHeightIn) {
		this.uicoolbarBtnHeightIn = uicoolbarBtnHeightIn;
	}

	@Column(name = "UIGridRowHeightIn", nullable = false)
	public int getUigridRowHeightIn() {
		return this.uigridRowHeightIn;
	}

	public void setUigridRowHeightIn(int uigridRowHeightIn) {
		this.uigridRowHeightIn = uigridRowHeightIn;
	}

	@Column(name = "UIDblClickRequiredBl", nullable = false)
	public boolean isUidblClickRequiredBl() {
		return this.uidblClickRequiredBl;
	}

	public void setUidblClickRequiredBl(boolean uidblClickRequiredBl) {
		this.uidblClickRequiredBl = uidblClickRequiredBl;
	}

	@Column(name = "UILVLargeIconsBl", nullable = false)
	public boolean isUilvlargeIconsBl() {
		return this.uilvlargeIconsBl;
	}

	public void setUilvlargeIconsBl(boolean uilvlargeIconsBl) {
		this.uilvlargeIconsBl = uilvlargeIconsBl;
	}

	@Column(name = "UIArrayBtnNewWidthIn", nullable = false)
	public int getUiarrayBtnNewWidthIn() {
		return this.uiarrayBtnNewWidthIn;
	}

	public void setUiarrayBtnNewWidthIn(int uiarrayBtnNewWidthIn) {
		this.uiarrayBtnNewWidthIn = uiarrayBtnNewWidthIn;
	}

	@Column(name = "UIArrayBtnFindWidthIn", nullable = false)
	public int getUiarrayBtnFindWidthIn() {
		return this.uiarrayBtnFindWidthIn;
	}

	public void setUiarrayBtnFindWidthIn(int uiarrayBtnFindWidthIn) {
		this.uiarrayBtnFindWidthIn = uiarrayBtnFindWidthIn;
	}

	@Column(name = "UICoolbarHeaderHeightIn", nullable = false)
	public int getUicoolbarHeaderHeightIn() {
		return this.uicoolbarHeaderHeightIn;
	}

	public void setUicoolbarHeaderHeightIn(int uicoolbarHeaderHeightIn) {
		this.uicoolbarHeaderHeightIn = uicoolbarHeaderHeightIn;
	}

	@Column(name = "UIShowBreadcrumbsBl", nullable = false)
	public boolean isUishowBreadcrumbsBl() {
		return this.uishowBreadcrumbsBl;
	}

	public void setUishowBreadcrumbsBl(boolean uishowBreadcrumbsBl) {
		this.uishowBreadcrumbsBl = uishowBreadcrumbsBl;
	}

	@Column(name = "UIModuleButtonWidthIn", nullable = false)
	public int getUimoduleButtonWidthIn() {
		return this.uimoduleButtonWidthIn;
	}

	public void setUimoduleButtonWidthIn(int uimoduleButtonWidthIn) {
		this.uimoduleButtonWidthIn = uimoduleButtonWidthIn;
	}

	@Column(name = "UIModuleButtonHeightIn", nullable = false)
	public int getUimoduleButtonHeightIn() {
		return this.uimoduleButtonHeightIn;
	}

	public void setUimoduleButtonHeightIn(int uimoduleButtonHeightIn) {
		this.uimoduleButtonHeightIn = uimoduleButtonHeightIn;
	}

	@Column(name = "UIModuleBtnXSeparationIn", nullable = false)
	public int getUimoduleBtnXseparationIn() {
		return this.uimoduleBtnXseparationIn;
	}

	public void setUimoduleBtnXseparationIn(int uimoduleBtnXseparationIn) {
		this.uimoduleBtnXseparationIn = uimoduleBtnXseparationIn;
	}

	@Column(name = "UIModuleBtnYSeparationIn", nullable = false)
	public int getUimoduleBtnYseparationIn() {
		return this.uimoduleBtnYseparationIn;
	}

	public void setUimoduleBtnYseparationIn(int uimoduleBtnYseparationIn) {
		this.uimoduleBtnYseparationIn = uimoduleBtnYseparationIn;
	}

	@Column(name = "UIArrayBtnXSeparationIn", nullable = false)
	public int getUiarrayBtnXseparationIn() {
		return this.uiarrayBtnXseparationIn;
	}

	public void setUiarrayBtnXseparationIn(int uiarrayBtnXseparationIn) {
		this.uiarrayBtnXseparationIn = uiarrayBtnXseparationIn;
	}

	@Column(name = "UIArrayBtnYSeparationIn", nullable = false)
	public int getUiarrayBtnYseparationIn() {
		return this.uiarrayBtnYseparationIn;
	}

	public void setUiarrayBtnYseparationIn(int uiarrayBtnYseparationIn) {
		this.uiarrayBtnYseparationIn = uiarrayBtnYseparationIn;
	}

	@Column(name = "UIFancyModuleBtnBl", nullable = false)
	public boolean isUifancyModuleBtnBl() {
		return this.uifancyModuleBtnBl;
	}

	public void setUifancyModuleBtnBl(boolean uifancyModuleBtnBl) {
		this.uifancyModuleBtnBl = uifancyModuleBtnBl;
	}

	@Column(name = "UIBtnEventPlannerBl", nullable = false)
	public boolean isUibtnEventPlannerBl() {
		return this.uibtnEventPlannerBl;
	}

	public void setUibtnEventPlannerBl(boolean uibtnEventPlannerBl) {
		this.uibtnEventPlannerBl = uibtnEventPlannerBl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUiconfig")
	public Set<TPcpc> getTPcpcs() {
		return this.TPcpcs;
	}

	public void setTPcpcs(Set<TPcpc> TPcpcs) {
		this.TPcpcs = TPcpcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUiconfig")
	public Set<TUnuiconfigNode> getTUnuiconfigNodes() {
		return this.TUnuiconfigNodes;
	}

	public void setTUnuiconfigNodes(Set<TUnuiconfigNode> TUnuiconfigNodes) {
		this.TUnuiconfigNodes = TUnuiconfigNodes;
	}

}
