package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TVcvalidCountry generated by hbm2java
 */
@Entity
@Table(name = "T_VCValidCountry")
public class TVcvalidCountry implements java.io.Serializable {

	private int vcvalidCountryId;
	private TCyCountry TCyCountry;
	private TSoStore TSoStore;

	public TVcvalidCountry() {
	}

	public TVcvalidCountry(int vcvalidCountryId, TCyCountry TCyCountry, TSoStore TSoStore) {
		this.vcvalidCountryId = vcvalidCountryId;
		this.TCyCountry = TCyCountry;
		this.TSoStore = TSoStore;
	}

	@Id

	@Column(name = "VCValidCountryID", unique = true, nullable = false)
	public int getVcvalidCountryId() {
		return this.vcvalidCountryId;
	}

	public void setVcvalidCountryId(int vcvalidCountryId) {
		this.vcvalidCountryId = vcvalidCountryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VCCountryID", nullable = false)
	public TCyCountry getTCyCountry() {
		return this.TCyCountry;
	}

	public void setTCyCountry(TCyCountry TCyCountry) {
		this.TCyCountry = TCyCountry;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VCStoreID", nullable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

}
