package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TVoVoucher generated by hbm2java
 */
@Entity
@Table(name = "T_VoVoucher")
public class TVoVoucher implements java.io.Serializable {

	private int voVoucherId;
	private TEmEmp TEmEmpByVoEmpId;
	private TInInvoice TInInvoiceByVoUsedInvoiceIdN;
	private TPcpc TPcpc;
	private TInInvoice TInInvoiceByVoFaultyInvoiceId;
	private TCccostCenter TCccostCenter;
	private TTstransStatus TTstransStatus;
	private TCuCust TCuCust;
	private TEmEmp TEmEmpByVoCommissionEmployeeId;
	private TSoStore TSoStore;
	private Date voCreationDate;
	private Date voExpiryDate;
	private Date voActualExpiryDateN;
	private float voCommissionRateFl;
	private boolean voCommissionableBl;
	private double voAmountMn;
	private short voCurrencyId;
	private float voExchangeRateFl;
	private Date voLastUpdatedDate;
	private String voNotesTxN;
	private Date voVoidDateN;
	private String voVoidReasonTxN;
	private Set<TVivoucherItem> TVivoucherItems = new HashSet<TVivoucherItem>(0);
	private Set<TPyPayment> TPyPayments = new HashSet<TPyPayment>(0);

	public TVoVoucher() {
	}

	public TVoVoucher(int voVoucherId, TEmEmp TEmEmpByVoEmpId, TPcpc TPcpc, TInInvoice TInInvoiceByVoFaultyInvoiceId,
			TCccostCenter TCccostCenter, TTstransStatus TTstransStatus, TCuCust TCuCust,
			TEmEmp TEmEmpByVoCommissionEmployeeId, TSoStore TSoStore, Date voCreationDate, Date voExpiryDate,
			float voCommissionRateFl, boolean voCommissionableBl, double voAmountMn, short voCurrencyId,
			float voExchangeRateFl, Date voLastUpdatedDate) {
		this.voVoucherId = voVoucherId;
		this.TEmEmpByVoEmpId = TEmEmpByVoEmpId;
		this.TPcpc = TPcpc;
		this.TInInvoiceByVoFaultyInvoiceId = TInInvoiceByVoFaultyInvoiceId;
		this.TCccostCenter = TCccostCenter;
		this.TTstransStatus = TTstransStatus;
		this.TCuCust = TCuCust;
		this.TEmEmpByVoCommissionEmployeeId = TEmEmpByVoCommissionEmployeeId;
		this.TSoStore = TSoStore;
		this.voCreationDate = voCreationDate;
		this.voExpiryDate = voExpiryDate;
		this.voCommissionRateFl = voCommissionRateFl;
		this.voCommissionableBl = voCommissionableBl;
		this.voAmountMn = voAmountMn;
		this.voCurrencyId = voCurrencyId;
		this.voExchangeRateFl = voExchangeRateFl;
		this.voLastUpdatedDate = voLastUpdatedDate;
	}

	public TVoVoucher(int voVoucherId, TEmEmp TEmEmpByVoEmpId, TInInvoice TInInvoiceByVoUsedInvoiceIdN, TPcpc TPcpc,
			TInInvoice TInInvoiceByVoFaultyInvoiceId, TCccostCenter TCccostCenter, TTstransStatus TTstransStatus,
			TCuCust TCuCust, TEmEmp TEmEmpByVoCommissionEmployeeId, TSoStore TSoStore, Date voCreationDate,
			Date voExpiryDate, Date voActualExpiryDateN, float voCommissionRateFl, boolean voCommissionableBl,
			double voAmountMn, short voCurrencyId, float voExchangeRateFl, Date voLastUpdatedDate,
			String voNotesTxN, Date voVoidDateN, String voVoidReasonTxN,
			Set<TVivoucherItem> TVivoucherItems, Set<TPyPayment> TPyPayments) {
		this.voVoucherId = voVoucherId;
		this.TEmEmpByVoEmpId = TEmEmpByVoEmpId;
		this.TInInvoiceByVoUsedInvoiceIdN = TInInvoiceByVoUsedInvoiceIdN;
		this.TPcpc = TPcpc;
		this.TInInvoiceByVoFaultyInvoiceId = TInInvoiceByVoFaultyInvoiceId;
		this.TCccostCenter = TCccostCenter;
		this.TTstransStatus = TTstransStatus;
		this.TCuCust = TCuCust;
		this.TEmEmpByVoCommissionEmployeeId = TEmEmpByVoCommissionEmployeeId;
		this.TSoStore = TSoStore;
		this.voCreationDate = voCreationDate;
		this.voExpiryDate = voExpiryDate;
		this.voActualExpiryDateN = voActualExpiryDateN;
		this.voCommissionRateFl = voCommissionRateFl;
		this.voCommissionableBl = voCommissionableBl;
		this.voAmountMn = voAmountMn;
		this.voCurrencyId = voCurrencyId;
		this.voExchangeRateFl = voExchangeRateFl;
		this.voLastUpdatedDate = voLastUpdatedDate;
		this.voNotesTxN = voNotesTxN;
		this.voVoidDateN = voVoidDateN;
		this.voVoidReasonTxN = voVoidReasonTxN;
		this.TVivoucherItems = TVivoucherItems;
		this.TPyPayments = TPyPayments;
	}

	@Id

	@Column(name = "VoVoucherID", unique = true, nullable = false)
	public int getVoVoucherId() {
		return this.voVoucherId;
	}

	public void setVoVoucherId(int voVoucherId) {
		this.voVoucherId = voVoucherId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VoEmpID", nullable = false)
	public TEmEmp getTEmEmpByVoEmpId() {
		return this.TEmEmpByVoEmpId;
	}

	public void setTEmEmpByVoEmpId(TEmEmp TEmEmpByVoEmpId) {
		this.TEmEmpByVoEmpId = TEmEmpByVoEmpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VoUsedInvoiceID_N")
	public TInInvoice getTInInvoiceByVoUsedInvoiceIdN() {
		return this.TInInvoiceByVoUsedInvoiceIdN;
	}

	public void setTInInvoiceByVoUsedInvoiceIdN(TInInvoice TInInvoiceByVoUsedInvoiceIdN) {
		this.TInInvoiceByVoUsedInvoiceIdN = TInInvoiceByVoUsedInvoiceIdN;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VoPCID", nullable = false)
	public TPcpc getTPcpc() {
		return this.TPcpc;
	}

	public void setTPcpc(TPcpc TPcpc) {
		this.TPcpc = TPcpc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VoFaultyInvoiceID", nullable = false)
	public TInInvoice getTInInvoiceByVoFaultyInvoiceId() {
		return this.TInInvoiceByVoFaultyInvoiceId;
	}

	public void setTInInvoiceByVoFaultyInvoiceId(TInInvoice TInInvoiceByVoFaultyInvoiceId) {
		this.TInInvoiceByVoFaultyInvoiceId = TInInvoiceByVoFaultyInvoiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VoCostCenterID", nullable = false)
	public TCccostCenter getTCccostCenter() {
		return this.TCccostCenter;
	}

	public void setTCccostCenter(TCccostCenter TCccostCenter) {
		this.TCccostCenter = TCccostCenter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VoTransStatusID", nullable = false)
	public TTstransStatus getTTstransStatus() {
		return this.TTstransStatus;
	}

	public void setTTstransStatus(TTstransStatus TTstransStatus) {
		this.TTstransStatus = TTstransStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VoCustID", nullable = false)
	public TCuCust getTCuCust() {
		return this.TCuCust;
	}

	public void setTCuCust(TCuCust TCuCust) {
		this.TCuCust = TCuCust;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VoCommissionEmployeeID", nullable = false)
	public TEmEmp getTEmEmpByVoCommissionEmployeeId() {
		return this.TEmEmpByVoCommissionEmployeeId;
	}

	public void setTEmEmpByVoCommissionEmployeeId(TEmEmp TEmEmpByVoCommissionEmployeeId) {
		this.TEmEmpByVoCommissionEmployeeId = TEmEmpByVoCommissionEmployeeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VoStoreID", nullable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VoCreationDate", nullable = false, length = 23)
	public Date getVoCreationDate() {
		return this.voCreationDate;
	}

	public void setVoCreationDate(Date voCreationDate) {
		this.voCreationDate = voCreationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VoExpiryDate", nullable = false, length = 23)
	public Date getVoExpiryDate() {
		return this.voExpiryDate;
	}

	public void setVoExpiryDate(Date voExpiryDate) {
		this.voExpiryDate = voExpiryDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VoActualExpiryDate_N", length = 23)
	public Date getVoActualExpiryDateN() {
		return this.voActualExpiryDateN;
	}

	public void setVoActualExpiryDateN(Date voActualExpiryDateN) {
		this.voActualExpiryDateN = voActualExpiryDateN;
	}

	@Column(name = "VoCommissionRateFl", nullable = false, precision = 24, scale = 0)
	public float getVoCommissionRateFl() {
		return this.voCommissionRateFl;
	}

	public void setVoCommissionRateFl(float voCommissionRateFl) {
		this.voCommissionRateFl = voCommissionRateFl;
	}

	@Column(name = "VoCommissionableBl", nullable = false)
	public boolean isVoCommissionableBl() {
		return this.voCommissionableBl;
	}

	public void setVoCommissionableBl(boolean voCommissionableBl) {
		this.voCommissionableBl = voCommissionableBl;
	}

	@Column(name = "VoAmountMn", nullable = false, precision = 53, scale = 0)
	public double getVoAmountMn() {
		return this.voAmountMn;
	}

	public void setVoAmountMn(double voAmountMn) {
		this.voAmountMn = voAmountMn;
	}

	@Column(name = "VoCurrencyID", nullable = false)
	public short getVoCurrencyId() {
		return this.voCurrencyId;
	}

	public void setVoCurrencyId(short voCurrencyId) {
		this.voCurrencyId = voCurrencyId;
	}

	@Column(name = "VoExchangeRateFl", nullable = false, precision = 24, scale = 0)
	public float getVoExchangeRateFl() {
		return this.voExchangeRateFl;
	}

	public void setVoExchangeRateFl(float voExchangeRateFl) {
		this.voExchangeRateFl = voExchangeRateFl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VoLastUpdatedDate", nullable = false, length = 23)
	public Date getVoLastUpdatedDate() {
		return this.voLastUpdatedDate;
	}

	public void setVoLastUpdatedDate(Date voLastUpdatedDate) {
		this.voLastUpdatedDate = voLastUpdatedDate;
	}

	@Column(name = "VoNotesTx_N")
	public String getVoNotesTxN() {
		return this.voNotesTxN;
	}

	public void setVoNotesTxN(String voNotesTxN) {
		this.voNotesTxN = voNotesTxN;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VoVoidDate_N", length = 23)
	public Date getVoVoidDateN() {
		return this.voVoidDateN;
	}

	public void setVoVoidDateN(Date voVoidDateN) {
		this.voVoidDateN = voVoidDateN;
	}

	@Column(name = "VoVoidReasonTx_N")
	public String getVoVoidReasonTxN() {
		return this.voVoidReasonTxN;
	}

	public void setVoVoidReasonTxN(String voVoidReasonTxN) {
		this.voVoidReasonTxN = voVoidReasonTxN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TVoVoucher")
	public Set<TVivoucherItem> getTVivoucherItems() {
		return this.TVivoucherItems;
	}

	public void setTVivoucherItems(Set<TVivoucherItem> TVivoucherItems) {
		this.TVivoucherItems = TVivoucherItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TVoVoucher")
	public Set<TPyPayment> getTPyPayments() {
		return this.TPyPayments;
	}

	public void setTPyPayments(Set<TPyPayment> TPyPayments) {
		this.TPyPayments = TPyPayments;
	}

}
