package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TXxexport generated by hbm2java
 */
@Entity
@Table(name = "T_XXExport")
public class TXxexport implements java.io.Serializable {

	private int xxexportId;
	private String xxexportTypeTx;
	private Date xxexportDate;

	public TXxexport() {
	}

	public TXxexport(int xxexportId, String xxexportTypeTx, Date xxexportDate) {
		this.xxexportId = xxexportId;
		this.xxexportTypeTx = xxexportTypeTx;
		this.xxexportDate = xxexportDate;
	}

	@Id

	@Column(name = "XXExportID", unique = true, nullable = false)
	public int getXxexportId() {
		return this.xxexportId;
	}

	public void setXxexportId(int xxexportId) {
		this.xxexportId = xxexportId;
	}

	@Column(name = "XXExportTypeTx", nullable = false)
	public String getXxexportTypeTx() {
		return this.xxexportTypeTx;
	}

	public void setXxexportTypeTx(String xxexportTypeTx) {
		this.xxexportTypeTx = xxexportTypeTx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "XXExportDate", nullable = false, length = 23)
	public Date getXxexportDate() {
		return this.xxexportDate;
	}

	public void setXxexportDate(Date xxexportDate) {
		this.xxexportDate = xxexportDate;
	}

}
