package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TXyexportError generated by hbm2java
 */
@Entity
@Table(name = "T_XYExportError")
public class TXyexportError implements java.io.Serializable {

	private TXyexportErrorId id;

	public TXyexportError() {
	}

	public TXyexportError(TXyexportErrorId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "xyexportId", column = @Column(name = "XYExportID", nullable = false)),
			@AttributeOverride(name = "xyexportErrorTx", column = @Column(name = "XYExportErrorTx", nullable = false)),
			@AttributeOverride(name = "xyemailTx", column = @Column(name = "XYEmailTx", nullable = false)) })
	public TXyexportErrorId getId() {
		return this.id;
	}

	public void setId(TXyexportErrorId id) {
		this.id = id;
	}

}
