package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TZ5storeSupplierId generated by hbm2java
 */
@Embeddable
public class TZ5storeSupplierId implements java.io.Serializable {

	private int z5supplierId;
	private short z5storeId;

	public TZ5storeSupplierId() {
	}

	public TZ5storeSupplierId(int z5supplierId, short z5storeId) {
		this.z5supplierId = z5supplierId;
		this.z5storeId = z5storeId;
	}

	@Column(name = "Z5SupplierID", nullable = false)
	public int getZ5supplierId() {
		return this.z5supplierId;
	}

	public void setZ5supplierId(int z5supplierId) {
		this.z5supplierId = z5supplierId;
	}

	@Column(name = "Z5StoreID", nullable = false)
	public short getZ5storeId() {
		return this.z5storeId;
	}

	public void setZ5storeId(short z5storeId) {
		this.z5storeId = z5storeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TZ5storeSupplierId))
			return false;
		TZ5storeSupplierId castOther = (TZ5storeSupplierId) other;

		return (this.getZ5supplierId() == castOther.getZ5supplierId())
				&& (this.getZ5storeId() == castOther.getZ5storeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getZ5supplierId();
		result = 37 * result + this.getZ5storeId();
		return result;
	}

}
