package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TZlStoreStockItem generated by hbm2java
 */
@Entity
@Table(name = "T_ZlStoreStockItem", uniqueConstraints = @UniqueConstraint(columnNames = { "ZlStoreID",
		"ZlStockItemID" }))
public class TZlStoreStockItem implements java.io.Serializable {

	private int zlStoreStockItemId;
	private TSoStore TSoStore;
	private TIcInventoryLocation TIcInventoryLocationByZlStoreLocationIdN;
	private TDbdiscountBand TDbdiscountBand;
	private TIcInventoryLocation TIcInventoryLocationByZlStoreRoomLocationIdN;
	private TSistockItem TSistockItem;
	private int zlNoInStockInX;
	private int zlMinStock1in;
	private int zlMinStock2in;
	private int zlMaxStock1in;
	private int zlMaxStock2in;
	private int zlNoOnOrderInX;
	private boolean zlForUploadBl;
	private double zlAvgCostPriceMn;
	private boolean zlDisplayOnWebBl;
	private Integer zlNoInStockIn;
	private Integer zlNoOnOrderIn;

	public TZlStoreStockItem() {
	}

	public TZlStoreStockItem(int zlStoreStockItemId, TSoStore TSoStore, TSistockItem TSistockItem, int zlNoInStockInX,
			int zlMinStock1in, int zlMinStock2in, int zlMaxStock1in, int zlMaxStock2in, int zlNoOnOrderInX,
			boolean zlForUploadBl, double zlAvgCostPriceMn, boolean zlDisplayOnWebBl) {
		this.zlStoreStockItemId = zlStoreStockItemId;
		this.TSoStore = TSoStore;
		this.TSistockItem = TSistockItem;
		this.zlNoInStockInX = zlNoInStockInX;
		this.zlMinStock1in = zlMinStock1in;
		this.zlMinStock2in = zlMinStock2in;
		this.zlMaxStock1in = zlMaxStock1in;
		this.zlMaxStock2in = zlMaxStock2in;
		this.zlNoOnOrderInX = zlNoOnOrderInX;
		this.zlForUploadBl = zlForUploadBl;
		this.zlAvgCostPriceMn = zlAvgCostPriceMn;
		this.zlDisplayOnWebBl = zlDisplayOnWebBl;
	}

	public TZlStoreStockItem(int zlStoreStockItemId, TSoStore TSoStore,
			TIcInventoryLocation TIcInventoryLocationByZlStoreLocationIdN, TDbdiscountBand TDbdiscountBand,
			TIcInventoryLocation TIcInventoryLocationByZlStoreRoomLocationIdN, TSistockItem TSistockItem,
			int zlNoInStockInX, int zlMinStock1in, int zlMinStock2in, int zlMaxStock1in, int zlMaxStock2in,
			int zlNoOnOrderInX, boolean zlForUploadBl, double zlAvgCostPriceMn, boolean zlDisplayOnWebBl,
			Integer zlNoInStockIn, Integer zlNoOnOrderIn) {
		this.zlStoreStockItemId = zlStoreStockItemId;
		this.TSoStore = TSoStore;
		this.TIcInventoryLocationByZlStoreLocationIdN = TIcInventoryLocationByZlStoreLocationIdN;
		this.TDbdiscountBand = TDbdiscountBand;
		this.TIcInventoryLocationByZlStoreRoomLocationIdN = TIcInventoryLocationByZlStoreRoomLocationIdN;
		this.TSistockItem = TSistockItem;
		this.zlNoInStockInX = zlNoInStockInX;
		this.zlMinStock1in = zlMinStock1in;
		this.zlMinStock2in = zlMinStock2in;
		this.zlMaxStock1in = zlMaxStock1in;
		this.zlMaxStock2in = zlMaxStock2in;
		this.zlNoOnOrderInX = zlNoOnOrderInX;
		this.zlForUploadBl = zlForUploadBl;
		this.zlAvgCostPriceMn = zlAvgCostPriceMn;
		this.zlDisplayOnWebBl = zlDisplayOnWebBl;
		this.zlNoInStockIn = zlNoInStockIn;
		this.zlNoOnOrderIn = zlNoOnOrderIn;
	}

	@Id

	@Column(name = "ZlStoreStockItemID", unique = true, nullable = false)
	public int getZlStoreStockItemId() {
		return this.zlStoreStockItemId;
	}

	public void setZlStoreStockItemId(int zlStoreStockItemId) {
		this.zlStoreStockItemId = zlStoreStockItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ZlStoreID", nullable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ZlStoreLocationID_N")
	public TIcInventoryLocation getTIcInventoryLocationByZlStoreLocationIdN() {
		return this.TIcInventoryLocationByZlStoreLocationIdN;
	}

	public void setTIcInventoryLocationByZlStoreLocationIdN(
			TIcInventoryLocation TIcInventoryLocationByZlStoreLocationIdN) {
		this.TIcInventoryLocationByZlStoreLocationIdN = TIcInventoryLocationByZlStoreLocationIdN;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ZlSaleDiscountBandID_N")
	public TDbdiscountBand getTDbdiscountBand() {
		return this.TDbdiscountBand;
	}

	public void setTDbdiscountBand(TDbdiscountBand TDbdiscountBand) {
		this.TDbdiscountBand = TDbdiscountBand;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ZlStoreRoomLocationID_N")
	public TIcInventoryLocation getTIcInventoryLocationByZlStoreRoomLocationIdN() {
		return this.TIcInventoryLocationByZlStoreRoomLocationIdN;
	}

	public void setTIcInventoryLocationByZlStoreRoomLocationIdN(
			TIcInventoryLocation TIcInventoryLocationByZlStoreRoomLocationIdN) {
		this.TIcInventoryLocationByZlStoreRoomLocationIdN = TIcInventoryLocationByZlStoreRoomLocationIdN;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ZlStockItemID", nullable = false)
	public TSistockItem getTSistockItem() {
		return this.TSistockItem;
	}

	public void setTSistockItem(TSistockItem TSistockItem) {
		this.TSistockItem = TSistockItem;
	}

	@Column(name = "ZlNoInStockInX", nullable = false)
	public int getZlNoInStockInX() {
		return this.zlNoInStockInX;
	}

	public void setZlNoInStockInX(int zlNoInStockInX) {
		this.zlNoInStockInX = zlNoInStockInX;
	}

	@Column(name = "ZlMinStock1In", nullable = false)
	public int getZlMinStock1in() {
		return this.zlMinStock1in;
	}

	public void setZlMinStock1in(int zlMinStock1in) {
		this.zlMinStock1in = zlMinStock1in;
	}

	@Column(name = "ZlMinStock2In", nullable = false)
	public int getZlMinStock2in() {
		return this.zlMinStock2in;
	}

	public void setZlMinStock2in(int zlMinStock2in) {
		this.zlMinStock2in = zlMinStock2in;
	}

	@Column(name = "ZlMaxStock1In", nullable = false)
	public int getZlMaxStock1in() {
		return this.zlMaxStock1in;
	}

	public void setZlMaxStock1in(int zlMaxStock1in) {
		this.zlMaxStock1in = zlMaxStock1in;
	}

	@Column(name = "ZlMaxStock2In", nullable = false)
	public int getZlMaxStock2in() {
		return this.zlMaxStock2in;
	}

	public void setZlMaxStock2in(int zlMaxStock2in) {
		this.zlMaxStock2in = zlMaxStock2in;
	}

	@Column(name = "ZlNoOnOrderInX", nullable = false)
	public int getZlNoOnOrderInX() {
		return this.zlNoOnOrderInX;
	}

	public void setZlNoOnOrderInX(int zlNoOnOrderInX) {
		this.zlNoOnOrderInX = zlNoOnOrderInX;
	}

	@Column(name = "ZlForUploadBl", nullable = false)
	public boolean isZlForUploadBl() {
		return this.zlForUploadBl;
	}

	public void setZlForUploadBl(boolean zlForUploadBl) {
		this.zlForUploadBl = zlForUploadBl;
	}

	@Column(name = "ZlAvgCostPriceMn", nullable = false, precision = 53, scale = 0)
	public double getZlAvgCostPriceMn() {
		return this.zlAvgCostPriceMn;
	}

	public void setZlAvgCostPriceMn(double zlAvgCostPriceMn) {
		this.zlAvgCostPriceMn = zlAvgCostPriceMn;
	}

	@Column(name = "ZlDisplayOnWebBl", nullable = false)
	public boolean isZlDisplayOnWebBl() {
		return this.zlDisplayOnWebBl;
	}

	public void setZlDisplayOnWebBl(boolean zlDisplayOnWebBl) {
		this.zlDisplayOnWebBl = zlDisplayOnWebBl;
	}

	@Column(name = "ZlNoInStockIn")
	public Integer getZlNoInStockIn() {
		return this.zlNoInStockIn;
	}

	public void setZlNoInStockIn(Integer zlNoInStockIn) {
		this.zlNoInStockIn = zlNoInStockIn;
	}

	@Column(name = "ZlNoOnOrderIn")
	public Integer getZlNoOnOrderIn() {
		return this.zlNoOnOrderIn;
	}

	public void setZlNoOnOrderIn(Integer zlNoOnOrderIn) {
		this.zlNoOnOrderIn = zlNoOnOrderIn;
	}

}
