package org.holtz.eve.jpa.entity;
// Generated Aug 4, 2017 9:16:24 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TZoStoreDataType generated by hbm2java
 */
@Entity
@Table(name = "T_ZoStoreDataType")
public class TZoStoreDataType implements java.io.Serializable {

	private TZoStoreDataTypeId id;
	private TSoStore TSoStore;
	private TDtdataType TDtdataType;
	private int zoNextId;
	private int zoMinId;
	private int zoMaxId;
	private String zoExportColsTxN;
	private String zoMcexportColsTxN;

	public TZoStoreDataType() {
	}

	public TZoStoreDataType(TZoStoreDataTypeId id, TSoStore TSoStore, TDtdataType TDtdataType, int zoNextId,
			int zoMinId, int zoMaxId) {
		this.id = id;
		this.TSoStore = TSoStore;
		this.TDtdataType = TDtdataType;
		this.zoNextId = zoNextId;
		this.zoMinId = zoMinId;
		this.zoMaxId = zoMaxId;
	}

	public TZoStoreDataType(TZoStoreDataTypeId id, TSoStore TSoStore, TDtdataType TDtdataType, int zoNextId,
			int zoMinId, int zoMaxId, String zoExportColsTxN, String zoMcexportColsTxN) {
		this.id = id;
		this.TSoStore = TSoStore;
		this.TDtdataType = TDtdataType;
		this.zoNextId = zoNextId;
		this.zoMinId = zoMinId;
		this.zoMaxId = zoMaxId;
		this.zoExportColsTxN = zoExportColsTxN;
		this.zoMcexportColsTxN = zoMcexportColsTxN;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "zoDataTypeId", column = @Column(name = "ZoDataTypeID", nullable = false)),
			@AttributeOverride(name = "zoStoreId", column = @Column(name = "ZoStoreID", nullable = false)) })
	public TZoStoreDataTypeId getId() {
		return this.id;
	}

	public void setId(TZoStoreDataTypeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ZoStoreID", nullable = false, insertable = false, updatable = false)
	public TSoStore getTSoStore() {
		return this.TSoStore;
	}

	public void setTSoStore(TSoStore TSoStore) {
		this.TSoStore = TSoStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ZoDataTypeID", nullable = false, insertable = false, updatable = false)
	public TDtdataType getTDtdataType() {
		return this.TDtdataType;
	}

	public void setTDtdataType(TDtdataType TDtdataType) {
		this.TDtdataType = TDtdataType;
	}

	@Column(name = "ZoNextID", nullable = false)
	public int getZoNextId() {
		return this.zoNextId;
	}

	public void setZoNextId(int zoNextId) {
		this.zoNextId = zoNextId;
	}

	@Column(name = "ZoMinID", nullable = false)
	public int getZoMinId() {
		return this.zoMinId;
	}

	public void setZoMinId(int zoMinId) {
		this.zoMinId = zoMinId;
	}

	@Column(name = "ZoMaxID", nullable = false)
	public int getZoMaxId() {
		return this.zoMaxId;
	}

	public void setZoMaxId(int zoMaxId) {
		this.zoMaxId = zoMaxId;
	}

	@Column(name = "ZoExportColsTx_N")
	public String getZoExportColsTxN() {
		return this.zoExportColsTxN;
	}

	public void setZoExportColsTxN(String zoExportColsTxN) {
		this.zoExportColsTxN = zoExportColsTxN;
	}

	@Column(name = "ZoMCExportColsTx_N")
	public String getZoMcexportColsTxN() {
		return this.zoMcexportColsTxN;
	}

	public void setZoMcexportColsTxN(String zoMcexportColsTxN) {
		this.zoMcexportColsTxN = zoMcexportColsTxN;
	}

}
